import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ===== TOURISME / HÔTELLERIE (25 templates) =====
  {
    code: 'tour_hebergement_hotelier',
    name: "Contrat d\"Hébergement Hôtelier",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Contrat encadrant la prestation d\"hébergement entre un hôtel et un client individuel ou entreprise, conforme aux usages OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_hotel', label: "Nom de l\"hôtel", type: 'text', required: true },
      { key: 'nom_client', label: "Nom complet du client", type: 'text', required: true },
      { key: 'date_arrivee', label: "Date d\"arrivée", type: 'date', required: true },
      { key: 'date_depart', label: "Date de départ", type: 'date', required: true },
      { key: 'type_chambre', label: "Type de chambre", type: 'text', required: true },
      { key: 'prix_nuit', label: "Prix par nuit (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"HÉBERGEMENT HÔTELIER</h1><p>Entre l"hôtel <strong>{{nom_hotel}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le présent contrat a pour objet la mise à disposition d"une chambre de type <strong>{{type_chambre}}</strong> du <strong>{{date_arrivee}}</strong> au <strong>{{date_depart}}</strong>.</p><h2>Article 2 – Prix</h2><p>Le prix convenu est de <strong>{{prix_nuit}}</strong> FCFA par nuit, toutes taxes comprises.</p><h2>Article 3 – Obligations de l"hôtel</h2><p>L"hôtel s"engage à fournir une chambre propre, sécurisée et conforme aux normes d"hygiène en vigueur en Côte d"Ivoire.</p><h2>Article 4 – Obligations du client</h2><p>Le client s"engage à respecter le règlement intérieur de l"établissement et à régler l"intégralité des sommes dues.</p><h2>Article 5 – Droit applicable</h2><p>Le présent contrat est soumis au droit ivoirien et aux dispositions de l"Acte Uniforme OHADA.</p></div>`,
  },
  {
    code: 'tour_reservation_groupe',
    name: "Contrat de Réservation Groupe",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de réservation hôtelière pour groupes, séminaires ou événements d\"entreprise.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_hotel', label: "Nom de l\"hôtel", type: 'text', required: true },
      { key: 'nom_groupe', label: "Nom du groupe / entreprise", type: 'text', required: true },
      { key: 'nombre_chambres', label: "Nombre de chambres réservées", type: 'text', required: true },
      { key: 'date_sejour', label: "Date de début du séjour", type: 'date', required: true },
      { key: 'duree_sejour', label: "Durée du séjour (nuits)", type: 'text', required: true },
      { key: 'tarif_groupe', label: "Tarif groupe négocié (FCFA/nuit/chambre)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE RÉSERVATION GROUPE</h1><p>Entre l"hôtel <strong>{{nom_hotel}}</strong> et le groupe <strong>{{nom_groupe}}</strong>.</p><h2>Article 1 – Réservation</h2><p>L"hôtel confirme la réservation de <strong>{{nombre_chambres}}</strong> chambres à compter du <strong>{{date_sejour}}</strong> pour une durée de <strong>{{duree_sejour}}</strong> nuits.</p><h2>Article 2 – Tarification</h2><p>Un tarif préférentiel de <strong>{{tarif_groupe}}</strong> FCFA par chambre et par nuit est accordé au groupe.</p><h2>Article 3 – Acompte</h2><p>Un acompte de 30 % du montant total est exigible à la signature du présent contrat.</p><h2>Article 4 – Annulation</h2><p>Toute annulation intervenant moins de 15 jours avant la date de début entraîne la perte de l"acompte versé.</p></div>`,
  },
  {
    code: 'tour_agence_voyages',
    name: "Contrat d\"Agence de Voyages",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 14000,
    description: "Contrat liant une agence de voyages à son client pour l\"organisation d\"un voyage ou séjour touristique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_agence', label: "Nom de l\"agence de voyages", type: 'text', required: true },
      { key: 'nom_client', label: "Nom complet du voyageur", type: 'text', required: true },
      { key: 'destination', label: "Destination du voyage", type: 'text', required: true },
      { key: 'date_depart', label: "Date de départ", type: 'date', required: true },
      { key: 'prix_forfait', label: "Prix du forfait (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"AGENCE DE VOYAGES</h1><p>Entre l"agence <strong>{{nom_agence}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Objet</h2><p>L"agence s"engage à organiser un voyage à destination de <strong>{{destination}}</strong> avec départ le <strong>{{date_depart}}</strong>.</p><h2>Article 2 – Prix du forfait</h2><p>Le prix du forfait est fixé à <strong>{{prix_forfait}}</strong> FCFA, incluant transport, hébergement et assurance de base.</p><h2>Article 3 – Prestations incluses</h2><p>Les prestations incluses dans le forfait sont détaillées en annexe jointe au présent contrat.</p><h2>Article 4 – Assurance</h2><p>Le client est invité à souscrire une assurance annulation et rapatriement auprès de l"agence ou d"un assureur de son choix.</p><h2>Article 5 – Droit applicable</h2><p>Le présent contrat est régi par le droit ivoirien et les conventions internationales applicables au transport touristique.</p></div>`,
  },
  {
    code: 'tour_bon_commande_excursion',
    name: "Bon de Commande Excursion",
    category: 'commercial_financier',
    price: 2000,
    priceMax: 6000,
    description: "Document commercial pour la réservation et la confirmation d\"une excursion touristique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'operateur', label: "Opérateur / prestataire excursion", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'type_excursion', label: "Type d\"excursion", type: 'text', required: true },
      { key: 'date_excursion', label: "Date de l\"excursion", type: 'date', required: true },
      { key: 'nombre_personnes', label: "Nombre de participants", type: 'text', required: true },
      { key: 'prix_unitaire', label: "Prix par personne (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>BON DE COMMANDE – EXCURSION TOURISTIQUE</h1><p>Prestataire : <strong>{{operateur}}</strong> | Client : <strong>{{nom_client}}</strong></p><h2>Détails de l"excursion</h2><table border="1" cellpadding="6" width="100%"><tr><th>Excursion</th><th>Date</th><th>Participants</th><th>Prix unitaire</th></tr><tr><td>{{type_excursion}}</td><td>{{date_excursion}}</td><td>{{nombre_personnes}}</td><td>{{prix_unitaire}} FCFA</td></tr></table><h2>Conditions</h2><p>La réservation est confirmée à réception du règlement intégral. Toute annulation 48h avant la date entraîne des frais de 50 % du montant total.</p></div>`,
  },
  {
    code: 'tour_guide_touristique',
    name: "Contrat de Guide Touristique",
    category: 'commercial_financier',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de prestation de services liant un guide touristique agréé à une agence ou un client.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_guide', label: "Nom du guide touristique", type: 'text', required: true },
      { key: 'numero_agrement', label: "Numéro d\"agrément", type: 'text', required: true },
      { key: 'nom_employeur', label: "Agence ou client employeur", type: 'text', required: true },
      { key: 'circuit', label: "Circuit / destination couverte", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de mission", type: 'date', required: true },
      { key: 'remuneration', label: "Rémunération journalière (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GUIDE TOURISTIQUE</h1><p>Entre <strong>{{nom_employeur}}</strong> et le guide <strong>{{nom_guide}}</strong> (Agrément n° <strong>{{numero_agrement}}</strong>).</p><h2>Article 1 – Mission</h2><p>Le guide est chargé d"assurer l"accompagnement et l"animation du circuit <strong>{{circuit}}</strong> à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Rémunération</h2><p>La rémunération est fixée à <strong>{{remuneration}}</strong> FCFA par jour de prestation, payable en fin de mission.</p><h2>Article 3 – Obligations</h2><p>Le guide s"engage à maintenir son agrément en vigueur, à respecter les règles de sécurité et à communiquer en français et dans toute langue maîtrisée.</p><h2>Article 4 – Confidentialité</h2><p>Le guide s"engage à ne pas divulguer les informations commerciales ou tarifaires de l"employeur.</p></div>`,
  },
  {
    code: 'tour_partenariat_hotel_to',
    name: "Accord de Partenariat Hôtel – Tour Opérateur",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord-cadre de partenariat commercial entre un établissement hôtelier et un tour opérateur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_hotel', label: "Nom de l\"hôtel", type: 'text', required: true },
      { key: 'nom_tour_operateur', label: "Nom du tour opérateur", type: 'text', required: true },
      { key: 'taux_commission', label: "Taux de commission accordé (%)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du partenariat", type: 'date', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT HÔTEL – TOUR OPÉRATEUR</h1><p>Entre l"hôtel <strong>{{nom_hotel}}</strong> et le tour opérateur <strong>{{nom_tour_operateur}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le présent accord établit les termes de la collaboration commerciale entre les parties pour la commercialisation des capacités hôtelières.</p><h2>Article 2 – Commission</h2><p>L"hôtel accorde au tour opérateur une commission de <strong>{{taux_commission}}</strong> % sur le prix public affiché pour chaque réservation confirmée.</p><h2>Article 3 – Durée</h2><p>Le présent accord prend effet le <strong>{{date_debut}}</strong> pour une durée de <strong>{{duree_contrat}}</strong> mois, renouvelable par tacite reconduction.</p><h2>Article 4 – Exclusivité</h2><p>Le présent accord ne confère aucune exclusivité territoriale, sauf disposition contraire annexée.</p></div>`,
  },
  {
    code: 'tour_traiteur_evenementiel',
    name: "Contrat de Service Traiteur Événementiel",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Contrat de prestation de service traiteur pour événements touristiques, congrès et réceptions.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'nom_traiteur', label: "Nom du prestataire traiteur", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client / organisateur", type: 'text', required: true },
      { key: 'type_evenement', label: "Type d\"événement", type: 'text', required: true },
      { key: 'date_evenement', label: "Date de l\"événement", type: 'date', required: true },
      { key: 'nombre_couverts', label: "Nombre de couverts prévus", type: 'text', required: true },
      { key: 'montant_prestation', label: "Montant de la prestation (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE TRAITEUR ÉVÉNEMENTIEL</h1><p>Entre le traiteur <strong>{{nom_traiteur}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le traiteur s"engage à assurer la restauration lors de l"événement de type <strong>{{type_evenement}}</strong> prévu le <strong>{{date_evenement}}</strong> pour <strong>{{nombre_couverts}}</strong> couverts.</p><h2>Article 2 – Montant</h2><p>Le montant total de la prestation est fixé à <strong>{{montant_prestation}}</strong> FCFA, réglable en deux tranches égales (50 % à la signature, 50 % le jour de l"événement).</p><h2>Article 3 – Menu</h2><p>Le menu détaillé est annexé au présent contrat et constitue une partie intégrante de celui-ci.</p><h2>Article 4 – Responsabilité</h2><p>Le traiteur est responsable de la qualité et de la conformité sanitaire des prestations fournies.</p></div>`,
  },
  {
    code: 'tour_location_salle_conference',
    name: "Accord de Location de Salle de Conférence",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Accord de mise à disposition de salle de conférence ou séminaire dans un établissement hôtelier.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_hotel', label: "Nom de l\"établissement", type: 'text', required: true },
      { key: 'nom_locataire', label: "Nom du locataire / organisateur", type: 'text', required: true },
      { key: 'nom_salle', label: "Nom ou référence de la salle", type: 'text', required: true },
      { key: 'date_occupation', label: "Date d\"occupation", type: 'date', required: true },
      { key: 'tarif_salle', label: "Tarif de location (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE LOCATION DE SALLE DE CONFÉRENCE</h1><p>Entre <strong>{{nom_hotel}}</strong> et <strong>{{nom_locataire}}</strong>.</p><h2>Article 1 – Mise à disposition</h2><p>L"établissement met à disposition la salle <strong>{{nom_salle}}</strong> le <strong>{{date_occupation}}</strong> pour usage de conférence ou séminaire.</p><h2>Article 2 – Tarif</h2><p>Le tarif de location est de <strong>{{tarif_salle}}</strong> FCFA pour la journée, matériel audiovisuel inclus.</p><h2>Article 3 – Équipements</h2><p>La salle est équipée : vidéoprojecteur, écran, tableau blanc, sono, connexion Wi-Fi haut débit, eau et café.</p><h2>Article 4 – Caution</h2><p>Une caution remboursable de 20 % du tarif est exigée pour couvrir tout dommage éventuel.</p></div>`,
  },
  {
    code: 'tour_service_evenementiel',
    name: "Contrat de Service d\"Événementiel",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat global de prestation événementielle couvrant organisation, logistique et animation.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'agence_evenementielle', label: "Nom de l\"agence événementielle", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'nature_evenement', label: "Nature de l\"événement", type: 'text', required: true },
      { key: 'date_evenement', label: "Date de l\"événement", type: 'date', required: true },
      { key: 'budget_global', label: "Budget global alloué (FCFA)", type: 'text', required: true },
      { key: 'lieu', label: "Lieu de l\"événement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"ÉVÉNEMENTIEL</h1><p>Entre l"agence <strong>{{agence_evenementielle}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Objet</h2><p>L"agence prend en charge l"organisation complète de l"événement <strong>{{nature_evenement}}</strong> prévu le <strong>{{date_evenement}}</strong> à <strong>{{lieu}}</strong>.</p><h2>Article 2 – Budget</h2><p>Le budget global convenu est de <strong>{{budget_global}}</strong> FCFA, incluant décoration, logistique, animation et coordination.</p><h2>Article 3 – Prestations</h2><p>Le détail des prestations est consigné dans le cahier des charges annexé au présent contrat.</p><h2>Article 4 – Responsabilité</h2><p>L"agence souscrit une assurance responsabilité civile couvrant l"ensemble de l"événement.</p></div>`,
  },
  {
    code: 'tour_concierge_entreprise',
    name: "Contrat de Concierge d\"Entreprise",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Contrat de service de conciergerie dédié aux entreprises clientes d\"un établissement hôtelier.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_hotel', label: "Nom de l\"hôtel", type: 'text', required: true },
      { key: 'nom_entreprise', label: "Nom de l\"entreprise cliente", type: 'text', required: true },
      { key: 'services_inclus', label: "Services de conciergerie inclus", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
      { key: 'abonnement_mensuel', label: "Abonnement mensuel (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE CONCIERGE D"ENTREPRISE</h1><p>Entre l"hôtel <strong>{{nom_hotel}}</strong> et l"entreprise <strong>{{nom_entreprise}}</strong>.</p><h2>Article 1 – Services</h2><p>L"hôtel met à disposition un service de conciergerie dédié comprenant : <strong>{{services_inclus}}</strong>.</p><h2>Article 2 – Abonnement</h2><p>Le présent contrat prend effet le <strong>{{date_debut}}</strong> moyennant un abonnement mensuel de <strong>{{abonnement_mensuel}}</strong> FCFA.</p><h2>Article 3 – Disponibilité</h2><p>Le service de conciergerie est disponible 7j/7 de 07h00 à 22h00 pour les collaborateurs de l"entreprise cliente.</p><h2>Article 4 – Confidentialité</h2><p>L"hôtel s"engage à traiter avec discrétion toutes les demandes formulées par les utilisateurs du service.</p></div>`,
  },
  {
    code: 'tour_transfert_aeroport',
    name: "Contrat de Service de Transfert Aéroport",
    category: 'commercial_financier',
    price: 2500,
    priceMax: 7000,
    description: "Contrat de prestation de transfert entre l\"aéroport et les hôtels ou sites touristiques.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'prestataire_transport', label: "Prestataire de transport", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client / passager", type: 'text', required: true },
      { key: 'aeroport', label: "Aéroport de prise en charge", type: 'text', required: true },
      { key: 'destination', label: "Destination finale", type: 'text', required: true },
      { key: 'date_transfert', label: "Date du transfert", type: 'date', required: true },
      { key: 'tarif_transfert', label: "Tarif du transfert (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE TRANSFERT AÉROPORT</h1><p>Entre le prestataire <strong>{{prestataire_transport}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Prestation</h2><p>Le prestataire assure le transfert du client depuis l"aéroport <strong>{{aeroport}}</strong> vers <strong>{{destination}}</strong> le <strong>{{date_transfert}}</strong>.</p><h2>Article 2 – Tarif</h2><p>Le tarif convenu est de <strong>{{tarif_transfert}}</strong> FCFA, comprenant le chauffeur, le véhicule climatisé et la prise en charge des bagages.</p><h2>Article 3 – Ponctualité</h2><p>Le chauffeur s"engage à être présent 30 minutes avant l"heure de prise en charge convenue.</p><h2>Article 4 – Assurance</h2><p>Le véhicule est couvert par une assurance tous risques passagers en cours de validité.</p></div>`,
  },
  {
    code: 'tour_camp_touristique',
    name: "Accord de Camp Touristique (Lodge/Safari)",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de gestion et de prestation pour camps touristiques, lodges et séjours safari en Afrique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_lodge', label: "Nom du lodge / camp", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client / groupe", type: 'text', required: true },
      { key: 'parc_reserve', label: "Parc ou réserve naturelle", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du séjour", type: 'date', required: true },
      { key: 'duree_nuits', label: "Nombre de nuits", type: 'text', required: true },
      { key: 'tarif_pension', label: "Tarif pension complète (FCFA/nuit/pers.)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CAMP TOURISTIQUE – LODGE / SAFARI</h1><p>Entre le camp <strong>{{nom_lodge}}</strong> situé dans la zone de <strong>{{parc_reserve}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Séjour</h2><p>Le camp accueille le client du <strong>{{date_debut}}</strong> pour <strong>{{duree_nuits}}</strong> nuits en formule pension complète.</p><h2>Article 2 – Tarif</h2><p>Le tarif est de <strong>{{tarif_pension}}</strong> FCFA par nuit et par personne, incluant sorties safari, repas et hébergement en tente/chalet.</p><h2>Article 3 – Conservation</h2><p>Le client s"engage à respecter les règles de conservation de la faune et de la flore, sous peine d"exclusion sans remboursement.</p><h2>Article 4 – Sécurité</h2><p>Le camp fournit des guides certifiés et des équipements de sécurité adaptés au milieu naturel.</p></div>`,
  },
  {
    code: 'tour_croisiere_fluviale',
    name: "Contrat de Service de Croisière Fluviale",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 14000,
    description: "Contrat de prestation de croisière touristique sur les fleuves et lagunes d\"Afrique de l\"Ouest.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'operateur_croisiere', label: "Opérateur de croisière", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client / groupe", type: 'text', required: true },
      { key: 'itineraire', label: "Itinéraire fluvial", type: 'text', required: true },
      { key: 'date_croisiere', label: "Date de la croisière", type: 'date', required: true },
      { key: 'tarif_personne', label: "Tarif par personne (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE CROISIÈRE FLUVIALE</h1><p>Entre l"opérateur <strong>{{operateur_croisiere}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Prestation</h2><p>L"opérateur organise une croisière fluviale sur l"itinéraire <strong>{{itineraire}}</strong> le <strong>{{date_croisiere}}</strong>.</p><h2>Article 2 – Tarif</h2><p>Le tarif est de <strong>{{tarif_personne}}</strong> FCFA par personne, incluant restauration à bord et animation.</p><h2>Article 3 – Sécurité maritime</h2><p>L"embarcation est conforme aux normes de sécurité en vigueur ; gilets de sauvetage disponibles pour tous les passagers.</p><h2>Article 4 – Annulation météo</h2><p>En cas d"annulation pour raison météorologique, un report ou un remboursement intégral est proposé au client.</p></div>`,
  },
  {
    code: 'tour_syndicat_initiative',
    name: "Accord de Syndicat d\"Initiative Touristique",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 11000,
    description: "Accord de partenariat entre collectivités locales et syndicats d\"initiative pour la promotion touristique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_syndicat', label: "Nom du syndicat d\"initiative", type: 'text', required: true },
      { key: 'collectivite', label: "Collectivité / mairie partenaire", type: 'text', required: true },
      { key: 'zone_couverture', label: "Zone géographique couverte", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l\"accord", type: 'date', required: true },
      { key: 'budget_annuel', label: "Budget annuel alloué (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SYNDICAT D"INITIATIVE TOURISTIQUE</h1><p>Entre le syndicat <strong>{{nom_syndicat}}</strong> et la collectivité <strong>{{collectivite}}</strong>, signé le <strong>{{date_accord}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le présent accord organise la promotion touristique de la zone <strong>{{zone_couverture}}</strong> par le syndicat d"initiative.</p><h2>Article 2 – Financement</h2><p>La collectivité alloue un budget annuel de <strong>{{budget_annuel}}</strong> FCFA pour les activités de promotion et d"accueil touristique.</p><h2>Article 3 – Missions du syndicat</h2><p>Le syndicat assure l"édition de guides touristiques, la tenue d\"un bureau d"information et l\"organisation d\"événements locaux.</p><h2>Article 4 – Reddition de comptes</h2><p>Le syndicat remet un rapport annuel d\"activités à la collectivité avant le 31 mars de l\"exercice suivant.</p></div>`,
  },
  {
    code: 'tour_location_vehicule_touristique',
    name: "Contrat de Location de Véhicule Touristique",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Contrat de location de véhicule avec ou sans chauffeur à usage touristique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'loueur', label: "Nom de la société de location", type: 'text', required: true },
      { key: 'nom_locataire', label: "Nom du locataire", type: 'text', required: true },
      { key: 'type_vehicule', label: "Type de véhicule", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de location", type: 'date', required: true },
      { key: 'duree_location', label: "Durée de la location (jours)", type: 'text', required: true },
      { key: 'tarif_journalier', label: "Tarif journalier (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE LOCATION DE VÉHICULE TOURISTIQUE</h1><p>Entre <strong>{{loueur}}</strong> et le locataire <strong>{{nom_locataire}}</strong>.</p><h2>Article 1 – Véhicule loué</h2><p>Le véhicule de type <strong>{{type_vehicule}}</strong> est mis à disposition du <strong>{{date_debut}}</strong> pour <strong>{{duree_location}}</strong> jours.</p><h2>Article 2 – Tarif</h2><p>Le tarif est de <strong>{{tarif_journalier}}</strong> FCFA par jour, carburant non inclus, assurance tous risques incluse.</p><h2>Article 3 – État du véhicule</h2><p>Un état des lieux contradictoire est établi à la prise en charge et à la restitution du véhicule.</p><h2>Article 4 – Responsabilité</h2><p>Le locataire est responsable de tout dommage causé pendant la période de location non couvert par l"assurance.</p></div>`,
  },
  {
    code: 'tour_animation_touristique',
    name: "Contrat d\"Animation Touristique",
    category: 'commercial_financier',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de prestation d\"animation culturelle et touristique pour établissements hôteliers et villages vacances.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_animateur', label: "Nom du prestataire / animateur", type: 'text', required: true },
      { key: 'nom_etablissement', label: "Nom de l\"établissement", type: 'text', required: true },
      { key: 'type_animation', label: "Type d\"animation proposée", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
      { key: 'remuneration', label: "Rémunération mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"ANIMATION TOURISTIQUE</h1><p>Entre <strong>{{nom_etablissement}}</strong> et l"animateur <strong>{{nom_animateur}}</strong>.</p><h2>Article 1 – Prestations</h2><p>L"animateur assure les animations suivantes : <strong>{{type_animation}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Rémunération</h2><p>La rémunération mensuelle est fixée à <strong>{{remuneration}}</strong> FCFA, versée en fin de mois.</p><h2>Article 3 – Horaires</h2><p>L"animateur intervient selon un planning hebdomadaire établi d\"un commun accord avec la direction.</p><h2>Article 4 – Droits d"auteur</h2><p>Les créations artistiques réalisées dans le cadre du contrat demeurent la propriété intellectuelle de l"animateur, sauf accord écrit contraire.</p></div>`,
  },
  {
    code: 'tour_label_tourisme_durable',
    name: "Accord de Label Tourisme Durable",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de certification et labellisation pour les établissements s\"engageant dans le tourisme responsable.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'organisme_label', label: "Organisme certificateur", type: 'text', required: true },
      { key: 'nom_etablissement', label: "Nom de l\"établissement candidat", type: 'text', required: true },
      { key: 'date_audit', label: "Date de l\"audit de certification", type: 'date', required: true },
      { key: 'criteres_principaux', label: "Critères principaux évalués", type: 'textarea', required: true },
      { key: 'duree_validite', label: "Durée de validité du label (ans)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE LABEL TOURISME DURABLE</h1><p>Entre l"organisme <strong>{{organisme_label}}</strong> et l"établissement <strong>{{nom_etablissement}}</strong>.</p><h2>Article 1 – Certification</h2><p>Suite à l"audit réalisé le <strong>{{date_audit}}</strong>, l"établissement est labellisé "Tourisme Durable" pour une durée de <strong>{{duree_validite}}</strong> an(s).</p><h2>Article 2 – Critères</h2><p>Les critères évalués comprennent : <strong>{{criteres_principaux}}</strong>.</p><h2>Article 3 – Obligations</h2><p>L"établissement s"engage à maintenir les standards requis et à permettre des audits de suivi annuels.</p><h2>Article 4 – Retrait du label</h2><p>Tout manquement grave aux engagements pris entraîne le retrait immédiat du label après mise en demeure restée sans effet.</p></div>`,
  },
  {
    code: 'tour_plan_developpement',
    name: "Plan de Développement Touristique",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 20000,
    description: "Document stratégique de planification du développement touristique d\"une destination ou d\"un établissement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'entite_beneficiaire', label: "Entité bénéficiaire", type: 'text', required: true },
      { key: 'zone_destination', label: "Destination / zone concernée", type: 'text', required: true },
      { key: 'horizon_planification', label: "Horizon de planification", type: 'text', required: true },
      { key: 'axes_strategiques', label: "Axes stratégiques prioritaires", type: 'textarea', required: true },
      { key: 'budget_previsionnel', label: "Budget prévisionnel total (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT TOURISTIQUE</h1><h2>Entité : {{entite_beneficiaire}} | Zone : {{zone_destination}}</h2><h2>Horizon : {{horizon_planification}}</h2><h2>1. Contexte et diagnostic</h2><p>Ce plan définit la stratégie de développement touristique pour la zone <strong>{{zone_destination}}</strong>, en tenant compte des atouts naturels, culturels et infrastructurels existants.</p><h2>2. Axes stratégiques</h2><p><strong>{{axes_strategiques}}</strong></p><h2>3. Budget prévisionnel</h2><p>Le budget total alloué à la mise en oeuvre du plan est de <strong>{{budget_previsionnel}}</strong> FCFA sur la période considérée.</p><h2>4. Indicateurs de suivi</h2><p>Des indicateurs de performance (fréquentation, recettes touristiques, emplois créés) seront suivis semestriellement.</p></div>`,
  },
  {
    code: 'tour_rapport_performance_hoteliere',
    name: "Rapport de Performance Hôtelière (KPIs)",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 11000,
    description: "Rapport d\"analyse des indicateurs clés de performance d\"un établissement hôtelier (taux d\"occupation, RevPAR, ADR).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_hotel', label: "Nom de l\"hôtel", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'taux_occupation', label: "Taux d\"occupation moyen (%)", type: 'text', required: true },
      { key: 'adr', label: "ADR – Tarif moyen journalier (FCFA)", type: 'text', required: true },
      { key: 'revpar', label: "RevPAR (FCFA)", type: 'text', required: true },
      { key: 'observations', label: "Observations et recommandations", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE HÔTELIÈRE</h1><h2>Établissement : {{nom_hotel}} | Période : {{periode_rapport}}</h2><h2>Indicateurs Clés de Performance</h2><table border="1" cellpadding="8" width="100%"><tr><th>KPI</th><th>Valeur</th></tr><tr><td>Taux d"occupation</td><td>{{taux_occupation}} %</td></tr><tr><td>ADR (Tarif Moyen)</td><td>{{adr}} FCFA</td></tr><tr><td>RevPAR</td><td>{{revpar}} FCFA</td></tr></table><h2>Analyse et Recommandations</h2><p>{{observations}}</p><h2>Conclusion</h2><p>Ce rapport constitue un outil de pilotage stratégique pour optimiser les performances commerciales de l"établissement.</p></div>`,
  },
  {
    code: 'tour_maintenance_hoteliere',
    name: "Contrat de Maintenance Hôtelière",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Contrat de maintenance préventive et corrective des équipements techniques d\"un établissement hôtelier.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'prestataire_maintenance', label: "Prestataire de maintenance", type: 'text', required: true },
      { key: 'nom_hotel', label: "Nom de l\"hôtel client", type: 'text', required: true },
      { key: 'equipements_couverts', label: "Équipements couverts", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
      { key: 'redevance_mensuelle', label: "Redevance mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MAINTENANCE HÔTELIÈRE</h1><p>Entre le prestataire <strong>{{prestataire_maintenance}}</strong> et l"hôtel <strong>{{nom_hotel}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le prestataire assure la maintenance préventive et corrective des équipements suivants : <strong>{{equipements_couverts}}</strong>.</p><h2>Article 2 – Durée et tarif</h2><p>Le contrat prend effet le <strong>{{date_debut}}</strong> avec une redevance mensuelle de <strong>{{redevance_mensuelle}}</strong> FCFA.</p><h2>Article 3 – Délais d"intervention</h2><p>Le prestataire s"engage à intervenir dans un délai de 4 heures pour toute panne impactant l"exploitation de l"hôtel.</p><h2>Article 4 – Pièces de rechange</h2><p>Le coût des pièces de rechange est facturé séparément, sur présentation de devis préalablement approuvé.</p></div>`,
  },
  {
    code: 'tour_blanchisserie_industrielle',
    name: "Accord de Blanchisserie Industrielle pour Hôtel",
    category: 'commercial_financier',
    price: 3500,
    priceMax: 10000,
    description: "Accord de prestation de blanchisserie industrielle pour la gestion du linge hôtelier.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'blanchisserie', label: "Nom de la blanchisserie", type: 'text', required: true },
      { key: 'nom_hotel', label: "Nom de l\"hôtel client", type: 'text', required: true },
      { key: 'volume_linge', label: "Volume mensuel estimé (kg)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de prestation", type: 'date', required: true },
      { key: 'tarif_kg', label: "Tarif au kilogramme (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE BLANCHISSERIE INDUSTRIELLE</h1><p>Entre la blanchisserie <strong>{{blanchisserie}}</strong> et l"hôtel <strong>{{nom_hotel}}</strong>.</p><h2>Article 1 – Prestation</h2><p>La blanchisserie prend en charge le lavage, séchage, repassage et conditionnement du linge hôtelier à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Volume et tarif</h2><p>Volume mensuel estimé : <strong>{{volume_linge}}</strong> kg. Tarif : <strong>{{tarif_kg}}</strong> FCFA/kg.</p><h2>Article 3 – Délais</h2><p>Le linge est restitué en 24 heures pour les articles standards et en 4 heures pour les commandes urgentes.</p><h2>Article 4 – Responsabilité</h2><p>La blanchisserie est responsable des dommages causés au linge durant le traitement, dans la limite de sa valeur de remplacement.</p></div>`,
  },
  {
    code: 'tour_spa_bien_etre',
    name: "Contrat de Service de Spa-Bien-Être",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Contrat de prestation de services spa, bien-être et soins corporels au sein d\"un établissement hôtelier.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'prestataire_spa', label: "Prestataire spa / bien-être", type: 'text', required: true },
      { key: 'nom_hotel', label: "Nom de l\"hôtel partenaire", type: 'text', required: true },
      { key: 'catalogue_soins', label: "Catalogue de soins proposés", type: 'textarea', required: true },
      { key: 'date_ouverture', label: "Date d\"ouverture du spa", type: 'date', required: true },
      { key: 'commission_hotel', label: "Commission reversée à l\"hôtel (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE SPA – BIEN-ÊTRE</h1><p>Entre le prestataire <strong>{{prestataire_spa}}</strong> et l"hôtel <strong>{{nom_hotel}}</strong>.</p><h2>Article 1 – Ouverture</h2><p>Le spa ouvre ses portes le <strong>{{date_ouverture}}</strong> au sein des locaux de l"hôtel.</p><h2>Article 2 – Prestations</h2><p>Le catalogue de soins comprend : <strong>{{catalogue_soins}}</strong>.</p><h2>Article 3 – Commission</h2><p>L"hôtel perçoit une commission de <strong>{{commission_hotel}}</strong> % sur le chiffre d"affaires net du spa, payable mensuellement.</p><h2>Article 4 – Normes sanitaires</h2><p>Le prestataire s"engage à respecter les normes d"hygiène et de sécurité applicables aux établissements de soins corporels.</p></div>`,
  },
  {
    code: 'tour_restauration_contractuelle',
    name: "Accord de Restauration Contractuelle (Cantines)",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Accord de prestation de restauration collective pour hôtels gérant des cantines ou restaurants de personnel.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'prestataire_restauration', label: "Prestataire de restauration", type: 'text', required: true },
      { key: 'nom_hotel', label: "Nom de l\"hôtel / établissement", type: 'text', required: true },
      { key: 'nombre_repas_jour', label: "Nombre de repas/jour estimés", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
      { key: 'prix_repas', label: "Prix unitaire d\"un repas (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RESTAURATION CONTRACTUELLE</h1><p>Entre le prestataire <strong>{{prestataire_restauration}}</strong> et l"établissement <strong>{{nom_hotel}}</strong>.</p><h2>Article 1 – Prestation</h2><p>Le prestataire assure la fourniture de repas équilibrés pour le personnel et/ou les résidents, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Volume et tarif</h2><p>Volume estimé : <strong>{{nombre_repas_jour}}</strong> repas/jour. Prix unitaire : <strong>{{prix_repas}}</strong> FCFA.</p><h2>Article 3 – Menus</h2><p>Les menus sont élaborés chaque semaine et soumis pour validation à la direction de l"établissement.</p><h2>Article 4 – Normes HACCP</h2><p>Le prestataire s"engage à respecter les protocoles HACCP et à tenir à disposition les enregistrements de contrôle qualité.</p></div>`,
  },
  {
    code: 'tour_securite_hoteliere',
    name: "Contrat de Service de Sécurité Hôtelière",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Contrat de prestation de gardiennage et de sécurité pour établissements hôteliers.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'societe_securite', label: "Société de sécurité prestataire", type: 'text', required: true },
      { key: 'nom_hotel', label: "Nom de l\"hôtel client", type: 'text', required: true },
      { key: 'nombre_agents', label: "Nombre d\"agents affectés", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
      { key: 'redevance_mensuelle', label: "Redevance mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE SÉCURITÉ HÔTELIÈRE</h1><p>Entre la société <strong>{{societe_securite}}</strong> et l"hôtel <strong>{{nom_hotel}}</strong>.</p><h2>Article 1 – Mission</h2><p>La société fournit <strong>{{nombre_agents}}</strong> agents de sécurité qualifiés à compter du <strong>{{date_debut}}</strong> pour assurer la sécurité des personnes et des biens.</p><h2>Article 2 – Rémunération</h2><p>La redevance mensuelle est de <strong>{{redevance_mensuelle}}</strong> FCFA, incluant salaires, équipements et assurances.</p><h2>Article 3 – Obligations</h2><p>Les agents sont soumis au règlement intérieur de l"hôtel et opèrent sous la supervision du chef de sécurité désigné.</p><h2>Article 4 – Responsabilité</h2><p>La société est responsable des actes de ses agents dans l"exercice de leurs fonctions.</p></div>`,
  },
  {
    code: 'tour_charte_accueil',
    name: "Charte d\"Accueil Touristique",
    category: 'commercial_financier',
    price: 2500,
    priceMax: 7000,
    description: "Charte définissant les engagements de qualité d\"accueil d\"un établissement ou d\"une destination touristique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_etablissement', label: "Nom de l\"établissement ou destination", type: 'text', required: true },
      { key: 'responsable_qualite', label: "Responsable qualité / directeur", type: 'text', required: true },
      { key: 'engagements_principaux', label: "Engagements principaux d\"accueil", type: 'textarea', required: true },
      { key: 'date_adoption', label: "Date d\"adoption de la charte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE D"ACCUEIL TOURISTIQUE</h1><h2>{{nom_etablissement}}</h2><p>Adoptée le <strong>{{date_adoption}}</strong> sous la responsabilité de <strong>{{responsable_qualite}}</strong>.</p><h2>Nos Engagements</h2><p><strong>{{engagements_principaux}}</strong></p><h2>Engagement 1 – Sourire et chaleur africaine</h2><p>Tout visiteur est accueilli avec le sourire, dans le respect de nos cultures et traditions d"hospitalité.</p><h2>Engagement 2 – Information et orientation</h2><p>Nous fournissons une information claire, honnête et complète sur nos services et ceux de la destination.</p><h2>Engagement 3 – Propreté et confort</h2><p>Nos installations sont maintenues propres et confortables à tout moment pour le bien-être de nos hôtes.</p><h2>Engagement 4 – Écoute et amélioration continue</h2><p>Nous recueillons les avis de nos visiteurs et nous engageons à améliorer continuellement la qualité de nos prestations.</p></div>`,
  },
  // ===== RESTAURATION / ALIMENTATION (25 templates) =====
  {
    code: 'rest_franchise_restauration_rapide',
    name: "Contrat de Franchise Restauration Rapide",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 25000,
    description: "Contrat de franchise pour l\"exploitation d\"une enseigne de restauration rapide en Afrique francophone.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'franchiseur', label: "Nom du franchiseur", type: 'text', required: true },
      { key: 'franchise', label: "Nom du franchisé", type: 'text', required: true },
      { key: 'enseigne', label: "Enseigne exploitée", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (ans)", type: 'text', required: true },
      { key: 'droit_entree', label: "Droit d\"entrée franchise (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE FRANCHISE – RESTAURATION RAPIDE</h1><p>Entre le franchiseur <strong>{{franchiseur}}</strong> et le franchisé <strong>{{franchisee}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le franchiseur concède au franchisé le droit d"exploiter l"enseigne <strong>{{enseigne}}</strong> selon le modèle défini dans le manuel d"exploitation.</p><h2>Article 2 – Durée</h2><p>Le contrat prend effet le <strong>{{date_debut}}</strong> pour une durée de <strong>{{duree_contrat}}</strong> ans.</p><h2>Article 3 – Droit d"entrée</h2><p>Le franchisé règle un droit d"entrée de <strong>{{droit_entree}}</strong> FCFA à la signature du présent contrat.</p><h2>Article 4 – Redevances</h2><p>Une redevance mensuelle de 5 % du chiffre d"affaires HT est due au franchiseur, payable avant le 15 de chaque mois.</p><h2>Article 5 – Formation</h2><p>Le franchiseur assure une formation initiale de 4 semaines pour le franchisé et son équipe de direction.</p></div>`,
  },
  {
    code: 'rest_gerance_restaurant',
    name: "Contrat de Gérance de Restaurant",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Contrat de gérance libre d\"un fonds de commerce de restauration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'proprietaire', label: "Nom du propriétaire du fonds", type: 'text', required: true },
      { key: 'gerant', label: "Nom du gérant", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant", type: 'text', required: true },
      { key: 'adresse_restaurant', label: "Adresse du restaurant", type: 'text', required: true },
      { key: 'date_prise_gerance', label: "Date de prise en gérance", type: 'date', required: true },
      { key: 'redevance_mensuelle', label: "Redevance mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GÉRANCE DE RESTAURANT</h1><p>Entre le propriétaire <strong>{{proprietaire}}</strong> et le gérant <strong>{{gerant}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le propriétaire confie au gérant la gestion du restaurant <strong>{{nom_restaurant}}</strong>, situé <strong>{{adresse_restaurant}}</strong>.</p><h2>Article 2 – Prise d"effet</h2><p>La gérance prend effet le <strong>{{date_prise_gerance}}</strong>.</p><h2>Article 3 – Redevance</h2><p>Le gérant verse au propriétaire une redevance mensuelle de <strong>{{redevance_mensuelle}}</strong> FCFA.</p><h2>Article 4 – Obligations du gérant</h2><p>Le gérant exploite le fonds à ses risques, s"acquitte de toutes les charges d"exploitation et maintient la clientèle.</p><h2>Article 5 – Droit applicable</h2><p>Le présent contrat est régi par le droit OHADA et le droit ivoirien applicable au commerce.</p></div>`,
  },
  {
    code: 'rest_livraison_plateforme',
    name: "Contrat de Service de Livraison (Plateforme)",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Contrat entre un restaurant et une plateforme de livraison de repas à domicile.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'plateforme', label: "Nom de la plateforme de livraison", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant partenaire", type: 'text', required: true },
      { key: 'taux_commission', label: "Taux de commission plateforme (%)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du partenariat", type: 'date', required: true },
      { key: 'zone_livraison', label: "Zone de livraison couverte", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE LIVRAISON – PLATEFORME NUMÉRIQUE</h1><p>Entre la plateforme <strong>{{plateforme}}</strong> et le restaurant <strong>{{nom_restaurant}}</strong>.</p><h2>Article 1 – Partenariat</h2><p>La plateforme référence le restaurant sur son application et assure la livraison des commandes dans la zone <strong>{{zone_livraison}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Commission</h2><p>La plateforme perçoit une commission de <strong>{{taux_commission}}</strong> % sur chaque commande livrée, déduite des reversements hebdomadaires.</p><h2>Article 3 – Délai de livraison</h2><p>La plateforme s"engage à assurer la livraison dans un délai moyen de 45 minutes à compter de la validation de la commande.</p><h2>Article 4 – Qualité</h2><p>Le restaurant est responsable de la qualité et de la conformité des plats préparés. La plateforme gère le service client relatif à la livraison.</p></div>`,
  },
  {
    code: 'rest_fournisseur_restauration',
    name: "Accord de Fournisseur de Restauration",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Accord-cadre d\"approvisionnement entre un restaurant et ses fournisseurs de denrées alimentaires.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_fournisseur', label: "Nom du fournisseur", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant client", type: 'text', required: true },
      { key: 'produits_fournis', label: "Catégories de produits fournis", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début de l\"accord", type: 'date', required: true },
      { key: 'delai_paiement', label: "Délai de paiement (jours)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FOURNISSEUR DE RESTAURATION</h1><p>Entre le fournisseur <strong>{{nom_fournisseur}}</strong> et le restaurant <strong>{{nom_restaurant}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le fournisseur s"engage à livrer les produits suivants : <strong>{{produits_fournis}}</strong>, selon les besoins exprimés par le restaurant.</p><h2>Article 2 – Durée</h2><p>Le présent accord prend effet le <strong>{{date_debut}}</strong> et se renouvelle tacitement par période annuelle.</p><h2>Article 3 – Paiement</h2><p>Les factures sont réglées dans un délai de <strong>{{delai_paiement}}</strong> jours à compter de la date de livraison.</p><h2>Article 4 – Qualité</h2><p>Les produits livrés doivent être conformes aux normes sanitaires ivoiriennes et accompagnés d"un bon de livraison.</p></div>`,
  },
  {
    code: 'rest_cuisinier_chef',
    name: "Contrat de Cuisinier Chef",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 11000,
    description: "Contrat de travail pour chef cuisinier dans un restaurant ou établissement de restauration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_chef', label: "Nom du chef cuisinier", type: 'text', required: true },
      { key: 'nom_etablissement', label: "Nom de l\"établissement employeur", type: 'text', required: true },
      { key: 'poste', label: "Intitulé du poste", type: 'text', required: true },
      { key: 'date_prise_poste', label: "Date de prise de poste", type: 'date', required: true },
      { key: 'salaire_mensuel', label: "Salaire mensuel brut (FCFA)", type: 'text', required: true },
      { key: 'specialite_culinaire', label: "Spécialité culinaire", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE CHEF CUISINIER</h1><p>Entre l"établissement <strong>{{nom_etablissement}}</strong> et le chef <strong>{{nom_chef}}</strong>.</p><h2>Article 1 – Engagement</h2><p>Le chef est engagé au poste de <strong>{{poste}}</strong>, spécialisé en <strong>{{specialite_culinaire}}</strong>, à compter du <strong>{{date_prise_poste}}</strong>.</p><h2>Article 2 – Rémunération</h2><p>Le salaire mensuel brut est de <strong>{{salaire_mensuel}}</strong> FCFA, conformément à la convention collective de la restauration.</p><h2>Article 3 – Missions</h2><p>Le chef est responsable de l"élaboration des menus, de la gestion des approvisionnements, du management de la brigade et du respect des normes HACCP.</p><h2>Article 4 – Clause d"exclusivité</h2><p>Le chef s"engage à exercer ses fonctions à titre exclusif pendant la durée du présent contrat.</p></div>`,
  },
  {
    code: 'rest_maitre_hotel',
    name: "Contrat de Maître d\"Hôtel",
    category: 'commercial_financier',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de travail pour maître d\"hôtel chargé de la gestion de la salle et du service client.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_maitre_hotel', label: "Nom du maître d\"hôtel", type: 'text', required: true },
      { key: 'nom_etablissement', label: "Nom de l\"établissement", type: 'text', required: true },
      { key: 'date_embauche', label: "Date d\"embauche", type: 'date', required: true },
      { key: 'salaire_mensuel', label: "Salaire mensuel brut (FCFA)", type: 'text', required: true },
      { key: 'responsabilites', label: "Principales responsabilités", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MAÎTRE D"HÔTEL</h1><p>Entre <strong>{{nom_etablissement}}</strong> et <strong>{{nom_maitre_hotel}}</strong>.</p><h2>Article 1 – Poste</h2><p>Le maître d"hôtel est engagé à compter du <strong>{{date_embauche}}</strong> pour assurer la gestion de la salle de restaurant.</p><h2>Article 2 – Rémunération</h2><p>Salaire mensuel brut : <strong>{{salaire_mensuel}}</strong> FCFA.</p><h2>Article 3 – Responsabilités</h2><p><strong>{{responsabilites}}</strong></p><h2>Article 4 – Présentation</h2><p>Le maître d"hôtel est tenu au port de la tenue professionnelle réglementaire et à une présentation irréprochable en permanence.</p></div>`,
  },
  {
    code: 'rest_carte_saisonniere',
    name: "Accord de Carte de Restaurant Saisonnière",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 8000,
    description: "Accord commercial pour l\"élaboration et la diffusion d\"une carte saisonnière entre un restaurant et ses partenaires.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_restaurant', label: "Nom du restaurant", type: 'text', required: true },
      { key: 'saison', label: "Saison concernée (ex : hivernage 2025)", type: 'text', required: true },
      { key: 'chef_responsable', label: "Chef responsable de la carte", type: 'text', required: true },
      { key: 'date_mise_en_vigueur', label: "Date de mise en vigueur", type: 'date', required: true },
      { key: 'nombre_plats', label: "Nombre de plats à la carte", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CARTE SAISONNIÈRE – RESTAURANT</h1><p>Restaurant : <strong>{{nom_restaurant}}</strong> | Saison : <strong>{{saison}}</strong></p><h2>Article 1 – Élaboration</h2><p>La carte saisonnière est élaborée par le chef <strong>{{chef_responsable}}</strong> et entre en vigueur le <strong>{{date_mise_en_vigueur}}</strong>.</p><h2>Article 2 – Composition</h2><p>La carte comprend <strong>{{nombre_plats}}</strong> plats valorisant les produits locaux de saison disponibles en Côte d"Ivoire.</p><h2>Article 3 – Révision</h2><p>La carte peut être révisée à tout moment en cas d"indisponibilité d"un produit, avec information préalable du personnel de salle.</p><h2>Article 4 – Affichage des prix</h2><p>Les prix sont affichés TTC et doivent être communiqués à la clientèle avant la commande, conformément à la réglementation en vigueur.</p></div>`,
  },
  {
    code: 'rest_traiteur_mariage',
    name: "Contrat de Traiteur Mariage",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de prestation de service traiteur pour cérémonies de mariage et réceptions familiales.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_traiteur', label: "Nom du traiteur", type: 'text', required: true },
      { key: 'nom_client', label: "Nom des mariés / client", type: 'text', required: true },
      { key: 'date_mariage', label: "Date du mariage", type: 'date', required: true },
      { key: 'lieu_reception', label: "Lieu de la réception", type: 'text', required: true },
      { key: 'nombre_couverts', label: "Nombre de couverts", type: 'text', required: true },
      { key: 'montant_total', label: "Montant total de la prestation (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE TRAITEUR MARIAGE</h1><p>Entre le traiteur <strong>{{nom_traiteur}}</strong> et le client <strong>{{nom_client}}</strong>.</p><h2>Article 1 – Prestation</h2><p>Le traiteur assure la restauration du mariage prévu le <strong>{{date_mariage}}</strong> à <strong>{{lieu_reception}}</strong> pour <strong>{{nombre_couverts}}</strong> convives.</p><h2>Article 2 – Montant</h2><p>Le montant total est de <strong>{{montant_total}}</strong> FCFA, payable : 40 % à la signature, 40 % deux semaines avant l"événement, 20 % le jour J.</p><h2>Article 3 – Prestations incluses</h2><p>Le contrat inclut : cocktail d"accueil, repas assis, desserts, mise en place, service à table et débarrassage.</p><h2>Article 4 – Personnel</h2><p>Le traiteur fournit l"ensemble du personnel de service, tenu de manière professionnelle.</p></div>`,
  },
  {
    code: 'rest_cantine_scolaire',
    name: "Accord de Cantine Scolaire",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Accord de prestation de restauration scolaire entre un opérateur et un établissement d\"enseignement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'prestataire', label: "Prestataire de restauration scolaire", type: 'text', required: true },
      { key: 'etablissement_scolaire', label: "Nom de l\"école / lycée", type: 'text', required: true },
      { key: 'nombre_eleves', label: "Nombre d\"élèves bénéficiaires", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
      { key: 'prix_repas', label: "Prix du repas par élève (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CANTINE SCOLAIRE</h1><p>Entre le prestataire <strong>{{prestataire}}</strong> et l"établissement <strong>{{etablissement_scolaire}}</strong>.</p><h2>Article 1 – Prestation</h2><p>Le prestataire assure la fourniture de repas équilibrés à <strong>{{nombre_eleves}}</strong> élèves, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Tarif</h2><p>Le prix du repas est de <strong>{{prix_repas}}</strong> FCFA par élève et par jour de scolarité.</p><h2>Article 3 – Nutrition</h2><p>Les repas respectent les recommandations nutritionnelles adaptées aux enfants scolarisés et valorisent les produits locaux ivoiriens.</p><h2>Article 4 – Contrôle</h2><p>L"établissement peut procéder à des contrôles qualité inopinés. Tout manquement grave entraîne résiliation du présent accord.</p></div>`,
  },
  {
    code: 'rest_food_truck',
    name: "Contrat de Service de Food Truck",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Contrat encadrant l\"exploitation et la prestation d\"un food truck sur un emplacement ou événement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'exploitant_truck', label: "Nom de l\"exploitant du food truck", type: 'text', required: true },
      { key: 'organisateur', label: "Organisateur / gestionnaire de site", type: 'text', required: true },
      { key: 'emplacement', label: "Emplacement attribué", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début d\"exploitation", type: 'date', required: true },
      { key: 'redevance', label: "Redevance mensuelle de stationnement (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE FOOD TRUCK</h1><p>Entre l"exploitant <strong>{{exploitant_truck}}</strong> et l"organisateur <strong>{{organisateur}}</strong>.</p><h2>Article 1 – Emplacement</h2><p>L"organisateur attribue l"emplacement <strong>{{emplacement}}</strong> au food truck à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Redevance</h2><p>L"exploitant règle une redevance mensuelle de <strong>{{redevance}}</strong> FCFA pour l"occupation du site.</p><h2>Article 3 – Obligations</h2><p>L"exploitant s"engage à maintenir la propreté de son emplacement, à respecter les horaires autorisés et les normes sanitaires en vigueur.</p><h2>Article 4 – Résiliation</h2><p>Tout non-paiement de la redevance à échéance entraîne une mise en demeure, puis résiliation sous 15 jours.</p></div>`,
  },
  {
    code: 'rest_marche_restauration',
    name: "Accord de Marché de Restauration",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 14000,
    description: "Accord de marché public ou privé de restauration collective pour administration ou entreprise.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'pouvoir_adjudicateur', label: "Pouvoir adjudicateur / donneur d\"ordre", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'text', required: true },
      { key: 'date_notification', label: "Date de notification du marché", type: 'date', required: true },
      { key: 'montant_marche', label: "Montant estimé du marché (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE MARCHÉ DE RESTAURATION</h1><p>Entre <strong>{{pouvoir_adjudicateur}}</strong> (donneur d"ordre) et <strong>{{titulaire}}</strong> (titulaire).</p><h2>Article 1 – Objet</h2><p>Le présent marché a pour objet : <strong>{{objet_marche}}</strong>, notifié le <strong>{{date_notification}}</strong>.</p><h2>Article 2 – Montant</h2><p>Le montant estimatif du marché est de <strong>{{montant_marche}}</strong> FCFA, révisable annuellement selon l"indice des prix.</p><h2>Article 3 – Exécution</h2><p>Le titulaire exécute le marché conformément au cahier des clauses techniques particulières (CCTP) annexé.</p><h2>Article 4 – Pénalités</h2><p>Tout manquement aux obligations de service entraîne l"application de pénalités définies dans le règlement du marché.</p></div>`,
  },
  {
    code: 'rest_gestion_cafeteria',
    name: "Contrat de Gestion de Cafétéria Entreprise",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Contrat de délégation de gestion d\"une cafétéria d\"entreprise à un prestataire spécialisé.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'entreprise_client', label: "Nom de l\"entreprise client", type: 'text', required: true },
      { key: 'gestionnaire', label: "Gestionnaire de la cafétéria", type: 'text', required: true },
      { key: 'capacite_accueil', label: "Capacité d\"accueil (couverts/jour)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de prise en gestion", type: 'date', required: true },
      { key: 'subvention_repas', label: "Subvention employeur par repas (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GESTION DE CAFÉTÉRIA D"ENTREPRISE</h1><p>Entre <strong>{{entreprise_client}}</strong> et le gestionnaire <strong>{{gestionnaire}}</strong>.</p><h2>Article 1 – Gestion déléguée</h2><p>L"entreprise délègue la gestion de sa cafétéria d"une capacité de <strong>{{capacite_accueil}}</strong> couverts/jour au gestionnaire, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Subvention</h2><p>L"entreprise verse une subvention de <strong>{{subvention_repas}}</strong> FCFA par repas servi à ses salariés.</p><h2>Article 3 – Qualité nutritionnelle</h2><p>Le gestionnaire s"engage à proposer des menus équilibrés, valorisant les produits frais et locaux.</p><h2>Article 4 – Reporting</h2><p>Un rapport mensuel d"activité (nombre de repas, satisfaction, incidents) est transmis à la direction des ressources humaines.</p></div>`,
  },
  {
    code: 'rest_fourniture_boissons',
    name: "Accord de Fourniture de Boissons (Brasseur)",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 11000,
    description: "Accord commercial entre un brasseur / distributeur de boissons et un établissement de restauration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'brasseur', label: "Nom du brasseur / distributeur", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant", type: 'text', required: true },
      { key: 'marques_referencees', label: "Marques référencées", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début de l\"accord", type: 'date', required: true },
      { key: 'remise_commerciale', label: "Remise commerciale accordée (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FOURNITURE DE BOISSONS</h1><p>Entre le brasseur <strong>{{brasseur}}</strong> et le restaurant <strong>{{nom_restaurant}}</strong>.</p><h2>Article 1 – Référencement</h2><p>Le restaurant s"engage à référencer les marques suivantes : <strong>{{marques_referencees}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Remise</h2><p>Le brasseur accorde une remise de <strong>{{remise_commerciale}}</strong> % sur le tarif public de vente aux établissements.</p><h2>Article 3 – Livraison</h2><p>Les livraisons sont effectuées sous 48 heures sur commande passée avant 12h00.</p><h2>Article 4 – Matériel</h2><p>Le brasseur peut mettre à disposition du matériel de froid en contrepartie d"un engagement de référencement exclusif sur la catégorie produit concernée.</p></div>`,
  },
  {
    code: 'rest_vending_machine',
    name: "Contrat de Service de Vending Machine",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 8000,
    description: "Contrat d\"installation et de gestion de distributeurs automatiques de boissons et snacks.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'operateur_vending', label: "Opérateur de vending machine", type: 'text', required: true },
      { key: 'client_site', label: "Nom du client / site d\"implantation", type: 'text', required: true },
      { key: 'nombre_machines', label: "Nombre de machines installées", type: 'text', required: true },
      { key: 'date_installation', label: "Date d\"installation", type: 'date', required: true },
      { key: 'commission_ca', label: "Commission sur CA reversée au site (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE VENDING MACHINE</h1><p>Entre l"opérateur <strong>{{operateur_vending}}</strong> et le client <strong>{{client_site}}</strong>.</p><h2>Article 1 – Installation</h2><p>L"opérateur installe et entretient <strong>{{nombre_machines}}</strong> distributeur(s) automatique(s) sur le site du client à compter du <strong>{{date_installation}}</strong>.</p><h2>Article 2 – Commission</h2><p>Le client perçoit une commission de <strong>{{commission_ca}}</strong> % sur le chiffre d"affaires HT des machines, versée mensuellement.</p><h2>Article 3 – Maintenance</h2><p>L"opérateur assure le réapprovisionnement et la maintenance des machines à ses frais.</p><h2>Article 4 – Électricité</h2><p>La consommation électrique des machines est à la charge du client, estimée à 250 kWh/mois par appareil.</p></div>`,
  },
  {
    code: 'rest_licence_marque',
    name: "Accord de Licence de Marque Restauration",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de licence d\"utilisation de marque pour l\"ouverture d\"un restaurant sous enseigne.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'titulaire_marque', label: "Titulaire de la marque", type: 'text', required: true },
      { key: 'licencie', label: "Licencié / exploitant", type: 'text', required: true },
      { key: 'marque', label: "Marque objet de la licence", type: 'text', required: true },
      { key: 'territoire', label: "Territoire de la licence", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de la licence", type: 'date', required: true },
      { key: 'redevance_licence', label: "Redevance annuelle de licence (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE LICENCE DE MARQUE – RESTAURATION</h1><p>Entre le titulaire <strong>{{titulaire_marque}}</strong> et le licencié <strong>{{licencie}}</strong>.</p><h2>Article 1 – Licence</h2><p>Le titulaire accorde au licencié le droit non exclusif d"utiliser la marque <strong>{{marque}}</strong> sur le territoire <strong>{{territoire}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Redevance</h2><p>Le licencié verse une redevance annuelle de <strong>{{redevance_licence}}</strong> FCFA.</p><h2>Article 3 – Contrôle qualité</h2><p>Le titulaire se réserve le droit de contrôler l"utilisation de la marque et le respect du cahier des charges associé.</p><h2>Article 4 – Propriété</h2><p>La marque demeure l"entière propriété du titulaire. Le licencié ne peut en aucun cas céder ou sous-licencier le présent accord.</p></div>`,
  },
  {
    code: 'rest_rapport_inspection_haccp',
    name: "Rapport d\"Inspection Hygiène Restaurant (HACCP)",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Rapport d\"inspection et de contrôle hygiénique d\"un restaurant selon les principes HACCP.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'inspecteur', label: "Nom de l\"inspecteur / organisme", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant inspecté", type: 'text', required: true },
      { key: 'date_inspection', label: "Date de l\"inspection", type: 'date', required: true },
      { key: 'observations', label: "Observations et points de non-conformité", type: 'textarea', required: true },
      { key: 'note_globale', label: "Note globale attribuée (/20)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D"INSPECTION HYGIÈNE – HACCP</h1><p>Établissement : <strong>{{nom_restaurant}}</strong> | Date : <strong>{{date_inspection}}</strong></p><p>Inspecteur : <strong>{{inspecteur}}</strong> | Note globale : <strong>{{note_globale}}/20</strong></p><h2>Points Contrôlés</h2><table border="1" cellpadding="6" width="100%"><tr><th>Point de contrôle</th><th>Conformité</th></tr><tr><td>Températures de conservation</td><td>Vérifiée</td></tr><tr><td>Propreté des surfaces</td><td>Vérifiée</td></tr><tr><td>Traçabilité des produits</td><td>Vérifiée</td></tr><tr><td>Formation du personnel</td><td>Vérifiée</td></tr></table><h2>Non-conformités et Recommandations</h2><p>{{observations}}</p><h2>Suivi</h2><p>Un rapport de suivi sera effectué dans un délai de 30 jours pour vérifier la mise en oeuvre des mesures correctives.</p></div>`,
  },
  {
    code: 'rest_plan_controle_sanitaire',
    name: "Plan de Contrôle Sanitaire Cuisines",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 11000,
    description: "Document de planification des contrôles sanitaires obligatoires pour les cuisines de restauration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_etablissement', label: "Nom de l\"établissement", type: 'text', required: true },
      { key: 'responsable_hygiene', label: "Responsable hygiène désigné", type: 'text', required: true },
      { key: 'date_mise_en_oeuvre', label: "Date de mise en oeuvre du plan", type: 'date', required: true },
      { key: 'points_critiques', label: "Points critiques identifiés (CCP)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE CONTRÔLE SANITAIRE DES CUISINES</h1><p>Établissement : <strong>{{nom_etablissement}}</strong> | Responsable hygiène : <strong>{{responsable_hygiene}}</strong></p><p>Date de mise en oeuvre : <strong>{{date_mise_en_oeuvre}}</strong></p><h2>Points Critiques de Contrôle (CCP)</h2><p><strong>{{points_critiques}}</strong></p><h2>Fréquence des contrôles</h2><table border="1" cellpadding="6" width="100%"><tr><th>Type de contrôle</th><th>Fréquence</th><th>Responsable</th></tr><tr><td>Températures frigos</td><td>2x/jour</td><td>Chef de partie</td></tr><tr><td>Nettoyage et désinfection</td><td>Quotidien</td><td>Équipe cuisine</td></tr><tr><td>Audit interne HACCP</td><td>Trimestriel</td><td>{{responsable_hygiene}}</td></tr></table><h2>Enregistrements</h2><p>Tous les contrôles sont consignés dans le registre sanitaire conservé pendant 5 ans.</p></div>`,
  },
  {
    code: 'rest_desinsectisation',
    name: "Contrat de Service de Désinsectisation Restaurant",
    category: 'commercial_financier',
    price: 2500,
    priceMax: 7000,
    description: "Contrat de prestation de désinsectisation et dératisation pour établissements de restauration.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'societe_3d', label: "Société de désinsectisation / 3D", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant client", type: 'text', required: true },
      { key: 'frequence_traitement', label: "Fréquence des traitements", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
      { key: 'tarif_annuel', label: "Tarif annuel du contrat (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE DÉSINSECTISATION – RESTAURANT</h1><p>Entre la société <strong>{{societe_3d}}</strong> et le restaurant <strong>{{nom_restaurant}}</strong>.</p><h2>Article 1 – Prestation</h2><p>La société assure des traitements 3D (dératisation, désinsectisation, désinfection) à la fréquence <strong>{{frequence_traitement}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Tarif</h2><p>Le tarif annuel est de <strong>{{tarif_annuel}}</strong> FCFA, payable en deux semestrialités.</p><h2>Article 3 – Produits</h2><p>Seuls des produits homologués et sans danger pour les denrées alimentaires sont utilisés dans les zones de production.</p><h2>Article 4 – Rapport d"intervention</h2><p>Un rapport est remis après chaque intervention, consigné dans le registre sanitaire de l"établissement.</p></div>`,
  },
  {
    code: 'rest_gestion_dechets',
    name: "Accord de Gestion des Déchets Restauration",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Accord de collecte et de traitement des déchets organiques et d\"emballages issus de la restauration.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'prestataire_dechets', label: "Prestataire de gestion des déchets", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant", type: 'text', required: true },
      { key: 'types_dechets', label: "Types de déchets couverts", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début de la prestation", type: 'date', required: true },
      { key: 'tarif_mensuel', label: "Tarif mensuel (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DES DÉCHETS – RESTAURATION</h1><p>Entre <strong>{{prestataire_dechets}}</strong> et le restaurant <strong>{{nom_restaurant}}</strong>.</p><h2>Article 1 – Périmètre</h2><p>Le prestataire assure la collecte et le traitement des déchets suivants : <strong>{{types_dechets}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Fréquence de collecte</h2><p>La collecte est effectuée au minimum 3 fois par semaine, ou selon les besoins exprimés par le restaurant.</p><h2>Article 3 – Tarif</h2><p>Le tarif mensuel est de <strong>{{tarif_mensuel}}</strong> FCFA.</p><h2>Article 4 – Traçabilité</h2><p>Le prestataire fournit un bordereau de suivi des déchets (BSD) pour chaque enlèvement, conformément à la réglementation environnementale ivoirienne.</p></div>`,
  },
  {
    code: 'rest_location_equipement_cuisine',
    name: "Contrat de Location d\"Équipement de Cuisine",
    category: 'commercial_financier',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de location de matériel et équipements professionnels de cuisine pour restaurateurs.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'loueur_equipement', label: "Société de location d\"équipements", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant locataire", type: 'text', required: true },
      { key: 'equipements', label: "Liste des équipements loués", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début de location", type: 'date', required: true },
      { key: 'loyer_mensuel', label: "Loyer mensuel total (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE LOCATION D"ÉQUIPEMENT DE CUISINE</h1><p>Entre <strong>{{loueur_equipement}}</strong> et le restaurant <strong>{{nom_restaurant}}</strong>.</p><h2>Article 1 – Équipements</h2><p>Le loueur met à disposition les équipements suivants : <strong>{{equipements}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Loyer</h2><p>Le loyer mensuel total est de <strong>{{loyer_mensuel}}</strong> FCFA, payable d"avance le 1er de chaque mois.</p><h2>Article 3 – Entretien</h2><p>L"entretien courant est à la charge du locataire. Les réparations dues à l"usure normale sont à la charge du loueur.</p><h2>Article 4 – Restitution</h2><p>Les équipements sont restitués en bon état de fonctionnement en fin de contrat, sous peine de facturation du coût de remise en état.</p></div>`,
  },
  {
    code: 'rest_certification_halal',
    name: "Accord de Certification Halal",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 14000,
    description: "Accord de certification halal pour restaurants et établissements de transformation alimentaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'organisme_certification', label: "Organisme de certification halal", type: 'text', required: true },
      { key: 'nom_etablissement', label: "Nom de l\"établissement candidat", type: 'text', required: true },
      { key: 'date_audit', label: "Date de l\"audit de certification", type: 'date', required: true },
      { key: 'categories_certifiees', label: "Catégories de produits / menus certifiés", type: 'textarea', required: true },
      { key: 'duree_validite', label: "Durée de validité du certificat (ans)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION HALAL</h1><p>Entre l"organisme <strong>{{organisme_certification}}</strong> et l"établissement <strong>{{nom_etablissement}}</strong>.</p><h2>Article 1 – Certification</h2><p>Suite à l"audit réalisé le <strong>{{date_audit}}</strong>, l"établissement est certifié halal pour les catégories suivantes : <strong>{{categories_certifiees}}</strong>.</p><h2>Article 2 – Durée</h2><p>Le certificat est valable <strong>{{duree_validite}}</strong> an(s) à compter de la date de délivrance.</p><h2>Article 3 – Obligations</h2><p>L"établissement s"engage à n"utiliser que des produits certifiés halal par un organisme reconnu et à permettre les contrôles inopinés de l"organisme certificateur.</p><h2>Article 4 – Utilisation du logo</h2><p>L"établissement est autorisé à afficher le logo de certification halal sur ses supports de communication pendant la durée de validité.</p></div>`,
  },
  {
    code: 'rest_prestation_self_service',
    name: "Contrat de Prestation Self-Service",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 11000,
    description: "Contrat de prestation de restauration en self-service pour collectivités, entreprises et établissements.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'prestataire', label: "Prestataire de restauration self-service", type: 'text', required: true },
      { key: 'client', label: "Nom du client / établissement", type: 'text', required: true },
      { key: 'nombre_convives_jour', label: "Nombre de convives/jour estimé", type: 'text', required: true },
      { key: 'date_debut', label: "Date de démarrage", type: 'date', required: true },
      { key: 'prix_ticket_repas', label: "Prix du ticket repas (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PRESTATION SELF-SERVICE</h1><p>Entre le prestataire <strong>{{prestataire}}</strong> et le client <strong>{{client}}</strong>.</p><h2>Article 1 – Prestation</h2><p>Le prestataire assure un service de restauration en self pour <strong>{{nombre_convives_jour}}</strong> convives/jour à compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 – Tarification</h2><p>Le prix du ticket repas est de <strong>{{prix_ticket_repas}}</strong> FCFA, révisable semestriellement selon l"indice des prix alimentaires.</p><h2>Article 3 – Choix des menus</h2><p>Au moins 2 choix de plats principaux, 2 entrées et 2 desserts sont proposés quotidiennement.</p><h2>Article 4 – Hygiène</h2><p>Le prestataire respecte les normes HACCP et fournit un relevé mensuel de ses contrôles de température et de traçabilité.</p></div>`,
  },
  {
    code: 'rest_kiosque_alimentaire',
    name: "Contrat de Kiosque Alimentaire Marché",
    category: 'commercial_financier',
    price: 2500,
    priceMax: 7000,
    description: "Contrat d\"attribution et d\"exploitation d\"un kiosque alimentaire dans un marché ou centre commercial.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'gestionnaire_marche', label: "Gestionnaire du marché / centre", type: 'text', required: true },
      { key: 'exploitant_kiosque', label: "Nom de l\"exploitant du kiosque", type: 'text', required: true },
      { key: 'reference_emplacement', label: "Référence de l\"emplacement", type: 'text', required: true },
      { key: 'date_attribution', label: "Date d\"attribution", type: 'date', required: true },
      { key: 'redevance_mensuelle', label: "Redevance mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE KIOSQUE ALIMENTAIRE – MARCHÉ</h1><p>Entre le gestionnaire <strong>{{gestionnaire_marche}}</strong> et l"exploitant <strong>{{exploitant_kiosque}}</strong>.</p><h2>Article 1 – Attribution</h2><p>L"emplacement <strong>{{reference_emplacement}}</strong> est attribué à l"exploitant à compter du <strong>{{date_attribution}}</strong> pour usage de vente alimentaire.</p><h2>Article 2 – Redevance</h2><p>La redevance mensuelle d"occupation est de <strong>{{redevance_mensuelle}}</strong> FCFA, payable le 5 de chaque mois.</p><h2>Article 3 – Activité autorisée</h2><p>L"exploitant est autorisé à exercer une activité de vente de produits alimentaires conformes aux normes sanitaires en vigueur.</p><h2>Article 4 – Propreté</h2><p>L"exploitant assure la propreté de son emplacement et contribue à la collecte des déchets selon le règlement intérieur du marché.</p></div>`,
  },
  {
    code: 'rest_cooperative_agricole_restaurant',
    name: "Accord de Coopérative Agricole-Restaurant (Circuit Court)",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Accord de partenariat en circuit court entre une coopérative agricole et un établissement de restauration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'cooperative', label: "Nom de la coopérative agricole", type: 'text', required: true },
      { key: 'nom_restaurant', label: "Nom du restaurant partenaire", type: 'text', required: true },
      { key: 'produits_circuit_court', label: "Produits livrés en circuit court", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début du partenariat", type: 'date', required: true },
      { key: 'volume_hebdomadaire', label: "Volume hebdomadaire estimé (kg)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CIRCUIT COURT – COOPÉRATIVE AGRICOLE / RESTAURANT</h1><p>Entre la coopérative <strong>{{cooperative}}</strong> et le restaurant <strong>{{nom_restaurant}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le présent accord vise à approvisionner le restaurant en produits locaux frais : <strong>{{produits_circuit_court}}</strong>, selon un modèle de circuit court direct.</p><h2>Article 2 – Volume</h2><p>Le volume hebdomadaire estimé est de <strong>{{volume_hebdomadaire}}</strong> kg, livré chaque lundi et jeudi matin.</p><h2>Article 3 – Prix</h2><p>Les prix sont négociés mensuellement sur la base des cours du marché agricole, avec un engagement de stabilité sur 4 semaines.</p><h2>Article 4 – Qualité et traçabilité</h2><p>La coopérative garantit la traçabilité de tous les produits livrés et fournit les certificats d"origine à la demande.</p><h2>Article 5 – Durée</h2><p>Le partenariat débute le <strong>{{date_debut}}</strong> pour une durée d"un an, renouvelable par accord des parties.</p></div>`,
  },
  {
    code: 'rest_charte_restauration_durable',
    name: "Charte de Restauration Durable",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Charte d\"engagements pour une restauration responsable, écoresponsable et durable en Afrique francophone.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_etablissement', label: "Nom de l\"établissement", type: 'text', required: true },
      { key: 'directeur', label: "Nom du directeur / responsable", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d\"adoption de la charte", type: 'date', required: true },
      { key: 'engagements_durabilite', label: "Engagements de durabilité souscrits", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE RESTAURATION DURABLE</h1><h2>{{nom_etablissement}}</h2><p>Adoptée le <strong>{{date_adoption}}</strong> sous l"autorité de <strong>{{directeur}}</strong>.</p><h2>Nos Engagements</h2><p><strong>{{engagements_durabilite}}</strong></p><h2>Pilier 1 – Approvisionnement responsable</h2><p>Nous privilégions les produits locaux, de saison et issus de l"agriculture durable, réduisant ainsi notre empreinte carbone liée au transport.</p><h2>Pilier 2 – Réduction du gaspillage alimentaire</h2><p>Nous mettons en place des portions adaptées, valorisons les invendus et compostons les déchets organiques.</p><h2>Pilier 3 – Économies d"énergie et d"eau</h2><p>Nous équipons nos cuisines d"appareils à faible consommation et sensibilisons notre personnel aux bonnes pratiques environnementales.</p><h2>Pilier 4 – Emploi local et formation</h2><p>Nous recrutons prioritairement dans la communauté locale et investissons dans la formation professionnelle de nos équipes.</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 35b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
