import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── RECHERCHE MÉDICALE (rech_) ───────────────────────────────────────────
  {
    code: 'rech_protocole_phase1',
    name: "Protocole d'essai clinique (phase I)",
    category: 'sante',
    price: 12000,
    priceMax: 40000,
    description: "Protocole standardisé pour essai clinique de phase I selon les bonnes pratiques cliniques OHADA/DPMED.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'promoteur', label: "Promoteur", type: 'text', required: true },
      { key: 'investigateur_principal', label: "Investigateur principal", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début prévue", type: 'date', required: true },
      { key: 'objectif_primaire', label: "Objectif primaire", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROTOCOLE D'ESSAI CLINIQUE — PHASE I</h1><h2>{{titre_essai}}</h2><p><strong>Promoteur :</strong> {{promoteur}}</p><p><strong>Investigateur principal :</strong> {{investigateur_principal}}</p><p><strong>Date de début prévue :</strong> {{date_debut}}</p><h3>1. Objectif primaire</h3><p>{{objectif_primaire}}</p><h3>2. Cadre réglementaire</h3><p>Le présent protocole est établi conformément aux Bonnes Pratiques Cliniques (BPC) de l'ICH E6 et aux exigences de la Direction de la Pharmacie et du Médicament (DPMED) de Côte d'Ivoire.</p></div>`,
  },
  {
    code: 'rech_protocole_phase23',
    name: "Protocole d'essai clinique (phase II-III)",
    category: 'sante',
    price: 14000,
    priceMax: 48000,
    description: "Protocole complet pour essai clinique de phase II ou III, incluant critères d'inclusion/exclusion et plan statistique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'phase', label: "Phase (II ou III)", type: 'text', required: true },
      { key: 'promoteur', label: "Promoteur", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
      { key: 'criteres_inclusion', label: "Critères d'inclusion", type: 'textarea', required: true },
      { key: 'plan_statistique', label: "Plan statistique résumé", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROTOCOLE D'ESSAI CLINIQUE — PHASE {{phase}}</h1><h2>{{titre_essai}}</h2><p><strong>Promoteur :</strong> {{promoteur}}</p><p><strong>Date de début :</strong> {{date_debut}}</p><h3>1. Critères d'inclusion</h3><p>{{criteres_inclusion}}</p><h3>2. Plan statistique</h3><p>{{plan_statistique}}</p><h3>3. Conformité réglementaire</h3><p>Essai conduit conformément aux BPC ICH E6(R2) et à la réglementation pharmaceutique OHADA en vigueur.</p></div>`,
  },
  {
    code: 'rech_consentement_eclaire',
    name: "Formulaire de consentement éclairé (essai clinique)",
    category: 'sante',
    price: 5000,
    priceMax: 14000,
    description: "Formulaire de consentement éclairé bilingue (français/langue locale) pour participant à un essai clinique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'nom_participant', label: "Nom du participant", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'description_essai', label: "Description de l'essai", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>FORMULAIRE DE CONSENTEMENT ÉCLAIRÉ</h1><h2>Essai clinique : {{titre_essai}}</h2><p>Je soussigné(e), <strong>{{nom_participant}}</strong>, déclare avoir reçu une information complète et compréhensible sur l'essai clinique décrit ci-après.</p><h3>Description de l'essai</h3><p>{{description_essai}}</p><h3>Droits du participant</h3><p>Je suis libre de refuser de participer ou de me retirer de cet essai à tout moment, sans avoir à motiver ma décision et sans subir aucun préjudice.</p><p><strong>Date :</strong> {{date_signature}}</p><p>Signature du participant : _____________________ Signature de l'investigateur : _____________________</p></div>`,
  },
  {
    code: 'rech_accord_cer',
    name: "Accord de comité d'éthique de la recherche (CER)",
    category: 'sante',
    price: 8000,
    priceMax: 24000,
    description: "Document d'accord entre un CER national/institutionnel et l'équipe de recherche pour approbation éthique d'un protocole.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'nom_cer', label: "Nom du comité d'éthique", type: 'text', required: true },
      { key: 'titre_protocole', label: "Titre du protocole soumis", type: 'text', required: true },
      { key: 'numero_dossier', label: "Numéro de dossier CER", type: 'text', required: true },
      { key: 'date_approbation', label: "Date d'approbation", type: 'date', required: true },
      { key: 'conditions_approbation', label: "Conditions d'approbation", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DU COMITÉ D'ÉTHIQUE DE LA RECHERCHE</h1><p><strong>Comité :</strong> {{nom_cer}}</p><p><strong>Protocole :</strong> {{titre_protocole}}</p><p><strong>N° de dossier :</strong> {{numero_dossier}}</p><p><strong>Date d'approbation :</strong> {{date_approbation}}</p><h3>Décision</h3><p>Le présent comité approuve le protocole susvisé sous réserve des conditions suivantes :</p><p>{{conditions_approbation}}</p><p>Cette approbation est valable pour une durée d'un an et doit être renouvelée annuellement.</p></div>`,
  },
  {
    code: 'rech_contrat_promoteur',
    name: "Contrat de promoteur d'essai clinique",
    category: 'sante',
    price: 13000,
    priceMax: 45000,
    description: "Contrat définissant les responsabilités du promoteur dans la conduite d'un essai clinique en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_promoteur', label: "Nom du promoteur", type: 'text', required: true },
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
      { key: 'budget_total', label: "Budget total alloué (FCFA)", type: 'text', required: true },
      { key: 'obligations_promoteur', label: "Obligations principales du promoteur", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PROMOTEUR D'ESSAI CLINIQUE</h1><p>Entre le promoteur <strong>{{nom_promoteur}}</strong> et les parties désignées dans l'essai intitulé <strong>{{titre_essai}}</strong>.</p><p><strong>Date :</strong> {{date_contrat}}</p><p><strong>Budget total :</strong> {{budget_total}} FCFA</p><h3>Obligations du promoteur</h3><p>{{obligations_promoteur}}</p><h3>Responsabilité</h3><p>Le promoteur assume la responsabilité globale de l'essai clinique et s'engage à respecter la réglementation DPMED et les BPC internationales.</p></div>`,
  },
  {
    code: 'rech_accord_investigateur',
    name: "Accord d'investigateur principal",
    category: 'sante',
    price: 7000,
    priceMax: 20000,
    description: "Accord formel entre le promoteur et l'investigateur principal définissant rôles, obligations et rémunération.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'nom_investigateur', label: "Nom de l'investigateur principal", type: 'text', required: true },
      { key: 'etablissement', label: "Établissement de recherche", type: 'text', required: true },
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'honoraires', label: "Honoraires prévus (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'INVESTIGATEUR PRINCIPAL</h1><p>Le présent accord est conclu entre le promoteur et <strong>{{nom_investigateur}}</strong>, rattaché à <strong>{{etablissement}}</strong>.</p><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date :</strong> {{date_accord}}</p><p><strong>Honoraires :</strong> {{honoraires}} FCFA</p><h3>Engagements de l'investigateur</h3><p>L'investigateur principal s'engage à conduire l'essai conformément au protocole approuvé, aux BPC et aux exigences réglementaires nationales.</p></div>`,
  },
  {
    code: 'rech_contrat_cra',
    name: "Contrat de moniteur d'essai clinique (CRA)",
    category: 'sante',
    price: 6000,
    priceMax: 18000,
    description: "Contrat de prestation de service pour moniteur d'essai clinique (Clinical Research Associate) intervenant sur sites ivoiriens.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 49,
    fieldsJson: F([
      { key: 'nom_cra', label: "Nom du CRA", type: 'text', required: true },
      { key: 'promoteur', label: "Promoteur mandant", type: 'text', required: true },
      { key: 'sites_assignes', label: "Sites assignés", type: 'textarea', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
      { key: 'remuneration', label: "Rémunération mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MONITEUR D'ESSAI CLINIQUE (CRA)</h1><p><strong>CRA :</strong> {{nom_cra}}</p><p><strong>Promoteur :</strong> {{promoteur}}</p><p><strong>Sites assignés :</strong> {{sites_assignes}}</p><p><strong>Date de début :</strong> {{date_debut}}</p><p><strong>Rémunération :</strong> {{remuneration}} FCFA/mois</p><h3>Missions</h3><p>Le CRA est chargé de la surveillance du bon déroulement de l'essai, de la vérification des données source et du respect des BPC sur les sites assignés.</p></div>`,
  },
  {
    code: 'rech_accord_coordination_multisites',
    name: "Accord de coordination centre multi-sites",
    category: 'sante',
    price: 9000,
    priceMax: 28000,
    description: "Accord entre le centre coordonnateur et les centres partenaires dans un essai clinique multi-sites en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 44,
    fieldsJson: F([
      { key: 'centre_coordonnateur', label: "Centre coordonnateur", type: 'text', required: true },
      { key: 'centres_partenaires', label: "Centres partenaires", type: 'textarea', required: true },
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE COORDINATION MULTI-SITES</h1><p><strong>Centre coordonnateur :</strong> {{centre_coordonnateur}}</p><p><strong>Centres partenaires :</strong> {{centres_partenaires}}</p><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Organisation</h3><p>Le centre coordonnateur assure la supervision scientifique et administrative de l'ensemble des sites participants et garantit l'harmonisation des procédures.</p></div>`,
  },
  {
    code: 'rech_contrat_labo_central',
    name: "Contrat de laboratoire central essai clinique",
    category: 'sante',
    price: 10000,
    priceMax: 32000,
    description: "Contrat de prestation entre le promoteur et le laboratoire central chargé des analyses biologiques de l'essai.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 47,
    fieldsJson: F([
      { key: 'nom_laboratoire', label: "Nom du laboratoire", type: 'text', required: true },
      { key: 'promoteur', label: "Promoteur", type: 'text', required: true },
      { key: 'analyses_prevues', label: "Types d'analyses prévues", type: 'textarea', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
      { key: 'cout_total', label: "Coût total estimé (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE LABORATOIRE CENTRAL — ESSAI CLINIQUE</h1><p><strong>Laboratoire :</strong> {{nom_laboratoire}}</p><p><strong>Promoteur :</strong> {{promoteur}}</p><p><strong>Date :</strong> {{date_contrat}}</p><h3>Analyses prévues</h3><p>{{analyses_prevues}}</p><p><strong>Coût total estimé :</strong> {{cout_total}} FCFA</p><h3>Qualité</h3><p>Le laboratoire s'engage à respecter les normes ISO 15189 et les exigences BPC pour la gestion des échantillons biologiques.</p></div>`,
  },
  {
    code: 'rech_accord_pharmacie_essai',
    name: "Accord de pharmacie essai clinique",
    category: 'sante',
    price: 7500,
    priceMax: 22000,
    description: "Accord définissant les responsabilités de la pharmacie hospitalière dans la gestion des médicaments expérimentaux.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'etablissement', label: "Établissement hospitalier", type: 'text', required: true },
      { key: 'responsable_pharmacie', label: "Pharmacien responsable", type: 'text', required: true },
      { key: 'produit_experimental', label: "Produit expérimental concerné", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PHARMACIE — ESSAI CLINIQUE</h1><p><strong>Établissement :</strong> {{etablissement}}</p><p><strong>Pharmacien responsable :</strong> {{responsable_pharmacie}}</p><p><strong>Produit expérimental :</strong> {{produit_experimental}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Responsabilités</h3><p>La pharmacie est responsable de la réception, du stockage dans les conditions requises, de la dispensation et de la traçabilité du médicament expérimental conformément aux BPC.</p></div>`,
  },
  {
    code: 'rech_rapport_monitoring',
    name: "Rapport de suivi essai clinique (rapport de monitoring)",
    category: 'sante',
    price: 4000,
    priceMax: 12000,
    description: "Rapport de visite de monitoring documentant l'état d'avancement de l'essai et les actions correctives requises.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'site_visite', label: "Site visité", type: 'text', required: true },
      { key: 'date_visite', label: "Date de la visite", type: 'date', required: true },
      { key: 'nom_cra', label: "Nom du CRA", type: 'text', required: true },
      { key: 'observations', label: "Observations et constats", type: 'textarea', required: true },
      { key: 'actions_correctives', label: "Actions correctives requises", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE MONITORING — VISITE DE SUIVI</h1><p><strong>Site :</strong> {{site_visite}}</p><p><strong>Date :</strong> {{date_visite}}</p><p><strong>CRA :</strong> {{nom_cra}}</p><h3>Observations</h3><p>{{observations}}</p><h3>Actions correctives</h3><p>{{actions_correctives}}</p><h3>Conclusion</h3><p>Ce rapport sera transmis à l'investigateur principal et au promoteur dans les 10 jours ouvrables suivant la visite.</p></div>`,
  },
  {
    code: 'rech_rapport_pharmacovigilance',
    name: "Rapport de pharmacovigilance (effets indésirables)",
    category: 'sante',
    price: 5000,
    priceMax: 16000,
    description: "Rapport de déclaration d'effets indésirables graves (EIG) dans le cadre d'un essai clinique, selon les exigences DPMED.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'date_survenue', label: "Date de survenue de l'EIG", type: 'date', required: true },
      { key: 'description_eig', label: "Description de l'effet indésirable grave", type: 'textarea', required: true },
      { key: 'mesures_prises', label: "Mesures prises", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PHARMACOVIGILANCE — EFFET INDÉSIRABLE GRAVE</h1><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date de survenue :</strong> {{date_survenue}}</p><h3>Description de l'EIG</h3><p>{{description_eig}}</p><h3>Mesures prises</h3><p>{{mesures_prises}}</p><h3>Déclaration réglementaire</h3><p>Ce rapport est soumis à la DPMED et au CER dans les délais réglementaires impartis (7 jours pour les EIG fatals, 15 jours pour les autres).</p></div>`,
  },
  {
    code: 'rech_accord_registre_essais',
    name: "Accord de registre des essais cliniques",
    category: 'sante',
    price: 4500,
    priceMax: 14000,
    description: "Accord d'enregistrement d'un essai clinique dans un registre international reconnu (ANZCTR, Pan African Clinical Trials Registry).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'registre_choisi', label: "Registre choisi", type: 'text', required: true },
      { key: 'numero_enregistrement', label: "Numéro d'enregistrement", type: 'text', required: true },
      { key: 'date_enregistrement', label: "Date d'enregistrement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'ENREGISTREMENT — REGISTRE DES ESSAIS CLINIQUES</h1><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Registre :</strong> {{registre_choisi}}</p><p><strong>Numéro :</strong> {{numero_enregistrement}}</p><p><strong>Date :</strong> {{date_enregistrement}}</p><h3>Engagement de transparence</h3><p>Le promoteur s'engage à mettre à jour les informations du registre à toutes les étapes clés de l'essai et à publier les résultats dans les 12 mois suivant la clôture.</p></div>`,
  },
  {
    code: 'rech_accord_publication',
    name: "Accord de publication des résultats essai",
    category: 'sante',
    price: 5500,
    priceMax: 16000,
    description: "Accord entre promoteur, investigateurs et partenaires définissant les droits et modalités de publication des résultats.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'parties_signataires', label: "Parties signataires", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'ordre_auteurs', label: "Critères d'ordre des auteurs", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PUBLICATION DES RÉSULTATS</h1><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Parties signataires</h3><p>{{parties_signataires}}</p><h3>Ordre des auteurs</h3><p>{{ordre_auteurs}}</p><h3>Droit de publication</h3><p>Le promoteur dispose d'un délai de révision de 30 jours avant toute soumission. Les résultats négatifs seront publiés au même titre que les résultats positifs.</p></div>`,
  },
  {
    code: 'rech_accord_data_repository',
    name: "Accord de dépôt de données (data repository)",
    category: 'sante',
    price: 6000,
    priceMax: 18000,
    description: "Accord encadrant le dépôt et le partage des données de recherche dans un entrepôt de données scientifiques.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 37,
    fieldsJson: F([
      { key: 'equipe_recherche', label: "Équipe de recherche", type: 'text', required: true },
      { key: 'entrepot_donnees', label: "Entrepôt de données choisi", type: 'text', required: true },
      { key: 'description_donnees', label: "Description des données déposées", type: 'textarea', required: true },
      { key: 'date_depot', label: "Date prévue de dépôt", type: 'date', required: true },
      { key: 'conditions_acces', label: "Conditions d'accès aux données", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DÉPÔT DE DONNÉES DE RECHERCHE</h1><p><strong>Équipe :</strong> {{equipe_recherche}}</p><p><strong>Entrepôt :</strong> {{entrepot_donnees}}</p><p><strong>Date de dépôt prévue :</strong> {{date_depot}}</p><h3>Description des données</h3><p>{{description_donnees}}</p><h3>Conditions d'accès</h3><p>{{conditions_acces}}</p><h3>Protection des données personnelles</h3><p>Toutes les données seront anonymisées conformément aux principes RGPD et aux directives éthiques nationales avant tout dépôt public.</p></div>`,
  },
  {
    code: 'rech_contrat_biostatistiques',
    name: "Contrat de service de biostatistiques essai clinique",
    category: 'sante',
    price: 9000,
    priceMax: 28000,
    description: "Contrat de prestation de service biostatistique pour l'analyse des données d'un essai clinique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'prestataire_stats', label: "Prestataire biostatistique", type: 'text', required: true },
      { key: 'promoteur', label: "Promoteur", type: 'text', required: true },
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'methodes_stats', label: "Méthodes statistiques prévues", type: 'textarea', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
      { key: 'budget', label: "Budget (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE BIOSTATISTIQUES</h1><p><strong>Prestataire :</strong> {{prestataire_stats}}</p><p><strong>Promoteur :</strong> {{promoteur}}</p><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date :</strong> {{date_contrat}}</p><h3>Méthodes statistiques</h3><p>{{methodes_stats}}</p><p><strong>Budget :</strong> {{budget}} FCFA</p><h3>Livrables</h3><p>Le prestataire fournira un plan d'analyse statistique (PAS), les programmes d'analyse et le rapport statistique final conformément aux ICH E9.</p></div>`,
  },
  {
    code: 'rech_rapport_inspection_reglementaire',
    name: "Rapport d'inspection réglementaire essai",
    category: 'sante',
    price: 7000,
    priceMax: 21000,
    description: "Rapport structuré répondant aux constats d'une inspection réglementaire DPMED sur un essai clinique en cours.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 41,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai inspecté", type: 'text', required: true },
      { key: 'date_inspection', label: "Date de l'inspection", type: 'date', required: true },
      { key: 'autorite_inspection', label: "Autorité ayant conduit l'inspection", type: 'text', required: true },
      { key: 'constats_principaux', label: "Constats principaux", type: 'textarea', required: true },
      { key: 'plan_correction', label: "Plan de correction (CAPA)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE RÉPONSE À L'INSPECTION RÉGLEMENTAIRE</h1><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date d'inspection :</strong> {{date_inspection}}</p><p><strong>Autorité :</strong> {{autorite_inspection}}</p><h3>Constats principaux</h3><p>{{constats_principaux}}</p><h3>Plan de correction (CAPA)</h3><p>{{plan_correction}}</p><h3>Engagement</h3><p>L'équipe de recherche s'engage à mettre en oeuvre l'ensemble des mesures correctives dans les délais convenus avec l'autorité réglementaire.</p></div>`,
  },
  {
    code: 'rech_accord_dpmed',
    name: "Accord avec autorité réglementaire (DPMED Côte d'Ivoire)",
    category: 'sante',
    price: 11000,
    priceMax: 35000,
    description: "Document d'accord formel entre le promoteur d'un essai clinique et la DPMED pour autorisation de conduite d'essai.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'promoteur', label: "Promoteur", type: 'text', required: true },
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'numero_autorisation', label: "Numéro d'autorisation DPMED", type: 'text', required: true },
      { key: 'date_autorisation', label: "Date d'autorisation", type: 'date', required: true },
      { key: 'conditions_speciales', label: "Conditions particulières imposées", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD AVEC LA DIRECTION DE LA PHARMACIE ET DU MÉDICAMENT (DPMED)</h1><p><strong>Promoteur :</strong> {{promoteur}}</p><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Numéro d'autorisation :</strong> {{numero_autorisation}}</p><p><strong>Date :</strong> {{date_autorisation}}</p><h3>Conditions particulières</h3><p>{{conditions_speciales}}</p><h3>Base légale</h3><p>La présente autorisation est délivrée conformément au décret portant réglementation des essais cliniques en République de Côte d'Ivoire et aux recommandations de l'OMS.</p></div>`,
  },
  {
    code: 'rech_accord_financement_essai',
    name: "Accord de financement essai (bailleur pharmaceutique)",
    category: 'sante',
    price: 12000,
    priceMax: 40000,
    description: "Convention de financement entre un bailleur pharmaceutique ou institutionnel et l'équipe de recherche clinique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'bailleur', label: "Bailleur de fonds", type: 'text', required: true },
      { key: 'equipe_recherche', label: "Équipe de recherche bénéficiaire", type: 'text', required: true },
      { key: 'titre_essai', label: "Titre de l'essai financé", type: 'text', required: true },
      { key: 'montant_financement', label: "Montant total du financement (FCFA)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'modalites_versement', label: "Modalités de versement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FINANCEMENT D'ESSAI CLINIQUE</h1><p><strong>Bailleur :</strong> {{bailleur}}</p><p><strong>Équipe bénéficiaire :</strong> {{equipe_recherche}}</p><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Montant :</strong> {{montant_financement}} FCFA</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Modalités de versement</h3><p>{{modalites_versement}}</p><h3>Redevabilité</h3><p>L'équipe bénéficiaire soumettra des rapports financiers trimestriels et un rapport final d'utilisation des fonds.</p></div>`,
  },
  {
    code: 'rech_plan_gestion_donnees',
    name: "Plan de gestion des données essai clinique (DMP)",
    category: 'sante',
    price: 6500,
    priceMax: 20000,
    description: "Document de planification décrivant la collecte, le stockage, la qualité et le partage des données d'un essai clinique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 43,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'responsable_donnees', label: "Responsable des données", type: 'text', required: true },
      { key: 'systeme_gestion', label: "Système de gestion des données (EDC)", type: 'text', required: true },
      { key: 'date_dmp', label: "Date du plan", type: 'date', required: true },
      { key: 'procedure_qualite', label: "Procédures de contrôle qualité", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE GESTION DES DONNÉES (DMP)</h1><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Responsable données :</strong> {{responsable_donnees}}</p><p><strong>Système EDC :</strong> {{systeme_gestion}}</p><p><strong>Date :</strong> {{date_dmp}}</p><h3>Procédures de contrôle qualité</h3><p>{{procedure_qualite}}</p><h3>Sécurité et archivage</h3><p>Les données seront conservées 15 ans après la clôture de l'essai, conformément aux exigences réglementaires en vigueur.</p></div>`,
  },
  {
    code: 'rech_accord_partenariat_nord_sud',
    name: "Accord de partenariat recherche nord-sud",
    category: 'sante',
    price: 10000,
    priceMax: 30000,
    description: "Convention de partenariat équitable de recherche entre une institution d'Afrique de l'Ouest et un partenaire du Nord.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'institution_sud', label: "Institution partenaire Sud", type: 'text', required: true },
      { key: 'institution_nord', label: "Institution partenaire Nord", type: 'text', required: true },
      { key: 'objet_partenariat', label: "Objet du partenariat", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'repartition_droits', label: "Répartition des droits de propriété intellectuelle", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT DE RECHERCHE NORD-SUD</h1><p><strong>Institution Sud :</strong> {{institution_sud}}</p><p><strong>Institution Nord :</strong> {{institution_nord}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Objet du partenariat</h3><p>{{objet_partenariat}}</p><h3>Propriété intellectuelle</h3><p>{{repartition_droits}}</p><h3>Principe d'équité</h3><p>Ce partenariat est fondé sur les principes d'égalité, de réciprocité et de renforcement des capacités de l'institution du Sud, conformément aux recommandations de la Déclaration de Montréal sur la recherche en santé mondiale.</p></div>`,
  },
  {
    code: 'rech_contrat_echantilotheque',
    name: "Contrat de service d'échantillothèque (biothèque)",
    category: 'sante',
    price: 8500,
    priceMax: 26000,
    description: "Contrat encadrant la collecte, la conservation et l'utilisation d'échantillons biologiques dans une biothèque.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 38,
    fieldsJson: F([
      { key: 'biotheque', label: "Nom de la biothèque", type: 'text', required: true },
      { key: 'depositaire', label: "Déposant des échantillons", type: 'text', required: true },
      { key: 'type_echantillons', label: "Type d'échantillons", type: 'text', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
      { key: 'conditions_utilisation', label: "Conditions d'utilisation des échantillons", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D'ÉCHANTILLOTHÈQUE (BIOTHÈQUE)</h1><p><strong>Biothèque :</strong> {{biotheque}}</p><p><strong>Déposant :</strong> {{depositaire}}</p><p><strong>Type d'échantillons :</strong> {{type_echantillons}}</p><p><strong>Date :</strong> {{date_contrat}}</p><h3>Conditions d'utilisation</h3><p>{{conditions_utilisation}}</p><h3>Éthique et consentement</h3><p>Tout usage secondaire des échantillons requiert l'approbation du CER et, selon les cas, un consentement additionnel des donneurs.</p></div>`,
  },
  {
    code: 'rech_rapport_cloture_essai',
    name: "Rapport de clôture essai clinique",
    category: 'sante',
    price: 7500,
    priceMax: 22000,
    description: "Rapport final de clôture d'un essai clinique résumant les résultats, déviations et leçons apprises.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'titre_essai', label: "Titre de l'essai", type: 'text', required: true },
      { key: 'date_cloture', label: "Date de clôture", type: 'date', required: true },
      { key: 'nombre_participants', label: "Nombre de participants inclus", type: 'text', required: true },
      { key: 'resultats_principaux', label: "Résultats principaux", type: 'textarea', required: true },
      { key: 'deviations_notables', label: "Déviations et problèmes notables", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE CLÔTURE — ESSAI CLINIQUE</h1><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date de clôture :</strong> {{date_cloture}}</p><p><strong>Participants inclus :</strong> {{nombre_participants}}</p><h3>Résultats principaux</h3><p>{{resultats_principaux}}</p><h3>Déviations et problèmes notables</h3><p>{{deviations_notables}}</p><h3>Archivage</h3><p>L'ensemble des documents essentiels de l'essai sera archivé conformément aux exigences BPC pour une durée minimale de 15 ans.</p></div>`,
  },
  {
    code: 'rech_accord_pasteur_ci',
    name: "Accord de partenariat Institut Pasteur Côte d'Ivoire",
    category: 'sante',
    price: 11000,
    priceMax: 36000,
    description: "Accord de collaboration scientifique avec l'Institut Pasteur de Côte d'Ivoire pour des activités de recherche conjointe.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'partenaire', label: "Partenaire institutionnel", type: 'text', required: true },
      { key: 'domaine_recherche', label: "Domaine de recherche", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'responsable_ci', label: "Responsable côté IPCI", type: 'text', required: true },
      { key: 'ressources_partagees', label: "Ressources et équipements partagés", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT — INSTITUT PASTEUR DE CÔTE D'IVOIRE</h1><p><strong>Partenaire :</strong> {{partenaire}}</p><p><strong>Responsable IPCI :</strong> {{responsable_ci}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Domaine de recherche</h3><p>{{domaine_recherche}}</p><h3>Ressources partagées</h3><p>{{ressources_partagees}}</p><h3>Gouvernance</h3><p>Un comité de pilotage se réunira trimestriellement pour évaluer l'avancement des activités et prendre les décisions stratégiques.</p></div>`,
  },
  {
    code: 'rech_charte_bpc',
    name: "Charte de bonne pratique clinique (BPC)",
    category: 'sante',
    price: 5000,
    priceMax: 15000,
    description: "Charte interne d'engagement aux bonnes pratiques cliniques pour toute l'équipe d'un essai clinique.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'etablissement', label: "Établissement ou équipe", type: 'text', required: true },
      { key: 'titre_essai', label: "Titre de l'essai concerné", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'engagement_specifique', label: "Engagements spécifiques de l'équipe", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE BONNE PRATIQUE CLINIQUE (BPC)</h1><p><strong>Établissement / Équipe :</strong> {{etablissement}}</p><p><strong>Essai :</strong> {{titre_essai}}</p><p><strong>Date :</strong> {{date_signature}}</p><h3>Principes BPC</h3><p>L'ensemble de l'équipe s'engage à respecter les 13 principes fondamentaux des BPC ICH E6, notamment la protection des droits, de la sécurité et du bien-être des participants, ainsi que la fiabilité des données générées.</p><h3>Engagements spécifiques</h3><p>{{engagement_specifique}}</p></div>`,
  },

  // ─── MATERNITÉ / PÉDIATRIE (mat_) ─────────────────────────────────────────
  {
    code: 'mat_dossier_grossesse',
    name: "Dossier de suivi de grossesse",
    category: 'sante',
    price: 3000,
    priceMax: 9000,
    description: "Dossier médical complet de suivi de grossesse, incluant antécédents, consultations prénatales et plan d'accouchement.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom de la patiente", type: 'text', required: true },
      { key: 'date_derniere_regles', label: "Date des dernières règles (DDR)", type: 'date', required: true },
      { key: 'date_accouchement_prevu', label: "Date d'accouchement prévue (DAP)", type: 'date', required: true },
      { key: 'antecedents_obstetricaux', label: "Antécédents obstétricaux", type: 'textarea', required: false },
      { key: 'groupe_sanguin', label: "Groupe sanguin et rhésus", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER DE SUIVI DE GROSSESSE</h1><p><strong>Patiente :</strong> {{nom_patiente}}</p><p><strong>DDR :</strong> {{date_derniere_regles}}</p><p><strong>DAP :</strong> {{date_accouchement_prevu}}</p><p><strong>Groupe sanguin :</strong> {{groupe_sanguin}}</p><h3>Antécédents obstétricaux</h3><p>{{antecedents_obstetricaux}}</p><h3>Suivi prénatal</h3><p>Consultations prénatales programmées au 1er, 4e, 6e, 8e et 9e mois. Échographies aux semaines 12, 22 et 32 d'aménorrhée.</p></div>`,
  },
  {
    code: 'mat_consultation_prenatale',
    name: "Formulaire de consultation prénatale",
    category: 'sante',
    price: 2000,
    priceMax: 6000,
    description: "Formulaire standardisé pour chaque consultation prénatale, consignant examen clinique et résultats biologiques.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 90,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom de la patiente", type: 'text', required: true },
      { key: 'date_consultation', label: "Date de la consultation", type: 'date', required: true },
      { key: 'terme_amenorrhee', label: "Terme en semaines d'aménorrhée", type: 'text', required: true },
      { key: 'poids', label: "Poids (kg)", type: 'text', required: true },
      { key: 'observations_cliniques', label: "Observations cliniques", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>FORMULAIRE DE CONSULTATION PRÉNATALE</h1><p><strong>Patiente :</strong> {{nom_patiente}}</p><p><strong>Date :</strong> {{date_consultation}}</p><p><strong>Terme :</strong> {{terme_amenorrhee}} SA</p><p><strong>Poids :</strong> {{poids}} kg</p><h3>Observations cliniques</h3><p>{{observations_cliniques}}</p><h3>Examens prescrits</h3><p>NFS, glycémie, ECBU, sérologie toxoplasmose/rubéole si nécessaire.</p></div>`,
  },
  {
    code: 'mat_plan_naissance',
    name: "Plan de naissance (birth plan)",
    category: 'sante',
    price: 2500,
    priceMax: 7000,
    description: "Document personnalisé exprimant les souhaits de la future mère concernant son accouchement et les soins du nouveau-né.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom de la future mère", type: 'text', required: true },
      { key: 'date_accouchement_prevu', label: "Date d'accouchement prévue", type: 'date', required: true },
      { key: 'souhaits_accouchement', label: "Souhaits pour l'accouchement", type: 'textarea', required: true },
      { key: 'souhaits_nouveau_ne', label: "Souhaits pour le nouveau-né", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>PLAN DE NAISSANCE</h1><p><strong>Future mère :</strong> {{nom_patiente}}</p><p><strong>Date prévue :</strong> {{date_accouchement_prevu}}</p><h3>Souhaits pour l'accouchement</h3><p>{{souhaits_accouchement}}</p><h3>Souhaits pour le nouveau-né</h3><p>{{souhaits_nouveau_ne}}</p><h3>Note</h3><p>Ce document exprime mes préférences et sera respecté dans la mesure du possible, sous réserve des impératifs médicaux.</p></div>`,
  },
  {
    code: 'mat_consentement_cesarienne',
    name: "Consentement césarienne",
    category: 'sante',
    price: 3500,
    priceMax: 10000,
    description: "Formulaire de consentement éclairé pour une intervention par césarienne, avec information sur les risques et alternatives.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom de la patiente", type: 'text', required: true },
      { key: 'indication_cesarienne', label: "Indication médicale", type: 'textarea', required: true },
      { key: 'chirurgien', label: "Chirurgien(ne)", type: 'text', required: true },
      { key: 'date_intervention', label: "Date de l'intervention prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONSENTEMENT ÉCLAIRÉ — CÉSARIENNE</h1><p>Je soussignée, <strong>{{nom_patiente}}</strong>, consens à l'intervention chirurgicale par césarienne réalisée par <strong>{{chirurgien}}</strong>, prévue le <strong>{{date_intervention}}</strong>.</p><h3>Indication médicale</h3><p>{{indication_cesarienne}}</p><h3>Risques et bénéfices</h3><p>J'ai été informée des risques liés à cette intervention (hémorragie, infection, complications anesthésiques) et de ses bénéfices, et j'ai pu poser toutes mes questions.</p><p>Signature : _____________________</p></div>`,
  },
  {
    code: 'mat_consentement_peridurale',
    name: "Consentement accouchement sous anesthésie péridurale",
    category: 'sante',
    price: 3000,
    priceMax: 9000,
    description: "Formulaire de consentement éclairé pour la pose d'une anesthésie péridurale lors de l'accouchement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom de la patiente", type: 'text', required: true },
      { key: 'anesthesiste', label: "Médecin anesthésiste", type: 'text', required: true },
      { key: 'date_pose', label: "Date de pose prévue", type: 'date', required: true },
      { key: 'informations_recues', label: "Informations reçues et questions posées", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CONSENTEMENT ÉCLAIRÉ — ANESTHÉSIE PÉRIDURALE</h1><p>Je soussignée, <strong>{{nom_patiente}}</strong>, consens à la pose d'une anesthésie péridurale par <strong>{{anesthesiste}}</strong>, le <strong>{{date_pose}}</strong>.</p><h3>Informations reçues</h3><p>{{informations_recues}}</p><h3>Risques expliqués</h3><p>J'ai été informée des risques potentiels (céphalées post-ponction, hypotension, échec partiel) et des alternatives disponibles.</p><p>Signature : _____________________</p></div>`,
  },
  {
    code: 'mat_consultation_postnatale',
    name: "Rapport de consultation post-natale",
    category: 'sante',
    price: 2500,
    priceMax: 7000,
    description: "Rapport de consultation post-natale de la mère à 6 semaines après l'accouchement.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom de la patiente", type: 'text', required: true },
      { key: 'date_accouchement', label: "Date d'accouchement", type: 'date', required: true },
      { key: 'date_consultation', label: "Date de la consultation post-natale", type: 'date', required: true },
      { key: 'etat_clinique', label: "État clinique et psychologique", type: 'textarea', required: true },
      { key: 'contraception_discutee', label: "Contraception discutée", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE CONSULTATION POST-NATALE</h1><p><strong>Patiente :</strong> {{nom_patiente}}</p><p><strong>Date d'accouchement :</strong> {{date_accouchement}}</p><p><strong>Date de consultation :</strong> {{date_consultation}}</p><h3>État clinique et psychologique</h3><p>{{etat_clinique}}</p><h3>Contraception</h3><p>{{contraception_discutee}}</p><h3>Recommandations</h3><p>Reprise du suivi gynécologique annuel préconisée. Frottis cervico-vaginal à programmer.</p></div>`,
  },
  {
    code: 'mat_suivi_nouveau_ne',
    name: "Fiche de suivi nouveau-né",
    category: 'sante',
    price: 2500,
    priceMax: 7000,
    description: "Fiche standardisée de surveillance du nouveau-né en salle de naissance et en maternité.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'nom_mere', label: "Nom de la mère", type: 'text', required: true },
      { key: 'date_naissance', label: "Date et heure de naissance", type: 'date', required: true },
      { key: 'poids_naissance', label: "Poids de naissance (g)", type: 'text', required: true },
      { key: 'score_apgar', label: "Score d'Apgar (1 et 5 min)", type: 'text', required: true },
      { key: 'observations', label: "Observations cliniques", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>FICHE DE SUIVI NOUVEAU-NÉ</h1><p><strong>Mère :</strong> {{nom_mere}}</p><p><strong>Date de naissance :</strong> {{date_naissance}}</p><p><strong>Poids :</strong> {{poids_naissance}} g</p><p><strong>Score d'Apgar :</strong> {{score_apgar}}</p><h3>Observations cliniques</h3><p>{{observations}}</p><h3>Soins immédiats</h3><p>Vitamine K1 (0,5 mg IM), collyre antibiotique, dépistage auditif néonatal et prélèvement pour dépistage néonatal.</p></div>`,
  },
  {
    code: 'mat_carnet_sante_enfant',
    name: "Carnet de santé de l'enfant (modèle)",
    category: 'sante',
    price: 3000,
    priceMax: 9000,
    description: "Modèle de carnet de santé pédiatrique adapté au calendrier vaccinal et au contexte sanitaire de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 91,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prénom de l'enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'nom_parents', label: "Noms des parents/tuteurs", type: 'text', required: true },
      { key: 'medecin_referent', label: "Médecin référent", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>CARNET DE SANTÉ DE L'ENFANT</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Né(e) le :</strong> {{date_naissance}}</p><p><strong>Parents / Tuteurs :</strong> {{nom_parents}}</p><p><strong>Médecin référent :</strong> {{medecin_referent}}</p><h3>Ce carnet</h3><p>Ce document doit être présenté à chaque consultation médicale et à l'entrée à l'école. Il contient le calendrier vaccinal, les courbes de croissance et le suivi du développement psychomoteur.</p></div>`,
  },
  {
    code: 'mat_programme_vaccination',
    name: "Programme de vaccination du nourrisson",
    category: 'sante',
    price: 2000,
    priceMax: 6000,
    description: "Programme de vaccination du nourrisson conforme au calendrier du Programme Élargi de Vaccination (PEV) de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'centre_vaccination', label: "Centre de vaccination", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PROGRAMME DE VACCINATION DU NOURRISSON</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Né(e) le :</strong> {{date_naissance}}</p><p><strong>Centre de vaccination :</strong> {{centre_vaccination}}</p><h3>Calendrier PEV Côte d'Ivoire</h3><ul><li>Naissance : BCG, polio oral</li><li>6 semaines : Pentavalent 1, Pneumo 1, Rotavirus 1, Polio oral</li><li>10 semaines : Pentavalent 2, Pneumo 2, Rotavirus 2</li><li>14 semaines : Pentavalent 3, Pneumo 3, IPV</li><li>9 mois : Rougeole, fièvre jaune</li></ul></div>`,
  },
  {
    code: 'mat_consultation_pediatrique',
    name: "Formulaire de consultation pédiatrique",
    category: 'sante',
    price: 2000,
    priceMax: 6000,
    description: "Formulaire de consultation pédiatrique standardisé pour nourrissons et jeunes enfants en structure de santé.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 87,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'age', label: "Âge de l'enfant", type: 'text', required: true },
      { key: 'date_consultation', label: "Date de consultation", type: 'date', required: true },
      { key: 'motif_consultation', label: "Motif de consultation", type: 'textarea', required: true },
      { key: 'examen_clinique', label: "Résultats de l'examen clinique", type: 'textarea', required: true },
      { key: 'prescription', label: "Prescription et conseils", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>FORMULAIRE DE CONSULTATION PÉDIATRIQUE</h1><p><strong>Enfant :</strong> {{nom_enfant}} — Âge : {{age}}</p><p><strong>Date :</strong> {{date_consultation}}</p><h3>Motif de consultation</h3><p>{{motif_consultation}}</p><h3>Examen clinique</h3><p>{{examen_clinique}}</p><h3>Prescription et conseils</h3><p>{{prescription}}</p></div>`,
  },
  {
    code: 'mat_suivi_croissance',
    name: "Fiche de suivi croissance enfant (courbe)",
    category: 'sante',
    price: 2500,
    priceMax: 7000,
    description: "Fiche de surveillance de la croissance staturo-pondérale de l'enfant selon les normes OMS.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'sexe', label: "Sexe de l'enfant", type: 'text', required: true },
      { key: 'mesures_recentes', label: "Dernières mesures (poids, taille, PC)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE SUIVI DE CROISSANCE</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Né(e) le :</strong> {{date_naissance}}</p><p><strong>Sexe :</strong> {{sexe}}</p><h3>Mesures récentes</h3><p>{{mesures_recentes}}</p><h3>Interprétation</h3><p>Comparaison aux courbes de référence OMS. Un Z-score inférieur à -2 pour le rapport poids/taille indique une malnutrition aiguë.</p></div>`,
  },
  {
    code: 'mat_consentement_acte_mineur',
    name: "Consentement pour acte médical sur mineur",
    category: 'sante',
    price: 3000,
    priceMax: 9000,
    description: "Formulaire de consentement parental ou tutoral pour tout acte médical ou chirurgical pratiqué sur un enfant mineur.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prénom de l'enfant", type: 'text', required: true },
      { key: 'nom_parent_tuteur', label: "Nom du parent ou tuteur légal", type: 'text', required: true },
      { key: 'acte_medical', label: "Description de l'acte médical", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONSENTEMENT POUR ACTE MÉDICAL SUR MINEUR</h1><p>Je soussigné(e), <strong>{{nom_parent_tuteur}}</strong>, parent / tuteur légal de l'enfant <strong>{{nom_enfant}}</strong>, consens à l'acte médical suivant :</p><h3>Acte médical</h3><p>{{acte_medical}}</p><p>J'ai reçu une information claire sur les bénéfices, les risques et les alternatives, et j'ai pu poser toutes mes questions.</p><p><strong>Date :</strong> {{date_signature}}</p><p>Signature : _____________________</p></div>`,
  },
  {
    code: 'mat_accord_pediatrie_specialisee',
    name: "Accord de prise en charge pédiatrique spécialisée",
    category: 'sante',
    price: 5000,
    priceMax: 15000,
    description: "Accord de prise en charge entre famille et service de pédiatrie spécialisée (cardiologie, neurologie, oncologie pédiatrique).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'specialite', label: "Spécialité pédiatrique", type: 'text', required: true },
      { key: 'etablissement', label: "Établissement de prise en charge", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'plan_therapeutique', label: "Plan thérapeutique résumé", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRISE EN CHARGE PÉDIATRIQUE SPÉCIALISÉE</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Spécialité :</strong> {{specialite}}</p><p><strong>Établissement :</strong> {{etablissement}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Plan thérapeutique</h3><p>{{plan_therapeutique}}</p><h3>Coordination</h3><p>Un médecin référent sera désigné pour coordonner la prise en charge et assurer le lien avec le médecin traitant.</p></div>`,
  },
  {
    code: 'mat_rapport_puericulture',
    name: "Rapport de consultation de puériculture",
    category: 'sante',
    price: 2000,
    priceMax: 6000,
    description: "Rapport de consultation de puériculture documentant développement, alimentation et hygiène de vie du nourrisson.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'age_mois', label: "Âge (mois)", type: 'text', required: true },
      { key: 'date_consultation', label: "Date de consultation", type: 'date', required: true },
      { key: 'observations_developpement', label: "Observations sur le développement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE CONSULTATION DE PUÉRICULTURE</h1><p><strong>Enfant :</strong> {{nom_enfant}} — {{age_mois}} mois</p><p><strong>Date :</strong> {{date_consultation}}</p><h3>Développement psychomoteur</h3><p>{{observations_developpement}}</p><h3>Conseils</h3><p>Diversification alimentaire, stimulations sensorielles adaptées à l'âge, prévention des accidents domestiques.</p></div>`,
  },
  {
    code: 'mat_accord_neonatologie',
    name: "Accord de service de néonatologie (prématurés)",
    category: 'sante',
    price: 6000,
    priceMax: 18000,
    description: "Accord de prise en charge d'un nouveau-né prématuré en service de néonatologie, signé par les parents.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'nom_nouveau_ne', label: "Nom du nouveau-né", type: 'text', required: true },
      { key: 'terme_naissance', label: "Terme à la naissance (SA)", type: 'text', required: true },
      { key: 'date_admission', label: "Date d'admission en néonatologie", type: 'date', required: true },
      { key: 'parents_tuteurs', label: "Noms des parents/tuteurs", type: 'text', required: true },
      { key: 'plan_soins', label: "Plan de soins initial", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRISE EN CHARGE EN NÉONATOLOGIE</h1><p><strong>Nouveau-né :</strong> {{nom_nouveau_ne}}</p><p><strong>Terme :</strong> {{terme_naissance}} SA</p><p><strong>Date d'admission :</strong> {{date_admission}}</p><p><strong>Parents / Tuteurs :</strong> {{parents_tuteurs}}</p><h3>Plan de soins initial</h3><p>{{plan_soins}}</p><h3>Information</h3><p>Les parents seront informés quotidiennement de l'évolution de leur enfant et encouragés à pratiquer le peau à peau (méthode kangourou).</p></div>`,
  },
  {
    code: 'mat_contrat_sage_femme',
    name: "Contrat de sage-femme libérale",
    category: 'sante',
    price: 5000,
    priceMax: 14000,
    description: "Contrat de prestation entre une sage-femme libérale et sa patiente, couvrant suivi prénatal et post-natal.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'nom_sage_femme', label: "Nom de la sage-femme", type: 'text', required: true },
      { key: 'nom_patiente', label: "Nom de la patiente", type: 'text', required: true },
      { key: 'prestations', label: "Prestations prévues", type: 'textarea', required: true },
      { key: 'date_debut_suivi', label: "Date de début du suivi", type: 'date', required: true },
      { key: 'honoraires', label: "Honoraires convenus (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SAGE-FEMME LIBÉRALE</h1><p>Entre <strong>{{nom_sage_femme}}</strong>, sage-femme libérale, et <strong>{{nom_patiente}}</strong>.</p><p><strong>Début du suivi :</strong> {{date_debut_suivi}}</p><h3>Prestations prévues</h3><p>{{prestations}}</p><p><strong>Honoraires :</strong> {{honoraires}} FCFA</p><h3>Obligations</h3><p>La sage-femme s'engage à assurer un suivi de qualité conforme aux recommandations professionnelles et à orienter vers un médecin spécialiste en cas de complication.</p></div>`,
  },
  {
    code: 'mat_accord_maternite_niveau3',
    name: "Accord de service de maternité de niveau III",
    category: 'sante',
    price: 8000,
    priceMax: 24000,
    description: "Accord de prise en charge dans une maternité de référence de niveau III pour grossesse à haut risque.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom de la patiente", type: 'text', required: true },
      { key: 'etablissement', label: "Maternité de niveau III", type: 'text', required: true },
      { key: 'facteurs_risque', label: "Facteurs de risque identifiés", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRISE EN CHARGE — MATERNITÉ DE NIVEAU III</h1><p><strong>Patiente :</strong> {{nom_patiente}}</p><p><strong>Établissement :</strong> {{etablissement}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Facteurs de risque</h3><p>{{facteurs_risque}}</p><h3>Organisation de la prise en charge</h3><p>Une équipe pluridisciplinaire (obstétricien, anesthésiste, néonatologiste) sera mobilisée pour assurer une prise en charge optimale de la mère et du nouveau-né.</p></div>`,
  },
  {
    code: 'mat_accord_partenariat_ong',
    name: "Accord de partenariat maternité-ONG",
    category: 'sante',
    price: 7000,
    priceMax: 21000,
    description: "Convention de partenariat entre une maternité et une ONG pour améliorer la santé maternelle en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 54,
    fieldsJson: F([
      { key: 'maternite', label: "Maternité partenaire", type: 'text', required: true },
      { key: 'ong', label: "ONG partenaire", type: 'text', required: true },
      { key: 'objectifs_partenariat', label: "Objectifs du partenariat", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'contributions', label: "Contributions respectives", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT MATERNITÉ — ONG</h1><p><strong>Maternité :</strong> {{maternite}}</p><p><strong>ONG :</strong> {{ong}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Objectifs</h3><p>{{objectifs_partenariat}}</p><h3>Contributions respectives</h3><p>{{contributions}}</p><h3>Durée</h3><p>Le présent accord est conclu pour une durée de 2 ans renouvelable par accord exprès des deux parties.</p></div>`,
  },
  {
    code: 'mat_plan_depistage_neonatal',
    name: "Plan de dépistage néonatal (tests de Guthrie)",
    category: 'sante',
    price: 4000,
    priceMax: 12000,
    description: "Plan opérationnel de mise en oeuvre du dépistage néonatal élargi (phénylcétonurie, hypothyroïdie, drépanocytose).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'etablissement', label: "Établissement de santé", type: 'text', required: true },
      { key: 'maladies_depistees', label: "Maladies dépistées", type: 'textarea', required: true },
      { key: 'laboratoire_reference', label: "Laboratoire de référence", type: 'text', required: true },
      { key: 'date_mise_en_oeuvre', label: "Date de mise en oeuvre", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉPISTAGE NÉONATAL</h1><p><strong>Établissement :</strong> {{etablissement}}</p><p><strong>Laboratoire de référence :</strong> {{laboratoire_reference}}</p><p><strong>Date de mise en oeuvre :</strong> {{date_mise_en_oeuvre}}</p><h3>Maladies dépistées</h3><p>{{maladies_depistees}}</p><h3>Procédure</h3><p>Prélèvement sur papier buvard (test de Guthrie) entre J2 et J4 de vie, après 48h d'alimentation lactée. Les résultats positifs déclenchent une procédure de rappel rapide.</p></div>`,
  },
  {
    code: 'mat_accord_lactation',
    name: "Accord de service de lactation (allaitement maternel)",
    category: 'sante',
    price: 3500,
    priceMax: 10000,
    description: "Accord de suivi par une consultante en lactation pour soutenir l'allaitement maternel exclusif.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'nom_mere', label: "Nom de la mère", type: 'text', required: true },
      { key: 'consultante_lactation', label: "Consultante en lactation (IBCLC)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début d'accompagnement", type: 'date', required: true },
      { key: 'difficultes_rencontrees', label: "Difficultés rencontrées", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE LACTATION</h1><p><strong>Mère :</strong> {{nom_mere}}</p><p><strong>Consultante IBCLC :</strong> {{consultante_lactation}}</p><p><strong>Date de début :</strong> {{date_debut}}</p><h3>Difficultés rencontrées</h3><p>{{difficultes_rencontrees}}</p><h3>Objectif</h3><p>Soutenir l'allaitement maternel exclusif jusqu'à 6 mois et l'allaitement complémentaire jusqu'à 2 ans, conformément aux recommandations de l'OMS et de l'UNICEF.</p></div>`,
  },
  {
    code: 'mat_signalement_enfant_danger',
    name: "Fiche de signalement enfant en danger (pédiatrie)",
    category: 'sante',
    price: 3000,
    priceMax: 9000,
    description: "Fiche de signalement aux autorités compétentes d'un enfant en situation de danger ou de maltraitance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'age_enfant', label: "Âge de l'enfant", type: 'text', required: true },
      { key: 'nature_danger', label: "Nature du danger ou de la maltraitance suspectée", type: 'textarea', required: true },
      { key: 'date_signalement', label: "Date du signalement", type: 'date', required: true },
      { key: 'auteur_signalement', label: "Professionnel auteur du signalement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE SIGNALEMENT — ENFANT EN DANGER</h1><p><strong>Enfant :</strong> {{nom_enfant}} — Âge : {{age_enfant}}</p><p><strong>Date :</strong> {{date_signalement}}</p><p><strong>Auteur du signalement :</strong> {{auteur_signalement}}</p><h3>Nature du danger</h3><p>{{nature_danger}}</p><h3>Destinataires</h3><p>Ce signalement est adressé au Procureur de la République compétent et à la Direction Régionale de la Santé, conformément aux dispositions légales de protection de l'enfance en Côte d'Ivoire.</p></div>`,
  },
  {
    code: 'mat_prise_en_charge_malnutrition',
    name: "Accord de prise en charge nutrition infantile (malnutrition)",
    category: 'sante',
    price: 4000,
    priceMax: 12000,
    description: "Accord de prise en charge nutritionnelle d'un enfant souffrant de malnutrition aiguë modérée ou sévère.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'type_malnutrition', label: "Type de malnutrition (MAS/MAM)", type: 'text', required: true },
      { key: 'centre_prise_en_charge', label: "Centre de prise en charge", type: 'text', required: true },
      { key: 'date_admission', label: "Date d'admission", type: 'date', required: true },
      { key: 'protocole_therapeutique', label: "Protocole thérapeutique (ATPE, F-75, F-100)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRISE EN CHARGE — NUTRITION INFANTILE</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Type de malnutrition :</strong> {{type_malnutrition}}</p><p><strong>Centre :</strong> {{centre_prise_en_charge}}</p><p><strong>Date d'admission :</strong> {{date_admission}}</p><h3>Protocole thérapeutique</h3><p>{{protocole_therapeutique}}</p><h3>Suivi</h3><p>Pesée hebdomadaire, évaluation du gain de poids et de l'appétit. Objectif : gain pondéral supérieur à 8 g/kg/jour.</p></div>`,
  },
  {
    code: 'mat_rapport_performance_maternite',
    name: "Rapport de performance maternité",
    category: 'sante',
    price: 5000,
    priceMax: 15000,
    description: "Rapport trimestriel ou annuel d'indicateurs de performance d'un service de maternité (mortalité, accouchements, césariennes).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'etablissement', label: "Établissement", type: 'text', required: true },
      { key: 'periode', label: "Période du rapport", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'indicateurs_cles', label: "Indicateurs clés (accouchements, taux de césarienne, décès maternels)", type: 'textarea', required: true },
      { key: 'analyse_tendances', label: "Analyse des tendances et recommandations", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE — MATERNITÉ</h1><p><strong>Établissement :</strong> {{etablissement}}</p><p><strong>Période :</strong> {{periode}}</p><p><strong>Date :</strong> {{date_rapport}}</p><h3>Indicateurs clés</h3><p>{{indicateurs_cles}}</p><h3>Analyse et recommandations</h3><p>{{analyse_tendances}}</p><h3>Référence</h3><p>Les indicateurs sont comparés aux cibles nationales du Plan National de Développement Sanitaire (PNDS) de Côte d'Ivoire.</p></div>`,
  },
  {
    code: 'mat_plan_mortalite_maternelle',
    name: "Plan de lutte contre la mortalité maternelle",
    category: 'sante',
    price: 8000,
    priceMax: 24000,
    description: "Plan d'action institutionnel pour la réduction de la mortalité maternelle dans un district ou établissement de santé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'structure_responsable', label: "Structure responsable", type: 'text', required: true },
      { key: 'zone_couverture', label: "Zone de couverture", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption du plan", type: 'date', required: true },
      { key: 'objectifs_chiffres', label: "Objectifs chiffrés de réduction (Ratio MM)", type: 'textarea', required: true },
      { key: 'axes_strategiques', label: "Axes stratégiques d'intervention", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE LUTTE CONTRE LA MORTALITÉ MATERNELLE</h1><p><strong>Structure :</strong> {{structure_responsable}}</p><p><strong>Zone :</strong> {{zone_couverture}}</p><p><strong>Date d'adoption :</strong> {{date_adoption}}</p><h3>Objectifs chiffrés</h3><p>{{objectifs_chiffres}}</p><h3>Axes stratégiques</h3><p>{{axes_strategiques}}</p><h3>Alignement</h3><p>Ce plan s'inscrit dans le cadre des ODD 3 (santé) et des objectifs du Plan National de Développement Sanitaire de Côte d'Ivoire pour réduire le ratio de mortalité maternelle en dessous de 300 pour 100 000 naissances vivantes.</p></div>`,
  },
  {
    code: 'mat_charte_bientraitance_enfant',
    name: "Charte de bientraitance de l'enfant à l'hôpital",
    category: 'sante',
    price: 3000,
    priceMax: 9000,
    description: "Charte d'engagement institutionnel pour la bientraitance et le respect des droits de l'enfant hospitalisé.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'etablissement', label: "Établissement de santé", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption de la charte", type: 'date', required: true },
      { key: 'directeur_etablissement', label: "Directeur de l'établissement", type: 'text', required: true },
      { key: 'engagements_specifiques', label: "Engagements spécifiques de l'établissement", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE BIENTRAITANCE DE L'ENFANT À L'HÔPITAL</h1><p><strong>Établissement :</strong> {{etablissement}}</p><p><strong>Directeur :</strong> {{directeur_etablissement}}</p><p><strong>Date d'adoption :</strong> {{date_adoption}}</p><h3>Principes fondamentaux</h3><ul><li>Respect de la dignité et de l'intimité de l'enfant</li><li>Droit à l'information adaptée à son âge</li><li>Présence et soutien des parents à toute heure</li><li>Prise en charge de la douleur comme priorité</li><li>Accès à l'éducation et au jeu pendant l'hospitalisation</li></ul><h3>Engagements spécifiques</h3><p>{{engagements_specifiques}}</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 52a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
