import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ── 25 templates Médecine / Chirurgie dentaire (med4_) ──────────────────────
  {
    code: 'med4_consultation',
    name: "Accord de service de consultation dentaire",
    category: 'sante', price: 2000, priceMax: 6000,
    description: "Accord encadrant la consultation dentaire initiale, l'examen clinique et le devis de traitement.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 72,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance du patient", type: 'date', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_consultation', label: "Date de la consultation", type: 'date', required: true },
      { key: 'observations', label: "Observations cliniques", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CONSULTATION DENTAIRE</h1><p>Entre le cabinet dentaire <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>, né(e) le {{date_naissance}}.</p><p>Date de la consultation : {{date_consultation}}.</p><h2>Objet</h2><p>Le présent accord définit les conditions de la consultation dentaire initiale comprenant l'examen clinique complet, l'interrogatoire médical et l'établissement d'un plan de traitement.</p><h2>Engagements du praticien</h2><p>Le praticien s'engage à réaliser un examen rigoureux, à informer le patient de son état bucco-dentaire et à lui remettre un devis détaillé.</p><h2>Observations</h2><p>{{observations}}</p><p>Fait à Abidjan, le {{date_consultation}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_detartrage',
    name: "Accord de service de détartrage et polissage (prophylaxie)",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la réalisation d'un détartrage supra et sous-gingival suivi d'un polissage dentaire.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 68,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_soin', label: "Date du soin", type: 'date', required: true },
      { key: 'tarif', label: "Tarif convenu (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DÉTARTRAGE ET POLISSAGE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Date du soin : {{date_soin}}. Tarif convenu : <strong>{{tarif}} FCFA</strong>.</p><h2>Description de l'acte</h2><p>Le présent accord porte sur la réalisation d'un détartrage supra et sous-gingival à l'aide d'ultrasons et de curettes, suivi d'un polissage coronaire avec une pâte prophylactique, dans le but de prévenir les maladies parodontales.</p><h2>Recommandations post-soin</h2><p>Le patient s'engage à respecter les consignes d'hygiène bucco-dentaire communiquées par le praticien et à se présenter aux contrôles périodiques recommandés.</p><p>Fait à Abidjan, le {{date_soin}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_extraction',
    name: "Accord de service d'extraction dentaire",
    category: 'sante', price: 3000, priceMax: 8000,
    description: "Consentement éclairé et accord de service pour l'extraction d'une ou plusieurs dents.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 75,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'dent_concernee', label: "Dent(s) concernée(s) (numéro ou description)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_intervention', label: "Date de l'intervention", type: 'date', required: true },
      { key: 'antecedents', label: "Antécédents médicaux pertinents", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'EXTRACTION DENTAIRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Dent(s) concernée(s) : <strong>{{dent_concernee}}</strong>. Date prévue : {{date_intervention}}.</p><h2>Information préalable</h2><p>Le praticien a informé le patient des indications, des risques (douleur post-opératoire, infection, alvéolite sèche, lésion nerveuse rare) et des alternatives thérapeutiques avant toute extraction.</p><h2>Antécédents médicaux</h2><p>{{antecedents}}</p><h2>Consentement</h2><p>Le patient reconnaît avoir reçu une information complète et consent librement à l'acte d'extraction. Il s'engage à respecter les prescriptions post-opératoires.</p><p>Fait à Abidjan, le {{date_intervention}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_soins_canalaires',
    name: "Accord de service de soins canalaires (traitement de canal)",
    category: 'sante', price: 4000, priceMax: 12000,
    description: "Accord pour la réalisation d'un traitement endodontique (dévitalisation et obturation canalaire).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'dent_traitee', label: "Dent traitée (numéro ou description)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
      { key: 'nombre_seances', label: "Nombre de séances prévues", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SOINS CANALAIRES</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Dent concernée : <strong>{{dent_traitee}}</strong>. Début du traitement : {{date_debut}}. Séances prévues : <strong>{{nombre_seances}}</strong>.</p><h2>Description</h2><p>Le traitement endodontique comprend l'élimination de la pulpe infectée ou nécrotique, le nettoyage et la mise en forme des canaux radiculaires, puis leur obturation hermétique à la gutta-percha.</p><h2>Engagements</h2><p>Le praticien s'engage à réaliser chaque séance avec soin et à contrôler le résultat radiographique. Le patient s'engage à se présenter à l'ensemble des séances et à éviter de mâcher du côté traité entre les séances.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_couronne',
    name: "Accord de service de pose de couronne dentaire",
    category: 'sante', price: 5000, priceMax: 15000,
    description: "Accord pour la préparation et la pose d'une couronne dentaire prothétique.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 66,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'dent_concernee', label: "Dent concernée (numéro)", type: 'text', required: true },
      { key: 'materiau', label: "Matériau de la couronne (céramique, métal-céramique, zircone)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_empreinte', label: "Date de l'empreinte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POSE DE COURONNE DENTAIRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Dent concernée : <strong>{{dent_concernee}}</strong>. Matériau : <strong>{{materiau}}</strong>. Date d'empreinte : {{date_empreinte}}.</p><h2>Protocole</h2><p>L'acte comprend la taille de la dent support, la prise d'empreintes, la réalisation prothétique en laboratoire, l'essayage et le scellement définitif de la couronne.</p><h2>Garantie</h2><p>La couronne est garantie contre les défauts de fabrication pour une durée de deux ans à compter du scellement, sous réserve d'une hygiène bucco-dentaire correcte et des contrôles annuels.</p><p>Fait à Abidjan, le {{date_empreinte}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_bridge',
    name: "Accord de service de pose de bridge dentaire",
    category: 'sante', price: 6000, priceMax: 18000,
    description: "Accord pour la réalisation et la pose d'un bridge dentaire fixe sur dents piliers.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'dents_piliers', label: "Dents piliers (numéros)", type: 'text', required: true },
      { key: 'nombre_elements', label: "Nombre d'éléments du bridge", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_preparation', label: "Date de préparation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POSE DE BRIDGE DENTAIRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Dents piliers : <strong>{{dents_piliers}}</strong>. Éléments : <strong>{{nombre_elements}}</strong>. Date de préparation : {{date_preparation}}.</p><h2>Description</h2><p>Le bridge est une prothèse fixe ancrée sur les dents piliers taillées, permettant de remplacer une ou plusieurs dents absentes par une ou plusieurs facettes inter-dents (pontique).</p><h2>Soins préalables</h2><p>Tout soin dentaire nécessaire sur les dents piliers (dépulpation, traitement parodontal) sera réalisé avant la pose du bridge. Le patient en a été informé et donne son accord.</p><p>Fait à Abidjan, le {{date_preparation}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_implant',
    name: "Accord de service de pose d'implant dentaire",
    category: 'sante', price: 8000, priceMax: 24000,
    description: "Consentement éclairé et accord pour la chirurgie implantaire et la restauration prothétique.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'site_implant', label: "Site d'implantation (numéro de dent manquante)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_chirurgie', label: "Date de la chirurgie", type: 'date', required: true },
      { key: 'contre_indications', label: "Contre-indications connues (diabète non équilibré, tabac, etc.)", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POSE D'IMPLANT DENTAIRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Site d'implantation : <strong>{{site_implant}}</strong>. Date de chirurgie : {{date_chirurgie}}.</p><h2>Risques et contre-indications</h2><p>Le patient a été informé des risques (échec d'ostéo-intégration, infection, lésion nerveuse, sinusite) et des contre-indications relatives. Contre-indications déclarées : {{contre_indications}}.</p><h2>Protocole en deux temps</h2><p>La chirurgie d'insertion de l'implant en titane est suivie d'une période d'ostéo-intégration (3 à 6 mois) avant la pose de la couronne prothétique définitive.</p><p>Fait à Abidjan, le {{date_chirurgie}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_prothese_amovible',
    name: "Accord de service de pose de prothèse amovible (dentier)",
    category: 'sante', price: 4000, priceMax: 12000,
    description: "Accord pour la réalisation et la pose d'une prothèse amovible partielle ou complète.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 64,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'type_prothese', label: "Type de prothèse (partielle / complète)", type: 'text', required: true },
      { key: 'arcade', label: "Arcade concernée (maxillaire / mandibulaire / les deux)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_empreinte', label: "Date de l'empreinte primaire", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POSE DE PROTHÈSE AMOVIBLE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Type : <strong>{{type_prothese}}</strong>. Arcade : <strong>{{arcade}}</strong>. Date d'empreinte : {{date_empreinte}}.</p><h2>Étapes de réalisation</h2><p>Les étapes comprennent : empreinte primaire, empreinte secondaire, enregistrement des rapports intermaxillaires, essayage des dents en cire, livraison et adaptation.</p><h2>Entretien</h2><p>Le patient s'engage à entretenir sa prothèse selon les consignes fournies (nettoyage quotidien, conserve dans l'eau la nuit) et à se présenter aux contrôles de suivi.</p><p>Fait à Abidjan, le {{date_empreinte}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_prothese_totale',
    name: "Accord de service de pose de prothèse totale",
    category: 'sante', price: 5000, priceMax: 14000,
    description: "Accord pour la réalisation d'une prothèse totale bimaxillaire chez le patient édenté.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 61,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du protocole", type: 'date', required: true },
      { key: 'teinte_choisie', label: "Teinte et forme des dents prothétiques", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POSE DE PROTHÈSE TOTALE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Début du protocole : {{date_debut}}. Teinte / forme choisie : <strong>{{teinte_choisie}}</strong>.</p><h2>Protocole</h2><p>La réalisation d'une prothèse totale comprend plusieurs séances : empreintes primaires et secondaires, enregistrement de l'occlusion, essayage esthétique et fonctionnel, puis livraison avec explications d'adaptation progressive.</p><h2>Période d'adaptation</h2><p>Un délai d'adaptation de deux à quatre semaines est prévisible. Des retouches d'occlusion sont incluses dans le tarif pendant les 30 premiers jours.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_chirurgie_orale',
    name: "Accord de service de chirurgie orale (kyste, dent de sagesse)",
    category: 'sante', price: 4000, priceMax: 12000,
    description: "Consentement et accord pour une intervention de chirurgie orale (kyste, dent incluse ou semi-incluse).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'type_intervention', label: "Nature de l'intervention (kyste / dent de sagesse / autre)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_intervention', label: "Date de l'intervention", type: 'date', required: true },
      { key: 'risques_specifiques', label: "Risques spécifiques communiqués au patient", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CHIRURGIE ORALE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Nature de l'intervention : <strong>{{type_intervention}}</strong>. Date : {{date_intervention}}.</p><h2>Information et consentement</h2><p>Le praticien a exposé au patient l'indication chirurgicale, le déroulement de l'acte sous anesthésie locale, les suites opératoires prévisibles (œdème, trismus, douleur) et les risques spécifiques mentionnés ci-après : {{risques_specifiques}}.</p><h2>Instructions post-opératoires</h2><p>Le patient s'engage à respecter les prescriptions médicamenteuses, à éviter tabac et alimentation chaude pendant 48 heures et à contacter le cabinet en cas de complications.</p><p>Fait à Abidjan, le {{date_intervention}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_orthodontie_bagues',
    name: "Accord de service de pose d'appareillage orthodontique (bagues)",
    category: 'sante', price: 6000, priceMax: 20000,
    description: "Accord pour le traitement orthodontique multi-bagues fixe avec suivi mensuel.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'nom_parent', label: "Nom du représentant légal (si mineur)", type: 'text', required: false },
      { key: 'nom_cabinet', label: "Nom du cabinet d'orthodontie", type: 'text', required: true },
      { key: 'date_pose', label: "Date de pose des bagues", type: 'date', required: true },
      { key: 'duree_traitement', label: "Durée estimée du traitement (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'APPAREILLAGE ORTHODONTIQUE (BAGUES)</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong> (représentant légal : {{nom_parent}} si mineur).</p><p>Date de pose : {{date_pose}}. Durée estimée : <strong>{{duree_traitement}} mois</strong>.</p><h2>Contenu du traitement</h2><p>Le traitement comprend la pose de brackets métalliques ou esthétiques, les activations mensuelles, les fils et élastiques, ainsi que la contention finale. Les consultations de suivi mensuel sont incluses.</p><h2>Obligations du patient</h2><p>Hygiène rigoureuse autour des brackets, respect des rendez-vous, port des élastiques inter-mâchoires selon prescription et signalement immédiat de tout bracket décollé.</p><p>Fait à Abidjan, le {{date_pose}}.</p><p>Signature du patient / représentant : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_gouttiere_alignement',
    name: "Accord de service d'alignement dental (gouttière)",
    category: 'sante', price: 7000, priceMax: 22000,
    description: "Accord pour un traitement orthodontique par gouttières transparentes thermoformées.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'nombre_gouttières', label: "Nombre de gouttières prévues", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ALIGNEMENT DENTAL PAR GOUTTIÈRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Nombre de gouttières : <strong>{{nombre_gouttières}}</strong>. Début : {{date_debut}}.</p><h2>Principe du traitement</h2><p>Le traitement par gouttières transparentes successives déplace progressivement les dents. Chaque gouttière est portée 20 à 22 heures par jour et changée toutes les deux semaines selon le protocole établi.</p><h2>Responsabilité du patient</h2><p>Le patient est responsable du port régulier des gouttières. Un non-respect des durées de port peut compromettre le résultat et entraîner des surcoûts. Les gouttières perdues ou cassées sont refacturées.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_blanchiment',
    name: "Accord de service de blanchiment dentaire",
    category: 'sante', price: 3000, priceMax: 9000,
    description: "Accord pour un traitement de blanchiment dentaire professionnel en cabinet ou ambulatoire.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'methode', label: "Méthode choisie (cabinet / gouttières ambulatoires / combinée)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_seance', label: "Date de la séance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE BLANCHIMENT DENTAIRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Méthode : <strong>{{methode}}</strong>. Date : {{date_seance}}.</p><h2>Information préalable</h2><p>Le patient a été informé que le blanchiment concerne uniquement les dents naturelles et non les restaurations existantes (couronnes, facettes, composites). Des sensibilités transitoires sont possibles après la séance.</p><h2>Contre-indications</h2><p>Femme enceinte ou allaitante, patient mineur de moins de 16 ans, sensibilités dentinaires sévères non traitées. Le patient atteste n'être concerné par aucune de ces contre-indications.</p><p>Fait à Abidjan, le {{date_seance}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_facettes',
    name: "Accord de service de pose de facettes dentaires",
    category: 'sante', price: 5000, priceMax: 16000,
    description: "Accord pour la réalisation et la pose de facettes dentaires en céramique ou composite.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'nombre_facettes', label: "Nombre de facettes prévues", type: 'text', required: true },
      { key: 'materiau', label: "Matériau (céramique / composite)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_prep', label: "Date de préparation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POSE DE FACETTES DENTAIRES</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Facettes : <strong>{{nombre_facettes}}</strong>. Matériau : <strong>{{materiau}}</strong>. Date de préparation : {{date_prep}}.</p><h2>Description</h2><p>Les facettes sont de fines coques adhérées à la surface des dents pour en améliorer la couleur, la forme ou la longueur. Une préparation minimale de l'émail peut être nécessaire.</p><h2>Durée de vie et entretien</h2><p>La durée de vie prévisionnelle est de 8 à 15 ans selon l'hygiène bucco-dentaire et l'absence de parafonctions (bruxisme, onycophagie). Le patient accepte de porter une gouttière de protection nocturne si recommandée.</p><p>Fait à Abidjan, le {{date_prep}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_parodontologie',
    name: "Accord de service de parodontologie (traitement des gencives)",
    category: 'sante', price: 3500, priceMax: 10000,
    description: "Accord pour le traitement des maladies parodontales (gingivite, parodontite).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'diagnostic', label: "Diagnostic parodontal (gingivite / parodontite légère-modérée-sévère)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PARODONTOLOGIE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Diagnostic : <strong>{{diagnostic}}</strong>. Début du traitement : {{date_debut}}.</p><h2>Plan de traitement</h2><p>Le traitement parodontal comprend : motivation et instruction à l'hygiène, détartrage supra-gingival, surfaçage radiculaire (curetage) sous anesthésie locale, et ré-évaluation à 6-8 semaines. Une phase chirurgicale complémentaire peut être nécessaire selon la réponse clinique.</p><h2>Facteurs de risque</h2><p>Le patient s'engage à arrêter ou réduire le tabagisme et à contrôler son diabète si applicable, ces facteurs aggravant significativement le pronostic parodontal.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_radiographie',
    name: "Accord de service de radiographie dentaire (panoramique)",
    category: 'sante', price: 2000, priceMax: 5000,
    description: "Accord pour la réalisation d'un orthopantomogramme (panoramique dentaire) ou de clichés rétro-alvéolaires.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 71,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'type_radio', label: "Type de radiographie (panoramique / rétro-alvéolaire / cone beam)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_examen', label: "Date de l'examen", type: 'date', required: true },
      { key: 'grossesse', label: "Patiente enceinte ? (oui / non)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE RADIOGRAPHIE DENTAIRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Type d'examen : <strong>{{type_radio}}</strong>. Date : {{date_examen}}. Grossesse déclarée : <strong>{{grossesse}}</strong>.</p><h2>Information sur les rayonnements</h2><p>Les doses de rayonnements utilisées en radiologie dentaire sont très faibles et les équipements sont conformes aux normes en vigueur. En cas de grossesse avérée, un tablier plombé sera systématiquement utilisé ou l'examen différé si possible.</p><h2>Conservation des clichés</h2><p>Les images radiographiques sont conservées dans le dossier médical du patient pour une durée minimale de 10 ans conformément à la réglementation.</p><p>Fait à Abidjan, le {{date_examen}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_xerostomie',
    name: "Accord de service de traitement de la xérostomie (bouche sèche)",
    category: 'sante', price: 2000, priceMax: 6000,
    description: "Accord pour la prise en charge de la xérostomie chronique et la prévention des caries associées.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 55,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'cause_suspectee', label: "Cause suspectée (médicaments, radiothérapie, maladie systémique)", type: 'textarea', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_prise_en_charge', label: "Date de prise en charge", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TRAITEMENT DE LA XÉROSTOMIE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Cause suspectée : {{cause_suspectee}}. Date de prise en charge : {{date_prise_en_charge}}.</p><h2>Protocole de traitement</h2><p>La prise en charge comprend : bilan salivaire, fluorothérapie intensive, substituts salivaires, conseils diététiques et suivi rapproché (tous les 3 mois) pour prévenir les caries cervicales liées à l'hyposialie.</p><h2>Coordination médicale</h2><p>Le praticien pourra adresser le patient à son médecin traitant pour réévaluer les traitements médicamenteux éventuellement responsables.</p><p>Fait à Abidjan, le {{date_prise_en_charge}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_bruxisme',
    name: "Accord de service de traitement des bruxismes (gouttière)",
    category: 'sante', price: 3000, priceMax: 8000,
    description: "Accord pour la confection d'une gouttière occlusale de protection contre le bruxisme nocturne.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'type_bruxisme', label: "Type (nocturne / diurne / les deux)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_empreinte', label: "Date de l'empreinte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TRAITEMENT DU BRUXISME PAR GOUTTIÈRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Type de bruxisme : <strong>{{type_bruxisme}}</strong>. Date d'empreinte : {{date_empreinte}}.</p><h2>Objectif de la gouttière</h2><p>La gouttière occlusale thermoformée protège les surfaces dentaires de l'usure pathologique, réduit les contraintes musculaires et articulaires (ATM) et peut améliorer la qualité du sommeil.</p><h2>Suivi</h2><p>Un contrôle à 3 semaines est prévu pour vérifier l'occlusion. La gouttière doit être portée toutes les nuits et nettoyée quotidiennement à l'eau froide. Elle est garantie contre les défauts matériaux pour 6 mois.</p><p>Fait à Abidjan, le {{date_empreinte}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_pedodontie',
    name: "Accord de service de soins dentaires enfant (pédodontie)",
    category: 'sante', price: 2000, priceMax: 6000,
    description: "Accord parental pour les soins dentaires pédiatriques (caries, extractions de dents lactéales, prévention).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 69,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom complet de l'enfant", type: 'text', required: true },
      { key: 'age_enfant', label: "Âge de l'enfant", type: 'text', required: true },
      { key: 'nom_parent', label: "Nom du représentant légal", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'soins_prevus', label: "Soins prévus", type: 'textarea', required: true },
      { key: 'date_soin', label: "Date du soin", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SOINS DENTAIRES PÉDIATRIQUES</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le représentant légal <strong>{{nom_parent}}</strong> pour l'enfant <strong>{{nom_enfant}}</strong> âgé de {{age_enfant}} ans.</p><p>Soins prévus : {{soins_prevus}}. Date : {{date_soin}}.</p><h2>Approche pédagogique</h2><p>Le praticien s'engage à adopter une approche non aversive (tell-show-do), à expliquer chaque geste à l'enfant et à utiliser des techniques de gestion comportementale adaptées à son âge pour favoriser une expérience positive.</p><h2>Anesthésie locale</h2><p>Le représentant légal consent à l'utilisation d'une anesthésie locale (gel topique + injection) si nécessaire. Toute sédation complémentaire fera l'objet d'un accord séparé.</p><p>Fait à Abidjan, le {{date_soin}}.</p><p>Signature du représentant légal : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_gerodontologie',
    name: "Accord de service de soins dentaires senior (gérodontologie)",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la prise en charge dentaire adaptée aux patients âgés ou en situation de dépendance.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'nom_referent', label: "Nom du référent ou tuteur (si applicable)", type: 'text', required: false },
      { key: 'pathologies_associees', label: "Pathologies systémiques associées", type: 'textarea', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_prise_en_charge', label: "Date de prise en charge", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE GÉRODONTOLOGIE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong> (référent : {{nom_referent}}).</p><p>Date de prise en charge : {{date_prise_en_charge}}.</p><h2>Adaptation aux besoins spécifiques</h2><p>Le praticien tient compte des pathologies associées ({{pathologies_associees}}), des interactions médicamenteuses (anticoagulants, bisphosphonates, immunosuppresseurs) et de la tolérance générale du patient pour adapter chaque protocole de soin.</p><h2>Accès et accompagnement</h2><p>Les rendez-vous seront planifiés en tenant compte des contraintes de mobilité du patient. Un contact avec l'établissement d'hébergement ou la famille peut être organisé si nécessaire.</p><p>Fait à Abidjan, le {{date_prise_en_charge}}.</p><p>Signature du patient / référent : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_depistage_cancer',
    name: "Accord de service de dépistage cancer buccal",
    category: 'sante', price: 2000, priceMax: 5000,
    description: "Accord pour un examen de dépistage des lésions précancéreuses et cancéreuses de la cavité buccale.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 56,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'facteurs_risque', label: "Facteurs de risque (tabac, alcool, HPV, etc.)", type: 'textarea', required: false },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_examen', label: "Date de l'examen", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DÉPISTAGE DU CANCER BUCCAL</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Date de l'examen : {{date_examen}}. Facteurs de risque : {{facteurs_risque}}.</p><h2>Déroulement</h2><p>L'examen de dépistage comprend l'inspection visuelle et la palpation systématique de toutes les muqueuses buccales (lèvres, joues, gencives, palais, plancher, langue) et des aires ganglionnaires cervicales.</p><h2>Conduite à tenir</h2><p>En cas de lésion suspecte, une biopsie ou une orientation vers un chirurgien maxillo-facial sera proposée sans délai. Le patient consent à cette démarche diagnostique complémentaire si nécessaire.</p><p>Fait à Abidjan, le {{date_examen}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_urgence_dentaire',
    name: "Accord de service de soin d'urgence dentaire (douleur aiguë)",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la prise en charge d'une urgence dentaire (pulpite aiguë, abcès, traumatisme).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 74,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'motif_urgence', label: "Motif de l'urgence (douleur / abcès / traumatisme / autre)", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet dentaire", type: 'text', required: true },
      { key: 'date_urgence', label: "Date et heure de la prise en charge", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SOIN D'URGENCE DENTAIRE</h1><p>Entre le cabinet <strong>{{nom_cabinet}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Motif : <strong>{{motif_urgence}}</strong>. Date de prise en charge : {{date_urgence}}.</p><h2>Acte d'urgence</h2><p>Le praticien réalisera les actes nécessaires pour soulager la douleur aiguë : anesthésie, ouverture de chambre, drainage d'abcès, prescriptions médicamenteuses (antalgiques, antibiotiques si indication). Les soins complémentaires seront programmés ultérieurement.</p><h2>Limites de l'acte d'urgence</h2><p>L'acte d'urgence vise le soulagement immédiat et ne constitue pas un traitement définitif. Le patient s'engage à prendre rendez-vous pour la suite du traitement dans les plus brefs délais.</p><p>Fait à Abidjan, le {{date_urgence}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_partenariat_clinique',
    name: "Accord de partenariat cabinet dentaire-clinique",
    category: 'sante', price: 5000, priceMax: 15000,
    description: "Convention de partenariat entre un cabinet dentaire et une clinique pour orientations de patients et plateaux techniques partagés.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 52,
    fieldsJson: F([
      { key: 'nom_cabinet', label: "Nom et adresse du cabinet dentaire", type: 'text', required: true },
      { key: 'nom_clinique', label: "Nom et adresse de la clinique partenaire", type: 'text', required: true },
      { key: 'date_debut', label: "Date d'entrée en vigueur du partenariat", type: 'date', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (en années)", type: 'text', required: true },
      { key: 'modalites_financieres', label: "Modalités financières convenues", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT CABINET DENTAIRE — CLINIQUE</h1><p>Entre le cabinet dentaire <strong>{{nom_cabinet}}</strong> et la clinique <strong>{{nom_clinique}}</strong>.</p><p>Date d'effet : {{date_debut}}. Durée : <strong>{{duree_contrat}} an(s)</strong>.</p><h2>Objet du partenariat</h2><p>Les parties conviennent de collaborer pour : l'orientation privilégiée des patients nécessitant une hospitalisation ou des actes de chirurgie maxillo-faciale, l'accès au plateau technique de la clinique (imagerie 3D, blocs opératoires), et la formation continue conjointe.</p><h2>Modalités financières</h2><p>{{modalites_financieres}}</p><h2>Confidentialité et données patients</h2><p>Les échanges d'informations médicales seront réalisés dans le strict respect du secret médical et des réglementations en vigueur sur la protection des données de santé.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature cabinet : _________________ &nbsp;&nbsp; Signature clinique : _________________</p></div>`,
  },
  {
    code: 'med4_bilan_bucco_dentaire',
    name: "Rapport de bilan de santé bucco-dentaire",
    category: 'sante', price: 2500, priceMax: 6000,
    description: "Rapport standardisé de bilan bucco-dentaire destiné au patient et/ou à son médecin traitant.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'date_bilan', label: "Date du bilan", type: 'date', required: true },
      { key: 'nom_praticien', label: "Nom du praticien rédacteur", type: 'text', required: true },
      { key: 'etat_parodontal', label: "État parodontal (sain / gingivite / parodontite)", type: 'text', required: true },
      { key: 'caries_detectees', label: "Caries détectées (numéros de dents)", type: 'textarea', required: false },
      { key: 'recommandations', label: "Recommandations thérapeutiques prioritaires", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE BILAN DE SANTÉ BUCCO-DENTAIRE</h1><p>Patient : <strong>{{nom_patient}}</strong>. Date du bilan : {{date_bilan}}. Praticien : Dr {{nom_praticien}}.</p><h2>État parodontal</h2><p>{{etat_parodontal}}</p><h2>Lésions carieuses</h2><p>{{caries_detectees}}</p><h2>Recommandations prioritaires</h2><p>{{recommandations}}</p><h2>Prochain contrôle recommandé</h2><p>Le prochain bilan bucco-dentaire est recommandé dans 6 à 12 mois selon les résultats du présent examen. Ce rapport est remis au patient et peut être transmis à son médecin traitant avec son accord.</p><p>Fait à Abidjan, le {{date_bilan}}. Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'med4_charte_sante_buccale',
    name: "Charte de la santé bucco-dentaire pour tous en Afrique",
    category: 'sante', price: 2000, priceMax: 5000,
    description: "Document de charte d'engagement pour la promotion de la santé bucco-dentaire en milieu communautaire africain.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 50,
    fieldsJson: F([
      { key: 'nom_structure', label: "Nom de la structure signataire (cabinet, association, école)", type: 'text', required: true },
      { key: 'responsable', label: "Nom du responsable signataire", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'actions_prevues', label: "Actions de santé communautaire prévues", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE LA SANTÉ BUCCO-DENTAIRE POUR TOUS EN AFRIQUE</h1><p>Signée par <strong>{{nom_structure}}</strong>, représentée par <strong>{{responsable}}</strong>, le {{date_signature}}.</p><h2>Préambule</h2><p>Considérant que les maladies bucco-dentaires touchent une large proportion de la population africaine, souvent faute d'accès aux soins préventifs et curatifs, la présente charte exprime l'engagement de la structure signataire à contribuer activement à l'amélioration de la santé orale des communautés.</p><h2>Engagements</h2><p>La structure s'engage à : organiser des séances de sensibilisation et de dépistage gratuit, former des acteurs communautaires aux gestes de prévention, et participer aux campagnes nationales de santé dentaire.</p><h2>Actions prévues</h2><p>{{actions_prevues}}</p><p>Signature : _________________</p></div>`,
  },
  // ── 25 templates Kinésithérapie / Réadaptation (kine_) ──────────────────────
  {
    code: 'kine_respiratoire',
    name: "Accord de service de kinésithérapie respiratoire",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la prise en charge en kinésithérapie respiratoire (désencombrement, réentraînement à l'effort).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'pathologie', label: "Pathologie respiratoire (asthme, BPCO, bronchite, post-COVID, etc.)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début des séances", type: 'date', required: true },
      { key: 'nombre_seances', label: "Nombre de séances prescrites", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE KINÉSITHÉRAPIE RESPIRATOIRE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Pathologie : <strong>{{pathologie}}</strong>. Début : {{date_debut}}. Séances prescrites : <strong>{{nombre_seances}}</strong>.</p><h2>Contenu des séances</h2><p>Les séances comprennent des techniques de désencombrement bronchique (drainage autogène, ELTGOL, flutter, percussion), des exercices de respiration diaphragmatique et un réentraînement progressif à l'effort selon la tolérance du patient.</p><h2>Suivi médical</h2><p>Le kinésithérapeute reste en lien avec le médecin prescripteur et rend compte de l'évolution à chaque bilan intermédiaire.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_orthopedique',
    name: "Accord de service de kinésithérapie orthopédique (post-fracture)",
    category: 'sante', price: 3000, priceMax: 9000,
    description: "Accord pour la rééducation fonctionnelle après fracture, entorse ou chirurgie orthopédique.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 73,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'lesion', label: "Lésion / intervention chirurgicale concernée", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de rééducation", type: 'date', required: true },
      { key: 'objectifs', label: "Objectifs fonctionnels visés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE KINÉSITHÉRAPIE ORTHOPÉDIQUE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Lésion : <strong>{{lesion}}</strong>. Début : {{date_debut}}.</p><h2>Objectifs fonctionnels</h2><p>{{objectifs}}</p><h2>Programme de rééducation</h2><p>Le programme inclut : mobilisation passive et active du segment lésé, renforcement musculaire progressif, travail proprioceptif et équilibre, traitement de la douleur (glace, électrothérapie) et conseils d'ergonomie au retour à domicile.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_neurologique',
    name: "Accord de service de kinésithérapie neurologique (AVC, hémiplégie)",
    category: 'sante', price: 3500, priceMax: 10000,
    description: "Accord pour la rééducation neuromotrice après AVC, hémiplégie ou autre atteinte neurologique.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 68,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'diagnostic_neuro', label: "Diagnostic neurologique (AVC / hémiplégie / autre)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de rééducation", type: 'date', required: true },
      { key: 'niveau_autonomie', label: "Niveau d'autonomie initial (score Barthel ou description)", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE KINÉSITHÉRAPIE NEUROLOGIQUE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Diagnostic : <strong>{{diagnostic_neuro}}</strong>. Début : {{date_debut}}.</p><h2>Évaluation initiale</h2><p>Niveau d'autonomie : {{niveau_autonomie}}.</p><h2>Programme</h2><p>La rééducation neurologique comprend : stimulation proprioceptive, travail de la verticalisation et de l'équilibre, rééducation de la marche, prévention des attitudes vicieuses et du syndrome épaule-main, ainsi qu'un entraînement aux activités de la vie quotidienne. Les proches du patient sont formés aux gestes d'aide.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient / tuteur : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_rpg',
    name: "Accord de service de rééducation posturale globale (RPG)",
    category: 'sante', price: 3000, priceMax: 9000,
    description: "Accord pour un traitement par rééducation posturale globale (méthode Souchard ou équivalente).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'motif_rpg', label: "Motif (scoliose, lombalgies, raideurs, etc.)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de la première séance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE RÉÉDUCATION POSTURALE GLOBALE (RPG)</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Motif : <strong>{{motif_rpg}}</strong>. Première séance : {{date_debut}}.</p><h2>Méthode</h2><p>La RPG traite les chaînes musculaires en position de stretching actif global. Chaque séance dure 60 minutes et met en jeu l'ensemble du corps pour corriger les déséquilibres posturaux à l'origine des douleurs chroniques.</p><h2>Fréquence</h2><p>Une séance tous les 15 jours est recommandée pour permettre au système nerveux central d'intégrer les corrections posturales entre les séances. Un minimum de 8 à 12 séances est généralement nécessaire.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_sport',
    name: "Accord de service de kinésithérapie du sport (sportif)",
    category: 'sante', price: 3000, priceMax: 9000,
    description: "Accord pour la rééducation et la prévention des blessures sportives.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([
      { key: 'nom_sportif', label: "Nom complet du sportif", type: 'text', required: true },
      { key: 'sport_pratique', label: "Sport pratiqué et niveau (loisir / compétition)", type: 'text', required: true },
      { key: 'blessure', label: "Nature de la blessure / lésion", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de rééducation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE KINÉSITHÉRAPIE DU SPORT</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le sportif <strong>{{nom_sportif}}</strong> pratiquant <strong>{{sport_pratique}}</strong>.</p><p>Blessure : <strong>{{blessure}}</strong>. Début de rééducation : {{date_debut}}.</p><h2>Objectif</h2><p>Rétablir les capacités physiques du sportif (force, souplesse, coordination, vitesse) et le préparer à une reprise sportive progressive et sécurisée, en prévenant toute récidive.</p><h2>Critères de reprise sportive</h2><p>La reprise progressive sera décidée conjointement avec le médecin du sport sur la base d'une batterie de tests fonctionnels validés. Aucune reprise compétitive ne sera autorisée avant validation clinique.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du sportif : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_pediatrique',
    name: "Accord de service de kinésithérapie pédiatrique",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord parental pour la kinésithérapie de l'enfant (troubles moteurs, retard de développement, pathologies pédiatriques).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom complet de l'enfant", type: 'text', required: true },
      { key: 'age_enfant', label: "Âge de l'enfant", type: 'text', required: true },
      { key: 'nom_parent', label: "Nom du représentant légal", type: 'text', required: true },
      { key: 'motif', label: "Motif de la prise en charge", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début des séances", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE KINÉSITHÉRAPIE PÉDIATRIQUE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le représentant légal <strong>{{nom_parent}}</strong> pour l'enfant <strong>{{nom_enfant}}</strong> âgé de {{age_enfant}} ans.</p><p>Motif : <strong>{{motif}}</strong>. Début des séances : {{date_debut}}.</p><h2>Approche</h2><p>Les séances sont conduites sous forme de jeux adaptés à l'âge de l'enfant. La participation active des parents est encouragée pour assurer la continuité des exercices à domicile. Des bilans réguliers sont réalisés pour ajuster le programme au développement de l'enfant.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du représentant légal : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_geriatrique',
    name: "Accord de service de kinésithérapie gériatrique",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la prise en charge kinésithérapique de la personne âgée (chutes, déconditionnement, douleurs).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'age_patient', label: "Âge du patient", type: 'text', required: true },
      { key: 'motif', label: "Motif de prise en charge (chutes, arthrose, déconditionnement, etc.)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début des séances", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE KINÉSITHÉRAPIE GÉRIATRIQUE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong> âgé de {{age_patient}} ans.</p><p>Motif : <strong>{{motif}}</strong>. Début : {{date_debut}}.</p><h2>Programme adapté</h2><p>Le programme comprend : exercices d'équilibre et de prévention des chutes, renforcement musculaire doux, stretching articulaire, marche thérapeutique et conseils d'aménagement du domicile pour réduire les risques de chute.</p><h2>Coordination</h2><p>Le kinésithérapeute coordonne son intervention avec le médecin traitant, l'infirmière et le cas échéant l'établissement d'hébergement pour personnes âgées.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient / famille : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_perineal',
    name: "Accord de service de rééducation périnéale (post-partum)",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la rééducation du périnée après accouchement (incontinence, prolapsus).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 66,
    fieldsJson: F([
      { key: 'nom_patiente', label: "Nom complet de la patiente", type: 'text', required: true },
      { key: 'date_accouchement', label: "Date de l'accouchement", type: 'date', required: true },
      { key: 'type_accouchement', label: "Type d'accouchement (voie basse / césarienne)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début des séances", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE RÉÉDUCATION PÉRINÉALE POST-PARTUM</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et la patiente <strong>{{nom_patiente}}</strong>.</p><p>Accouchement le {{date_accouchement}} ({{type_accouchement}}). Début des séances : {{date_debut}}.</p><h2>Objectifs</h2><p>La rééducation périnéale vise à corriger l'incontinence urinaire d'effort ou d'urgence, à prévenir les prolapsus pelviens et à restaurer la tonicité et la sensibilité du plancher pelvien.</p><h2>Techniques utilisées</h2><p>Biofeedback électromyographique, électrostimulation fonctionnelle, travail musculaire actif avec ou sans sonde, exercices de Kegel personnalisés et conseils posturaux pour la reprise des activités physiques.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature de la patiente : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_lymphodrainage',
    name: "Accord de service de lymphodrainage manuel (lipoedème)",
    category: 'sante', price: 3000, priceMax: 8000,
    description: "Accord pour des séances de drainage lymphatique manuel dans le cadre d'un lipoedème ou lymphoedème.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 59,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'diagnostic', label: "Diagnostic (lipoedème / lymphoedème / stade)", type: 'text', required: true },
      { key: 'membres_traites', label: "Membres traités (membres supérieurs / inférieurs)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE LYMPHODRAINAGE MANUEL</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Diagnostic : <strong>{{diagnostic}}</strong>. Membres traités : <strong>{{membres_traites}}</strong>. Début : {{date_debut}}.</p><h2>Protocole</h2><p>Le lymphodrainage manuel est réalisé selon la technique Vodder, en manœuvres douces et rythmées visant à stimuler la contraction des lymphangions. Il est suivi du port de vêtements compressifs adaptés.</p><h2>Phase intensive</h2><p>La phase décongestive intensive comprend 5 séances par semaine pendant 2 à 4 semaines, suivie d'une phase d'entretien mensuelle. Le patient s'engage à porter les bandages ou orthèses de compression prescrits.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_massage_therapeutique',
    name: "Accord de service de massage thérapeutique kinésithérapie",
    category: 'sante', price: 2000, priceMax: 6000,
    description: "Accord pour des séances de massage thérapeutique dans un cadre kinésithérapique médical.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 64,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'indication', label: "Indication médicale du massage", type: 'text', required: true },
      { key: 'zones_traitees', label: "Zones anatomiques traitées", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE MASSAGE THÉRAPEUTIQUE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Indication : <strong>{{indication}}</strong>. Zones traitées : <strong>{{zones_traitees}}</strong>. Début : {{date_debut}}.</p><h2>Cadre médical</h2><p>Le massage est réalisé sur prescription médicale dans un objectif thérapeutique précis (décontraction musculaire, drainage, cicatrisation, désensibilisation). Il se distingue des massages de confort non médicaux.</p><h2>Contre-indications</h2><p>Le praticien vérifiera à chaque séance l'absence de contre-indication (phlébite, infection cutanée locale, tumeur, inflammation aiguë) avant de débuter le massage.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_electrotherapie',
    name: "Accord de service d'électrothérapie (TENS, ultrasons)",
    category: 'sante', price: 2000, priceMax: 6000,
    description: "Accord pour l'utilisation d'appareils d'électrothérapie dans le traitement de la douleur.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'technique', label: "Technique utilisée (TENS / ultrasons / ionophorèse / autre)", type: 'text', required: true },
      { key: 'zone_traitee', label: "Zone anatomique traitée", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ÉLECTROTHÉRAPIE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Technique : <strong>{{technique}}</strong>. Zone traitée : <strong>{{zone_traitee}}</strong>. Début : {{date_debut}}.</p><h2>Information et contre-indications</h2><p>Le patient a été informé du principe et des sensations attendues pendant la séance. Contre-indications absolues vérifiées : pace-maker cardiaque, grossesse sur la zone traitée, épilepsie, tumeur maligne sur la zone, implants métalliques au niveau de la zone.</p><h2>Paramétrage</h2><p>Les paramètres (fréquence, intensité, durée) sont déterminés par le thérapeute selon le protocole thérapeutique adapté à la pathologie et ajustés séance après séance selon la réponse clinique.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_cryotherapie',
    name: "Accord de service de cryothérapie kinésithérapie (glace)",
    category: 'sante', price: 2000, priceMax: 5000,
    description: "Accord pour l'application thérapeutique du froid dans le cadre d'une rééducation kinésithérapique.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 55,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'indication', label: "Indication (inflammation aiguë, hématome, entorse, etc.)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CRYOTHÉRAPIE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Indication : <strong>{{indication}}</strong>. Début : {{date_debut}}.</p><h2>Protocole</h2><p>La cryothérapie est appliquée sous forme de poches de glace ou cold-packs, toujours protégés par une serviette pour éviter les brûlures cutanées. La durée d'application est de 15 à 20 minutes maximum par séance, sans dépasser 3 applications par jour.</p><h2>Contre-indications</h2><p>La cryothérapie est contre-indiquée en cas de maladie de Raynaud, de cryoglobulinémie, de troubles de la sensibilité ou de lésions cutanées ouvertes sur la zone traitée. Le patient confirme n'être concerné par aucune de ces contre-indications.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_thermotherapie',
    name: "Accord de service de thermothérapie (infrarouge, paraffine)",
    category: 'sante', price: 2000, priceMax: 5000,
    description: "Accord pour l'application thérapeutique de chaleur (infrarouge, bain de paraffine) en kinésithérapie.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 56,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'methode_chaleur', label: "Méthode (infrarouge / paraffine / compresses chaudes)", type: 'text', required: true },
      { key: 'zone_traitee', label: "Zone anatomique traitée", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE THERMOTHÉRAPIE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Méthode : <strong>{{methode_chaleur}}</strong>. Zone traitée : <strong>{{zone_traitee}}</strong>. Début : {{date_debut}}.</p><h2>Bénéfices attendus</h2><p>La thermothérapie vise à diminuer les contractures musculaires, à augmenter la plasticité des tissus conjonctifs et à préparer la zone à la mobilisation thérapeutique suivante.</p><h2>Précautions</h2><p>La thermothérapie est déconseillée en phase inflammatoire aiguë (moins de 48 heures post-traumatique). La température et la durée sont contrôlées pour éviter tout risque de brûlure.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_balneotherapie',
    name: "Accord de service de balnéokinésithérapie (piscine)",
    category: 'sante', price: 3500, priceMax: 10000,
    description: "Accord pour la rééducation en milieu aquatique (balnéokinésithérapie) dans une piscine thérapeutique.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 57,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'indication', label: "Indication (arthrose, SEP, rééducation post-opératoire, etc.)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début des séances", type: 'date', required: true },
      { key: 'nombre_seances', label: "Nombre de séances prévues", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE BALNÉOKINÉSITHÉRAPIE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Indication : <strong>{{indication}}</strong>. Début : {{date_debut}}. Séances prévues : <strong>{{nombre_seances}}</strong>.</p><h2>Bénéfices de l'eau</h2><p>La poussée d'Archimède allège le poids du corps, permettant des exercices impossibles à sec. La résistance de l'eau renforce les muscles en douceur. La température de l'eau (32-34 °C) favorise la décontraction musculaire et diminue la douleur.</p><h2>Hygiène et sécurité</h2><p>Le patient doit se présenter en bonne santé générale (absence de plaies ouvertes, d'incontinence fécale, d'infections cutanées ou urinaires actives). Il doit apporter son bonnet de bain et suivre les consignes de sécurité.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_ergotherapie',
    name: "Accord de service d'ergothérapie (autonomie quotidienne)",
    category: 'sante', price: 3000, priceMax: 8000,
    description: "Accord pour une prise en charge en ergothérapie visant à restaurer l'autonomie dans les activités de vie quotidienne.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'limitations', label: "Limitations fonctionnelles décrites", type: 'textarea', required: true },
      { key: 'nom_ergo', label: "Nom de l'ergothérapeute", type: 'text', required: true },
      { key: 'date_bilan', label: "Date du bilan d'ergothérapie", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ERGOTHÉRAPIE</h1><p>Entre l'ergothérapeute <strong>{{nom_ergo}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Date du bilan : {{date_bilan}}.</p><h2>Limitations fonctionnelles</h2><p>{{limitations}}</p><h2>Programme</h2><p>L'ergothérapie comprend : évaluation des capacités fonctionnelles (AVQ), entraînement aux gestes de la vie quotidienne (habillage, cuisine, toilette), adaptation du poste de travail ou du domicile, préconisation d'aides techniques et formation du patient et de ses aidants.</p><p>Fait à Abidjan, le {{date_bilan}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature de l'ergothérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_orthophonie',
    name: "Accord de service d'orthophonie (troubles du langage)",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la prise en charge orthophonique des troubles du langage oral, écrit ou de la déglutition.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'trouble', label: "Nature du trouble (dyslexie, bégaiement, aphasie, dysphagie, etc.)", type: 'text', required: true },
      { key: 'nom_ortho', label: "Nom de l'orthophoniste", type: 'text', required: true },
      { key: 'date_bilan', label: "Date du bilan orthophonique", type: 'date', required: true },
      { key: 'frequence', label: "Fréquence des séances", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ORTHOPHONIE</h1><p>Entre l'orthophoniste <strong>{{nom_ortho}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Trouble : <strong>{{trouble}}</strong>. Bilan : {{date_bilan}}. Fréquence : <strong>{{frequence}}</strong>.</p><h2>Programme thérapeutique</h2><p>La rééducation orthophonique s'appuie sur les résultats du bilan initial. Elle comprend des exercices spécifiques de langage, de phonation, de déglutition ou de communication augmentative selon les besoins identifiés, ainsi que des conseils aux proches ou aux enseignants.</p><p>Fait à Abidjan, le {{date_bilan}}.</p><p>Signature du patient / représentant légal : _________________ &nbsp;&nbsp; Signature de l'orthophoniste : _________________</p></div>`,
  },
  {
    code: 'kine_psychomotricite',
    name: "Accord de service de psychomotricité",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour une prise en charge en psychomotricité (enfant ou adulte, troubles du schéma corporel, TDA/H, etc.).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'motif', label: "Motif de prise en charge", type: 'text', required: true },
      { key: 'nom_psychomot', label: "Nom du psychomotricien", type: 'text', required: true },
      { key: 'date_debut', label: "Date de la première séance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PSYCHOMOTRICITÉ</h1><p>Entre le psychomotricien <strong>{{nom_psychomot}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Motif : <strong>{{motif}}</strong>. Première séance : {{date_debut}}.</p><h2>Approche thérapeutique</h2><p>La psychomotricité travaille sur les relations entre le corps, les émotions et les fonctions cognitives par des médiations corporelles (relaxation, jeux moteurs, danse, sport adapté). Elle vise à améliorer le schéma corporel, la coordination, l'attention et la régulation émotionnelle.</p><h2>Durée de la prise en charge</h2><p>Une réévaluation est effectuée après 10 séances pour ajuster les objectifs thérapeutiques en concertation avec la famille et les autres professionnels de santé impliqués.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient / représentant légal : _________________ &nbsp;&nbsp; Signature du psychomotricien : _________________</p></div>`,
  },
  {
    code: 'kine_orthese',
    name: "Accord de service d'appareillage orthétique (orthèse)",
    category: 'sante', price: 3000, priceMax: 9000,
    description: "Accord pour la prescription, la confection et la remise d'une orthèse sur mesure.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'type_orthese', label: "Type d'orthèse (attelle, semelle, corset, orthèse plantaire, etc.)", type: 'text', required: true },
      { key: 'indication', label: "Indication médicale", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute / orthoprothésiste", type: 'text', required: true },
      { key: 'date_livraison', label: "Date de livraison prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'APPAREILLAGE ORTHÉTIQUE</h1><p>Entre le praticien <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Orthèse : <strong>{{type_orthese}}</strong>. Indication : <strong>{{indication}}</strong>. Livraison prévue : {{date_livraison}}.</p><h2>Fabrication et adaptation</h2><p>L'orthèse est réalisée sur mesure à partir des empreintes ou mensurations du patient. Des séances d'adaptation sont prévues pour assurer le confort et l'efficacité de l'appareillage.</p><h2>Garantie</h2><p>L'orthèse est garantie contre les défauts de fabrication pendant 6 mois. Elle doit être portée selon les prescriptions et rapportée au moindre signe d'inconfort ou de modification de l'état du patient.</p><p>Fait à Abidjan, le {{date_livraison}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien : _________________</p></div>`,
  },
  {
    code: 'kine_prothetique',
    name: "Accord de service d'appareillage prothétique (amputés)",
    category: 'sante', price: 5000, priceMax: 15000,
    description: "Accord pour la prescription, la confection et la rééducation à la prothèse pour patient amputé.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 55,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'niveau_amputation', label: "Niveau d'amputation (transtibial, transfémoral, transradial, etc.)", type: 'text', required: true },
      { key: 'type_prothese_kine', label: "Type de prothèse (activité, confort, sport)", type: 'text', required: true },
      { key: 'nom_equipe', label: "Nom de l'équipe de rééducation (praticien référent)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de la phase prothétique", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'APPAREILLAGE PROTHÉTIQUE</h1><p>Entre l'équipe de rééducation (<strong>{{nom_equipe}}</strong>) et le patient <strong>{{nom_patient}}</strong>.</p><p>Niveau d'amputation : <strong>{{niveau_amputation}}</strong>. Type de prothèse : <strong>{{type_prothese_kine}}</strong>. Début : {{date_debut}}.</p><h2>Programme de rééducation prothétique</h2><p>La rééducation comprend : modelage du moignon, entraînement à la chaussage-déchaussage, apprentissage de la marche (avec béquilles puis en autonomie), travail d'équilibre et reprise progressive des activités de la vie quotidienne et professionnelle.</p><h2>Suivi et ajustements</h2><p>Des bilans trimestriels sont prévus pour adapter l'emboiture à l'évolution du moignon et optimiser le fonctionnement de la prothèse.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du praticien référent : _________________</p></div>`,
  },
  {
    code: 'kine_vestibulaire',
    name: "Accord de service de rééducation vestibulaire (vertige)",
    category: 'sante', price: 2500, priceMax: 7000,
    description: "Accord pour la rééducation vestibulaire en cas de vertiges, névrite vestibulaire ou VPPB.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'diagnostic_vestibulaire', label: "Diagnostic vestibulaire (VPPB, névrite, etc.)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE RÉÉDUCATION VESTIBULAIRE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le patient <strong>{{nom_patient}}</strong>.</p><p>Diagnostic : <strong>{{diagnostic_vestibulaire}}</strong>. Début : {{date_debut}}.</p><h2>Techniques</h2><p>Pour le VPPB, la manœuvre d'Epley ou de Sémont sera réalisée dès la première séance. Pour les autres pathologies vestibulaires, un programme de rééducation vestibulaire par habituation, stabilisation du regard et exercices d'équilibre est mis en place.</p><h2>Information</h2><p>Le patient est prévenu que les manœuvres de repositionnement peuvent provoquer une crise de vertige brève mais intense. Il doit être accompagné pour rentrer chez lui après la première séance.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_respiratoire_pediatrique',
    name: "Accord de service de kinésithérapie respiratoire pédiatrique",
    category: 'sante', price: 2000, priceMax: 6000,
    description: "Accord parental pour la kinésithérapie respiratoire du nourrisson ou de l'enfant (bronchiolite, mucoviscidose).",
    templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom complet de l'enfant", type: 'text', required: true },
      { key: 'age_enfant', label: "Âge de l'enfant", type: 'text', required: true },
      { key: 'nom_parent', label: "Nom du représentant légal", type: 'text', required: true },
      { key: 'diagnostic_resp', label: "Diagnostic (bronchiolite, asthme, mucoviscidose, etc.)", type: 'text', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début des séances", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE KINÉSITHÉRAPIE RESPIRATOIRE PÉDIATRIQUE</h1><p>Entre le kinésithérapeute <strong>{{nom_kine}}</strong> et le représentant légal <strong>{{nom_parent}}</strong> pour l'enfant <strong>{{nom_enfant}}</strong> âgé de {{age_enfant}}.</p><p>Diagnostic : <strong>{{diagnostic_resp}}</strong>. Début des séances : {{date_debut}}.</p><h2>Techniques adaptées à l'enfant</h2><p>Les techniques utilisées chez le nourrisson et le jeune enfant (augmentation du flux expiratoire, toux provoquée, drainage de posture) sont douces et adaptées à l'âge et au développement de l'enfant. Les parents sont formés aux gestes à réaliser à domicile entre les séances.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du représentant légal : _________________ &nbsp;&nbsp; Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_cognitive',
    name: "Accord de service de rééducation cognitive (traumatisme crânien)",
    category: 'sante', price: 3500, priceMax: 10000,
    description: "Accord pour la rééducation neuropsychologique et cognitive après traumatisme crânien ou AVC.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'evenement', label: "Événement causal (traumatisme crânien léger / modéré / sévère / AVC)", type: 'text', required: true },
      { key: 'deficits', label: "Déficits cognitifs identifiés (mémoire, attention, langage, etc.)", type: 'textarea', required: true },
      { key: 'nom_equipe', label: "Nom de l'équipe de rééducation", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de la rééducation cognitive", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE RÉÉDUCATION COGNITIVE</h1><p>Entre l'équipe de rééducation (<strong>{{nom_equipe}}</strong>) et le patient <strong>{{nom_patient}}</strong>.</p><p>Événement : <strong>{{evenement}}</strong>. Début : {{date_debut}}.</p><h2>Déficits pris en charge</h2><p>{{deficits}}</p><h2>Programme interdisciplinaire</h2><p>La rééducation cognitive associe un neuropsychologue, un orthophoniste et un kinésithérapeute. Elle comprend des exercices de remédiation cognitive assistée par ordinateur, de compensation par stratégies et d'adaptation de l'environnement pour favoriser l'autonomie.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature du patient / tuteur : _________________ &nbsp;&nbsp; Signature de l'équipe référente : _________________</p></div>`,
  },
  {
    code: 'kine_partenariat_hopital',
    name: "Accord de partenariat kinésithérapeute-hôpital",
    category: 'sante', price: 5000, priceMax: 14000,
    description: "Convention de partenariat entre un cabinet de kinésithérapie et un hôpital ou centre hospitalier.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 52,
    fieldsJson: F([
      { key: 'nom_cabinet_kine', label: "Nom et adresse du cabinet de kinésithérapie", type: 'text', required: true },
      { key: 'nom_hopital', label: "Nom et adresse de l'hôpital partenaire", type: 'text', required: true },
      { key: 'date_debut', label: "Date d'entrée en vigueur", type: 'date', required: true },
      { key: 'duree_partenariat', label: "Durée du partenariat (en années)", type: 'text', required: true },
      { key: 'services_concernes', label: "Services hospitaliers concernés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT KINÉSITHÉRAPEUTE — HÔPITAL</h1><p>Entre le cabinet de kinésithérapie <strong>{{nom_cabinet_kine}}</strong> et l'hôpital <strong>{{nom_hopital}}</strong>.</p><p>Date d'effet : {{date_debut}}. Durée : <strong>{{duree_partenariat}} an(s)</strong>.</p><h2>Services concernés</h2><p>{{services_concernes}}</p><h2>Objet du partenariat</h2><p>Le présent accord organise : le relais de soins des patients en sortie d'hospitalisation, les stages de formation pour les étudiants en kinésithérapie, les réunions de concertation pluridisciplinaire conjointes et l'accès aux plateaux de rééducation de l'hôpital pour les patients adressés par le cabinet.</p><h2>Confidentialité</h2><p>Les échanges d'informations médicales respectent le secret professionnel et la législation sur la protection des données de santé.</p><p>Fait à Abidjan, le {{date_debut}}.</p><p>Signature cabinet : _________________ &nbsp;&nbsp; Signature hôpital : _________________</p></div>`,
  },
  {
    code: 'kine_bilan_fonctionnel',
    name: "Rapport de bilan fonctionnel kinésithérapie",
    category: 'sante', price: 2500, priceMax: 6000,
    description: "Rapport standardisé de bilan fonctionnel kinésithérapique remis au patient et au médecin prescripteur.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'nom_patient', label: "Nom complet du patient", type: 'text', required: true },
      { key: 'date_bilan', label: "Date du bilan", type: 'date', required: true },
      { key: 'nom_kine', label: "Nom du kinésithérapeute rédacteur", type: 'text', required: true },
      { key: 'deficiences', label: "Déficiences et limitations fonctionnelles observées", type: 'textarea', required: true },
      { key: 'objectifs_traitement', label: "Objectifs thérapeutiques et plan de traitement proposé", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE BILAN FONCTIONNEL EN KINÉSITHÉRAPIE</h1><p>Patient : <strong>{{nom_patient}}</strong>. Date du bilan : {{date_bilan}}. Kinésithérapeute : <strong>{{nom_kine}}</strong>.</p><h2>Déficiences et limitations fonctionnelles</h2><p>{{deficiences}}</p><h2>Objectifs thérapeutiques et plan de traitement</h2><p>{{objectifs_traitement}}</p><h2>Prochain bilan</h2><p>Un bilan de réévaluation est prévu à l'issue du programme de rééducation pour mesurer les progrès obtenus et décider de la poursuite, de la modification ou de la clôture de la prise en charge.</p><p>Fait à Abidjan, le {{date_bilan}}. Signature du kinésithérapeute : _________________</p></div>`,
  },
  {
    code: 'kine_charte_reeducation',
    name: "Charte de la rééducation et du retour à l'autonomie",
    category: 'sante', price: 2000, priceMax: 5000,
    description: "Document de charte engageant une structure de rééducation envers ses patients pour un accompagnement de qualité vers l'autonomie.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 51,
    fieldsJson: F([
      { key: 'nom_structure', label: "Nom de la structure de rééducation signataire", type: 'text', required: true },
      { key: 'responsable', label: "Nom du responsable signataire", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature de la charte", type: 'date', required: true },
      { key: 'engagements_specifiques', label: "Engagements spécifiques de la structure", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE LA RÉÉDUCATION ET DU RETOUR À L'AUTONOMIE</h1><p>Signée par <strong>{{nom_structure}}</strong>, représentée par <strong>{{responsable}}</strong>, le {{date_signature}}.</p><h2>Préambule</h2><p>La rééducation est un droit pour toute personne en situation de handicap ou de perte d'autonomie temporaire ou permanente. La présente charte exprime l'engagement de la structure signataire à offrir des soins de rééducation de qualité, accessibles, centrés sur le patient et orientés vers le retour à l'autonomie.</p><h2>Valeurs fondamentales</h2><p>Respect de la dignité du patient, personnalisation des soins, continuité et coordination de la prise en charge, transparence de l'information et implication active du patient et de ses proches dans le projet thérapeutique.</p><h2>Engagements spécifiques</h2><p>{{engagements_specifiques}}</p><p>Signature : _________________</p></div>`,
  },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 106a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
