import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── PÊCHE / AQUACULTURE (25 templates) ───────────────────────────────────
  {
    code: 'peche_permis_artisanal',
    name: "Permis de Pêche Artisanale",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Permis officiel autorisant l'exercice de la pêche artisanale sur les eaux nationales.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_pecheur', label: "Nom complet du pêcheur", type: 'text', required: true },
      { key: 'zone_peche', label: "Zone de pêche autorisée", type: 'text', required: true },
      { key: 'type_engin', label: "Type d\"engin de pêche", type: 'text', required: true },
      { key: 'date_delivrance', label: "Date de délivrance", type: 'date', required: true },
      { key: 'date_expiration', label: "Date d\"expiration", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PERMIS DE PÊCHE ARTISANALE</h1><p>Le présent permis est délivré à <strong>{{nom_pecheur}}</strong>, autorisé à exercer la pêche artisanale dans la zone : <strong>{{zone_peche}}</strong>, avec l"engin de type : <strong>{{type_engin}}</strong>.</p><p>Délivré le : {{date_delivrance}}<br/>Valable jusqu"au : {{date_expiration}}</p><p>Ce permis est personnel et incessible. Toute infraction entraîne son retrait immédiat.</p><div class="signature"><p>Le Directeur des Pêches</p><p>Signature et cachet :</p></div></div>`,
  },
  {
    code: 'peche_contrat_industriel',
    name: "Contrat de Pêche Industrielle",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 24000,
    description: "Contrat encadrant l'exploitation industrielle des ressources halieutiques conformément à la réglementation OHADA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'societe_peche', label: "Raison sociale de la société de pêche", type: 'text', required: true },
      { key: 'autorisation_numero', label: "Numéro d\"autorisation d\"exploitation", type: 'text', required: true },
      { key: 'tonnage_autorise', label: "Tonnage annuel autorisé (en tonnes)", type: 'text', required: true },
      { key: 'zone_exclusive', label: "Zone économique exclusive concernée", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début d\"exploitation", type: 'date', required: true },
      { key: 'date_fin', label: "Date de fin de contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PÊCHE INDUSTRIELLE</h1><p>Entre l"État et la société <strong>{{societe_peche}}</strong>, titulaire de l"autorisation N° <strong>{{autorisation_numero}}</strong>.</p><p>La société est autorisée à prélever un tonnage maximum de <strong>{{tonnage_autorise}}</strong> tonnes par an dans la zone <strong>{{zone_exclusive}}</strong>.</p><p>Durée : du {{date_debut}} au {{date_fin}}.</p><p>La société s"engage à respecter les quotas fixés, les périodes de repos biologique et les normes sanitaires en vigueur.</p><div class="signature"><p>Pour l"État :</p><p>Pour la Société :</p></div></div>`,
  },
  {
    code: 'peche_accord_cooperative',
    name: "Accord de Coopérative de Pêcheurs",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 12000,
    description: "Accord constitutif d'une coopérative de pêcheurs artisanaux en vue de la mise en commun des ressources et des revenus.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_cooperative', label: "Dénomination de la coopérative", type: 'text', required: true },
      { key: 'nombre_membres', label: "Nombre de membres fondateurs", type: 'text', required: true },
      { key: 'siege_social', label: "Siège social de la coopérative", type: 'text', required: true },
      { key: 'president_nom', label: "Nom du président élu", type: 'text', required: true },
      { key: 'date_creation', label: "Date de création", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE COOPÉRATIVE DE PÊCHEURS</h1><p>Les soussignés, au nombre de <strong>{{nombre_membres}}</strong>, conviennent de constituer la coopérative de pêcheurs dénommée <strong>{{nom_cooperative}}</strong>, dont le siège est établi à <strong>{{siege_social}}</strong>.</p><p>Président élu : <strong>{{president_nom}}</strong></p><p>Date de création : {{date_creation}}</p><p>La coopérative a pour objet la mise en commun des moyens de pêche, la commercialisation groupée des produits et la défense des intérêts de ses membres.</p><div class="signature"><p>Les membres fondateurs :</p></div></div>`,
  },
  {
    code: 'peche_contrat_filet',
    name: "Contrat de Service de Pêche au Filet",
    category: 'agro_environnement',
    price: 2500,
    priceMax: 7500,
    description: "Contrat de prestation de service pour la pêche au filet entre un prestataire et un commanditaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'prestataire_nom', label: "Nom du prestataire (pêcheur)", type: 'text', required: true },
      { key: 'commanditaire_nom', label: "Nom du commanditaire", type: 'text', required: true },
      { key: 'type_filet', label: "Type de filet utilisé", type: 'text', required: true },
      { key: 'remuneration', label: "Rémunération convenue (FCFA)", type: 'text', required: true },
      { key: 'date_prestation', label: "Date de la prestation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE PÊCHE AU FILET</h1><p>Entre <strong>{{prestataire_nom}}</strong> (prestataire) et <strong>{{commanditaire_nom}}</strong> (commanditaire).</p><p>Le prestataire s"engage à effectuer une campagne de pêche au filet de type <strong>{{type_filet}}</strong> pour le compte du commanditaire.</p><p>Rémunération convenue : <strong>{{remuneration}} FCFA</strong></p><p>Date d"exécution : {{date_prestation}}</p><p>Le produit de la pêche appartient au commanditaire sauf accord contraire stipulé aux présentes.</p><div class="signature"><p>Le Prestataire :</p><p>Le Commanditaire :</p></div></div>`,
  },
  {
    code: 'peche_location_pirogue',
    name: "Accord de Location de Pirogue de Pêche",
    category: 'agro_environnement',
    price: 2000,
    priceMax: 6000,
    description: "Accord de location d'une pirogue de pêche entre un propriétaire et un locataire pêcheur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'proprietaire_nom', label: "Nom du propriétaire de la pirogue", type: 'text', required: true },
      { key: 'locataire_nom', label: "Nom du locataire", type: 'text', required: true },
      { key: 'description_pirogue', label: "Description de la pirogue (taille, moteur)", type: 'text', required: true },
      { key: 'loyer_mensuel', label: "Loyer mensuel (FCFA)", type: 'text', required: true },
      { key: 'date_debut_location', label: "Date de début de location", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE LOCATION DE PIROGUE DE PÊCHE</h1><p>Entre <strong>{{proprietaire_nom}}</strong> (bailleur) et <strong>{{locataire_nom}}</strong> (locataire).</p><p>Le bailleur met à disposition du locataire la pirogue suivante : <strong>{{description_pirogue}}</strong>, moyennant un loyer mensuel de <strong>{{loyer_mensuel}} FCFA</strong>.</p><p>Prise d"effet : {{date_debut_location}}</p><p>Le locataire est responsable de l"entretien courant de la pirogue et des dommages causés par son usage.</p><div class="signature"><p>Le Bailleur :</p><p>Le Locataire :</p></div></div>`,
  },
  {
    code: 'peche_fumage_poisson',
    name: "Contrat de Service de Fumage de Poisson",
    category: 'agro_environnement',
    price: 2000,
    priceMax: 6000,
    description: "Contrat de prestation pour le fumage de poisson entre un transformateur et un fournisseur de matière première.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'transformateur_nom', label: "Nom du fumeur/transformateur", type: 'text', required: true },
      { key: 'fournisseur_nom', label: "Nom du fournisseur de poisson", type: 'text', required: true },
      { key: 'quantite_kg', label: "Quantité de poisson à fumer (kg)", type: 'text', required: true },
      { key: 'tarif_kg', label: "Tarif de fumage par kg (FCFA)", type: 'text', required: true },
      { key: 'date_livraison', label: "Date de livraison souhaitée", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE FUMAGE DE POISSON</h1><p>Entre <strong>{{transformateur_nom}}</strong> (prestataire) et <strong>{{fournisseur_nom}}</strong> (client).</p><p>Le prestataire s"engage à fumer <strong>{{quantite_kg}} kg</strong> de poisson au tarif de <strong>{{tarif_kg}} FCFA/kg</strong>.</p><p>Livraison prévue le : {{date_livraison}}</p><p>Le produit fumé sera conditionné conformément aux normes sanitaires en vigueur. Toute perte due à un défaut de traitement engage la responsabilité du prestataire.</p><div class="signature"><p>Le Prestataire :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'peche_accord_maree_fraiche',
    name: "Accord de Service de Marée Fraîche",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Accord d'approvisionnement régulier en produits de la mer frais entre un pêcheur et un distributeur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'pecheur_nom', label: "Nom du pêcheur fournisseur", type: 'text', required: true },
      { key: 'distributeur_nom', label: "Nom du distributeur", type: 'text', required: true },
      { key: 'volume_hebdomadaire', label: "Volume hebdomadaire garanti (kg)", type: 'text', required: true },
      { key: 'prix_kg', label: "Prix de cession par kg (FCFA)", type: 'text', required: true },
      { key: 'date_debut_accord', label: "Date de début de l\"accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE MARÉE FRAÎCHE</h1><p>Entre <strong>{{pecheur_nom}}</strong> (fournisseur) et <strong>{{distributeur_nom}}</strong> (distributeur).</p><p>Le fournisseur s"engage à livrer <strong>{{volume_hebdomadaire}} kg</strong> de produits de mer frais par semaine au prix de <strong>{{prix_kg}} FCFA/kg</strong>.</p><p>Début de l"accord : {{date_debut_accord}}</p><p>Les produits doivent être livrés sous glace et conformes aux normes sanitaires. Le distributeur s"engage à enlever la marchandise dans les délais convenus.</p><div class="signature"><p>Le Fournisseur :</p><p>Le Distributeur :</p></div></div>`,
  },
  {
    code: 'peche_vente_cree',
    name: "Contrat de Vente de Poisson Frais (Criée)",
    category: 'agro_environnement',
    price: 1500,
    priceMax: 4500,
    description: "Contrat de vente aux enchères de poisson frais dans le cadre d'une criée officielle.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'vendeur_nom', label: "Nom du vendeur (pêcheur)", type: 'text', required: true },
      { key: 'acheteur_nom', label: "Nom de l\"acheteur", type: 'text', required: true },
      { key: 'espece_poisson', label: "Espèce de poisson vendue", type: 'text', required: true },
      { key: 'quantite_vendue', label: "Quantité vendue (kg)", type: 'text', required: true },
      { key: 'prix_adjudication', label: "Prix d\"adjudication (FCFA)", type: 'text', required: true },
      { key: 'date_vente', label: "Date de la vente", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE DE POISSON FRAIS - CRIÉE</h1><p>Il a été convenu entre <strong>{{vendeur_nom}}</strong> (vendeur) et <strong>{{acheteur_nom}}</strong> (acheteur) la vente de <strong>{{quantite_vendue}} kg</strong> de <strong>{{espece_poisson}}</strong> au prix d"adjudication de <strong>{{prix_adjudication}} FCFA</strong>.</p><p>Date : {{date_vente}}</p><p>La vente est ferme et définitive. Le paiement s"effectue au comptant avant enlèvement de la marchandise.</p><div class="signature"><p>Le Vendeur :</p><p>L"Acheteur :</p></div></div>`,
  },
  {
    code: 'peche_accord_poissonnerie',
    name: "Accord de Service de Poissonnerie",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 10500,
    description: "Accord d'exploitation d'un point de vente de poissons frais et produits de mer.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'exploitant_nom', label: "Nom de l\"exploitant de la poissonnerie", type: 'text', required: true },
      { key: 'adresse_poissonnerie', label: "Adresse de la poissonnerie", type: 'text', required: true },
      { key: 'fournisseur_principal', label: "Fournisseur principal de poisson", type: 'text', required: true },
      { key: 'capacite_stockage', label: "Capacité de stockage en froid (kg)", type: 'text', required: true },
      { key: 'date_ouverture', label: "Date d\"ouverture", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POISSONNERIE</h1><p><strong>{{exploitant_nom}}</strong> exploite la poissonnerie sise à <strong>{{adresse_poissonnerie}}</strong> conformément aux présentes dispositions.</p><p>Fournisseur principal : <strong>{{fournisseur_principal}}</strong><br/>Capacité de stockage frigorifique : <strong>{{capacite_stockage}} kg</strong></p><p>Ouverture : {{date_ouverture}}</p><p>L"exploitant s"engage à respecter la chaîne du froid, les normes d"hygiène et les réglementations sanitaires applicables aux commerces de produits de la mer.</p><div class="signature"><p>L"Exploitant :</p><p>L"Autorité sanitaire :</p></div></div>`,
  },
  {
    code: 'peche_transformation_poisson',
    name: "Contrat de Service de Transformation de Poisson",
    category: 'agro_environnement',
    price: 4500,
    priceMax: 13500,
    description: "Contrat de transformation artisanale ou semi-industrielle de poisson (séchage, salage, mise en conserve artisanale).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'unite_transformation', label: "Nom de l\"unité de transformation", type: 'text', required: true },
      { key: 'client_nom', label: "Nom du client donneur d\"ordre", type: 'text', required: true },
      { key: 'procede_transformation', label: "Procédé de transformation (séchage/salage/fumage)", type: 'text', required: true },
      { key: 'volume_traite', label: "Volume à traiter (kg)", type: 'text', required: true },
      { key: 'date_traitement', label: "Date de traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE TRANSFORMATION DE POISSON</h1><p>Entre <strong>{{unite_transformation}}</strong> (transformateur) et <strong>{{client_nom}}</strong> (client).</p><p>Procédé retenu : <strong>{{procede_transformation}}</strong><br/>Volume à traiter : <strong>{{volume_traite}} kg</strong></p><p>Date prévue : {{date_traitement}}</p><p>Le transformateur garantit la qualité du produit fini selon les normes de conservation en vigueur. Le client fournit la matière première en état de fraîcheur acceptable.</p><div class="signature"><p>Le Transformateur :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'peche_ferme_aquacole',
    name: "Accord de Ferme Aquacole (Tilapia/Silure)",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Accord d'exploitation d'une ferme aquacole pour l'élevage de tilapia ou de silure en bassin ou en cage.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'exploitant_aquacole', label: "Nom de l\"exploitant aquacole", type: 'text', required: true },
      { key: 'espece_elevee', label: "Espèce élevée (Tilapia/Silure/Autre)", type: 'text', required: true },
      { key: 'capacite_production', label: "Capacité de production annuelle (kg)", type: 'text', required: true },
      { key: 'localisation_ferme', label: "Localisation de la ferme aquacole", type: 'text', required: true },
      { key: 'date_mise_en_eau', label: "Date de mise en eau des bassins", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FERME AQUACOLE</h1><p><strong>{{exploitant_aquacole}}</strong> exploite une ferme aquacole dédiée à l"élevage de <strong>{{espece_elevee}}</strong>, située à <strong>{{localisation_ferme}}</strong>.</p><p>Capacité de production annuelle estimée : <strong>{{capacite_production}} kg</strong><br/>Date de mise en eau : {{date_mise_en_eau}}</p><p>L"exploitant s"engage à respecter les densités d"élevage recommandées, la qualité de l"eau et les mesures sanitaires imposées par les autorités compétentes.</p><div class="signature"><p>L"Exploitant :</p><p>L"Autorité de tutelle :</p></div></div>`,
  },
  {
    code: 'peche_ecloserie_poissons',
    name: "Contrat de Service d\"Ecloserie de Poissons",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de production et de fourniture d'alevins issus d'une écloserie piscicole.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 47,
    fieldsJson: F([
      { key: 'ecloserie_nom', label: "Nom de l\"écloserie", type: 'text', required: true },
      { key: 'acheteur_alevins', label: "Nom de l\"acheteur d\"alevins", type: 'text', required: true },
      { key: 'espece_alevin', label: "Espèce d\"alevin commandée", type: 'text', required: true },
      { key: 'quantite_alevins', label: "Quantité d\"alevins (unités)", type: 'text', required: true },
      { key: 'date_livraison_alevins', label: "Date de livraison prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"ECLOSERIE DE POISSONS</h1><p>Entre <strong>{{ecloserie_nom}}</strong> (fournisseur) et <strong>{{acheteur_alevins}}</strong> (acheteur).</p><p>L"écloserie s"engage à livrer <strong>{{quantite_alevins}}</strong> alevins de <strong>{{espece_alevin}}</strong>, sains et calibrés, à la date du <strong>{{date_livraison_alevins}}</strong>.</p><p>Les alevins sont garantis contre les mortalités dues à des défauts de production. La mortalité au transport est à la charge de l"acheteur sauf stipulation contraire.</p><div class="signature"><p>L"Ecloserie :</p><p>L"Acheteur :</p></div></div>`,
  },
  {
    code: 'peche_nourriture_aquacole',
    name: "Accord de Service de Nourriture Aquacole",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Accord de fourniture régulière d'aliments pour poissons (granulés, farine de poisson) à une ferme aquacole.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'fournisseur_aliment', label: "Nom du fournisseur d\"aliments", type: 'text', required: true },
      { key: 'ferme_cliente', label: "Nom de la ferme cliente", type: 'text', required: true },
      { key: 'type_aliment', label: "Type d\"aliment (granulés/farine/autre)", type: 'text', required: true },
      { key: 'quantite_mensuelle', label: "Quantité mensuelle commandée (kg)", type: 'text', required: true },
      { key: 'date_premier_livraison', label: "Date de première livraison", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FOURNITURE DE NOURRITURE AQUACOLE</h1><p>Entre <strong>{{fournisseur_aliment}}</strong> (fournisseur) et <strong>{{ferme_cliente}}</strong> (client).</p><p>Le fournisseur s"engage à livrer <strong>{{quantite_mensuelle}} kg</strong> par mois d"aliments de type <strong>{{type_aliment}}</strong> à partir du <strong>{{date_premier_livraison}}</strong>.</p><p>Les aliments doivent être conformes aux normes nutritionnelles requises pour l"espèce cible et conditionnés dans des sacs étanches à l"humidité.</p><div class="signature"><p>Le Fournisseur :</p><p>La Ferme :</p></div></div>`,
  },
  {
    code: 'peche_cage_flottante',
    name: "Contrat de Service de Cage Flottante d\"Elevage",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de mise à disposition et d'exploitation de cages flottantes pour l'aquaculture en milieu lacustre ou lagunaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 44,
    fieldsJson: F([
      { key: 'prestataire_cage', label: "Nom du prestataire de cages", type: 'text', required: true },
      { key: 'exploitant_cage', label: "Nom de l\"exploitant aquacole", type: 'text', required: true },
      { key: 'nombre_cages', label: "Nombre de cages mises à disposition", type: 'text', required: true },
      { key: 'site_installation', label: "Site d\"installation des cages", type: 'text', required: true },
      { key: 'date_installation', label: "Date d\"installation prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE CAGE FLOTTANTE D"ELEVAGE</h1><p>Entre <strong>{{prestataire_cage}}</strong> (prestataire) et <strong>{{exploitant_cage}}</strong> (exploitant).</p><p>Le prestataire met à disposition <strong>{{nombre_cages}}</strong> cage(s) flottante(s) sur le site de <strong>{{site_installation}}</strong>, avec installation prévue le <strong>{{date_installation}}</strong>.</p><p>L"exploitant assume la gestion biologique des cages. Le prestataire assure la maintenance structurelle des équipements.</p><div class="signature"><p>Le Prestataire :</p><p>L"Exploitant :</p></div></div>`,
  },
  {
    code: 'peche_certification_durable',
    name: "Accord de Certification Pêche Durable (MSC Adapté)",
    category: 'agro_environnement',
    price: 7000,
    priceMax: 21000,
    description: "Accord d'engagement vers une certification de pêche durable adaptée au contexte ouest-africain.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'organisme_peche', label: "Nom de l\"organisme de pêche candidat", type: 'text', required: true },
      { key: 'organisme_certificateur', label: "Organisme certificateur", type: 'text', required: true },
      { key: 'perimetre_certification', label: "Périmètre de certification (espèce/zone)", type: 'text', required: true },
      { key: 'duree_processus', label: "Durée du processus de certification (mois)", type: 'text', required: true },
      { key: 'date_engagement', label: "Date d\"engagement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION PÊCHE DURABLE</h1><p>Entre <strong>{{organisme_peche}}</strong> et l"organisme certificateur <strong>{{organisme_certificateur}}</strong>.</p><p>Périmètre : <strong>{{perimetre_certification}}</strong><br/>Durée estimée du processus : <strong>{{duree_processus}} mois</strong></p><p>Date d"engagement : {{date_engagement}}</p><p>Le candidat s"engage à mettre en oeuvre les plans d"action requis pour atteindre les critères de durabilité écologique, de gestion halieutique et de traçabilité de la chaîne de valeur.</p><div class="signature"><p>L"Organisme de Pêche :</p><p>Le Certificateur :</p></div></div>`,
  },
  {
    code: 'peche_inspection_sanitaire',
    name: "Rapport d\"Inspection Sanitaire Produits de la Mer",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 10500,
    description: "Rapport officiel d'inspection sanitaire des produits de la mer délivré par les autorités vétérinaires ou sanitaires.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'inspecteur_nom', label: "Nom de l\"inspecteur sanitaire", type: 'text', required: true },
      { key: 'etablissement_inspecte', label: "Etablissement inspecté", type: 'text', required: true },
      { key: 'resultats_inspection', label: "Résultats de l\"inspection", type: 'textarea', required: true },
      { key: 'recommandations', label: "Recommandations et mesures correctives", type: 'textarea', required: false },
      { key: 'date_inspection', label: "Date d\"inspection", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D"INSPECTION SANITAIRE - PRODUITS DE LA MER</h1><p>Inspecteur : <strong>{{inspecteur_nom}}</strong><br/>Etablissement inspecté : <strong>{{etablissement_inspecte}}</strong><br/>Date : {{date_inspection}}</p><h2>Résultats</h2><p>{{resultats_inspection}}</p><h2>Recommandations</h2><p>{{recommandations}}</p><div class="signature"><p>L"Inspecteur :</p><p>Le Responsable de l"Etablissement :</p></div></div>`,
  },
  {
    code: 'peche_plan_developpement_aquaculture',
    name: "Plan de Développement de l\"Aquaculture",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 24000,
    description: "Document de planification stratégique pour le développement d'une filière aquacole à l'échelle locale ou régionale.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 38,
    fieldsJson: F([
      { key: 'region_concernee', label: "Région ou zone concernée", type: 'text', required: true },
      { key: 'objectifs_production', label: "Objectifs de production (tonnes/an)", type: 'text', required: true },
      { key: 'axes_strategiques', label: "Axes stratégiques prioritaires", type: 'textarea', required: true },
      { key: 'budget_previsionnel', label: "Budget prévisionnel (FCFA)", type: 'text', required: true },
      { key: 'horizon_planification', label: "Horizon de planification (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT DE L"AQUACULTURE</h1><p>Zone concernée : <strong>{{region_concernee}}</strong><br/>Objectifs : <strong>{{objectifs_production}} tonnes/an</strong><br/>Horizon : <strong>{{horizon_planification}} ans</strong><br/>Budget : <strong>{{budget_previsionnel}} FCFA</strong></p><h2>Axes stratégiques</h2><p>{{axes_strategiques}}</p><p>Ce plan est soumis à approbation des autorités compétentes et fera l"objet d"un suivi-évaluation annuel.</p><div class="signature"><p>L"Autorité de Planification :</p></div></div>`,
  },
  {
    code: 'peche_service_glacons',
    name: "Contrat de Service de Glaçon pour Conservation",
    category: 'agro_environnement',
    price: 1500,
    priceMax: 4500,
    description: "Contrat de fourniture de glace pour la conservation des produits halieutiques tout au long de la chaîne de valeur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'fournisseur_glace', label: "Nom du fournisseur de glace", type: 'text', required: true },
      { key: 'client_glace', label: "Nom du client (pêcheur/marché)", type: 'text', required: true },
      { key: 'quantite_glace_jour', label: "Quantité de glace par jour (kg)", type: 'text', required: true },
      { key: 'prix_kg_glace', label: "Prix par kg de glace (FCFA)", type: 'text', required: true },
      { key: 'date_debut_contrat', label: "Date de début du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE FOURNITURE DE GLAÇONS - CONSERVATION POISSON</h1><p>Entre <strong>{{fournisseur_glace}}</strong> (fournisseur) et <strong>{{client_glace}}</strong> (client).</p><p>Quantité journalière : <strong>{{quantite_glace_jour}} kg</strong> au tarif de <strong>{{prix_kg_glace}} FCFA/kg</strong>.</p><p>Début de fourniture : {{date_debut_contrat}}</p><p>La glace est livrée quotidiennement avant le début des activités de pêche ou de commercialisation. Toute rupture de fourniture doit être signalée 24h à l"avance.</p><div class="signature"><p>Le Fournisseur :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'peche_transport_frigorifique',
    name: "Accord de Service de Transport Frigorifique (Poisson)",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Accord de transport réfrigéré de produits de la mer entre un point d'expédition et un marché de destination.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'transporteur_nom', label: "Nom du transporteur frigorifique", type: 'text', required: true },
      { key: 'expediteur_nom', label: "Nom de l\"expéditeur", type: 'text', required: true },
      { key: 'origine_destination', label: "Trajet (origine - destination)", type: 'text', required: true },
      { key: 'tarif_transport', label: "Tarif de transport (FCFA/voyage)", type: 'text', required: true },
      { key: 'date_premier_voyage', label: "Date du premier voyage", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSPORT FRIGORIFIQUE - POISSON</h1><p>Entre <strong>{{transporteur_nom}}</strong> (transporteur) et <strong>{{expediteur_nom}}</strong> (expéditeur).</p><p>Trajet : <strong>{{origine_destination}}</strong><br/>Tarif : <strong>{{tarif_transport}} FCFA/voyage</strong><br/>Premier voyage : {{date_premier_voyage}}</p><p>Le transporteur garantit le maintien de la chaîne du froid entre 0°C et 4°C durant tout le transport. Il est responsable des pertes dues à une défaillance frigorifique.</p><div class="signature"><p>Le Transporteur :</p><p>L"Expéditeur :</p></div></div>`,
  },
  {
    code: 'peche_vente_crevettes',
    name: "Contrat de Vente de Crevettes et Langoustes",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de vente en gros de crevettes et langoustes pour l'export ou la distribution locale.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'vendeur_crevettes', label: "Nom du vendeur", type: 'text', required: true },
      { key: 'acheteur_crevettes', label: "Nom de l\"acheteur", type: 'text', required: true },
      { key: 'produit_detail', label: "Détail du produit (crevettes/langoustes, calibre)", type: 'text', required: true },
      { key: 'quantite_kg', label: "Quantité en kg", type: 'text', required: true },
      { key: 'prix_total', label: "Prix total de la vente (FCFA)", type: 'text', required: true },
      { key: 'date_livraison_crevettes', label: "Date de livraison", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE DE CREVETTES ET LANGOUSTES</h1><p>Entre <strong>{{vendeur_crevettes}}</strong> (vendeur) et <strong>{{acheteur_crevettes}}</strong> (acheteur).</p><p>Produit : <strong>{{produit_detail}}</strong><br/>Quantité : <strong>{{quantite_kg}} kg</strong><br/>Prix total : <strong>{{prix_total}} FCFA</strong></p><p>Livraison prévue le : {{date_livraison_crevettes}}</p><p>Les produits sont livrés sous glace, frais, propres et triés. Un certificat sanitaire accompagne chaque lot.</p><div class="signature"><p>Le Vendeur :</p><p>L"Acheteur :</p></div></div>`,
  },
  {
    code: 'peche_accord_conserverie',
    name: "Accord de Service de Conserverie de Poisson",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Accord de mise en conserve industrielle ou semi-artisanale de poisson pour une entreprise agroalimentaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 42,
    fieldsJson: F([
      { key: 'conserverie_nom', label: "Nom de la conserverie", type: 'text', required: true },
      { key: 'client_conserverie', label: "Nom du client donneur d\"ordre", type: 'text', required: true },
      { key: 'produit_conserve', label: "Produit à mettre en conserve", type: 'text', required: true },
      { key: 'volume_production', label: "Volume de production (boîtes/mois)", type: 'text', required: true },
      { key: 'date_demarrage', label: "Date de démarrage de la production", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CONSERVERIE DE POISSON</h1><p>Entre <strong>{{conserverie_nom}}</strong> (transformateur) et <strong>{{client_conserverie}}</strong> (client).</p><p>Produit : <strong>{{produit_conserve}}</strong><br/>Volume mensuel : <strong>{{volume_production}} boîtes</strong></p><p>Démarrage : {{date_demarrage}}</p><p>La conserverie garantit la conformité aux normes sanitaires, l"étanchéité des boîtes et l"exactitude des informations portées sur les étiquettes. Le client valide les recettes et le conditionnement.</p><div class="signature"><p>La Conserverie :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'peche_tracabilite_halieutique',
    name: "Contrat de Service de Traçabilité Halieutique",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de mise en place d'un système de traçabilité des produits de la pêche de la capture à la mise en marché.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 36,
    fieldsJson: F([
      { key: 'prestataire_tracabilite', label: "Nom du prestataire de traçabilité", type: 'text', required: true },
      { key: 'client_tracabilite', label: "Nom de l\"opérateur de pêche client", type: 'text', required: true },
      { key: 'systeme_utilise', label: "Système de traçabilité utilisé (numérique/papier)", type: 'text', required: true },
      { key: 'perimetre_tracabilite', label: "Périmètre (espèces et zones couvertes)", type: 'text', required: true },
      { key: 'date_mise_en_oeuvre', label: "Date de mise en oeuvre", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE TRAÇABILITÉ HALIEUTIQUE</h1><p>Entre <strong>{{prestataire_tracabilite}}</strong> et <strong>{{client_tracabilite}}</strong>.</p><p>Système : <strong>{{systeme_utilise}}</strong><br/>Périmètre : <strong>{{perimetre_tracabilite}}</strong></p><p>Mise en oeuvre : {{date_mise_en_oeuvre}}</p><p>Le prestataire s"engage à déployer un système permettant d"identifier l"origine de chaque lot de poisson depuis la capture jusqu"au point de vente final, conformément aux exigences réglementaires en vigueur.</p><div class="signature"><p>Le Prestataire :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'peche_financement_campagne',
    name: "Accord de Financement Campagne de Pêche",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Accord de financement entre un bailleur de fonds et un groupement de pêcheurs pour une campagne de pêche saisonnière.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'bailleur_nom', label: "Nom du bailleur de fonds", type: 'text', required: true },
      { key: 'groupement_pecheurs', label: "Nom du groupement de pêcheurs", type: 'text', required: true },
      { key: 'montant_financement', label: "Montant du financement (FCFA)", type: 'text', required: true },
      { key: 'conditions_remboursement', label: "Conditions de remboursement", type: 'textarea', required: true },
      { key: 'date_deblocage', label: "Date de déblocage des fonds", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FINANCEMENT CAMPAGNE DE PÊCHE</h1><p>Entre <strong>{{bailleur_nom}}</strong> (bailleur) et <strong>{{groupement_pecheurs}}</strong> (bénéficiaire).</p><p>Montant : <strong>{{montant_financement}} FCFA</strong><br/>Déblocage prévu : {{date_deblocage}}</p><h2>Conditions de remboursement</h2><p>{{conditions_remboursement}}</p><p>Les fonds serviront exclusivement au financement de la campagne de pêche. Toute utilisation à d"autres fins entraîne l"exigibilité immédiate du remboursement.</p><div class="signature"><p>Le Bailleur :</p><p>Le Groupement :</p></div></div>`,
  },
  {
    code: 'peche_convention_bilaterale',
    name: "Convention de Coopération Pêche Bilatérale",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Convention bilatérale de coopération dans le domaine de la pêche entre deux États ou organisations régionales.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 33,
    fieldsJson: F([
      { key: 'partie_A', label: "Première partie (État/Organisation)", type: 'text', required: true },
      { key: 'partie_B', label: "Deuxième partie (État/Organisation)", type: 'text', required: true },
      { key: 'domaines_cooperation', label: "Domaines de coopération convenus", type: 'textarea', required: true },
      { key: 'duree_convention', label: "Durée de la convention (années)", type: 'text', required: true },
      { key: 'date_signature_convention', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE COOPÉRATION PÊCHE BILATÉRALE</h1><p>Entre <strong>{{partie_A}}</strong> et <strong>{{partie_B}}</strong>.</p><p>Durée : <strong>{{duree_convention}} ans</strong> à compter du {{date_signature_convention}}.</p><h2>Domaines de coopération</h2><p>{{domaines_cooperation}}</p><p>Les parties s"engagent à respecter les engagements pris au titre de la présente convention et à se réunir au moins une fois par an pour évaluer leur mise en oeuvre.</p><div class="signature"><p>Pour la Partie A :</p><p>Pour la Partie B :</p></div></div>`,
  },
  {
    code: 'peche_rapport_gestion_durable',
    name: "Rapport de Gestion Durable des Ressources Halieutiques",
    category: 'agro_environnement',
    price: 7000,
    priceMax: 21000,
    description: "Rapport annuel d'évaluation et de gestion durable des ressources halieutiques d'une zone ou d'une espèce ciblée.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 35,
    fieldsJson: F([
      { key: 'redacteur_rapport', label: "Nom du rédacteur du rapport", type: 'text', required: true },
      { key: 'zone_gestion', label: "Zone halieutique concernée", type: 'text', required: true },
      { key: 'etat_ressources', label: "Etat des ressources (surexploitées/durables/en récupération)", type: 'text', required: true },
      { key: 'mesures_gestion', label: "Mesures de gestion recommandées", type: 'textarea', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE GESTION DURABLE DES RESSOURCES HALIEUTIQUES</h1><p>Rédacteur : <strong>{{redacteur_rapport}}</strong><br/>Zone : <strong>{{zone_gestion}}</strong><br/>Date : {{date_rapport}}</p><h2>Etat des ressources</h2><p>{{etat_ressources}}</p><h2>Mesures recommandées</h2><p>{{mesures_gestion}}</p><p>Ce rapport est soumis aux autorités compétentes pour validation et mise en oeuvre des recommandations dans les délais prescrits.</p><div class="signature"><p>Le Rédacteur :</p><p>L"Autorité de Tutelle :</p></div></div>`,
  },

  // ─── ELEVAGE / AVICULTURE / VÉTÉRINAIRE (25 templates) ───────────────────
  {
    code: 'elev_contrat_bovin_naisseur',
    name: "Contrat d\"Elevage de Bovins (Naisseur-Engraisseur)",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat encadrant la relation entre un éleveur naisseur et un engraisseur pour la production de bovins de boucherie.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'naisseur_nom', label: "Nom du naisseur (éleveur producteur)", type: 'text', required: true },
      { key: 'engraisseur_nom', label: "Nom de l\"engraisseur", type: 'text', required: true },
      { key: 'nombre_tetes', label: "Nombre de têtes concernées", type: 'text', required: true },
      { key: 'race_bovin', label: "Race bovine", type: 'text', required: true },
      { key: 'prix_tete', label: "Prix convenu par tête (FCFA)", type: 'text', required: true },
      { key: 'date_transfert', label: "Date de transfert des animaux", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"ELEVAGE DE BOVINS - NAISSEUR/ENGRAISSEUR</h1><p>Entre <strong>{{naisseur_nom}}</strong> (naisseur) et <strong>{{engraisseur_nom}}</strong> (engraisseur).</p><p>Race : <strong>{{race_bovin}}</strong> — Nombre de têtes : <strong>{{nombre_tetes}}</strong><br/>Prix convenu par tête : <strong>{{prix_tete}} FCFA</strong><br/>Transfert prévu le : {{date_transfert}}</p><p>Le naisseur garantit que les animaux sont sains, vaccinés et identifiés. L"engraisseur prend en charge les frais d"alimentation et les soins vétérinaires jusqu"à la vente.</p><div class="signature"><p>Le Naisseur :</p><p>L"Engraisseur :</p></div></div>`,
  },
  {
    code: 'elev_service_abattage',
    name: "Contrat de Service d\"Abattage et Découpe",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Contrat de prestation d'abattage et de découpe d'animaux d'élevage par un abattoir ou un boucher professionnel.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'abattoir_nom', label: "Nom de l\"abattoir/prestataire", type: 'text', required: true },
      { key: 'client_abattage', label: "Nom du client propriétaire des animaux", type: 'text', required: true },
      { key: 'espece_animal', label: "Espèce animale à abattre", type: 'text', required: true },
      { key: 'nombre_animaux', label: "Nombre d\"animaux", type: 'text', required: true },
      { key: 'date_abattage', label: "Date d\"abattage prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"ABATTAGE ET DÉCOUPE</h1><p>Entre <strong>{{abattoir_nom}}</strong> (prestataire) et <strong>{{client_abattage}}</strong> (client).</p><p>Espèce : <strong>{{espece_animal}}</strong> — Nombre : <strong>{{nombre_animaux}}</strong><br/>Date d"abattage : {{date_abattage}}</p><p>Le prestataire s"engage à réaliser l"abattage dans des conditions hygiéniques conformes à la réglementation, à procéder à l"inspection ante et post-mortem et à restituer au client les pièces de viande nettes et emballées.</p><div class="signature"><p>L"Abattoir :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'elev_ferme_avicole',
    name: "Accord de Ferme Avicole (Poulets de Chair)",
    category: 'agro_environnement',
    price: 4500,
    priceMax: 13500,
    description: "Accord d'exploitation d'une ferme avicole pour la production de poulets de chair en intégration ou en autonomie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'aviculteur_nom', label: "Nom de l\"aviculteur", type: 'text', required: true },
      { key: 'integrateur_nom', label: "Nom de l\"intégrateur ou partenaire technique", type: 'text', required: true },
      { key: 'capacite_batiment', label: "Capacité du bâtiment (nombre de places)", type: 'text', required: true },
      { key: 'prix_kg_vif', label: "Prix de vente convenu au kg vif (FCFA)", type: 'text', required: true },
      { key: 'date_premier_lot', label: "Date de mise en place du premier lot", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FERME AVICOLE - POULETS DE CHAIR</h1><p>Entre <strong>{{aviculteur_nom}}</strong> (aviculteur) et <strong>{{integrateur_nom}}</strong> (partenaire technique).</p><p>Capacité : <strong>{{capacite_batiment}}</strong> places<br/>Prix au kg vif : <strong>{{prix_kg_vif}} FCFA</strong><br/>Premier lot : {{date_premier_lot}}</p><p>L"intégrateur fournit les poussins, l"aliment et l"encadrement technique. L"aviculteur fournit le bâtiment, la main-d"oeuvre et les charges d"exploitation courantes.</p><div class="signature"><p>L"Aviculteur :</p><p>L"Intégrateur :</p></div></div>`,
  },
  {
    code: 'elev_collecte_oeufs',
    name: "Contrat de Service de Collecte d\"Oeufs",
    category: 'agro_environnement',
    price: 2000,
    priceMax: 6000,
    description: "Contrat de collecte et de distribution d'oeufs entre un producteur avicole et un collecteur/distributeur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'producteur_oeufs', label: "Nom du producteur d\"oeufs", type: 'text', required: true },
      { key: 'collecteur_nom', label: "Nom du collecteur/distributeur", type: 'text', required: true },
      { key: 'volume_hebdo_oeufs', label: "Volume hebdomadaire collecté (nombre d\"oeufs)", type: 'text', required: true },
      { key: 'prix_oeuf', label: "Prix à l\"oeuf (FCFA)", type: 'text', required: true },
      { key: 'date_debut_collecte', label: "Date de début de collecte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE COLLECTE D"OEUFS</h1><p>Entre <strong>{{producteur_oeufs}}</strong> (producteur) et <strong>{{collecteur_nom}}</strong> (collecteur).</p><p>Volume hebdomadaire : <strong>{{volume_hebdo_oeufs}} oeufs</strong> au prix de <strong>{{prix_oeuf}} FCFA/oeuf</strong>.<br/>Début de collecte : {{date_debut_collecte}}</p><p>Le collecteur s"engage à enlever les oeufs trois fois par semaine minimum et à payer le producteur dans les 72h suivant la collecte.</p><div class="signature"><p>Le Producteur :</p><p>Le Collecteur :</p></div></div>`,
  },
  {
    code: 'elev_production_laitiere',
    name: "Accord de Service de Production Laitière",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 12000,
    description: "Accord de production et de livraison de lait cru entre un éleveur laitier et une laiterie ou un collecteur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'eleveur_laitier', label: "Nom de l\"éleveur laitier", type: 'text', required: true },
      { key: 'laiterie_nom', label: "Nom de la laiterie ou du collecteur", type: 'text', required: true },
      { key: 'volume_journalier', label: "Volume journalier garanti (litres)", type: 'text', required: true },
      { key: 'prix_litre', label: "Prix d\"achat par litre (FCFA)", type: 'text', required: true },
      { key: 'date_debut_livraison', label: "Date de début des livraisons", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PRODUCTION LAITIÈRE</h1><p>Entre <strong>{{eleveur_laitier}}</strong> (éleveur) et <strong>{{laiterie_nom}}</strong> (acheteur).</p><p>Volume journalier garanti : <strong>{{volume_journalier}} litres</strong> au prix de <strong>{{prix_litre}} FCFA/litre</strong>.<br/>Début des livraisons : {{date_debut_livraison}}</p><p>Le lait livré doit respecter les critères de qualité (taux butyreux, teneur en germes) définis en annexe. Tout lot non conforme est refusé sans pénalité pour l"acheteur.</p><div class="signature"><p>L"Eleveur :</p><p>La Laiterie :</p></div></div>`,
  },
  {
    code: 'elev_cooperative_laitiere',
    name: "Contrat de Coopérative Laitière",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat constitutif d'une coopérative laitière regroupant des éleveurs pour la collecte et la transformation collective du lait.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'nom_cooperative_laitiere', label: "Nom de la coopérative laitière", type: 'text', required: true },
      { key: 'nombre_adherents', label: "Nombre d\"adhérents fondateurs", type: 'text', required: true },
      { key: 'capacite_collecte', label: "Capacité de collecte quotidienne (litres)", type: 'text', required: true },
      { key: 'siege_cooperative', label: "Siège de la coopérative", type: 'text', required: true },
      { key: 'date_creation_coop', label: "Date de création", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE COOPÉRATIVE LAITIÈRE</h1><p>Les soussignés, au nombre de <strong>{{nombre_adherents}}</strong>, fondent la coopérative laitière <strong>{{nom_cooperative_laitiere}}</strong>, dont le siège est établi à <strong>{{siege_cooperative}}</strong>.</p><p>Capacité de collecte quotidienne : <strong>{{capacite_collecte}} litres</strong><br/>Date de création : {{date_creation_coop}}</p><p>La coopérative a pour mission la collecte, le refroidissement, la transformation et la commercialisation du lait de ses membres selon des règles de partage équitable des bénéfices.</p><div class="signature"><p>Les Membres Fondateurs :</p></div></div>`,
  },
  {
    code: 'elev_veterinaire_terrain',
    name: "Accord de Service de Vétérinaire de Terrain",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 10500,
    description: "Accord de suivi sanitaire régulier d'un élevage par un vétérinaire praticien de terrain.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'veterinaire_nom', label: "Nom et numéro d\"ordre du vétérinaire", type: 'text', required: true },
      { key: 'eleveur_suivi', label: "Nom de l\"éleveur bénéficiaire", type: 'text', required: true },
      { key: 'type_elevage_suivi', label: "Type d\"élevage suivi", type: 'text', required: true },
      { key: 'frequence_visites', label: "Fréquence des visites de terrain", type: 'text', required: true },
      { key: 'honoraires_mensuels', label: "Honoraires mensuels forfaitaires (FCFA)", type: 'text', required: true },
      { key: 'date_debut_suivi', label: "Date de début du suivi", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE VÉTÉRINAIRE DE TERRAIN</h1><p>Entre Dr. <strong>{{veterinaire_nom}}</strong> et <strong>{{eleveur_suivi}}</strong>.</p><p>Elevage suivi : <strong>{{type_elevage_suivi}}</strong><br/>Fréquence des visites : <strong>{{frequence_visites}}</strong><br/>Honoraires mensuels : <strong>{{honoraires_mensuels}} FCFA</strong><br/>Début du suivi : {{date_debut_suivi}}</p><p>Le vétérinaire s"engage à assurer le suivi sanitaire de l"élevage, à prescrire les traitements nécessaires et à rédiger des comptes rendus de visite.</p><div class="signature"><p>Le Vétérinaire :</p><p>L"Eleveur :</p></div></div>`,
  },
  {
    code: 'elev_vaccination_animale',
    name: "Contrat de Service de Vaccination Animale",
    category: 'agro_environnement',
    price: 2500,
    priceMax: 7500,
    description: "Contrat de campagne de vaccination des animaux d'élevage contre les maladies endémiques ciblées.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'vaccinateur_nom', label: "Nom du vaccinateur ou de l\"équipe", type: 'text', required: true },
      { key: 'eleveur_vaccine', label: "Nom de l\"éleveur bénéficiaire", type: 'text', required: true },
      { key: 'maladie_ciblee', label: "Maladie ciblée par la vaccination", type: 'text', required: true },
      { key: 'nombre_animaux_vaccines', label: "Nombre d\"animaux à vacciner", type: 'text', required: true },
      { key: 'date_vaccination', label: "Date de la campagne de vaccination", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE VACCINATION ANIMALE</h1><p>Entre <strong>{{vaccinateur_nom}}</strong> (vaccinateur) et <strong>{{eleveur_vaccine}}</strong> (éleveur).</p><p>Maladie ciblée : <strong>{{maladie_ciblee}}</strong><br/>Nombre d"animaux à vacciner : <strong>{{nombre_animaux_vaccines}}</strong><br/>Date prévue : {{date_vaccination}}</p><p>Le vaccinateur fournit les vaccins homologués, effectue les injections dans les règles de l"art et remet un carnet de vaccination à l"éleveur. La conservation à froid des vaccins est à la charge du vaccinateur jusqu"au moment de l"injection.</p><div class="signature"><p>Le Vaccinateur :</p><p>L"Eleveur :</p></div></div>`,
  },
  {
    code: 'elev_distribution_medicaments',
    name: "Accord de Distribution de Médicaments Vétérinaires",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 10500,
    description: "Accord de distribution exclusive ou préférentielle de médicaments vétérinaires entre un grossiste et un distributeur local.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'grossiste_nom', label: "Nom du grossiste fournisseur", type: 'text', required: true },
      { key: 'distributeur_local', label: "Nom du distributeur local", type: 'text', required: true },
      { key: 'gamme_produits', label: "Gamme de produits concernée", type: 'text', required: true },
      { key: 'zone_distribution', label: "Zone géographique de distribution", type: 'text', required: true },
      { key: 'date_debut_distribution', label: "Date de début de la distribution", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTION DE MÉDICAMENTS VÉTÉRINAIRES</h1><p>Entre <strong>{{grossiste_nom}}</strong> (grossiste) et <strong>{{distributeur_local}}</strong> (distributeur).</p><p>Gamme : <strong>{{gamme_produits}}</strong><br/>Zone : <strong>{{zone_distribution}}</strong><br/>Début : {{date_debut_distribution}}</p><p>Le distributeur s"engage à respecter la chaîne du froid, les dates de péremption et les règles de vente applicables aux médicaments vétérinaires. Il dispose d"une agrément en cours de validité.</p><div class="signature"><p>Le Grossiste :</p><p>Le Distributeur :</p></div></div>`,
  },
  {
    code: 'elev_insemination_artificielle',
    name: "Contrat de Service d\"Insémination Artificielle Animale",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Contrat de prestation d'insémination artificielle pour l'amélioration génétique du cheptel.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'technicien_ia', label: "Nom du technicien en insémination artificielle", type: 'text', required: true },
      { key: 'eleveur_ia', label: "Nom de l\"éleveur bénéficiaire", type: 'text', required: true },
      { key: 'race_semence', label: "Race de la semence utilisée", type: 'text', required: true },
      { key: 'nombre_femelles', label: "Nombre de femelles à inséminées", type: 'text', required: true },
      { key: 'date_intervention', label: "Date d\"intervention prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"INSÉMINATION ARTIFICIELLE</h1><p>Entre <strong>{{technicien_ia}}</strong> (technicien) et <strong>{{eleveur_ia}}</strong> (éleveur).</p><p>Race de semence : <strong>{{race_semence}}</strong><br/>Nombre de femelles : <strong>{{nombre_femelles}}</strong><br/>Date d"intervention : {{date_intervention}}</p><p>Le technicien utilise des paillettes de semence certifiées et insémine selon les protocoles sanitaires en vigueur. Le taux de gestation est constaté conjointement 45 jours après l"intervention.</p><div class="signature"><p>Le Technicien :</p><p>L"Eleveur :</p></div></div>`,
  },
  {
    code: 'elev_laboratoire_veterinaire',
    name: "Accord de Service de Laboratoire Vétérinaire",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 12000,
    description: "Accord de partenariat entre un laboratoire vétérinaire et un éleveur ou groupement pour des analyses sanitaires régulières.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'laboratoire_nom', label: "Nom du laboratoire vétérinaire", type: 'text', required: true },
      { key: 'client_labo', label: "Nom de l\"éleveur ou du groupement", type: 'text', required: true },
      { key: 'analyses_prevues', label: "Types d\"analyses prévues", type: 'textarea', required: true },
      { key: 'frequence_analyses', label: "Fréquence des analyses (mensuelle/trimestrielle)", type: 'text', required: true },
      { key: 'date_premier_prelevement', label: "Date du premier prélèvement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE LABORATOIRE VÉTÉRINAIRE</h1><p>Entre <strong>{{laboratoire_nom}}</strong> (laboratoire) et <strong>{{client_labo}}</strong> (client).</p><p>Fréquence : <strong>{{frequence_analyses}}</strong><br/>Premier prélèvement : {{date_premier_prelevement}}</p><h2>Analyses prévues</h2><p>{{analyses_prevues}}</p><p>Les résultats sont transmis dans un délai maximum de 7 jours ouvrables après réception des échantillons. Le laboratoire garantit la confidentialité des résultats.</p><div class="signature"><p>Le Laboratoire :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'elev_fourniture_aliments_betail',
    name: "Contrat de Fourniture d\"Aliments Bétail",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Contrat de fourniture régulière d'aliments composés pour bétail entre un fabricant ou grossiste et un éleveur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'fournisseur_aliment_betail', label: "Nom du fournisseur d\"aliments bétail", type: 'text', required: true },
      { key: 'eleveur_client', label: "Nom de l\"éleveur client", type: 'text', required: true },
      { key: 'type_aliment_betail', label: "Type d\"aliment (concentré/foin/CMV)", type: 'text', required: true },
      { key: 'quantite_mensuelle_betail', label: "Quantité mensuelle (sacs ou kg)", type: 'text', required: true },
      { key: 'prix_unitaire_aliment', label: "Prix unitaire (FCFA/sac ou kg)", type: 'text', required: true },
      { key: 'date_premiere_livraison', label: "Date de première livraison", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE FOURNITURE D"ALIMENTS BÉTAIL</h1><p>Entre <strong>{{fournisseur_aliment_betail}}</strong> (fournisseur) et <strong>{{eleveur_client}}</strong> (client).</p><p>Type d"aliment : <strong>{{type_aliment_betail}}</strong><br/>Quantité mensuelle : <strong>{{quantite_mensuelle_betail}}</strong><br/>Prix unitaire : <strong>{{prix_unitaire_aliment}} FCFA</strong><br/>Première livraison : {{date_premiere_livraison}}</p><p>Le fournisseur garantit la composition nutritionnelle et la conformité des produits aux normes en vigueur. Les livraisons s"effectuent à la ferme, franco de port.</p><div class="signature"><p>Le Fournisseur :</p><p>L"Eleveur :</p></div></div>`,
  },
  {
    code: 'elev_transport_animaux',
    name: "Accord de Service de Transport d\"Animaux",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Accord de transport d'animaux vivants entre un éleveur et un transporteur agréé, dans le respect du bien-être animal.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'transporteur_animaux', label: "Nom du transporteur d\"animaux", type: 'text', required: true },
      { key: 'proprietaire_animaux', label: "Nom du propriétaire des animaux", type: 'text', required: true },
      { key: 'espece_transportee', label: "Espèce animale transportée", type: 'text', required: true },
      { key: 'trajet_animaux', label: "Trajet (lieu de chargement - destination)", type: 'text', required: true },
      { key: 'date_transport', label: "Date de transport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TRANSPORT D"ANIMAUX</h1><p>Entre <strong>{{transporteur_animaux}}</strong> (transporteur) et <strong>{{proprietaire_animaux}}</strong> (propriétaire).</p><p>Espèce : <strong>{{espece_transportee}}</strong><br/>Trajet : <strong>{{trajet_animaux}}</strong><br/>Date : {{date_transport}}</p><p>Le transporteur dispose d"un véhicule agréé pour le transport d"animaux. Il s"engage à respecter les densités maximales de chargement, à abreuver les animaux et à les livrer en bonne santé à destination.</p><div class="signature"><p>Le Transporteur :</p><p>Le Propriétaire :</p></div></div>`,
  },
  {
    code: 'elev_abattoir_industriel',
    name: "Contrat de Service d\"Abattoir Industriel",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Contrat de prestation de service avec un abattoir industriel pour l'abattage et le conditionnement de viande à grande échelle.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 46,
    fieldsJson: F([
      { key: 'abattoir_industriel_nom', label: "Nom de l\"abattoir industriel", type: 'text', required: true },
      { key: 'client_abattoir', label: "Nom du client (éleveur ou négoce)", type: 'text', required: true },
      { key: 'volume_mensuel_abattage', label: "Volume mensuel d\"abattage (têtes)", type: 'text', required: true },
      { key: 'tarif_prestation', label: "Tarif de prestation par tête (FCFA)", type: 'text', required: true },
      { key: 'date_debut_contrat_abattoir', label: "Date de début du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"ABATTOIR INDUSTRIEL</h1><p>Entre <strong>{{abattoir_industriel_nom}}</strong> et <strong>{{client_abattoir}}</strong>.</p><p>Volume mensuel : <strong>{{volume_mensuel_abattage}} têtes</strong><br/>Tarif par tête : <strong>{{tarif_prestation}} FCFA</strong><br/>Début : {{date_debut_contrat_abattoir}}</p><p>L"abattoir s"engage à traiter les animaux selon les normes d"hygiène agréées, à réaliser l"inspection vétérinaire obligatoire et à fournir au client les certificats sanitaires réglementaires pour chaque lot abattu.</p><div class="signature"><p>L"Abattoir :</p><p>Le Client :</p></div></div>`,
  },
  {
    code: 'elev_certification_halal',
    name: "Accord de Certification Viande Halal",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Accord de certification halal pour une unité d'abattage ou de transformation de viande selon les rites islamiques.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'organisme_halal', label: "Organisme de certification halal", type: 'text', required: true },
      { key: 'unite_certifiee', label: "Unité d\"abattage ou de transformation certifiée", type: 'text', required: true },
      { key: 'portee_certification', label: "Portée de la certification (espèces/produits)", type: 'text', required: true },
      { key: 'validite_certificat', label: "Durée de validité du certificat (mois)", type: 'text', required: true },
      { key: 'date_certification_halal', label: "Date de délivrance de la certification", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION VIANDE HALAL</h1><p>L"organisme <strong>{{organisme_halal}}</strong> certifie que <strong>{{unite_certifiee}}</strong> est conforme aux exigences de la certification halal.</p><p>Portée : <strong>{{portee_certification}}</strong><br/>Validité : <strong>{{validite_certificat}} mois</strong> à compter du {{date_certification_halal}}</p><p>L"unité certifiée s"engage à maintenir en permanence les conditions ayant permis l"obtention du certificat et à accepter les audits inopinés de l"organisme certificateur.</p><div class="signature"><p>L"Organisme :</p><p>L"Unité Certifiée :</p></div></div>`,
  },
  {
    code: 'elev_suivi_zoosanitaire_porcin',
    name: "Contrat de Suivi Zoo-Sanitaire (Elevage Porcin)",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 12000,
    description: "Contrat de suivi sanitaire spécialisé pour un élevage porcin, incluant la prévention des maladies et la gestion des biosécurités.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'veterinaire_porcin', label: "Nom du vétérinaire spécialiste porcin", type: 'text', required: true },
      { key: 'elevage_porcin_nom', label: "Nom et localisation de l\"élevage porcin", type: 'text', required: true },
      { key: 'effectif_porcin', label: "Effectif du troupeau porcin (truies reproductrices)", type: 'text', required: true },
      { key: 'programme_sante', label: "Programme de santé préventif retenu", type: 'textarea', required: true },
      { key: 'date_debut_suivi_porcin', label: "Date de début du suivi", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SUIVI ZOO-SANITAIRE - ELEVAGE PORCIN</h1><p>Dr. <strong>{{veterinaire_porcin}}</strong> assure le suivi de l"élevage <strong>{{elevage_porcin_nom}}</strong>.</p><p>Effectif : <strong>{{effectif_porcin}} truies reproductrices</strong><br/>Début du suivi : {{date_debut_suivi_porcin}}</p><h2>Programme de santé préventif</h2><p>{{programme_sante}}</p><p>Le vétérinaire s"engage à des visites bimensuelles et à une disponibilité d"urgence 7j/7 en cas d"épisode pathologique sévère.</p><div class="signature"><p>Le Vétérinaire :</p><p>L"Eleveur :</p></div></div>`,
  },
  {
    code: 'elev_aquaculture_continentale',
    name: "Accord de Service d\"Aquaculture Continentale (Escargots/Grenouilles)",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 12000,
    description: "Accord d'exploitation d'une unité d'aquaculture continentale spécialisée dans l'héliciculture ou la grenouillère.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 38,
    fieldsJson: F([
      { key: 'exploitant_continentale', label: "Nom de l\"exploitant", type: 'text', required: true },
      { key: 'espece_elevage_cont', label: "Espèce élevée (escargots/grenouilles/autre)", type: 'text', required: true },
      { key: 'superficie_unite', label: "Superficie de l\"unité de production (m²)", type: 'text', required: true },
      { key: 'production_annuelle_cont', label: "Production annuelle visée (kg)", type: 'text', required: true },
      { key: 'date_demarrage_cont', label: "Date de démarrage", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D"AQUACULTURE CONTINENTALE</h1><p><strong>{{exploitant_continentale}}</strong> exploite une unité de production de <strong>{{espece_elevage_cont}}</strong>, d"une superficie de <strong>{{superficie_unite}} m²</strong>.</p><p>Production annuelle visée : <strong>{{production_annuelle_cont}} kg</strong><br/>Démarrage : {{date_demarrage_cont}}</p><p>L"exploitant s"engage à respecter les normes zootechniques de l"espèce, les conditions d"hygiène et les dispositions environnementales en vigueur.</p><div class="signature"><p>L"Exploitant :</p><p>L"Autorité de Tutelle :</p></div></div>`,
  },
  {
    code: 'elev_contrat_lapins',
    name: "Contrat d\"Elevage de Lapins",
    category: 'agro_environnement',
    price: 2000,
    priceMax: 6000,
    description: "Contrat d'exploitation d'un élevage cuniculicole pour la production de viande de lapin.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 42,
    fieldsJson: F([
      { key: 'cuniculiculteur_nom', label: "Nom de l\"éleveur de lapins", type: 'text', required: true },
      { key: 'partenaire_technique', label: "Nom du partenaire technique ou acheteur", type: 'text', required: true },
      { key: 'nombre_cages_lapins', label: "Nombre de cages de production", type: 'text', required: true },
      { key: 'prix_kg_lapin', label: "Prix de vente du kg de lapin vif (FCFA)", type: 'text', required: true },
      { key: 'date_debut_elevage_lapins', label: "Date de démarrage de l\"élevage", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"ELEVAGE DE LAPINS</h1><p>Entre <strong>{{cuniculiculteur_nom}}</strong> (éleveur) et <strong>{{partenaire_technique}}</strong> (partenaire).</p><p>Nombre de cages : <strong>{{nombre_cages_lapins}}</strong><br/>Prix au kg vif : <strong>{{prix_kg_lapin}} FCFA</strong><br/>Démarrage : {{date_debut_elevage_lapins}}</p><p>Le partenaire fournit l"appui technique et les débouchés commerciaux. L"éleveur est responsable de l"alimentation, de l"entretien et des soins quotidiens des animaux.</p><div class="signature"><p>L"Eleveur :</p><p>Le Partenaire :</p></div></div>`,
  },
  {
    code: 'elev_pisciculture_etang',
    name: "Accord de Service de Pisciculture en Etang",
    category: 'agro_environnement',
    price: 4500,
    priceMax: 13500,
    description: "Accord d'exploitation d'un étang piscicole pour la production de poissons d'eau douce.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'pisciculteur_nom', label: "Nom du pisciculteur", type: 'text', required: true },
      { key: 'superficie_etang', label: "Superficie de l\"étang (m²)", type: 'text', required: true },
      { key: 'espece_poisson_etang', label: "Espèce de poisson élevée", type: 'text', required: true },
      { key: 'rendement_vise', label: "Rendement visé (kg/m²/an)", type: 'text', required: true },
      { key: 'date_mise_en_charge', label: "Date de mise en charge de l\"étang", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PISCICULTURE EN ETANG</h1><p><strong>{{pisciculteur_nom}}</strong> exploite un étang de <strong>{{superficie_etang}} m²</strong> dédié à l"élevage de <strong>{{espece_poisson_etang}}</strong>.</p><p>Rendement visé : <strong>{{rendement_vise}} kg/m²/an</strong><br/>Mise en charge : {{date_mise_en_charge}}</p><p>Le pisciculteur s"engage à gérer la qualité de l"eau, à alimenter les poissons régulièrement et à effectuer les traitements sanitaires nécessaires pour atteindre le rendement cible.</p><div class="signature"><p>Le Pisciculteur :</p><p>Le Partenaire ou Financeur :</p></div></div>`,
  },
  {
    code: 'elev_formation_eleveurs',
    name: "Contrat de Service de Formation Eleveurs",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 12000,
    description: "Contrat de formation professionnelle des éleveurs sur les techniques d'élevage moderne, la nutrition animale et la santé des troupeaux.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'organisme_formation', label: "Organisme de formation", type: 'text', required: true },
      { key: 'groupe_eleveurs', label: "Groupe d\"éleveurs bénéficiaires", type: 'text', required: true },
      { key: 'themes_formation', label: "Thèmes de la formation", type: 'textarea', required: true },
      { key: 'duree_formation', label: "Durée de la formation (jours)", type: 'text', required: true },
      { key: 'date_debut_formation', label: "Date de début de la formation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE FORMATION DES ELEVEURS</h1><p>Entre <strong>{{organisme_formation}}</strong> (formateur) et <strong>{{groupe_eleveurs}}</strong> (bénéficiaires).</p><p>Durée : <strong>{{duree_formation}} jours</strong> à partir du {{date_debut_formation}}</p><h2>Thèmes de formation</h2><p>{{themes_formation}}</p><p>A l"issue de la formation, un certificat de participation est remis à chaque éleveur ayant suivi au moins 80% des sessions.</p><div class="signature"><p>L"Organisme de Formation :</p><p>Le Représentant du Groupe :</p></div></div>`,
  },
  {
    code: 'elev_ferme_didactique',
    name: "Accord de Ferme Didactique Agropastorale",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Accord d'exploitation d'une ferme à vocation pédagogique pour la formation pratique des agriculteurs et étudiants en agronomie.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 35,
    fieldsJson: F([
      { key: 'gestionnaire_ferme_did', label: "Nom du gestionnaire de la ferme didactique", type: 'text', required: true },
      { key: 'institution_partenaire', label: "Institution partenaire (école/ONG/ministère)", type: 'text', required: true },
      { key: 'modules_pedagogiques', label: "Modules pédagogiques proposés", type: 'textarea', required: true },
      { key: 'capacite_accueil', label: "Capacité d\"accueil (stagiaires par session)", type: 'text', required: true },
      { key: 'date_ouverture_ferme', label: "Date d\"ouverture de la ferme", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FERME DIDACTIQUE AGROPASTORALE</h1><p>Entre <strong>{{gestionnaire_ferme_did}}</strong> (gestionnaire) et <strong>{{institution_partenaire}}</strong> (institution partenaire).</p><p>Capacité d"accueil : <strong>{{capacite_accueil}} stagiaires</strong> par session<br/>Ouverture : {{date_ouverture_ferme}}</p><h2>Modules pédagogiques</h2><p>{{modules_pedagogiques}}</p><p>La ferme est ouverte aux visites encadrées et aux stages pratiques. Les deux parties définissent conjointement le programme pédagogique annuel.</p><div class="signature"><p>Le Gestionnaire :</p><p>L"Institution Partenaire :</p></div></div>`,
  },
  {
    code: 'elev_plan_sante_animale',
    name: "Plan de Santé Animale de l\"Exploitation",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Document de planification sanitaire annuel pour une exploitation d'élevage, élaboré conjointement avec le vétérinaire traitant.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'exploitation_nom', label: "Nom et localisation de l\"exploitation", type: 'text', required: true },
      { key: 'veterinaire_traitant', label: "Nom du vétérinaire traitant", type: 'text', required: true },
      { key: 'effectif_total', label: "Effectif total de l\"exploitation (toutes espèces)", type: 'text', required: true },
      { key: 'programme_preventif', label: "Programme préventif annuel (vaccinations, vermifugations)", type: 'textarea', required: true },
      { key: 'date_elaboration_plan', label: "Date d\"élaboration du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE SANTÉ ANIMALE DE L"EXPLOITATION</h1><p>Exploitation : <strong>{{exploitation_nom}}</strong><br/>Vétérinaire traitant : Dr. <strong>{{veterinaire_traitant}}</strong><br/>Effectif total : <strong>{{effectif_total}}</strong> animaux<br/>Date : {{date_elaboration_plan}}</p><h2>Programme préventif annuel</h2><p>{{programme_preventif}}</p><p>Ce plan est révisé annuellement et en cas d"apparition d"une nouvelle maladie sur l"exploitation ou dans la zone. Il est joint au registre d"élevage.</p><div class="signature"><p>Le Vétérinaire :</p><p>L"Eleveur :</p></div></div>`,
  },
  {
    code: 'elev_rapport_performance_troupeau',
    name: "Rapport de Performance Troupeau",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 10500,
    description: "Rapport technique périodique évaluant les performances zootechniques d'un troupeau (croissance, reproduction, mortalité).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 44,
    fieldsJson: F([
      { key: 'redacteur_perf', label: "Nom du rédacteur (technicien ou vétérinaire)", type: 'text', required: true },
      { key: 'troupeau_identifiant', label: "Identification du troupeau évalué", type: 'text', required: true },
      { key: 'periode_evaluation', label: "Période d\"évaluation", type: 'text', required: true },
      { key: 'indicateurs_performance', label: "Principaux indicateurs de performance", type: 'textarea', required: true },
      { key: 'date_rapport_perf', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE TROUPEAU</h1><p>Rédacteur : <strong>{{redacteur_perf}}</strong><br/>Troupeau : <strong>{{troupeau_identifiant}}</strong><br/>Période : <strong>{{periode_evaluation}}</strong><br/>Date : {{date_rapport_perf}}</p><h2>Indicateurs de performance</h2><p>{{indicateurs_performance}}</p><p>Ce rapport est destiné à l"éleveur et à tout partenaire financier ou technique. Il sert de base à l"ajustement du plan de conduite d"élevage.</p><div class="signature"><p>Le Rédacteur :</p><p>L"Eleveur :</p></div></div>`,
  },
  {
    code: 'elev_pharmacie_veterinaire',
    name: "Convention de Pharmacie Vétérinaire Agréée",
    category: 'agro_environnement',
    price: 4500,
    priceMax: 13500,
    description: "Convention d'agrément et de fonctionnement d'une pharmacie vétérinaire selon les dispositions réglementaires nationales.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'pharmacie_vet_nom', label: "Nom de la pharmacie vétérinaire", type: 'text', required: true },
      { key: 'responsable_technique', label: "Nom du responsable technique (vétérinaire ou pharmacien)", type: 'text', required: true },
      { key: 'adresse_pharmacie', label: "Adresse de la pharmacie", type: 'text', required: true },
      { key: 'numero_agrement', label: "Numéro d\"agrément délivré", type: 'text', required: true },
      { key: 'date_agrement', label: "Date de délivrance de l\"agrément", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PHARMACIE VÉTÉRINAIRE AGRÉÉE</h1><p>La pharmacie vétérinaire <strong>{{pharmacie_vet_nom}}</strong>, sous la responsabilité technique de <strong>{{responsable_technique}}</strong>, sise à <strong>{{adresse_pharmacie}}</strong>, est agréée sous le N° <strong>{{numero_agrement}}</strong> en date du {{date_agrement}}.</p><p>L"établissement est autorisé à détenir, délivrer et vendre des médicaments vétérinaires conformément à la liste des spécialités autorisées en vigueur. Tout manquement entraîne la suspension ou le retrait de l"agrément.</p><div class="signature"><p>L"Autorité Vétérinaire :</p><p>Le Responsable Technique :</p></div></div>`,
  },
  {
    code: 'elev_charte_bienetre_animal',
    name: "Charte de Bien-Etre Animal en Elevage",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Charte d'engagement volontaire d'un éleveur ou d'une filière pour le respect des principes de bien-être animal.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 38,
    fieldsJson: F([
      { key: 'signataire_charte', label: "Nom du signataire (éleveur ou organisation)", type: 'text', required: true },
      { key: 'type_production_charte', label: "Type de production concernée", type: 'text', required: true },
      { key: 'engagements_bea', label: "Engagements de bien-être animal pris", type: 'textarea', required: true },
      { key: 'organisme_garant', label: "Organisme garant de la charte", type: 'text', required: true },
      { key: 'date_signature_charte', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE BIEN-ETRE ANIMAL EN ELEVAGE</h1><p>Signataire : <strong>{{signataire_charte}}</strong><br/>Type de production : <strong>{{type_production_charte}}</strong><br/>Garant : <strong>{{organisme_garant}}</strong><br/>Date : {{date_signature_charte}}</p><h2>Engagements pris</h2><p>{{engagements_bea}}</p><p>Le signataire accepte les contrôles périodiques de l"organisme garant et s"engage à corriger tout écart constaté dans un délai raisonnable. La charte est renouvelable annuellement.</p><div class="signature"><p>Le Signataire :</p><p>L"Organisme Garant :</p></div></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 41b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
