import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── DROIT DE LA FAMILLE (25 templates, préfixe fam_, catégorie juridique_admin) ───

  {
    code: 'fam_mariage_communaute',
    name: "Contrat de mariage sous régime de la communauté",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de mariage établissant le régime de la communauté des biens entre époux, conforme au droit ivoirien et OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_epoux', label: "Nom complet de l'époux", type: 'text', required: true },
      { key: 'nom_epouse', label: "Nom complet de l'épouse", type: 'text', required: true },
      { key: 'date_mariage', label: "Date du mariage", type: 'date', required: true },
      { key: 'lieu_mariage', label: "Lieu de célébration du mariage", type: 'text', required: true },
      { key: 'biens_communs', label: "Description des biens mis en commun", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARIAGE — RÉGIME DE LA COMMUNAUTÉ</h1><p>Entre <strong>{{nom_epoux}}</strong> et <strong>{{nom_epouse}}</strong>, futurs époux, il est convenu ce qui suit :</p><p>Le mariage célébré le {{date_mariage}} à {{lieu_mariage}} sera soumis au régime de la communauté des biens conformément aux dispositions du Code Civil applicable en République de Côte d'Ivoire.</p><p>Biens mis en commun : {{biens_communs}}</p><p>Fait en deux exemplaires originaux, à Abidjan, le {{date_mariage}}.</p><p>Signature de l'époux : ___________________ Signature de l'épouse : ___________________</p></div>`,
  },

  {
    code: 'fam_mariage_separation',
    name: "Contrat de mariage sous régime de séparation de biens",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de mariage établissant la séparation totale des biens entre époux, chaque époux conservant l'administration et la jouissance de ses propres biens.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_epoux', label: "Nom complet de l'époux", type: 'text', required: true },
      { key: 'nom_epouse', label: "Nom complet de l'épouse", type: 'text', required: true },
      { key: 'date_mariage', label: "Date du mariage", type: 'date', required: true },
      { key: 'lieu_mariage', label: "Lieu de célébration", type: 'text', required: true },
      { key: 'biens_epoux', label: "Biens propres de l'époux", type: 'textarea', required: false },
      { key: 'biens_epouse', label: "Biens propres de l'épouse", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARIAGE — RÉGIME DE SÉPARATION DE BIENS</h1><p>Entre <strong>{{nom_epoux}}</strong> et <strong>{{nom_epouse}}</strong>, futurs époux :</p><p>Il est expressément convenu que le mariage célébré le {{date_mariage}} à {{lieu_mariage}} sera régi par le régime de la séparation de biens.</p><p>Chaque époux conserve la pleine propriété, l'administration et la libre disposition de tous ses biens présents et futurs.</p><p>Biens propres de l'époux : {{biens_epoux}}</p><p>Biens propres de l'épouse : {{biens_epouse}}</p><p>Fait à Abidjan, le {{date_mariage}}.</p></div>`,
  },

  {
    code: 'fam_mariage_polygamique',
    name: "Contrat de mariage polygamique (droit coutumier CI)",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de mariage polygamique selon le droit coutumier ivoirien, précisant les droits et obligations entre le mari et chacune de ses épouses.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_mari', label: "Nom complet du mari", type: 'text', required: true },
      { key: 'nom_epouse_nouvelle', label: "Nom complet de la nouvelle épouse", type: 'text', required: true },
      { key: 'date_union', label: "Date de l'union", type: 'date', required: true },
      { key: 'rang_epouse', label: "Rang de l'épouse (2ème, 3ème...)", type: 'text', required: true },
      { key: 'dot_convenue', label: "Dot convenue et modalités", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARIAGE POLYGAMIQUE — DROIT COUTUMIER</h1><p>Le présent contrat est conclu entre <strong>{{nom_mari}}</strong> et <strong>{{nom_epouse_nouvelle}}</strong> ({{rang_epouse}} épouse), le {{date_union}}.</p><p>Conformément aux usages coutumiers reconnus en République de Côte d'Ivoire, les parties conviennent des droits et obligations suivants :</p><p>Dot convenue : {{dot_convenue}}</p><p>Le mari s'engage à traiter équitablement toutes ses épouses conformément aux obligations coutumières applicables.</p><p>Fait à Abidjan, le {{date_union}}.</p></div>`,
  },

  {
    code: 'fam_reconnaissance_paternite',
    name: "Accord de reconnaissance de paternité",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Acte de reconnaissance volontaire de paternité d'un enfant naturel, établi devant officier d'état civil conformément au droit ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'nom_pere', label: "Nom complet du père", type: 'text', required: true },
      { key: 'nom_enfant', label: "Nom complet de l'enfant", type: 'text', required: true },
      { key: 'date_naissance_enfant', label: "Date de naissance de l'enfant", type: 'date', required: true },
      { key: 'nom_mere', label: "Nom complet de la mère", type: 'text', required: true },
      { key: 'date_reconnaissance', label: "Date de la reconnaissance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE RECONNAISSANCE DE PATERNITÉ</h1><p>Je soussigné, <strong>{{nom_pere}}</strong>, déclare reconnaître être le père de l'enfant <strong>{{nom_enfant}}</strong>, né(e) le {{date_naissance_enfant}}, dont la mère est <strong>{{nom_mere}}</strong>.</p><p>Cette reconnaissance volontaire est effectuée ce {{date_reconnaissance}} conformément aux articles applicables du Code Civil ivoirien.</p><p>Je m'engage à assumer toutes les obligations légales attachées à la qualité de père reconnu.</p><p>Signature du père : ___________________</p></div>`,
  },

  {
    code: 'fam_adoption_simple',
    name: "Accord d'adoption simple",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Convention d'adoption simple maintenant les liens avec la famille d'origine, établie conformément aux dispositions du Code Civil ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_adoptant', label: "Nom complet de l'adoptant", type: 'text', required: true },
      { key: 'nom_enfant_adopte', label: "Nom de l'enfant adopté", type: 'text', required: true },
      { key: 'date_naissance_adopte', label: "Date de naissance de l'adopté", type: 'date', required: true },
      { key: 'nom_famille_origine', label: "Famille d'origine", type: 'text', required: true },
      { key: 'conditions_adoption', label: "Conditions et engagements", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'ADOPTION SIMPLE</h1><p>Le présent accord est établi entre l'adoptant <strong>{{nom_adoptant}}</strong> et la famille d'origine <strong>{{nom_famille_origine}}</strong>, concernant l'adoption simple de <strong>{{nom_enfant_adopte}}</strong>, né(e) le {{date_naissance_adopte}}.</p><p>L'adoption simple est prononcée conformément aux articles du Code Civil ivoirien. L'enfant conserve ses liens avec sa famille d'origine.</p><p>Conditions et engagements : {{conditions_adoption}}</p><p>Signatures des parties : ___________________</p></div>`,
  },

  {
    code: 'fam_adoption_pleniere',
    name: "Accord d'adoption plénière",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Convention d'adoption plénière rompant définitivement les liens avec la famille biologique, soumise à homologation judiciaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_adoptant', label: "Nom complet de l'adoptant", type: 'text', required: true },
      { key: 'nom_conjoint_adoptant', label: "Nom du conjoint adoptant (si applicable)", type: 'text', required: false },
      { key: 'nom_enfant_adopte', label: "Nom de l'enfant adopté", type: 'text', required: true },
      { key: 'date_naissance_adopte', label: "Date de naissance de l'adopté", type: 'date', required: true },
      { key: 'tribunal_competent', label: "Tribunal compétent", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'ADOPTION PLÉNIÈRE</h1><p>Les adoptants <strong>{{nom_adoptant}}</strong> {{nom_conjoint_adoptant}} sollicitent l'adoption plénière de <strong>{{nom_enfant_adopte}}</strong>, né(e) le {{date_naissance_adopte}}.</p><p>L'adoption plénière, une fois prononcée par {{tribunal_competent}}, confère à l'enfant adopté une filiation se substituant à sa filiation d'origine. Tous liens avec la famille biologique sont définitivement rompus.</p><p>L'enfant portera le nom de la famille adoptive et bénéficiera de tous les droits successoraux.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_delegation_autorite_parentale',
    name: "Accord de délégation de l'autorité parentale",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Convention de délégation temporaire ou permanente de l'autorité parentale à un tiers de confiance, soumise à approbation judiciaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_parent_delegant', label: "Nom du parent délégant", type: 'text', required: true },
      { key: 'nom_delegataire', label: "Nom du délégataire (tiers)", type: 'text', required: true },
      { key: 'nom_enfant', label: "Nom de l'enfant concerné", type: 'text', required: true },
      { key: 'duree_delegation', label: "Durée de la délégation", type: 'text', required: true },
      { key: 'motif_delegation', label: "Motif de la délégation", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DÉLÉGATION DE L'AUTORITÉ PARENTALE</h1><p>Le parent <strong>{{nom_parent_delegant}}</strong> délègue à <strong>{{nom_delegataire}}</strong> l'autorité parentale sur l'enfant <strong>{{nom_enfant}}</strong>.</p><p>Durée de la délégation : {{duree_delegation}}</p><p>Motif : {{motif_delegation}}</p><p>Cette délégation est soumise à l'homologation du Tribunal de Première Instance compétent conformément au droit ivoirien.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_garde_partagee',
    name: "Accord de garde d'enfant partagée (séparation)",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Convention organisant la garde alternée d'un enfant entre deux parents séparés, précisant les modalités pratiques de résidence alternée.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_parent_1', label: "Nom du premier parent", type: 'text', required: true },
      { key: 'nom_parent_2', label: "Nom du second parent", type: 'text', required: true },
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'modalites_garde', label: "Modalités de garde alternée", type: 'textarea', required: true },
      { key: 'date_prise_effet', label: "Date de prise d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GARDE PARTAGÉE</h1><p>Entre <strong>{{nom_parent_1}}</strong> et <strong>{{nom_parent_2}}</strong>, parents de <strong>{{nom_enfant}}</strong> :</p><p>Les parties conviennent d'organiser la garde de leur enfant en résidence alternée à compter du {{date_prise_effet}}.</p><p>Modalités de garde : {{modalites_garde}}</p><p>Cet accord peut être soumis à homologation judiciaire sur demande de l'une des parties.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_droit_visite',
    name: "Accord de droit de visite et d'hébergement",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Convention fixant les droits de visite et d'hébergement du parent non gardien, incluant vacances scolaires et jours fériés.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_parent_gardien', label: "Nom du parent gardien", type: 'text', required: true },
      { key: 'nom_parent_visiteur', label: "Nom du parent visiteur", type: 'text', required: true },
      { key: 'nom_enfant', label: "Nom de l'enfant", type: 'text', required: true },
      { key: 'calendrier_visites', label: "Calendrier des visites et hébergements", type: 'textarea', required: true },
      { key: 'lieu_remise_enfant', label: "Lieu de remise de l'enfant", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DROIT DE VISITE ET D'HÉBERGEMENT</h1><p>Entre <strong>{{nom_parent_gardien}}</strong> (parent gardien) et <strong>{{nom_parent_visiteur}}</strong> (parent visiteur), pour l'enfant <strong>{{nom_enfant}}</strong> :</p><p>Calendrier convenu : {{calendrier_visites}}</p><p>Lieu de remise de l'enfant : {{lieu_remise_enfant}}</p><p>Les deux parents s'engagent à respecter le présent calendrier dans l'intérêt supérieur de l'enfant.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_pension_alimentaire_enfants',
    name: "Accord de pension alimentaire enfants",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Convention fixant le montant et les modalités de versement de la pension alimentaire pour enfant(s) à charge d'un parent séparé.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'nom_debiteur', label: "Nom du débiteur de pension", type: 'text', required: true },
      { key: 'nom_creancier', label: "Nom du créancier (parent gardien)", type: 'text', required: true },
      { key: 'noms_enfants', label: "Noms des enfants bénéficiaires", type: 'textarea', required: true },
      { key: 'montant_mensuel', label: "Montant mensuel (FCFA)", type: 'text', required: true },
      { key: 'date_premier_versement', label: "Date du premier versement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PENSION ALIMENTAIRE</h1><p><strong>{{nom_debiteur}}</strong> s'engage à verser à <strong>{{nom_creancier}}</strong> une pension alimentaire mensuelle de <strong>{{montant_mensuel}} FCFA</strong> pour les enfants : {{noms_enfants}}.</p><p>Le premier versement interviendra le {{date_premier_versement}}, puis le même jour de chaque mois.</p><p>Cette pension est indexée et révisable annuellement ou en cas de changement de situation. En cas de non-paiement, le créancier peut saisir les voies d'exécution légales.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_prestation_compensatoire',
    name: "Accord de prestation compensatoire (divorce)",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Convention fixant la prestation compensatoire destinée à compenser la disparité de niveau de vie créée par la dissolution du mariage.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_debiteur', label: "Nom du débiteur de la prestation", type: 'text', required: true },
      { key: 'nom_beneficiaire', label: "Nom du bénéficiaire", type: 'text', required: true },
      { key: 'montant_prestation', label: "Montant ou nature de la prestation", type: 'textarea', required: true },
      { key: 'modalites_versement', label: "Modalités de versement", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRESTATION COMPENSATOIRE</h1><p>Dans le cadre de la dissolution de leur mariage, <strong>{{nom_debiteur}}</strong> s'engage à verser une prestation compensatoire à <strong>{{nom_beneficiaire}}</strong>.</p><p>Nature et montant de la prestation : {{montant_prestation}}</p><p>Modalités de versement : {{modalites_versement}}</p><p>Le présent accord prend effet à la date du {{date_accord}} et sera soumis à l'homologation du juge compétent.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_divorce_consentement_mutuel',
    name: "Accord de divorce par consentement mutuel",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Convention de divorce amiable organisant la dissolution du mariage et réglant l'ensemble des conséquences patrimoniales et familiales.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'nom_epoux', label: "Nom complet de l'époux", type: 'text', required: true },
      { key: 'nom_epouse', label: "Nom complet de l'épouse", type: 'text', required: true },
      { key: 'date_mariage', label: "Date du mariage dissous", type: 'date', required: true },
      { key: 'enfants_communs', label: "Enfants communs et mesures les concernant", type: 'textarea', required: false },
      { key: 'partage_biens', label: "Modalités de partage des biens", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE DIVORCE PAR CONSENTEMENT MUTUEL</h1><p><strong>{{nom_epoux}}</strong> et <strong>{{nom_epouse}}</strong>, mariés le {{date_mariage}}, conviennent mutuellement de mettre fin à leur union.</p><p>Sort des enfants communs : {{enfants_communs}}</p><p>Partage des biens : {{partage_biens}}</p><p>La présente convention sera soumise à l'homologation du Tribunal de Première Instance conformément au Code Civil ivoirien.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_divorce_pour_faute',
    name: "Accord de divorce pour faute",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 54000,
    description: "Convention documentant les faits constitutifs de faute grave rendant intolérable le maintien du lien conjugal, en vue d'une procédure de divorce contentieux.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_demandeur', label: "Nom du demandeur au divorce", type: 'text', required: true },
      { key: 'nom_defendeur', label: "Nom du défendeur", type: 'text', required: true },
      { key: 'faits_repproches', label: "Faits reprochés constitutifs de faute", type: 'textarea', required: true },
      { key: 'date_faits', label: "Date des principaux faits", type: 'date', required: true },
      { key: 'tribunal_saisi', label: "Tribunal saisi", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>MÉMOIRE EN DIVORCE POUR FAUTE</h1><p><strong>{{nom_demandeur}}</strong> expose au {{tribunal_saisi}} les faits constitutifs de faute grave imputables à <strong>{{nom_defendeur}}</strong>.</p><p>Faits reprochés : {{faits_repproches}}</p><p>Ces faits, survenus notamment le {{date_faits}}, rendent intolérable le maintien du lien conjugal et justifient le prononcé du divorce aux torts exclusifs du défendeur.</p><p>Signature du demandeur : ___________________</p></div>`,
  },

  {
    code: 'fam_rupture_pacs',
    name: "Convention de rupture amiable de PACS",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Convention organisant la rupture amiable d'un Pacte Civil de Solidarité et réglant les conséquences patrimoniales de la séparation.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'nom_partenaire_1', label: "Nom du premier partenaire", type: 'text', required: true },
      { key: 'nom_partenaire_2', label: "Nom du second partenaire", type: 'text', required: true },
      { key: 'date_pacs', label: "Date de conclusion du PACS", type: 'date', required: true },
      { key: 'date_rupture', label: "Date de rupture souhaitée", type: 'date', required: true },
      { key: 'modalites_partage', label: "Modalités de partage des biens communs", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE RUPTURE AMIABLE DE PACS</h1><p><strong>{{nom_partenaire_1}}</strong> et <strong>{{nom_partenaire_2}}</strong>, liés par un PACS conclu le {{date_pacs}}, conviennent mutuellement de mettre fin à leur pacte à compter du {{date_rupture}}.</p><p>Modalités de partage : {{modalites_partage}}</p><p>Cette déclaration conjointe sera remise à l'officier d'état civil ou au notaire ayant enregistré le PACS initial.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_reconnaissance_enfant_naturel',
    name: "Accord de reconnaissance d'enfant naturel",
    category: 'juridique_admin',
    price: 4000,
    priceMax: 12000,
    description: "Acte conjoint de reconnaissance d'un enfant né hors mariage, établissant la filiation paternelle et maternelle.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_pere', label: "Nom complet du père", type: 'text', required: true },
      { key: 'nom_mere', label: "Nom complet de la mère", type: 'text', required: true },
      { key: 'nom_enfant', label: "Prénom(s) et nom de l'enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance de l'enfant", type: 'date', required: true },
      { key: 'lieu_naissance', label: "Lieu de naissance", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE RECONNAISSANCE D'ENFANT NATUREL</h1><p>Nous soussignés, <strong>{{nom_pere}}</strong> et <strong>{{nom_mere}}</strong>, reconnaissons conjointement être les parents de l'enfant <strong>{{nom_enfant}}</strong>, né(e) le {{date_naissance}} à {{lieu_naissance}}.</p><p>Nous déclarons assumer conjointement l'autorité parentale et toutes les obligations légales y afférentes.</p><p>Fait devant l'officier d'état civil compétent.</p><p>Signature du père : ___________________ Signature de la mère : ___________________</p></div>`,
  },

  {
    code: 'fam_naissance_tardive',
    name: "Acte de naissance tardive (légalisation)",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Déclaration de naissance tardive établie sur jugement supplétif du tribunal, permettant la régularisation de l'état civil d'une personne non déclarée à la naissance.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_personne', label: "Nom de la personne concernée", type: 'text', required: true },
      { key: 'date_naissance_estimee', label: "Date de naissance estimée", type: 'date', required: true },
      { key: 'lieu_naissance', label: "Lieu de naissance", type: 'text', required: true },
      { key: 'nom_pere', label: "Nom du père", type: 'text', required: true },
      { key: 'nom_mere', label: "Nom de la mère", type: 'text', required: true },
      { key: 'temoins', label: "Témoins et leurs déclarations", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>DEMANDE DE JUGEMENT SUPPLÉTIF DE NAISSANCE</h1><p>Il est demandé au Tribunal de Première Instance d'établir un jugement supplétif d'acte de naissance pour <strong>{{nom_personne}}</strong>, né(e) le {{date_naissance_estimee}} à {{lieu_naissance}}, de père <strong>{{nom_pere}}</strong> et de mère <strong>{{nom_mere}}</strong>.</p><p>Témoignages : {{temoins}}</p><p>Le présent jugement supplétif tiendra lieu d'acte de naissance conformément à la loi ivoirienne sur l'état civil.</p></div>`,
  },

  {
    code: 'fam_changement_prenom',
    name: "Accord de changement de prénom",
    category: 'juridique_admin',
    price: 4000,
    priceMax: 12000,
    description: "Demande officielle de changement de prénom motivée par un intérêt légitime, soumise à l'officier d'état civil ou au tribunal compétent.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_demandeur', label: "Nom et prénom actuel du demandeur", type: 'text', required: true },
      { key: 'prenom_actuel', label: "Prénom actuel à changer", type: 'text', required: true },
      { key: 'prenom_demande', label: "Nouveau prénom souhaité", type: 'text', required: true },
      { key: 'motif_changement', label: "Motif du changement", type: 'textarea', required: true },
      { key: 'date_demande', label: "Date de la demande", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DEMANDE DE CHANGEMENT DE PRÉNOM</h1><p>Le soussigné <strong>{{nom_demandeur}}</strong> sollicite le changement de son prénom <strong>{{prenom_actuel}}</strong> en <strong>{{prenom_demande}}</strong>.</p><p>Motif : {{motif_changement}}</p><p>Demande formulée le {{date_demande}} auprès de l'autorité compétente.</p><p>Signature : ___________________</p></div>`,
  },

  {
    code: 'fam_changement_nom',
    name: "Accord de changement de nom de famille",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Demande de changement de nom de famille motivée, soumise au Garde des Sceaux ou au tribunal compétent en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'nom_actuel', label: "Nom de famille actuel", type: 'text', required: true },
      { key: 'nom_souhaite', label: "Nouveau nom de famille souhaité", type: 'text', required: true },
      { key: 'prenoms', label: "Prénoms du demandeur", type: 'text', required: true },
      { key: 'motif', label: "Motif justifiant le changement", type: 'textarea', required: true },
      { key: 'date_demande', label: "Date de la demande", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DEMANDE DE CHANGEMENT DE NOM DE FAMILLE</h1><p>Le soussigné <strong>{{prenoms}} {{nom_actuel}}</strong> sollicite l'autorisation de porter le nom <strong>{{nom_souhaite}}</strong>.</p><p>Motif : {{motif}}</p><p>La présente demande est formulée le {{date_demande}} conformément aux dispositions légales en vigueur en République de Côte d'Ivoire.</p><p>Signature : ___________________</p></div>`,
  },

  {
    code: 'fam_succession_ab_intestat',
    name: "Acte de succession ab intestat (sans testament)",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Acte organisant la dévolution successorale légale en l'absence de testament, selon l'ordre légal des héritiers défini par le Code Civil ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'nom_defunt', label: "Nom complet du défunt", type: 'text', required: true },
      { key: 'date_deces', label: "Date du décès", type: 'date', required: true },
      { key: 'liste_heritiers', label: "Liste des héritiers légaux et leur lien de parenté", type: 'textarea', required: true },
      { key: 'masse_successorale', label: "Description de la masse successorale", type: 'textarea', required: true },
      { key: 'notaire', label: "Notaire en charge", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACTE DE SUCCESSION AB INTESTAT</h1><p>Suite au décès de <strong>{{nom_defunt}}</strong> survenu le {{date_deces}}, sans testament connu, la succession est dévolue légalement aux héritiers suivants :</p><p>{{liste_heritiers}}</p><p>Masse successorale : {{masse_successorale}}</p><p>La présente succession est régie par les dispositions du Code Civil ivoirien relatives à l'ordre légal des héritiers. Notaire instrumentaire : {{notaire}}</p></div>`,
  },

  {
    code: 'fam_partage_successoral',
    name: "Acte de partage successoral amiable",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Convention de partage amiable entre héritiers des biens composant la succession, évitant un partage judiciaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_defunt', label: "Nom du défunt", type: 'text', required: true },
      { key: 'heritiers_signataires', label: "Noms de tous les héritiers signataires", type: 'textarea', required: true },
      { key: 'biens_partages', label: "Description des biens et attribution à chaque héritier", type: 'textarea', required: true },
      { key: 'date_partage', label: "Date du partage", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE PARTAGE SUCCESSORAL AMIABLE</h1><p>Les héritiers de <strong>{{nom_defunt}}</strong>, dont les noms suivent : {{heritiers_signataires}}, conviennent amiablement du partage des biens successoraux comme suit :</p><p>{{biens_partages}}</p><p>Ce partage est définitif et libère chacun des héritiers de toute prétention sur les biens attribués aux autres. Fait le {{date_partage}}.</p><p>Signatures de tous les héritiers : ___________________</p></div>`,
  },

  {
    code: 'fam_renonciation_succession',
    name: "Accord de renonciation à succession",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Déclaration formelle par laquelle un héritier renonce à la succession d'un défunt, déchargé ainsi de toute obligation successorale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_renonciateur', label: "Nom de l'héritier renonçant", type: 'text', required: true },
      { key: 'nom_defunt', label: "Nom du défunt", type: 'text', required: true },
      { key: 'lien_parente', label: "Lien de parenté avec le défunt", type: 'text', required: true },
      { key: 'date_renonciation', label: "Date de la renonciation", type: 'date', required: true },
      { key: 'motif', label: "Motif de la renonciation (facultatif)", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>DÉCLARATION DE RENONCIATION À SUCCESSION</h1><p>Je soussigné(e), <strong>{{nom_renonciateur}}</strong>, héritier(ère) en qualité de {{lien_parente}} de <strong>{{nom_defunt}}</strong>, déclare renoncer expressément à la succession dudit défunt.</p><p>Motif : {{motif}}</p><p>Cette renonciation est pure, simple et irrévocable. Elle est faite le {{date_renonciation}} conformément à l'article applicable du Code Civil ivoirien.</p><p>Signature : ___________________</p></div>`,
  },

  {
    code: 'fam_legs_testament',
    name: "Accord de legs particulier (testament)",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Testament olographe ou authentique portant sur un legs particulier d'un bien déterminé à un légataire désigné.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'nom_testateur', label: "Nom complet du testateur", type: 'text', required: true },
      { key: 'nom_legataire', label: "Nom du légataire", type: 'text', required: true },
      { key: 'bien_legue', label: "Description précise du bien légué", type: 'textarea', required: true },
      { key: 'conditions_legs', label: "Conditions éventuelles du legs", type: 'textarea', required: false },
      { key: 'date_testament', label: "Date du testament", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>TESTAMENT — LEGS PARTICULIER</h1><p>Je soussigné(e), <strong>{{nom_testateur}}</strong>, sain(e) de corps et d'esprit, lègue à <strong>{{nom_legataire}}</strong> le bien suivant :</p><p>{{bien_legue}}</p><p>Conditions : {{conditions_legs}}</p><p>Ce testament olographe est entièrement écrit de ma main, daté et signé le {{date_testament}}.</p><p>Signature du testateur : ___________________</p></div>`,
  },

  {
    code: 'fam_donation_partage',
    name: "Accord de donation-partage anticipée",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 54000,
    description: "Acte notarié de donation-partage permettant au donateur de distribuer de son vivant une partie de ses biens à ses héritiers présomptifs.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_donateur', label: "Nom complet du donateur", type: 'text', required: true },
      { key: 'donataires_biens', label: "Donataires et biens attribués à chacun", type: 'textarea', required: true },
      { key: 'valeur_totale', label: "Valeur totale des biens donnés (FCFA)", type: 'text', required: true },
      { key: 'reserve_usufruit', label: "Réserve d'usufruit par le donateur (oui/non + détails)", type: 'textarea', required: false },
      { key: 'date_donation', label: "Date de l'acte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE DONATION-PARTAGE ANTICIPÉE</h1><p><strong>{{nom_donateur}}</strong> procède à une donation-partage de ses biens entre ses héritiers présomptifs :</p><p>{{donataires_biens}}</p><p>Valeur totale des biens transmis : {{valeur_totale}} FCFA</p><p>Réserve d'usufruit : {{reserve_usufruit}}</p><p>Fait par acte notarié le {{date_donation}}.</p></div>`,
  },

  {
    code: 'fam_fiducie_successorale',
    name: "Accord de fiducie successorale",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 60000,
    description: "Convention de fiducie successorale confiant la gestion temporaire d'actifs successoraux à un fiduciaire pour le compte de bénéficiaires désignés.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'nom_constituant', label: "Nom du constituant (testateur/héritier)", type: 'text', required: true },
      { key: 'nom_fiduciaire', label: "Nom du fiduciaire", type: 'text', required: true },
      { key: 'beneficiaires', label: "Bénéficiaires de la fiducie", type: 'textarea', required: true },
      { key: 'actifs_fiducie', label: "Actifs placés en fiducie", type: 'textarea', required: true },
      { key: 'duree_fiducie', label: "Durée de la fiducie", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE FIDUCIE SUCCESSORALE</h1><p><strong>{{nom_constituant}}</strong> (constituant) confie à <strong>{{nom_fiduciaire}}</strong> (fiduciaire) la gestion en fiducie des actifs suivants :</p><p>{{actifs_fiducie}}</p><p>Bénéficiaires : {{beneficiaires}}</p><p>Durée : {{duree_fiducie}}</p><p>Le fiduciaire s'engage à gérer les actifs dans l'intérêt exclusif des bénéficiaires, conformément aux termes de la présente convention.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'fam_mediation_familiale',
    name: "Charte de médiation familiale en Afrique",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Charte organisant une médiation familiale africaine intégrant les mécanismes traditionnels de résolution des conflits et le droit moderne ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'parties_en_conflit', label: "Parties en conflit", type: 'textarea', required: true },
      { key: 'nom_mediateur', label: "Nom du médiateur", type: 'text', required: true },
      { key: 'objet_mediation', label: "Objet du différend familial", type: 'textarea', required: true },
      { key: 'date_premiere_seance', label: "Date de la première séance", type: 'date', required: true },
      { key: 'engagements_parties', label: "Engagements des parties", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE MÉDIATION FAMILIALE</h1><p>La présente charte régit la médiation engagée entre : {{parties_en_conflit}}, sous la conduite du médiateur <strong>{{nom_mediateur}}</strong>.</p><p>Objet du différend : {{objet_mediation}}</p><p>Première séance : {{date_premiere_seance}}</p><p>Principes : confidentialité, bonne foi, respect mutuel, prise en compte des valeurs culturelles africaines et du droit positif ivoirien.</p><p>Engagements : {{engagements_parties}}</p><p>Signatures : ___________________</p></div>`,
  },

  // ─── GESTION DE PATRIMOINE (25 templates, préfixe pat2_, catégorie commercial_financier) ───

  {
    code: 'pat2_mandat_gestion_patrimoine',
    name: "Accord de mandat de gestion de patrimoine privé",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 45000,
    description: "Mandat confiant à un gestionnaire professionnel la gestion discrétionnaire ou conseillée d'un patrimoine privé, conforme au cadre OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_mandant', label: "Nom complet du mandant", type: 'text', required: true },
      { key: 'nom_mandataire', label: "Nom du gestionnaire mandataire", type: 'text', required: true },
      { key: 'perimetre_gestion', label: "Périmètre et actifs confiés en gestion", type: 'textarea', required: true },
      { key: 'type_mandat', label: "Type de mandat (discrétionnaire/conseillé)", type: 'text', required: true },
      { key: 'duree_mandat', label: "Durée du mandat", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>MANDAT DE GESTION DE PATRIMOINE PRIVÉ</h1><p><strong>{{nom_mandant}}</strong> confie à <strong>{{nom_mandataire}}</strong> un mandat de type {{type_mandat}} pour la gestion des actifs suivants :</p><p>{{perimetre_gestion}}</p><p>Durée du mandat : {{duree_mandat}}</p><p>Le mandataire s'engage à gérer les actifs dans l'intérêt du mandant, selon les objectifs définis et dans le respect de la réglementation OHADA applicable.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_conseil_cgp',
    name: "Accord de conseil en gestion de patrimoine (CGP)",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Convention de prestation de conseil patrimonial global par un Conseiller en Gestion de Patrimoine (CGP), définissant les missions, honoraires et responsabilités.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom complet du client", type: 'text', required: true },
      { key: 'nom_cgp', label: "Nom du conseiller en gestion de patrimoine", type: 'text', required: true },
      { key: 'missions', label: "Missions confiées au CGP", type: 'textarea', required: true },
      { key: 'honoraires', label: "Honoraires et modalités de facturation", type: 'textarea', required: true },
      { key: 'duree_mission', label: "Durée de la mission", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE CONSEIL EN GESTION DE PATRIMOINE</h1><p>Entre <strong>{{nom_client}}</strong> (client) et <strong>{{nom_cgp}}</strong> (Conseiller en Gestion de Patrimoine) :</p><p>Missions : {{missions}}</p><p>Honoraires : {{honoraires}}</p><p>Durée : {{duree_mission}}</p><p>Le CGP s'engage à fournir des conseils personnalisés, objectifs et conformes aux intérêts du client, dans le respect des réglementations en vigueur en Côte d'Ivoire.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_bilan_patrimonial',
    name: "Accord de bilan patrimonial (audit)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Convention d'audit patrimonial complet permettant d'établir un état des lieux des actifs, passifs, revenus et objectifs du client.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom complet du client", type: 'text', required: true },
      { key: 'nom_auditeur', label: "Nom de l'auditeur patrimonial", type: 'text', required: true },
      { key: 'date_audit', label: "Date de réalisation du bilan", type: 'date', required: true },
      { key: 'actifs_declares', label: "Actifs déclarés par le client", type: 'textarea', required: true },
      { key: 'objectifs_patrimoniaux', label: "Objectifs patrimoniaux du client", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>BILAN PATRIMONIAL — AUDIT COMPLET</h1><p>Bilan établi le {{date_audit}} pour <strong>{{nom_client}}</strong> par <strong>{{nom_auditeur}}</strong>.</p><p>Actifs déclarés : {{actifs_declares}}</p><p>Objectifs patrimoniaux : {{objectifs_patrimoniaux}}</p><p>Le présent bilan est confidentiel et constitue la base des recommandations patrimoniales à venir. Il sera révisé annuellement ou lors de tout changement significatif de situation.</p></div>`,
  },

  {
    code: 'pat2_strategie_globale',
    name: "Accord de stratégie patrimoniale globale",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Document de stratégie patrimoniale définissant les axes prioritaires d'investissement, de protection et de transmission sur un horizon long terme.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'nom_conseiller', label: "Nom du conseiller", type: 'text', required: true },
      { key: 'axes_strategiques', label: "Axes stratégiques retenus", type: 'textarea', required: true },
      { key: 'horizon_temporel', label: "Horizon temporel (années)", type: 'text', required: true },
      { key: 'date_strategie', label: "Date d'établissement de la stratégie", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>STRATÉGIE PATRIMONIALE GLOBALE</h1><p>Stratégie établie pour <strong>{{nom_client}}</strong> par <strong>{{nom_conseiller}}</strong>, le {{date_strategie}}, sur un horizon de {{horizon_temporel}} ans.</p><p>Axes stratégiques : {{axes_strategiques}}</p><p>Cette stratégie sera révisée annuellement et adaptée en fonction de l'évolution de la situation personnelle, fiscale et économique du client.</p></div>`,
  },

  {
    code: 'pat2_family_office',
    name: "Accord de service de family office",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 60000,
    description: "Convention de services de family office multi-familles ou mono-famille, couvrant la gestion patrimoniale, juridique, fiscale et administrative d'une grande famille.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_famille', label: "Nom de la famille cliente", type: 'text', required: true },
      { key: 'nom_family_office', label: "Dénomination du family office", type: 'text', required: true },
      { key: 'services_inclus', label: "Services inclus dans la prestation", type: 'textarea', required: true },
      { key: 'honoraires_annuels', label: "Honoraires annuels (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE FAMILY OFFICE</h1><p>La famille <strong>{{nom_famille}}</strong> confie à <strong>{{nom_family_office}}</strong> la gestion globale de ses intérêts patrimoniaux.</p><p>Services inclus : {{services_inclus}}</p><p>Honoraires annuels : {{honoraires_annuels}} FCFA</p><p>Durée : {{duree_contrat}}</p><p>Le family office s'engage à une totale confidentialité et à mettre en place une organisation dédiée aux besoins spécifiques de la famille.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_trust_fiducie',
    name: "Accord de service de trust (fiducie anglophone)",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 60000,
    description: "Convention de constitution et gestion d'un trust ou fiducie, mécanisme de protection et transmission d'actifs adapté au contexte africain francophone.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'nom_settlor', label: "Nom du constituant (settlor)", type: 'text', required: true },
      { key: 'nom_trustee', label: "Nom du trustee/fiduciaire", type: 'text', required: true },
      { key: 'beneficiaires', label: "Bénéficiaires du trust", type: 'textarea', required: true },
      { key: 'actifs_trust', label: "Actifs placés dans le trust", type: 'textarea', required: true },
      { key: 'duree_trust', label: "Durée du trust", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE TRUST / FIDUCIE</h1><p><strong>{{nom_settlor}}</strong> constitue un trust en faveur de <strong>{{beneficiaires}}</strong>, sous la gestion de <strong>{{nom_trustee}}</strong>.</p><p>Actifs placés : {{actifs_trust}}</p><p>Durée : {{duree_trust}}</p><p>Le trustee s'engage à gérer les actifs conformément aux instructions du constituant et dans l'intérêt exclusif des bénéficiaires désignés.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_assurance_vie_patrimoniale',
    name: "Accord de service d'assurance vie comme outil patrimonial",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Convention de souscription et gestion d'un contrat d'assurance vie à vocation patrimoniale, intégrant les objectifs de transmission et d'optimisation fiscale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'nom_souscripteur', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'nom_assureur', label: "Nom de la compagnie d'assurance", type: 'text', required: true },
      { key: 'beneficiaires_assurance', label: "Clause bénéficiaire désignée", type: 'textarea', required: true },
      { key: 'capital_souscrit', label: "Capital souscrit (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE VIE PATRIMONIALE</h1><p><strong>{{nom_souscripteur}}</strong> souscrit auprès de <strong>{{nom_assureur}}</strong> un contrat d'assurance vie d'un capital de <strong>{{capital_souscrit}} FCFA</strong> pour une durée de {{duree_contrat}}.</p><p>Clause bénéficiaire : {{beneficiaires_assurance}}</p><p>Ce contrat est utilisé comme outil de transmission patrimoniale et de capitalisation à long terme, bénéficiant des avantages fiscaux applicables en Côte d'Ivoire.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_demembrement_propriete',
    name: "Accord de service de démembrement de propriété (usufruit/nue-propriété)",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Convention organisant le démembrement de propriété d'un bien entre usufruitier et nu-propriétaire, outil clé d'optimisation patrimoniale et successorale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_usufruitier', label: "Nom de l'usufruitier", type: 'text', required: true },
      { key: 'nom_nu_proprietaire', label: "Nom du nu-propriétaire", type: 'text', required: true },
      { key: 'bien_demembre', label: "Description du bien démembré", type: 'textarea', required: true },
      { key: 'duree_usufruit', label: "Durée de l'usufruit", type: 'text', required: true },
      { key: 'valeur_bien', label: "Valeur vénale du bien (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DÉMEMBREMENT DE PROPRIÉTÉ</h1><p>Le bien suivant fait l'objet d'un démembrement de propriété :</p><p>{{bien_demembre}} — valeur : {{valeur_bien}} FCFA</p><p>Usufruitier : <strong>{{nom_usufruitier}}</strong> — Durée de l'usufruit : {{duree_usufruit}}</p><p>Nu-propriétaire : <strong>{{nom_nu_proprietaire}}</strong></p><p>À l'extinction de l'usufruit, la pleine propriété sera consolidée entre les mains du nu-propriétaire sans droits de mutation supplémentaires.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_donation_usufruit_temporaire',
    name: "Accord de service de donation temporaire d'usufruit",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Convention de donation temporaire d'usufruit permettant au donateur de transférer les revenus d'un bien à un bénéficiaire pour une durée déterminée.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_donateur', label: "Nom du donateur (nu-propriétaire)", type: 'text', required: true },
      { key: 'nom_donataire', label: "Nom du donataire (usufruitier temporaire)", type: 'text', required: true },
      { key: 'bien_concerne', label: "Bien objet de la donation d'usufruit", type: 'textarea', required: true },
      { key: 'duree_donation', label: "Durée de la donation temporaire", type: 'text', required: true },
      { key: 'date_prise_effet', label: "Date de prise d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DONATION TEMPORAIRE D'USUFRUIT</h1><p><strong>{{nom_donateur}}</strong> donne temporairement l'usufruit du bien suivant à <strong>{{nom_donataire}}</strong> :</p><p>{{bien_concerne}}</p><p>Durée : {{duree_donation}} à compter du {{date_prise_effet}}</p><p>Durant cette période, le donataire percevra tous les fruits et revenus du bien. À l'échéance, l'usufruit retournera automatiquement au donateur.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_sci_patrimoniale',
    name: "Accord de service de SCI (Société Civile Immobilière) patrimoniale",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 54000,
    description: "Convention d'accompagnement à la création et gestion d'une SCI patrimoniale permettant la détention et transmission organisée de biens immobiliers en famille.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'denomination_sci', label: "Dénomination sociale de la SCI", type: 'text', required: true },
      { key: 'associes', label: "Liste des associés et parts respectives", type: 'textarea', required: true },
      { key: 'capital_social', label: "Capital social (FCFA)", type: 'text', required: true },
      { key: 'biens_apportes', label: "Biens immobiliers apportés à la SCI", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE SERVICE SCI PATRIMONIALE</h1><p>Constitution de la SCI <strong>{{denomination_sci}}</strong> au capital de {{capital_social}} FCFA pour le client <strong>{{nom_client}}</strong>.</p><p>Associés : {{associes}}</p><p>Biens apportés : {{biens_apportes}}</p><p>La SCI permettra une gestion organisée, une transmission facilitée des parts sociales et une optimisation de la fiscalité immobilière conformément au droit OHADA.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_holding_patrimoniale',
    name: "Accord de service de holding patrimoniale",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 60000,
    description: "Convention d'accompagnement à la structuration d'une holding patrimoniale pour l'organisation et l'optimisation de la détention d'actifs professionnels et privés.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du dirigeant/client", type: 'text', required: true },
      { key: 'nom_holding', label: "Dénomination de la holding", type: 'text', required: true },
      { key: 'filiales', label: "Filiales et participations détenues", type: 'textarea', required: true },
      { key: 'objectifs_holding', label: "Objectifs de la holding", type: 'textarea', required: true },
      { key: 'date_creation', label: "Date de création prévue", type: 'date', required: false },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE SERVICE HOLDING PATRIMONIALE</h1><p>Structuration de la holding <strong>{{nom_holding}}</strong> pour <strong>{{nom_client}}</strong>.</p><p>Filiales et participations : {{filiales}}</p><p>Objectifs : {{objectifs_holding}}</p><p>La holding sera constituée conformément aux dispositions de l'Acte Uniforme OHADA relatif aux sociétés commerciales et permettra une optimisation globale de la structure patrimoniale.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_optimisation_fiscale',
    name: "Accord de service d'optimisation fiscale patrimoniale",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 45000,
    description: "Convention de conseil en optimisation fiscale patrimoniale, identifiant les mécanismes légaux permettant de réduire la charge fiscale sur les revenus et le patrimoine.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'nom_conseiller_fiscal', label: "Nom du conseiller fiscal", type: 'text', required: true },
      { key: 'situation_fiscale', label: "Situation fiscale actuelle", type: 'textarea', required: true },
      { key: 'leviers_optimisation', label: "Leviers d'optimisation identifiés", type: 'textarea', required: true },
      { key: 'date_mission', label: "Date de la mission", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D'OPTIMISATION FISCALE PATRIMONIALE</h1><p>Mission réalisée pour <strong>{{nom_client}}</strong> par <strong>{{nom_conseiller_fiscal}}</strong> le {{date_mission}}.</p><p>Situation fiscale actuelle : {{situation_fiscale}}</p><p>Leviers d'optimisation retenus : {{leviers_optimisation}}</p><p>Toutes les recommandations s'inscrivent dans le strict cadre légal ivoirien et OHADA. Aucune stratégie de fraude ou d'évasion fiscale n'est suggérée.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_investissement_locatif',
    name: "Accord de service d'investissement locatif (buy-to-let)",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Convention d'accompagnement à l'investissement locatif, couvrant l'analyse de rentabilité, le financement et la gestion du bien acquis.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'nom_investisseur', label: "Nom de l'investisseur", type: 'text', required: true },
      { key: 'nom_conseiller', label: "Nom du conseiller", type: 'text', required: true },
      { key: 'bien_vise', label: "Description du bien visé", type: 'textarea', required: true },
      { key: 'rendement_cible', label: "Rendement locatif cible (%)", type: 'text', required: true },
      { key: 'budget_total', label: "Budget total d'acquisition (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D'INVESTISSEMENT LOCATIF</h1><p><strong>{{nom_conseiller}}</strong> accompagne <strong>{{nom_investisseur}}</strong> dans son projet d'investissement locatif.</p><p>Bien visé : {{bien_vise}}</p><p>Budget total : {{budget_total}} FCFA — Rendement cible : {{rendement_cible}}%</p><p>La mission inclut l'analyse de marché, la structuration du financement, l'optimisation fiscale et la mise en place de la gestion locative.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_scpi',
    name: "Accord de service de SCPI (Société Civile de Placement Immobilier)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Convention de souscription et conseil sur des parts de SCPI, permettant un investissement immobilier mutualisé accessible à partir de faibles montants.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_souscripteur', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'nom_scpi', label: "Nom de la SCPI", type: 'text', required: true },
      { key: 'montant_souscription', label: "Montant de souscription (FCFA)", type: 'text', required: true },
      { key: 'nombre_parts', label: "Nombre de parts souscrites", type: 'text', required: true },
      { key: 'date_souscription', label: "Date de souscription", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE SOUSCRIPTION SCPI</h1><p><strong>{{nom_souscripteur}}</strong> souscrit {{nombre_parts}} parts de la SCPI <strong>{{nom_scpi}}</strong> pour un montant total de {{montant_souscription}} FCFA le {{date_souscription}}.</p><p>Le souscripteur a été informé des risques liés à cet investissement, notamment l'absence de garantie de capital et les risques de liquidité.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_crowdfunding_immo',
    name: "Accord de service de crowdfunding immobilier",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Convention de participation à un financement participatif immobilier, définissant les droits de l'investisseur, le projet financé et les modalités de retour.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_investisseur', label: "Nom de l'investisseur", type: 'text', required: true },
      { key: 'nom_plateforme', label: "Nom de la plateforme de crowdfunding", type: 'text', required: true },
      { key: 'projet_finance', label: "Description du projet immobilier financé", type: 'textarea', required: true },
      { key: 'montant_investi', label: "Montant investi (FCFA)", type: 'text', required: true },
      { key: 'taux_retour', label: "Taux de retour attendu (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE CROWDFUNDING IMMOBILIER</h1><p><strong>{{nom_investisseur}}</strong> investit {{montant_investi}} FCFA sur la plateforme <strong>{{nom_plateforme}}</strong> dans le projet : {{projet_finance}}</p><p>Taux de retour attendu : {{taux_retour}}% — Durée estimée selon prospectus.</p><p>L'investisseur reconnait avoir pris connaissance des risques inhérents à cet investissement et accepte les conditions générales de la plateforme.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_gestion_art_alternatifs',
    name: "Accord de service de gestion d'art et actifs alternatifs",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Convention de conseil et gestion d'actifs alternatifs (oeuvres d'art, collections, cryptomonnaies, matières premières) dans une optique de diversification patrimoniale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'nom_gestionnaire', label: "Nom du gestionnaire spécialisé", type: 'text', required: true },
      { key: 'actifs_concernes', label: "Actifs alternatifs concernés", type: 'textarea', required: true },
      { key: 'valeur_estimee', label: "Valeur estimée du portefeuille alternatif (FCFA)", type: 'text', required: true },
      { key: 'duree_mandat', label: "Durée du mandat de gestion", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE GESTION D'ACTIFS ALTERNATIFS</h1><p><strong>{{nom_gestionnaire}}</strong> assure la gestion des actifs alternatifs de <strong>{{nom_client}}</strong> pour une valeur estimée de {{valeur_estimee}} FCFA.</p><p>Actifs concernés : {{actifs_concernes}}</p><p>Durée du mandat : {{duree_mandat}}</p><p>Le gestionnaire s'engage à un suivi régulier, à des reportings trimestriels et au respect des orientations du client.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_prevoyance_deces',
    name: "Accord de service de prévoyance patrimoniale (décès)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Convention de mise en place d'une stratégie de prévoyance patrimoniale incluant couverture décès, garantie invalidité et organisation successorale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'nom_conseiller', label: "Nom du conseiller prévoyance", type: 'text', required: true },
      { key: 'besoins_prevoyance', label: "Besoins de prévoyance identifiés", type: 'textarea', required: true },
      { key: 'solutions_retenues', label: "Solutions de prévoyance retenues", type: 'textarea', required: true },
      { key: 'date_souscription', label: "Date de souscription", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PRÉVOYANCE PATRIMONIALE</h1><p>Mission réalisée pour <strong>{{nom_client}}</strong> par <strong>{{nom_conseiller}}</strong> le {{date_souscription}}.</p><p>Besoins identifiés : {{besoins_prevoyance}}</p><p>Solutions retenues : {{solutions_retenues}}</p><p>La stratégie de prévoyance vise à protéger le patrimoine et les proches en cas d'événement grave (décès, invalidité), en complémentarité avec les dispositifs de sécurité sociale applicables.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_transmission_patrimoine_pro',
    name: "Accord de service de transmission de patrimoine professionnel",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 60000,
    description: "Convention d'accompagnement à la transmission d'une entreprise ou d'actifs professionnels dans un cadre patrimonial optimisé (donation, cession, pacte Dutreil).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_cedant', label: "Nom du cédant/transmettant", type: 'text', required: true },
      { key: 'nom_repreneur', label: "Nom du repreneur/bénéficiaire", type: 'text', required: true },
      { key: 'entreprise_cible', label: "Entreprise ou actifs professionnels transmis", type: 'textarea', required: true },
      { key: 'valeur_transmission', label: "Valeur de la transmission (FCFA)", type: 'text', required: true },
      { key: 'modalites_transmission', label: "Modalités de transmission retenues", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE TRANSMISSION DE PATRIMOINE PROFESSIONNEL</h1><p>Transmission de <strong>{{entreprise_cible}}</strong> de <strong>{{nom_cedant}}</strong> à <strong>{{nom_repreneur}}</strong>.</p><p>Valeur : {{valeur_transmission}} FCFA</p><p>Modalités : {{modalites_transmission}}</p><p>L'opération est structurée pour optimiser les aspects fiscaux et successoraux tout en assurant la continuité de l'activité transmise.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_liquidation_divorce',
    name: "Accord de service de liquidation de patrimoine (divorce)",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 45000,
    description: "Convention d'accompagnement professionnel à la liquidation du patrimoine commun lors d'un divorce, incluant valorisation des actifs et partage équitable.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_epoux_1', label: "Nom du premier époux", type: 'text', required: true },
      { key: 'nom_epoux_2', label: "Nom du second époux", type: 'text', required: true },
      { key: 'actifs_communs', label: "Inventaire des actifs communs", type: 'textarea', required: true },
      { key: 'passifs_communs', label: "Inventaire des passifs communs (dettes)", type: 'textarea', required: false },
      { key: 'nom_expert', label: "Nom de l'expert patrimonial mandaté", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE LIQUIDATION PATRIMONIALE (DIVORCE)</h1><p>Liquidation du patrimoine commun de <strong>{{nom_epoux_1}}</strong> et <strong>{{nom_epoux_2}}</strong> par <strong>{{nom_expert}}</strong>.</p><p>Actifs communs : {{actifs_communs}}</p><p>Passifs communs : {{passifs_communs}}</p><p>L'expert procédera à la valorisation contradictoire des actifs, à la détermination des droits de chaque époux et à la proposition d'un partage équitable.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_gestion_indivision',
    name: "Accord de service de gestion de patrimoine en indivision",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Convention organisant la gestion d'un patrimoine détenu en indivision entre plusieurs co-indivisaires, prévenant les blocages et conflits.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'co_indivisaires', label: "Noms et quotes-parts des co-indivisaires", type: 'textarea', required: true },
      { key: 'biens_indivis', label: "Description des biens en indivision", type: 'textarea', required: true },
      { key: 'gerant_indivision', label: "Gérant désigné de l'indivision", type: 'text', required: true },
      { key: 'regles_gestion', label: "Règles de gestion et prise de décision", type: 'textarea', required: true },
      { key: 'duree_convention', label: "Durée de la convention d'indivision", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE GESTION D'INDIVISION</h1><p>Les co-indivisaires suivants : {{co_indivisaires}} conviennent d'organiser la gestion de leurs biens indivis.</p><p>Biens en indivision : {{biens_indivis}}</p><p>Gérant désigné : <strong>{{gerant_indivision}}</strong></p><p>Règles de gestion : {{regles_gestion}}</p><p>Durée : {{duree_convention}}</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_representation_mineur',
    name: "Accord de service de représentation légale du mineur (bien)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Convention organisant la représentation légale d'un mineur propriétaire de biens, confiée à un administrateur légal ou à un tiers mandaté par le juge.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_mineur', label: "Nom du mineur propriétaire", type: 'text', required: true },
      { key: 'nom_representant', label: "Nom du représentant légal/mandataire", type: 'text', required: true },
      { key: 'biens_mineur', label: "Biens appartenant au mineur", type: 'textarea', required: true },
      { key: 'pouvoirs_representant', label: "Étendue des pouvoirs du représentant", type: 'textarea', required: true },
      { key: 'date_nomination', label: "Date de nomination", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE REPRÉSENTATION LÉGALE DU MINEUR</h1><p><strong>{{nom_representant}}</strong> est mandaté pour représenter le mineur <strong>{{nom_mineur}}</strong> dans la gestion de ses biens à compter du {{date_nomination}}.</p><p>Biens du mineur : {{biens_mineur}}</p><p>Étendue des pouvoirs : {{pouvoirs_representant}}</p><p>Le représentant devra rendre compte annuellement de sa gestion et agir dans l'intérêt exclusif du mineur.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_defiscalisation',
    name: "Accord de service de conseil en défiscalisation",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Convention de conseil en défiscalisation identifiant et mettant en place les dispositifs légaux de réduction d'impôt adaptés à la situation du client en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'nom_conseil', label: "Nom du conseil en défiscalisation", type: 'text', required: true },
      { key: 'pression_fiscale_actuelle', label: "Pression fiscale actuelle (description)", type: 'textarea', required: true },
      { key: 'dispositifs_retenus', label: "Dispositifs de défiscalisation retenus", type: 'textarea', required: true },
      { key: 'economies_estimees', label: "Économies fiscales estimées (FCFA/an)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE CONSEIL EN DÉFISCALISATION</h1><p>Mission confiée à <strong>{{nom_conseil}}</strong> par <strong>{{nom_client}}</strong>.</p><p>Situation fiscale actuelle : {{pression_fiscale_actuelle}}</p><p>Dispositifs retenus : {{dispositifs_retenus}}</p><p>Économies fiscales estimées : {{economies_estimees}} FCFA par an</p><p>Toutes les recommandations respectent strictement le cadre légal ivoirien. Aucune fraude fiscale n'est conseillée ni tolérée.</p><p>Signatures : ___________________</p></div>`,
  },

  {
    code: 'pat2_rapport_performance',
    name: "Rapport de performance portefeuille patrimonial",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Rapport périodique de performance du portefeuille patrimonial d'un client, présentant les rendements, l'évolution des actifs et les recommandations d'ajustement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'valeur_portefeuille', label: "Valeur du portefeuille en fin de période (FCFA)", type: 'text', required: true },
      { key: 'performance_periode', label: "Performance de la période (%)", type: 'text', required: true },
      { key: 'recommandations', label: "Recommandations d'ajustement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE PATRIMONIALE</h1><p>Rapport établi pour <strong>{{nom_client}}</strong> — Période : {{periode_rapport}}</p><p>Valeur du portefeuille : <strong>{{valeur_portefeuille}} FCFA</strong></p><p>Performance de la période : <strong>{{performance_periode}}%</strong></p><p>Recommandations : {{recommandations}}</p><p>Ce rapport est confidentiel et destiné exclusivement au client. Il ne constitue pas un conseil en investissement au sens réglementaire.</p></div>`,
  },

  {
    code: 'pat2_plan_developpement',
    name: "Plan de développement patrimonial long terme",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 45000,
    description: "Document stratégique de développement patrimonial sur 10 à 20 ans, définissant les étapes de constitution, valorisation et transmission du patrimoine.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'situation_actuelle', label: "Situation patrimoniale actuelle", type: 'textarea', required: true },
      { key: 'objectifs_long_terme', label: "Objectifs patrimoniaux long terme", type: 'textarea', required: true },
      { key: 'etapes_plan', label: "Étapes et jalons du plan patrimonial", type: 'textarea', required: true },
      { key: 'horizon_plan', label: "Horizon du plan (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT PATRIMONIAL LONG TERME</h1><p>Plan établi pour <strong>{{nom_client}}</strong> sur un horizon de {{horizon_plan}} ans.</p><p>Situation actuelle : {{situation_actuelle}}</p><p>Objectifs : {{objectifs_long_terme}}</p><p>Étapes du plan : {{etapes_plan}}</p><p>Ce plan sera révisé tous les deux ans pour tenir compte des évolutions de situation personnelle, économique et réglementaire.</p></div>`,
  },

  {
    code: 'pat2_charte_confidentialite',
    name: "Charte de confidentialité du conseiller en patrimoine",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Charte de confidentialité engageant le conseiller en gestion de patrimoine à protéger toutes les informations personnelles et financières de son client.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_conseiller', label: "Nom du conseiller en patrimoine", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'informations_protegees', label: "Nature des informations couvertes par la confidentialité", type: 'textarea', required: true },
      { key: 'duree_confidentialite', label: "Durée de l'obligation de confidentialité", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE CONFIDENTIALITÉ DU CONSEILLER EN PATRIMOINE</h1><p>Le soussigné <strong>{{nom_conseiller}}</strong>, conseiller en gestion de patrimoine, s'engage envers <strong>{{nom_client}}</strong> à maintenir la plus stricte confidentialité sur toutes les informations reçues dans le cadre de sa mission.</p><p>Informations couvertes : {{informations_protegees}}</p><p>Durée de l'obligation : {{duree_confidentialite}}</p><p>Toute violation de cette charte engage la responsabilité civile et pénale du conseiller. Signée le {{date_signature}}.</p><p>Signature : ___________________</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 73a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
