import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── PETITE ENFANCE / PRÉSCOLAIRE (pres_) ───────────────────────────────────
  {
    code: 'pres_inscription_creche',
    name: "Dossier d\"inscription en creche",
    category: 'academique',
    price: 2500,
    priceMax: 7500,
    description: "Dossier complet d\"inscription d\"un nourrisson ou d\"un enfant en bas age dans une structure de type creche en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'nom_parent', label: "Nom du parent ou tuteur legal", type: 'text', required: true },
      { key: 'contact_parent', label: "Contact telephonique du parent", type: 'text', required: true },
      { key: 'adresse_domicile', label: "Adresse du domicile familial", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER D"INSCRIPTION EN CRECHE</h1><p><strong>Etablissement :</strong> {{nom_creche}}</p><p><strong>Nom de l"enfant :</strong> {{nom_enfant}}</p><p><strong>Date de naissance :</strong> {{date_naissance}}</p><p><strong>Parent / Tuteur :</strong> {{nom_parent}}</p><p><strong>Contact :</strong> {{contact_parent}}</p><p><strong>Adresse :</strong> {{adresse_domicile}}</p><p>Le soussigne declare avoir pris connaissance du reglement interieur de la creche et s"engage a le respecter.</p><p>Fait a Abidjan, le {{date_naissance}}</p><p>Signature du parent : _______________</p></div>`,
  },
  {
    code: 'pres_contrat_accueil_creche',
    name: "Contrat d\"accueil creche et garderie",
    category: 'academique',
    price: 3000,
    priceMax: 9000,
    description: "Contrat formalisant les conditions d\"accueil d\"un enfant au sein d\"une creche ou garderie agree en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom complet de l\"enfant", type: 'text', required: true },
      { key: 'date_entree', label: "Date d\"entree dans la structure", type: 'date', required: true },
      { key: 'nom_structure', label: "Denomination de la creche", type: 'text', required: true },
      { key: 'horaires_accueil', label: "Horaires d\"accueil convenus", type: 'text', required: true },
      { key: 'montant_mensuel', label: "Montant mensuel de la garde (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"ACCUEIL CRECHE ET GARDERIE</h1><p>Entre la structure <strong>{{nom_structure}}</strong> et les parents de l"enfant <strong>{{nom_enfant}}</strong>, il est convenu ce qui suit :</p><p><strong>Article 1 – Prise en charge :</strong> L"enfant sera accueilli a compter du {{date_entree}} selon les horaires suivants : {{horaires_accueil}}.</p><p><strong>Article 2 – Tarification :</strong> Le montant mensuel est fixe a {{montant_mensuel}} FCFA, payable en debut de mois.</p><p><strong>Article 3 – Obligations des parties :</strong> Chaque partie s"engage a respecter les termes du present contrat et le reglement interieur de la structure.</p><p>Fait en deux exemplaires originaux.</p><p>Signature de la direction : _______________   Signature du parent : _______________</p></div>`,
  },
  {
    code: 'pres_reglement_interieur_creche',
    name: "Reglement interieur de creche",
    category: 'academique',
    price: 2000,
    priceMax: 6000,
    description: "Document reglementaire definissant les droits, obligations et regles de vie au sein d\"une creche en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_creche', label: "Nom de la creche", type: 'text', required: true },
      { key: 'responsable_creche', label: "Nom du directeur ou responsable", type: 'text', required: true },
      { key: 'adresse_creche', label: "Adresse de la creche", type: 'text', required: true },
      { key: 'capacite_accueil', label: "Capacite totale d\"accueil (enfants)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>REGLEMENT INTERIEUR</h1><h2>{{nom_creche}}</h2><p><strong>Adresse :</strong> {{adresse_creche}}</p><p><strong>Responsable :</strong> {{responsable_creche}}</p><p><strong>Capacite d"accueil :</strong> {{capacite_accueil}} enfants</p><h3>Article 1 – Admission</h3><p>L"admission de chaque enfant est subordonnee a la constitution d"un dossier complet et au reglement des frais d"inscription.</p><h3>Article 2 – Sante et hygiene</h3><p>Tout enfant presentant des signes de maladie contagieuse sera tenu a l"ecart jusqu"a presentation d"un certificat de guerison.</p><h3>Article 3 – Discipline</h3><p>Les parents s"engagent a respecter les horaires d"accueil et de sortie affiches dans l"etablissement.</p><p>Lu et approuve le : _______________</p></div>`,
  },
  {
    code: 'pres_autorisation_soins_creche',
    name: "Autorisation parentale de soins en creche",
    category: 'academique',
    price: 1500,
    priceMax: 4500,
    description: "Formulaire d\"autorisation donnee par les parents pour que la creche puisse administrer des soins de premiere urgence a leur enfant.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'nom_parent', label: "Nom du parent ou tuteur", type: 'text', required: true },
      { key: 'allergies_connues', label: "Allergies ou contre-indications connues", type: 'textarea', required: false },
      { key: 'medecin_traitant', label: "Nom et contact du medecin traitant", type: 'text', required: true },
      { key: 'date_autorisation', label: "Date de signature de l\"autorisation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>AUTORISATION PARENTALE DE SOINS EN CRECHE</h1><p>Je soussigne(e) <strong>{{nom_parent}}</strong>, parent ou tuteur legal de l"enfant <strong>{{nom_enfant}}</strong>, autorise expressement le personnel de la creche a prodiguer les premiers soins necessaires en cas d"urgence.</p><p><strong>Allergies / Contre-indications :</strong> {{allergies_connues}}</p><p><strong>Medecin traitant :</strong> {{medecin_traitant}}</p><p>En cas de necessite, j"autorise egalement le transfert de l"enfant vers l"etablissement de sante le plus proche.</p><p>Fait le {{date_autorisation}}</p><p>Signature : _______________</p></div>`,
  },
  {
    code: 'pres_fiche_sante_nourrisson',
    name: "Fiche de sante du nourrisson",
    category: 'academique',
    price: 1500,
    priceMax: 4000,
    description: "Fiche medicale et sanitaire du nourrisson renseignee a l\"entree en creche, comprenant les antecedents et le carnet de vaccinations.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'groupe_sanguin', label: "Groupe sanguin et rhesus", type: 'text', required: false },
      { key: 'vaccins_effectues', label: "Vaccins effectues (liste)", type: 'textarea', required: true },
      { key: 'antecedents_medicaux', label: "Antecedents medicaux importants", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>FICHE DE SANTE DU NOURRISSON</h1><p><strong>Nom :</strong> {{nom_enfant}}</p><p><strong>Date de naissance :</strong> {{date_naissance}}</p><p><strong>Groupe sanguin :</strong> {{groupe_sanguin}}</p><h3>Vaccinations</h3><p>{{vaccins_effectues}}</p><h3>Antecedents medicaux</h3><p>{{antecedents_medicaux}}</p><p>Certifie exact par le parent le : _______________   Signature : _______________</p></div>`,
  },
  {
    code: 'pres_plan_alimentaire_creche',
    name: "Plan alimentaire de creche",
    category: 'academique',
    price: 2000,
    priceMax: 5000,
    description: "Document definissant les menus hebdomadaires et les regles nutritionnelles appliquees en creche pour les enfants de 0 a 3 ans.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_creche', label: "Nom de la creche", type: 'text', required: true },
      { key: 'periode_plan', label: "Periode couverte par le plan", type: 'text', required: true },
      { key: 'menu_semaine', label: "Detail des menus de la semaine", type: 'textarea', required: true },
      { key: 'responsable_nutrition', label: "Nom du responsable nutrition", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN ALIMENTAIRE DE CRECHE</h1><p><strong>Etablissement :</strong> {{nom_creche}}</p><p><strong>Periode :</strong> {{periode_plan}}</p><p><strong>Responsable nutrition :</strong> {{responsable_nutrition}}</p><h3>Menus de la semaine</h3><p>{{menu_semaine}}</p><p>Ce plan est elabore en conformite avec les recommandations nutritionnelles de l"OMS et adapte aux specificites alimentaires locales ivoiriennes.</p><p>Valide par le responsable le : _______________</p></div>`,
  },
  {
    code: 'pres_rapport_developpement_enfant',
    name: "Rapport de developpement de l\"enfant",
    category: 'academique',
    price: 2500,
    priceMax: 7000,
    description: "Rapport periodique etabli par l\"educatrice sur le developpement psychomoteur, langagier et social de l\"enfant en creche ou maternelle.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'periode_rapport', label: "Periode evaluee", type: 'text', required: true },
      { key: 'observations_motricite', label: "Observations sur la motricite", type: 'textarea', required: true },
      { key: 'observations_langage', label: "Observations sur le langage", type: 'textarea', required: true },
      { key: 'recommandations', label: "Recommandations de l\"educatrice", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE DEVELOPPEMENT DE L"ENFANT</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Periode :</strong> {{periode_rapport}}</p><h3>Developpement moteur</h3><p>{{observations_motricite}}</p><h3>Developpement du langage</h3><p>{{observations_langage}}</p><h3>Recommandations</h3><p>{{recommandations}}</p><p>Rapport etabli par l"educatrice responsable le : _______________</p></div>`,
  },
  {
    code: 'pres_programme_pedagogique_prescolaire',
    name: "Programme pedagogique prescolaire",
    category: 'academique',
    price: 3000,
    priceMax: 8000,
    description: "Programme d\"activites pedagogiques pour les enfants de 2 a 5 ans, conforme aux orientations du Ministere de l\"Education Nationale ivoirien.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_etablissement', label: "Nom de l\"etablissement prescolaire", type: 'text', required: true },
      { key: 'annee_scolaire', label: "Annee scolaire", type: 'text', required: true },
      { key: 'tranche_age', label: "Tranche d\"age visee", type: 'text', required: true },
      { key: 'objectifs_annuels', label: "Objectifs pedagogiques annuels", type: 'textarea', required: true },
      { key: 'activites_programmees', label: "Activites et ateliers programmes", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROGRAMME PEDAGOGIQUE PRESCOLAIRE</h1><p><strong>Etablissement :</strong> {{nom_etablissement}}</p><p><strong>Annee scolaire :</strong> {{annee_scolaire}}</p><p><strong>Tranche d"age :</strong> {{tranche_age}}</p><h3>Objectifs annuels</h3><p>{{objectifs_annuels}}</p><h3>Activites et ateliers</h3><p>{{activites_programmees}}</p><p>Valide par la direction pedagogique le : _______________</p></div>`,
  },
  {
    code: 'pres_contrat_educatrice_eje',
    name: "Contrat d\"educatrice de jeunes enfants",
    category: 'academique',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de travail specifique pour une educatrice de jeunes enfants (EJE) employee dans une creche ou un etablissement prescolaire en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'nom_educatrice', label: "Nom et prenoms de l\"educatrice", type: 'text', required: true },
      { key: 'date_embauche', label: "Date de prise de poste", type: 'date', required: true },
      { key: 'nom_creche', label: "Nom de la structure employeuse", type: 'text', required: true },
      { key: 'salaire_mensuel', label: "Salaire mensuel brut (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Duree du contrat (CDD/CDI)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE TRAVAIL – EDUCATRICE DE JEUNES ENFANTS</h1><p>Entre <strong>{{nom_creche}}</strong>, ci-apres "l"employeur", et <strong>{{nom_educatrice}}</strong>, ci-apres "la salariee", il est conclu le present contrat de travail.</p><p><strong>Date de prise de poste :</strong> {{date_embauche}}</p><p><strong>Duree :</strong> {{duree_contrat}}</p><p><strong>Remuneration :</strong> {{salaire_mensuel}} FCFA brut mensuel</p><p>La salariee s"engage a exercer ses fonctions avec competence et bienveillance conformement au referentiel du metier d"educatrice de jeunes enfants.</p><p>Fait en deux exemplaires.</p><p>L"employeur : _______________   La salariee : _______________</p></div>`,
  },
  {
    code: 'pres_convention_partenariat_creche_maternelle',
    name: "Convention de partenariat creche-maternelle",
    category: 'academique',
    price: 4000,
    priceMax: 12000,
    description: "Convention formalisant la collaboration pedagogique et administrative entre une creche et une ecole maternelle pour faciliter la transition des enfants.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'nom_creche', label: "Denomination de la creche", type: 'text', required: true },
      { key: 'nom_maternelle', label: "Denomination de l\"ecole maternelle", type: 'text', required: true },
      { key: 'date_convention', label: "Date de signature de la convention", type: 'date', required: true },
      { key: 'duree_convention', label: "Duree de la convention", type: 'text', required: true },
      { key: 'objectifs_partenariat', label: "Objectifs du partenariat", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PARTENARIAT CRECHE – MATERNELLE</h1><p>Entre <strong>{{nom_creche}}</strong> et <strong>{{nom_maternelle}}</strong>, il est conclu la presente convention de partenariat.</p><p><strong>Date :</strong> {{date_convention}}</p><p><strong>Duree :</strong> {{duree_convention}}</p><h3>Objectifs</h3><p>{{objectifs_partenariat}}</p><p>Les deux parties s"engagent a collaborer dans l"interet superieur des enfants et a partager les informations pedagogiques pertinentes.</p><p>Directrice de la creche : _______________   Directrice de la maternelle : _______________</p></div>`,
  },
  {
    code: 'pres_inscription_maternelle',
    name: "Dossier d\"inscription a l\"ecole maternelle",
    category: 'academique',
    price: 2000,
    priceMax: 6000,
    description: "Dossier administratif complet pour l\"inscription d\"un enfant en classe de petite, moyenne ou grande section de maternelle en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'section_demandee', label: "Section demandee (PS/MS/GS)", type: 'text', required: true },
      { key: 'nom_parent', label: "Nom du parent ou representant legal", type: 'text', required: true },
      { key: 'nom_ecole', label: "Nom de l\"ecole maternelle", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER D"INSCRIPTION – ECOLE MATERNELLE</h1><p><strong>Ecole :</strong> {{nom_ecole}}</p><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Ne(e) le :</strong> {{date_naissance}}</p><p><strong>Section demandee :</strong> {{section_demandee}}</p><p><strong>Parent / Representant legal :</strong> {{nom_parent}}</p><p>Je certifie l"exactitude des informations fournies et m"engage a fournir les documents requis (extrait de naissance, carnet de sante, photos d"identite).</p><p>Date et signature : _______________</p></div>`,
  },
  {
    code: 'pres_livret_competences_maternelle',
    name: "Livret de competences maternelle",
    category: 'academique',
    price: 2500,
    priceMax: 7000,
    description: "Livret d\"evaluation des competences acquises par l\"enfant au cours de sa scolarite en maternelle, remis aux parents en fin de trimestre.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'section', label: "Section (PS / MS / GS)", type: 'text', required: true },
      { key: 'trimestre', label: "Trimestre evalue", type: 'text', required: true },
      { key: 'competences_acquises', label: "Competences acquises", type: 'textarea', required: true },
      { key: 'appreciation_generale', label: "Appreciation generale de l\"enseignant", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>LIVRET DE COMPETENCES MATERNELLE</h1><p><strong>Eleve :</strong> {{nom_enfant}}</p><p><strong>Section :</strong> {{section}}</p><p><strong>Trimestre :</strong> {{trimestre}}</p><h3>Competences acquises</h3><p>{{competences_acquises}}</p><h3>Appreciation generale</h3><p>{{appreciation_generale}}</p><p>Visa de l"enseignant(e) : _______________   Visa des parents : _______________</p></div>`,
  },
  {
    code: 'pres_pai',
    name: "Projet d\"accueil individualise (PAI)",
    category: 'academique',
    price: 3000,
    priceMax: 9000,
    description: "Document officiel etabli entre l\"etablissement scolaire, les parents et le medecin pour adapter l\"accueil d\"un enfant presentant un trouble de sante ou un handicap.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'pathologie', label: "Pathologie ou trouble concerne", type: 'text', required: true },
      { key: 'amenagements_prevus', label: "Amenagements et adaptations prevus", type: 'textarea', required: true },
      { key: 'nom_medecin', label: "Nom du medecin referent", type: 'text', required: true },
      { key: 'date_pai', label: "Date d\"etablissement du PAI", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PROJET D"ACCUEIL INDIVIDUALISE (PAI)</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Pathologie / Trouble :</strong> {{pathologie}}</p><p><strong>Medecin referent :</strong> {{nom_medecin}}</p><p><strong>Date :</strong> {{date_pai}}</p><h3>Amenagements mis en place</h3><p>{{amenagements_prevus}}</p><p>Signatures : Direction : _______________ Parents : _______________ Medecin : _______________</p></div>`,
  },
  {
    code: 'pres_signalement_enfant_vulnerable',
    name: "Fiche de signalement enfant vulnerable en milieu scolaire",
    category: 'academique',
    price: 2000,
    priceMax: 5000,
    description: "Fiche de signalement permettant au personnel de l\"etablissement prescolaire de remonter une situation de vulnerabilite ou de maltraitance concernant un enfant.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'faits_observes', label: "Description des faits observes", type: 'textarea', required: true },
      { key: 'date_observation', label: "Date et heure de l\"observation", type: 'date', required: true },
      { key: 'nom_signalant', label: "Nom de l\"agent signalant", type: 'text', required: true },
      { key: 'mesures_prises', label: "Mesures d\"urgence prises", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>FICHE DE SIGNALEMENT – ENFANT VULNERABLE</h1><p><strong>Enfant concerne :</strong> {{nom_enfant}}</p><p><strong>Date d"observation :</strong> {{date_observation}}</p><p><strong>Agent signalant :</strong> {{nom_signalant}}</p><h3>Faits observes</h3><p>{{faits_observes}}</p><h3>Mesures d"urgence</h3><p>{{mesures_prises}}</p><p>Ce document est strictement confidentiel et transmis a la direction et aux autorites competentes.</p></div>`,
  },
  {
    code: 'pres_contrat_nourrice_agreee',
    name: "Contrat de nourrice agreee",
    category: 'academique',
    price: 3000,
    priceMax: 8000,
    description: "Contrat etabli entre des parents et une nourrice agreee par les services sociaux, definissant les conditions de garde a domicile d\"un nourrisson.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_nourrice', label: "Nom et prenoms de la nourrice", type: 'text', required: true },
      { key: 'nom_enfant', label: "Nom de l\"enfant garde", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut de la garde", type: 'date', required: true },
      { key: 'remuneration', label: "Remuneration mensuelle (FCFA)", type: 'text', required: true },
      { key: 'adresse_garde', label: "Lieu de la garde", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE NOURRICE AGREEE</h1><p>Entre les parents de <strong>{{nom_enfant}}</strong> et <strong>{{nom_nourrice}}</strong>, nourrice agreee, il est convenu ce qui suit :</p><p><strong>Debut de la garde :</strong> {{date_debut}}</p><p><strong>Lieu de garde :</strong> {{adresse_garde}}</p><p><strong>Remuneration mensuelle :</strong> {{remuneration}} FCFA</p><p>La nourrice s"engage a assurer la securite, le confort et le bien-etre de l"enfant durant les heures de garde.</p><p>Signatures : Parents : _______________   Nourrice : _______________</p></div>`,
  },
  {
    code: 'pres_convention_assistante_maternelle',
    name: "Convention avec assistante maternelle",
    category: 'academique',
    price: 3500,
    priceMax: 10000,
    description: "Convention d\"accueil detaillee passee entre une famille et une assistante maternelle agreee, en conformite avec la legislation ivoirienne du travail.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'nom_assistante', label: "Nom de l\"assistante maternelle", type: 'text', required: true },
      { key: 'numero_agrement', label: "Numero d\"agrement officiel", type: 'text', required: true },
      { key: 'nom_enfant', label: "Nom de l\"enfant accueilli", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut de l\"accueil", type: 'date', required: true },
      { key: 'salaire_net', label: "Salaire net mensuel (FCFA)", type: 'text', required: true },
      { key: 'horaires', label: "Horaires d\"accueil hebdomadaires", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D"ACCUEIL – ASSISTANTE MATERNELLE</h1><p><strong>Assistante maternelle :</strong> {{nom_assistante}} (Agrement N° {{numero_agrement}})</p><p><strong>Enfant accueilli :</strong> {{nom_enfant}}</p><p><strong>Debut de l"accueil :</strong> {{date_debut}}</p><p><strong>Horaires :</strong> {{horaires}}</p><p><strong>Remuneration nette :</strong> {{salaire_net}} FCFA / mois</p><p>Les parties s"engagent a respecter les dispositions du Code du Travail de Cote d"Ivoire.</p><p>Signatures : Famille : _______________   Assistante maternelle : _______________</p></div>`,
  },
  {
    code: 'pres_reglement_fonctionnement_am',
    name: "Reglement de fonctionnement assistante maternelle",
    category: 'academique',
    price: 2000,
    priceMax: 5500,
    description: "Document reglementaire complementaire a la convention, precisant les regles de vie pratiques, protocoles d\"urgence et modalites de communication avec la famille.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'nom_assistante', label: "Nom de l\"assistante maternelle", type: 'text', required: true },
      { key: 'adresse_accueil', label: "Adresse du lieu d\"accueil", type: 'text', required: true },
      { key: 'nombre_enfants_max', label: "Nombre maximal d\"enfants accueillis", type: 'text', required: true },
      { key: 'protocole_urgence', label: "Protocole en cas d\"urgence medicale", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>REGLEMENT DE FONCTIONNEMENT – ASSISTANTE MATERNELLE</h1><p><strong>Assistante :</strong> {{nom_assistante}}</p><p><strong>Adresse :</strong> {{adresse_accueil}}</p><p><strong>Capacite maximale :</strong> {{nombre_enfants_max}} enfants</p><h3>Protocole d"urgence</h3><p>{{protocole_urgence}}</p><p>Ce reglement est remis a chaque famille lors de la signature de la convention d"accueil.</p></div>`,
  },
  {
    code: 'pres_contrat_association_parents',
    name: "Contrat d\"association parents d\"eleves maternelle",
    category: 'academique',
    price: 2500,
    priceMax: 7000,
    description: "Acte fondateur ou d\"adhesion d\"une association de parents d\"eleves au sein d\"un etablissement maternelle, selon le droit associatif ivoirien.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'nom_association', label: "Denomination de l\"association", type: 'text', required: true },
      { key: 'nom_ecole', label: "Ecole de rattachement", type: 'text', required: true },
      { key: 'president', label: "Nom du president elu", type: 'text', required: true },
      { key: 'date_creation', label: "Date de creation ou d\"adhesion", type: 'date', required: true },
      { key: 'objectifs', label: "Objectifs de l\"association", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"ASSOCIATION DE PARENTS D"ELEVES</h1><h2>{{nom_association}}</h2><p><strong>Ecole :</strong> {{nom_ecole}}</p><p><strong>President :</strong> {{president}}</p><p><strong>Date :</strong> {{date_creation}}</p><h3>Objectifs</h3><p>{{objectifs}}</p><p>Lu et approuve par les membres fondateurs.</p></div>`,
  },
  {
    code: 'pres_cr_reunion_parents_maternelle',
    name: "Compte rendu de reunion parents maternelle",
    category: 'academique',
    price: 1500,
    priceMax: 4000,
    description: "Modele de compte rendu officiel des reunions de parents d\"eleves organisees par l\"etablissement maternelle, avec suivi des decisions.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'nom_ecole', label: "Nom de l\"ecole maternelle", type: 'text', required: true },
      { key: 'date_reunion', label: "Date de la reunion", type: 'date', required: true },
      { key: 'ordre_du_jour', label: "Ordre du jour de la reunion", type: 'textarea', required: true },
      { key: 'decisions_prises', label: "Decisions prises en reunion", type: 'textarea', required: true },
      { key: 'secretaire_seance', label: "Nom du secretaire de seance", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>COMPTE RENDU DE REUNION PARENTS – MATERNELLE</h1><p><strong>Ecole :</strong> {{nom_ecole}}</p><p><strong>Date :</strong> {{date_reunion}}</p><p><strong>Secretaire de seance :</strong> {{secretaire_seance}}</p><h3>Ordre du jour</h3><p>{{ordre_du_jour}}</p><h3>Decisions</h3><p>{{decisions_prises}}</p><p>Approuve par la direction le : _______________</p></div>`,
  },
  {
    code: 'pres_plan_mise_en_securite',
    name: "Plan de mise en securite d\"etablissement scolaire prescolaire",
    category: 'academique',
    price: 3500,
    priceMax: 10000,
    description: "Plan d\"evacuation et de mise en securite en cas de sinistre ou d\"urgence pour un etablissement accueillant des enfants en bas age.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'nom_etablissement', label: "Nom de l\"etablissement", type: 'text', required: true },
      { key: 'responsable_securite', label: "Nom du responsable securite", type: 'text', required: true },
      { key: 'risques_identifies', label: "Risques identifies (incendie, inondation, etc.)", type: 'textarea', required: true },
      { key: 'procedure_evacuation', label: "Procedure d\"evacuation des enfants", type: 'textarea', required: true },
      { key: 'contacts_urgence', label: "Contacts d\"urgence (pompiers, SAMU, police)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE MISE EN SECURITE – ETABLISSEMENT PRESCOLAIRE</h1><p><strong>Etablissement :</strong> {{nom_etablissement}}</p><p><strong>Responsable securite :</strong> {{responsable_securite}}</p><p><strong>Contacts d"urgence :</strong> {{contacts_urgence}}</p><h3>Risques identifies</h3><p>{{risques_identifies}}</p><h3>Procedure d"evacuation</h3><p>{{procedure_evacuation}}</p><p>Ce plan est affiche dans chaque salle de classe et revise chaque annee.</p></div>`,
  },
  {
    code: 'pres_protocole_medicament_ecole',
    name: "Protocole d\"administration de medicament a l\"ecole",
    category: 'academique',
    price: 2000,
    priceMax: 5500,
    description: "Protocole officiel permettant au personnel scolaire d\"administrer un traitement medical prescrit a un eleve du prescolaire dans l\"enceinte de l\"etablissement.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'medicament', label: "Nom du medicament prescrit", type: 'text', required: true },
      { key: 'posologie', label: "Posologie et horaire d\"administration", type: 'textarea', required: true },
      { key: 'nom_medecin', label: "Nom du medecin prescripteur", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut du traitement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PROTOCOLE D"ADMINISTRATION DE MEDICAMENT A L"ECOLE</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Medicament :</strong> {{medicament}}</p><p><strong>Prescripteur :</strong> {{nom_medecin}}</p><p><strong>Debut du traitement :</strong> {{date_debut}}</p><h3>Posologie et conditions d"administration</h3><p>{{posologie}}</p><p>Autorisation parentale : _______________   Visa de la direction : _______________</p></div>`,
  },
  {
    code: 'pres_accord_garderie_periscolaire',
    name: "Accord de garderie periscolaire",
    category: 'academique',
    price: 2000,
    priceMax: 6000,
    description: "Accord entre l\"etablissement et les parents pour la prise en charge de l\"enfant dans le cadre des activites periscolaires (garderie du matin et du soir).",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l\"enfant", type: 'text', required: true },
      { key: 'type_garderie', label: "Garderie du matin / du soir / les deux", type: 'text', required: true },
      { key: 'horaires', label: "Horaires de la garderie", type: 'text', required: true },
      { key: 'tarif_mensuel', label: "Tarif mensuel (FCFA)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut de la garderie", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GARDERIE PERISCOLAIRE</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Type de garderie :</strong> {{type_garderie}}</p><p><strong>Horaires :</strong> {{horaires}}</p><p><strong>Tarif mensuel :</strong> {{tarif_mensuel}} FCFA</p><p><strong>Debut :</strong> {{date_debut}}</p><p>Les parents s"engagent a venir chercher l"enfant a l"heure prevue. Tout depassement fera l"objet d"une facturation supplementaire.</p><p>Signature : _______________</p></div>`,
  },
  {
    code: 'pres_contrat_activites_extrascolaires',
    name: "Contrat d\"activites extrascolaires",
    category: 'academique',
    price: 2000,
    priceMax: 6000,
    description: "Contrat d\"inscription et de participation d\"un enfant a des activites extrascolaires (sport, arts, eveil musical) proposees par l\"etablissement ou un partenaire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 54,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'activite', label: "Activite concernee", type: 'text', required: true },
      { key: 'nom_prestataire', label: "Nom du prestataire ou de l\"animateur", type: 'text', required: true },
      { key: 'tarif', label: "Tarif (FCFA)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"ACTIVITES EXTRASCOLAIRES</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Activite :</strong> {{activite}}</p><p><strong>Prestataire :</strong> {{nom_prestataire}}</p><p><strong>Tarif :</strong> {{tarif}} FCFA</p><p><strong>Debut :</strong> {{date_debut}}</p><p>Les parents certifient que l"enfant est apte a pratiquer l"activite mentionnee ci-dessus.</p><p>Signature : _______________</p></div>`,
  },
  {
    code: 'pres_plan_lutte_decrochage',
    name: "Plan de lutte contre le decrochage precoce",
    category: 'academique',
    price: 3000,
    priceMax: 8000,
    description: "Plan d\"action elabore par l\"etablissement prescolaire pour identifier et accompagner les enfants a risque d\"abandon scolaire precoce.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 47,
    fieldsJson: F([
      { key: 'nom_etablissement', label: "Nom de l\"etablissement", type: 'text', required: true },
      { key: 'annee_scolaire', label: "Annee scolaire", type: 'text', required: true },
      { key: 'profil_enfants_risque', label: "Profil des enfants identifies a risque", type: 'textarea', required: true },
      { key: 'actions_retenues', label: "Actions de remobilisation retenues", type: 'textarea', required: true },
      { key: 'responsable_suivi', label: "Responsable du suivi du plan", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE LUTTE CONTRE LE DECROCHAGE PRECOCE</h1><p><strong>Etablissement :</strong> {{nom_etablissement}}</p><p><strong>Annee scolaire :</strong> {{annee_scolaire}}</p><p><strong>Responsable du suivi :</strong> {{responsable_suivi}}</p><h3>Profil des enfants a risque</h3><p>{{profil_enfants_risque}}</p><h3>Actions de remobilisation</h3><p>{{actions_retenues}}</p><p>Valide par la direction le : _______________</p></div>`,
  },
  {
    code: 'pres_bilan_fin_cycle_prescolaire',
    name: "Bilan de fin de cycle prescolaire",
    category: 'academique',
    price: 2500,
    priceMax: 7000,
    description: "Bilan synthetique etabli en fin de grande section de maternelle, dressant un portrait global du developpement et des acquis de l\"enfant avant son entree en CP.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l\"enfant", type: 'text', required: true },
      { key: 'annee_scolaire', label: "Annee scolaire", type: 'text', required: true },
      { key: 'acquis_fondamentaux', label: "Acquis fondamentaux (lecture, numeratie, motricite)", type: 'textarea', required: true },
      { key: 'points_vigilance', label: "Points de vigilance pour le CP", type: 'textarea', required: false },
      { key: 'enseignante', label: "Nom de l\"enseignante responsable", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>BILAN DE FIN DE CYCLE PRESCOLAIRE</h1><p><strong>Eleve :</strong> {{nom_enfant}}</p><p><strong>Annee scolaire :</strong> {{annee_scolaire}}</p><p><strong>Enseignante :</strong> {{enseignante}}</p><h3>Acquis fondamentaux</h3><p>{{acquis_fondamentaux}}</p><h3>Points de vigilance pour le CP</h3><p>{{points_vigilance}}</p><p>Document transmis a l"enseignant(e) de CP avec l"accord des parents.</p><p>Signatures : _______________</p></div>`,
  },

  // ─── ACTION SOCIALE / PROTECTION SOCIALE (soc2_) ────────────────────────────
  {
    code: 'soc2_rapport_enquete_sociale',
    name: "Rapport d\"enquete sociale",
    category: 'association',
    price: 3500,
    priceMax: 10000,
    description: "Rapport etabli par un travailleur social a l\"issue d\"une enquete de situation aupres d\"un individu ou d\"une famille en situation de fragilite en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom et prenoms du beneficiaire", type: 'text', required: true },
      { key: 'adresse_enquete', label: "Adresse du lieu d\"enquete", type: 'text', required: true },
      { key: 'date_enquete', label: "Date de l\"enquete", type: 'date', required: true },
      { key: 'situation_sociale', label: "Description de la situation sociale", type: 'textarea', required: true },
      { key: 'propositions_aide', label: "Propositions d\"aide et de suivi", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D"ENQUETE SOCIALE</h1><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Adresse :</strong> {{adresse_enquete}}</p><p><strong>Date de l"enquete :</strong> {{date_enquete}}</p><h3>Situation sociale constatee</h3><p>{{situation_sociale}}</p><h3>Propositions d"aide</h3><p>{{propositions_aide}}</p><p>Rapport etabli par le travailleur social : _______________</p></div>`,
  },
  {
    code: 'soc2_plan_aide_sociale',
    name: "Plan d\"aide sociale individualise",
    category: 'association',
    price: 3000,
    priceMax: 9000,
    description: "Plan d\"accompagnement personnalise co-construit entre le service social et le beneficiaire, definissant les objectifs et les moyens d\"aide mobilises.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom du beneficiaire", type: 'text', required: true },
      { key: 'objectifs_plan', label: "Objectifs prioritaires du plan", type: 'textarea', required: true },
      { key: 'actions_planifiees', label: "Actions planifiees et echeances", type: 'textarea', required: true },
      { key: 'referent_social', label: "Nom du referent social", type: 'text', required: true },
      { key: 'date_plan', label: "Date d\"elaboration du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D"AIDE SOCIALE INDIVIDUALISE</h1><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Referent social :</strong> {{referent_social}}</p><p><strong>Date :</strong> {{date_plan}}</p><h3>Objectifs prioritaires</h3><p>{{objectifs_plan}}</p><h3>Actions planifiees</h3><p>{{actions_planifiees}}</p><p>Signatures : Referent : _______________   Beneficiaire : _______________</p></div>`,
  },
  {
    code: 'soc2_convention_hebergement_urgence',
    name: "Convention d\"hebergement d\"urgence",
    category: 'association',
    price: 4000,
    priceMax: 11000,
    description: "Convention entre une structure d\"accueil et une personne sans abri ou en situation de danger, etablissant les conditions d\"hebergement temporaire d\"urgence.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom de la personne hebergee", type: 'text', required: true },
      { key: 'nom_structure', label: "Denomination de la structure d\"accueil", type: 'text', required: true },
      { key: 'date_entree', label: "Date d\"entree en hebergement", type: 'date', required: true },
      { key: 'duree_prevue', label: "Duree prevue de l\"hebergement", type: 'text', required: true },
      { key: 'conditions_accueil', label: "Conditions et regles de vie communes", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D"HEBERGEMENT D"URGENCE</h1><p>Entre <strong>{{nom_structure}}</strong> et <strong>{{nom_beneficiaire}}</strong>, il est convenu ce qui suit :</p><p><strong>Date d"entree :</strong> {{date_entree}}</p><p><strong>Duree prevue :</strong> {{duree_prevue}}</p><h3>Conditions d"accueil</h3><p>{{conditions_accueil}}</p><p>La presente convention peut etre resiliee a tout moment en cas de non-respect des regles etablies.</p><p>Signatures : Structure : _______________   Beneficiaire : _______________</p></div>`,
  },
  {
    code: 'soc2_accord_prise_en_charge_vulnerables',
    name: "Accord de prise en charge de personnes vulnerables",
    category: 'association',
    price: 3500,
    priceMax: 10000,
    description: "Accord formalisant la prise en charge globale (medicale, sociale, psychologique) d\"une personne vulnerabe (enfant, personne agee, handicapee) par un organisme social.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom de la personne prise en charge", type: 'text', required: true },
      { key: 'type_vulnerabilite', label: "Nature de la vulnerabilite", type: 'text', required: true },
      { key: 'nom_organisme', label: "Nom de l\"organisme de prise en charge", type: 'text', required: true },
      { key: 'services_offerts', label: "Services et accompagnements offerts", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l\"accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRISE EN CHARGE DE PERSONNES VULNERABLES</h1><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Nature de la vulnerabilite :</strong> {{type_vulnerabilite}}</p><p><strong>Organisme :</strong> {{nom_organisme}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Services et accompagnements</h3><p>{{services_offerts}}</p><p>Cet accord est conclu dans le respect de la dignite et des droits fondamentaux de la personne.</p></div>`,
  },
  {
    code: 'soc2_contrat_educateur_specialise',
    name: "Contrat de travail d\"educateur specialise",
    category: 'association',
    price: 3500,
    priceMax: 10500,
    description: "Contrat de travail pour un educateur specialise embauche par une association ou un service public d\"action sociale en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_educateur', label: "Nom et prenoms de l\"educateur", type: 'text', required: true },
      { key: 'nom_employeur', label: "Nom de la structure employeuse", type: 'text', required: true },
      { key: 'date_prise_poste', label: "Date de prise de poste", type: 'date', required: true },
      { key: 'salaire_brut', label: "Salaire mensuel brut (FCFA)", type: 'text', required: true },
      { key: 'type_contrat', label: "Type de contrat (CDD / CDI)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE TRAVAIL – EDUCATEUR SPECIALISE</h1><p>Entre <strong>{{nom_employeur}}</strong> et <strong>{{nom_educateur}}</strong>.</p><p><strong>Prise de poste :</strong> {{date_prise_poste}}</p><p><strong>Type de contrat :</strong> {{type_contrat}}</p><p><strong>Remuneration :</strong> {{salaire_brut}} FCFA brut mensuel</p><p>L"educateur specialise s"engage a intervenir aupres des publics vulnerables dans le respect du code de deontologie de la profession.</p><p>Signatures : Employeur : _______________   Salarie : _______________</p></div>`,
  },
  {
    code: 'soc2_convention_foyer_accueil',
    name: "Convention de foyer d\"accueil social",
    category: 'association',
    price: 4000,
    priceMax: 12000,
    description: "Convention regulant le fonctionnement d\"un foyer d\"accueil (jeunes, femmes en difficulte, personnes desocialisees) en partenariat avec les autorites ivoiriennes.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'nom_foyer', label: "Denomination du foyer d\"accueil", type: 'text', required: true },
      { key: 'autorite_partenaire', label: "Autorite publique partenaire", type: 'text', required: true },
      { key: 'capacite_accueil', label: "Capacite d\"accueil du foyer", type: 'text', required: true },
      { key: 'missions_foyer', label: "Missions et objectifs du foyer", type: 'textarea', required: true },
      { key: 'date_convention', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE FOYER D"ACCUEIL SOCIAL</h1><p><strong>Foyer :</strong> {{nom_foyer}}</p><p><strong>Partenaire public :</strong> {{autorite_partenaire}}</p><p><strong>Capacite :</strong> {{capacite_accueil}} residents</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Missions</h3><p>{{missions_foyer}}</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'soc2_accord_maison_retraite',
    name: "Accord de maison de retraite",
    category: 'association',
    price: 4500,
    priceMax: 12000,
    description: "Accord d\"entree et de sejour d\"une personne agee dans une maison de retraite ou un etablissement pour personnes agees dependantes en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 54,
    fieldsJson: F([
      { key: 'nom_resident', label: "Nom et prenoms du resident", type: 'text', required: true },
      { key: 'nom_etablissement', label: "Nom de la maison de retraite", type: 'text', required: true },
      { key: 'date_entree', label: "Date d\"entree dans l\"etablissement", type: 'date', required: true },
      { key: 'tarif_mensuel', label: "Tarif mensuel tout compris (FCFA)", type: 'text', required: true },
      { key: 'nom_referent_famille', label: "Nom du referent familial", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D"ENTREE EN MAISON DE RETRAITE</h1><p><strong>Etablissement :</strong> {{nom_etablissement}}</p><p><strong>Resident :</strong> {{nom_resident}}</p><p><strong>Date d"entree :</strong> {{date_entree}}</p><p><strong>Tarif mensuel :</strong> {{tarif_mensuel}} FCFA</p><p><strong>Referent familial :</strong> {{nom_referent_famille}}</p><p>La structure s"engage a assurer le bien-etre, la securite et la dignite du resident tout au long de son sejour.</p><p>Signatures : Direction : _______________   Famille : _______________</p></div>`,
  },
  {
    code: 'soc2_contrat_tutelle_majeur_protege',
    name: "Contrat de tutelle de majeur protege",
    category: 'association',
    price: 5000,
    priceMax: 12000,
    description: "Contrat encadrant la mission d\"un tuteur designe par la justice ivoirienne pour proteger les interets d\"un adulte dont les facultes sont alterees.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'nom_protege', label: "Nom du majeur protege", type: 'text', required: true },
      { key: 'nom_tuteur', label: "Nom et qualite du tuteur", type: 'text', required: true },
      { key: 'date_jugement', label: "Date du jugement de mise sous tutelle", type: 'date', required: true },
      { key: 'tribunal', label: "Tribunal ayant prononce la mesure", type: 'text', required: true },
      { key: 'obligations_tuteur', label: "Principales obligations du tuteur", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE TUTELLE – MAJEUR PROTEGE</h1><p><strong>Majeur protege :</strong> {{nom_protege}}</p><p><strong>Tuteur :</strong> {{nom_tuteur}}</p><p><strong>Jugement du :</strong> {{date_jugement}}</p><p><strong>Tribunal :</strong> {{tribunal}}</p><h3>Obligations du tuteur</h3><p>{{obligations_tuteur}}</p><p>Le tuteur agit sous le controle du juge des tutelles et rend compte annuellement de sa gestion.</p></div>`,
  },
  {
    code: 'soc2_rapport_suivi_famille',
    name: "Rapport de suivi de famille en difficulte",
    category: 'association',
    price: 3000,
    priceMax: 8000,
    description: "Rapport periodique de suivi social etabli par un assistant social pour une famille beneficiaire d\"un accompagnement social en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'nom_famille', label: "Nom de la famille suivie", type: 'text', required: true },
      { key: 'periode_suivi', label: "Periode de suivi concernee", type: 'text', required: true },
      { key: 'evolution_situation', label: "Evolution de la situation sociale", type: 'textarea', required: true },
      { key: 'obstacles_rencontres', label: "Obstacles et difficultes rencontres", type: 'textarea', required: false },
      { key: 'prochaines_etapes', label: "Prochaines etapes du suivi", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE SUIVI – FAMILLE EN DIFFICULTE</h1><p><strong>Famille :</strong> {{nom_famille}}</p><p><strong>Periode :</strong> {{periode_suivi}}</p><h3>Evolution de la situation</h3><p>{{evolution_situation}}</p><h3>Obstacles</h3><p>{{obstacles_rencontres}}</p><h3>Prochaines etapes</h3><p>{{prochaines_etapes}}</p><p>Rapport redige par : _______________   Date : _______________</p></div>`,
  },
  {
    code: 'soc2_convention_centre_accueil',
    name: "Convention avec centre d\"accueil social",
    category: 'association',
    price: 4000,
    priceMax: 11000,
    description: "Convention de cooperation entre un centre d\"accueil social et un organisme public ou prive pour la prise en charge de populations en difficulte.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_centre', label: "Nom du centre d\"accueil", type: 'text', required: true },
      { key: 'nom_partenaire', label: "Nom de l\"organisme partenaire", type: 'text', required: true },
      { key: 'population_cible', label: "Population cible de la convention", type: 'text', required: true },
      { key: 'engagements_reciproques', label: "Engagements reciproques des parties", type: 'textarea', required: true },
      { key: 'date_convention', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION AVEC CENTRE D"ACCUEIL SOCIAL</h1><p><strong>Centre d"accueil :</strong> {{nom_centre}}</p><p><strong>Partenaire :</strong> {{nom_partenaire}}</p><p><strong>Population cible :</strong> {{population_cible}}</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Engagements reciproques</h3><p>{{engagements_reciproques}}</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'soc2_accord_reseau_aide_sociale',
    name: "Accord de reseau d\"aide sociale",
    category: 'association',
    price: 3500,
    priceMax: 9000,
    description: "Accord de cooperation entre plusieurs associations et organismes sociaux constituant un reseau d\"entraide et d\"orientation des personnes en difficulte.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 49,
    fieldsJson: F([
      { key: 'nom_reseau', label: "Denomination du reseau", type: 'text', required: true },
      { key: 'membres_reseau', label: "Liste des membres du reseau", type: 'textarea', required: true },
      { key: 'objectifs_reseau', label: "Objectifs du reseau d\"aide", type: 'textarea', required: true },
      { key: 'coordinateur', label: "Nom du coordinateur du reseau", type: 'text', required: true },
      { key: 'date_accord', label: "Date de signature de l\"accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RESEAU D"AIDE SOCIALE</h1><h2>{{nom_reseau}}</h2><p><strong>Coordinateur :</strong> {{coordinateur}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Membres du reseau</h3><p>{{membres_reseau}}</p><h3>Objectifs communs</h3><p>{{objectifs_reseau}}</p><p>Signatures des membres fondateurs : _______________</p></div>`,
  },
  {
    code: 'soc2_contrat_aide_a_domicile',
    name: "Contrat de prestataire d\"aide a domicile",
    category: 'association',
    price: 3000,
    priceMax: 8500,
    description: "Contrat entre un prestataire de services d\"aide a domicile et un beneficiaire ou sa famille, pour des prestations d\"assistance aux personnes agees ou dependantes.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'nom_prestataire', label: "Nom du prestataire ou de l\"auxiliaire", type: 'text', required: true },
      { key: 'nom_beneficiaire', label: "Nom du beneficiaire", type: 'text', required: true },
      { key: 'prestations', label: "Nature des prestations assurees", type: 'textarea', required: true },
      { key: 'tarif_horaire', label: "Tarif horaire (FCFA)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut des interventions", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PRESTATAIRE D"AIDE A DOMICILE</h1><p><strong>Prestataire :</strong> {{nom_prestataire}}</p><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Debut des interventions :</strong> {{date_debut}}</p><p><strong>Tarif horaire :</strong> {{tarif_horaire}} FCFA</p><h3>Prestations assurées</h3><p>{{prestations}}</p><p>Signatures : Prestataire : _______________   Beneficiaire / Famille : _______________</p></div>`,
  },
  {
    code: 'soc2_plan_soutien_familles_monoparentales',
    name: "Plan de soutien aux familles monoparentales",
    category: 'association',
    price: 3000,
    priceMax: 8000,
    description: "Plan d\"accompagnement specialise destine aux familles monoparentales en difficulte, incluant aides financieres, soutien scolaire et accompagnement a l\"emploi.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_parent', label: "Nom du parent chef de famille", type: 'text', required: true },
      { key: 'nombre_enfants', label: "Nombre d\"enfants a charge", type: 'text', required: true },
      { key: 'aides_mobilisees', label: "Aides et dispositifs mobilises", type: 'textarea', required: true },
      { key: 'referent', label: "Nom du referent social", type: 'text', required: true },
      { key: 'date_plan', label: "Date d\"elaboration du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE SOUTIEN AUX FAMILLES MONOPARENTALES</h1><p><strong>Parent :</strong> {{nom_parent}}</p><p><strong>Enfants a charge :</strong> {{nombre_enfants}}</p><p><strong>Referent social :</strong> {{referent}}</p><p><strong>Date :</strong> {{date_plan}}</p><h3>Aides et dispositifs</h3><p>{{aides_mobilisees}}</p><p>Ce plan est revise tous les six mois en fonction de l"evolution de la situation familiale.</p></div>`,
  },
  {
    code: 'soc2_convention_aide_alimentaire',
    name: "Convention d\"aide alimentaire d\"urgence",
    category: 'association',
    price: 2500,
    priceMax: 7000,
    description: "Convention entre une association caritative ou un service social et un beneficiaire pour la fourniture d\"une aide alimentaire d\"urgence en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'nom_organisme', label: "Nom de l\"organisme distribuant l\"aide", type: 'text', required: true },
      { key: 'nom_beneficiaire', label: "Nom du beneficiaire", type: 'text', required: true },
      { key: 'nature_aide', label: "Nature de l\"aide alimentaire fournie", type: 'textarea', required: true },
      { key: 'duree_aide', label: "Duree prevue de l\"aide", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D"AIDE ALIMENTAIRE D"URGENCE</h1><p><strong>Organisme :</strong> {{nom_organisme}}</p><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Duree :</strong> {{duree_aide}}</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Nature de l"aide</h3><p>{{nature_aide}}</p><p>Cette aide est accordee a titre exceptionnel et ne constitue pas un droit acquis.</p></div>`,
  },
  {
    code: 'soc2_accord_partenariat_caritas',
    name: "Accord de partenariat CARITAS et association locale",
    category: 'association',
    price: 4000,
    priceMax: 11000,
    description: "Accord de partenariat entre CARITAS Cote d\"Ivoire ou une ONG similaire et une association locale pour la mise en oeuvre d\"activites de solidarite et de developpement social.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'nom_ong', label: "Denomination de l\"ONG partenaire", type: 'text', required: true },
      { key: 'nom_association', label: "Denomination de l\"association locale", type: 'text', required: true },
      { key: 'programme_commun', label: "Programme ou projet commun", type: 'textarea', required: true },
      { key: 'apports_respectifs', label: "Apports respectifs des deux parties", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT</h1><p><strong>ONG :</strong> {{nom_ong}}</p><p><strong>Association locale :</strong> {{nom_association}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Programme commun</h3><p>{{programme_commun}}</p><h3>Apports respectifs</h3><p>{{apports_respectifs}}</p><p>Signatures : ONG : _______________   Association : _______________</p></div>`,
  },
  {
    code: 'soc2_convention_transit_migrant',
    name: "Convention centre de transit pour migrants",
    category: 'association',
    price: 4500,
    priceMax: 12000,
    description: "Convention definissant les conditions d\"accueil et d\"orientation des migrants en situation de transit ou de vulnerabilite sur le territoire ivoirien.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 51,
    fieldsJson: F([
      { key: 'nom_centre', label: "Nom du centre de transit", type: 'text', required: true },
      { key: 'autorite_signataire', label: "Autorite publique co-signataire", type: 'text', required: true },
      { key: 'capacite', label: "Capacite maximale du centre", type: 'text', required: true },
      { key: 'services_fournis', label: "Services fournis aux migrants", type: 'textarea', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION – CENTRE DE TRANSIT POUR MIGRANTS</h1><p><strong>Centre :</strong> {{nom_centre}}</p><p><strong>Autorite publique :</strong> {{autorite_signataire}}</p><p><strong>Capacite :</strong> {{capacite}} personnes</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Services fournis</h3><p>{{services_fournis}}</p><p>La presente convention est conforme aux engagements internationaux de la Cote d"Ivoire en matiere de protection des migrants.</p></div>`,
  },
  {
    code: 'soc2_accord_soutien_psychologique',
    name: "Accord de soutien psychologique",
    category: 'association',
    price: 3000,
    priceMax: 8000,
    description: "Accord de prise en charge psychologique d\"une personne en souffrance par un psychologue ou une cellule d\"ecoute associative en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom du beneficiaire (confidentiel)", type: 'text', required: true },
      { key: 'nom_psychologue', label: "Nom du psychologue ou du referent", type: 'text', required: true },
      { key: 'motif_suivi', label: "Motif du suivi psychologique", type: 'textarea', required: true },
      { key: 'modalites_seances', label: "Frequence et modalites des seances", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut du suivi", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SOUTIEN PSYCHOLOGIQUE</h1><p>Document strictement confidentiel.</p><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Psychologue referent :</strong> {{nom_psychologue}}</p><p><strong>Debut du suivi :</strong> {{date_debut}}</p><p><strong>Modalites :</strong> {{modalites_seances}}</p><h3>Motif du suivi</h3><p>{{motif_suivi}}</p><p>Le beneficiaire donne son consentement eclaire pour la prise en charge.</p></div>`,
  },
  {
    code: 'soc2_contrat_travailleur_social',
    name: "Contrat de travailleur social",
    category: 'association',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de travail specifique a un travailleur social (assistant social, conseiller en economie sociale) employe dans une structure associative ou publique en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'nom_travailleur', label: "Nom et prenoms du travailleur social", type: 'text', required: true },
      { key: 'nom_structure', label: "Nom de la structure employeuse", type: 'text', required: true },
      { key: 'date_embauche', label: "Date d\"embauche", type: 'date', required: true },
      { key: 'salaire_brut', label: "Salaire brut mensuel (FCFA)", type: 'text', required: true },
      { key: 'missions', label: "Description des missions confiees", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE TRAVAILLEUR SOCIAL</h1><p>Entre <strong>{{nom_structure}}</strong> et <strong>{{nom_travailleur}}</strong>.</p><p><strong>Date d"embauche :</strong> {{date_embauche}}</p><p><strong>Salaire brut :</strong> {{salaire_brut}} FCFA</p><h3>Missions confiees</h3><p>{{missions}}</p><p>Signatures : Employeur : _______________   Salarie : _______________</p></div>`,
  },
  {
    code: 'soc2_rapport_visite_domicile',
    name: "Rapport de visite a domicile",
    category: 'association',
    price: 2000,
    priceMax: 5500,
    description: "Rapport standardise etabli par un travailleur social a l\"issue d\"une visite a domicile chez un beneficiaire ou une famille en situation de suivi social.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom du beneficiaire visite", type: 'text', required: true },
      { key: 'adresse_visite', label: "Adresse du domicile visite", type: 'text', required: true },
      { key: 'date_visite', label: "Date et heure de la visite", type: 'date', required: true },
      { key: 'observations', label: "Observations et constats de la visite", type: 'textarea', required: true },
      { key: 'suites_a_donner', label: "Suites a donner", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE VISITE A DOMICILE</h1><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Adresse :</strong> {{adresse_visite}}</p><p><strong>Date de visite :</strong> {{date_visite}}</p><h3>Observations</h3><p>{{observations}}</p><h3>Suites a donner</h3><p>{{suites_a_donner}}</p><p>Rapport etabli par : _______________</p></div>`,
  },
  {
    code: 'soc2_fiche_signalement_maltraitance',
    name: "Fiche de signalement de maltraitance",
    category: 'association',
    price: 2000,
    priceMax: 5000,
    description: "Fiche confidentielle de signalement d\"une situation de maltraitance (physique, psychologique, negligence) aupres des autorites competentes en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'nom_victime', label: "Nom presume de la victime (confidentiel)", type: 'text', required: true },
      { key: 'nature_maltraitance', label: "Nature de la maltraitance suspectee", type: 'textarea', required: true },
      { key: 'date_signalement', label: "Date du signalement", type: 'date', required: true },
      { key: 'nom_signalant', label: "Nom de l\"agent effectuant le signalement", type: 'text', required: true },
      { key: 'autorite_destinataire', label: "Autorite destinataire du signalement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE SIGNALEMENT – MALTRAITANCE</h1><p>DOCUMENT STRICTEMENT CONFIDENTIEL</p><p><strong>Victime presumee :</strong> {{nom_victime}}</p><p><strong>Date :</strong> {{date_signalement}}</p><p><strong>Agent signalant :</strong> {{nom_signalant}}</p><p><strong>Autorite destinataire :</strong> {{autorite_destinataire}}</p><h3>Nature de la maltraitance</h3><p>{{nature_maltraitance}}</p><p>Ce document est transmis sous pli confidentiel.</p></div>`,
  },
  {
    code: 'soc2_procedure_protection_enfance',
    name: "Procedure de protection de l\"enfance en danger",
    category: 'association',
    price: 3500,
    priceMax: 10000,
    description: "Document procedural etablissant les etapes a suivre pour la protection d\"un enfant en danger ou en risque de danger, conformement a la legislation ivoirienne.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l\"enfant concerne", type: 'text', required: true },
      { key: 'motif_danger', label: "Motif et nature du danger", type: 'textarea', required: true },
      { key: 'etapes_procedure', label: "Etapes de la procedure de protection", type: 'textarea', required: true },
      { key: 'autorites_impliquees', label: "Autorites et services impliques", type: 'text', required: true },
      { key: 'date_declenchement', label: "Date de declenchement de la procedure", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PROCEDURE DE PROTECTION DE L"ENFANCE EN DANGER</h1><p><strong>Enfant concerne :</strong> {{nom_enfant}}</p><p><strong>Date de declenchement :</strong> {{date_declenchement}}</p><p><strong>Autorites impliquees :</strong> {{autorites_impliquees}}</p><h3>Motif du danger</h3><p>{{motif_danger}}</p><h3>Etapes de la procedure</h3><p>{{etapes_procedure}}</p></div>`,
  },
  {
    code: 'soc2_convention_placement_familial',
    name: "Convention de placement familial",
    category: 'association',
    price: 4000,
    priceMax: 11000,
    description: "Convention encadrant le placement d\"un enfant au sein d\"une famille d\"accueil agree par les services sociaux ivoiriens, en remplacement de son milieu familial naturel.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l\"enfant place", type: 'text', required: true },
      { key: 'nom_famille_accueil', label: "Nom de la famille d\"accueil", type: 'text', required: true },
      { key: 'date_placement', label: "Date de debut du placement", type: 'date', required: true },
      { key: 'duree_placement', label: "Duree prevue du placement", type: 'text', required: true },
      { key: 'conditions_placement', label: "Conditions et obligations du placement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PLACEMENT FAMILIAL</h1><p><strong>Enfant place :</strong> {{nom_enfant}}</p><p><strong>Famille d"accueil :</strong> {{nom_famille_accueil}}</p><p><strong>Date de debut :</strong> {{date_placement}}</p><p><strong>Duree prevue :</strong> {{duree_placement}}</p><h3>Conditions et obligations</h3><p>{{conditions_placement}}</p><p>La famille d"accueil s"engage a assurer la protection et le bien-etre de l"enfant place.</p><p>Signatures : Services sociaux : _______________   Famille d"accueil : _______________</p></div>`,
  },
  {
    code: 'soc2_rapport_situation_enfant_place',
    name: "Rapport de situation d\"enfant place",
    category: 'association',
    price: 2500,
    priceMax: 7000,
    description: "Rapport periodique etabli par le service social responsable du suivi d\"un enfant place en famille d\"accueil ou en etablissement de protection.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom de l\"enfant", type: 'text', required: true },
      { key: 'lieu_placement', label: "Lieu de placement actuel", type: 'text', required: true },
      { key: 'periode_rapport', label: "Periode couverte par le rapport", type: 'text', required: true },
      { key: 'evolution_enfant', label: "Evolution de l\"enfant depuis le dernier rapport", type: 'textarea', required: true },
      { key: 'recommandations', label: "Recommandations du service social", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE SITUATION – ENFANT PLACE</h1><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Lieu de placement :</strong> {{lieu_placement}}</p><p><strong>Periode :</strong> {{periode_rapport}}</p><h3>Evolution</h3><p>{{evolution_enfant}}</p><h3>Recommandations</h3><p>{{recommandations}}</p><p>Rapport etabli par le service social le : _______________</p></div>`,
  },
  {
    code: 'soc2_accord_reinsertion_sociale',
    name: "Accord de reinsertion sociale",
    category: 'association',
    price: 3500,
    priceMax: 9500,
    description: "Accord d\"accompagnement a la reinsertion sociale d\"une personne fragilisee (ex-detenu, personne sortant de rue, ancien dependant) dans la societe ivoirienne.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom et prenoms du beneficiaire", type: 'text', required: true },
      { key: 'profil_beneficiaire', label: "Profil et parcours du beneficiaire", type: 'textarea', required: true },
      { key: 'actions_reinsertion', label: "Actions de reinsertion prevues", type: 'textarea', required: true },
      { key: 'nom_structure', label: "Structure de reinsertion responsable", type: 'text', required: true },
      { key: 'date_accord', label: "Date de signature de l\"accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE REINSERTION SOCIALE</h1><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Structure responsable :</strong> {{nom_structure}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Profil du beneficiaire</h3><p>{{profil_beneficiaire}}</p><h3>Actions de reinsertion</h3><p>{{actions_reinsertion}}</p><p>Le beneficiaire s"engage a participer activement au programme de reinsertion.</p></div>`,
  },
  {
    code: 'soc2_plan_prevention_recidive',
    name: "Plan de prevention de la recidive",
    category: 'association',
    price: 4000,
    priceMax: 11000,
    description: "Plan d\"action elabore par un service social ou de probation pour prevenir la recidive d\"une personne ayant fait l\"objet d\"une condamnation en Cote d\"Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom du beneficiaire (confidentiel)", type: 'text', required: true },
      { key: 'infractions_passees', label: "Nature des infractions passees", type: 'textarea', required: true },
      { key: 'facteurs_risque', label: "Facteurs de risque identifies", type: 'textarea', required: true },
      { key: 'mesures_prevention', label: "Mesures de prevention retenues", type: 'textarea', required: true },
      { key: 'date_plan', label: "Date d\"elaboration du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE PREVENTION DE LA RECIDIVE</h1><p>Document confidentiel.</p><p><strong>Beneficiaire :</strong> {{nom_beneficiaire}}</p><p><strong>Date :</strong> {{date_plan}}</p><h3>Infractions passees</h3><p>{{infractions_passees}}</p><h3>Facteurs de risque</h3><p>{{facteurs_risque}}</p><h3>Mesures de prevention</h3><p>{{mesures_prevention}}</p><p>Ce plan est soumis au controle de l"autorite judiciaire competente.</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 33a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
