import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ============================================================
  // HÔTELLERIE (20 templates)
  // ============================================================
  { code: 'hotel_contrat_reservation', name: "Contrat de réservation hôtel", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Contrat de réservation de chambre entre un hôtel et son client, précisant les dates de séjour, le type de chambre et les conditions tarifaires.", templateType: 'pdf', classe: 'B', active: true, popularity: 72,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'nomClient',label:"Nom complet du client",type:'text',required:true},{key:'dateArrivee',label:"Date d'arrivée",type:'date',required:true},{key:'dateDepart',label:"Date de départ",type:'date',required:true},{key:'typeChambre',label:"Type de chambre réservée",type:'text',required:true},{key:'montantTotal',label:"Montant total du séjour (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE RÉSERVATION HÔTELIÈRE</h1><p>Entre l'établissement hôtelier <strong>{{nomHotel}}</strong>, ci-après dénommé "l'Hôtel", et <strong>{{nomClient}}</strong>, ci-après dénommé "le Client", il est convenu ce qui suit.</p><h2>Article 1 — Objet</h2><p>L'Hôtel réserve au Client une chambre de type <strong>{{typeChambre}}</strong> pour la période allant du <strong>{{dateArrivee}}</strong> au <strong>{{dateDepart}}</strong>.</p><h2>Article 2 — Prix et modalités de paiement</h2><p>Le montant total du séjour est fixé à <strong>{{montantTotal}} FCFA</strong>, toutes taxes comprises. Un acompte de 30 % est exigible à la signature du présent contrat, le solde étant payable au plus tard le jour du départ.</p><h2>Article 3 — Annulation</h2><p>Toute annulation intervenant moins de 72 heures avant la date d'arrivée entraîne la retenue de l'acompte versé. En cas de non-présentation (no-show), la première nuitée est intégralement facturée.</p><h2>Article 4 — Droit applicable</h2><p>Le présent contrat est régi par le droit ivoirien et les Actes uniformes OHADA. Tout litige sera soumis aux juridictions compétentes du lieu de situation de l'Hôtel.</p><div class="signatures"><p>Fait en deux exemplaires originaux.</p><p>L'Hôtel : ______________________</p><p>Le Client : ______________________</p></div></div>` },

  { code: 'hotel_fiche_client', name: "Fiche client hôtel", category: 'commercial_financier', price: 1500, priceMax: 4500,
    description: "Fiche d'enregistrement des informations du client à son arrivée à l'hôtel, conforme aux obligations d'identification de la clientèle.", templateType: 'pdf', classe: 'C', active: true, popularity: 65,
    fieldsJson: F([{key:'nomClient',label:"Nom et prénoms du client",type:'text',required:true},{key:'nationalite',label:"Nationalité",type:'text',required:true},{key:'pieceIdentite',label:"Nature et numéro de la pièce d'identité",type:'text',required:true},{key:'dateArrivee',label:"Date d'arrivée",type:'date',required:true},{key:'numeroChambre',label:"Numéro de chambre attribuée",type:'text',required:true}]),
    body: `<div class="doc"><h1>FICHE CLIENT</h1><h2>Identification du client</h2><p>Nom et prénoms : <strong>{{nomClient}}</strong></p><p>Nationalité : <strong>{{nationalite}}</strong></p><p>Pièce d'identité présentée : <strong>{{pieceIdentite}}</strong></p><h2>Séjour</h2><p>Date d'arrivée : <strong>{{dateArrivee}}</strong></p><p>Chambre attribuée : <strong>{{numeroChambre}}</strong></p><h2>Mentions</h2><p>Le client certifie l'exactitude des informations portées sur la présente fiche. Ces informations sont recueillies conformément à la réglementation applicable aux établissements d'hébergement en Côte d'Ivoire et sont traitées de manière confidentielle.</p><div class="signatures"><p>Signature du client : ______________________</p><p>Visa de la réception : ______________________</p></div></div>` },

  { code: 'hotel_registre_police', name: "Registre de police hôtel", category: 'commercial_financier', price: 2000, priceMax: 6000,
    description: "Modèle de registre de police recensant les clients hébergés, tenu à la disposition des autorités conformément à la réglementation hôtelière.", templateType: 'pdf', classe: 'C', active: true, popularity: 58,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'établissement",type:'text',required:true},{key:'periode',label:"Période couverte par le registre",type:'text',required:true},{key:'responsable',label:"Responsable de la tenue du registre",type:'text',required:true},{key:'observations',label:"Observations générales",type:'textarea',required:false}]),
    body: `<div class="doc"><h1>REGISTRE DE POLICE</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Période couverte : <strong>{{periode}}</strong></p><p>Responsable de la tenue : <strong>{{responsable}}</strong></p><h2>Objet du registre</h2><p>Le présent registre recense, dans l'ordre chronologique des arrivées, l'identité complète de chaque client hébergé : nom, prénoms, date et lieu de naissance, nationalité, domicile, nature et numéro de la pièce d'identité, dates d'arrivée et de départ, numéro de chambre.</p><h2>Tenue et conservation</h2><p>Le registre est coté et paraphé. Il est tenu à jour quotidiennement et présenté à toute réquisition des autorités de police et de gendarmerie. Il est conservé pendant une durée minimale de trois ans.</p><h2>Observations</h2><p>{{observations}}</p><div class="signatures"><p>Le responsable de l'établissement : ______________________</p></div></div>` },

  { code: 'hotel_contrat_gerance', name: "Contrat de gérance hôtel", category: 'commercial_financier', price: 12000, priceMax: 36000,
    description: "Contrat de gérance confiant l'exploitation d'un établissement hôtelier à un gérant, avec définition des pouvoirs, de la rémunération et des obligations conformément au droit OHADA.", templateType: 'pdf', classe: 'A', active: true, popularity: 45,
    fieldsJson: F([{key:'proprietaire',label:"Nom du propriétaire de l'hôtel",type:'text',required:true},{key:'gerant',label:"Nom du gérant",type:'text',required:true},{key:'nomHotel',label:"Nom de l'établissement",type:'text',required:true},{key:'duree',label:"Durée de la gérance",type:'text',required:true},{key:'remuneration',label:"Rémunération du gérant",type:'text',required:true},{key:'dateDebut',label:"Date de prise d'effet",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE GÉRANCE D'ÉTABLISSEMENT HÔTELIER</h1><p>Entre <strong>{{proprietaire}}</strong>, propriétaire de l'établissement, d'une part, et <strong>{{gerant}}</strong>, ci-après dénommé "le Gérant", d'autre part.</p><h2>Article 1 — Objet</h2><p>Le propriétaire confie au Gérant, qui accepte, la gérance de l'établissement hôtelier <strong>{{nomHotel}}</strong>, conformément aux dispositions de l'Acte uniforme OHADA portant sur le droit commercial général relatives à la location-gérance.</p><h2>Article 2 — Durée</h2><p>Le présent contrat est conclu pour une durée de <strong>{{duree}}</strong>, à compter du <strong>{{dateDebut}}</strong>. Il pourra être renouvelé par accord écrit des parties.</p><h2>Article 3 — Rémunération</h2><p>Le Gérant percevra la rémunération suivante : <strong>{{remuneration}}</strong>. Les modalités de reddition des comptes sont fixées mensuellement.</p><h2>Article 4 — Obligations du Gérant</h2><p>Le Gérant exploite l'établissement en bon professionnel, respecte les normes hôtelières et sanitaires applicables, maintient le fonds en bon état et souscrit les assurances nécessaires. Il ne peut modifier la destination de l'établissement sans accord écrit du propriétaire.</p><h2>Article 5 — Publicité et immatriculation</h2><p>Le présent contrat fera l'objet des mesures de publicité prescrites par l'Acte uniforme OHADA, notamment la mention au Registre du Commerce et du Crédit Mobilier.</p><h2>Article 6 — Litiges</h2><p>Tout différend relatif au présent contrat sera soumis aux juridictions commerciales compétentes de Côte d'Ivoire, après tentative de règlement amiable.</p><div class="signatures"><p>Le Propriétaire : ______________________</p><p>Le Gérant : ______________________</p></div></div>` },

  { code: 'hotel_procedure_checkin', name: "Procédure check-in / check-out", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Procédure opérationnelle standardisée décrivant les étapes d'accueil à l'arrivée et de départ des clients de l'hôtel.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'heureCheckin',label:"Heure officielle de check-in",type:'text',required:true},{key:'heureCheckout',label:"Heure officielle de check-out",type:'text',required:true},{key:'responsable',label:"Responsable de la procédure",type:'text',required:true},{key:'dateMaj',label:"Date de mise à jour",type:'date',required:true}]),
    body: `<div class="doc"><h1>PROCÉDURE CHECK-IN / CHECK-OUT</h1><p>Établissement : <strong>{{nomHotel}}</strong> — Mise à jour du <strong>{{dateMaj}}</strong></p><p>Responsable : <strong>{{responsable}}</strong></p><h2>1. Check-in (à partir de {{heureCheckin}})</h2><p>Accueillir le client avec courtoisie ; vérifier la réservation dans le système ; contrôler la pièce d'identité et renseigner la fiche client ; encaisser l'acompte ou la garantie ; remettre la clé ou la carte magnétique ; présenter les services de l'établissement et accompagner le client vers sa chambre.</p><h2>2. Check-out (au plus tard à {{heureCheckout}})</h2><p>Vérifier l'état de la chambre auprès des étages ; éditer la facture détaillée et la faire valider par le client ; encaisser le solde ; récupérer la clé ; proposer un questionnaire de satisfaction ; mettre à jour le planning des chambres.</p><h2>3. Cas particuliers</h2><p>Arrivée anticipée ou départ tardif : appliquer la grille tarifaire en vigueur après vérification des disponibilités. Litige de facturation : en référer immédiatement au chef de réception.</p><div class="signatures"><p>Visa de la direction : ______________________</p></div></div>` },

  { code: 'hotel_grille_tarifaire', name: "Grille tarifaire des chambres", category: 'commercial_financier', price: 2500, priceMax: 7500,
    description: "Document officiel de tarification des chambres et prestations de l'hôtel, affichable et opposable à la clientèle.", templateType: 'pdf', classe: 'C', active: true, popularity: 55,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'saison',label:"Saison ou période tarifaire",type:'text',required:true},{key:'detailTarifs',label:"Détail des tarifs par catégorie de chambre",type:'textarea',required:true},{key:'dateApplication',label:"Date d'application",type:'date',required:true}]),
    body: `<div class="doc"><h1>GRILLE TARIFAIRE DES CHAMBRES</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Période tarifaire : <strong>{{saison}}</strong> — Applicable à compter du <strong>{{dateApplication}}</strong></p><h2>Tarifs par catégorie</h2><p>{{detailTarifs}}</p><h2>Conditions générales</h2><p>Les tarifs sont exprimés en francs CFA, toutes taxes comprises, par chambre et par nuitée. Le petit-déjeuner, les consommations du minibar et les prestations annexes sont facturés en supplément sauf mention contraire. La direction se réserve le droit de modifier la présente grille, les réservations confirmées demeurant au tarif convenu.</p><div class="signatures"><p>La Direction : ______________________</p></div></div>` },

  { code: 'hotel_contrat_evenementiel', name: "Contrat événementiel hôtel", category: 'commercial_financier', price: 6000, priceMax: 18000,
    description: "Contrat d'organisation d'un événement (mariage, banquet, cocktail, réception) au sein d'un hôtel, avec prestations, effectifs et conditions financières.", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'nomClient',label:"Nom du client organisateur",type:'text',required:true},{key:'typeEvenement',label:"Type d'événement",type:'text',required:true},{key:'dateEvenement',label:"Date de l'événement",type:'date',required:true},{key:'nombreInvites',label:"Nombre d'invités prévu",type:'text',required:true},{key:'montant',label:"Montant total de la prestation (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE PRESTATION ÉVÉNEMENTIELLE</h1><p>Entre l'hôtel <strong>{{nomHotel}}</strong> et <strong>{{nomClient}}</strong>, ci-après dénommé "l'Organisateur".</p><h2>Article 1 — Objet</h2><p>L'Hôtel met à la disposition de l'Organisateur ses espaces et services pour l'organisation de l'événement suivant : <strong>{{typeEvenement}}</strong>, prévu le <strong>{{dateEvenement}}</strong>, pour un effectif estimé à <strong>{{nombreInvites}}</strong> invités.</p><h2>Article 2 — Prestations et prix</h2><p>Le montant total des prestations est arrêté à <strong>{{montant}} FCFA</strong> TTC. Un acompte de 50 % est versé à la signature, le solde au plus tard 48 heures avant l'événement. Tout dépassement d'effectif ou prestation supplémentaire fera l'objet d'une facturation complémentaire.</p><h2>Article 3 — Annulation</h2><p>En cas d'annulation par l'Organisateur moins de 15 jours avant la date prévue, l'acompte reste acquis à l'Hôtel. En cas de force majeure dûment justifiée, les parties conviennent d'un report sans pénalité.</p><h2>Article 4 — Responsabilité</h2><p>L'Organisateur répond des dommages causés par ses invités aux installations. L'Hôtel décline toute responsabilité pour les objets de valeur non déposés au coffre.</p><div class="signatures"><p>Pour l'Hôtel : ______________________</p><p>L'Organisateur : ______________________</p></div></div>` },

  { code: 'hotel_fiche_maintenance', name: "Fiche d'intervention maintenance", category: 'commercial_financier', price: 1500, priceMax: 4500,
    description: "Fiche de suivi des interventions techniques et de maintenance dans les chambres et parties communes de l'hôtel.", templateType: 'pdf', classe: 'C', active: true, popularity: 50,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'lieuIntervention',label:"Lieu de l'intervention (chambre, étage, local)",type:'text',required:true},{key:'descriptionPanne',label:"Description de la panne ou de l'anomalie",type:'textarea',required:true},{key:'technicien',label:"Nom du technicien intervenant",type:'text',required:true},{key:'dateIntervention',label:"Date de l'intervention",type:'date',required:true}]),
    body: `<div class="doc"><h1>FICHE D'INTERVENTION MAINTENANCE</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Lieu : <strong>{{lieuIntervention}}</strong> — Date : <strong>{{dateIntervention}}</strong></p><h2>Anomalie signalée</h2><p>{{descriptionPanne}}</p><h2>Intervention</h2><p>Technicien : <strong>{{technicien}}</strong></p><p>Travaux réalisés : ____________________________________________</p><p>Pièces remplacées : ____________________________________________</p><h2>Clôture</h2><p>État après intervention : conforme / à surveiller / intervention complémentaire requise (rayer les mentions inutiles).</p><div class="signatures"><p>Le technicien : ______________________</p><p>Le responsable technique : ______________________</p></div></div>` },

  { code: 'hotel_plan_nettoyage', name: "Plan de nettoyage des étages", category: 'commercial_financier', price: 2000, priceMax: 6000,
    description: "Plan de nettoyage et d'entretien des chambres et parties communes, organisant le travail du service des étages de l'hôtel.", templateType: 'pdf', classe: 'C', active: true, popularity: 48,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'etageZone',label:"Étage ou zone concernée",type:'text',required:true},{key:'tachesQuotidiennes',label:"Détail des tâches quotidiennes et périodiques",type:'textarea',required:true},{key:'gouvernante',label:"Nom de la gouvernante responsable",type:'text',required:true},{key:'periode',label:"Période d'application",type:'text',required:true}]),
    body: `<div class="doc"><h1>PLAN DE NETTOYAGE DES ÉTAGES</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Zone concernée : <strong>{{etageZone}}</strong> — Période : <strong>{{periode}}</strong></p><p>Gouvernante responsable : <strong>{{gouvernante}}</strong></p><h2>Tâches programmées</h2><p>{{tachesQuotidiennes}}</p><h2>Consignes générales</h2><p>Le nettoyage des chambres en recouche est effectué chaque jour avant 14 heures. Les chambres à blanc font l'objet d'un contrôle systématique de la gouvernante avant remise à la réception. Les produits d'entretien sont utilisés conformément aux fiches techniques et stockés dans les offices fermés à clé. Toute anomalie technique constatée est signalée au service maintenance par fiche d'intervention.</p><div class="signatures"><p>La gouvernante : ______________________</p><p>La direction : ______________________</p></div></div>` },

  { code: 'hotel_rapport_occupation', name: "Rapport d'occupation mensuel", category: 'commercial_financier', price: 3500, priceMax: 10500,
    description: "Rapport mensuel d'activité présentant le taux d'occupation, le prix moyen chambre et le revenu hébergement de l'hôtel.", templateType: 'pdf', classe: 'B', active: true, popularity: 57,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'moisConcerne',label:"Mois concerné",type:'text',required:true},{key:'tauxOccupation',label:"Taux d'occupation du mois (%)",type:'text',required:true},{key:'revenuHebergement',label:"Revenu hébergement du mois (FCFA)",type:'text',required:true},{key:'commentaires',label:"Analyse et commentaires",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>RAPPORT D'OCCUPATION MENSUEL</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Mois concerné : <strong>{{moisConcerne}}</strong></p><h2>Indicateurs clés</h2><p>Taux d'occupation : <strong>{{tauxOccupation}} %</strong></p><p>Revenu hébergement : <strong>{{revenuHebergement}} FCFA</strong></p><p>Prix moyen chambre et RevPAR : à reporter depuis le système de gestion hôtelière.</p><h2>Analyse de la période</h2><p>{{commentaires}}</p><h2>Recommandations</h2><p>Actions commerciales et tarifaires proposées pour le mois suivant : ____________________________________________</p><div class="signatures"><p>Établi par la direction de l'hébergement : ______________________</p><p>Visa de la direction générale : ______________________</p></div></div>` },

  { code: 'hotel_contrat_blanchisserie', name: "Contrat de blanchisserie hôtel", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Contrat de prestation de blanchisserie entre un hôtel et un prestataire externe pour le traitement du linge d'hébergement et de restauration.", templateType: 'pdf', classe: 'B', active: true, popularity: 44,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'prestataire',label:"Nom du prestataire de blanchisserie",type:'text',required:true},{key:'prestations',label:"Détail des prestations et fréquences",type:'textarea',required:true},{key:'conditionsTarifaires',label:"Conditions tarifaires convenues",type:'text',required:true},{key:'dateDebut',label:"Date de début du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE PRESTATION DE BLANCHISSERIE</h1><p>Entre l'hôtel <strong>{{nomHotel}}</strong>, ci-après "le Client", et <strong>{{prestataire}}</strong>, ci-après "le Prestataire".</p><h2>Article 1 — Objet</h2><p>Le Prestataire assure le ramassage, le traitement et la livraison du linge de l'hôtel (linge de lit, linge de toilette, linge de table et tenues du personnel) selon le détail suivant :</p><p>{{prestations}}</p><h2>Article 2 — Conditions financières</h2><p>Les prestations sont facturées selon les conditions suivantes : <strong>{{conditionsTarifaires}}</strong>. Les factures sont payables à 30 jours fin de mois.</p><h2>Article 3 — Qualité et délais</h2><p>Le Prestataire garantit un traitement conforme aux normes d'hygiène applicables, la traçabilité des lots et le respect des délais convenus. Tout article détérioré ou manquant est remboursé à sa valeur de remplacement.</p><h2>Article 4 — Durée et résiliation</h2><p>Le contrat prend effet le <strong>{{dateDebut}}</strong> pour une durée d'un an renouvelable par tacite reconduction, chaque partie pouvant y mettre fin avec un préavis de deux mois.</p><div class="signatures"><p>Pour le Client : ______________________</p><p>Pour le Prestataire : ______________________</p></div></div>` },

  { code: 'hotel_charte_qualite', name: "Charte qualité hôtel", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Charte formalisant les engagements de qualité de service de l'hôtel envers sa clientèle et ses partenaires.", templateType: 'pdf', classe: 'B', active: true, popularity: 46,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'engagements',label:"Liste des engagements qualité",type:'textarea',required:true},{key:'directeur',label:"Nom du directeur de l'établissement",type:'text',required:true},{key:'dateAdoption',label:"Date d'adoption de la charte",type:'date',required:true}]),
    body: `<div class="doc"><h1>CHARTE QUALITÉ</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Adoptée le <strong>{{dateAdoption}}</strong> sous l'autorité de <strong>{{directeur}}</strong>, directeur de l'établissement.</p><h2>Notre engagement</h2><p>L'ensemble du personnel de l'hôtel s'engage à offrir à chaque client un accueil chaleureux, des prestations conformes aux standards annoncés et un traitement diligent de toute réclamation.</p><h2>Engagements détaillés</h2><p>{{engagements}}</p><h2>Suivi de la qualité</h2><p>La satisfaction de la clientèle est mesurée en continu par des questionnaires et le suivi des avis. Les résultats sont examinés chaque mois en réunion de direction et donnent lieu à des actions correctives dont la mise en œuvre est vérifiée.</p><div class="signatures"><p>Le Directeur : ______________________</p></div></div>` },

  { code: 'hotel_fiche_reclamation', name: "Fiche de réclamation client", category: 'commercial_financier', price: 1200, priceMax: 3600,
    description: "Fiche d'enregistrement et de traitement des réclamations formulées par les clients de l'hôtel.", templateType: 'pdf', classe: 'C', active: true, popularity: 52,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'nomClient',label:"Nom du client",type:'text',required:true},{key:'numeroChambre',label:"Numéro de chambre",type:'text',required:false},{key:'objetReclamation',label:"Objet détaillé de la réclamation",type:'textarea',required:true},{key:'dateReclamation',label:"Date de la réclamation",type:'date',required:true},{key:'suiteDonnee',label:"Suite donnée ou geste commercial",type:'text',required:false}]),
    body: `<div class="doc"><h1>FICHE DE RÉCLAMATION CLIENT</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Client : <strong>{{nomClient}}</strong> — Chambre : <strong>{{numeroChambre}}</strong></p><p>Date de la réclamation : <strong>{{dateReclamation}}</strong></p><h2>Objet de la réclamation</h2><p>{{objetReclamation}}</p><h2>Traitement</h2><p>Service concerné : ______________________</p><p>Suite donnée : <strong>{{suiteDonnee}}</strong></p><p>Délai de réponse au client : 48 heures maximum. La présente fiche est transmise au chef de service concerné puis archivée par la direction après clôture.</p><div class="signatures"><p>Agent ayant reçu la réclamation : ______________________</p><p>Visa de la direction : ______________________</p></div></div>` },

  { code: 'hotel_contrat_agence_voyage', name: "Contrat hôtel - agence de voyage", category: 'commercial_financier', price: 6000, priceMax: 18000,
    description: "Contrat de partenariat commercial entre un hôtel et une agence de voyage, définissant allotement, tarifs contractés et commissions.", templateType: 'pdf', classe: 'B', active: true, popularity: 49,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'nomAgence',label:"Nom de l'agence de voyage",type:'text',required:true},{key:'tauxCommission',label:"Taux de commission de l'agence (%)",type:'text',required:true},{key:'allotement',label:"Allotement de chambres consenti",type:'text',required:true},{key:'duree',label:"Durée du contrat",type:'text',required:true},{key:'dateSignature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE PARTENARIAT HÔTEL - AGENCE DE VOYAGE</h1><p>Entre l'hôtel <strong>{{nomHotel}}</strong> et l'agence <strong>{{nomAgence}}</strong>, il est conclu le présent contrat en date du <strong>{{dateSignature}}</strong>.</p><h2>Article 1 — Objet</h2><p>L'Hôtel consent à l'Agence un allotement de <strong>{{allotement}}</strong>, que l'Agence commercialise auprès de sa clientèle aux tarifs contractés figurant en annexe.</p><h2>Article 2 — Commission</h2><p>L'Agence perçoit une commission de <strong>{{tauxCommission}} %</strong> sur le montant hors taxes des nuitées effectivement consommées. Le règlement des commissions intervient mensuellement sur présentation de facture.</p><h2>Article 3 — Rétrocession et délais de relâche</h2><p>Les chambres non confirmées sont rétrocédées à l'Hôtel selon les délais de relâche convenus en annexe. Passé ces délais, les annulations sont soumises aux conditions générales de l'Hôtel.</p><h2>Article 4 — Durée</h2><p>Le présent contrat est conclu pour une durée de <strong>{{duree}}</strong>, renouvelable par accord écrit. Il est régi par le droit ivoirien et les Actes uniformes OHADA.</p><div class="signatures"><p>Pour l'Hôtel : ______________________</p><p>Pour l'Agence : ______________________</p></div></div>` },

  { code: 'hotel_securite_incendie', name: "Procédure sécurité incendie hôtel", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Procédure de prévention et de gestion du risque incendie dans un hôtel : consignes, alarme, évacuation et points de rassemblement.", templateType: 'pdf', classe: 'B', active: true, popularity: 47,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'consignes',label:"Consignes détaillées et points de rassemblement",type:'textarea',required:true},{key:'responsableSecurite',label:"Nom du responsable sécurité",type:'text',required:true},{key:'dateMaj',label:"Date de mise à jour",type:'date',required:true}]),
    body: `<div class="doc"><h1>PROCÉDURE SÉCURITÉ INCENDIE</h1><p>Établissement : <strong>{{nomHotel}}</strong> — Mise à jour du <strong>{{dateMaj}}</strong></p><p>Responsable sécurité : <strong>{{responsableSecurite}}</strong></p><h2>1. Prévention</h2><p>Vérification périodique des extincteurs, des blocs autonomes d'éclairage de sécurité, du système d'alarme et du désenfumage. Maintien du dégagement permanent des issues de secours. Affichage des plans d'évacuation à chaque étage et dans chaque chambre.</p><h2>2. Conduite à tenir en cas d'incendie</h2><p>Donner l'alarme ; alerter les sapeurs-pompiers (180 / 112) ; attaquer le feu naissant avec les moyens de première intervention sans prise de risque ; procéder à l'évacuation des clients étage par étage, en commençant par le niveau sinistré ; ne jamais utiliser les ascenseurs.</p><h2>3. Consignes propres à l'établissement</h2><p>{{consignes}}</p><h2>4. Exercices</h2><p>Un exercice d'évacuation est organisé au moins deux fois par an et consigné au registre de sécurité.</p><div class="signatures"><p>Le responsable sécurité : ______________________</p><p>La direction : ______________________</p></div></div>` },

  { code: 'hotel_rapport_nuit', name: "Rapport de nuit (night audit)", category: 'commercial_financier', price: 2000, priceMax: 6000,
    description: "Rapport de clôture journalière établi par l'auditeur de nuit : recettes, occupation, incidents et contrôles de caisse.", templateType: 'pdf', classe: 'C', active: true, popularity: 43,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'dateNuit',label:"Date de la nuit auditée",type:'date',required:true},{key:'auditeur',label:"Nom de l'auditeur de nuit",type:'text',required:true},{key:'recettesJour',label:"Total des recettes de la journée (FCFA)",type:'text',required:true},{key:'observations',label:"Incidents et observations de la nuit",type:'textarea',required:false}]),
    body: `<div class="doc"><h1>RAPPORT DE NUIT — NIGHT AUDIT</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Nuit du : <strong>{{dateNuit}}</strong> — Auditeur : <strong>{{auditeur}}</strong></p><h2>Clôture de la journée</h2><p>Total des recettes : <strong>{{recettesJour}} FCFA</strong></p><p>Chambres occupées : ________ — Arrivées : ________ — Départs : ________ — No-show : ________</p><h2>Contrôles effectués</h2><p>Rapprochement des caisses, vérification des débiteurs divers, contrôle des annulations et des gratuités, édition des rapports de gestion, sauvegarde du système, passage de la date.</p><h2>Incidents et observations</h2><p>{{observations}}</p><div class="signatures"><p>L'auditeur de nuit : ______________________</p><p>Le chef de réception : ______________________</p></div></div>` },

  { code: 'hotel_fiche_receptionniste', name: "Fiche de fonction réceptionniste", category: 'commercial_financier', price: 2500, priceMax: 7500,
    description: "Fiche de poste du réceptionniste d'hôtel : missions, responsabilités, rattachement hiérarchique et compétences requises.", templateType: 'pdf', classe: 'C', active: true, popularity: 51,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'titulaire',label:"Nom du titulaire du poste",type:'text',required:true},{key:'missions',label:"Missions et responsabilités détaillées",type:'textarea',required:true},{key:'superieur',label:"Supérieur hiérarchique direct",type:'text',required:true},{key:'dateEffet',label:"Date de prise d'effet",type:'date',required:true}]),
    body: `<div class="doc"><h1>FICHE DE FONCTION — RÉCEPTIONNISTE</h1><p>Établissement : <strong>{{nomHotel}}</strong></p><p>Titulaire : <strong>{{titulaire}}</strong> — Prise d'effet : <strong>{{dateEffet}}</strong></p><p>Rattachement hiérarchique : <strong>{{superieur}}</strong></p><h2>Finalité du poste</h2><p>Assurer l'accueil physique et téléphonique de la clientèle, la gestion des réservations, les opérations de check-in et de check-out ainsi que la facturation, dans le respect des standards de qualité de l'établissement.</p><h2>Missions et responsabilités</h2><p>{{missions}}</p><h2>Compétences requises</h2><p>Maîtrise du logiciel de gestion hôtelière, sens de l'accueil, rigueur dans la tenue de caisse, pratique du français et d'une langue étrangère appréciée, discrétion professionnelle.</p><div class="signatures"><p>Le titulaire : ______________________</p><p>La direction : ______________________</p></div></div>` },

  { code: 'hotel_contrat_spa', name: "Contrat spa / bien-être", category: 'commercial_financier', price: 5000, priceMax: 15000,
    description: "Contrat de partenariat entre un hôtel et un prestataire de services de spa et de bien-être exploitant un espace au sein de l'établissement.", templateType: 'pdf', classe: 'B', active: true, popularity: 40,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'prestataire',label:"Nom du prestataire spa / bien-être",type:'text',required:true},{key:'services',label:"Services proposés (massages, soins, hammam...)",type:'textarea',required:true},{key:'partageRevenus',label:"Modalités de partage des revenus",type:'text',required:true},{key:'duree',label:"Durée du contrat",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE PARTENARIAT SPA / BIEN-ÊTRE</h1><p>Entre l'hôtel <strong>{{nomHotel}}</strong> et <strong>{{prestataire}}</strong>, ci-après "le Prestataire".</p><h2>Article 1 — Objet</h2><p>L'Hôtel met à la disposition du Prestataire un espace aménagé au sein de l'établissement pour l'exploitation de services de bien-être au profit de la clientèle de l'hôtel et de la clientèle extérieure.</p><h2>Article 2 — Services proposés</h2><p>{{services}}</p><h2>Article 3 — Conditions financières</h2><p>Les revenus sont répartis selon les modalités suivantes : <strong>{{partageRevenus}}</strong>. Un état récapitulatif est établi chaque fin de mois et le règlement intervient sous quinzaine.</p><h2>Article 4 — Obligations du Prestataire</h2><p>Le Prestataire emploie un personnel qualifié, respecte les normes d'hygiène et de sécurité applicables, souscrit une assurance responsabilité civile professionnelle et maintient un niveau de service conforme à l'image de l'Hôtel.</p><h2>Article 5 — Durée</h2><p>Le contrat est conclu pour une durée de <strong>{{duree}}</strong>, renouvelable par accord écrit des parties. Il est régi par le droit ivoirien.</p><div class="signatures"><p>Pour l'Hôtel : ______________________</p><p>Pour le Prestataire : ______________________</p></div></div>` },

  { code: 'hotel_convention_seminaire', name: "Convention séminaire entreprise", category: 'commercial_financier', price: 6000, priceMax: 18000,
    description: "Convention entre un hôtel et une entreprise pour l'organisation d'un séminaire : salles, hébergement, restauration et pauses.", templateType: 'pdf', classe: 'B', active: true, popularity: 54,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'entreprise',label:"Nom de l'entreprise cliente",type:'text',required:true},{key:'datesSeminaire',label:"Dates du séminaire",type:'text',required:true},{key:'nombreParticipants',label:"Nombre de participants",type:'text',required:true},{key:'montant',label:"Montant total de la convention (FCFA)",type:'text',required:true},{key:'modalites',label:"Détail des prestations (salles, pauses, repas, hébergement)",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE SÉMINAIRE</h1><p>Entre l'hôtel <strong>{{nomHotel}}</strong> et l'entreprise <strong>{{entreprise}}</strong>.</p><h2>Article 1 — Objet</h2><p>L'Hôtel accueille le séminaire de l'entreprise aux dates suivantes : <strong>{{datesSeminaire}}</strong>, pour un effectif de <strong>{{nombreParticipants}}</strong> participants.</p><h2>Article 2 — Prestations convenues</h2><p>{{modalites}}</p><h2>Article 3 — Conditions financières</h2><p>Le montant total de la convention est arrêté à <strong>{{montant}} FCFA</strong> TTC. Un acompte de 40 % est versé à la signature, le solde à réception de la facture définitive. Le nombre de participants est confirmé au plus tard 72 heures avant le début du séminaire ; ce nombre sert de base minimale de facturation.</p><h2>Article 4 — Annulation</h2><p>Toute annulation totale intervenant moins de 10 jours avant la date prévue entraîne la facturation de 50 % du montant de la convention.</p><div class="signatures"><p>Pour l'Hôtel : ______________________</p><p>Pour l'Entreprise : ______________________</p></div></div>` },

  { code: 'hotel_contrat_fournisseur', name: "Contrat fournisseur hôtel", category: 'commercial_financier', price: 5000, priceMax: 15000,
    description: "Contrat cadre d'approvisionnement entre un hôtel et un fournisseur de produits ou de services, avec conditions de livraison et de règlement.", templateType: 'pdf', classe: 'B', active: true, popularity: 42,
    fieldsJson: F([{key:'nomHotel',label:"Nom de l'hôtel",type:'text',required:true},{key:'fournisseur',label:"Nom du fournisseur",type:'text',required:true},{key:'produits',label:"Produits ou services fournis",type:'textarea',required:true},{key:'conditionsReglement',label:"Conditions de règlement",type:'text',required:true},{key:'dateDebut',label:"Date de début du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT CADRE FOURNISSEUR</h1><p>Entre l'hôtel <strong>{{nomHotel}}</strong>, ci-après "le Client", et <strong>{{fournisseur}}</strong>, ci-après "le Fournisseur".</p><h2>Article 1 — Objet</h2><p>Le Fournisseur s'engage à approvisionner le Client dans les conditions du présent contrat pour les produits et services suivants :</p><p>{{produits}}</p><h2>Article 2 — Commandes et livraisons</h2><p>Les commandes sont passées par bon de commande signé du service des achats. Les livraisons sont effectuées aux jours et heures convenus et font l'objet d'un contrôle quantitatif et qualitatif contradictoire à réception. Toute non-conformité est signalée sous 24 heures et donne lieu à remplacement ou avoir.</p><h2>Article 3 — Prix et règlement</h2><p>Les prix sont ceux du barème annexé au présent contrat. Conditions de règlement : <strong>{{conditionsReglement}}</strong>.</p><h2>Article 4 — Durée</h2><p>Le contrat prend effet le <strong>{{dateDebut}}</strong> pour une durée d'un an renouvelable. Il est régi par le droit ivoirien et l'Acte uniforme OHADA portant sur le droit commercial général.</p><div class="signatures"><p>Pour le Client : ______________________</p><p>Pour le Fournisseur : ______________________</p></div></div>` },

  // ============================================================
  // RESTAURATION (15 templates)
  // ============================================================
  { code: 'rest_plan_haccp', name: "Plan HACCP restaurant", category: 'commercial_financier', price: 8000, priceMax: 24000,
    description: "Plan de maîtrise sanitaire fondé sur la méthode HACCP pour un restaurant : analyse des dangers, points critiques et mesures de surveillance.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'responsableQualite',label:"Responsable qualité / hygiène",type:'text',required:true},{key:'dangersIdentifies',label:"Dangers identifiés (biologiques, chimiques, physiques)",type:'textarea',required:true},{key:'mesuresMaitrise',label:"Points critiques et mesures de maîtrise",type:'textarea',required:true},{key:'dateMaj',label:"Date de mise à jour du plan",type:'date',required:true}]),
    body: `<div class="doc"><h1>PLAN HACCP</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Mise à jour du <strong>{{dateMaj}}</strong></p><p>Responsable qualité : <strong>{{responsableQualite}}</strong></p><h2>1. Champ d'application</h2><p>Le présent plan couvre l'ensemble des étapes de production : réception des marchandises, stockage, préparation froide et chaude, refroidissement, remise en température, service et gestion des invendus.</p><h2>2. Analyse des dangers</h2><p>{{dangersIdentifies}}</p><h2>3. Points critiques et mesures de maîtrise</h2><p>{{mesuresMaitrise}}</p><h2>4. Surveillance et enregistrements</h2><p>Les températures des enceintes froides sont relevées deux fois par jour, les températures de cuisson et de refroidissement sont contrôlées et enregistrées. Les fiches de non-conformité déclenchent les actions correctives définies au présent plan.</p><h2>5. Vérification</h2><p>Le plan est vérifié annuellement et à chaque modification significative des procédés, en cohérence avec la réglementation ivoirienne applicable à la restauration commerciale.</p><div class="signatures"><p>Le responsable qualité : ______________________</p><p>La direction : ______________________</p></div></div>` },

  { code: 'rest_fiche_technique_plat', name: "Fiche technique de plat", category: 'commercial_financier', price: 2000, priceMax: 6000,
    description: "Fiche technique de production culinaire : ingrédients, grammages, étapes de préparation et coût portion du plat.", templateType: 'pdf', classe: 'C', active: true, popularity: 66,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'nomPlat',label:"Nom du plat",type:'text',required:true},{key:'ingredients',label:"Ingrédients et grammages pour le nombre de portions",type:'textarea',required:true},{key:'preparation',label:"Étapes de préparation",type:'textarea',required:true},{key:'coutPortion',label:"Coût matière par portion (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>FICHE TECHNIQUE DE PLAT</h1><p>Établissement : <strong>{{nomRestaurant}}</strong></p><h2>{{nomPlat}}</h2><h3>Ingrédients et grammages</h3><p>{{ingredients}}</p><h3>Progression de la recette</h3><p>{{preparation}}</p><h3>Données de gestion</h3><p>Coût matière par portion : <strong>{{coutPortion}} FCFA</strong></p><p>Prix de vente conseillé : appliquer le coefficient multiplicateur retenu par l'établissement (généralement entre 3 et 4).</p><h3>Dressage et service</h3><p>Respecter la présentation photographiée en annexe, contrôler la température de service et la conformité des grammages avant l'envoi.</p><div class="signatures"><p>Le chef de cuisine : ______________________</p></div></div>` },

  { code: 'rest_cout_matiere', name: "Calcul de coût matière", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Document de calcul et de suivi du ratio coût matière du restaurant sur une période donnée : achats, variations de stock et ventes.", templateType: 'pdf', classe: 'B', active: true, popularity: 53,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'periode',label:"Période analysée",type:'text',required:true},{key:'totalAchats',label:"Total des achats consommés (FCFA)",type:'text',required:true},{key:'chiffreAffaires',label:"Chiffre d'affaires de la période (FCFA)",type:'text',required:true},{key:'ratioCible',label:"Ratio coût matière cible (%)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CALCUL DE COÛT MATIÈRE</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Période : <strong>{{periode}}</strong></p><h2>Données de la période</h2><p>Achats consommés (achats + stock initial - stock final) : <strong>{{totalAchats}} FCFA</strong></p><p>Chiffre d'affaires : <strong>{{chiffreAffaires}} FCFA</strong></p><h2>Calcul du ratio</h2><p>Ratio coût matière = achats consommés / chiffre d'affaires x 100 = ________ %</p><p>Ratio cible de l'établissement : <strong>{{ratioCible}} %</strong></p><h2>Analyse des écarts</h2><p>Tout écart supérieur à deux points par rapport à la cible fait l'objet d'une analyse : dérive des grammages, pertes et casse, vols, erreurs d'inventaire, hausse des prix fournisseurs, offerts non enregistrés.</p><h2>Actions correctives</h2><p>____________________________________________</p><div class="signatures"><p>Le contrôleur des coûts : ______________________</p><p>La direction : ______________________</p></div></div>` },

  { code: 'rest_menu_engineering', name: "Analyse menu engineering", category: 'commercial_financier', price: 5000, priceMax: 15000,
    description: "Analyse de la rentabilité et de la popularité des plats de la carte selon la méthode du menu engineering, avec recommandations d'optimisation.", templateType: 'pdf', classe: 'B', active: true, popularity: 41,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'periode',label:"Période analysée",type:'text',required:true},{key:'analysePlats',label:"Classement des plats (stars, plow horses, puzzles, dogs)",type:'textarea',required:true},{key:'recommandations',label:"Recommandations d'optimisation de la carte",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>ANALYSE MENU ENGINEERING</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Période : <strong>{{periode}}</strong></p><h2>Méthodologie</h2><p>Chaque plat de la carte est positionné selon deux axes : sa popularité (part des ventes) et sa marge brute unitaire. Quatre catégories en résultent : les stars (populaires et rentables), les plow horses (populaires, peu rentables), les puzzles (rentables, peu vendus) et les dogs (ni populaires ni rentables).</p><h2>Classement des plats</h2><p>{{analysePlats}}</p><h2>Recommandations</h2><p>{{recommandations}}</p><h2>Suivi</h2><p>Les modifications de carte issues de la présente analyse sont mises en œuvre puis réévaluées à la prochaine période pour mesurer leur impact sur la marge globale.</p><div class="signatures"><p>Établi par : ______________________</p><p>Validé par la direction : ______________________</p></div></div>` },

  { code: 'rest_contrat_traiteur', name: "Contrat traiteur", category: 'commercial_financier', price: 5000, priceMax: 15000,
    description: "Contrat de prestation traiteur pour un événement : menus, effectifs, logistique, personnel de service et conditions financières.", templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([{key:'nomTraiteur',label:"Nom du traiteur",type:'text',required:true},{key:'nomClient',label:"Nom du client",type:'text',required:true},{key:'evenement',label:"Nature et lieu de l'événement",type:'text',required:true},{key:'dateEvenement',label:"Date de l'événement",type:'date',required:true},{key:'nombreConvives',label:"Nombre de convives",type:'text',required:true},{key:'montant',label:"Montant total de la prestation (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE PRESTATION TRAITEUR</h1><p>Entre <strong>{{nomTraiteur}}</strong>, ci-après "le Traiteur", et <strong>{{nomClient}}</strong>, ci-après "le Client".</p><h2>Article 1 — Objet</h2><p>Le Traiteur assure la prestation de restauration pour l'événement suivant : <strong>{{evenement}}</strong>, le <strong>{{dateEvenement}}</strong>, pour <strong>{{nombreConvives}}</strong> convives. Le détail des menus figure en annexe.</p><h2>Article 2 — Prix et règlement</h2><p>Le montant total est fixé à <strong>{{montant}} FCFA</strong> TTC. Acompte de 50 % à la commande, solde au plus tard le jour de la prestation. Le nombre définitif de convives, confirmé 72 heures avant l'événement, constitue la base minimale de facturation.</p><h2>Article 3 — Obligations du Traiteur</h2><p>Le Traiteur respecte les règles d'hygiène applicables à la restauration, assure la chaîne du froid jusqu'au lieu de la prestation et fournit le personnel de service convenu. Il est titulaire d'une assurance responsabilité civile professionnelle.</p><h2>Article 4 — Annulation</h2><p>En cas d'annulation par le Client moins de 7 jours avant l'événement, l'acompte reste acquis au Traiteur ; moins de 48 heures avant, la totalité de la prestation est due.</p><div class="signatures"><p>Le Traiteur : ______________________</p><p>Le Client : ______________________</p></div></div>` },

  { code: 'rest_fiche_stock', name: "Fiche de stock cuisine", category: 'commercial_financier', price: 1500, priceMax: 4500,
    description: "Fiche de suivi des stocks de denrées en cuisine : entrées, sorties, stock minimum et dates d'inventaire.", templateType: 'pdf', classe: 'C', active: true, popularity: 56,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'produit',label:"Désignation du produit",type:'text',required:true},{key:'quantiteStock',label:"Quantité en stock",type:'text',required:true},{key:'seuilAlerte',label:"Seuil de réapprovisionnement",type:'text',required:true},{key:'dateInventaire',label:"Date du dernier inventaire",type:'date',required:true}]),
    body: `<div class="doc"><h1>FICHE DE STOCK CUISINE</h1><p>Établissement : <strong>{{nomRestaurant}}</strong></p><h2>Produit suivi</h2><p>Désignation : <strong>{{produit}}</strong></p><p>Quantité en stock au <strong>{{dateInventaire}}</strong> : <strong>{{quantiteStock}}</strong></p><p>Seuil de réapprovisionnement : <strong>{{seuilAlerte}}</strong></p><h2>Mouvements</h2><p>Date | Entrées | Sorties | Stock | Visa</p><p>_____ | _______ | _______ | _____ | ____</p><p>_____ | _______ | _______ | _____ | ____</p><p>_____ | _______ | _______ | _____ | ____</p><h2>Règles de gestion</h2><p>Appliquer la règle du premier entré, premier sorti (FIFO). Contrôler les dates limites de consommation à chaque mouvement. Déclencher la commande dès l'atteinte du seuil de réapprovisionnement. Signaler toute perte ou casse sur la fiche de non-conformité.</p><div class="signatures"><p>Le responsable économat : ______________________</p></div></div>` },

  { code: 'rest_procedure_hygiene', name: "Procédure hygiène cuisine", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Procédure des bonnes pratiques d'hygiène en cuisine : hygiène du personnel, nettoyage, désinfection et gestion des déchets.", templateType: 'pdf', classe: 'B', active: true, popularity: 59,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'reglesHygiene',label:"Règles spécifiques à l'établissement",type:'textarea',required:true},{key:'responsable',label:"Responsable hygiène",type:'text',required:true},{key:'dateMaj',label:"Date de mise à jour",type:'date',required:true}]),
    body: `<div class="doc"><h1>PROCÉDURE HYGIÈNE CUISINE</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Mise à jour du <strong>{{dateMaj}}</strong></p><p>Responsable hygiène : <strong>{{responsable}}</strong></p><h2>1. Hygiène du personnel</h2><p>Tenue professionnelle propre et complète (veste, tablier, coiffe, chaussures de sécurité) ; lavage des mains à la prise de poste, après chaque manipulation à risque et après chaque passage aux sanitaires ; interdiction de bijoux ; aucune personne présentant une plaie non protégée ou une maladie contagieuse ne manipule les denrées.</p><h2>2. Nettoyage et désinfection</h2><p>Application du plan de nettoyage affiché : surfaces de travail après chaque service, sols quotidiennement, chambres froides chaque semaine, hottes et filtres chaque mois. Utilisation exclusive de produits homologués selon leur fiche technique.</p><h2>3. Gestion des déchets</h2><p>Poubelles à commande non manuelle, évacuation à chaque fin de service, local déchets nettoyé et désinfecté quotidiennement.</p><h2>4. Règles propres à l'établissement</h2><p>{{reglesHygiene}}</p><div class="signatures"><p>Le responsable hygiène : ______________________</p><p>La direction : ______________________</p></div></div>` },

  { code: 'rest_planning_equipe', name: "Planning équipe restaurant", category: 'commercial_financier', price: 2000, priceMax: 6000,
    description: "Planning hebdomadaire du personnel de salle et de cuisine, avec horaires, repos et responsables de service.", templateType: 'pdf', classe: 'C', active: true, popularity: 54,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'semaine',label:"Semaine concernée",type:'text',required:true},{key:'detailHoraires',label:"Détail des horaires par employé et par jour",type:'textarea',required:true},{key:'responsable',label:"Responsable du planning",type:'text',required:true}]),
    body: `<div class="doc"><h1>PLANNING ÉQUIPE</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Semaine : <strong>{{semaine}}</strong></p><p>Établi par : <strong>{{responsable}}</strong></p><h2>Répartition des horaires</h2><p>{{detailHoraires}}</p><h2>Règles applicables</h2><p>Le planning respecte les durées maximales de travail et les repos prévus par le Code du travail ivoirien et la convention collective applicable. Il est affiché au plus tard le jeudi précédant la semaine concernée. Toute permutation entre employés est soumise à l'accord préalable du responsable. Les absences imprévues sont signalées sans délai afin d'organiser le remplacement.</p><div class="signatures"><p>Le responsable : ______________________</p><p>Visa de la direction : ______________________</p></div></div>` },

  { code: 'rest_contrat_livraison', name: "Contrat de livraison de repas", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Contrat entre un restaurant et un prestataire de livraison de repas définissant la zone desservie, les commissions et les engagements de qualité.", templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'prestataireLivraison',label:"Nom du prestataire de livraison",type:'text',required:true},{key:'zoneLivraison',label:"Zone de livraison couverte",type:'text',required:true},{key:'commission',label:"Commission ou tarification convenue",type:'text',required:true},{key:'dateDebut',label:"Date de début du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LIVRAISON DE REPAS</h1><p>Entre <strong>{{nomRestaurant}}</strong>, ci-après "le Restaurant", et <strong>{{prestataireLivraison}}</strong>, ci-après "le Livreur".</p><h2>Article 1 — Objet</h2><p>Le Livreur assure la livraison des commandes du Restaurant auprès de la clientèle située dans la zone suivante : <strong>{{zoneLivraison}}</strong>.</p><h2>Article 2 — Conditions financières</h2><p>La rémunération du Livreur est fixée comme suit : <strong>{{commission}}</strong>. Un état récapitulatif des courses est établi chaque fin de semaine et le règlement intervient selon les modalités convenues.</p><h2>Article 3 — Engagements de qualité</h2><p>Le Livreur utilise des contenants isothermes propres, respecte la chaîne du chaud et du froid, livre dans les délais annoncés au client et adopte une tenue et un comportement conformes à l'image du Restaurant. Le Restaurant remet les commandes complètes, correctement emballées et étiquetées.</p><h2>Article 4 — Responsabilité et durée</h2><p>Le Livreur est responsable des commandes de leur remise jusqu'à la livraison. Le contrat prend effet le <strong>{{dateDebut}}</strong> pour une durée indéterminée, chaque partie pouvant y mettre fin avec un préavis de 30 jours.</p><div class="signatures"><p>Pour le Restaurant : ______________________</p><p>Pour le Livreur : ______________________</p></div></div>` },

  { code: 'rest_charte_allergenes', name: "Charte allergènes", category: 'commercial_financier', price: 2500, priceMax: 7500,
    description: "Charte d'information de la clientèle sur les allergènes présents dans les plats et procédure interne de prévention des risques allergiques.", templateType: 'pdf', classe: 'C', active: true, popularity: 45,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'allergenesPresents',label:"Allergènes présents par plat ou famille de plats",type:'textarea',required:true},{key:'mesuresPrevention',label:"Mesures de prévention en cuisine",type:'textarea',required:true},{key:'dateMaj',label:"Date de mise à jour",type:'date',required:true}]),
    body: `<div class="doc"><h1>CHARTE ALLERGÈNES</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Mise à jour du <strong>{{dateMaj}}</strong></p><h2>Engagement d'information</h2><p>L'établissement informe sa clientèle de la présence des principaux allergènes dans les plats proposés : gluten, crustacés, œufs, poissons, arachides, soja, lait, fruits à coque, céleri, moutarde, sésame, sulfites, lupin et mollusques. Le personnel de salle est formé à répondre aux questions des clients et à transmettre toute demande particulière en cuisine.</p><h2>Allergènes présents dans la carte</h2><p>{{allergenesPresents}}</p><h2>Mesures de prévention en cuisine</h2><p>{{mesuresPrevention}}</p><h2>Limite</h2><p>Malgré les précautions prises, la présence de traces croisées ne peut être totalement exclue dans un environnement de cuisine commune. Les clients présentant une allergie sévère sont invités à le signaler avant toute commande.</p><div class="signatures"><p>La direction : ______________________</p></div></div>` },

  { code: 'rest_fiche_fournisseur', name: "Fiche fournisseur alimentaire", category: 'commercial_financier', price: 2000, priceMax: 6000,
    description: "Fiche de référencement d'un fournisseur alimentaire : produits, contacts, conditions commerciales et évaluation qualité.", templateType: 'pdf', classe: 'C', active: true, popularity: 44,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'nomFournisseur',label:"Nom du fournisseur",type:'text',required:true},{key:'produitsFournis',label:"Produits fournis",type:'textarea',required:true},{key:'contact',label:"Contact commercial (téléphone, email)",type:'text',required:true},{key:'conditions',label:"Conditions commerciales (délais, paiement, livraison)",type:'text',required:true}]),
    body: `<div class="doc"><h1>FICHE FOURNISSEUR ALIMENTAIRE</h1><p>Établissement : <strong>{{nomRestaurant}}</strong></p><h2>Identification du fournisseur</h2><p>Raison sociale : <strong>{{nomFournisseur}}</strong></p><p>Contact commercial : <strong>{{contact}}</strong></p><h2>Produits référencés</h2><p>{{produitsFournis}}</p><h2>Conditions commerciales</h2><p>{{conditions}}</p><h2>Exigences qualité</h2><p>Le fournisseur garantit la conformité sanitaire des produits livrés, le respect de la chaîne du froid pour les denrées périssables, un étiquetage complet et des documents commerciaux conformes. Toute livraison non conforme est refusée et consignée.</p><h2>Évaluation périodique</h2><p>Qualité des produits : ____ / 10 — Respect des délais : ____ / 10 — Réactivité : ____ / 10</p><div class="signatures"><p>Le responsable des achats : ______________________</p></div></div>` },

  { code: 'rest_registre_temperature', name: "Registre de température frigos", category: 'commercial_financier', price: 1500, priceMax: 4500,
    description: "Registre de relevé quotidien des températures des enceintes froides du restaurant, avec actions correctives en cas de dépassement.", templateType: 'pdf', classe: 'C', active: true, popularity: 49,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'equipement',label:"Équipement suivi (frigo, congélateur, chambre froide)",type:'text',required:true},{key:'releves',label:"Relevés de température de la période",type:'textarea',required:true},{key:'responsable',label:"Responsable des relevés",type:'text',required:true},{key:'semaine',label:"Semaine concernée",type:'text',required:true}]),
    body: `<div class="doc"><h1>REGISTRE DE TEMPÉRATURE DES ENCEINTES FROIDES</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Semaine : <strong>{{semaine}}</strong></p><p>Équipement : <strong>{{equipement}}</strong> — Responsable des relevés : <strong>{{responsable}}</strong></p><h2>Températures de référence</h2><p>Réfrigérateur : entre 0 et +4 °C. Congélateur : -18 °C ou moins. Chambre froide positive : entre 0 et +3 °C.</p><h2>Relevés de la période (deux relevés par jour, matin et soir)</h2><p>{{releves}}</p><h2>Conduite à tenir en cas de dépassement</h2><p>Vérifier la fermeture des portes et le dégivrage ; contrôler à nouveau après 30 minutes ; en cas de dépassement persistant, transférer les denrées vers une enceinte conforme, évaluer les produits exposés et prévenir le service de maintenance. Consigner l'incident et les actions menées au verso.</p><div class="signatures"><p>Visa du responsable hygiène : ______________________</p></div></div>` },

  { code: 'rest_contrat_franchise', name: "Contrat de franchise restaurant", category: 'commercial_financier', price: 12000, priceMax: 36000,
    description: "Contrat de franchise de restauration : concession d'enseigne et de savoir-faire, redevances, territoire et obligations des parties selon le droit OHADA.", templateType: 'pdf', classe: 'A', active: true, popularity: 38,
    fieldsJson: F([{key:'franchiseur',label:"Nom du franchiseur",type:'text',required:true},{key:'franchise',label:"Nom du franchisé",type:'text',required:true},{key:'enseigne',label:"Enseigne concédée",type:'text',required:true},{key:'redevances',label:"Droit d'entrée et redevances",type:'text',required:true},{key:'duree',label:"Durée du contrat",type:'text',required:true},{key:'territoire',label:"Territoire concédé",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE FRANCHISE DE RESTAURATION</h1><p>Entre <strong>{{franchiseur}}</strong>, ci-après "le Franchiseur", et <strong>{{franchise}}</strong>, ci-après "le Franchisé".</p><h2>Article 1 — Objet</h2><p>Le Franchiseur concède au Franchisé le droit d'exploiter un restaurant sous l'enseigne <strong>{{enseigne}}</strong>, avec transmission du savoir-faire, du concept, des recettes et des méthodes de gestion, sur le territoire suivant : <strong>{{territoire}}</strong>.</p><h2>Article 2 — Durée</h2><p>Le contrat est conclu pour une durée de <strong>{{duree}}</strong>, renouvelable dans les conditions prévues aux présentes.</p><h2>Article 3 — Conditions financières</h2><p>Le Franchisé verse au Franchiseur : <strong>{{redevances}}</strong>. Les redevances sont calculées sur le chiffre d'affaires hors taxes et payables mensuellement, avec communication des états de ventes.</p><h2>Article 4 — Obligations du Franchiseur</h2><p>Formation initiale et continue du Franchisé et de son personnel, assistance à l'ouverture, transmission des manuels opératoires, animation du réseau et actions de communication de l'enseigne.</p><h2>Article 5 — Obligations du Franchisé</h2><p>Respect intégral du concept et des normes de l'enseigne, approvisionnement auprès des fournisseurs référencés, confidentialité du savoir-faire, non-concurrence pendant le contrat et pour la durée convenue après son terme.</p><h2>Article 6 — Droit applicable</h2><p>Le présent contrat est régi par le droit ivoirien et les Actes uniformes OHADA. Tout litige sera soumis, à défaut de règlement amiable, à l'arbitrage ou aux juridictions compétentes convenues entre les parties.</p><div class="signatures"><p>Le Franchiseur : ______________________</p><p>Le Franchisé : ______________________</p></div></div>` },

  { code: 'rest_rapport_hygiene', name: "Rapport d'hygiène interne", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Rapport d'audit hygiène interne du restaurant : constats, non-conformités relevées et plan d'actions correctives.", templateType: 'pdf', classe: 'B', active: true, popularity: 42,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'auditeur',label:"Nom de l'auditeur",type:'text',required:true},{key:'constats',label:"Constats et non-conformités relevées",type:'textarea',required:true},{key:'actionsCorrectives',label:"Actions correctives et délais",type:'textarea',required:true},{key:'dateAudit',label:"Date de l'audit",type:'date',required:true}]),
    body: `<div class="doc"><h1>RAPPORT D'HYGIÈNE INTERNE</h1><p>Établissement : <strong>{{nomRestaurant}}</strong></p><p>Audit réalisé le <strong>{{dateAudit}}</strong> par <strong>{{auditeur}}</strong></p><h2>Périmètre de l'audit</h2><p>Réception et stockage des marchandises, chambres froides, zones de préparation, plonge, gestion des déchets, hygiène du personnel, documents de traçabilité et enregistrements HACCP.</p><h2>Constats</h2><p>{{constats}}</p><h2>Plan d'actions correctives</h2><p>{{actionsCorrectives}}</p><h2>Suivi</h2><p>La mise en œuvre des actions correctives est vérifiée lors d'un contre-audit programmé dans un délai maximal de 30 jours. Le présent rapport est archivé dans le classeur qualité de l'établissement.</p><div class="signatures"><p>L'auditeur : ______________________</p><p>La direction : ______________________</p></div></div>` },

  { code: 'rest_budget_previsionnel', name: "Budget prévisionnel restaurant", category: 'commercial_financier', price: 6000, priceMax: 18000,
    description: "Budget prévisionnel d'exploitation d'un restaurant : chiffre d'affaires attendu, charges, résultat prévisionnel et hypothèses retenues.", templateType: 'pdf', classe: 'B', active: true, popularity: 50,
    fieldsJson: F([{key:'nomRestaurant',label:"Nom du restaurant",type:'text',required:true},{key:'exercice',label:"Exercice concerné",type:'text',required:true},{key:'chiffreAffairesPrev',label:"Chiffre d'affaires prévisionnel (FCFA)",type:'text',required:true},{key:'totalCharges',label:"Total des charges prévisionnelles (FCFA)",type:'text',required:true},{key:'resultatPrev',label:"Résultat prévisionnel (FCFA)",type:'text',required:true},{key:'hypotheses',label:"Hypothèses retenues (couverts, ticket moyen, saisonnalité)",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>BUDGET PRÉVISIONNEL D'EXPLOITATION</h1><p>Établissement : <strong>{{nomRestaurant}}</strong> — Exercice : <strong>{{exercice}}</strong></p><h2>Synthèse prévisionnelle</h2><p>Chiffre d'affaires prévisionnel : <strong>{{chiffreAffairesPrev}} FCFA</strong></p><p>Total des charges prévisionnelles : <strong>{{totalCharges}} FCFA</strong></p><p>Résultat prévisionnel : <strong>{{resultatPrev}} FCFA</strong></p><h2>Hypothèses retenues</h2><p>{{hypotheses}}</p><h2>Structure des charges</h2><p>Coût matière, charges de personnel, loyer et charges locatives, énergie et fluides, entretien et maintenance, marketing et communication, honoraires, impôts et taxes, amortissements : à détailler en annexe conformément au référentiel comptable SYSCOHADA.</p><h2>Suivi budgétaire</h2><p>Le réalisé est rapproché du budget chaque mois ; les écarts significatifs sont analysés et donnent lieu à des mesures correctives.</p><div class="signatures"><p>Établi par : ______________________</p><p>Validé par la direction : ______________________</p></div></div>` },

  // ============================================================
  // TOURISME (15 templates)
  // ============================================================
  { code: 'tour_contrat_circuit', name: "Contrat circuit touristique", category: 'commercial_financier', price: 5000, priceMax: 15000,
    description: "Contrat de vente d'un circuit touristique entre une agence et son client : itinéraire, prestations incluses, prix et conditions d'annulation.", templateType: 'pdf', classe: 'B', active: true, popularity: 61,
    fieldsJson: F([{key:'nomAgence',label:"Nom de l'agence de voyage",type:'text',required:true},{key:'nomClient',label:"Nom du client",type:'text',required:true},{key:'nomCircuit',label:"Intitulé du circuit",type:'text',required:true},{key:'dateDepart',label:"Date de départ",type:'date',required:true},{key:'duree',label:"Durée du circuit",type:'text',required:true},{key:'prixTotal',label:"Prix total du circuit (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE CIRCUIT TOURISTIQUE</h1><p>Entre l'agence <strong>{{nomAgence}}</strong> et <strong>{{nomClient}}</strong>, ci-après "le Voyageur".</p><h2>Article 1 — Objet</h2><p>L'agence organise au profit du Voyageur le circuit <strong>{{nomCircuit}}</strong>, d'une durée de <strong>{{duree}}</strong>, avec départ le <strong>{{dateDepart}}</strong>. Le programme détaillé, remis au Voyageur, fait partie intégrante du présent contrat.</p><h2>Article 2 — Prix et prestations incluses</h2><p>Le prix total du circuit est de <strong>{{prixTotal}} FCFA</strong> par personne. Il comprend les prestations expressément mentionnées au programme (transport, hébergement, repas, visites, guidage). Les dépenses personnelles, pourboires et prestations non mentionnées restent à la charge du Voyageur.</p><h2>Article 3 — Paiement et annulation</h2><p>Un acompte de 40 % est versé à la réservation, le solde au plus tard 15 jours avant le départ. Barème d'annulation : plus de 30 jours avant le départ, retenue de 10 % ; de 30 à 15 jours, 30 % ; de 14 à 7 jours, 60 % ; moins de 7 jours, 100 %.</p><h2>Article 4 — Responsabilité</h2><p>L'agence est responsable de la bonne exécution des prestations prévues, sauf cas de force majeure ou fait du Voyageur. Elle est titulaire des autorisations et assurances exigées par la réglementation ivoirienne du tourisme.</p><div class="signatures"><p>Pour l'Agence : ______________________</p><p>Le Voyageur : ______________________</p></div></div>` },

  { code: 'tour_convention_guide', name: "Convention guide touristique", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Convention de collaboration entre une agence ou un site touristique et un guide : missions, rémunération et obligations professionnelles.", templateType: 'pdf', classe: 'B', active: true, popularity: 46,
    fieldsJson: F([{key:'structure',label:"Nom de l'agence ou de la structure",type:'text',required:true},{key:'nomGuide',label:"Nom du guide touristique",type:'text',required:true},{key:'missions',label:"Missions confiées au guide",type:'textarea',required:true},{key:'remuneration',label:"Rémunération convenue",type:'text',required:true},{key:'duree',label:"Durée de la convention",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE GUIDE TOURISTIQUE</h1><p>Entre <strong>{{structure}}</strong>, ci-après "la Structure", et <strong>{{nomGuide}}</strong>, ci-après "le Guide".</p><h2>Article 1 — Objet</h2><p>La Structure confie au Guide, qui accepte, les missions de guidage et d'accompagnement suivantes :</p><p>{{missions}}</p><h2>Article 2 — Rémunération</h2><p>Le Guide perçoit la rémunération suivante : <strong>{{remuneration}}</strong>. Les frais engagés dans le cadre des missions (transport, restauration en circuit) sont pris en charge selon les modalités convenues avant chaque prestation.</p><h2>Article 3 — Obligations du Guide</h2><p>Le Guide justifie des qualifications et agréments requis par la réglementation ivoirienne du tourisme. Il assure les prestations avec professionnalisme, ponctualité et courtoisie, veille à la sécurité des visiteurs, valorise le patrimoine visité et respecte la confidentialité des informations commerciales de la Structure.</p><h2>Article 4 — Durée et résiliation</h2><p>La présente convention est conclue pour une durée de <strong>{{duree}}</strong>. Chaque partie peut y mettre fin avec un préavis de 30 jours. Tout manquement grave autorise la résiliation immédiate.</p><div class="signatures"><p>Pour la Structure : ______________________</p><p>Le Guide : ______________________</p></div></div>` },

  { code: 'tour_location_vehicule', name: "Contrat de location de véhicule touristique", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Contrat de location d'un véhicule avec ou sans chauffeur pour des prestations touristiques : durée, tarif, assurance et responsabilités.", templateType: 'pdf', classe: 'B', active: true, popularity: 55,
    fieldsJson: F([{key:'loueur',label:"Nom du loueur",type:'text',required:true},{key:'locataire',label:"Nom du locataire",type:'text',required:true},{key:'vehicule',label:"Véhicule loué (marque, modèle, immatriculation)",type:'text',required:true},{key:'dateDebut',label:"Date de début de location",type:'date',required:true},{key:'dateFin',label:"Date de fin de location",type:'date',required:true},{key:'tarif',label:"Tarif de la location (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LOCATION DE VÉHICULE TOURISTIQUE</h1><p>Entre <strong>{{loueur}}</strong>, ci-après "le Loueur", et <strong>{{locataire}}</strong>, ci-après "le Locataire".</p><h2>Article 1 — Objet</h2><p>Le Loueur met à la disposition du Locataire le véhicule suivant : <strong>{{vehicule}}</strong>, pour la période du <strong>{{dateDebut}}</strong> au <strong>{{dateFin}}</strong>, à des fins de transport touristique.</p><h2>Article 2 — Tarif et caution</h2><p>Le prix de la location est fixé à <strong>{{tarif}} FCFA</strong>, carburant non compris sauf mention contraire. Une caution est versée à la remise des clés et restituée après état des lieux de retour, déduction faite des éventuels dommages.</p><h2>Article 3 — État du véhicule</h2><p>Un état contradictoire du véhicule est dressé au départ et au retour. Le véhicule est restitué avec le même niveau de carburant. Le kilométrage et les conditions d'utilisation convenus figurent en annexe.</p><h2>Article 4 — Assurance et responsabilité</h2><p>Le véhicule est couvert par une assurance en cours de validité. Le Locataire demeure responsable des franchises, des infractions au code de la route commises pendant la location et de toute utilisation non conforme au présent contrat.</p><div class="signatures"><p>Le Loueur : ______________________</p><p>Le Locataire : ______________________</p></div></div>` },

  { code: 'tour_assurance_groupe', name: "Assurance voyage groupe", category: 'commercial_financier', price: 6000, priceMax: 18000,
    description: "Convention d'assurance voyage pour un groupe de touristes : garanties, période de couverture, destination et modalités de déclaration des sinistres.", templateType: 'pdf', classe: 'B', active: true, popularity: 39,
    fieldsJson: F([{key:'nomAgence',label:"Nom de l'agence souscriptrice",type:'text',required:true},{key:'assureur',label:"Nom de la compagnie d'assurance",type:'text',required:true},{key:'groupe',label:"Identification du groupe assuré (effectif)",type:'text',required:true},{key:'destination',label:"Destination du voyage",type:'text',required:true},{key:'periodeCouverture',label:"Période de couverture",type:'text',required:true},{key:'garanties',label:"Garanties souscrites et plafonds",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>CONVENTION D'ASSURANCE VOYAGE GROUPE</h1><p>Souscripteur : <strong>{{nomAgence}}</strong></p><p>Assureur : <strong>{{assureur}}</strong></p><h2>Article 1 — Objet</h2><p>La présente convention garantit le groupe suivant : <strong>{{groupe}}</strong>, pour un voyage à destination de <strong>{{destination}}</strong>, pendant la période de couverture : <strong>{{periodeCouverture}}</strong>.</p><h2>Article 2 — Garanties souscrites</h2><p>{{garanties}}</p><h2>Article 3 — Déclaration des sinistres</h2><p>Tout sinistre est déclaré à l'assureur dans un délai de cinq jours ouvrés à compter de sa survenance, accompagné des justificatifs requis. En cas d'urgence médicale, le plateau d'assistance est contacté sans délai au numéro figurant sur la carte d'assuré.</p><h2>Article 4 — Exclusions</h2><p>Sont exclues les conséquences des faits intentionnels de l'assuré, des activités à risque non déclarées et des affections antérieures non stabilisées, dans les conditions détaillées aux conditions générales de la police. La liste nominative des assurés figure en annexe.</p><div class="signatures"><p>Pour le Souscripteur : ______________________</p><p>Pour l'Assureur : ______________________</p></div></div>` },

  { code: 'tour_programme_voyage', name: "Programme de voyage détaillé", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Programme jour par jour d'un voyage organisé : itinéraire, prestations incluses, horaires et informations pratiques pour les participants.", templateType: 'pdf', classe: 'B', active: true, popularity: 52,
    fieldsJson: F([{key:'nomAgence',label:"Nom de l'agence organisatrice",type:'text',required:true},{key:'intituleVoyage',label:"Intitulé du voyage",type:'text',required:true},{key:'itineraire',label:"Programme détaillé jour par jour",type:'textarea',required:true},{key:'datesVoyage',label:"Dates du voyage",type:'text',required:true},{key:'prestationsIncluses',label:"Prestations incluses et non incluses",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>PROGRAMME DE VOYAGE</h1><h2>{{intituleVoyage}}</h2><p>Organisé par : <strong>{{nomAgence}}</strong> — Dates : <strong>{{datesVoyage}}</strong></p><h2>Itinéraire jour par jour</h2><p>{{itineraire}}</p><h2>Prestations</h2><p>{{prestationsIncluses}}</p><h2>Informations pratiques</h2><p>Se présenter au point de rendez-vous 30 minutes avant chaque départ. Se munir d'une pièce d'identité en cours de validité, de vêtements adaptés et de l'attestation d'assurance remise par l'agence. Les horaires sont donnés à titre indicatif et peuvent être ajustés pour des raisons de sécurité, de météo ou de circulation ; toute modification significative est communiquée aux participants dans les meilleurs délais.</p><h2>Contact</h2><p>Accompagnateur joignable pendant toute la durée du voyage au numéro communiqué lors du départ.</p></div>` },

  { code: 'tour_cgv_voyage', name: "Conditions générales de vente voyage", category: 'commercial_financier', price: 8000, priceMax: 24000,
    description: "Conditions générales de vente de prestations de voyage : inscription, prix, paiement, annulation, modification, responsabilité et réclamations.", templateType: 'pdf', classe: 'B', active: true, popularity: 48,
    fieldsJson: F([{key:'nomAgence',label:"Nom de l'agence de voyage",type:'text',required:true},{key:'modalitesPaiement',label:"Modalités d'inscription et de paiement",type:'textarea',required:true},{key:'conditionsAnnulation',label:"Barème et conditions d'annulation",type:'textarea',required:true},{key:'responsabilite',label:"Clauses de responsabilité et d'assurance",type:'textarea',required:true},{key:'dateMaj',label:"Date de mise à jour des CGV",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONDITIONS GÉNÉRALES DE VENTE</h1><p>Agence : <strong>{{nomAgence}}</strong> — Version en vigueur au <strong>{{dateMaj}}</strong></p><h2>Article 1 — Champ d'application</h2><p>Les présentes conditions régissent la vente de tous voyages, circuits, séjours et prestations touristiques proposés par l'agence. Toute inscription emporte adhésion sans réserve aux présentes conditions.</p><h2>Article 2 — Inscription et paiement</h2><p>{{modalitesPaiement}}</p><h2>Article 3 — Annulation et modification</h2><p>{{conditionsAnnulation}}</p><h2>Article 4 — Responsabilité et assurances</h2><p>{{responsabilite}}</p><h2>Article 5 — Réclamations</h2><p>Toute réclamation relative à un voyage est adressée à l'agence par écrit dans un délai de 30 jours suivant le retour, accompagnée des justificatifs. L'agence accuse réception sous 7 jours et apporte une réponse motivée sous 30 jours.</p><h2>Article 6 — Droit applicable</h2><p>Les présentes conditions sont régies par le droit ivoirien et la réglementation applicable aux agences de voyages. À défaut de règlement amiable, les litiges relèvent des juridictions compétentes du siège de l'agence.</p></div>` },

  { code: 'tour_fiche_satisfaction', name: "Fiche de satisfaction touriste", category: 'commercial_financier', price: 1200, priceMax: 3600,
    description: "Questionnaire de satisfaction remis aux touristes en fin de circuit ou de séjour pour évaluer les prestations et recueillir leurs suggestions.", templateType: 'pdf', classe: 'C', active: true, popularity: 47,
    fieldsJson: F([{key:'nomAgence',label:"Nom de l'agence ou de la structure",type:'text',required:true},{key:'nomCircuit',label:"Circuit ou séjour évalué",type:'text',required:true},{key:'nomClient',label:"Nom du participant (facultatif)",type:'text',required:false},{key:'noteGlobale',label:"Note globale sur 10",type:'text',required:true},{key:'commentaires',label:"Commentaires et suggestions",type:'textarea',required:false},{key:'dateRetour',label:"Date de fin du voyage",type:'date',required:true}]),
    body: `<div class="doc"><h1>FICHE DE SATISFACTION</h1><p>Structure : <strong>{{nomAgence}}</strong></p><p>Circuit ou séjour : <strong>{{nomCircuit}}</strong> — Terminé le <strong>{{dateRetour}}</strong></p><p>Participant : <strong>{{nomClient}}</strong></p><h2>Votre évaluation</h2><p>Accueil et informations avant le départ : Très satisfait / Satisfait / Peu satisfait / Insatisfait</p><p>Transport : Très satisfait / Satisfait / Peu satisfait / Insatisfait</p><p>Hébergement : Très satisfait / Satisfait / Peu satisfait / Insatisfait</p><p>Restauration : Très satisfait / Satisfait / Peu satisfait / Insatisfait</p><p>Guidage et accompagnement : Très satisfait / Satisfait / Peu satisfait / Insatisfait</p><p>Note globale : <strong>{{noteGlobale}} / 10</strong></p><h2>Vos commentaires et suggestions</h2><p>{{commentaires}}</p><p>Merci de votre confiance. Vos réponses nous aident à améliorer la qualité de nos prestations.</p></div>` },

  { code: 'tour_partenariat_receptif', name: "Contrat de partenariat réceptif", category: 'commercial_financier', price: 7000, priceMax: 21000,
    description: "Contrat entre une agence émettrice et un réceptif local pour l'organisation des prestations à destination : programmes, tarifs et commissions.", templateType: 'pdf', classe: 'B', active: true, popularity: 37,
    fieldsJson: F([{key:'agenceEmettrice',label:"Nom de l'agence émettrice",type:'text',required:true},{key:'receptif',label:"Nom du réceptif local",type:'text',required:true},{key:'destination',label:"Destination couverte",type:'text',required:true},{key:'prestations',label:"Prestations confiées au réceptif",type:'textarea',required:true},{key:'commission',label:"Conditions tarifaires et commissions",type:'text',required:true},{key:'duree',label:"Durée du partenariat",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE PARTENARIAT RÉCEPTIF</h1><p>Entre <strong>{{agenceEmettrice}}</strong>, ci-après "l'Émetteur", et <strong>{{receptif}}</strong>, ci-après "le Réceptif".</p><h2>Article 1 — Objet</h2><p>Le Réceptif assure, pour le compte de l'Émetteur, l'organisation et l'exécution des prestations touristiques à destination de <strong>{{destination}}</strong>, selon le détail suivant :</p><p>{{prestations}}</p><h2>Article 2 — Conditions financières</h2><p>{{commission}}. Les tarifs confidentiels annexés au présent contrat ne peuvent être communiqués à des tiers. La facturation intervient après chaque dossier, le règlement sous 30 jours.</p><h2>Article 3 — Qualité et responsabilité</h2><p>Le Réceptif garantit la conformité des prestations aux programmes vendus, la qualification de ses guides et chauffeurs, la conformité de ses véhicules et la détention des agréments exigés par la réglementation locale. Tout incident significatif est signalé à l'Émetteur sous 24 heures.</p><h2>Article 4 — Durée et exclusivité</h2><p>Le partenariat est conclu pour une durée de <strong>{{duree}}</strong>. Toute clause d'exclusivité éventuelle est précisée en annexe. Le contrat est régi par le droit ivoirien et les usages internationaux du tourisme.</p><div class="signatures"><p>Pour l'Émetteur : ______________________</p><p>Pour le Réceptif : ______________________</p></div></div>` },

  { code: 'tour_licence_agence', name: "Dossier de licence agence de voyage", category: 'commercial_financier', price: 12000, priceMax: 36000,
    description: "Dossier de demande de licence d'exploitation d'agence de voyage auprès des autorités ivoiriennes du tourisme : identification, pièces et engagements.", templateType: 'pdf', classe: 'A', active: true, popularity: 35,
    fieldsJson: F([{key:'demandeur',label:"Nom du demandeur (dirigeant)",type:'text',required:true},{key:'nomAgence',label:"Dénomination de l'agence",type:'text',required:true},{key:'adresseSiege',label:"Adresse du siège de l'agence",type:'text',required:true},{key:'formeJuridique',label:"Forme juridique et capital social",type:'text',required:true},{key:'piecesJointes',label:"Liste des pièces jointes au dossier",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>DOSSIER DE DEMANDE DE LICENCE D'AGENCE DE VOYAGE</h1><h2>1. Identification du demandeur</h2><p>Demandeur : <strong>{{demandeur}}</strong></p><p>Dénomination de l'agence : <strong>{{nomAgence}}</strong></p><p>Siège : <strong>{{adresseSiege}}</strong></p><p>Forme juridique et capital : <strong>{{formeJuridique}}</strong></p><h2>2. Objet de la demande</h2><p>Le demandeur sollicite auprès du ministère en charge du tourisme la délivrance de la licence d'exploitation d'agence de voyages et de tourisme, conformément à la réglementation ivoirienne régissant les professions touristiques.</p><h2>3. Pièces constitutives du dossier</h2><p>{{piecesJointes}}</p><h2>4. Engagements du demandeur</h2><p>Le demandeur s'engage à exercer l'activité dans le respect de la réglementation en vigueur, à souscrire les garanties financières et les assurances de responsabilité civile professionnelle exigées, à employer un personnel qualifié et à porter à la connaissance de l'administration toute modification substantielle affectant l'agence (dirigeants, siège, forme juridique).</p><h2>5. Attestation sur l'honneur</h2><p>Le demandeur atteste sur l'honneur l'exactitude des renseignements fournis et la sincérité des pièces produites.</p><div class="signatures"><p>Fait à ____________, le ____________</p><p>Le demandeur : ______________________</p></div></div>` },

  { code: 'tour_rapport_activite', name: "Rapport d'activité touristique", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Rapport périodique d'activité d'une structure touristique : statistiques de fréquentation, faits marquants et perspectives.", templateType: 'pdf', classe: 'B', active: true, popularity: 40,
    fieldsJson: F([{key:'structure',label:"Nom de la structure touristique",type:'text',required:true},{key:'periode',label:"Période couverte par le rapport",type:'text',required:true},{key:'statistiques',label:"Statistiques de fréquentation et de chiffre d'affaires",type:'textarea',required:true},{key:'faitsMarquants',label:"Faits marquants de la période",type:'textarea',required:true},{key:'perspectives',label:"Perspectives et actions prévues",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>RAPPORT D'ACTIVITÉ TOURISTIQUE</h1><p>Structure : <strong>{{structure}}</strong></p><p>Période couverte : <strong>{{periode}}</strong></p><h2>1. Statistiques de la période</h2><p>{{statistiques}}</p><h2>2. Faits marquants</h2><p>{{faitsMarquants}}</p><h2>3. Analyse</h2><p>Comparaison avec la période précédente et avec la même période de l'année antérieure ; évolution de la clientèle nationale et internationale ; performance des canaux de commercialisation.</p><h2>4. Perspectives et plan d'actions</h2><p>{{perspectives}}</p><div class="signatures"><p>Établi par : ______________________</p><p>Visa de la direction : ______________________</p></div></div>` },

  { code: 'tour_convention_site', name: "Convention d'exploitation de site touristique", category: 'commercial_financier', price: 9000, priceMax: 27000,
    description: "Convention entre une collectivité ou un propriétaire et un exploitant pour la mise en valeur et l'exploitation d'un site touristique.", templateType: 'pdf', classe: 'B', active: true, popularity: 33,
    fieldsJson: F([{key:'collectivite',label:"Collectivité ou propriétaire du site",type:'text',required:true},{key:'exploitant',label:"Nom de l'exploitant",type:'text',required:true},{key:'siteTouristique',label:"Désignation du site touristique",type:'text',required:true},{key:'duree',label:"Durée de la convention",type:'text',required:true},{key:'redevance',label:"Redevance ou contrepartie financière",type:'text',required:true},{key:'obligations',label:"Obligations d'aménagement et d'entretien",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>CONVENTION D'EXPLOITATION DE SITE TOURISTIQUE</h1><p>Entre <strong>{{collectivite}}</strong>, ci-après "le Concédant", et <strong>{{exploitant}}</strong>, ci-après "l'Exploitant".</p><h2>Article 1 — Objet</h2><p>Le Concédant confie à l'Exploitant la mise en valeur, l'animation et l'exploitation touristique du site suivant : <strong>{{siteTouristique}}</strong>.</p><h2>Article 2 — Durée</h2><p>La convention est conclue pour une durée de <strong>{{duree}}</strong>, renouvelable dans les conditions convenues entre les parties.</p><h2>Article 3 — Conditions financières</h2><p>L'Exploitant verse au Concédant la contrepartie suivante : <strong>{{redevance}}</strong>. Les modalités de contrôle des recettes du site sont précisées en annexe.</p><h2>Article 4 — Obligations de l'Exploitant</h2><p>{{obligations}}</p><h2>Article 5 — Préservation du site</h2><p>L'Exploitant veille à la préservation du patrimoine naturel et culturel du site, au respect des capacités d'accueil, à la sécurité des visiteurs et à l'association des communautés locales aux retombées de l'activité.</p><h2>Article 6 — Résiliation</h2><p>Le non-respect des obligations essentielles de la présente convention autorise sa résiliation après mise en demeure restée sans effet pendant 60 jours. La convention est régie par le droit ivoirien.</p><div class="signatures"><p>Pour le Concédant : ______________________</p><p>Pour l'Exploitant : ______________________</p></div></div>` },

  { code: 'tour_croisiere_lagunaire', name: "Contrat croisière lagunaire", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Contrat de prestation de croisière lagunaire : embarcation, itinéraire, effectif de passagers, consignes de sécurité et tarif.", templateType: 'pdf', classe: 'B', active: true, popularity: 44,
    fieldsJson: F([{key:'operateur',label:"Nom de l'opérateur de croisière",type:'text',required:true},{key:'nomClient',label:"Nom du client",type:'text',required:true},{key:'embarcation',label:"Embarcation utilisée",type:'text',required:true},{key:'dateCroisiere',label:"Date de la croisière",type:'date',required:true},{key:'nombrePassagers',label:"Nombre de passagers",type:'text',required:true},{key:'tarif',label:"Tarif de la prestation (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE CROISIÈRE LAGUNAIRE</h1><p>Entre <strong>{{operateur}}</strong>, ci-après "l'Opérateur", et <strong>{{nomClient}}</strong>, ci-après "le Client".</p><h2>Article 1 — Objet</h2><p>L'Opérateur organise au profit du Client une croisière lagunaire à bord de l'embarcation <strong>{{embarcation}}</strong>, le <strong>{{dateCroisiere}}</strong>, pour <strong>{{nombrePassagers}}</strong> passagers. L'itinéraire et les prestations à bord figurent en annexe.</p><h2>Article 2 — Tarif</h2><p>Le prix de la prestation est fixé à <strong>{{tarif}} FCFA</strong>. Un acompte de 50 % est versé à la réservation, le solde avant l'embarquement.</p><h2>Article 3 — Sécurité</h2><p>L'embarcation est conforme aux normes de navigation lagunaire en vigueur et équipée de gilets de sauvetage en nombre suffisant, portés obligatoirement par tous les passagers. Le pilote est seul juge des conditions de navigation ; en cas de météo défavorable, la croisière est reportée sans frais ou remboursée.</p><h2>Article 4 — Responsabilité</h2><p>L'Opérateur est assuré pour le transport de passagers. Le Client répond du comportement des membres de son groupe et des dommages causés à l'embarcation. L'embarquement de passagers au-delà de la capacité autorisée est strictement interdit.</p><div class="signatures"><p>Pour l'Opérateur : ______________________</p><p>Le Client : ______________________</p></div></div>` },

  { code: 'tour_charte_ecotourisme', name: "Charte écotourisme", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Charte d'engagement écotouristique d'une structure : préservation de l'environnement, retombées locales et sensibilisation des visiteurs.", templateType: 'pdf', classe: 'B', active: true, popularity: 36,
    fieldsJson: F([{key:'structure',label:"Nom de la structure signataire",type:'text',required:true},{key:'engagements',label:"Engagements environnementaux et sociaux détaillés",type:'textarea',required:true},{key:'communaute',label:"Communautés locales associées",type:'text',required:true},{key:'dateAdoption',label:"Date d'adoption de la charte",type:'date',required:true}]),
    body: `<div class="doc"><h1>CHARTE ÉCOTOURISME</h1><p>Structure signataire : <strong>{{structure}}</strong></p><p>Adoptée le <strong>{{dateAdoption}}</strong></p><h2>Préambule</h2><p>Consciente de la richesse et de la fragilité du patrimoine naturel et culturel des territoires visités, la structure signataire adopte la présente charte et en fait le socle de ses activités touristiques.</p><h2>Engagements</h2><p>{{engagements}}</p><h2>Retombées locales</h2><p>La structure associe les communautés suivantes aux activités et à leurs retombées économiques : <strong>{{communaute}}</strong>. Elle privilégie les emplois, les guides, les hébergements et les productions locales.</p><h2>Sensibilisation des visiteurs</h2><p>Chaque visiteur est informé des bonnes pratiques : respect de la faune et de la flore, gestion des déchets, économie de l'eau et de l'énergie, respect des usages et de la dignité des populations d'accueil, encadrement des photographies de personnes.</p><h2>Suivi</h2><p>Les engagements de la présente charte sont évalués chaque année et les résultats communiqués aux partenaires.</p><div class="signatures"><p>Pour la structure : ______________________</p></div></div>` },

  { code: 'tour_plan_developpement', name: "Plan de développement touristique", category: 'commercial_financier', price: 12000, priceMax: 36000,
    description: "Plan stratégique de développement touristique d'un territoire ou d'une structure : diagnostic, axes stratégiques, budget et indicateurs de suivi.", templateType: 'pdf', classe: 'A', active: true, popularity: 32,
    fieldsJson: F([{key:'territoire',label:"Territoire ou structure concerné",type:'text',required:true},{key:'porteur',label:"Porteur du plan",type:'text',required:true},{key:'diagnostic',label:"Diagnostic de l'offre et de la demande",type:'textarea',required:true},{key:'axesStrategiques',label:"Axes stratégiques et actions prioritaires",type:'textarea',required:true},{key:'budgetEstime',label:"Budget estimatif global (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT TOURISTIQUE</h1><p>Territoire ou structure : <strong>{{territoire}}</strong></p><p>Porteur du plan : <strong>{{porteur}}</strong></p><h2>1. Diagnostic</h2><p>{{diagnostic}}</p><h2>2. Vision et objectifs</h2><p>Le présent plan vise à accroître durablement la fréquentation, les retombées économiques locales et la qualité de l'expérience visiteur, en cohérence avec la stratégie nationale de développement du tourisme en Côte d'Ivoire.</p><h2>3. Axes stratégiques et actions</h2><p>{{axesStrategiques}}</p><h2>4. Budget et financement</h2><p>Budget estimatif global : <strong>{{budgetEstime}} FCFA</strong>. Sources de financement envisagées : fonds propres, concours publics, partenariats privés et financements des bailleurs, à détailler par action en annexe.</p><h2>5. Gouvernance et suivi</h2><p>Un comité de pilotage réunissant les acteurs publics, privés et communautaires se réunit chaque trimestre. Les indicateurs de suivi (arrivées, nuitées, emplois créés, recettes, satisfaction) sont renseignés semestriellement et publiés dans le rapport d'activité.</p><div class="signatures"><p>Le porteur du plan : ______________________</p></div></div>` },

  { code: 'tour_brochure_tarifaire', name: "Brochure tarifaire des séjours", category: 'commercial_financier', price: 2000, priceMax: 6000,
    description: "Brochure présentant les séjours et circuits proposés avec leurs tarifs, la période de validité et les conditions applicables.", templateType: 'pdf', classe: 'C', active: true, popularity: 41,
    fieldsJson: F([{key:'nomAgence',label:"Nom de l'agence",type:'text',required:true},{key:'saison',label:"Saison ou période concernée",type:'text',required:true},{key:'detailSejours',label:"Détail des séjours et tarifs",type:'textarea',required:true},{key:'conditions',label:"Conditions applicables aux tarifs",type:'textarea',required:true},{key:'dateValidite',label:"Date limite de validité des tarifs",type:'date',required:true}]),
    body: `<div class="doc"><h1>BROCHURE TARIFAIRE DES SÉJOURS</h1><p>Agence : <strong>{{nomAgence}}</strong></p><p>Saison : <strong>{{saison}}</strong> — Tarifs valables jusqu'au <strong>{{dateValidite}}</strong></p><h2>Nos séjours et circuits</h2><p>{{detailSejours}}</p><h2>Conditions applicables</h2><p>{{conditions}}</p><h2>Mentions</h2><p>Les prix sont exprimés en francs CFA par personne, sur la base d'une chambre double sauf mention contraire. Ils comprennent les prestations expressément indiquées pour chaque séjour et demeurent soumis à disponibilité au moment de la réservation. Les conditions générales de vente de l'agence, remises à toute demande, sont applicables à chaque inscription.</p><p>Renseignements et réservations auprès de nos conseillers voyage.</p></div>` },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 15b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
