import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ── 25 Diagnostic immobilier / Transaction (préfixe diag_) ──
  {
    code: 'diag_amiante',
    name: "Accord de service de diagnostic amiante (immeuble)",
    category: 'immobilier', price: 5000, priceMax: 18000,
    description: "Accord entre le propriétaire d'un immeuble et un diagnostiqueur agréé pour la recherche et l'identification de matériaux amiantés conformément à la réglementation OHADA.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 71,
    fieldsJson: F([
      { key: 'nom_proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien immobilier", type: 'text', required: true },
      { key: 'date_intervention', label: "Date d'intervention prévue", type: 'date', required: true },
      { key: 'nom_diagnostiqueur', label: "Nom du diagnostiqueur agréé", type: 'text', required: true },
      { key: 'observations', label: "Observations particulières", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC AMIANTE</h1><p>Entre <strong>{{nom_proprietaire}}</strong>, propriétaire du bien sis à <strong>{{adresse_bien}}</strong>, et le diagnostiqueur agréé <strong>{{nom_diagnostiqueur}}</strong>.</p><p>Date d'intervention prévue : <strong>{{date_intervention}}</strong>.</p><p>Le diagnostiqueur s'engage à réaliser la recherche d'amiante dans les matériaux et produits de construction de l'immeuble, conformément aux normes en vigueur en Côte d'Ivoire et aux dispositions de l'Acte uniforme OHADA relatif aux contrats de prestation de services.</p><p>Observations : {{observations}}</p><p>Fait à Abidjan, le {{date_intervention}}.</p><p>Signature du propriétaire : __________________ Signature du diagnostiqueur : __________________</p></div>`,
  },
  {
    code: 'diag_plomb',
    name: "Accord de service de diagnostic plomb (peinture)",
    category: 'immobilier', price: 4500, priceMax: 16000,
    description: "Convention de prestation pour la détection du plomb dans les peintures d'un bien immobilier, établie entre le donneur d'ordre et l'expert agréé.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'donneur_ordre', label: "Donneur d'ordre", type: 'text', required: true },
      { key: 'adresse_immeuble', label: "Adresse de l'immeuble", type: 'text', required: true },
      { key: 'date_diagnostic', label: "Date du diagnostic", type: 'date', required: true },
      { key: 'expert_agree', label: "Expert agréé", type: 'text', required: true },
      { key: 'surface_concernee', label: "Surface concernée (m²)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC PLOMB (PEINTURE)</h1><p><strong>{{donneur_ordre}}</strong> confie à <strong>{{expert_agree}}</strong> la mission de diagnostic plomb portant sur le bien situé à <strong>{{adresse_immeuble}}</strong>.</p><p>Surface concernée : <strong>{{surface_concernee}} m²</strong>. Date prévue : <strong>{{date_diagnostic}}</strong>.</p><p>L'expert s'engage à remettre un rapport détaillé dans un délai de dix (10) jours ouvrables suivant l'intervention, conformément aux bonnes pratiques professionnelles applicables en Côte d'Ivoire.</p><p>Signatures des parties : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_termites',
    name: "Accord de service de diagnostic termites",
    category: 'immobilier', price: 4000, priceMax: 14000,
    description: "Accord de prestation pour l'inspection et le rapport relatif à la présence de termites et d'insectes xylophages dans un bien immobilier.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 68,
    fieldsJson: F([
      { key: 'proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_visite', label: "Date de la visite", type: 'date', required: true },
      { key: 'prestataire', label: "Nom du prestataire", type: 'text', required: true },
      { key: 'zones_inspectees', label: "Zones à inspecter", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC TERMITES</h1><p><strong>{{proprietaire}}</strong>, propriétaire du bien sis <strong>{{adresse_bien}}</strong>, mandate <strong>{{prestataire}}</strong> pour réaliser un diagnostic termites le <strong>{{date_visite}}</strong>.</p><p>Zones à inspecter : {{zones_inspectees}}</p><p>Le prestataire remettra un rapport circonstancié mentionnant la présence ou l'absence de termites et d'insectes xylophages, assorti de recommandations de traitement le cas échéant.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_electrique',
    name: "Accord de service de diagnostic électrique",
    category: 'immobilier', price: 5000, priceMax: 17000,
    description: "Convention de diagnostic de l'installation électrique intérieure d'un bien immobilier en vue d'une vente ou d'une mise en location.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 74,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_diagnostic', label: "Date du diagnostic", type: 'date', required: true },
      { key: 'technicien', label: "Technicien agréé", type: 'text', required: true },
      { key: 'anciennete_installation', label: "Ancienneté de l'installation (années)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC ÉLECTRIQUE</h1><p><strong>{{nom_client}}</strong> confie à <strong>{{technicien}}</strong> la mission de diagnostic de l'installation électrique du bien situé à <strong>{{adresse_bien}}</strong>.</p><p>Date prévue : <strong>{{date_diagnostic}}</strong>. Ancienneté estimée de l'installation : <strong>{{anciennete_installation}} ans</strong>.</p><p>Le technicien vérifiera la conformité de l'installation aux normes électriques ivoiriennes en vigueur et établira un rapport de diagnostic détaillé identifiant tout risque pour la sécurité des personnes.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_gaz',
    name: "Accord de service de diagnostic gaz",
    category: 'immobilier', price: 5000, priceMax: 16000,
    description: "Accord de prestation pour le diagnostic des installations intérieures de gaz dans un bien immobilier destiné à la vente ou à la location.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 66,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_diagnostic', label: "Date du diagnostic", type: 'date', required: true },
      { key: 'expert_gaz', label: "Expert gaz agréé", type: 'text', required: true },
      { key: 'type_installation', label: "Type d'installation gaz", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC GAZ</h1><p><strong>{{nom_client}}</strong> mandate <strong>{{expert_gaz}}</strong> pour réaliser le diagnostic de l'installation intérieure de gaz du bien situé à <strong>{{adresse_bien}}</strong>, le <strong>{{date_diagnostic}}</strong>.</p><p>Type d'installation : {{type_installation}}.</p><p>L'expert vérifiera l'état des tuyauteries fixes, des équipements à gaz et de la ventilation des locaux, conformément aux normes applicables en Côte d'Ivoire et aux bonnes pratiques OHADA en matière de sécurité immobilière.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_dpe',
    name: "Accord de service de diagnostic de performance énergétique (DPE)",
    category: 'immobilier', price: 6000, priceMax: 20000,
    description: "Convention de réalisation d'un diagnostic de performance énergétique (DPE) d'un bien immobilier, permettant d'évaluer sa consommation d'énergie et son impact environnemental.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 77,
    fieldsJson: F([
      { key: 'nom_proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_diagnostic', label: "Date du diagnostic", type: 'date', required: true },
      { key: 'diagnostiqueur', label: "Diagnostiqueur certifié", type: 'text', required: true },
      { key: 'surface_habitable', label: "Surface habitable (m²)", type: 'text', required: true },
      { key: 'annee_construction', label: "Année de construction", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC DE PERFORMANCE ÉNERGÉTIQUE (DPE)</h1><p><strong>{{nom_proprietaire}}</strong>, propriétaire du bien sis <strong>{{adresse_bien}}</strong> (surface habitable : <strong>{{surface_habitable}} m²</strong>, construit en <strong>{{annee_construction}}</strong>), confie à <strong>{{diagnostiqueur}}</strong> la réalisation d'un DPE le <strong>{{date_diagnostic}}</strong>.</p><p>Le diagnostiqueur s'engage à évaluer la consommation énergétique du bien et ses émissions de gaz à effet de serre, et à délivrer une étiquette énergétique conforme aux standards internationaux applicables en Afrique de l'Ouest.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_assainissement',
    name: "Accord de service de diagnostic assainissement non collectif",
    category: 'immobilier', price: 4500, priceMax: 15000,
    description: "Accord de prestation pour le contrôle et le diagnostic du système d'assainissement non collectif (fosse septique, puits perdu) d'un bien immobilier.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'nom_proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_controle', label: "Date de contrôle", type: 'date', required: true },
      { key: 'organisme_agr', label: "Organisme agréé", type: 'text', required: true },
      { key: 'type_systeme', label: "Type de système d'assainissement", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC ASSAINISSEMENT NON COLLECTIF</h1><p><strong>{{nom_proprietaire}}</strong> mandate <strong>{{organisme_agr}}</strong> pour contrôler le système d'assainissement non collectif du bien situé à <strong>{{adresse_bien}}</strong>, le <strong>{{date_controle}}</strong>.</p><p>Type de système : {{type_systeme}}.</p><p>L'organisme agréé remettra un rapport de contrôle mentionnant la conformité ou non du système, les risques sanitaires identifiés et les travaux de mise en conformité éventuellement requis.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_carrez',
    name: "Accord de service de métrage loi Carrez",
    category: 'immobilier', price: 3500, priceMax: 12000,
    description: "Convention de prestation pour la mesure certifiée de la superficie privative d'un lot de copropriété conformément aux règles de la loi Carrez adaptées au droit ivoirien.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([
      { key: 'nom_vendeur', label: "Nom du vendeur", type: 'text', required: true },
      { key: 'adresse_lot', label: "Adresse et numéro du lot", type: 'text', required: true },
      { key: 'date_mesure', label: "Date de mesure", type: 'date', required: true },
      { key: 'metreur', label: "Métreur certifié", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE MÉTRAGE LOI CARREZ</h1><p><strong>{{nom_vendeur}}</strong>, vendeur du lot sis <strong>{{adresse_lot}}</strong>, mandate <strong>{{metreur}}</strong> pour la mesure certifiée de la superficie privative dudit lot, le <strong>{{date_mesure}}</strong>.</p><p>Le métreur certifié s'engage à mesurer la superficie privative selon les règles de calcul reconnues, à exclure les surfaces dont la hauteur sous plafond est inférieure à 1,80 m, et à délivrer un certificat de surface opposable aux tiers.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_risques_naturels',
    name: "Accord de service de diagnostic état des risques naturels",
    category: 'immobilier', price: 4000, priceMax: 13000,
    description: "Convention pour l'établissement d'un état des risques naturels, miniers et technologiques (ERNMT) applicables à un bien immobilier en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([
      { key: 'nom_proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_etablissement', label: "Date d'établissement", type: 'date', required: true },
      { key: 'expert_risques', label: "Expert en risques", type: 'text', required: true },
      { key: 'commune', label: "Commune / Département", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC ÉTAT DES RISQUES NATURELS</h1><p><strong>{{nom_proprietaire}}</strong> confie à <strong>{{expert_risques}}</strong> l'établissement de l'état des risques naturels pour le bien situé à <strong>{{adresse_bien}}</strong>, commune de <strong>{{commune}}</strong>, le <strong>{{date_etablissement}}</strong>.</p><p>L'expert analysera les risques naturels (inondations, glissements de terrain, etc.) et technologiques répertoriés par les autorités ivoiriennes compétentes, et remettra un formulaire ERNMT dûment renseigné.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_dtg',
    name: "Accord de service de diagnostic technique global (DTG)",
    category: 'immobilier', price: 8000, priceMax: 28000,
    description: "Accord pour la réalisation d'un diagnostic technique global portant sur l'état général de l'immeuble, les travaux nécessaires et la situation du syndicat de copropriété.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 55,
    fieldsJson: F([
      { key: 'syndicat_cop', label: "Syndicat de copropriété", type: 'text', required: true },
      { key: 'adresse_immeuble', label: "Adresse de l'immeuble", type: 'text', required: true },
      { key: 'date_diagnostic', label: "Date du diagnostic", type: 'date', required: true },
      { key: 'bureau_etude', label: "Bureau d'étude mandaté", type: 'text', required: true },
      { key: 'nombre_lots', label: "Nombre de lots", type: 'text', required: true },
      { key: 'observations', label: "Observations préliminaires", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DIAGNOSTIC TECHNIQUE GLOBAL (DTG)</h1><p>Le syndicat de copropriété <strong>{{syndicat_cop}}</strong> de l'immeuble sis <strong>{{adresse_immeuble}}</strong> ({{nombre_lots}} lots) mandate <strong>{{bureau_etude}}</strong> pour la réalisation d'un diagnostic technique global, le <strong>{{date_diagnostic}}</strong>.</p><p>Observations préliminaires : {{observations}}</p><p>Le bureau d'étude examinera l'état du bâti, des équipements collectifs et des parties communes, et remettra un rapport assorti d'un plan de travaux sur dix (10) ans et d'une estimation des coûts.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_expertise_venale',
    name: "Accord de service d'expertise immobilière (valeur vénale)",
    category: 'immobilier', price: 10000, priceMax: 35000,
    description: "Convention de prestation d'expertise immobilière visant à déterminer la valeur vénale d'un bien, conformément aux méthodes reconnues et au droit OHADA.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 82,
    fieldsJson: F([
      { key: 'donneur_ordre', label: "Donneur d'ordre", type: 'text', required: true },
      { key: 'description_bien', label: "Description du bien", type: 'textarea', required: true },
      { key: 'date_expertise', label: "Date de l'expertise", type: 'date', required: true },
      { key: 'expert_immobilier', label: "Expert immobilier agréé", type: 'text', required: true },
      { key: 'finalite_expertise', label: "Finalité de l'expertise", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'EXPERTISE IMMOBILIÈRE (VALEUR VÉNALE)</h1><p><strong>{{donneur_ordre}}</strong> confie à <strong>{{expert_immobilier}}</strong> la mission d'expertise immobilière aux fins de détermination de la valeur vénale du bien ci-après décrit : <em>{{description_bien}}</em>.</p><p>Finalité de l'expertise : <strong>{{finalite_expertise}}</strong>. Date prévue : <strong>{{date_expertise}}</strong>.</p><p>L'expert remettra un rapport d'expertise motivé, fondé sur les méthodes par comparaison, par le revenu et par le coût de remplacement, conformément aux standards professionnels en vigueur en Côte d'Ivoire et aux principes de l'OHADA.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_avant_sinistre',
    name: "Accord de service d'expertise avant-sinistre immobilier",
    category: 'immobilier', price: 7000, priceMax: 25000,
    description: "Convention permettant au propriétaire de faire évaluer l'état et la valeur de son bien avant tout sinistre, facilitant ainsi les démarches d'indemnisation ultérieures.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 59,
    fieldsJson: F([
      { key: 'nom_proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_expertise', label: "Date de l'expertise", type: 'date', required: true },
      { key: 'expert_mandate', label: "Expert mandaté", type: 'text', required: true },
      { key: 'assureur', label: "Compagnie d'assurance", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'EXPERTISE AVANT-SINISTRE IMMOBILIER</h1><p><strong>{{nom_proprietaire}}</strong>, assuré auprès de <strong>{{assureur}}</strong>, mandate <strong>{{expert_mandate}}</strong> pour réaliser une expertise d'état du bien situé à <strong>{{adresse_bien}}</strong>, le <strong>{{date_expertise}}</strong>.</p><p>Cette expertise préventive a pour objet de dresser un état descriptif et évaluatif du bien avant tout sinistre éventuel, afin de servir de référence en cas de recours en indemnisation auprès de la compagnie d'assurance.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_apres_sinistre',
    name: "Accord de service d'expertise après-sinistre (dégâts des eaux)",
    category: 'immobilier', price: 6000, priceMax: 22000,
    description: "Convention de mission d'expertise post-sinistre pour l'évaluation des dommages causés par des dégâts des eaux dans un bien immobilier.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 64,
    fieldsJson: F([
      { key: 'nom_sinistre', label: "Nom du sinistré", type: 'text', required: true },
      { key: 'adresse_sinistre', label: "Adresse du sinistre", type: 'text', required: true },
      { key: 'date_sinistre', label: "Date du sinistre", type: 'date', required: true },
      { key: 'date_expertise', label: "Date de l'expertise", type: 'date', required: true },
      { key: 'expert_mandate', label: "Expert mandaté", type: 'text', required: true },
      { key: 'description_degats', label: "Description des dégâts", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'EXPERTISE APRÈS-SINISTRE (DÉGÂTS DES EAUX)</h1><p><strong>{{nom_sinistre}}</strong>, sinistré pour le bien sis <strong>{{adresse_sinistre}}</strong>, mandate <strong>{{expert_mandate}}</strong> pour une expertise post-sinistre suite aux dégâts des eaux survenus le <strong>{{date_sinistre}}</strong>.</p><p>Date d'expertise : <strong>{{date_expertise}}</strong>.</p><p>Description des dégâts : {{description_degats}}</p><p>L'expert évaluera l'étendue des dommages, les causes du sinistre et le montant de l'indemnisation due, conformément aux conditions générales du contrat d'assurance et au code des assurances applicable en Côte d'Ivoire.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_audit_technique',
    name: "Accord de service d'audit technique de bâtiment",
    category: 'immobilier', price: 9000, priceMax: 30000,
    description: "Convention de mission d'audit technique global d'un bâtiment visant à évaluer l'état structurel, les équipements et la conformité réglementaire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 70,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'adresse_batiment', label: "Adresse du bâtiment", type: 'text', required: true },
      { key: 'date_audit', label: "Date de l'audit", type: 'date', required: true },
      { key: 'bureau_audit', label: "Bureau d'audit technique", type: 'text', required: true },
      { key: 'perimetre_audit', label: "Périmètre de l'audit", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'AUDIT TECHNIQUE DE BÂTIMENT</h1><p><strong>{{maitre_ouvrage}}</strong> confie à <strong>{{bureau_audit}}</strong> la mission d'audit technique du bâtiment situé à <strong>{{adresse_batiment}}</strong>, programmée le <strong>{{date_audit}}</strong>.</p><p>Périmètre de l'audit : {{perimetre_audit}}</p><p>Le bureau d'audit examinera la structure, les façades, la toiture, les réseaux et équipements techniques, et remettra un rapport complet assorti d'une hiérarchisation des travaux à réaliser et d'une estimation budgétaire, conformément aux normes de construction applicables en Côte d'Ivoire.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_conformite_neuf',
    name: "Accord de service de contrôle de conformité construction neuve",
    category: 'immobilier', price: 7500, priceMax: 25000,
    description: "Convention de mission de contrôle de conformité des travaux d'une construction neuve par rapport aux plans approuvés et aux normes techniques ivoiriennes.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 73,
    fieldsJson: F([
      { key: 'promoteur', label: "Promoteur / Maître d'ouvrage", type: 'text', required: true },
      { key: 'adresse_chantier', label: "Adresse du chantier", type: 'text', required: true },
      { key: 'date_controle', label: "Date de contrôle", type: 'date', required: true },
      { key: 'organisme_controle', label: "Organisme de contrôle", type: 'text', required: true },
      { key: 'reference_permis', label: "Référence du permis de construire", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CONTRÔLE DE CONFORMITÉ CONSTRUCTION NEUVE</h1><p><strong>{{promoteur}}</strong> mandate <strong>{{organisme_controle}}</strong> pour le contrôle de conformité de la construction neuve sise <strong>{{adresse_chantier}}</strong>, autorisée par le permis de construire N° <strong>{{reference_permis}}</strong>.</p><p>Date de contrôle : <strong>{{date_controle}}</strong>.</p><p>L'organisme de contrôle vérifiera la conformité des ouvrages réalisés aux plans architecturaux et techniques approuvés, ainsi qu'aux normes et réglementations techniques de la construction applicables en République de Côte d'Ivoire.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_mandataire',
    name: "Accord de mandataire immobilier (agent non titulaire carte)",
    category: 'immobilier', price: 5000, priceMax: 18000,
    description: "Accord encadrant la relation entre un agent immobilier titulaire de la carte professionnelle et un mandataire collaborateur non titulaire, dans le respect des règles OHADA.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([
      { key: 'agent_titulaire', label: "Agent titulaire (mandant)", type: 'text', required: true },
      { key: 'numero_carte', label: "N° de carte professionnelle", type: 'text', required: true },
      { key: 'mandataire', label: "Nom du mandataire", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
      { key: 'secteur_geographique', label: "Secteur géographique confié", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE MANDATAIRE IMMOBILIER</h1><p>Entre <strong>{{agent_titulaire}}</strong>, agent immobilier titulaire de la carte professionnelle N° <strong>{{numero_carte}}</strong> (ci-après le Mandant), et <strong>{{mandataire}}</strong> (ci-après le Mandataire), il est convenu ce qui suit à compter du <strong>{{date_debut}}</strong>.</p><p>Secteur géographique confié : <strong>{{secteur_geographique}}</strong>.</p><p>Le Mandataire agit au nom et pour le compte du Mandant, sans pouvoir engager ce dernier au-delà des limites fixées par le présent accord, conformément aux dispositions de l'Acte uniforme OHADA sur le droit commercial général relatives au mandat.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_agence_vente',
    name: "Accord de service d'agence immobilière (vente)",
    category: 'immobilier', price: 6000, priceMax: 20000,
    description: "Mandat de vente exclusive ou simple confié à une agence immobilière par un propriétaire souhaitant céder son bien, régi par le droit ivoirien et les principes OHADA.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 85,
    fieldsJson: F([
      { key: 'nom_mandant', label: "Nom du mandant (propriétaire)", type: 'text', required: true },
      { key: 'agence', label: "Agence immobilière mandatée", type: 'text', required: true },
      { key: 'description_bien', label: "Description du bien à vendre", type: 'textarea', required: true },
      { key: 'prix_vente', label: "Prix de vente souhaité (FCFA)", type: 'text', required: true },
      { key: 'date_mandat', label: "Date du mandat", type: 'date', required: true },
      { key: 'duree_mandat', label: "Durée du mandat (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'AGENCE IMMOBILIÈRE (VENTE)</h1><p><strong>{{nom_mandant}}</strong> confie à <strong>{{agence}}</strong> le mandat de vendre le bien ci-après décrit : <em>{{description_bien}}</em>.</p><p>Prix de vente : <strong>{{prix_vente}} FCFA</strong>. Date : <strong>{{date_mandat}}</strong>. Durée : <strong>{{duree_mandat}} mois</strong>.</p><p>L'agence s'engage à déployer tous les moyens de prospection et de publicité appropriés pour trouver un acquéreur au prix convenu, et percevra une commission dont le taux est fixé aux conditions particulières, conformément aux usages de la profession immobilière en Côte d'Ivoire.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_agence_location',
    name: "Accord de service d'agence immobilière (location)",
    category: 'immobilier', price: 5000, priceMax: 17000,
    description: "Mandat de location confié à une agence immobilière par un bailleur souhaitant louer son bien, avec définition des honoraires et des obligations de chaque partie.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 80,
    fieldsJson: F([
      { key: 'nom_bailleur', label: "Nom du bailleur", type: 'text', required: true },
      { key: 'agence', label: "Agence immobilière mandatée", type: 'text', required: true },
      { key: 'description_bien', label: "Description du bien à louer", type: 'textarea', required: true },
      { key: 'loyer_mensuel', label: "Loyer mensuel souhaité (FCFA)", type: 'text', required: true },
      { key: 'date_mandat', label: "Date du mandat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'AGENCE IMMOBILIÈRE (LOCATION)</h1><p><strong>{{nom_bailleur}}</strong> confie à <strong>{{agence}}</strong> le mandat de trouver un locataire pour le bien ci-après décrit : <em>{{description_bien}}</em>.</p><p>Loyer mensuel souhaité : <strong>{{loyer_mensuel}} FCFA</strong>. Date du mandat : <strong>{{date_mandat}}</strong>.</p><p>L'agence s'engage à diffuser les annonces, à organiser les visites et à présenter les candidatures de locataires solvables, en échange des honoraires convenus aux conditions particulières, dans le respect du droit des obligations applicable en Côte d'Ivoire.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_gestion_locative',
    name: "Accord de service de gestion locative par agence",
    category: 'immobilier', price: 6000, priceMax: 22000,
    description: "Convention de gestion locative complète d'un bien immobilier confiée à une agence spécialisée, incluant encaissement des loyers, entretien et suivi administratif.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 78,
    fieldsJson: F([
      { key: 'nom_proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'agence_gestion', label: "Agence de gestion locative", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien géré", type: 'text', required: true },
      { key: 'date_debut', label: "Date de prise en gestion", type: 'date', required: true },
      { key: 'taux_honoraires', label: "Taux des honoraires de gestion (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE GESTION LOCATIVE PAR AGENCE</h1><p><strong>{{nom_proprietaire}}</strong> confie à <strong>{{agence_gestion}}</strong> la gestion locative du bien situé à <strong>{{adresse_bien}}</strong>, à compter du <strong>{{date_debut}}</strong>.</p><p>Honoraires de gestion : <strong>{{taux_honoraires}}%</strong> des loyers effectivement encaissés.</p><p>L'agence assure l'encaissement des loyers, la délivrance des quittances, le suivi des réparations locatives et la gestion des relations avec le locataire en place ou entrant, dans le cadre du mandat de gestion conforme aux usages professionnels ivoiriens.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_estimation_ligne',
    name: "Accord de service d'estimation immobilière en ligne",
    category: 'immobilier', price: 3000, priceMax: 10000,
    description: "Convention de prestation d'estimation de valeur vénale d'un bien immobilier réalisée à distance via des outils numériques, avec rapport synthétique transmis par voie électronique.",
    templateType: 'pdf', classe: 'C', active: true, popularity: 56,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien à estimer", type: 'text', required: true },
      { key: 'date_commande', label: "Date de la commande", type: 'date', required: true },
      { key: 'email_livraison', label: "Email de livraison du rapport", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ESTIMATION IMMOBILIÈRE EN LIGNE</h1><p><strong>{{nom_client}}</strong> passe commande d'une estimation immobilière en ligne pour le bien situé à <strong>{{adresse_bien}}</strong>, le <strong>{{date_commande}}</strong>.</p><p>Le rapport d'estimation sera livré par voie électronique à l'adresse <strong>{{email_livraison}}</strong> dans un délai de quarante-huit (48) heures ouvrables.</p><p>Cette estimation indicative est fondée sur l'analyse comparative du marché immobilier local et ne saurait se substituer à une expertise immobilière contradictoire réalisée sur site.</p><p>Signature du client : __________________</p></div>`,
  },
  {
    code: 'diag_partenariat_notaire',
    name: "Accord de partenariat agence immobilière-notaire",
    category: 'immobilier', price: 5000, priceMax: 18000,
    description: "Convention de partenariat entre une agence immobilière et un office notarial pour la réalisation conjointe de transactions immobilières et le partage des diligences.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 69,
    fieldsJson: F([
      { key: 'nom_agence', label: "Nom de l'agence immobilière", type: 'text', required: true },
      { key: 'nom_notaire', label: "Nom de l'étude notariale", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'perimetre_geo', label: "Périmètre géographique", type: 'text', required: true },
      { key: 'modalites_partage', label: "Modalités de partage des diligences", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT AGENCE IMMOBILIÈRE – NOTAIRE</h1><p><strong>{{nom_agence}}</strong> et l'étude <strong>{{nom_notaire}}</strong> concluent le présent accord de partenariat le <strong>{{date_accord}}</strong>, pour le périmètre géographique de <strong>{{perimetre_geo}}</strong>.</p><p>Modalités de partage : {{modalites_partage}}</p><p>Les parties s'engagent à collaborer loyalement dans la réalisation des transactions immobilières, l'agence assurant la prospection et la négociation commerciale, et le notaire instrumentant les actes authentiques de vente conformément au droit ivoirien et aux actes uniformes OHADA.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_visite_virtuelle',
    name: "Accord de service de visite virtuelle immobilière (360)",
    category: 'immobilier', price: 4000, priceMax: 14000,
    description: "Convention de prestation pour la réalisation et la mise en ligne d'une visite virtuelle à 360 degrés d'un bien immobilier à des fins commerciales.",
    templateType: 'pdf', classe: 'C', active: true, popularity: 61,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'date_prise_vues', label: "Date de prise de vues", type: 'date', required: true },
      { key: 'prestataire_360', label: "Prestataire visite 360", type: 'text', required: true },
      { key: 'duree_hebergement', label: "Durée d'hébergement en ligne (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE VISITE VIRTUELLE IMMOBILIÈRE (360°)</h1><p><strong>{{nom_client}}</strong> mandate <strong>{{prestataire_360}}</strong> pour la réalisation d'une visite virtuelle à 360 degrés du bien situé à <strong>{{adresse_bien}}</strong>.</p><p>Date de prise de vues : <strong>{{date_prise_vues}}</strong>. Durée d'hébergement : <strong>{{duree_hebergement}} mois</strong>.</p><p>Le prestataire s'engage à livrer la visite virtuelle interactive sous quinze (15) jours ouvrables, hébergée sur sa plateforme et accessible via un lien URL transmis au client, avec les droits d'exploitation nécessaires à la diffusion commerciale du bien.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'diag_rapport_expertise',
    name: "Rapport d'expertise immobilière",
    category: 'immobilier', price: 12000, priceMax: 40000,
    description: "Document d'expertise immobilière rédigé par un expert agréé, exposant les méthodes d'évaluation retenues, les données de marché analysées et la valeur vénale ou locative estimée.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 88,
    fieldsJson: F([
      { key: 'expert_nom', label: "Nom et qualité de l'expert", type: 'text', required: true },
      { key: 'objet_expertise', label: "Objet de l'expertise", type: 'textarea', required: true },
      { key: 'adresse_bien', label: "Adresse du bien expertisé", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'valeur_estimee', label: "Valeur estimée (FCFA)", type: 'text', required: true },
      { key: 'methode_retenue', label: "Méthode d'évaluation retenue", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'EXPERTISE IMMOBILIÈRE</h1><p>Établi par <strong>{{expert_nom}}</strong> le <strong>{{date_rapport}}</strong>.</p><h2>Objet de l'expertise</h2><p>{{objet_expertise}}</p><h2>Bien expertisé</h2><p>{{adresse_bien}}</p><h2>Méthode d'évaluation</h2><p>{{methode_retenue}}</p><h2>Valeur estimée</h2><p><strong>{{valeur_estimee}} FCFA</strong></p><p>Ce rapport est établi conformément aux standards d'expertise immobilière reconnus en Côte d'Ivoire et aux principes du droit OHADA. Il est soumis au secret professionnel et ne peut être communiqué à des tiers sans l'accord du donneur d'ordre.</p><p>Signature de l'expert : __________________</p></div>`,
  },
  {
    code: 'diag_valorisation_patrimoine',
    name: "Plan de valorisation patrimoniale immobilière",
    category: 'immobilier', price: 9000, priceMax: 30000,
    description: "Document stratégique présentant un plan de valorisation d'un patrimoine immobilier, incluant recommandations de travaux, optimisation locative et projection de rentabilité.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 72,
    fieldsJson: F([
      { key: 'proprietaire', label: "Nom du propriétaire", type: 'text', required: true },
      { key: 'description_patrimoine', label: "Description du patrimoine immobilier", type: 'textarea', required: true },
      { key: 'date_plan', label: "Date d'établissement du plan", type: 'date', required: true },
      { key: 'conseil_immobilier', label: "Conseil immobilier rédacteur", type: 'text', required: true },
      { key: 'objectif_rentabilite', label: "Objectif de rentabilité (%)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>PLAN DE VALORISATION PATRIMONIALE IMMOBILIÈRE</h1><p>Établi pour <strong>{{proprietaire}}</strong> par <strong>{{conseil_immobilier}}</strong> le <strong>{{date_plan}}</strong>.</p><h2>Descriptif du patrimoine</h2><p>{{description_patrimoine}}</p><h2>Objectif de rentabilité</h2><p>{{objectif_rentabilite}} %</p><h2>Recommandations stratégiques</h2><p>Ce plan présente les axes de valorisation retenus : travaux d'amélioration, optimisation locative, arbitrages patrimoniaux et projection financière sur cinq (5) ans, dans le respect des règles fiscales et juridiques applicables en Côte d'Ivoire.</p><p>Signature du conseil : __________________</p></div>`,
  },
  {
    code: 'diag_charte_transaction',
    name: "Charte de la transaction immobilière transparente",
    category: 'immobilier', price: 4000, priceMax: 13000,
    description: "Charte éthique et déontologique signée par les parties à une transaction immobilière, garantissant transparence, loyauté et respect des règles professionnelles OHADA.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 57,
    fieldsJson: F([
      { key: 'agence_signataire', label: "Agence signataire", type: 'text', required: true },
      { key: 'vendeur', label: "Vendeur", type: 'text', required: true },
      { key: 'acquereur', label: "Acquéreur", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE LA TRANSACTION IMMOBILIÈRE TRANSPARENTE</h1><p>Signée entre <strong>{{agence_signataire}}</strong>, <strong>{{vendeur}}</strong> et <strong>{{acquereur}}</strong> le <strong>{{date_signature}}</strong>.</p><p>Les signataires s'engagent à respecter les principes suivants : sincérité des informations communiquées sur le bien, absence de pratiques discriminatoires, loyauté dans la négociation, divulgation de tout conflit d'intérêts, et règlement amiable des différends avant tout recours judiciaire, conformément aux valeurs professionnelles de l'immobilier ivoirien et aux exigences de l'OHADA en matière de bonne foi contractuelle.</p><p>Signatures : __________________ __________________ __________________</p></div>`,
  },

  // ── 25 Copropriété / Syndic (préfixe cop2_) ──
  {
    code: 'cop2_contrat_syndic',
    name: "Contrat de syndic de copropriété (mandat)",
    category: 'immobilier', price: 8000, priceMax: 28000,
    description: "Contrat de mandat de gestion et d'administration d'une copropriété confié à un syndic professionnel, régissant ses missions, ses honoraires et ses obligations envers le syndicat des copropriétaires.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 86,
    fieldsJson: F([
      { key: 'syndicat_cop', label: "Syndicat des copropriétaires", type: 'text', required: true },
      { key: 'nom_syndic', label: "Nom du syndic professionnel", type: 'text', required: true },
      { key: 'adresse_immeuble', label: "Adresse de l'immeuble", type: 'text', required: true },
      { key: 'date_debut', label: "Date de prise de fonction", type: 'date', required: true },
      { key: 'honoraires_annuels', label: "Honoraires annuels (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SYNDIC DE COPROPRIÉTÉ (MANDAT)</h1><p>Le syndicat des copropriétaires de l'immeuble sis <strong>{{adresse_immeuble}}</strong>, représenté par son conseil syndical, mandate <strong>{{nom_syndic}}</strong> pour assurer la gestion et l'administration de la copropriété, à compter du <strong>{{date_debut}}</strong> pour une durée de <strong>{{duree_contrat}} an(s)</strong>.</p><p>Honoraires annuels : <strong>{{honoraires_annuels}} FCFA</strong>.</p><p>Le syndic accomplit toutes les diligences prévues par le règlement de copropriété et les délibérations de l'assemblée générale, dans le respect des règles de gestion des biens collectifs conformes au droit ivoirien et aux principes OHADA.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_reglement_copro',
    name: "Règlement de copropriété (immeuble collectif)",
    category: 'immobilier', price: 12000, priceMax: 40000,
    description: "Document fondateur d'une copropriété définissant la répartition des parties communes et privatives, les droits et obligations des copropriétaires et les règles de vie collective.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 90,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom ou dénomination de l'immeuble", type: 'text', required: true },
      { key: 'adresse_immeuble', label: "Adresse de l'immeuble", type: 'text', required: true },
      { key: 'promoteur_fondateur', label: "Promoteur / Fondateur", type: 'text', required: true },
      { key: 'date_etablissement', label: "Date d'établissement", type: 'date', required: true },
      { key: 'nombre_lots', label: "Nombre total de lots", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RÈGLEMENT DE COPROPRIÉTÉ</h1><h2>Immeuble : {{nom_immeuble}}</h2><p>Adresse : <strong>{{adresse_immeuble}}</strong> – {{nombre_lots}} lots. Établi par <strong>{{promoteur_fondateur}}</strong> le <strong>{{date_etablissement}}</strong>.</p><h2>Article 1 – Objet</h2><p>Le présent règlement régit l'organisation et le fonctionnement de la copropriété, la destination de l'immeuble, la jouissance et l'administration des parties communes, ainsi que les droits et obligations de chaque copropriétaire, conformément aux dispositions légales ivoiriennes et aux principes de l'Acte uniforme OHADA sur les sociétés.</p><h2>Article 2 – Parties communes et privatives</h2><p>Sont parties communes : le sol, les fondations, les gros murs, les toitures, les escaliers, couloirs et locaux communs. Chaque lot privatif est délimité par le plan annexé au présent règlement.</p><h2>Article 3 – Charges</h2><p>Les charges générales sont réparties entre les copropriétaires proportionnellement aux tantièmes figurant à l'état descriptif de division annexé.</p><p>Signatures : __________________</p></div>`,
  },
  {
    code: 'cop2_etat_descriptif',
    name: "État descriptif de division (lots de copropriété)",
    category: 'immobilier', price: 7000, priceMax: 24000,
    description: "Document notarial ou para-notarial décrivant et numérotant les lots d'une copropriété, avec indication des millièmes de parties communes attachés à chaque lot.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 75,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'adresse_immeuble', label: "Adresse de l'immeuble", type: 'text', required: true },
      { key: 'redacteur', label: "Rédacteur de l'acte", type: 'text', required: true },
      { key: 'date_acte', label: "Date de l'acte", type: 'date', required: true },
      { key: 'detail_lots', label: "Détail des lots (numéros, surfaces, tantièmes)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ÉTAT DESCRIPTIF DE DIVISION</h1><h2>Immeuble : {{nom_immeuble}} – {{adresse_immeuble}}</h2><p>Établi par <strong>{{redacteur}}</strong> le <strong>{{date_acte}}</strong>.</p><h2>Description des lots</h2><p>{{detail_lots}}</p><p>Cet état descriptif de division constitue la pièce fondatrice de la répartition des droits entre copropriétaires. Toute modification requiert un vote en assemblée générale et une mise à jour par acte notarié, conformément au droit ivoirien applicable à la copropriété.</p><p>Signature du rédacteur : __________________</p></div>`,
  },
  {
    code: 'cop2_pv_ag',
    name: "Procès-verbal d'assemblée générale de copropriété",
    category: 'immobilier', price: 5000, priceMax: 17000,
    description: "Procès-verbal officiel des délibérations de l'assemblée générale des copropriétaires, constatant les résolutions adoptées et les votes exprimés.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 83,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_ag', label: "Date de l'assemblée", type: 'date', required: true },
      { key: 'president_seance', label: "Président de séance", type: 'text', required: true },
      { key: 'nombre_presents', label: "Nombre de copropriétaires présents/représentés", type: 'text', required: true },
      { key: 'resolutions', label: "Résolutions adoptées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÈS-VERBAL D'ASSEMBLÉE GÉNÉRALE DE COPROPRIÉTÉ</h1><p>Immeuble : <strong>{{nom_immeuble}}</strong>. Assemblée tenue le <strong>{{date_ag}}</strong>, présidée par <strong>{{president_seance}}</strong>. Nombre de copropriétaires présents ou représentés : <strong>{{nombre_presents}}</strong>.</p><h2>Résolutions adoptées</h2><p>{{resolutions}}</p><p>Le présent procès-verbal est signé par le président de séance et le secrétaire de l'assemblée, et notifié à chaque copropriétaire dans les conditions prévues par le règlement de copropriété et les dispositions légales ivoiriennes applicables.</p><p>Président : __________________ Secrétaire : __________________</p></div>`,
  },
  {
    code: 'cop2_vote_travaux',
    name: "Accord de vote résolution travaux en copropriété",
    category: 'immobilier', price: 4500, priceMax: 15000,
    description: "Document formalisant l'accord des copropriétaires sur une résolution de travaux votée en assemblée générale, avec indication des modalités de financement et d'exécution.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_vote', label: "Date du vote", type: 'date', required: true },
      { key: 'description_travaux', label: "Description des travaux votés", type: 'textarea', required: true },
      { key: 'montant_vote', label: "Montant global voté (FCFA)", type: 'text', required: true },
      { key: 'entreprise_retenue', label: "Entreprise retenue", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE VOTE RÉSOLUTION TRAVAUX EN COPROPRIÉTÉ</h1><p>L'assemblée générale de la copropriété <strong>{{nom_immeuble}}</strong>, réunie le <strong>{{date_vote}}</strong>, a voté à la majorité requise les travaux suivants :</p><p>{{description_travaux}}</p><p>Montant global voté : <strong>{{montant_vote}} FCFA</strong>. Entreprise retenue : <strong>{{entreprise_retenue}}</strong>.</p><p>Le syndic est mandaté pour signer le contrat de travaux et appeler les fonds correspondants auprès des copropriétaires selon la clé de répartition du règlement de copropriété.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_autorisation_travaux_privatifs',
    name: "Accord d'autorisation de travaux dans un lot privatif",
    category: 'immobilier', price: 4000, priceMax: 13000,
    description: "Autorisation délivrée par le syndicat des copropriétaires à un copropriétaire souhaitant réaliser des travaux dans son lot privatif affectant les parties communes ou l'aspect extérieur.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([
      { key: 'nom_copro', label: "Nom du copropriétaire demandeur", type: 'text', required: true },
      { key: 'numero_lot', label: "Numéro du lot privatif", type: 'text', required: true },
      { key: 'description_travaux', label: "Description des travaux projetés", type: 'textarea', required: true },
      { key: 'date_autorisation', label: "Date de l'autorisation", type: 'date', required: true },
      { key: 'conditions', label: "Conditions et réserves", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD D'AUTORISATION DE TRAVAUX DANS UN LOT PRIVATIF</h1><p>Le syndicat des copropriétaires autorise <strong>{{nom_copro}}</strong>, propriétaire du lot N° <strong>{{numero_lot}}</strong>, à réaliser les travaux ci-après décrits : <em>{{description_travaux}}</em>.</p><p>Date d'autorisation : <strong>{{date_autorisation}}</strong>.</p><p>Conditions et réserves : {{conditions}}</p><p>Le copropriétaire s'engage à exécuter les travaux dans le respect du règlement de copropriété, à ne pas porter atteinte aux parties communes et à remettre les lieux en état en cas de dommages, conformément aux obligations légales applicables en Côte d'Ivoire.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_budget_charges',
    name: "Accord de fixation des charges communes (budget)",
    category: 'immobilier', price: 5000, priceMax: 17000,
    description: "Document formalisant l'approbation par l'assemblée générale du budget prévisionnel de la copropriété et les modalités d'appel des charges communes aux copropriétaires.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 76,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'exercice', label: "Exercice budgétaire (année)", type: 'text', required: true },
      { key: 'date_vote', label: "Date de vote du budget", type: 'date', required: true },
      { key: 'montant_budget', label: "Montant total du budget (FCFA)", type: 'text', required: true },
      { key: 'detail_postes', label: "Détail des principaux postes de charges", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FIXATION DES CHARGES COMMUNES (BUDGET)</h1><p>L'assemblée générale de la copropriété <strong>{{nom_immeuble}}</strong>, réunie le <strong>{{date_vote}}</strong>, approuve le budget prévisionnel de l'exercice <strong>{{exercice}}</strong> pour un montant total de <strong>{{montant_budget}} FCFA</strong>.</p><h2>Principaux postes de charges</h2><p>{{detail_postes}}</p><p>Le syndic appellera les charges trimestriellement selon la clé de répartition du règlement de copropriété. Tout copropriétaire peut consulter les comptes au siège du syndic sur rendez-vous.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_recouvrement_charges',
    name: "Accord de recouvrement de charges impayées en copropriété",
    category: 'immobilier', price: 5000, priceMax: 18000,
    description: "Accord amiable entre le syndicat des copropriétaires et un copropriétaire débiteur pour l'apurement des charges impayées, avec échéancier de règlement.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'nom_debiteur', label: "Nom du copropriétaire débiteur", type: 'text', required: true },
      { key: 'montant_du', label: "Montant total dû (FCFA)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'echeancier', label: "Échéancier de remboursement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RECOUVREMENT DE CHARGES IMPAYÉES EN COPROPRIÉTÉ</h1><p>Entre le syndicat de copropriété de <strong>{{nom_immeuble}}</strong> et <strong>{{nom_debiteur}}</strong>, il est convenu le <strong>{{date_accord}}</strong> un plan d'apurement des charges impayées d'un montant de <strong>{{montant_du}} FCFA</strong>.</p><h2>Échéancier</h2><p>{{echeancier}}</p><p>En cas de non-respect de l'échéancier, le syndicat se réserve le droit d'engager toute procédure judiciaire de recouvrement prévue par le droit ivoirien et les dispositions de l'Acte uniforme OHADA sur les voies d'exécution.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_creation_syndicat',
    name: "Accord de création du syndicat des copropriétaires",
    category: 'immobilier', price: 7000, priceMax: 24000,
    description: "Acte constitutif du syndicat des copropriétaires d'un immeuble, définissant son objet, son siège social et les modalités initiales de fonctionnement.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 68,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'adresse_immeuble', label: "Adresse de l'immeuble", type: 'text', required: true },
      { key: 'date_creation', label: "Date de création", type: 'date', required: true },
      { key: 'nombre_copro', label: "Nombre de copropriétaires fondateurs", type: 'text', required: true },
      { key: 'premier_syndic', label: "Premier syndic désigné", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CRÉATION DU SYNDICAT DES COPROPRIÉTAIRES</h1><p>Les copropriétaires de l'immeuble <strong>{{nom_immeuble}}</strong>, sis <strong>{{adresse_immeuble}}</strong>, au nombre de <strong>{{nombre_copro}}</strong>, créent ce jour <strong>{{date_creation}}</strong> le syndicat des copropriétaires.</p><p>Le syndicat a pour objet la conservation de l'immeuble et l'administration des parties communes. Il désigne <strong>{{premier_syndic}}</strong> comme premier syndic.</p><p>Les copropriétaires s'engagent à respecter le règlement de copropriété et à participer aux assemblées générales, conformément au droit ivoirien de la copropriété et aux actes uniformes OHADA applicables.</p><p>Signatures des copropriétaires fondateurs : __________________</p></div>`,
  },
  {
    code: 'cop2_syndic_benevole',
    name: "Accord de syndicat bénévole (petite copropriété)",
    category: 'immobilier', price: 4000, priceMax: 13000,
    description: "Accord désignant un copropriétaire bénévole comme syndic non professionnel d'une petite copropriété, avec définition de ses missions et de ses prérogatives limitées.",
    templateType: 'pdf', classe: 'C', active: true, popularity: 59,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'syndic_benevole', label: "Nom du syndic bénévole", type: 'text', required: true },
      { key: 'lot_syndic', label: "Numéro de lot du syndic bénévole", type: 'text', required: true },
      { key: 'date_designation', label: "Date de désignation", type: 'date', required: true },
      { key: 'duree_mandat', label: "Durée du mandat (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SYNDICAT BÉNÉVOLE (PETITE COPROPRIÉTÉ)</h1><p>Les copropriétaires de l'immeuble <strong>{{nom_immeuble}}</strong> désignent <strong>{{syndic_benevole}}</strong> (lot N° <strong>{{lot_syndic}}</strong>) comme syndic bénévole non professionnel, à compter du <strong>{{date_designation}}</strong> pour une durée de <strong>{{duree_mandat}} mois</strong>.</p><p>Le syndic bénévole assure à titre gratuit la gestion courante de la copropriété (appel de charges, paiement des fournisseurs, tenue des assemblées générales) dans les limites des décisions collectives des copropriétaires.</p><p>Signatures : __________________</p></div>`,
  },
  {
    code: 'cop2_conseil_syndical',
    name: "Accord de conseil syndical (comité)",
    category: 'immobilier', price: 4000, priceMax: 13000,
    description: "Document constitutif du conseil syndical d'une copropriété, désignant ses membres, définissant ses attributions de contrôle et d'assistance au syndic.",
    templateType: 'pdf', classe: 'C', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'membres_conseil', label: "Membres du conseil syndical", type: 'textarea', required: true },
      { key: 'date_designation', label: "Date de désignation", type: 'date', required: true },
      { key: 'president_conseil', label: "Président du conseil syndical", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONSEIL SYNDICAL (COMITÉ)</h1><p>L'assemblée générale de la copropriété <strong>{{nom_immeuble}}</strong>, réunie le <strong>{{date_designation}}</strong>, désigne le conseil syndical composé des membres suivants :</p><p>{{membres_conseil}}</p><p>Président du conseil syndical : <strong>{{president_conseil}}</strong>.</p><p>Le conseil syndical assiste et contrôle le syndic dans sa gestion, peut examiner les pièces comptables et formuler des avis sur toute question intéressant la copropriété, conformément aux dispositions légales ivoiriennes applicables.</p><p>Signatures : __________________</p></div>`,
  },
  {
    code: 'cop2_delegation_pouvoir_ag',
    name: "Accord de délégation de pouvoir en AG de copropriété",
    category: 'immobilier', price: 3000, priceMax: 10000,
    description: "Formulaire de délégation de pouvoir permettant à un copropriétaire empêché de confier son droit de vote à un mandataire pour l'assemblée générale.",
    templateType: 'pdf', classe: 'C', active: true, popularity: 71,
    fieldsJson: F([
      { key: 'nom_mandant', label: "Nom du copropriétaire mandant", type: 'text', required: true },
      { key: 'numero_lot_mandant', label: "Numéro de lot du mandant", type: 'text', required: true },
      { key: 'nom_mandataire', label: "Nom du mandataire", type: 'text', required: true },
      { key: 'date_ag', label: "Date de l'assemblée générale", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DÉLÉGATION DE POUVOIR EN AG DE COPROPRIÉTÉ</h1><p><strong>{{nom_mandant}}</strong>, copropriétaire du lot N° <strong>{{numero_lot_mandant}}</strong>, donne pouvoir à <strong>{{nom_mandataire}}</strong> de le représenter avec tous ses droits de vote à l'assemblée générale du <strong>{{date_ag}}</strong>.</p><p>Le mandataire exercera les droits de vote du mandant sur toutes les résolutions inscrites à l'ordre du jour, selon sa propre appréciation et dans l'intérêt bien compris du mandant.</p><p>Cette délégation est établie conformément aux règles de représentation applicables aux assemblées de copropriétaires en Côte d'Ivoire.</p><p>Signature du mandant : __________________</p></div>`,
  },
  {
    code: 'cop2_etat_lieux_communs',
    name: "Accord d'état des lieux parties communes",
    category: 'immobilier', price: 4000, priceMax: 14000,
    description: "Procès-verbal d'état des lieux des parties communes d'une copropriété, dressé contradictoirement pour constater leur état et prévenir tout litige entre le syndicat et les copropriétaires.",
    templateType: 'pdf', classe: 'C', active: true, popularity: 58,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_etat_lieux', label: "Date de l'état des lieux", type: 'date', required: true },
      { key: 'redacteur', label: "Rédacteur / Huissier", type: 'text', required: true },
      { key: 'description_etat', label: "Description de l'état des parties communes", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'ÉTAT DES LIEUX PARTIES COMMUNES</h1><p>État des lieux des parties communes de l'immeuble <strong>{{nom_immeuble}}</strong>, dressé le <strong>{{date_etat_lieux}}</strong> par <strong>{{redacteur}}</strong>.</p><h2>État constaté</h2><p>{{description_etat}}</p><p>Cet état des lieux est annexé au registre de la copropriété et servira de référence lors de tout état des lieux ultérieur ou en cas de litige portant sur la dégradation des parties communes.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_travaux_urgence',
    name: "Accord de travaux d'urgence (syndic provisoire)",
    category: 'immobilier', price: 5000, priceMax: 17000,
    description: "Accord autorisant le syndic à engager des travaux d'urgence nécessaires à la conservation de l'immeuble sans attendre la convocation d'une assemblée générale.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 66,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'nom_syndic', label: "Nom du syndic", type: 'text', required: true },
      { key: 'date_decision', label: "Date de la décision", type: 'date', required: true },
      { key: 'nature_urgence', label: "Nature de l'urgence", type: 'textarea', required: true },
      { key: 'montant_estime', label: "Montant estimé des travaux (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRAVAUX D'URGENCE (SYNDIC PROVISOIRE)</h1><p>Le syndic <strong>{{nom_syndic}}</strong> de l'immeuble <strong>{{nom_immeuble}}</strong> constate le <strong>{{date_decision}}</strong> une situation d'urgence nécessitant des travaux immédiats :</p><p><strong>{{nature_urgence}}</strong></p><p>Montant estimé : <strong>{{montant_estime}} FCFA</strong>.</p><p>En application de ses prérogatives de syndic et conformément aux dispositions légales ivoiriennes, le syndic engage les travaux conservatoires nécessaires et convoque une assemblée générale extraordinaire dans les plus brefs délais pour ratification.</p><p>Signature du syndic : __________________</p></div>`,
  },
  {
    code: 'cop2_ravalement_facade',
    name: "Accord de ravalement de facade (copropriété)",
    category: 'immobilier', price: 6000, priceMax: 20000,
    description: "Accord de copropriété autorisant et organisant le ravalement de la facade de l'immeuble, avec sélection de l'entreprise, calendrier et modalités financières.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 72,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_vote', label: "Date de vote en AG", type: 'date', required: true },
      { key: 'entreprise_ravalement', label: "Entreprise de ravalement retenue", type: 'text', required: true },
      { key: 'montant_marche', label: "Montant du marché (FCFA)", type: 'text', required: true },
      { key: 'delai_travaux', label: "Délai d'exécution (semaines)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RAVALEMENT DE FACADE (COPROPRIÉTÉ)</h1><p>L'assemblée générale de la copropriété <strong>{{nom_immeuble}}</strong>, réunie le <strong>{{date_vote}}</strong>, vote à la majorité requise le ravalement de la facade et retient l'offre de <strong>{{entreprise_ravalement}}</strong>.</p><p>Montant du marché : <strong>{{montant_marche}} FCFA</strong>. Délai d'exécution : <strong>{{delai_travaux}} semaines</strong>.</p><p>Le syndic est mandaté pour signer le contrat d'entreprise, superviser l'exécution des travaux et procéder à la réception des ouvrages dans les conditions prévues par le droit ivoirien de la construction.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_renovation_toiture',
    name: "Accord de rénovation toiture (vote spécial)",
    category: 'immobilier', price: 6000, priceMax: 22000,
    description: "Accord de copropriété résultant d'un vote spécial en assemblée générale pour la rénovation complète ou partielle de la toiture de l'immeuble.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 69,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_vote', label: "Date du vote spécial", type: 'date', required: true },
      { key: 'type_renovation', label: "Type de rénovation (totale / partielle)", type: 'text', required: true },
      { key: 'entreprise_retenue', label: "Entreprise retenue", type: 'text', required: true },
      { key: 'budget_vote', label: "Budget voté (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉNOVATION TOITURE (VOTE SPÉCIAL)</h1><p>L'assemblée générale extraordinaire de la copropriété <strong>{{nom_immeuble}}</strong>, réunie le <strong>{{date_vote}}</strong>, vote à la majorité qualifiée requise la rénovation <strong>{{type_renovation}}</strong> de la toiture, confiée à <strong>{{entreprise_retenue}}</strong> pour un budget de <strong>{{budget_vote}} FCFA</strong>.</p><p>Le financement sera assuré par appel de fonds exceptionnel auprès des copropriétaires selon la clé de répartition du règlement de copropriété. Le syndic veillera à la constitution des garanties d'exécution requises.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_ascenseur',
    name: "Accord d'installation d'ascenseur en copropriété",
    category: 'immobilier', price: 7000, priceMax: 25000,
    description: "Accord de copropriété autorisant l'installation d'un ascenseur dans les parties communes, avec définition des modalités techniques, financières et de maintenance.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_vote', label: "Date du vote en AG", type: 'date', required: true },
      { key: 'fournisseur_ascenseur', label: "Fournisseur / installateur", type: 'text', required: true },
      { key: 'cout_installation', label: "Coût d'installation (FCFA)", type: 'text', required: true },
      { key: 'cout_maintenance_annuel', label: "Coût de maintenance annuel (FCFA)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD D'INSTALLATION D'ASCENSEUR EN COPROPRIÉTÉ</h1><p>L'assemblée générale de la copropriété <strong>{{nom_immeuble}}</strong>, réunie le <strong>{{date_vote}}</strong>, vote à la majorité requise l'installation d'un ascenseur par <strong>{{fournisseur_ascenseur}}</strong>, pour un coût de <strong>{{cout_installation}} FCFA</strong>.</p><p>Coût de maintenance annuel estimé : <strong>{{cout_maintenance_annuel}} FCFA</strong>.</p><p>Le financement est assuré par appel de fonds auprès des copropriétaires. La charge de maintenance est intégrée au budget annuel. L'ascenseur, une fois installé, devient partie commune de l'immeuble sous la responsabilité du syndicat.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_panneaux_solaires',
    name: "Accord de pose de panneaux solaires parties communes",
    category: 'immobilier', price: 6000, priceMax: 20000,
    description: "Accord de copropriété autorisant l'installation de panneaux solaires photovoltaïques sur les parties communes (toiture, terrasse) pour la production d'électricité collective.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 64,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_vote', label: "Date du vote", type: 'date', required: true },
      { key: 'installateur', label: "Installateur solaire", type: 'text', required: true },
      { key: 'puissance_kwc', label: "Puissance installée (kWc)", type: 'text', required: true },
      { key: 'cout_projet', label: "Coût total du projet (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE POSE DE PANNEAUX SOLAIRES PARTIES COMMUNES</h1><p>L'assemblée générale de la copropriété <strong>{{nom_immeuble}}</strong>, réunie le <strong>{{date_vote}}</strong>, vote l'installation de panneaux solaires d'une puissance de <strong>{{puissance_kwc}} kWc</strong> par <strong>{{installateur}}</strong>, pour un coût de <strong>{{cout_projet}} FCFA</strong>.</p><p>L'énergie produite sera affectée aux parties communes (éclairage, pompes, ascenseur) avec déduction sur les charges collectives. Le surplus éventuel pourra être revendu dans le cadre des dispositions légales ivoiriennes sur les énergies renouvelables.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_maintenance_ascenseur',
    name: "Accord de contrat de maintenance ascenseur (copropriété)",
    category: 'immobilier', price: 5000, priceMax: 17000,
    description: "Contrat de maintenance préventive et corrective de l'ascenseur d'une copropriété, signé entre le syndicat des copropriétaires et un prestataire technique agréé.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 61,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire de maintenance", type: 'text', required: true },
      { key: 'date_contrat', label: "Date de signature du contrat", type: 'date', required: true },
      { key: 'cout_annuel', label: "Coût annuel de maintenance (FCFA)", type: 'text', required: true },
      { key: 'frequence_visites', label: "Fréquence des visites préventives", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONTRAT DE MAINTENANCE ASCENSEUR (COPROPRIÉTÉ)</h1><p>Le syndicat de copropriété de <strong>{{nom_immeuble}}</strong> confie à <strong>{{prestataire}}</strong> la maintenance préventive et corrective de l'ascenseur de l'immeuble, le <strong>{{date_contrat}}</strong>.</p><p>Coût annuel : <strong>{{cout_annuel}} FCFA</strong>. Fréquence des visites préventives : <strong>{{frequence_visites}}</strong>.</p><p>Le prestataire garantit une intervention curative sous vingt-quatre (24) heures en cas de panne, et fournit un rapport d'intervention après chaque visite. Il respecte les normes de sécurité des ascenseurs applicables en Côte d'Ivoire.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_nettoyage_communs',
    name: "Accord de contrat de nettoyage parties communes",
    category: 'immobilier', price: 4000, priceMax: 13000,
    description: "Contrat de prestation de nettoyage régulier des parties communes d'une copropriété (halls, escaliers, couloirs, abords) conclu entre le syndicat et une société de nettoyage.",
    templateType: 'pdf', classe: 'C', active: true, popularity: 74,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'societe_nettoyage', label: "Société de nettoyage", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de la prestation", type: 'date', required: true },
      { key: 'frequence', label: "Fréquence de nettoyage", type: 'text', required: true },
      { key: 'montant_mensuel', label: "Montant mensuel (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONTRAT DE NETTOYAGE PARTIES COMMUNES</h1><p>Le syndicat de copropriété de <strong>{{nom_immeuble}}</strong> confie à <strong>{{societe_nettoyage}}</strong> le nettoyage des parties communes à compter du <strong>{{date_debut}}</strong>.</p><p>Fréquence : <strong>{{frequence}}</strong>. Montant mensuel : <strong>{{montant_mensuel}} FCFA</strong>.</p><p>La société de nettoyage s'engage à utiliser des produits adaptés, à respecter les horaires convenus et à affecter un personnel formé et identifiable. Un cahier d'entretien est tenu à jour et mis à la disposition du syndic.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_gardiennage',
    name: "Accord de contrat de gardiennage immeuble",
    category: 'immobilier', price: 5000, priceMax: 17000,
    description: "Contrat de prestation de gardiennage et de surveillance d'un immeuble en copropriété, définissant les missions du gardien, ses horaires et les conditions de son intervention.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 77,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'societe_gardiennage', label: "Société de gardiennage", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de la mission", type: 'date', required: true },
      { key: 'horaires', label: "Horaires de gardiennage", type: 'text', required: true },
      { key: 'cout_mensuel', label: "Coût mensuel (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONTRAT DE GARDIENNAGE IMMEUBLE</h1><p>Le syndicat de copropriété de <strong>{{nom_immeuble}}</strong> confie à <strong>{{societe_gardiennage}}</strong> le gardiennage et la surveillance de l'immeuble à compter du <strong>{{date_debut}}</strong>.</p><p>Horaires : <strong>{{horaires}}</strong>. Coût mensuel : <strong>{{cout_mensuel}} FCFA</strong>.</p><p>Le gardien assure le contrôle des accès, la surveillance des parties communes, la levée du courrier et la remontée des informations relatives à la sécurité de l'immeuble. Il agit sous l'autorité du syndic conformément aux dispositions légales ivoiriennes relatives aux prestataires de sécurité.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_assurance_immeuble',
    name: "Accord de souscription assurance multirisque immeuble",
    category: 'immobilier', price: 5000, priceMax: 18000,
    description: "Accord encadrant la souscription par le syndicat des copropriétaires d'un contrat d'assurance multirisque immeuble couvrant les parties communes contre les principaux sinistres.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 80,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'compagnie_assurance', label: "Compagnie d'assurance", type: 'text', required: true },
      { key: 'date_souscription', label: "Date de souscription", type: 'date', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle (FCFA)", type: 'text', required: true },
      { key: 'garanties_principales', label: "Principales garanties souscrites", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SOUSCRIPTION ASSURANCE MULTIRISQUE IMMEUBLE</h1><p>Le syndicat de copropriété de <strong>{{nom_immeuble}}</strong> souscrit auprès de <strong>{{compagnie_assurance}}</strong> un contrat d'assurance multirisque immeuble le <strong>{{date_souscription}}</strong>, moyennant une prime annuelle de <strong>{{prime_annuelle}} FCFA</strong>.</p><h2>Garanties principales</h2><p>{{garanties_principales}}</p><p>Ce contrat couvre les parties communes de l'immeuble. Chaque copropriétaire reste tenu de souscrire une assurance complémentaire pour ses parties privatives, conformément aux obligations légales ivoiriennes et au code des assurances de la Conférence Interafricaine des Marchés d'Assurances (CIMA).</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_rapport_annuel_syndic',
    name: "Rapport annuel du syndic de copropriété",
    category: 'immobilier', price: 6000, priceMax: 20000,
    description: "Rapport annuel présenté par le syndic à l'assemblée générale, rendant compte de sa gestion, de la situation financière de la copropriété et des travaux réalisés.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 79,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'nom_syndic', label: "Nom du syndic", type: 'text', required: true },
      { key: 'exercice', label: "Exercice concerné (année)", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'bilan_financier', label: "Bilan financier de l'exercice", type: 'textarea', required: true },
      { key: 'travaux_realises', label: "Travaux réalisés durant l'exercice", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT ANNUEL DU SYNDIC DE COPROPRIÉTÉ</h1><h2>Immeuble : {{nom_immeuble}} – Exercice {{exercice}}</h2><p>Rapport établi par <strong>{{nom_syndic}}</strong> le <strong>{{date_rapport}}</strong>.</p><h2>Bilan financier</h2><p>{{bilan_financier}}</p><h2>Travaux réalisés</h2><p>{{travaux_realises}}</p><p>Ce rapport est soumis à l'approbation de l'assemblée générale annuelle. Il retrace fidèlement la gestion de la copropriété durant l'exercice écoulé, dans le respect des obligations comptables et de transparence imposées au syndic par le droit ivoirien applicable.</p><p>Signature du syndic : __________________</p></div>`,
  },
  {
    code: 'cop2_plan_travaux_pluriannuel',
    name: "Plan de travaux pluriannuel de copropriété",
    category: 'immobilier', price: 8000, priceMax: 28000,
    description: "Document de planification des travaux à réaliser sur les parties communes d'une copropriété sur une période de cinq à dix ans, avec estimation budgétaire et ordre de priorité.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 73,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'redacteur', label: "Rédacteur du plan", type: 'text', required: true },
      { key: 'date_plan', label: "Date d'établissement du plan", type: 'date', required: true },
      { key: 'horizon_plan', label: "Horizon du plan (années)", type: 'text', required: true },
      { key: 'travaux_prioritaires', label: "Travaux prioritaires identifiés", type: 'textarea', required: true },
      { key: 'budget_total_estime', label: "Budget total estimé (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE TRAVAUX PLURIANNUEL DE COPROPRIÉTÉ</h1><h2>Immeuble : {{nom_immeuble}}</h2><p>Établi par <strong>{{redacteur}}</strong> le <strong>{{date_plan}}</strong> pour un horizon de <strong>{{horizon_plan}} ans</strong>.</p><h2>Travaux prioritaires</h2><p>{{travaux_prioritaires}}</p><h2>Budget total estimé</h2><p><strong>{{budget_total_estime}} FCFA</strong></p><p>Ce plan pluriannuel est adopté par l'assemblée générale et constitue le document de référence pour la programmation des appels de fonds exceptionnels. Il est révisable chaque année en fonction de l'évolution de l'état du bâti et des contraintes financières du syndicat.</p><p>Signatures : __________________ __________________</p></div>`,
  },
  {
    code: 'cop2_charte_bonne_gestion',
    name: "Charte de bonne gestion des copropriétés en Afrique",
    category: 'immobilier', price: 4500, priceMax: 15000,
    description: "Charte de gouvernance et de bonnes pratiques adoptée par un syndicat de copropriétaires, promouvant la transparence, la participation citoyenne et le respect des obligations OHADA.",
    templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'nom_immeuble', label: "Nom de l'immeuble", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption de la charte", type: 'date', required: true },
      { key: 'nombre_adherents', label: "Nombre de copropriétaires signataires", type: 'text', required: true },
      { key: 'valeurs_retenues', label: "Valeurs et engagements retenus", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE BONNE GESTION DES COPROPRIÉTÉS EN AFRIQUE</h1><p>Adoptée le <strong>{{date_adoption}}</strong> par les <strong>{{nombre_adherents}}</strong> copropriétaires de l'immeuble <strong>{{nom_immeuble}}</strong>.</p><h2>Engagements collectifs</h2><p>{{valeurs_retenues}}</p><p>Les signataires s'engagent à respecter les principes de bonne gouvernance, de transparence financière, de participation active aux assemblées générales et de règlement amiable des conflits. Cette charte s'inscrit dans les valeurs communautaires africaines et les exigences de l'Acte uniforme OHADA applicable aux copropriétés, pour une gestion harmonieuse et durable du patrimoine immobilier commun.</p><p>Signatures des copropriétaires : __________________</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 83b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
