import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── PÉTROLE / GAZ (25) ───────────────────────────────────────────────────
  {
    code: 'petr_cpp',
    name: "Contrat de Partage de Production Pétrolière (CPP)",
    category: 'agro_environnement',
    price: 25000,
    priceMax: 80000,
    description: "Contrat de partage de production pétrolière conforme au droit OHADA et à la réglementation ivoirienne du secteur pétrolier amont.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'nom_societe', label: "Nom de la société pétrolière", type: 'text', required: true },
      { key: 'bloc_petrolier', label: "Identification du bloc pétrolier", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature du contrat", type: 'date', required: true },
      { key: 'duree_exploration', label: "Durée de la phase d'exploration (années)", type: 'text', required: true },
      { key: 'quote_part_etat', label: "Quote-part de l'État (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PARTAGE DE PRODUCTION PÉTROLIÈRE</h1><p>Entre la République de Côte d"Ivoire, représentée par le Ministère des Mines et du Pétrole, et la société <strong>{{nom_societe}}</strong>, pour le bloc pétrolier <strong>{{bloc_petrolier}}</strong>.</p><p>Date de signature : {{date_signature}}. Durée de la phase d"exploration : {{duree_exploration}} ans. Quote-part de l"État : {{quote_part_etat}} %.</p><p>Les parties conviennent que la production pétrolière sera partagée conformément aux dispositions du Code Pétrolier ivoirien et aux termes du présent contrat.</p></div>`,
  },
  {
    code: 'petr_concession_exploration',
    name: "Accord de Concession d'Exploration Pétrolière",
    category: 'agro_environnement',
    price: 20000,
    priceMax: 60000,
    description: "Accord de concession pour l'exploration pétrolière offshore ou onshore en Côte d'Ivoire, incluant les obligations environnementales.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'operateur', label: "Nom de l\"opérateur pétrolier", type: 'text', required: true },
      { key: 'zone_exploration', label: "Zone d\"exploration (offshore/onshore)", type: 'text', required: true },
      { key: 'superficie_km2', label: "Superficie en km²", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début d\"exploration", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONCESSION D"EXPLORATION PÉTROLIÈRE</h1><p>La présente concession est accordée à <strong>{{operateur}}</strong> pour l"exploration pétrolière dans la zone <strong>{{zone_exploration}}</strong>, d"une superficie de {{superficie_km2}} km², à compter du {{date_debut}}.</p><p>L"opérateur s"engage à respecter les normes HSE en vigueur et à soumettre des rapports trimestriels à la Direction des Hydrocarbures.</p></div>`,
  },
  {
    code: 'petr_service_contract',
    name: "Contrat de Services Pétroliers (Service Contract)",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Contrat de services pétroliers pour prestataires spécialisés intervenant sur les opérations de forage, production ou maintenance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'prestataire', label: "Nom du prestataire de services", type: 'text', required: true },
      { key: 'type_service', label: "Type de service pétrolier", type: 'text', required: true },
      { key: 'montant_contrat', label: "Montant du contrat (FCFA)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début des services", type: 'date', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICES PÉTROLIERS</h1><p>Le présent contrat est conclu entre l"opérateur pétrolier et <strong>{{prestataire}}</strong> pour la fourniture de services de <strong>{{type_service}}</strong>.</p><p>Montant : {{montant_contrat}} FCFA. Durée : {{duree_contrat}} mois à compter du {{date_debut}}.</p><p>Le prestataire s"engage à fournir du personnel qualifié et à respecter les standards HSE de l"opérateur.</p></div>`,
  },
  {
    code: 'petr_joa',
    name: "Accord de Joint Venture Pétrolier (JOA)",
    category: 'agro_environnement',
    price: 22000,
    priceMax: 70000,
    description: "Joint Operating Agreement régissant les droits et obligations des coparticipants dans une opération pétrolière conjointe.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'operateur_principal', label: "Opérateur principal", type: 'text', required: true },
      { key: 'coparticipants', label: "Nom(s) des coparticipants", type: 'textarea', required: true },
      { key: 'participation_operateur', label: "Participation de l\"opérateur (%)", type: 'text', required: true },
      { key: 'bloc_concerne', label: "Bloc pétrolier concerné", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE JOINT VENTURE PÉTROLIER (JOA)</h1><p>Le présent accord est conclu entre <strong>{{operateur_principal}}</strong> (opérateur, {{participation_operateur}}%) et les coparticipants : {{coparticipants}}, pour les opérations sur le bloc <strong>{{bloc_concerne}}</strong>.</p><p>L"opérateur principal assure la conduite des opérations au nom de toutes les parties, dans le respect du programme de travaux approuvé par le comité opérationnel.</p></div>`,
  },
  {
    code: 'petr_lifting',
    name: "Contrat de Vente de Pétrole Brut (Lifting)",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 55000,
    description: "Contrat de vente et d'enlèvement de pétrole brut (lifting) entre producteur et acheteur, avec conditions de prix et de livraison.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'vendeur', label: "Nom du vendeur (producteur)", type: 'text', required: true },
      { key: 'acheteur', label: "Nom de l\"acheteur", type: 'text', required: true },
      { key: 'volume_barils', label: "Volume en barils (Bbl)", type: 'text', required: true },
      { key: 'prix_baril', label: "Prix par baril (USD)", type: 'text', required: true },
      { key: 'date_livraison', label: "Date de livraison", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE DE PÉTROLE BRUT (LIFTING)</h1><p><strong>{{vendeur}}</strong> (ci-après "le Vendeur") s"engage à vendre et à livrer à <strong>{{acheteur}}</strong> (ci-après "l"Acheteur") un volume de {{volume_barils}} barils de pétrole brut au prix de {{prix_baril}} USD/Bbl, livrable le {{date_livraison}}.</p><p>Les conditions de livraison, de paiement et de qualité sont précisées aux annexes du présent contrat.</p></div>`,
  },
  {
    code: 'petr_pipeline_transport',
    name: "Accord de Transport par Pipeline",
    category: 'agro_environnement',
    price: 16000,
    priceMax: 48000,
    description: "Accord régissant le transport d'hydrocarbures par pipeline, incluant tarifs de transport, droits d'accès et obligations des parties.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'expediteur', label: "Nom de l\"expéditeur", type: 'text', required: true },
      { key: 'transporteur', label: "Nom du transporteur (pipeline)", type: 'text', required: true },
      { key: 'trajet', label: "Trajet du pipeline (origine - destination)", type: 'text', required: true },
      { key: 'tarif_transport', label: "Tarif de transport (FCFA/tonne)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSPORT PAR PIPELINE</h1><p>Le présent accord est conclu entre <strong>{{expediteur}}</strong> et <strong>{{transporteur}}</strong> pour le transport d"hydrocarbures sur le trajet <strong>{{trajet}}</strong>.</p><p>Tarif de transport appliqué : {{tarif_transport}} FCFA par tonne. Les conditions techniques d"injection, de qualité et de livraison sont définies en annexe.</p></div>`,
  },
  {
    code: 'petr_stockage',
    name: "Contrat de Stockage de Produits Pétroliers",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Contrat de stockage de produits pétroliers dans un dépôt agréé, avec conditions de sécurité et assurance obligatoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'deposant', label: "Nom du déposant", type: 'text', required: true },
      { key: 'depot', label: "Nom et localisation du dépôt", type: 'text', required: true },
      { key: 'volume_stocke', label: "Volume à stocker (m³)", type: 'text', required: true },
      { key: 'duree_stockage', label: "Durée de stockage (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE STOCKAGE DE PRODUITS PÉTROLIERS</h1><p><strong>{{deposant}}</strong> confie au dépôt <strong>{{depot}}</strong> le stockage de {{volume_stocke}} m³ de produits pétroliers pour une durée de {{duree_stockage}} mois.</p><p>Le dépositaire garantit la conservation des produits conformément aux normes de sécurité en vigueur et aux prescriptions de l"Autorité Nationale de Régulation du Pétrole.</p></div>`,
  },
  {
    code: 'petr_raffinage_facon',
    name: "Accord de Raffinage à Façon",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Accord de raffinage à façon entre un propriétaire de brut et une raffinerie, précisant les rendements et les frais de traitement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'proprietaire_brut', label: "Propriétaire du pétrole brut", type: 'text', required: true },
      { key: 'raffinerie', label: "Nom de la raffinerie", type: 'text', required: true },
      { key: 'volume_brut', label: "Volume de brut à raffiner (tonnes)", type: 'text', required: true },
      { key: 'frais_raffinage', label: "Frais de raffinage (USD/tonne)", type: 'text', required: true },
      { key: 'date_traitement', label: "Date de traitement prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RAFFINAGE À FAÇON</h1><p><strong>{{proprietaire_brut}}</strong> confie à la raffinerie <strong>{{raffinerie}}</strong> le traitement de {{volume_brut}} tonnes de pétrole brut aux frais de raffinage de {{frais_raffinage}} USD/tonne, avec traitement prévu le {{date_traitement}}.</p><p>Les rendements garantis et la qualité des produits finis sont précisés en annexe technique.</p></div>`,
  },
  {
    code: 'petr_distribution_sir',
    name: "Contrat de Distribution de Produits Pétroliers (SIR)",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de distribution de produits pétroliers issus de la SIR (Société Ivoirienne de Raffinage) pour distributeurs agréés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'distributeur', label: "Nom du distributeur agréé", type: 'text', required: true },
      { key: 'zone_distribution', label: "Zone géographique de distribution", type: 'text', required: true },
      { key: 'quota_mensuel', label: "Quota mensuel alloué (m³)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE DISTRIBUTION DE PRODUITS PÉTROLIERS</h1><p>La SIR autorise <strong>{{distributeur}}</strong> à distribuer ses produits pétroliers dans la zone <strong>{{zone_distribution}}</strong>, avec un quota mensuel de {{quota_mensuel}} m³, à compter du {{date_debut}}.</p><p>Le distributeur s"engage à respecter les prix homologués et les conditions générales de distribution fixées par la SIR.</p></div>`,
  },
  {
    code: 'petr_service_station',
    name: "Accord de Service-Station Pétrolière",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 25000,
    description: "Accord de gérance ou d'exploitation d'une station-service pétrolière, incluant obligations d'approvisionnement et normes de qualité.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'gerant', label: "Nom du gérant de la station", type: 'text', required: true },
      { key: 'localisation_station', label: "Localisation de la station-service", type: 'text', required: true },
      { key: 'fournisseur', label: "Nom du fournisseur principal", type: 'text', required: true },
      { key: 'duree_accord', label: "Durée de l\"accord (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D"EXPLOITATION DE SERVICE-STATION PÉTROLIÈRE</h1><p>Le présent accord est conclu entre <strong>{{fournisseur}}</strong> et <strong>{{gerant}}</strong> pour l"exploitation de la station-service sise à <strong>{{localisation_station}}</strong>, pour une durée de {{duree_accord}} an(s).</p><p>Le gérant s"engage à s"approvisionner exclusivement auprès du fournisseur désigné et à maintenir les équipements selon les standards de la marque.</p></div>`,
  },
  {
    code: 'petr_franchise_station',
    name: "Contrat de Franchise Station-Service",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 38000,
    description: "Contrat de franchise pour l'exploitation d'une station-service sous enseigne d'une major pétrolière, avec redevances et obligations de marque.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'franchiseur', label: "Nom du franchiseur (major pétrolière)", type: 'text', required: true },
      { key: 'franchise', label: "Nom du franchisé", type: 'text', required: true },
      { key: 'redevance_mensuelle', label: "Redevance mensuelle (FCFA)", type: 'text', required: true },
      { key: 'adresse_station', label: "Adresse de la station", type: 'text', required: true },
      { key: 'date_ouverture', label: "Date d\"ouverture prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE FRANCHISE STATION-SERVICE</h1><p><strong>{{franchiseur}}</strong> accorde à <strong>{{franchise}}</strong> le droit d"exploiter une station-service sous son enseigne, sise à <strong>{{adresse_station}}</strong>, avec ouverture prévue le {{date_ouverture}}.</p><p>Redevance mensuelle : {{redevance_mensuelle}} FCFA. Le franchisé s"engage à respecter le manuel opérationnel de la marque et les standards qualité du franchiseur.</p></div>`,
  },
  {
    code: 'petr_gnl_transport',
    name: "Accord de Service de Transport de Gaz Naturel (GNL)",
    category: 'agro_environnement',
    price: 20000,
    priceMax: 60000,
    description: "Accord de transport de gaz naturel liquéfié (GNL) incluant conditions de chargement, transport maritime et déchargement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'expediteur_gnl', label: "Expéditeur GNL", type: 'text', required: true },
      { key: 'transporteur_gnl', label: "Transporteur maritime GNL", type: 'text', required: true },
      { key: 'volume_gnl', label: "Volume GNL (tonnes métriques)", type: 'text', required: true },
      { key: 'port_chargement', label: "Port de chargement", type: 'text', required: true },
      { key: 'port_decharge', label: "Port de déchargement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TRANSPORT DE GAZ NATUREL LIQUÉFIÉ (GNL)</h1><p><strong>{{expediteur_gnl}}</strong> confie à <strong>{{transporteur_gnl}}</strong> le transport de {{volume_gnl}} tonnes métriques de GNL, du port de <strong>{{port_chargement}}</strong> au port de <strong>{{port_decharge}}</strong>.</p><p>Les conditions de température de transport, de sécurité et d"assurance cargo sont précisées dans les annexes techniques.</p></div>`,
  },
  {
    code: 'petr_gpl_distribution',
    name: "Contrat de Distribution de Gaz Butane (GPL)",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de distribution de gaz butane (GPL) pour revendeurs agréés en Côte d'Ivoire, incluant conditions de sécurité et prix homologués.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'revendeur_gpl', label: "Nom du revendeur agréé GPL", type: 'text', required: true },
      { key: 'zone_vente', label: "Zone de vente", type: 'text', required: true },
      { key: 'quota_bouteilles', label: "Quota mensuel (nombre de bouteilles)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de la distribution", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE DISTRIBUTION DE GAZ BUTANE (GPL)</h1><p>Le présent contrat autorise <strong>{{revendeur_gpl}}</strong> à distribuer du gaz butane dans la zone <strong>{{zone_vente}}</strong>, avec un quota mensuel de {{quota_bouteilles}} bouteilles, à compter du {{date_debut}}.</p><p>Le revendeur s"engage à respecter les prix homologués par l"État et les normes de sécurité en vigueur pour la manipulation des produits GPL.</p></div>`,
  },
  {
    code: 'petr_maintenance_pipeline',
    name: "Accord de Service de Maintenance de Pipeline",
    category: 'agro_environnement',
    price: 14000,
    priceMax: 42000,
    description: "Accord de maintenance préventive et corrective de pipelines pétroliers, incluant inspections périodiques et interventions d'urgence.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'client_pipeline', label: "Nom du client (propriétaire pipeline)", type: 'text', required: true },
      { key: 'prestataire_maintenance', label: "Prestataire de maintenance", type: 'text', required: true },
      { key: 'lineaire_pipeline', label: "Linéaire de pipeline (km)", type: 'text', required: true },
      { key: 'frequence_inspection', label: "Fréquence des inspections", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE MAINTENANCE DE PIPELINE</h1><p><strong>{{prestataire_maintenance}}</strong> assure la maintenance préventive et corrective du pipeline de <strong>{{client_pipeline}}</strong>, d"un linéaire de {{lineaire_pipeline}} km, avec des inspections {{frequence_inspection}}.</p><p>Le prestataire garantit un délai d"intervention de 4 heures maximum pour toute urgence et fournit un rapport mensuel de l"état des installations.</p></div>`,
  },
  {
    code: 'petr_hse_service',
    name: "Contrat de Service HSE Pétrolier",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Contrat de prestation de services HSE (Hygiène, Sécurité, Environnement) pour sites pétroliers, audits et formations réglementaires.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'client_hse', label: "Nom du client pétrolier", type: 'text', required: true },
      { key: 'consultant_hse', label: "Cabinet/consultant HSE", type: 'text', required: true },
      { key: 'scope_hse', label: "Périmètre des prestations HSE", type: 'textarea', required: true },
      { key: 'duree_mission', label: "Durée de la mission (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE HSE PÉTROLIER</h1><p><strong>{{consultant_hse}}</strong> fournit à <strong>{{client_hse}}</strong> des services HSE pour une durée de {{duree_mission}} mois, couvrant : {{scope_hse}}.</p><p>Les prestations comprennent audits HSE, formations du personnel, rédaction de plans d"urgence et accompagnement aux inspections réglementaires.</p></div>`,
  },
  {
    code: 'petr_formation_drilling',
    name: "Accord de Formation Personnel Pétrolier (Drilling)",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Accord de formation spécialisée du personnel pétrolier aux techniques de forage (drilling), incluant certifications internationales.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'organisme_formation', label: "Organisme de formation", type: 'text', required: true },
      { key: 'entreprise_cliente', label: "Entreprise cliente", type: 'text', required: true },
      { key: 'nombre_stagiaires', label: "Nombre de stagiaires", type: 'text', required: true },
      { key: 'programme_formation', label: "Programme de formation", type: 'textarea', required: true },
      { key: 'date_debut_formation', label: "Date de début de la formation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FORMATION PERSONNEL PÉTROLIER</h1><p><strong>{{organisme_formation}}</strong> s"engage à former {{nombre_stagiaires}} agents de <strong>{{entreprise_cliente}}</strong> aux techniques de forage pétrolier, à compter du {{date_debut_formation}}.</p><p>Programme : {{programme_formation}}. Une certification internationale sera délivrée aux stagiaires ayant satisfait aux évaluations finales.</p></div>`,
  },
  {
    code: 'petr_ingenierie',
    name: "Contrat de Service d'Ingénierie Pétrolière",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 55000,
    description: "Contrat de services d'ingénierie pétrolière (FEED, EPCM, études de conception) pour projets d'exploration et de production.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'bureau_ingenierie', label: "Bureau d\"ingénierie", type: 'text', required: true },
      { key: 'projet_petrolier', label: "Nom du projet pétrolier", type: 'text', required: true },
      { key: 'phase_ingenierie', label: "Phase d\"ingénierie (FEED/EPCM/autre)", type: 'text', required: true },
      { key: 'budget_estime', label: "Budget estimé (USD)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"INGÉNIERIE PÉTROLIÈRE</h1><p><strong>{{bureau_ingenierie}}</strong> réalise les études d"ingénierie en phase <strong>{{phase_ingenierie}}</strong> pour le projet <strong>{{projet_petrolier}}</strong>, avec un budget estimé de {{budget_estime}} USD.</p><p>Les livrables, le calendrier et les critères d"acceptance sont définis dans le cahier des charges joint en annexe.</p></div>`,
  },
  {
    code: 'petr_cession_blocs',
    name: "Accord de Cession de Blocs Pétroliers",
    category: 'agro_environnement',
    price: 25000,
    priceMax: 75000,
    description: "Accord de cession ou de transfert de droits sur des blocs pétroliers entre compagnies, soumis à l'approbation de l'État.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'cedant', label: "Nom du cédant", type: 'text', required: true },
      { key: 'cessionnaire', label: "Nom du cessionnaire", type: 'text', required: true },
      { key: 'blocs_cedes', label: "Blocs pétroliers cédés", type: 'text', required: true },
      { key: 'prix_cession', label: "Prix de cession (USD)", type: 'text', required: true },
      { key: 'date_cession', label: "Date effective de cession", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CESSION DE BLOCS PÉTROLIERS</h1><p><strong>{{cedant}}</strong> cède à <strong>{{cessionnaire}}</strong> ses droits sur les blocs pétroliers <strong>{{blocs_cedes}}</strong> au prix de {{prix_cession}} USD, avec effet au {{date_cession}}, sous réserve de l"approbation des autorités compétentes.</p><p>Le cessionnaire reprend l"ensemble des droits, obligations et engagements attachés aux blocs cédés.</p></div>`,
  },
  {
    code: 'petr_evaluation_reserves',
    name: "Rapport d'Évaluation de Réserves Pétrolières",
    category: 'agro_environnement',
    price: 20000,
    priceMax: 60000,
    description: "Rapport professionnel d'évaluation et de certification de réserves pétrolières selon les normes SPE/PRMS pour due diligence.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'societe_evaluatrice', label: "Société évaluatrice indépendante", type: 'text', required: true },
      { key: 'actif_petrolier', label: "Actif pétrolier évalué", type: 'text', required: true },
      { key: 'reserves_prouvees', label: "Réserves prouvées (MMBbl)", type: 'text', required: true },
      { key: 'date_evaluation', label: "Date de l\"évaluation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D"ÉVALUATION DE RÉSERVES PÉTROLIÈRES</h1><p>Ce rapport est établi par <strong>{{societe_evaluatrice}}</strong> concernant l"actif pétrolier <strong>{{actif_petrolier}}</strong>, à la date du {{date_evaluation}}.</p><p>Réserves prouvées (1P) : {{reserves_prouvees}} MMBbl. L"évaluation est conduite conformément aux normes SPE/PRMS et aux meilleures pratiques de l"industrie pétrolière internationale.</p></div>`,
  },
  {
    code: 'petr_plan_urgence',
    name: "Plan de Réponse aux Urgences Pétrolières",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Plan de réponse aux urgences pour sites pétroliers (déversements, incendies, explosions), conforme aux exigences réglementaires ivoiriennes.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'site_petrolier', label: "Nom et localisation du site pétrolier", type: 'text', required: true },
      { key: 'responsable_urgences', label: "Responsable urgences (nom et titre)", type: 'text', required: true },
      { key: 'types_risques', label: "Types de risques identifiés", type: 'textarea', required: true },
      { key: 'date_revision', label: "Date de révision du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE RÉPONSE AUX URGENCES PÉTROLIÈRES</h1><p>Ce plan de réponse aux urgences est établi pour le site <strong>{{site_petrolier}}</strong>, sous la responsabilité de <strong>{{responsable_urgences}}</strong>. Dernière révision : {{date_revision}}.</p><p>Risques identifiés : {{types_risques}}. Les procédures d"intervention, les contacts d"urgence et les ressources mobilisables sont détaillés dans les annexes opérationnelles.</p></div>`,
  },
  {
    code: 'petr_qhse_certification',
    name: "Accord de Certification QHSE Pétrolier",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Accord de certification QHSE (Qualité, Hygiène, Sécurité, Environnement) pour entreprises du secteur pétrolier ivoirien.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'entreprise_certifier', label: "Entreprise à certifier", type: 'text', required: true },
      { key: 'organisme_certification', label: "Organisme certificateur", type: 'text', required: true },
      { key: 'referentiel_qhse', label: "Référentiel QHSE (ISO 9001, ISO 14001, etc.)", type: 'text', required: true },
      { key: 'date_audit', label: "Date d\"audit de certification", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION QHSE PÉTROLIER</h1><p><strong>{{organisme_certification}}</strong> s"engage à auditer et certifier <strong>{{entreprise_certifier}}</strong> selon le référentiel <strong>{{referentiel_qhse}}</strong>, avec audit prévu le {{date_audit}}.</p><p>La certification atteste de la conformité du système de management QHSE aux exigences du référentiel et aux réglementations du secteur pétrolier en vigueur en Côte d"Ivoire.</p></div>`,
  },
  {
    code: 'petr_depollution',
    name: "Contrat de Service de Dépollution Pétrolière",
    category: 'agro_environnement',
    price: 16000,
    priceMax: 50000,
    description: "Contrat de prestation de services de dépollution et de réhabilitation de sites contaminés par des hydrocarbures.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'responsable_pollution', label: "Responsable de la pollution", type: 'text', required: true },
      { key: 'prestataire_depollution', label: "Prestataire de dépollution", type: 'text', required: true },
      { key: 'site_pollue', label: "Localisation du site pollué", type: 'text', required: true },
      { key: 'superficie_site', label: "Superficie du site (ha)", type: 'text', required: true },
      { key: 'delai_rehabilitation', label: "Délai de réhabilitation (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE DÉPOLLUTION PÉTROLIÈRE</h1><p><strong>{{prestataire_depollution}}</strong> réalise la dépollution et la réhabilitation du site pollué de <strong>{{responsable_pollution}}</strong>, localisé à <strong>{{site_pollue}}</strong>, d"une superficie de {{superficie_site}} ha, dans un délai de {{delai_rehabilitation}} mois.</p><p>Les techniques de traitement, les critères de succès et les rapports de suivi environnemental sont définis en annexe.</p></div>`,
  },
  {
    code: 'petr_convention_sir',
    name: "Convention avec SIR (Société Ivoirienne de Raffinage)",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Convention de partenariat ou de prestation avec la SIR (Société Ivoirienne de Raffinage) pour fourniture de services ou de produits.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'partenaire_sir', label: "Nom du partenaire/prestataire", type: 'text', required: true },
      { key: 'objet_convention', label: "Objet de la convention", type: 'textarea', required: true },
      { key: 'montant_convention', label: "Montant de la convention (FCFA)", type: 'text', required: true },
      { key: 'date_entree_vigueur', label: "Date d\"entrée en vigueur", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION AVEC LA SOCIÉTÉ IVOIRIENNE DE RAFFINAGE (SIR)</h1><p>La présente convention est conclue entre la Société Ivoirienne de Raffinage (SIR) et <strong>{{partenaire_sir}}</strong>, portant sur : {{objet_convention}}, pour un montant de {{montant_convention}} FCFA, avec effet au {{date_entree_vigueur}}.</p><p>Les conditions techniques, financières et les obligations de chaque partie sont détaillées dans les articles suivants et les annexes jointes.</p></div>`,
  },
  {
    code: 'petr_accord_petroci',
    name: "Accord avec PETROCI",
    category: 'agro_environnement',
    price: 20000,
    priceMax: 60000,
    description: "Accord de coopération ou de prestation avec PETROCI (Pétrole de Côte d'Ivoire), société nationale des hydrocarbures.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 81,
    fieldsJson: F([
      { key: 'partenaire_petroci', label: "Nom du partenaire", type: 'text', required: true },
      { key: 'type_accord', label: "Type d\"accord (coopération/prestation/JV)", type: 'text', required: true },
      { key: 'bloc_ou_projet', label: "Bloc ou projet concerné", type: 'text', required: true },
      { key: 'duree_accord', label: "Durée de l\"accord (années)", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD AVEC PETROCI — PÉTROLE DE CÔTE D"IVOIRE</h1><p>Le présent accord de <strong>{{type_accord}}</strong> est conclu entre PETROCI et <strong>{{partenaire_petroci}}</strong>, concernant le bloc/projet <strong>{{bloc_ou_projet}}</strong>, pour une durée de {{duree_accord}} an(s), signé le {{date_signature}}.</p><p>PETROCI représente l"État de Côte d"Ivoire dans les opérations pétrolières nationales et veille à la conformité des opérations aux dispositions du Code Pétrolier ivoirien.</p></div>`,
  },
  {
    code: 'petr_conformite_reglementaire',
    name: "Rapport de Conformité Réglementaire Secteur Pétrolier",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Rapport annuel de conformité réglementaire pour opérateurs et prestataires du secteur pétrolier ivoirien, requis par la Direction des Hydrocarbures.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'entreprise_rapportante', label: "Entreprise rapportante", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'responsable_conformite', label: "Responsable conformité (nom et titre)", type: 'text', required: true },
      { key: 'date_rapport', label: "Date d\"établissement du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE CONFORMITÉ RÉGLEMENTAIRE — SECTEUR PÉTROLIER</h1><p>Ce rapport de conformité est établi par <strong>{{entreprise_rapportante}}</strong>, sous la responsabilité de <strong>{{responsable_conformite}}</strong>, pour la période <strong>{{periode_rapport}}</strong>, à la date du {{date_rapport}}.</p><p>Il couvre la conformité aux obligations légales, réglementaires et contractuelles applicables aux opérations pétrolières en Côte d"Ivoire, notamment le Code Pétrolier, les décrets d"application et les arrêtés ministériels en vigueur.</p></div>`,
  },

  // ─── AUTOMOBILE / MÉCANIQUE INDUSTRIELLE (25) ────────────────────────────
  {
    code: 'auto_concessionnaire',
    name: "Contrat de Concessionnaire Automobile",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 45000,
    description: "Contrat de concession automobile entre constructeur/importateur et concessionnaire agréé, avec obligations de vente et de service après-vente.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'constructeur', label: "Nom du constructeur/importateur", type: 'text', required: true },
      { key: 'concessionnaire', label: "Nom du concessionnaire", type: 'text', required: true },
      { key: 'zone_chalandise', label: "Zone de chalandise attribuée", type: 'text', required: true },
      { key: 'objectif_vente_annuel', label: "Objectif de vente annuel (véhicules)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE CONCESSIONNAIRE AUTOMOBILE</h1><p><strong>{{constructeur}}</strong> accorde à <strong>{{concessionnaire}}</strong> le droit exclusif de vente et de service pour sa gamme de véhicules dans la zone <strong>{{zone_chalandise}}</strong>, pour une durée de {{duree_contrat}} an(s).</p><p>Objectif de vente annuel : {{objectif_vente_annuel}} véhicules. Le concessionnaire s"engage à maintenir des standards de présentation, de service et de satisfaction client conformes aux exigences de la marque.</p></div>`,
  },
  {
    code: 'auto_distribution_vehicules',
    name: "Accord de Distribution de Véhicules",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Accord de distribution non exclusive de véhicules automobiles sur le territoire ivoirien, avec conditions tarifaires et logistiques.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'fournisseur_vehicules', label: "Fournisseur de véhicules", type: 'text', required: true },
      { key: 'distributeur_vehicules', label: "Distributeur", type: 'text', required: true },
      { key: 'marque_modeles', label: "Marques et modèles concernés", type: 'text', required: true },
      { key: 'remise_accordee', label: "Remise accordée sur prix catalogue (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTION DE VÉHICULES</h1><p><strong>{{fournisseur_vehicules}}</strong> autorise <strong>{{distributeur_vehicules}}</strong> à distribuer les véhicules de la gamme <strong>{{marque_modeles}}</strong> sur le territoire ivoirien, avec une remise de {{remise_accordee}}% sur le prix catalogue constructeur.</p><p>Les conditions de commande, de livraison et de garantie constructeur sont précisées aux annexes du présent accord.</p></div>`,
  },
  {
    code: 'auto_sav',
    name: "Contrat de Service Après-Vente (SAV) Automobile",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de service après-vente automobile pour clients particuliers et entreprises, incluant garanties, délais et conditions tarifaires.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'garage_sav', label: "Nom du garage/concessionnaire SAV", type: 'text', required: true },
      { key: 'client_sav', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_marque', label: "Marque et modèle du véhicule", type: 'text', required: true },
      { key: 'immatriculation', label: "Numéro d\"immatriculation", type: 'text', required: true },
      { key: 'duree_garantie_sav', label: "Durée de garantie SAV (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE APRÈS-VENTE AUTOMOBILE</h1><p><strong>{{garage_sav}}</strong> s"engage envers <strong>{{client_sav}}</strong> à assurer le service après-vente du véhicule <strong>{{vehicule_marque}}</strong> immatriculé <strong>{{immatriculation}}</strong>, avec une garantie de {{duree_garantie_sav}} mois sur les pièces et la main-d"oeuvre.</p></div>`,
  },
  {
    code: 'auto_franchise_garage',
    name: "Accord de Franchise Garage Automobile",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 38000,
    description: "Contrat de franchise pour l'exploitation d'un garage automobile sous enseigne nationale, incluant transfert de savoir-faire et redevances.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'franchiseur_garage', label: "Franchiseur (enseigne garage)", type: 'text', required: true },
      { key: 'franchise_garage', label: "Franchisé (gérant garage)", type: 'text', required: true },
      { key: 'adresse_garage', label: "Adresse du garage", type: 'text', required: true },
      { key: 'droit_entree', label: "Droit d\"entrée (FCFA)", type: 'text', required: true },
      { key: 'redevance_ca', label: "Redevance sur CA (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FRANCHISE GARAGE AUTOMOBILE</h1><p><strong>{{franchiseur_garage}}</strong> accorde à <strong>{{franchise_garage}}</strong> le droit d"exploiter un garage sous son enseigne, situé à <strong>{{adresse_garage}}</strong>. Droit d"entrée : {{droit_entree}} FCFA. Redevance : {{redevance_ca}}% du chiffre d"affaires mensuel.</p><p>Le franchisé bénéficie du savoir-faire, des outils, des formations et de l"assistance du franchiseur dans les conditions définies au manuel de la franchise.</p></div>`,
  },
  {
    code: 'auto_reparation_mecanique',
    name: "Contrat de Service de Réparation Mécanique",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de réparation mécanique pour véhicule, précisant les travaux à effectuer, le devis et les délais d'exécution.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'garage_reparation', label: "Nom du garage", type: 'text', required: true },
      { key: 'client_vehicule', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_info', label: "Véhicule (marque, modèle, immat.)", type: 'text', required: true },
      { key: 'travaux_prevus', label: "Travaux de réparation prévus", type: 'textarea', required: true },
      { key: 'montant_devis', label: "Montant du devis (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE RÉPARATION MÉCANIQUE</h1><p>Le garage <strong>{{garage_reparation}}</strong> s"engage à effectuer les réparations suivantes sur le véhicule <strong>{{vehicule_info}}</strong> appartenant à <strong>{{client_vehicule}}</strong> :</p><p>{{travaux_prevus}}</p><p>Montant du devis accepté : {{montant_devis}} FCFA. La garantie sur les réparations est de 3 mois ou 5 000 km.</p></div>`,
  },
  {
    code: 'auto_carrosserie',
    name: "Accord de Service de Carrosserie Automobile",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de service de carrosserie automobile (réparation chocs, peinture, redressage) avec devis détaillé et délais.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'carrossier', label: "Nom du carrossier", type: 'text', required: true },
      { key: 'client_carrosserie', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_carrosserie', label: "Véhicule (marque, modèle, immat.)", type: 'text', required: true },
      { key: 'degats_constates', label: "Dégâts constatés et travaux", type: 'textarea', required: true },
      { key: 'delai_livraison', label: "Délai de livraison (jours)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CARROSSERIE AUTOMOBILE</h1><p><strong>{{carrossier}}</strong> prend en charge le véhicule <strong>{{vehicule_carrosserie}}</strong> de <strong>{{client_carrosserie}}</strong> pour les travaux suivants : {{degats_constates}}.</p><p>Délai de livraison : {{delai_livraison}} jours ouvrés. Un rapport photographique avant/après sera fourni au client à la livraison.</p></div>`,
  },
  {
    code: 'auto_pneumatiques',
    name: "Contrat de Service de Pneumatiques",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de fourniture et de pose de pneumatiques pour véhicules particuliers et utilitaires, avec conditions de garantie.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'fournisseur_pneus', label: "Fournisseur de pneumatiques", type: 'text', required: true },
      { key: 'client_pneus', label: "Nom du client", type: 'text', required: true },
      { key: 'marque_pneus', label: "Marque et dimension des pneumatiques", type: 'text', required: true },
      { key: 'quantite_pneus', label: "Quantité de pneumatiques", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE PNEUMATIQUES</h1><p><strong>{{fournisseur_pneus}}</strong> s"engage à fournir et poser {{quantite_pneus}} pneumatiques <strong>{{marque_pneus}}</strong> pour le véhicule de <strong>{{client_pneus}}</strong>.</p><p>Les pneumatiques sont garantis contre tout défaut de fabrication pendant 12 mois ou 20 000 km. Un équilibrage et un contrôle de la géométrie sont inclus dans la prestation.</p></div>`,
  },
  {
    code: 'auto_vidange_entretien',
    name: "Accord de Service de Vidange et d'Entretien",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de service régulier de vidange et d'entretien automobile, avec planning d'entretien préventif personnalisé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 87,
    fieldsJson: F([
      { key: 'centre_entretien', label: "Centre d\"entretien automobile", type: 'text', required: true },
      { key: 'client_entretien', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_entretien', label: "Véhicule (marque, modèle, immat.)", type: 'text', required: true },
      { key: 'periodicite_vidange', label: "Périodicité de vidange (km ou mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE VIDANGE ET D"ENTRETIEN</h1><p><strong>{{centre_entretien}}</strong> assure l"entretien préventif du véhicule <strong>{{vehicule_entretien}}</strong> de <strong>{{client_entretien}}</strong>, avec vidanges et contrôles périodiques tous les {{periodicite_vidange}}.</p><p>Le planning d"entretien préventif personnalisé est établi en annexe. Chaque intervention donne lieu à un carnet d"entretien mis à jour.</p></div>`,
  },
  {
    code: 'auto_location_vtc',
    name: "Contrat de Location de Véhicules (VTC)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 25000,
    description: "Contrat de location de véhicules avec chauffeur (VTC) pour entreprises ou particuliers, incluant conditions d'utilisation et assurance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'societe_vtc', label: "Société VTC", type: 'text', required: true },
      { key: 'client_vtc', label: "Nom du client", type: 'text', required: true },
      { key: 'type_vehicule_vtc', label: "Type de véhicule loué", type: 'text', required: true },
      { key: 'tarif_heure', label: "Tarif horaire (FCFA)", type: 'text', required: true },
      { key: 'date_debut_location', label: "Date de début de la location", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE LOCATION DE VÉHICULES AVEC CHAUFFEUR (VTC)</h1><p><strong>{{societe_vtc}}</strong> met à disposition de <strong>{{client_vtc}}</strong> un véhicule de type <strong>{{type_vehicule_vtc}}</strong> avec chauffeur, à compter du {{date_debut_location}}, au tarif de {{tarif_heure}} FCFA/heure.</p><p>Le véhicule est assuré tous risques. Le chauffeur respecte le code de conduite professionnel de la société VTC.</p></div>`,
  },
  {
    code: 'auto_lld',
    name: "Accord de Location Longue Durée (LLD) Automobile",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Accord de location longue durée de véhicules pour entreprises, incluant entretien, assurance et services associés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'bailleur_lld', label: "Société de LLD (bailleur)", type: 'text', required: true },
      { key: 'locataire_lld', label: "Entreprise locataire", type: 'text', required: true },
      { key: 'flotte_lld', label: "Nombre et type de véhicules", type: 'text', required: true },
      { key: 'loyer_mensuel', label: "Loyer mensuel par véhicule (FCFA)", type: 'text', required: true },
      { key: 'duree_lld', label: "Durée du contrat LLD (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE LOCATION LONGUE DURÉE (LLD) AUTOMOBILE</h1><p><strong>{{bailleur_lld}}</strong> met à la disposition de <strong>{{locataire_lld}}</strong> une flotte de {{flotte_lld}} pour une durée de {{duree_lld}} mois, au loyer mensuel de {{loyer_mensuel}} FCFA par véhicule.</p><p>La LLD inclut l"entretien préventif, les réparations et l"assurance tous risques. À l"échéance, le locataire peut restituer les véhicules ou renouveler le contrat.</p></div>`,
  },
  {
    code: 'auto_leasing',
    name: "Contrat de Leasing Automobile",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Contrat de leasing automobile (crédit-bail) pour acquisition de véhicules neufs par les entreprises, avec option d'achat finale.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'bailleur_leasing', label: "Établissement de crédit-bail", type: 'text', required: true },
      { key: 'preneur_leasing', label: "Preneur de leasing (entreprise)", type: 'text', required: true },
      { key: 'vehicule_leasing', label: "Véhicule en leasing (marque/modèle)", type: 'text', required: true },
      { key: 'valeur_vehicule', label: "Valeur du véhicule (FCFA)", type: 'text', required: true },
      { key: 'loyer_leasing', label: "Loyer mensuel de leasing (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE LEASING AUTOMOBILE</h1><p><strong>{{bailleur_leasing}}</strong> met en crédit-bail à <strong>{{preneur_leasing}}</strong> le véhicule <strong>{{vehicule_leasing}}</strong> d"une valeur de {{valeur_vehicule}} FCFA, au loyer mensuel de {{loyer_leasing}} FCFA.</p><p>À l"échéance du contrat, le preneur peut exercer son option d"achat aux conditions définies à l"article relatif à la valeur résiduelle.</p></div>`,
  },
  {
    code: 'auto_controle_technique',
    name: "Accord de Service de Contrôle Technique Automobile",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de service de contrôle technique automobile agréé, conforme aux réglementations ivoiriennes de sécurité routière.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'centre_ct', label: "Centre de contrôle technique agréé", type: 'text', required: true },
      { key: 'proprietaire_vehicule', label: "Nom du propriétaire du véhicule", type: 'text', required: true },
      { key: 'vehicule_controle', label: "Véhicule (marque, modèle, immat.)", type: 'text', required: true },
      { key: 'date_controle', label: "Date du contrôle technique", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CONTRÔLE TECHNIQUE AUTOMOBILE</h1><p>Le centre de contrôle technique agréé <strong>{{centre_ct}}</strong> effectue le contrôle technique du véhicule <strong>{{vehicule_controle}}</strong> appartenant à <strong>{{proprietaire_vehicule}}</strong>, le {{date_controle}}.</p><p>Le contrôle porte sur l"ensemble des organes de sécurité conformément au référentiel réglementaire ivoirien en vigueur. Le procès-verbal est remis au propriétaire à l"issue du contrôle.</p></div>`,
  },
  {
    code: 'auto_depannage_routier',
    name: "Contrat de Service de Dépannage Routier",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 20000,
    description: "Contrat d'assistance et de dépannage routier 24h/24 pour véhicules en panne, couvrant l'ensemble du territoire ivoirien.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'societe_depannage', label: "Société de dépannage", type: 'text', required: true },
      { key: 'adherent_depannage', label: "Nom de l\"adhérent", type: 'text', required: true },
      { key: 'vehicules_couverts', label: "Véhicule(s) couvert(s)", type: 'text', required: true },
      { key: 'zone_couverture', label: "Zone de couverture", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE DÉPANNAGE ROUTIER</h1><p><strong>{{societe_depannage}}</strong> garantit à <strong>{{adherent_depannage}}</strong> une assistance dépannage 24h/24 et 7j/7 pour le(s) véhicule(s) <strong>{{vehicules_couverts}}</strong> dans la zone <strong>{{zone_couverture}}</strong>.</p><p>Délai d"intervention garanti : 60 minutes en zone urbaine et 2 heures en zone périurbaine. Les prestations incluent dépannage sur place et remorquage si nécessaire.</p></div>`,
  },
  {
    code: 'auto_remorquage',
    name: "Accord de Service de Remorquage Automobile",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de service de remorquage de véhicules accidentés ou en panne, avec tarification selon distance et type de véhicule.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'societe_remorquage', label: "Société de remorquage", type: 'text', required: true },
      { key: 'client_remorquage', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_remorque', label: "Véhicule à remorquer (marque/immat.)", type: 'text', required: true },
      { key: 'destination_remorquage', label: "Destination du remorquage", type: 'text', required: true },
      { key: 'tarif_remorquage', label: "Tarif de remorquage (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE REMORQUAGE AUTOMOBILE</h1><p><strong>{{societe_remorquage}}</strong> prend en charge le remorquage du véhicule <strong>{{vehicule_remorque}}</strong> de <strong>{{client_remorquage}}</strong> jusqu"à <strong>{{destination_remorquage}}</strong>, au tarif de {{tarif_remorquage}} FCFA.</p><p>La société de remorquage est responsable du véhicule pendant toute la durée du transport et est couverte par une assurance responsabilité civile professionnelle.</p></div>`,
  },
  {
    code: 'auto_pieces_detachees',
    name: "Contrat de Fournisseur de Pièces Détachées (Import)",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Contrat d'importation et de fourniture de pièces détachées automobiles pour garagistes et concessionnaires en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'importateur_pieces', label: "Importateur de pièces détachées", type: 'text', required: true },
      { key: 'acheteur_pieces', label: "Acheteur (garage/concessionnaire)", type: 'text', required: true },
      { key: 'marques_pieces', label: "Marques de véhicules concernées", type: 'text', required: true },
      { key: 'remise_grossiste', label: "Remise grossiste accordée (%)", type: 'text', required: true },
      { key: 'delai_livraison_pieces', label: "Délai de livraison moyen (jours)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE FOURNISSEUR DE PIÈCES DÉTACHÉES AUTOMOBILES</h1><p><strong>{{importateur_pieces}}</strong> s"engage à fournir à <strong>{{acheteur_pieces}}</strong> des pièces détachées d"origine et de qualité équivalente pour les marques <strong>{{marques_pieces}}</strong>, avec une remise grossiste de {{remise_grossiste}}% et un délai de livraison de {{delai_livraison_pieces}} jours ouvrés.</p><p>Toutes les pièces sont garanties conformes aux normes constructeur et accompagnées des certificats de conformité requis.</p></div>`,
  },
  {
    code: 'auto_tolerie_peinture',
    name: "Accord de Service de Tôlerie-Peinture Automobile",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de service de tôlerie et de peinture automobile, avec devis estimatif et conditions de garantie sur les travaux.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 81,
    fieldsJson: F([
      { key: 'atelier_tolerie', label: "Atelier de tôlerie-peinture", type: 'text', required: true },
      { key: 'client_tolerie', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_tolerie', label: "Véhicule (marque, modèle, couleur)", type: 'text', required: true },
      { key: 'travaux_tolerie', label: "Travaux de tôlerie et peinture", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TÔLERIE-PEINTURE AUTOMOBILE</h1><p>L"atelier <strong>{{atelier_tolerie}}</strong> prend en charge le véhicule <strong>{{vehicule_tolerie}}</strong> de <strong>{{client_tolerie}}</strong> pour les travaux suivants : {{travaux_tolerie}}.</p><p>La garantie sur les travaux de peinture est de 12 mois contre le cloquage, le décollement et les défauts d"aspect visibles dans des conditions normales d"utilisation.</p></div>`,
  },
  {
    code: 'auto_expertise_sotra',
    name: "Rapport d'Expertise Automobile (SOTRA)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Rapport d'expertise automobile pour évaluation de dommages, notamment pour sinistres traités par la SOTRA ou compagnies d'assurance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'expert_auto', label: "Nom de l\"expert automobile agréé", type: 'text', required: true },
      { key: 'vehicule_expertise', label: "Véhicule expertisé (marque, modèle, immat.)", type: 'text', required: true },
      { key: 'circonstances_sinistre', label: "Circonstances du sinistre", type: 'textarea', required: true },
      { key: 'date_expertise', label: "Date de l\"expertise", type: 'date', required: true },
      { key: 'montant_dommages', label: "Montant estimé des dommages (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D"EXPERTISE AUTOMOBILE</h1><p>L"expert agréé <strong>{{expert_auto}}</strong> a procédé à l"expertise du véhicule <strong>{{vehicule_expertise}}</strong> le {{date_expertise}}, suite au sinistre suivant : {{circonstances_sinistre}}.</p><p>Montant estimé des dommages : <strong>{{montant_dommages}} FCFA</strong>. Ce rapport est établi contradictoirement et vaut justificatif auprès des compagnies d"assurance.</p></div>`,
  },
  {
    code: 'auto_lavage',
    name: "Contrat de Service de Lavage Automobile",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de service de lavage et d'entretien esthétique de véhicules, avec abonnements mensuel et annuel disponibles.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'centre_lavage', label: "Centre de lavage automobile", type: 'text', required: true },
      { key: 'client_lavage', label: "Nom du client", type: 'text', required: true },
      { key: 'formule_abonnement', label: "Formule d\"abonnement choisie", type: 'text', required: true },
      { key: 'nombre_vehicules', label: "Nombre de véhicules couverts", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE LAVAGE AUTOMOBILE</h1><p><strong>{{centre_lavage}}</strong> propose à <strong>{{client_lavage}}</strong> la formule d"abonnement <strong>{{formule_abonnement}}</strong> pour {{nombre_vehicules}} véhicule(s).</p><p>Les prestations incluent lavage extérieur, nettoyage intérieur, traitement des plastiques et lustrage selon la formule choisie. L"abonnement est nominatif et non transférable.</p></div>`,
  },
  {
    code: 'auto_gpl_auto',
    name: "Accord de Service d'Installation GPL Automobile",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 25000,
    description: "Accord d'installation de kit GPL (gaz propane liquéfié) sur véhicule automobile, incluant certification et garantie d'installation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'installateur_gpl', label: "Installateur GPL agréé", type: 'text', required: true },
      { key: 'client_gpl', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_gpl', label: "Véhicule cible (marque, modèle, immat.)", type: 'text', required: true },
      { key: 'kit_gpl', label: "Référence du kit GPL installé", type: 'text', required: true },
      { key: 'date_installation', label: "Date d\"installation prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D"INSTALLATION GPL AUTOMOBILE</h1><p><strong>{{installateur_gpl}}</strong> installe un kit GPL <strong>{{kit_gpl}}</strong> sur le véhicule <strong>{{vehicule_gpl}}</strong> de <strong>{{client_gpl}}</strong>, avec installation prévue le {{date_installation}}.</p><p>L"installation est garantie 24 mois et est accompagnée d"un certificat de conformité délivré par l"organisme de contrôle agréé.</p></div>`,
  },
  {
    code: 'auto_electronique_auto',
    name: "Contrat de Service d'Électronique Automobile",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de diagnostic et de réparation électronique automobile (calculateurs, systèmes embarqués, autoradio, alarmes).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'atelier_electronique', label: "Atelier électronique automobile", type: 'text', required: true },
      { key: 'client_electronique', label: "Nom du client", type: 'text', required: true },
      { key: 'vehicule_electronique', label: "Véhicule (marque, modèle, immat.)", type: 'text', required: true },
      { key: 'pannes_electroniques', label: "Pannes électroniques diagnostiquées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"ÉLECTRONIQUE AUTOMOBILE</h1><p>L"atelier <strong>{{atelier_electronique}}</strong> effectue le diagnostic et la réparation électronique du véhicule <strong>{{vehicule_electronique}}</strong> de <strong>{{client_electronique}}</strong>.</p><p>Pannes diagnostiquées : {{pannes_electroniques}}. La garantie sur les réparations électroniques est de 6 mois. Un rapport de diagnostic OBD est remis au client.</p></div>`,
  },
  {
    code: 'auto_formation_mecaniciens',
    name: "Accord de Formation de Mécaniciens Automobiles",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 25000,
    description: "Accord de formation professionnelle des mécaniciens automobiles, incluant formation pratique sur véhicules et certification.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'centre_formation_meca', label: "Centre de formation professionnelle", type: 'text', required: true },
      { key: 'entreprise_formatee', label: "Entreprise bénéficiaire", type: 'text', required: true },
      { key: 'programme_meca', label: "Programme de formation (modules)", type: 'textarea', required: true },
      { key: 'duree_formation_meca', label: "Durée de la formation (jours)", type: 'text', required: true },
      { key: 'date_formation_meca', label: "Date de début de la formation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FORMATION DE MÉCANICIENS AUTOMOBILES</h1><p><strong>{{centre_formation_meca}}</strong> dispense une formation professionnelle à <strong>{{entreprise_formatee}}</strong> sur les modules suivants : {{programme_meca}}.</p><p>Durée : {{duree_formation_meca}} jours, à compter du {{date_formation_meca}}. Une attestation de formation est délivrée à chaque participant ayant satisfait à l"évaluation finale.</p></div>`,
  },
  {
    code: 'auto_vehicules_occasion',
    name: "Contrat de Service de Vente de Véhicules d'Occasion",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 22000,
    description: "Contrat de vente de véhicules d'occasion entre professionnel et particulier, avec inspection préalable et garantie légale.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'vendeur_occasion', label: "Vendeur professionnel", type: 'text', required: true },
      { key: 'acheteur_occasion', label: "Acheteur", type: 'text', required: true },
      { key: 'vehicule_occasion', label: "Véhicule d\"occasion (marque, modèle, immat., année)", type: 'text', required: true },
      { key: 'prix_vente_occasion', label: "Prix de vente (FCFA)", type: 'text', required: true },
      { key: 'date_vente_occasion', label: "Date de la vente", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE DE VÉHICULE D"OCCASION</h1><p><strong>{{vendeur_occasion}}</strong> vend à <strong>{{acheteur_occasion}}</strong> le véhicule d"occasion <strong>{{vehicule_occasion}}</strong> au prix de {{prix_vente_occasion}} FCFA, en date du {{date_vente_occasion}}.</p><p>Le véhicule a fait l"objet d"une inspection mécanique préalable dont le rapport est joint. La garantie légale de 3 mois s"applique conformément au droit ivoirien de la consommation.</p></div>`,
  },
  {
    code: 'auto_plateforme_digitale',
    name: "Accord de Plateforme Digitale de Vente Auto",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Accord d'utilisation d'une plateforme digitale de vente et d'achat de véhicules automobiles pour professionnels de l'automobile.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'operateur_plateforme', label: "Opérateur de la plateforme", type: 'text', required: true },
      { key: 'professionnel_auto', label: "Professionnel de l\"automobile", type: 'text', required: true },
      { key: 'formule_plateforme', label: "Formule d\"abonnement plateforme", type: 'text', required: true },
      { key: 'commission_vente', label: "Commission sur vente (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D"UTILISATION DE PLATEFORME DIGITALE DE VENTE AUTOMOBILE</h1><p><strong>{{operateur_plateforme}}</strong> accorde à <strong>{{professionnel_auto}}</strong> l"accès à sa plateforme de vente digitale selon la formule <strong>{{formule_plateforme}}</strong>, avec une commission de {{commission_vente}}% sur chaque transaction conclue via la plateforme.</p><p>L"opérateur s"engage à assurer la visibilité des annonces, la sécurisation des transactions et l"assistance technique aux utilisateurs professionnels.</p></div>`,
  },
  {
    code: 'auto_fleet_management',
    name: "Rapport de Bilan Automobile Fleet Management",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Rapport de bilan et de gestion de flotte automobile (fleet management) pour entreprises disposant d'un parc de véhicules.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'societe_fleet', label: "Société propriétaire de la flotte", type: 'text', required: true },
      { key: 'responsable_fleet', label: "Responsable fleet management", type: 'text', required: true },
      { key: 'taille_flotte', label: "Nombre de véhicules dans la flotte", type: 'text', required: true },
      { key: 'periode_bilan', label: "Période du bilan", type: 'text', required: true },
      { key: 'date_bilan', label: "Date d\"établissement du bilan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE BILAN AUTOMOBILE — FLEET MANAGEMENT</h1><p>Ce rapport de bilan de flotte est établi par <strong>{{responsable_fleet}}</strong> pour la flotte de <strong>{{societe_fleet}}</strong> ({{taille_flotte}} véhicules), pour la période <strong>{{periode_bilan}}</strong>, à la date du {{date_bilan}}.</p><p>Le rapport détaille les coûts totaux de possession (TCO), le taux de disponibilité, les incidents déclarés, l"analyse des consommations de carburant et les recommandations de renouvellement de parc.</p></div>`,
  },
  {
    code: 'auto_mobilite_durable',
    name: "Charte de Mobilité Durable Entreprise",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 25000,
    description: "Charte de mobilité durable pour entreprises ivoiriennes, promouvant l'utilisation de véhicules propres et la réduction de l'empreinte carbone.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'entreprise_mobilite', label: "Nom de l\"entreprise signataire", type: 'text', required: true },
      { key: 'dirigeant_mobilite', label: "Dirigeant signataire (nom et titre)", type: 'text', required: true },
      { key: 'objectifs_mobilite', label: "Objectifs de mobilité durable", type: 'textarea', required: true },
      { key: 'date_adoption', label: "Date d\"adoption de la charte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE MOBILITÉ DURABLE ENTREPRISE</h1><p><strong>{{entreprise_mobilite}}</strong>, représentée par <strong>{{dirigeant_mobilite}}</strong>, adopte la présente charte de mobilité durable le {{date_adoption}}.</p><p>Objectifs : {{objectifs_mobilite}}. L"entreprise s"engage à intégrer progressivement des véhicules hybrides et électriques dans sa flotte, à optimiser les déplacements professionnels et à sensibiliser ses collaborateurs aux enjeux de la mobilité durable en Côte d"Ivoire.</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 40b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
