import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  {
    code: 'cyber_pssi',
    name: "Politique de Sécurité des Systèmes d'Information (PSSI)",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Document cadre définissant les orientations stratégiques et les règles de sécurité des systèmes d'information de l'organisation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption", type: 'date', required: true },
      { key: 'responsable_securite', label: "Responsable sécurité (RSSI)", type: 'text', required: true },
      { key: 'perimetre_application', label: "Périmètre d'application", type: 'textarea', required: true },
      { key: 'version_document', label: "Version du document", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE SÉCURITÉ DES SYSTÈMES D'INFORMATION</h1><h2>{{nom_organisation}}</h2><p><strong>Version :</strong> {{version_document}} | <strong>Date d'adoption :</strong> {{date_adoption}}</p><p><strong>Responsable :</strong> {{responsable_securite}}</p><h2>1. OBJET ET PÉRIMÈTRE</h2><p>La présente Politique de Sécurité des Systèmes d'Information (PSSI) définit les orientations stratégiques, les principes directeurs et les règles de sécurité applicables au sein de {{nom_organisation}}.</p><p><strong>Périmètre d'application :</strong> {{perimetre_application}}</p><h2>2. ENJEUX ET OBJECTIFS</h2><p>La sécurité des systèmes d'information vise à garantir la confidentialité, l'intégrité et la disponibilité des données et des services informatiques.</p><h2>3. PRINCIPES FONDAMENTAUX</h2><p>3.1 Confidentialité : Les informations ne sont accessibles qu'aux personnes autorisées.</p><p>3.2 Intégrité : Les données ne peuvent être modifiées que par des personnes habilitées.</p><p>3.3 Disponibilité : Les systèmes sont accessibles aux utilisateurs autorisés au moment voulu.</p><h2>4. RESPONSABILITÉS</h2><p>La Direction Générale s'engage à soutenir la mise en oeuvre de cette politique. Le RSSI coordonne les actions de sécurité.</p><h2>5. SANCTIONS</h2><p>Tout manquement aux règles définies dans la présente PSSI est susceptible d'entraîner des sanctions disciplinaires.</p><p class="signature">Approuvé par la Direction Générale de {{nom_organisation}}</p></div>`,
  },
  {
    code: 'cyber_plan_reponse_incidents',
    name: "Plan de Réponse aux Incidents Cyber",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 35000,
    description: "Plan structuré définissant les procédures de détection, d'analyse, de confinement et de récupération suite à un incident de cybersécurité.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_incident', label: "Responsable gestion des incidents", type: 'text', required: true },
      { key: 'date_document', label: "Date du document", type: 'date', required: true },
      { key: 'contacts_urgence', label: "Contacts d'urgence", type: 'textarea', required: true },
      { key: 'classification_incidents', label: "Classification des niveaux d'incidents", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>PLAN DE RÉPONSE AUX INCIDENTS CYBER</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_document}} | <strong>Responsable :</strong> {{responsable_incident}}</p><h2>1. OBJECTIF</h2><p>Ce plan définit les procédures à suivre en cas d'incident de cybersécurité affectant les systèmes d'information de {{nom_organisation}}.</p><h2>2. CLASSIFICATION DES INCIDENTS</h2><p>{{classification_incidents}}</p><h2>3. PHASES DE RÉPONSE</h2><p><strong>Phase 1 - Détection :</strong> Identification et signalement de l'incident.</p><p><strong>Phase 2 - Analyse :</strong> Évaluation de l'impact et de la gravité.</p><p><strong>Phase 3 - Confinement :</strong> Isolation des systèmes compromis.</p><p><strong>Phase 4 - Éradication :</strong> Suppression de la menace.</p><p><strong>Phase 5 - Récupération :</strong> Restauration des services.</p><p><strong>Phase 6 - Retour d'expérience :</strong> Analyse post-incident et amélioration.</p><h2>4. CONTACTS D'URGENCE</h2><p>{{contacts_urgence}}</p><p class="signature">Document approuvé par {{responsable_incident}}</p></div>`,
  },
  {
    code: 'cyber_gestion_crise',
    name: "Procédure de Gestion de Crise Cyber",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Procédure opérationnelle de gestion d'une crise cybersécurité majeure, incluant la cellule de crise et la communication de crise.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'directeur_crise', label: "Directeur de crise", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'membres_cellule_crise', label: "Membres de la cellule de crise", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE GESTION DE CRISE CYBER</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Directeur de crise :</strong> {{directeur_crise}}</p><h2>1. DÉCLENCHEMENT DE LA CELLULE DE CRISE</h2><p>La cellule de crise est activée dès lors qu'un incident cyber est classifié de niveau critique ou majeur.</p><h2>2. COMPOSITION DE LA CELLULE DE CRISE</h2><p>{{membres_cellule_crise}}</p><h2>3. RÔLES ET RESPONSABILITÉS</h2><p><strong>Directeur de crise :</strong> {{directeur_crise}} - Coordination générale et prise de décision.</p><p><strong>RSSI :</strong> Analyse technique et recommandations.</p><p><strong>Direction Juridique :</strong> Obligations légales et notifications.</p><p><strong>Communication :</strong> Gestion des parties prenantes.</p><h2>4. COMMUNICATION DE CRISE</h2><p>La communication interne et externe est centralisée et validée par le directeur de crise avant diffusion.</p><h2>5. CLÔTURE DE LA CRISE</h2><p>La cellule de crise est dissoute après validation du retour à la normale et rédaction du rapport de post-crise.</p></div>`,
  },
  {
    code: 'cyber_audit_securite',
    name: "Rapport d'Audit de Sécurité Informatique",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 55000,
    description: "Rapport formel d'audit évaluant le niveau de sécurité des systèmes d'information, identifiant les vulnérabilités et recommandant des mesures correctives.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Organisation auditée", type: 'text', required: true },
      { key: 'auditeur', label: "Auditeur / Cabinet d'audit", type: 'text', required: true },
      { key: 'date_audit', label: "Date de l'audit", type: 'date', required: true },
      { key: 'perimetre_audit', label: "Périmètre de l'audit", type: 'textarea', required: true },
      { key: 'synthese_conclusions', label: "Synthèse des conclusions", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'AUDIT DE SÉCURITÉ INFORMATIQUE</h1><p><strong>Organisation :</strong> {{nom_organisation}}</p><p><strong>Auditeur :</strong> {{auditeur}} | <strong>Date :</strong> {{date_audit}}</p><h2>1. PÉRIMÈTRE DE L'AUDIT</h2><p>{{perimetre_audit}}</p><h2>2. MÉTHODOLOGIE</h2><p>L'audit a été conduit selon les référentiels ISO 27001, NIST Cybersecurity Framework et les bonnes pratiques ANSSI.</p><h2>3. SYNTHÈSE DES CONCLUSIONS</h2><p>{{synthese_conclusions}}</p><h2>4. CONSTATATIONS ET RISQUES</h2><p>Les vulnérabilités identifiées sont classifiées selon leur criticité : Critique, Haute, Moyenne, Faible.</p><h2>5. RECOMMANDATIONS</h2><p>Des mesures correctives prioritaires sont recommandées pour réduire le niveau de risque global.</p><h2>6. PLAN D'ACTION</h2><p>Un plan d'action avec les échéances de remédiation est joint en annexe.</p><p class="signature">Rapport établi par {{auditeur}}</p></div>`,
  },
  {
    code: 'cyber_pentest',
    name: "Rapport de Test d'Intrusion (Pentest)",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 60000,
    description: "Rapport technique détaillé des résultats d'un test d'intrusion (pentest) réalisé sur les systèmes d'information, avec les vulnérabilités découvertes et les recommandations.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 90,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Organisation testée", type: 'text', required: true },
      { key: 'prestataire_pentest', label: "Prestataire pentest", type: 'text', required: true },
      { key: 'date_test', label: "Date du test", type: 'date', required: true },
      { key: 'perimetre_test', label: "Périmètre du test", type: 'textarea', required: true },
      { key: 'type_test', label: "Type de test (boite noire/blanche/grise)", type: 'text', required: true },
      { key: 'score_risque_global', label: "Score de risque global", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE TEST D'INTRUSION (PENTEST)</h1><p><strong>Organisation :</strong> {{nom_organisation}} | <strong>Prestataire :</strong> {{prestataire_pentest}}</p><p><strong>Date :</strong> {{date_test}} | <strong>Type :</strong> {{type_test}}</p><h2>1. PÉRIMÈTRE DU TEST</h2><p>{{perimetre_test}}</p><h2>2. SCORE DE RISQUE GLOBAL</h2><p><strong>Score :</strong> {{score_risque_global}}</p><h2>3. MÉTHODOLOGIE</h2><p>Les tests ont été conduits selon la méthodologie OWASP, PTES et OSSTMM.</p><h2>4. VULNÉRABILITÉS IDENTIFIÉES</h2><p>Critiques : À corriger immédiatement. Hautes : À corriger sous 30 jours. Moyennes : À planifier. Faibles : À surveiller.</p><h2>5. PREUVES DE CONCEPT (PoC)</h2><p>Les preuves d'exploitation sont documentées et transmises de manière sécurisée.</p><h2>6. RECOMMANDATIONS</h2><p>Des contre-mesures spécifiques sont recommandées pour chaque vulnérabilité identifiée.</p><p class="signature">CONFIDENTIEL - {{prestataire_pentest}} pour {{nom_organisation}}</p></div>`,
  },
  {
    code: 'cyber_pci',
    name: "Plan de Continuité Informatique (PCI)",
    category: 'juridique_admin',
    price: 14000,
    priceMax: 40000,
    description: "Plan garantissant la continuité des services informatiques critiques en cas de sinistre ou d'incident majeur affectant les systèmes d'information.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_pci', label: "Responsable du PCI", type: 'text', required: true },
      { key: 'date_document', label: "Date du document", type: 'date', required: true },
      { key: 'systemes_critiques', label: "Systèmes informatiques critiques", type: 'textarea', required: true },
      { key: 'rto_rpo', label: "Objectifs RTO et RPO", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE CONTINUITÉ INFORMATIQUE (PCI)</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_document}} | <strong>Responsable :</strong> {{responsable_pci}}</p><h2>1. OBJECTIFS</h2><p>Le PCI vise à maintenir ou restaurer rapidement les services informatiques essentiels en cas d'incident majeur.</p><h2>2. SYSTÈMES CRITIQUES</h2><p>{{systemes_critiques}}</p><h2>3. OBJECTIFS DE CONTINUITÉ</h2><p>{{rto_rpo}}</p><h2>4. STRATÉGIES DE CONTINUITÉ</h2><p>Des solutions de redondance, de basculement et de reprise sont définies pour chaque système critique.</p><h2>5. TESTS ET EXERCICES</h2><p>Le PCI est testé au minimum une fois par an par simulation d'incident.</p><p class="signature">Approuvé par {{responsable_pci}} - {{nom_organisation}}</p></div>`,
  },
  {
    code: 'cyber_pri',
    name: "Plan de Reprise Informatique (PRI)",
    category: 'juridique_admin',
    price: 13000,
    priceMax: 38000,
    description: "Plan détaillant les procédures techniques de restauration des systèmes informatiques après un sinistre ou une interruption majeure.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_reprise', label: "Responsable de la reprise", type: 'text', required: true },
      { key: 'date_document', label: "Date du document", type: 'date', required: true },
      { key: 'site_reprise', label: "Site de reprise / environnement de secours", type: 'text', required: true },
      { key: 'procedures_restauration', label: "Procédures de restauration prioritaires", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE REPRISE INFORMATIQUE (PRI)</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_document}} | <strong>Responsable :</strong> {{responsable_reprise}}</p><h2>1. OBJECTIF</h2><p>Le PRI définit les étapes techniques permettant de restaurer les systèmes d'information après un sinistre.</p><h2>2. SITE DE REPRISE</h2><p>{{site_reprise}}</p><h2>3. PROCÉDURES DE RESTAURATION</h2><p>{{procedures_restauration}}</p><h2>4. ORDRE DE PRIORITÉ DE REPRISE</h2><p>Les systèmes sont restaurés dans l'ordre défini par leur criticité métier.</p><h2>5. VALIDATION DE LA REPRISE</h2><p>Chaque service restauré fait l'objet de tests de validation avant remise en production.</p><p class="signature">Document établi par {{responsable_reprise}} - {{nom_organisation}}</p></div>`,
  },
  {
    code: 'cyber_charte_utilisation_si',
    name: "Charte d'Utilisation des Systèmes Informatiques",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 20000,
    description: "Charte définissant les règles d'usage des systèmes informatiques et des ressources numériques de l'organisation par les employés.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entrée en vigueur", type: 'date', required: true },
      { key: 'ressources_concernees', label: "Ressources informatiques concernées", type: 'textarea', required: true },
      { key: 'sanctions_applicables', label: "Sanctions en cas de manquement", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE D'UTILISATION DES SYSTÈMES INFORMATIQUES</h1><h2>{{nom_organisation}}</h2><p><strong>Date d'entrée en vigueur :</strong> {{date_entree_vigueur}}</p><h2>1. OBJET</h2><p>La présente charte définit les règles d'utilisation des ressources informatiques mises à disposition des utilisateurs par {{nom_organisation}}.</p><h2>2. RESSOURCES CONCERNÉES</h2><p>{{ressources_concernees}}</p><h2>3. RÈGLES D'UTILISATION</h2><p>3.1 Les ressources informatiques sont destinées à un usage professionnel.</p><p>3.2 Tout accès non autorisé est interdit.</p><p>3.3 Les mots de passe sont personnels et confidentiels.</p><p>3.4 L'installation de logiciels non autorisés est prohibée.</p><h2>4. CONFIDENTIALITÉ</h2><p>L'utilisateur s'engage à respecter la confidentialité des informations auxquelles il a accès.</p><h2>5. SANCTIONS</h2><p>{{sanctions_applicables}}</p><p class="signature">J'ai pris connaissance de la présente charte et m'engage à la respecter.</p></div>`,
  },
  {
    code: 'cyber_sla_securite',
    name: "Accord de Niveau de Service Sécurité (SLA Sécurité)",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Accord contractuel définissant les niveaux de service attendus en matière de cybersécurité entre un prestataire et son client.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_prestataire', label: "Nom du prestataire de sécurité", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'niveaux_service', label: "Niveaux de service définis", type: 'textarea', required: true },
      { key: 'penalites', label: "Pénalités en cas de non-respect", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE NIVEAU DE SERVICE SÉCURITÉ (SLA SÉCURITÉ)</h1><p><strong>Prestataire :</strong> {{nom_prestataire}} | <strong>Client :</strong> {{nom_client}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>1. OBJET</h2><p>Le présent accord définit les niveaux de service en cybersécurité fournis par {{nom_prestataire}} à {{nom_client}}.</p><h2>2. NIVEAUX DE SERVICE</h2><p>{{niveaux_service}}</p><h2>3. INDICATEURS DE PERFORMANCE</h2><p>Les performances sont mesurées mensuellement et font l'objet d'un rapport partagé.</p><h2>4. PÉNALITÉS</h2><p>{{penalites}}</p><h2>5. RÉVISION</h2><p>Le présent accord est révisable annuellement ou en cas de changement majeur du périmètre.</p><p class="signature">Signatures des parties : {{nom_prestataire}} / {{nom_client}}</p></div>`,
  },
  {
    code: 'cyber_contrat_mssp',
    name: "Contrat MSSP (Prestataire de Sécurité Managée)",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 55000,
    description: "Contrat encadrant la prestation de services de sécurité gérés (MSSP), incluant la surveillance, la détection et la réponse aux incidents.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'nom_mssp', label: "Nom du MSSP", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
      { key: 'services_inclus', label: "Services de sécurité inclus", type: 'textarea', required: true },
      { key: 'duree_contrat', label: "Durée du contrat", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICES DE SÉCURITÉ MANAGÉE (MSSP)</h1><p><strong>MSSP :</strong> {{nom_mssp}} | <strong>Client :</strong> {{nom_client}}</p><p><strong>Date :</strong> {{date_contrat}} | <strong>Durée :</strong> {{duree_contrat}}</p><h2>1. OBJET DU CONTRAT</h2><p>{{nom_mssp}} s'engage à fournir des services de sécurité managée à {{nom_client}} dans les conditions définies ci-après.</p><h2>2. SERVICES INCLUS</h2><p>{{services_inclus}}</p><h2>3. OBLIGATIONS DU MSSP</h2><p>Surveillance 24h/24, 7j/7. Détection et qualification des alertes. Réponse aux incidents selon les SLA définis.</p><h2>4. OBLIGATIONS DU CLIENT</h2><p>Fourniture des accès nécessaires. Coopération en cas d'incident. Paiement des prestations selon l'échéancier.</p><h2>5. CONFIDENTIALITÉ</h2><p>Toutes les informations échangées sont strictement confidentielles.</p><p class="signature">Signatures : {{nom_mssp}} / {{nom_client}}</p></div>`,
  },
  {
    code: 'cyber_iam',
    name: "Procédure de Gestion des Accès et Identités (IAM)",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Procédure définissant les règles de gestion des identités numériques et des droits d'accès aux systèmes d'information.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_iam', label: "Responsable IAM", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'systemes_concernes', label: "Systèmes concernés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE GESTION DES ACCÈS ET IDENTITÉS (IAM)</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Responsable :</strong> {{responsable_iam}}</p><h2>1. OBJECTIF</h2><p>Cette procédure définit les règles de création, modification, suspension et suppression des accès aux systèmes d'information.</p><h2>2. SYSTÈMES CONCERNÉS</h2><p>{{systemes_concernes}}</p><h2>3. CYCLE DE VIE DES ACCÈS</h2><p><strong>Création :</strong> Sur demande validée par le responsable hiérarchique.</p><p><strong>Modification :</strong> En cas de changement de poste ou de périmètre.</p><p><strong>Suspension :</strong> En cas d'absence prolongée ou de départ temporaire.</p><p><strong>Suppression :</strong> Immédiate en cas de départ définitif.</p><h2>4. PRINCIPE DU MOINDRE PRIVILÈGE</h2><p>Chaque utilisateur dispose uniquement des droits nécessaires à l'exercice de ses fonctions.</p><h2>5. REVUE DES ACCÈS</h2><p>Une revue des droits d'accès est effectuée semestriellement.</p></div>`,
  },
  {
    code: 'cyber_politique_sauvegarde',
    name: "Politique de Sauvegarde des Données",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Politique définissant les règles et procédures de sauvegarde des données informatiques de l'organisation.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_sauvegarde', label: "Responsable des sauvegardes", type: 'text', required: true },
      { key: 'date_politique', label: "Date de la politique", type: 'date', required: true },
      { key: 'frequence_sauvegardes', label: "Fréquence et types de sauvegardes", type: 'textarea', required: true },
      { key: 'duree_retention', label: "Durée de rétention des sauvegardes", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE SAUVEGARDE DES DONNÉES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_politique}} | <strong>Responsable :</strong> {{responsable_sauvegarde}}</p><h2>1. OBJECTIF</h2><p>Garantir la disponibilité et l'intégrité des données de {{nom_organisation}} en cas de sinistre ou d'incident.</p><h2>2. FRÉQUENCE ET TYPES DE SAUVEGARDES</h2><p>{{frequence_sauvegardes}}</p><h2>3. DURÉE DE RÉTENTION</h2><p>{{duree_retention}}</p><h2>4. RÈGLE 3-2-1</h2><p>3 copies des données, sur 2 supports différents, dont 1 hors site.</p><h2>5. TESTS DE RESTAURATION</h2><p>Les sauvegardes sont testées trimestriellement pour vérifier leur intégrité et leur capacité de restauration.</p><h2>6. CHIFFREMENT</h2><p>Les sauvegardes sont chiffrées pour protéger la confidentialité des données.</p></div>`,
  },
  {
    code: 'cyber_gestion_vulnerabilites',
    name: "Procédure de Gestion des Vulnérabilités",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Procédure définissant le processus d'identification, d'évaluation et de remédiation des vulnérabilités affectant les systèmes d'information.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_vulnerabilites', label: "Responsable gestion des vulnérabilités", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'outils_scan', label: "Outils de scan utilisés", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE GESTION DES VULNÉRABILITÉS</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Responsable :</strong> {{responsable_vulnerabilites}}</p><h2>1. OBJECTIF</h2><p>Identifier, évaluer, prioriser et remédier aux vulnérabilités affectant les systèmes d'information.</p><h2>2. IDENTIFICATION</h2><p>Scans automatisés réguliers et veille sur les bulletins de sécurité (CVE, CERT).</p><p><strong>Outils utilisés :</strong> {{outils_scan}}</p><h2>3. ÉVALUATION ET PRIORISATION</h2><p>Chaque vulnérabilité est notée selon le score CVSS et l'exposition du système.</p><h2>4. REMÉDIATION</h2><p>Critique : 24-48h. Haute : 7 jours. Moyenne : 30 jours. Faible : 90 jours.</p><h2>5. SUIVI ET REPORTING</h2><p>Un tableau de bord des vulnérabilités est maintenu à jour et présenté mensuellement.</p></div>`,
  },
  {
    code: 'cyber_rapport_siem',
    name: "Rapport de Surveillance SIEM",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Rapport périodique de surveillance des événements de sécurité collectés et analysés par le système SIEM de l'organisation.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'solution_siem', label: "Solution SIEM utilisée", type: 'text', required: true },
      { key: 'synthese_alertes', label: "Synthèse des alertes et incidents", type: 'textarea', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE SURVEILLANCE SIEM</h1><h2>{{nom_organisation}}</h2><p><strong>Période :</strong> {{periode_rapport}} | <strong>Date :</strong> {{date_rapport}}</p><p><strong>Solution SIEM :</strong> {{solution_siem}}</p><h2>1. SYNTHÈSE DE LA PÉRIODE</h2><p>{{synthese_alertes}}</p><h2>2. STATISTIQUES DES ÉVÉNEMENTS</h2><p>Nombre total d'événements collectés, alertes générées, incidents qualifiés, faux positifs.</p><h2>3. INCIDENTS NOTABLES</h2><p>Description des incidents significatifs détectés et des actions prises.</p><h2>4. INDICATEURS DE PERFORMANCE</h2><p>Temps moyen de détection (MTTD), temps moyen de réponse (MTTR).</p><h2>5. RECOMMANDATIONS</h2><p>Ajustements des règles de corrélation et améliorations recommandées.</p></div>`,
  },
  {
    code: 'cyber_chiffrement_donnees',
    name: "Procédure de Chiffrement des Données Sensibles",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Procédure définissant les règles et méthodes de chiffrement des données sensibles de l'organisation, au repos et en transit.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_chiffrement', label: "Responsable du chiffrement", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'donnees_concernees', label: "Catégories de données à chiffrer", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE CHIFFREMENT DES DONNÉES SENSIBLES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Responsable :</strong> {{responsable_chiffrement}}</p><h2>1. OBJECTIF</h2><p>Protéger la confidentialité des données sensibles par le chiffrement.</p><h2>2. DONNÉES CONCERNÉES</h2><p>{{donnees_concernees}}</p><h2>3. ALGORITHMES ET STANDARDS</h2><p><strong>Données au repos :</strong> AES-256. <strong>Données en transit :</strong> TLS 1.2 minimum. <strong>Mots de passe :</strong> bcrypt ou Argon2.</p><h2>4. GESTION DES CLÉS</h2><p>Les clés de chiffrement sont gérées dans un système de gestion des clés (KMS) dédié.</p><h2>5. CAS PARTICULIERS</h2><p>Les dispositifs mobiles et les supports amovibles doivent être chiffrés intégralement.</p></div>`,
  },
  {
    code: 'cyber_sensibilisation',
    name: "Plan de Sensibilisation à la Cybersécurité",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Plan définissant le programme de formation et de sensibilisation des employés aux enjeux et bonnes pratiques de la cybersécurité.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_sensibilisation', label: "Responsable du programme", type: 'text', required: true },
      { key: 'annee_programme', label: "Année du programme", type: 'text', required: true },
      { key: 'actions_prevues', label: "Actions de sensibilisation prévues", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE SENSIBILISATION À LA CYBERSÉCURITÉ</h1><h2>{{nom_organisation}} - Année {{annee_programme}}</h2><p><strong>Responsable :</strong> {{responsable_sensibilisation}}</p><h2>1. OBJECTIFS DU PROGRAMME</h2><p>Développer une culture de la cybersécurité au sein de {{nom_organisation}} et réduire les risques liés au facteur humain.</p><h2>2. PUBLIC CIBLE</h2><p>Tous les employés, selon des modules adaptés à leur niveau de responsabilité.</p><h2>3. ACTIONS PRÉVUES</h2><p>{{actions_prevues}}</p><h2>4. THÈMES PRIORITAIRES</h2><p>Phishing, mots de passe, confidentialité des données, utilisation des réseaux sociaux, protection des équipements mobiles.</p><h2>5. ÉVALUATION</h2><p>Tests de phishing simulés, quiz de sensibilisation, indicateurs de comportement.</p></div>`,
  },
  {
    code: 'cyber_teletravail_securise',
    name: "Charte de Télétravail Sécurisé",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Charte définissant les règles de sécurité informatique applicables aux employés en situation de télétravail.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entrée en vigueur", type: 'date', required: true },
      { key: 'equipements_autorises', label: "Équipements autorisés en télétravail", type: 'textarea', required: true },
      { key: 'regles_connexion', label: "Règles de connexion sécurisée", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE TÉLÉTRAVAIL SÉCURISÉ</h1><h2>{{nom_organisation}}</h2><p><strong>Date d'entrée en vigueur :</strong> {{date_entree_vigueur}}</p><h2>1. OBJECTIF</h2><p>Garantir la sécurité des systèmes d'information lors de l'exercice du télétravail.</p><h2>2. ÉQUIPEMENTS AUTORISÉS</h2><p>{{equipements_autorises}}</p><h2>3. CONNEXION SÉCURISÉE</h2><p>{{regles_connexion}}</p><h2>4. RÈGLES D'USAGE EN TÉLÉTRAVAIL</h2><p>Utilisation du VPN obligatoire. Verrouillage de l'écran en cas d'absence. Interdiction d'utiliser les réseaux Wi-Fi publics non sécurisés.</p><h2>5. CONFIDENTIALITÉ</h2><p>Le télétravailleur s'engage à préserver la confidentialité des données professionnelles dans son environnement de travail à domicile.</p><p class="signature">Signé par l'employé et validé par la DSI</p></div>`,
  },
  {
    code: 'cyber_bug_bounty',
    name: "Accord de Bug Bounty",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Accord encadrant le programme de divulgation responsable des vulnérabilités (bug bounty), définissant les règles, récompenses et périmètres.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'perimetre_programme', label: "Périmètre du programme (in-scope)", type: 'textarea', required: true },
      { key: 'grille_recompenses', label: "Grille des récompenses", type: 'textarea', required: true },
      { key: 'regles_engagement', label: "Règles d'engagement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE BUG BOUNTY - PROGRAMME DE DIVULGATION RESPONSABLE</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_accord}}</p><h2>1. OBJECTIF</h2><p>{{nom_organisation}} encourage la divulgation responsable des vulnérabilités de sécurité affectant ses systèmes.</p><h2>2. PÉRIMÈTRE</h2><p>{{perimetre_programme}}</p><h2>3. RÈGLES D'ENGAGEMENT</h2><p>{{regles_engagement}}</p><h2>4. GRILLE DES RÉCOMPENSES</h2><p>{{grille_recompenses}}</p><h2>5. PROCESSUS DE SIGNALEMENT</h2><p>Les vulnérabilités sont signalées de manière confidentielle à l'adresse sécurisée dédiée.</p><h2>6. ENGAGEMENTS DE L'ORGANISATION</h2><p>Accusé de réception sous 48h. Évaluation sous 7 jours. Versement de la récompense après correction validée.</p></div>`,
  },
  {
    code: 'cyber_soc_externalise',
    name: "Contrat de SOC Externalisé",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 60000,
    description: "Contrat encadrant la prestation d'un Centre Opérationnel de Sécurité (SOC) externalisé, avec les engagements de surveillance et de réponse.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'nom_prestataire_soc', label: "Nom du prestataire SOC", type: 'text', required: true },
      { key: 'nom_client', label: "Nom du client", type: 'text', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
      { key: 'perimetre_surveillance', label: "Périmètre de surveillance", type: 'textarea', required: true },
      { key: 'engagements_sla', label: "Engagements SLA du SOC", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SOC EXTERNALISÉ</h1><p><strong>Prestataire SOC :</strong> {{nom_prestataire_soc}} | <strong>Client :</strong> {{nom_client}}</p><p><strong>Date :</strong> {{date_contrat}}</p><h2>1. OBJET</h2><p>Le présent contrat définit les conditions de la prestation de Centre Opérationnel de Sécurité (SOC) assurée par {{nom_prestataire_soc}}.</p><h2>2. PÉRIMÈTRE DE SURVEILLANCE</h2><p>{{perimetre_surveillance}}</p><h2>3. PRESTATIONS INCLUSES</h2><p>Surveillance 24h/24, 7j/7. Détection des incidents. Qualification et escalade. Réponse initiale aux incidents.</p><h2>4. ENGAGEMENTS SLA</h2><p>{{engagements_sla}}</p><h2>5. REPORTING</h2><p>Rapport hebdomadaire et mensuel transmis au client. Comité de pilotage trimestriel.</p><p class="signature">Signatures : {{nom_prestataire_soc}} / {{nom_client}}</p></div>`,
  },
  {
    code: 'cyber_gestion_incidents_cert',
    name: "Procédure de Gestion des Incidents CERT",
    category: 'juridique_admin',
    price: 11000,
    priceMax: 33000,
    description: "Procédure opérationnelle du CERT (Computer Emergency Response Team) pour la gestion et la coordination des incidents de sécurité.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation / CERT", type: 'text', required: true },
      { key: 'responsable_cert', label: "Responsable CERT", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'perimetre_intervention', label: "Périmètre d'intervention du CERT", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE GESTION DES INCIDENTS CERT</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Responsable CERT :</strong> {{responsable_cert}}</p><h2>1. MISSION DU CERT</h2><p>Le CERT de {{nom_organisation}} assure la coordination de la réponse aux incidents de cybersécurité.</p><h2>2. PÉRIMÈTRE D'INTERVENTION</h2><p>{{perimetre_intervention}}</p><h2>3. PROCESSUS DE TRAITEMENT DES INCIDENTS</h2><p>Réception et triage. Analyse et qualification. Coordination de la réponse. Communication aux parties prenantes. Clôture et capitalisation.</p><h2>4. COORDINATION EXTERNE</h2><p>Coopération avec les CERT nationaux et sectoriels, les autorités compétentes et les partenaires.</p><h2>5. CLASSIFICATION TLP</h2><p>Les informations échangées sont classifiées selon le protocole TLP (Traffic Light Protocol).</p></div>`,
  },
  {
    code: 'cyber_maturite',
    name: "Rapport de Maturité Cybersécurité",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Rapport évaluant le niveau de maturité cybersécurité de l'organisation selon un référentiel reconnu (CMMI, ISO 27001, NIST CSF).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'evaluateur', label: "Évaluateur", type: 'text', required: true },
      { key: 'date_evaluation', label: "Date de l'évaluation", type: 'date', required: true },
      { key: 'referentiel', label: "Référentiel utilisé", type: 'text', required: true },
      { key: 'score_maturite', label: "Score de maturité global", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE MATURITÉ CYBERSÉCURITÉ</h1><h2>{{nom_organisation}}</h2><p><strong>Évaluateur :</strong> {{evaluateur}} | <strong>Date :</strong> {{date_evaluation}}</p><p><strong>Référentiel :</strong> {{referentiel}} | <strong>Score global :</strong> {{score_maturite}}</p><h2>1. MÉTHODOLOGIE D'ÉVALUATION</h2><p>L'évaluation est conduite selon le référentiel {{referentiel}} sur les cinq domaines clés de la cybersécurité.</p><h2>2. RÉSULTATS PAR DOMAINE</h2><p>Gouvernance. Identification des risques. Protection. Détection. Réponse et récupération.</p><h2>3. POINTS FORTS</h2><p>Identification des pratiques matures et des bonnes pratiques en place.</p><h2>4. AXES D'AMÉLIORATION</h2><p>Recommandations priorisées pour progresser vers le niveau de maturité cible.</p><h2>5. FEUILLE DE ROUTE</h2><p>Plan d'action sur 12, 24 et 36 mois pour atteindre les objectifs de maturité.</p></div>`,
  },
  {
    code: 'cyber_patch_management',
    name: "Plan de Patch Management",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Plan définissant le processus de gestion des correctifs de sécurité pour maintenir les systèmes à jour et réduire les vulnérabilités.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_patches', label: "Responsable patch management", type: 'text', required: true },
      { key: 'date_document', label: "Date du document", type: 'date', required: true },
      { key: 'inventaire_systemes', label: "Inventaire des systèmes concernés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE PATCH MANAGEMENT</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_document}} | <strong>Responsable :</strong> {{responsable_patches}}</p><h2>1. OBJECTIF</h2><p>Garantir la mise à jour régulière des systèmes pour corriger les vulnérabilités connues.</p><h2>2. INVENTAIRE DES SYSTÈMES</h2><p>{{inventaire_systemes}}</p><h2>3. PROCESSUS DE DÉPLOIEMENT</h2><p>Veille. Évaluation de criticité. Test en environnement de pré-production. Déploiement planifié. Vérification post-déploiement.</p><h2>4. DÉLAIS DE DÉPLOIEMENT</h2><p>Critique : 48-72h. Haute : 7 jours. Moyenne : 30 jours. Faible : 90 jours.</p><h2>5. EXCEPTIONS</h2><p>Les exceptions sont documentées et soumises à une analyse de risque compensatoire.</p></div>`,
  },
  {
    code: 'cyber_acces_physiques',
    name: "Procédure de Contrôle des Accès Physiques",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Procédure définissant les règles de contrôle d'accès physique aux locaux abritant les systèmes d'information sensibles.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_securite_physique', label: "Responsable sécurité physique", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'zones_protegees', label: "Zones protégées et niveaux de sécurité", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE CONTRÔLE DES ACCÈS PHYSIQUES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Responsable :</strong> {{responsable_securite_physique}}</p><h2>1. OBJECTIF</h2><p>Prévenir les accès non autorisés aux zones abritant les systèmes d'information et les données sensibles.</p><h2>2. ZONES PROTÉGÉES</h2><p>{{zones_protegees}}</p><h2>3. MESURES DE CONTRÔLE</h2><p>Badges d'accès nominatifs. Journalisation des accès. Vidéosurveillance. Accompagnement des visiteurs.</p><h2>4. PROCÉDURE VISITEURS</h2><p>Tout visiteur doit être enregistré, accompagné et équipé d'un badge visiteur visible.</p><h2>5. GESTION DES BADGES</h2><p>Les badges sont désactivés immédiatement en cas de perte ou de départ du collaborateur.</p></div>`,
  },
  {
    code: 'cyber_cti_partage',
    name: "Accord de Partage d'Informations sur les Menaces (CTI)",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Accord encadrant le partage d'informations sur les cybermenaces (Cyber Threat Intelligence) entre organisations partenaires.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'partie_a', label: "Organisation partie A", type: 'text', required: true },
      { key: 'partie_b', label: "Organisation partie B", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'types_informations', label: "Types d'informations échangées", type: 'textarea', required: true },
      { key: 'protocole_echange', label: "Protocole d'échange (TLP, STIX/TAXII)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTAGE D'INFORMATIONS SUR LES MENACES CYBER (CTI)</h1><p><strong>Partie A :</strong> {{partie_a}} | <strong>Partie B :</strong> {{partie_b}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>1. OBJET</h2><p>Le présent accord définit les conditions du partage réciproque d'informations sur les cybermenaces entre {{partie_a}} et {{partie_b}}.</p><h2>2. TYPES D'INFORMATIONS ÉCHANGÉES</h2><p>{{types_informations}}</p><h2>3. PROTOCOLE D'ÉCHANGE</h2><p>{{protocole_echange}}</p><h2>4. CONFIDENTIALITÉ</h2><p>Les informations échangées ne peuvent être partagées avec des tiers sans accord préalable des deux parties.</p><h2>5. RESPONSABILITÉ</h2><p>Chaque partie est responsable de l'utilisation qu'elle fait des informations reçues.</p><p class="signature">Signatures : {{partie_a}} / {{partie_b}}</p></div>`,
  },
  {
    code: 'cyber_conformite_iso27001',
    name: "Rapport de Conformité ISO 27001",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 55000,
    description: "Rapport évaluant la conformité de l'organisation aux exigences de la norme ISO 27001 pour la certification de son système de management de la sécurité de l'information.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'organisme_certification', label: "Organisme de certification", type: 'text', required: true },
      { key: 'date_audit', label: "Date de l'audit", type: 'date', required: true },
      { key: 'perimetre_smsi', label: "Périmètre du SMSI", type: 'textarea', required: true },
      { key: 'score_conformite', label: "Taux de conformité global (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE CONFORMITÉ ISO 27001</h1><h2>{{nom_organisation}}</h2><p><strong>Organisme :</strong> {{organisme_certification}} | <strong>Date :</strong> {{date_audit}}</p><p><strong>Taux de conformité global :</strong> {{score_conformite}}</p><h2>1. PÉRIMÈTRE DU SMSI</h2><p>{{perimetre_smsi}}</p><h2>2. RÉSULTATS PAR CLAUSE</h2><p>Clauses 4 à 10 évaluées avec le niveau de conformité pour chaque exigence.</p><h2>3. ANNEXE A - CONTRÔLES DE SÉCURITÉ</h2><p>Évaluation des 93 contrôles de l'annexe A de la norme ISO 27001:2022.</p><h2>4. NON-CONFORMITÉS MAJEURES</h2><p>Identification et description des non-conformités majeures requérant une action corrective.</p><h2>5. RECOMMANDATIONS</h2><p>Axes d'amélioration pour atteindre la certification ou le renouvellement.</p><p class="signature">Rapport établi par {{organisme_certification}}</p></div>`,
  },
  {
    code: 'rgpd_registre_traitements',
    name: "Registre des Activités de Traitement",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Document obligatoire répertoriant l'ensemble des traitements de données personnelles réalisés par l'organisation, conformément à l'article 30 du RGPD.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 90,
    fieldsJson: F([
      { key: 'nom_responsable_traitement', label: "Nom du responsable de traitement", type: 'text', required: true },
      { key: 'nom_dpo', label: "Nom du DPO (Délégué à la Protection des Données)", type: 'text', required: false },
      { key: 'date_mise_a_jour', label: "Date de mise à jour", type: 'date', required: true },
      { key: 'activites_traitement', label: "Activités de traitement (description)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>REGISTRE DES ACTIVITÉS DE TRAITEMENT</h1><h2>Article 30 du Règlement Général sur la Protection des Données (RGPD)</h2><p><strong>Responsable de traitement :</strong> {{nom_responsable_traitement}}</p><p><strong>DPO :</strong> {{nom_dpo}} | <strong>Dernière mise à jour :</strong> {{date_mise_a_jour}}</p><h2>ACTIVITÉS DE TRAITEMENT</h2><p>{{activites_traitement}}</p><h2>INFORMATIONS REQUISES PAR TRAITEMENT</h2><p>Finalités du traitement. Base légale. Catégories de personnes concernées. Catégories de données traitées. Destinataires des données. Transferts hors UE/CEDEAO. Durées de conservation. Mesures de sécurité.</p><p class="signature">Registre tenu par {{nom_responsable_traitement}} - Document confidentiel</p></div>`,
  },
  {
    code: 'rgpd_aipd',
    name: "Analyse d'Impact Relative à la Protection des Données (AIPD)",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Analyse obligatoire évaluant les risques pour les droits et libertés des personnes physiques liés à un traitement de données personnelles à risque élevé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'nom_traitement', label: "Nom du traitement concerné", type: 'text', required: true },
      { key: 'date_aipd', label: "Date de l'AIPD", type: 'date', required: true },
      { key: 'description_traitement', label: "Description du traitement", type: 'textarea', required: true },
      { key: 'mesures_risques', label: "Mesures pour traiter les risques identifiés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ANALYSE D'IMPACT RELATIVE À LA PROTECTION DES DONNÉES (AIPD)</h1><h2>{{nom_organisation}}</h2><p><strong>Traitement :</strong> {{nom_traitement}} | <strong>Date :</strong> {{date_aipd}}</p><h2>1. DESCRIPTION DU TRAITEMENT</h2><p>{{description_traitement}}</p><h2>2. NÉCESSITÉ ET PROPORTIONNALITÉ</h2><p>Évaluation de la nécessité et de la proportionnalité du traitement au regard de sa finalité.</p><h2>3. IDENTIFICATION DES RISQUES</h2><p>Accès illégitime. Modification non désirée. Disparition des données.</p><h2>4. MESURES POUR TRAITER LES RISQUES</h2><p>{{mesures_risques}}</p><h2>5. AVIS DU DPO</h2><p>Le DPO a été consulté et a émis son avis sur la présente analyse d'impact.</p><p class="signature">Validé par le Responsable de traitement de {{nom_organisation}}</p></div>`,
  },
  {
    code: 'rgpd_politique_confidentialite',
    name: "Politique de Confidentialité (Externe)",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Document public informant les utilisateurs et clients de la manière dont leurs données personnelles sont collectées, utilisées et protégées.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 92,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_mise_a_jour', label: "Date de mise à jour", type: 'date', required: true },
      { key: 'contact_dpo', label: "Contact DPO / Protection des données", type: 'text', required: true },
      { key: 'donnees_collectees', label: "Données collectées et finalités", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE CONFIDENTIALITÉ</h1><h2>{{nom_organisation}}</h2><p><strong>Dernière mise à jour :</strong> {{date_mise_a_jour}}</p><h2>1. QUI SOMMES-NOUS ?</h2><p>{{nom_organisation}} est responsable du traitement de vos données personnelles dans le cadre de ses activités.</p><h2>2. DONNÉES COLLECTÉES ET FINALITÉS</h2><p>{{donnees_collectees}}</p><h2>3. VOS DROITS</h2><p>Conformément à la réglementation applicable, vous disposez des droits suivants : droit d'accès, de rectification, d'effacement, de limitation, d'opposition et de portabilité.</p><h2>4. CONSERVATION DES DONNÉES</h2><p>Vos données sont conservées pour la durée strictement nécessaire aux finalités pour lesquelles elles ont été collectées.</p><h2>5. CONTACT</h2><p>Pour exercer vos droits : {{contact_dpo}}</p></div>`,
  },
  {
    code: 'rgpd_politique_interne',
    name: "Politique de Protection des Données (Interne)",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Document interne définissant les règles et engagements de l'organisation en matière de protection des données personnelles pour ses collaborateurs.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption", type: 'date', required: true },
      { key: 'responsable_protection', label: "Responsable protection des données", type: 'text', required: true },
      { key: 'principes_traitement', label: "Principes de traitement appliqués", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE PROTECTION DES DONNÉES PERSONNELLES (INTERNE)</h1><h2>{{nom_organisation}}</h2><p><strong>Date d'adoption :</strong> {{date_adoption}} | <strong>Responsable :</strong> {{responsable_protection}}</p><h2>1. OBJET</h2><p>La présente politique définit les engagements de {{nom_organisation}} en matière de protection des données personnelles.</p><h2>2. PRINCIPES FONDAMENTAUX</h2><p>{{principes_traitement}}</p><h2>3. RESPONSABILITÉS</h2><p>Chaque collaborateur est responsable de la protection des données auxquelles il accède dans le cadre de ses fonctions.</p><h2>4. FORMATION ET SENSIBILISATION</h2><p>Une formation à la protection des données est dispensée à tous les nouveaux collaborateurs.</p><h2>5. SANCTIONS</h2><p>Le non-respect de cette politique peut entraîner des mesures disciplinaires.</p></div>`,
  },
  {
    code: 'rgpd_dpa_sous_traitance',
    name: "Accord de Sous-Traitance des Données Personnelles (DPA)",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Accord contractuel obligatoire entre un responsable de traitement et son sous-traitant, définissant les obligations de protection des données personnelles.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 87,
    fieldsJson: F([
      { key: 'nom_responsable_traitement', label: "Responsable de traitement", type: 'text', required: true },
      { key: 'nom_sous_traitant', label: "Sous-traitant", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'objet_traitement', label: "Objet et nature du traitement", type: 'textarea', required: true },
      { key: 'mesures_securite', label: "Mesures de sécurité mises en oeuvre", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SOUS-TRAITANCE DES DONNÉES PERSONNELLES (DPA)</h1><p><strong>Responsable de traitement :</strong> {{nom_responsable_traitement}}</p><p><strong>Sous-traitant :</strong> {{nom_sous_traitant}} | <strong>Date :</strong> {{date_accord}}</p><h2>1. OBJET ET NATURE DU TRAITEMENT</h2><p>{{objet_traitement}}</p><h2>2. OBLIGATIONS DU SOUS-TRAITANT</h2><p>Traiter les données uniquement sur instruction documentée. Ne pas recruter de sous-traitants ultérieurs sans autorisation. Garantir la sécurité des données. Aider le responsable à répondre aux droits des personnes. Supprimer ou restituer les données en fin de contrat.</p><h2>3. MESURES DE SÉCURITÉ</h2><p>{{mesures_securite}}</p><h2>4. NOTIFICATION DES VIOLATIONS</h2><p>Toute violation de données est notifiée au responsable de traitement dans un délai de 72 heures.</p><p class="signature">Signatures : {{nom_responsable_traitement}} / {{nom_sous_traitant}}</p></div>`,
  },
  {
    code: 'rgpd_transfert_hors_ue',
    name: "Accord de Transfert de Données Hors UE/CEDEAO",
    category: 'juridique_admin',
    price: 13000,
    priceMax: 39000,
    description: "Accord encadrant le transfert de données personnelles vers des pays n'offrant pas un niveau de protection adéquat, incluant les clauses contractuelles types.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'exportateur_donnees', label: "Exportateur de données", type: 'text', required: true },
      { key: 'importateur_donnees', label: "Importateur de données", type: 'text', required: true },
      { key: 'pays_destination', label: "Pays de destination des données", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'garanties_adequation', label: "Garanties d'adéquation ou mécanisme de transfert", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSFERT DE DONNÉES PERSONNELLES HORS UE/CEDEAO</h1><p><strong>Exportateur :</strong> {{exportateur_donnees}} | <strong>Importateur :</strong> {{importateur_donnees}}</p><p><strong>Pays de destination :</strong> {{pays_destination}} | <strong>Date :</strong> {{date_accord}}</p><h2>1. OBJET</h2><p>Le présent accord encadre le transfert de données personnelles vers {{pays_destination}}, en l'absence de décision d'adéquation.</p><h2>2. GARANTIES DE TRANSFERT</h2><p>{{garanties_adequation}}</p><h2>3. DROITS DES PERSONNES CONCERNÉES</h2><p>L'importateur s'engage à permettre l'exercice des droits des personnes concernées.</p><h2>4. RECOURS EN CAS DE VIOLATION</h2><p>Les mécanismes de recours disponibles pour les personnes concernées sont précisés.</p><p class="signature">Signatures : {{exportateur_donnees}} / {{importateur_donnees}}</p></div>`,
  },
  {
    code: 'rgpd_charte_employes',
    name: "Charte de Protection des Données des Employés",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Charte informant les employés sur le traitement de leurs données personnelles dans le cadre de leur relation de travail.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'nom_employeur', label: "Nom de l'employeur", type: 'text', required: true },
      { key: 'date_document', label: "Date du document", type: 'date', required: true },
      { key: 'donnees_rh_traitees', label: "Données RH traitées", type: 'textarea', required: true },
      { key: 'contact_exercice_droits', label: "Contact pour exercer vos droits", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE PROTECTION DES DONNÉES DES EMPLOYÉS</h1><h2>{{nom_employeur}}</h2><p><strong>Date :</strong> {{date_document}}</p><h2>1. INTRODUCTION</h2><p>{{nom_employeur}} traite des données personnelles vous concernant dans le cadre de la gestion de la relation de travail.</p><h2>2. DONNÉES TRAITÉES</h2><p>{{donnees_rh_traitees}}</p><h2>3. FINALITÉS DU TRAITEMENT</h2><p>Gestion de la paie. Administration du personnel. Formation. Évaluation des performances. Obligations légales.</p><h2>4. VOS DROITS</h2><p>Vous disposez des droits d'accès, de rectification, d'opposition et de portabilité.</p><h2>5. CONTACT</h2><p>Pour exercer vos droits : {{contact_exercice_droits}}</p></div>`,
  },
  {
    code: 'rgpd_gestion_droits_personnes',
    name: "Procédure de Gestion des Droits des Personnes",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Procédure définissant le processus de réception et de traitement des demandes d'exercice des droits des personnes concernées par les traitements de données.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 81,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'point_contact_droits', label: "Point de contact pour les droits", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'delai_traitement', label: "Délai de traitement des demandes", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE GESTION DES DROITS DES PERSONNES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Contact :</strong> {{point_contact_droits}}</p><h2>1. DROITS RECONNUS</h2><p>Droit d'accès (Art. 15). Droit de rectification (Art. 16). Droit à l'effacement (Art. 17). Droit à la limitation (Art. 18). Droit à la portabilité (Art. 20). Droit d'opposition (Art. 21).</p><h2>2. PROCESSUS DE TRAITEMENT</h2><p>Réception de la demande. Vérification de l'identité du demandeur. Traitement et réponse dans le délai réglementaire. Documentation de la demande.</p><h2>3. DÉLAIS DE RÉPONSE</h2><p>{{delai_traitement}}</p><h2>4. CAS DE REFUS</h2><p>En cas de refus, la personne est informée des motifs et des voies de recours disponibles.</p></div>`,
  },
  {
    code: 'rgpd_notification_violation',
    name: "Procédure de Notification de Violation de Données",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Procédure définissant les étapes de détection, d'évaluation et de notification d'une violation de données personnelles à l'autorité de contrôle et aux personnes concernées.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'autorite_controle', label: "Autorité de contrôle compétente", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'responsable_notification', label: "Responsable de la notification", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE NOTIFICATION DE VIOLATION DE DONNÉES PERSONNELLES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Autorité :</strong> {{autorite_controle}}</p><h2>1. DÉTECTION ET QUALIFICATION</h2><p>Toute personne suspectant ou constatant une violation de données doit le signaler immédiatement à {{responsable_notification}}.</p><h2>2. ÉVALUATION DE LA GRAVITÉ</h2><p>Évaluation du risque pour les droits et libertés des personnes concernées.</p><h2>3. NOTIFICATION À L'AUTORITÉ DE CONTRÔLE</h2><p>Si le risque est avéré, notification à {{autorite_controle}} dans les 72 heures suivant la prise de connaissance.</p><h2>4. NOTIFICATION AUX PERSONNES CONCERNÉES</h2><p>Si le risque est élevé, notification directe aux personnes concernées dans les meilleurs délais.</p><h2>5. DOCUMENTATION</h2><p>Toute violation est documentée dans le registre des violations, même si elle ne fait pas l'objet d'une notification.</p></div>`,
  },
  {
    code: 'rgpd_audit_conformite',
    name: "Rapport d'Audit Conformité Protection des Données",
    category: 'juridique_admin',
    price: 14000,
    priceMax: 42000,
    description: "Rapport d'audit évaluant la conformité de l'organisation aux exigences de la réglementation sur la protection des données personnelles.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Organisation auditée", type: 'text', required: true },
      { key: 'auditeur', label: "Auditeur", type: 'text', required: true },
      { key: 'date_audit', label: "Date de l'audit", type: 'date', required: true },
      { key: 'perimetre_audit', label: "Périmètre de l'audit", type: 'textarea', required: true },
      { key: 'taux_conformite', label: "Taux de conformité global", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'AUDIT CONFORMITÉ PROTECTION DES DONNÉES</h1><h2>{{nom_organisation}}</h2><p><strong>Auditeur :</strong> {{auditeur}} | <strong>Date :</strong> {{date_audit}}</p><p><strong>Taux de conformité :</strong> {{taux_conformite}}</p><h2>1. PÉRIMÈTRE DE L'AUDIT</h2><p>{{perimetre_audit}}</p><h2>2. RÉSULTATS PAR DOMAINE</h2><p>Base légale des traitements. Droits des personnes. Sécurité des données. Sous-traitance. Transferts internationaux. Registre des traitements.</p><h2>3. NON-CONFORMITÉS IDENTIFIÉES</h2><p>Description des écarts constatés et de leur impact.</p><h2>4. PLAN DE REMÉDIATION</h2><p>Actions correctives recommandées avec priorités et délais.</p><p class="signature">Rapport établi par {{auditeur}}</p></div>`,
  },
  {
    code: 'rgpd_plan_conformite',
    name: "Plan de Mise en Conformité RGPD",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Plan structuré définissant les étapes et actions pour mettre l'organisation en conformité avec le RGPD et les réglementations locales sur la protection des données.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_projet', label: "Responsable du projet de conformité", type: 'text', required: true },
      { key: 'date_lancement', label: "Date de lancement du projet", type: 'date', required: true },
      { key: 'etat_des_lieux', label: "État des lieux initial", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE MISE EN CONFORMITÉ RGPD</h1><h2>{{nom_organisation}}</h2><p><strong>Responsable :</strong> {{responsable_projet}} | <strong>Lancement :</strong> {{date_lancement}}</p><h2>1. ÉTAT DES LIEUX</h2><p>{{etat_des_lieux}}</p><h2>2. ÉTAPES DU PROJET</h2><p>Étape 1 : Cartographie des traitements. Étape 2 : Analyse des bases légales. Étape 3 : Mise à jour des documents. Étape 4 : Sécurisation des données. Étape 5 : Formation des équipes. Étape 6 : Mise en place des procédures.</p><h2>3. GOUVERNANCE</h2><p>Désignation du DPO. Comité de pilotage. Reporting régulier à la Direction.</p><h2>4. CALENDRIER</h2><p>Jalons et dates cibles pour chaque étape du projet de conformité.</p></div>`,
  },
  {
    code: 'rgpd_contrat_dpo',
    name: "Contrat de Délégué à la Protection des Données (DPO)",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Contrat formalisant la mission du Délégué à la Protection des Données (DPO), qu'il soit interne ou externe à l'organisation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'nom_dpo', label: "Nom du DPO", type: 'text', required: true },
      { key: 'date_prise_fonction', label: "Date de prise de fonction", type: 'date', required: true },
      { key: 'missions_dpo', label: "Missions du DPO", type: 'textarea', required: true },
      { key: 'statut_dpo', label: "Statut du DPO (interne / externe)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT / LETTRE DE MISSION - DÉLÉGUÉ À LA PROTECTION DES DONNÉES (DPO)</h1><p><strong>Organisation :</strong> {{nom_organisation}} | <strong>DPO :</strong> {{nom_dpo}}</p><p><strong>Date de prise de fonction :</strong> {{date_prise_fonction}} | <strong>Statut :</strong> {{statut_dpo}}</p><h2>1. DÉSIGNATION</h2><p>{{nom_organisation}} désigne {{nom_dpo}} en qualité de Délégué à la Protection des Données conformément à l'article 37 du RGPD.</p><h2>2. MISSIONS</h2><p>{{missions_dpo}}</p><h2>3. INDÉPENDANCE</h2><p>Le DPO exerce ses missions en toute indépendance. Il ne reçoit aucune instruction concernant l'exercice de ses missions.</p><h2>4. RESSOURCES</h2><p>L'organisation met à disposition du DPO les ressources nécessaires à l'exercice de ses missions.</p><h2>5. PROTECTION CONTRE LES SANCTIONS</h2><p>Le DPO ne peut être sanctionné pour l'exercice de ses missions.</p><p class="signature">Signatures : {{nom_organisation}} / {{nom_dpo}}</p></div>`,
  },
  {
    code: 'rgpd_politique_cookies',
    name: "Politique de Gestion des Cookies",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Document informant les utilisateurs des cookies et traceurs utilisés sur le site web, et définissant les modalités de recueil du consentement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'nom_site_web', label: "Nom / URL du site web", type: 'text', required: true },
      { key: 'nom_organisation', label: "Nom de l'organisation éditrice", type: 'text', required: true },
      { key: 'date_mise_a_jour', label: "Date de mise à jour", type: 'date', required: true },
      { key: 'types_cookies', label: "Types de cookies utilisés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE GESTION DES COOKIES</h1><h2>{{nom_site_web}} - {{nom_organisation}}</h2><p><strong>Dernière mise à jour :</strong> {{date_mise_a_jour}}</p><h2>1. QU'EST-CE QU'UN COOKIE ?</h2><p>Un cookie est un fichier texte déposé sur votre terminal lors de la visite d'un site web.</p><h2>2. COOKIES UTILISÉS</h2><p>{{types_cookies}}</p><h2>3. FINALITÉS</h2><p>Cookies strictement nécessaires au fonctionnement. Cookies de performance et d'analyse. Cookies de personnalisation. Cookies publicitaires.</p><h2>4. GESTION DE VOTRE CONSENTEMENT</h2><p>Vous pouvez paramétrer vos préférences en matière de cookies à tout moment via notre gestionnaire de cookies.</p><h2>5. DURÉE DE CONSERVATION</h2><p>Les cookies sont conservés pour une durée maximale de 13 mois.</p></div>`,
  },
  {
    code: 'rgpd_co_responsabilite',
    name: "Accord de Co-Responsabilité de Traitement",
    category: 'juridique_admin',
    price: 11000,
    priceMax: 33000,
    description: "Accord entre deux responsables conjoints de traitement définissant leurs rôles et responsabilités respectifs conformément à l'article 26 du RGPD.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'responsable_a', label: "Co-responsable A", type: 'text', required: true },
      { key: 'responsable_b', label: "Co-responsable B", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'traitement_commun', label: "Description du traitement commun", type: 'textarea', required: true },
      { key: 'repartition_responsabilites', label: "Répartition des responsabilités", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CO-RESPONSABILITÉ DE TRAITEMENT</h1><p><strong>Co-responsable A :</strong> {{responsable_a}} | <strong>Co-responsable B :</strong> {{responsable_b}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>1. TRAITEMENT COMMUN</h2><p>{{traitement_commun}}</p><h2>2. RÉPARTITION DES RESPONSABILITÉS</h2><p>{{repartition_responsabilites}}</p><h2>3. POINT DE CONTACT UNIQUE</h2><p>Un point de contact unique est désigné pour les personnes concernées souhaitant exercer leurs droits.</p><h2>4. GESTION DES VIOLATIONS</h2><p>Les co-responsables se notifient mutuellement sans délai en cas de violation de données.</p><p class="signature">Signatures : {{responsable_a}} / {{responsable_b}}</p></div>`,
  },
  {
    code: 'rgpd_suppression_anonymisation',
    name: "Procédure de Suppression et d'Anonymisation des Données",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Procédure définissant les méthodes et délais de suppression ou d'anonymisation des données personnelles en fin de durée de conservation.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_procedure', label: "Responsable de la procédure", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'categories_donnees', label: "Catégories de données concernées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE SUPPRESSION ET D'ANONYMISATION DES DONNÉES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Responsable :</strong> {{responsable_procedure}}</p><h2>1. OBJECTIF</h2><p>Garantir que les données personnelles ne sont pas conservées au-delà de la durée nécessaire.</p><h2>2. DONNÉES CONCERNÉES</h2><p>{{categories_donnees}}</p><h2>3. MÉTHODES DE SUPPRESSION</h2><p>Suppression logique avec purge des sauvegardes. Destruction physique des supports. Anonymisation irréversible.</p><h2>4. MÉTHODES D'ANONYMISATION</h2><p>Généralisation. Suppression d'attributs. Perturbation des données. Agrégation.</p><h2>5. TRAÇABILITÉ</h2><p>Chaque suppression ou anonymisation est documentée et tracée.</p></div>`,
  },
  {
    code: 'rgpd_plan_formation',
    name: "Plan de Formation Protection des Données",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Plan définissant le programme de formation des collaborateurs aux obligations et bonnes pratiques en matière de protection des données personnelles.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_formation', label: "Responsable du plan de formation", type: 'text', required: true },
      { key: 'annee_plan', label: "Année du plan de formation", type: 'text', required: true },
      { key: 'modules_formation', label: "Modules de formation prévus", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE FORMATION PROTECTION DES DONNÉES</h1><h2>{{nom_organisation}} - Année {{annee_plan}}</h2><p><strong>Responsable :</strong> {{responsable_formation}}</p><h2>1. OBJECTIFS</h2><p>Former les collaborateurs aux enjeux de la protection des données et à leurs obligations.</p><h2>2. PUBLIC CIBLE</h2><p>Tous les collaborateurs, avec des modules adaptés aux fonctions à risque.</p><h2>3. MODULES DE FORMATION</h2><p>{{modules_formation}}</p><h2>4. MODALITÉS</h2><p>Formation présentielle. E-learning. Ateliers pratiques. Tests de validation.</p><h2>5. SUIVI ET ÉVALUATION</h2><p>Taux de complétion. Résultats aux tests. Actions correctives.</p></div>`,
  },
  {
    code: 'rgpd_rapport_annuel_dpo',
    name: "Rapport Annuel DPO",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Rapport annuel du Délégué à la Protection des Données (DPO) dressant le bilan des activités de protection des données et les perspectives.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'nom_dpo', label: "Nom du DPO", type: 'text', required: true },
      { key: 'annee_rapport', label: "Année couverte par le rapport", type: 'text', required: true },
      { key: 'bilan_activites', label: "Bilan des activités de l'année", type: 'textarea', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT ANNUEL DU DÉLÉGUÉ À LA PROTECTION DES DONNÉES</h1><h2>{{nom_organisation}} - Année {{annee_rapport}}</h2><p><strong>DPO :</strong> {{nom_dpo}} | <strong>Date :</strong> {{date_rapport}}</p><h2>1. BILAN DES ACTIVITÉS</h2><p>{{bilan_activites}}</p><h2>2. ÉTAT DE LA CONFORMITÉ</h2><p>Évolution du taux de conformité, traitements audités, non-conformités corrigées.</p><h2>3. INCIDENTS ET VIOLATIONS</h2><p>Nombre de violations de données constatées, notifications effectuées, mesures prises.</p><h2>4. DROITS DES PERSONNES</h2><p>Demandes reçues, délais de traitement, nature des droits exercés.</p><h2>5. PERSPECTIVES</h2><p>Priorités pour l'année à venir et ressources nécessaires.</p><p class="signature">Rapport présenté par {{nom_dpo}} à la Direction de {{nom_organisation}}</p></div>`,
  },
  {
    code: 'rgpd_donnees_sante',
    name: "Convention de Traitement de Données Sensibles de Santé",
    category: 'juridique_admin',
    price: 14000,
    priceMax: 42000,
    description: "Convention encadrant le traitement de données de santé, catégorie particulière de données personnelles nécessitant des garanties renforcées.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_responsable_traitement', label: "Responsable de traitement", type: 'text', required: true },
      { key: 'nom_partenaire', label: "Partenaire / sous-traitant", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
      { key: 'finalites_traitement_sante', label: "Finalités du traitement de données de santé", type: 'textarea', required: true },
      { key: 'mesures_securite_renforcees', label: "Mesures de sécurité renforcées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE TRAITEMENT DE DONNÉES SENSIBLES DE SANTÉ</h1><p><strong>Responsable :</strong> {{nom_responsable_traitement}} | <strong>Partenaire :</strong> {{nom_partenaire}}</p><p><strong>Date :</strong> {{date_convention}}</p><h2>1. CADRE LÉGAL</h2><p>Le traitement de données de santé est soumis aux dispositions de l'article 9 du RGPD et aux réglementations sectorielles applicables.</p><h2>2. FINALITÉS DU TRAITEMENT</h2><p>{{finalites_traitement_sante}}</p><h2>3. BASE LÉGALE</h2><p>Le traitement repose sur une base légale explicite conforme à l'article 9(2) du RGPD.</p><h2>4. MESURES DE SÉCURITÉ RENFORCÉES</h2><p>{{mesures_securite_renforcees}}</p><h2>5. ACCÈS AUX DONNÉES</h2><p>L'accès aux données de santé est strictement limité aux personnes habilitées et soumises au secret professionnel.</p><p class="signature">Signatures : {{nom_responsable_traitement}} / {{nom_partenaire}}</p></div>`,
  },
  {
    code: 'rgpd_pseudonymisation',
    name: "Accord de Pseudonymisation des Données",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Accord définissant les modalités de pseudonymisation des données personnelles pour réduire les risques tout en permettant leur utilisation à des fins analytiques ou de recherche.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_pseudonymisation', label: "Responsable technique", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'technique_pseudonymisation', label: "Technique de pseudonymisation utilisée", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PSEUDONYMISATION DES DONNÉES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_accord}} | <strong>Responsable technique :</strong> {{responsable_pseudonymisation}}</p><h2>1. DÉFINITION ET OBJECTIF</h2><p>La pseudonymisation consiste à traiter des données de façon à ne plus pouvoir les attribuer à une personne sans utiliser des informations supplémentaires conservées séparément.</p><h2>2. TECHNIQUE UTILISÉE</h2><p>{{technique_pseudonymisation}}</p><h2>3. GESTION DES CLÉS DE RÉ-IDENTIFICATION</h2><p>Les clés permettant la ré-identification sont conservées séparément avec des mesures de sécurité renforcées.</p><h2>4. ACCÈS AUX DONNÉES PSEUDONYMISÉES</h2><p>Les données pseudonymisées restent des données personnelles et sont traitées comme telles.</p><h2>5. DOCUMENTATION</h2><p>Le processus de pseudonymisation est documenté dans le registre des traitements.</p></div>`,
  },
  {
    code: 'rgpd_portabilite_donnees',
    name: "Procédure de Portabilité des Données",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Procédure définissant les modalités techniques et organisationnelles pour répondre aux demandes de portabilité des données personnelles.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_portabilite', label: "Responsable de la portabilité", type: 'text', required: true },
      { key: 'date_procedure', label: "Date de la procédure", type: 'date', required: true },
      { key: 'formats_export', label: "Formats d'export proposés", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE PORTABILITÉ DES DONNÉES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_procedure}} | <strong>Responsable :</strong> {{responsable_portabilite}}</p><h2>1. DROIT À LA PORTABILITÉ</h2><p>Le droit à la portabilité permet aux personnes de récupérer leurs données dans un format structuré, couramment utilisé et lisible par machine.</p><h2>2. DONNÉES CONCERNÉES</h2><p>Les données fournies par la personne concernée et traitées sur la base du consentement ou d'un contrat.</p><h2>3. FORMATS D'EXPORT</h2><p>{{formats_export}}</p><h2>4. PROCESSUS DE TRAITEMENT</h2><p>Réception de la demande. Vérification de l'identité. Extraction et mise en forme. Transmission sécurisée sous 30 jours.</p><h2>5. TRANSFERT DIRECT</h2><p>Le cas échéant, les données peuvent être transmises directement à un autre responsable de traitement.</p></div>`,
  },
  {
    code: 'rgpd_evaluation_risques_privacy',
    name: "Rapport d'Évaluation des Risques Privacy",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Rapport d'évaluation des risques pour la vie privée liés aux activités de traitement de données de l'organisation, avec plan de mitigation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'evaluateur', label: "Évaluateur", type: 'text', required: true },
      { key: 'date_evaluation', label: "Date de l'évaluation", type: 'date', required: true },
      { key: 'traitements_evalues', label: "Traitements évalués", type: 'textarea', required: true },
      { key: 'risques_identifies', label: "Risques privacy identifiés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'ÉVALUATION DES RISQUES PRIVACY</h1><h2>{{nom_organisation}}</h2><p><strong>Évaluateur :</strong> {{evaluateur}} | <strong>Date :</strong> {{date_evaluation}}</p><h2>1. TRAITEMENTS ÉVALUÉS</h2><p>{{traitements_evalues}}</p><h2>2. MÉTHODOLOGIE</h2><p>Identification des menaces. Évaluation des vraisemblances et des impacts. Calcul du niveau de risque résiduel.</p><h2>3. RISQUES IDENTIFIÉS</h2><p>{{risques_identifies}}</p><h2>4. MESURES DE MITIGATION</h2><p>Pour chaque risque identifié, des mesures techniques et organisationnelles sont recommandées.</p><h2>5. RISQUES RÉSIDUELS</h2><p>Les risques résiduels après mitigation sont présentés et soumis à l'acceptation de la Direction.</p><p class="signature">Rapport établi par {{evaluateur}}</p></div>`,
  },
  {
    code: 'rgpd_plan_incidents_donnees',
    name: "Plan de Gestion des Incidents de Données",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Plan définissant les procédures de détection, de gestion et de notification des incidents de données personnelles.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'responsable_incidents', label: "Responsable gestion des incidents", type: 'text', required: true },
      { key: 'date_plan', label: "Date du plan", type: 'date', required: true },
      { key: 'equipe_intervention', label: "Équipe d'intervention", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE GESTION DES INCIDENTS DE DONNÉES PERSONNELLES</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_plan}} | <strong>Responsable :</strong> {{responsable_incidents}}</p><h2>1. OBJECTIF</h2><p>Définir les procédures pour gérer efficacement les incidents de données personnelles et respecter les obligations de notification.</p><h2>2. ÉQUIPE D'INTERVENTION</h2><p>{{equipe_intervention}}</p><h2>3. PROCESSUS DE GESTION</h2><p>Détection et signalement. Qualification de l'incident. Confinement et remédiation. Évaluation de l'impact. Notification si requise. Documentation et retour d'expérience.</p><h2>4. CRITÈRES DE NOTIFICATION</h2><p>Notification à l'autorité si risque avéré. Notification aux personnes si risque élevé.</p><h2>5. DÉLAIS</h2><p>Notification à l'autorité dans les 72 heures. Notification aux personnes sans délai indu.</p></div>`,
  },
  {
    code: 'rgpd_accord_traitement_rh',
    name: "Accord de Traitement Données RH",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Accord définissant le cadre du traitement des données personnelles des ressources humaines, entre l'employeur et les prestataires RH.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'nom_employeur', label: "Nom de l'employeur", type: 'text', required: true },
      { key: 'nom_prestataire_rh', label: "Prestataire RH", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'donnees_rh_traitees', label: "Données RH faisant l'objet du traitement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRAITEMENT DES DONNÉES RESSOURCES HUMAINES</h1><p><strong>Employeur :</strong> {{nom_employeur}} | <strong>Prestataire RH :</strong> {{nom_prestataire_rh}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>1. OBJET</h2><p>Le présent accord définit les conditions dans lesquelles {{nom_prestataire_rh}} traite les données RH pour le compte de {{nom_employeur}}.</p><h2>2. DONNÉES TRAITÉES</h2><p>{{donnees_rh_traitees}}</p><h2>3. FINALITÉS</h2><p>Gestion de la paie. Administration du personnel. Gestion des congés et absences. Formation.</p><h2>4. OBLIGATIONS DE SÉCURITÉ</h2><p>Le prestataire s'engage à mettre en place les mesures techniques et organisationnelles appropriées.</p><h2>5. SOUS-TRAITANCE</h2><p>Toute sous-traitance ultérieure est soumise à l'autorisation préalable écrite de l'employeur.</p><p class="signature">Signatures : {{nom_employeur}} / {{nom_prestataire_rh}}</p></div>`,
  },
  {
    code: 'rgpd_convention_clients',
    name: "Convention de Traitement Données Clients",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Convention définissant le cadre du traitement des données personnelles des clients dans le cadre d'une relation commerciale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
      { key: 'categories_clients', label: "Catégories de clients concernés", type: 'text', required: true },
      { key: 'finalites_traitement', label: "Finalités du traitement des données clients", type: 'textarea', required: true },
      { key: 'durees_conservation', label: "Durées de conservation applicables", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE TRAITEMENT DES DONNÉES CLIENTS</h1><h2>{{nom_organisation}}</h2><p><strong>Date :</strong> {{date_convention}} | <strong>Clients :</strong> {{categories_clients}}</p><h2>1. DONNÉES CLIENTS COLLECTÉES</h2><p>Dans le cadre de la relation commerciale, {{nom_organisation}} collecte et traite les données personnelles de ses clients.</p><h2>2. FINALITÉS DU TRAITEMENT</h2><p>{{finalites_traitement}}</p><h2>3. BASE LÉGALE</h2><p>Exécution d'un contrat. Intérêt légitime. Obligation légale. Consentement selon les cas.</p><h2>4. DURÉES DE CONSERVATION</h2><p>{{durees_conservation}}</p><h2>5. DROITS DES CLIENTS</h2><p>Les clients peuvent exercer leurs droits en contactant le DPO ou le service dédié.</p></div>`,
  },
  {
    code: 'rgpd_charte_ia_donnees',
    name: "Charte d'Utilisation de l'IA et des Données",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Charte définissant les règles d'utilisation éthique et conforme de l'intelligence artificielle et des données personnelles au sein de l'organisation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_organisation', label: "Nom de l'organisation", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption", type: 'date', required: true },
      { key: 'responsable_ia', label: "Responsable IA / DPO", type: 'text', required: true },
      { key: 'systemes_ia_concernes', label: "Systèmes d'IA concernés", type: 'textarea', required: true },
      { key: 'principes_ethiques', label: "Principes éthiques adoptés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE D'UTILISATION DE L'INTELLIGENCE ARTIFICIELLE ET DES DONNÉES</h1><h2>{{nom_organisation}}</h2><p><strong>Date d'adoption :</strong> {{date_adoption}} | <strong>Responsable :</strong> {{responsable_ia}}</p><h2>1. OBJET</h2><p>La présente charte définit les principes et règles gouvernant l'utilisation de l'intelligence artificielle et des données au sein de {{nom_organisation}}.</p><h2>2. SYSTÈMES D'IA CONCERNÉS</h2><p>{{systemes_ia_concernes}}</p><h2>3. PRINCIPES ÉTHIQUES</h2><p>{{principes_ethiques}}</p><h2>4. DONNÉES ET TRANSPARENCE</h2><p>Les traitements de données par l'IA sont documentés. Les personnes concernées sont informées des décisions automatisées. Un droit à l'explication est garanti.</p><h2>5. GOUVERNANCE DE L'IA</h2><p>Un comité IA est mis en place pour superviser l'usage éthique et conforme de l'IA.</p><h2>6. INTERDICTIONS</h2><p>L'utilisation de l'IA à des fins discriminatoires, de manipulation ou de surveillance non autorisée est strictement interdite.</p><p class="signature">Adoptée par la Direction de {{nom_organisation}}</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 32a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
