import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── EXPORT / IMPORT (25 templates) ───
  {
    code: 'exp_vente_cif',
    name: "Contrat de vente internationale (CIF)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de vente internationale sous incoterm CIF (Cost, Insurance and Freight) conforme aux règles OHADA et Incoterms 2020.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'vendeur', label: "Nom et adresse du vendeur", type: 'text', required: true },
      { key: 'acheteur', label: "Nom et adresse de l'acheteur", type: 'text', required: true },
      { key: 'description_marchandise', label: "Description de la marchandise", type: 'textarea', required: true },
      { key: 'port_destination', label: "Port de destination", type: 'text', required: true },
      { key: 'prix_total', label: "Prix total CIF (en FCFA ou devise)", type: 'text', required: true },
      { key: 'date_livraison', label: "Date de livraison prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE INTERNATIONALE (CIF)</h1><p>Entre le vendeur : <strong>{{vendeur}}</strong> et l'acheteur : <strong>{{acheteur}}</strong>.</p><h2>Article 1 – Marchandise</h2><p>{{description_marchandise}}</p><h2>Article 2 – Incoterm et port</h2><p>La vente est conclue sous l'incoterm CIF. Port de destination : {{port_destination}}.</p><h2>Article 3 – Prix</h2><p>Prix total convenu : {{prix_total}}. Ce prix inclut le coût de la marchandise, le fret maritime et l'assurance jusqu'au port de destination.</p><h2>Article 4 – Livraison</h2><p>Date de livraison prévue : {{date_livraison}}.</p><h2>Article 5 – Droit applicable</h2><p>Le présent contrat est régi par l'Acte uniforme OHADA relatif au droit commercial général et les Incoterms 2020 de la CCI.</p></div>`,
  },
  {
    code: 'exp_vente_fob',
    name: "Contrat de vente internationale (FOB)",
    category: 'commercial_financier',
    price: 7500,
    priceMax: 22000,
    description: "Contrat de vente internationale sous incoterm FOB (Free On Board) adapté aux exportateurs de Côte d'Ivoire et de la zone OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'exportateur', label: "Exportateur (nom, adresse, pays)", type: 'text', required: true },
      { key: 'importateur', label: "Importateur (nom, adresse, pays)", type: 'text', required: true },
      { key: 'marchandise', label: "Désignation de la marchandise", type: 'textarea', required: true },
      { key: 'port_embarquement', label: "Port d'embarquement FOB", type: 'text', required: true },
      { key: 'prix_fob', label: "Prix FOB (montant et devise)", type: 'text', required: true },
      { key: 'date_expedition', label: "Date d'expédition prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE INTERNATIONALE (FOB)</h1><p>Exportateur : <strong>{{exportateur}}</strong></p><p>Importateur : <strong>{{importateur}}</strong></p><h2>Article 1 – Objet</h2><p>Le présent contrat a pour objet la vente des marchandises suivantes : {{marchandise}}.</p><h2>Article 2 – Incoterm FOB</h2><p>La livraison s'effectue FOB port d'embarquement : {{port_embarquement}}. Les risques sont transférés à l'acheteur dès que la marchandise est à bord du navire.</p><h2>Article 3 – Prix</h2><p>Prix FOB convenu : {{prix_fob}}.</p><h2>Article 4 – Expédition</h2><p>Date d'expédition prévue : {{date_expedition}}.</p><h2>Article 5 – Litiges</h2><p>Tout litige sera soumis à la CCJA (Cour Commune de Justice et d'Arbitrage) de l'OHADA.</p></div>`,
  },
  {
    code: 'exp_vente_exw',
    name: "Contrat de vente internationale (EXW)",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 20000,
    description: "Contrat de vente internationale sous incoterm EXW (Ex Works) où l'acheteur prend en charge tous les frais à partir des locaux du vendeur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'vendeur', label: "Vendeur (raison sociale et adresse)", type: 'text', required: true },
      { key: 'acheteur', label: "Acheteur (raison sociale et pays)", type: 'text', required: true },
      { key: 'lieu_enlevement', label: "Lieu d'enlèvement EXW", type: 'text', required: true },
      { key: 'description_produits', label: "Description des produits", type: 'textarea', required: true },
      { key: 'prix_exw', label: "Prix EXW total", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE INTERNATIONALE (EXW)</h1><p>Vendeur : <strong>{{vendeur}}</strong> — Acheteur : <strong>{{acheteur}}</strong></p><h2>Article 1 – Marchandise</h2><p>{{description_produits}}</p><h2>Article 2 – Incoterm EXW</h2><p>La livraison s'effectue EXW (Ex Works) au lieu suivant : {{lieu_enlevement}}. L'acheteur prend en charge tous les frais et risques à compter de la mise à disposition.</p><h2>Article 3 – Prix</h2><p>Prix EXW convenu : {{prix_exw}}. Tous les coûts ultérieurs (transport, assurance, dédouanement) sont à la charge de l'acheteur.</p><h2>Article 4 – Droit applicable</h2><p>Acte uniforme OHADA relatif au droit commercial général.</p></div>`,
  },
  {
    code: 'exp_facture_commerciale',
    name: "Facture commerciale internationale",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 8000,
    description: "Facture commerciale internationale conforme aux exigences douanières CEDEAO et OHADA, requise pour tout envoi à l'exportation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 90,
    fieldsJson: F([
      { key: 'exportateur', label: "Exportateur (nom, adresse, RCCM)", type: 'text', required: true },
      { key: 'importateur', label: "Importateur (nom, adresse, pays)", type: 'text', required: true },
      { key: 'numero_facture', label: "Numéro de facture", type: 'text', required: true },
      { key: 'date_facture', label: "Date de la facture", type: 'date', required: true },
      { key: 'detail_marchandises', label: "Détail des marchandises (désignation, quantité, PU, total)", type: 'textarea', required: true },
      { key: 'conditions_paiement', label: "Conditions de paiement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FACTURE COMMERCIALE INTERNATIONALE</h1><p>N° : <strong>{{numero_facture}}</strong> — Date : {{date_facture}}</p><h2>Vendeur / Exportateur</h2><p>{{exportateur}}</p><h2>Acheteur / Importateur</h2><p>{{importateur}}</p><h2>Détail des marchandises</h2><p>{{detail_marchandises}}</p><h2>Conditions de paiement</h2><p>{{conditions_paiement}}</p><p><em>Document établi conformément aux exigences de la douane et du commerce international.</em></p></div>`,
  },
  {
    code: 'exp_packing_list',
    name: "Packing List (Liste de colisage)",
    category: 'commercial_financier',
    price: 2500,
    priceMax: 7000,
    description: "Liste de colisage (packing list) détaillant le contenu de chaque colis pour les opérations douanières à l'export depuis la Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'expediteur', label: "Expéditeur", type: 'text', required: true },
      { key: 'destinataire', label: "Destinataire", type: 'text', required: true },
      { key: 'reference_commande', label: "Référence commande / facture", type: 'text', required: true },
      { key: 'detail_colis', label: "Détail des colis (N°, contenu, poids brut, poids net, dimensions)", type: 'textarea', required: true },
      { key: 'poids_total', label: "Poids total brut / net", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>LISTE DE COLISAGE (PACKING LIST)</h1><p>Expéditeur : <strong>{{expediteur}}</strong></p><p>Destinataire : <strong>{{destinataire}}</strong></p><p>Référence : {{reference_commande}}</p><h2>Détail des colis</h2><p>{{detail_colis}}</p><h2>Récapitulatif</h2><p>Poids total : {{poids_total}}</p><p><em>Document établi à des fins douanières conformément aux normes CEDEAO.</em></p></div>`,
  },
  {
    code: 'exp_cert_origine_forma',
    name: "Certificat d'origine Form A (SGP)",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Certificat d'origine Form A pour le Système Généralisé de Préférences (SGP), permettant aux exportateurs ivoiriens de bénéficier de tarifs préférentiels.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'exportateur', label: "Exportateur (nom, adresse, pays)", type: 'text', required: true },
      { key: 'importateur', label: "Importateur / destinataire", type: 'text', required: true },
      { key: 'pays_destination', label: "Pays de destination", type: 'text', required: true },
      { key: 'description_produit', label: "Description des produits et critères d'origine", type: 'textarea', required: true },
      { key: 'date_declaration', label: "Date de la déclaration", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CERTIFICAT D'ORIGINE — FORMULAIRE A (SGP)</h1><p>Exportateur : <strong>{{exportateur}}</strong></p><p>Importateur : <strong>{{importateur}}</strong></p><p>Pays de destination : {{pays_destination}}</p><h2>Description des marchandises</h2><p>{{description_produit}}</p><h2>Déclaration de l'exportateur</h2><p>Je soussigné déclare que les marchandises décrites ci-dessus sont originaires de Côte d'Ivoire et satisfont aux critères d'origine du SGP.</p><p>Date : {{date_declaration}}</p></div>`,
  },
  {
    code: 'exp_cert_phytosanitaire',
    name: "Certificat phytosanitaire export",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Certificat phytosanitaire pour l'exportation de végétaux et produits végétaux, conforme aux normes CIPV et aux exigences du pays importateur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'exportateur', label: "Nom et adresse de l'exportateur", type: 'text', required: true },
      { key: 'produit_vegetal', label: "Description du produit végétal", type: 'textarea', required: true },
      { key: 'pays_destination', label: "Pays de destination", type: 'text', required: true },
      { key: 'traitement_effectue', label: "Traitement phytosanitaire effectué", type: 'text', required: true },
      { key: 'date_inspection', label: "Date d'inspection", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CERTIFICAT PHYTOSANITAIRE</h1><p>Autorité compétente : Direction de la Protection des Végétaux — Côte d'Ivoire</p><p>Exportateur : <strong>{{exportateur}}</strong></p><p>Pays de destination : {{pays_destination}}</p><h2>Description du produit</h2><p>{{produit_vegetal}}</p><h2>Traitement</h2><p>{{traitement_effectue}}</p><p>Date d'inspection : {{date_inspection}}</p><p><em>Ce certificat atteste que les végétaux décrits ont été inspectés conformément aux procédures officielles et sont exempts d'organismes nuisibles.</em></p></div>`,
  },
  {
    code: 'exp_cert_sanitaire_alim',
    name: "Certificat sanitaire export produits alimentaires",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 14000,
    description: "Certificat sanitaire pour l'exportation de produits alimentaires depuis la Côte d'Ivoire, conforme aux normes Codex Alimentarius et UEMOA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'producteur', label: "Producteur / exportateur", type: 'text', required: true },
      { key: 'produit_alimentaire', label: "Description du produit alimentaire", type: 'textarea', required: true },
      { key: 'lot_reference', label: "Numéro de lot et référence", type: 'text', required: true },
      { key: 'pays_destination', label: "Pays de destination", type: 'text', required: true },
      { key: 'date_inspection', label: "Date d'inspection sanitaire", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CERTIFICAT SANITAIRE — PRODUITS ALIMENTAIRES</h1><p>Autorité compétente : Ministère des Ressources Animales et Halieutiques / LANADA — Côte d'Ivoire</p><p>Exportateur : <strong>{{producteur}}</strong></p><p>Produit : {{produit_alimentaire}}</p><p>Lot / Référence : {{lot_reference}}</p><p>Pays de destination : {{pays_destination}}</p><p>Date d'inspection : {{date_inspection}}</p><h2>Attestation</h2><p>Les produits alimentaires décrits ci-dessus ont été inspectés et sont jugés propres à la consommation humaine et conformes aux réglementations sanitaires en vigueur.</p></div>`,
  },
  {
    code: 'exp_cert_analyse_labo',
    name: "Certificat d'analyse laboratoire export",
    category: 'commercial_financier',
    price: 5500,
    priceMax: 16000,
    description: "Certificat d'analyse de laboratoire requis pour l'exportation de produits nécessitant une validation qualité (résidus pesticides, métaux lourds, microbiologie).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'laboratoire', label: "Laboratoire émetteur (nom, accréditation)", type: 'text', required: true },
      { key: 'client_exportateur', label: "Client / exportateur", type: 'text', required: true },
      { key: 'echantillon', label: "Description de l'échantillon analysé", type: 'textarea', required: true },
      { key: 'resultats_analyses', label: "Résultats des analyses", type: 'textarea', required: true },
      { key: 'date_analyse', label: "Date des analyses", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CERTIFICAT D'ANALYSE — LABORATOIRE</h1><p>Laboratoire : <strong>{{laboratoire}}</strong></p><p>Client / Exportateur : {{client_exportateur}}</p><p>Date des analyses : {{date_analyse}}</p><h2>Échantillon</h2><p>{{echantillon}}</p><h2>Résultats</h2><p>{{resultats_analyses}}</p><p><em>Ce certificat est délivré sous la responsabilité du laboratoire accrédité. Les résultats ne concernent que l'échantillon analysé.</em></p></div>`,
  },
  {
    code: 'exp_contrat_representant',
    name: "Contrat de représentation commerciale internationale",
    category: 'commercial_financier',
    price: 9000,
    priceMax: 28000,
    description: "Contrat désignant un représentant commercial dans un pays étranger pour promouvoir et vendre les produits d'une entreprise ivoirienne ou OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'commettant', label: "Commettant (entreprise mandante)", type: 'text', required: true },
      { key: 'representant', label: "Représentant commercial (nom, pays)", type: 'text', required: true },
      { key: 'territoire', label: "Territoire de représentation", type: 'text', required: true },
      { key: 'produits_concernes', label: "Produits / services concernés", type: 'textarea', required: true },
      { key: 'commission', label: "Taux de commission (%)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE REPRÉSENTATION COMMERCIALE INTERNATIONALE</h1><p>Entre le commettant : <strong>{{commettant}}</strong> et le représentant : <strong>{{representant}}</strong>.</p><h2>Article 1 – Territoire</h2><p>Le représentant est autorisé à exercer son activité sur le territoire suivant : {{territoire}}.</p><h2>Article 2 – Produits</h2><p>{{produits_concernes}}</p><h2>Article 3 – Rémunération</h2><p>Commission : {{commission}} sur le chiffre d'affaires réalisé.</p><h2>Article 4 – Durée</h2><p>{{duree_contrat}}</p><h2>Article 5 – Droit applicable</h2><p>Acte uniforme OHADA relatif au droit commercial général et droit du pays du représentant.</p></div>`,
  },
  {
    code: 'exp_distributeur_exclusif',
    name: "Accord de distributeur exclusif international",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Accord conférant l'exclusivité de distribution à un partenaire étranger pour les produits d'une entreprise de la zone OHADA sur un territoire défini.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'fournisseur', label: "Fournisseur / fabricant", type: 'text', required: true },
      { key: 'distributeur', label: "Distributeur exclusif (nom, pays)", type: 'text', required: true },
      { key: 'territoire_exclusif', label: "Territoire exclusif accordé", type: 'text', required: true },
      { key: 'gamme_produits', label: "Gamme de produits concernée", type: 'textarea', required: true },
      { key: 'objectif_vente', label: "Objectif de vente annuel minimum", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTEUR EXCLUSIF INTERNATIONAL</h1><p>Fournisseur : <strong>{{fournisseur}}</strong></p><p>Distributeur exclusif : <strong>{{distributeur}}</strong></p><h2>Article 1 – Exclusivité territoriale</h2><p>Le fournisseur accorde au distributeur l'exclusivité de distribution sur le territoire : {{territoire_exclusif}}.</p><h2>Article 2 – Produits</h2><p>{{gamme_produits}}</p><h2>Article 3 – Objectifs</h2><p>Objectif minimum annuel : {{objectif_vente}}. En cas de non-atteinte, le fournisseur se réserve le droit de revoir l'exclusivité.</p><h2>Article 4 – Droit applicable et arbitrage</h2><p>CCJA – OHADA pour tout litige.</p></div>`,
  },
  {
    code: 'exp_agent_commercial_intl',
    name: "Contrat d'agent commercial international",
    category: 'commercial_financier',
    price: 9500,
    priceMax: 27000,
    description: "Contrat d'agent commercial mandaté pour négocier et conclure des contrats au nom d'une entreprise exportatrice de la zone OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'mandant', label: "Mandant (entreprise exportatrice)", type: 'text', required: true },
      { key: 'agent', label: "Agent commercial (nom, pays, statut)", type: 'text', required: true },
      { key: 'zone_prospection', label: "Zone de prospection", type: 'text', required: true },
      { key: 'pouvoirs_agent', label: "Étendue des pouvoirs de l'agent", type: 'textarea', required: true },
      { key: 'remuneration', label: "Rémunération (commission ou fixe)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'AGENT COMMERCIAL INTERNATIONAL</h1><p>Mandant : <strong>{{mandant}}</strong> — Agent : <strong>{{agent}}</strong></p><h2>Article 1 – Mission</h2><p>L'agent est mandaté pour prospecter et négocier sur la zone : {{zone_prospection}}.</p><h2>Article 2 – Pouvoirs</h2><p>{{pouvoirs_agent}}</p><h2>Article 3 – Rémunération</h2><p>{{remuneration}}</p><h2>Article 4 – Obligations de l'agent</h2><p>L'agent s'engage à agir loyalement, à rendre compte régulièrement et à respecter les instructions du mandant.</p><h2>Article 5 – Résiliation</h2><p>Résiliation possible avec préavis de 3 mois. Indemnité compensatrice conforme au droit applicable.</p></div>`,
  },
  {
    code: 'exp_licence_export',
    name: "Accord de licence export (produits réglementés)",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 35000,
    description: "Accord de licence pour l'exportation de produits soumis à réglementation spécifique (produits chimiques, pharmaceutiques, matériels à double usage).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'concedant', label: "Concédant (détenteur de la licence)", type: 'text', required: true },
      { key: 'licencie', label: "Licencié (exportateur)", type: 'text', required: true },
      { key: 'produit_reglemente', label: "Produit réglementé et autorisation obtenue", type: 'textarea', required: true },
      { key: 'pays_autorises', label: "Pays d'exportation autorisés", type: 'text', required: true },
      { key: 'redevance', label: "Redevance de licence", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE LICENCE EXPORT — PRODUITS RÉGLEMENTÉS</h1><p>Concédant : <strong>{{concedant}}</strong> — Licencié : <strong>{{licencie}}</strong></p><h2>Article 1 – Produit et autorisation</h2><p>{{produit_reglemente}}</p><h2>Article 2 – Territoire</h2><p>Pays d'exportation autorisés : {{pays_autorises}}. Toute exportation vers d'autres destinations est strictement interdite.</p><h2>Article 3 – Redevance</h2><p>{{redevance}}</p><h2>Article 4 – Conformité réglementaire</h2><p>Le licencié s'engage à respecter l'ensemble des réglementations douanières, sanitaires et sécuritaires applicables dans chaque pays de destination.</p></div>`,
  },
  {
    code: 'exp_joint_venture',
    name: "Accord de joint venture export",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 45000,
    description: "Accord de coentreprise pour structurer un partenariat entre deux entités en vue de conquérir des marchés d'exportation en commun.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'partie_a', label: "Partie A (entreprise, pays)", type: 'text', required: true },
      { key: 'partie_b', label: "Partie B (entreprise, pays)", type: 'text', required: true },
      { key: 'objet_jv', label: "Objet de la joint venture", type: 'textarea', required: true },
      { key: 'repartition_capital', label: "Répartition du capital (%)", type: 'text', required: true },
      { key: 'marches_cibles', label: "Marchés d'exportation cibles", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE JOINT VENTURE EXPORT</h1><p>Partie A : <strong>{{partie_a}}</strong> — Partie B : <strong>{{partie_b}}</strong></p><h2>Article 1 – Objet</h2><p>{{objet_jv}}</p><h2>Article 2 – Capital et gouvernance</h2><p>Répartition du capital : {{repartition_capital}}. La gestion de la coentreprise sera assurée par un comité de direction paritaire.</p><h2>Article 3 – Marchés cibles</h2><p>{{marches_cibles}}</p><h2>Article 4 – Droit applicable</h2><p>Acte uniforme OHADA relatif aux sociétés commerciales et au GIE.</p></div>`,
  },
  {
    code: 'exp_courtier_intl',
    name: "Contrat de courtier en commerce international",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 20000,
    description: "Contrat définissant la mission d'un courtier chargé de rapprocher acheteurs et vendeurs dans le cadre d'opérations de commerce international.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'donneur_ordre', label: "Donneur d'ordre", type: 'text', required: true },
      { key: 'courtier', label: "Courtier (nom, agrément)", type: 'text', required: true },
      { key: 'mission', label: "Description de la mission de courtage", type: 'textarea', required: true },
      { key: 'courtage', label: "Taux ou montant du courtage", type: 'text', required: true },
      { key: 'duree_mission', label: "Durée de la mission", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE COURTIER EN COMMERCE INTERNATIONAL</h1><p>Donneur d'ordre : <strong>{{donneur_ordre}}</strong> — Courtier : <strong>{{courtier}}</strong></p><h2>Article 1 – Mission</h2><p>{{mission}}</p><h2>Article 2 – Rémunération</h2><p>Courtage : {{courtage}}. Payable à la conclusion effective de la transaction.</p><h2>Article 3 – Durée</h2><p>{{duree_mission}}</p><h2>Article 4 – Obligations du courtier</h2><p>Le courtier agit en tant qu'intermédiaire indépendant et s'engage à respecter la confidentialité des informations commerciales.</p></div>`,
  },
  {
    code: 'exp_foire_exposition',
    name: "Contrat de foire et exposition internationale",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Contrat encadrant la participation d'une entreprise de la zone OHADA à une foire ou exposition commerciale internationale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'exposant', label: "Entreprise exposante", type: 'text', required: true },
      { key: 'organisateur', label: "Organisateur de la foire", type: 'text', required: true },
      { key: 'evenement', label: "Nom et lieu de l'événement", type: 'text', required: true },
      { key: 'dates_evenement', label: "Dates de l'événement", type: 'text', required: true },
      { key: 'surface_stand', label: "Surface du stand et emplacement", type: 'text', required: true },
      { key: 'frais_participation', label: "Frais de participation", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PARTICIPATION — FOIRE ET EXPOSITION INTERNATIONALE</h1><p>Exposant : <strong>{{exposant}}</strong> — Organisateur : <strong>{{organisateur}}</strong></p><h2>Article 1 – Événement</h2><p>Événement : {{evenement}} — Dates : {{dates_evenement}}</p><h2>Article 2 – Stand</h2><p>Surface et emplacement : {{surface_stand}}</p><h2>Article 3 – Frais</h2><p>Frais de participation : {{frais_participation}}</p><h2>Article 4 – Obligations de l'exposant</h2><p>L'exposant s'engage à respecter le règlement intérieur de la foire et à assurer la présence d'un représentant qualifié durant toute la durée de l'événement.</p></div>`,
  },
  {
    code: 'exp_partenariat_bilateral',
    name: "Accord de partenariat commercial bilatéral",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Accord structurant un partenariat commercial entre deux entreprises de pays différents pour développer leurs échanges commerciaux bilatéraux.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'partenaire_ci', label: "Partenaire Côte d'Ivoire / OHADA", type: 'text', required: true },
      { key: 'partenaire_etranger', label: "Partenaire étranger (nom, pays)", type: 'text', required: true },
      { key: 'objet_partenariat', label: "Objet du partenariat", type: 'textarea', required: true },
      { key: 'engagements_reciproques', label: "Engagements réciproques des parties", type: 'textarea', required: true },
      { key: 'duree', label: "Durée du partenariat", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT COMMERCIAL BILATÉRAL</h1><p>Partie ivoirienne : <strong>{{partenaire_ci}}</strong> — Partie étrangère : <strong>{{partenaire_etranger}}</strong></p><h2>Article 1 – Objet</h2><p>{{objet_partenariat}}</p><h2>Article 2 – Engagements réciproques</h2><p>{{engagements_reciproques}}</p><h2>Article 3 – Durée</h2><p>{{duree}}</p><h2>Article 4 – Droit applicable</h2><p>Les parties conviennent de soumettre le présent accord au droit OHADA et, subsidiairement, aux conventions commerciales bilatérales en vigueur.</p></div>`,
  },
  {
    code: 'exp_purchasing_agreement',
    name: "Contrat d'achat international (Purchasing Agreement)",
    category: 'commercial_financier',
    price: 8500,
    priceMax: 25000,
    description: "Contrat d'achat international encadrant les conditions générales d'approvisionnement d'un importateur auprès de fournisseurs étrangers.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'acheteur', label: "Acheteur / importateur", type: 'text', required: true },
      { key: 'fournisseur', label: "Fournisseur étranger", type: 'text', required: true },
      { key: 'produits_achetes', label: "Produits achetés et spécifications", type: 'textarea', required: true },
      { key: 'prix_et_devise', label: "Prix unitaire et devise de facturation", type: 'text', required: true },
      { key: 'conditions_livraison', label: "Conditions et délai de livraison", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ACHAT INTERNATIONAL (PURCHASING AGREEMENT)</h1><p>Acheteur : <strong>{{acheteur}}</strong> — Fournisseur : <strong>{{fournisseur}}</strong></p><h2>Article 1 – Produits</h2><p>{{produits_achetes}}</p><h2>Article 2 – Prix</h2><p>{{prix_et_devise}}</p><h2>Article 3 – Livraison</h2><p>{{conditions_livraison}}</p><h2>Article 4 – Contrôle qualité</h2><p>L'acheteur se réserve le droit de procéder à des inspections avant embarquement. Tout produit non conforme sera refusé aux frais du fournisseur.</p></div>`,
  },
  {
    code: 'exp_cacao_cafe_ccc',
    name: "Accord de cacao et café export (CONSEIL DU CAFE-CACAO)",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Accord d'exportation de cacao ou café conforme à la réglementation du Conseil du Café-Cacao (CCC) de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'exportateur_agree', label: "Exportateur agréé CCC (nom, agrément)", type: 'text', required: true },
      { key: 'acheteur_international', label: "Acheteur international", type: 'text', required: true },
      { key: 'produit', label: "Produit (cacao ou café) et grade", type: 'text', required: true },
      { key: 'quantite_tonnes', label: "Quantité en tonnes métriques", type: 'text', required: true },
      { key: 'prix_tonne', label: "Prix par tonne métrique et devise", type: 'text', required: true },
      { key: 'campagne', label: "Campagne et saison d'exportation", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXPORTATION — CACAO ET CAFÉ (CCC)</h1><p>Exportateur agréé : <strong>{{exportateur_agree}}</strong> — Acheteur : <strong>{{acheteur_international}}</strong></p><h2>Article 1 – Produit</h2><p>Produit : {{produit}} — Campagne : {{campagne}}</p><h2>Article 2 – Quantité</h2><p>Quantité : {{quantite_tonnes}}</p><h2>Article 3 – Prix</h2><p>Prix : {{prix_tonne}}</p><h2>Article 4 – Conformité CCC</h2><p>Le présent accord est soumis à la réglementation du Conseil du Café-Cacao, notamment en matière de normes de qualité, de pesage et de conditionnement. L'exportateur garantit la conformité des lots au cahier des charges du CCC.</p></div>`,
  },
  {
    code: 'exp_cajou_cca',
    name: "Contrat de noix de cajou export (CCA Côte d'Ivoire)",
    category: 'commercial_financier',
    price: 11000,
    priceMax: 33000,
    description: "Contrat d'exportation de noix de cajou brutes ou transformées, conforme à la réglementation du Conseil du Coton et de l'Anacarde (CCA) de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'exportateur', label: "Exportateur agréé (nom, numéro CCA)", type: 'text', required: true },
      { key: 'acheteur', label: "Acheteur / importateur étranger", type: 'text', required: true },
      { key: 'type_cajou', label: "Type de cajou (brut ou transformé) et grade", type: 'text', required: true },
      { key: 'tonnage', label: "Tonnage contractuel", type: 'text', required: true },
      { key: 'prix_kg', label: "Prix au kilogramme ou à la tonne", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'EXPORTATION — NOIX DE CAJOU (CCA)</h1><p>Exportateur : <strong>{{exportateur}}</strong> — Acheteur : <strong>{{acheteur}}</strong></p><h2>Article 1 – Produit</h2><p>Type : {{type_cajou}} — Tonnage : {{tonnage}}</p><h2>Article 2 – Prix</h2><p>{{prix_kg}}</p><h2>Article 3 – Qualité et normes</h2><p>Les noix de cajou doivent satisfaire aux normes de qualité édictées par le CCA en vigueur au moment de l'expédition (taux d'humidité, KOR minimum, absence de moisissures).</p><h2>Article 4 – Conformité réglementaire</h2><p>Toute exportation nécessite une autorisation préalable du CCA et le respect du prix plancher fixé pour la campagne.</p></div>`,
  },
  {
    code: 'exp_caoutchouc_naturel',
    name: "Accord de caoutchouc naturel export",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Accord d'exportation de caoutchouc naturel produit en Côte d'Ivoire, premier producteur africain, conforme aux normes ASTM et ISO applicables.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'producteur_exportateur', label: "Producteur / exportateur ivoirien", type: 'text', required: true },
      { key: 'acheteur', label: "Acheteur international", type: 'text', required: true },
      { key: 'grade_caoutchouc', label: "Grade (RSS, TSR, etc.) et quantité", type: 'text', required: true },
      { key: 'prix_tonne', label: "Prix à la tonne (SGN ou devise)", type: 'text', required: true },
      { key: 'conditions_livraison', label: "Conditions de livraison (incoterm et port)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXPORTATION — CAOUTCHOUC NATUREL</h1><p>Exportateur : <strong>{{producteur_exportateur}}</strong> — Acheteur : <strong>{{acheteur}}</strong></p><h2>Article 1 – Produit</h2><p>Grade et quantité : {{grade_caoutchouc}}</p><h2>Article 2 – Prix</h2><p>{{prix_tonne}}</p><h2>Article 3 – Livraison</h2><p>{{conditions_livraison}}</p><h2>Article 4 – Qualité</h2><p>Le caoutchouc devra être conforme aux normes ISO 2000 et suivantes. Un certificat d'analyse accompagnera chaque lot.</p></div>`,
  },
  {
    code: 'exp_coton',
    name: "Contrat de coton export",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Contrat d'exportation de coton fibre depuis la zone OHADA (Côte d'Ivoire, Mali, Burkina Faso), conforme aux règles du Conseil du Coton et de l'Anacarde.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'exportateur', label: "Exportateur (égrenage, pays)", type: 'text', required: true },
      { key: 'acheteur', label: "Filateur / acheteur étranger", type: 'text', required: true },
      { key: 'grade_coton', label: "Grade et caractéristiques HVI", type: 'textarea', required: true },
      { key: 'quantite_balles', label: "Quantité en balles / tonnes", type: 'text', required: true },
      { key: 'prix', label: "Prix (cents/livre ou FCFA/kg)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'EXPORTATION — COTON FIBRE</h1><p>Exportateur : <strong>{{exportateur}}</strong> — Acheteur : <strong>{{acheteur}}</strong></p><h2>Article 1 – Produit</h2><p>{{grade_coton}}</p><h2>Article 2 – Quantité</h2><p>{{quantite_balles}}</p><h2>Article 3 – Prix</h2><p>{{prix}}</p><h2>Article 4 – Contrôle qualité</h2><p>L'ensemble des balles sera soumis à un contrôle HVI (High Volume Instrument). Les certificats d'analyse seront fournis avant expédition.</p></div>`,
  },
  {
    code: 'exp_palme',
    name: "Accord de palme export",
    category: 'commercial_financier',
    price: 9000,
    priceMax: 27000,
    description: "Accord d'exportation d'huile de palme brute (CPO) ou de produits dérivés, conforme aux standards RSPO et aux réglementations OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'producteur', label: "Producteur / huilerie exportatrice", type: 'text', required: true },
      { key: 'acheteur', label: "Acheteur international (raffinage)", type: 'text', required: true },
      { key: 'produit_palme', label: "Produit (CPO, PFAD, PKO) et qualité", type: 'text', required: true },
      { key: 'volume_tonnes', label: "Volume en tonnes métriques", type: 'text', required: true },
      { key: 'prix_cpo', label: "Prix à la tonne (USD ou FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXPORTATION — HUILE DE PALME</h1><p>Producteur : <strong>{{producteur}}</strong> — Acheteur : <strong>{{acheteur}}</strong></p><h2>Article 1 – Produit</h2><p>Produit : {{produit_palme}} — Volume : {{volume_tonnes}}</p><h2>Article 2 – Prix</h2><p>{{prix_cpo}}</p><h2>Article 3 – Certification</h2><p>Les parties s'engagent à respecter les exigences de la Table Ronde sur l'Huile de Palme Durable (RSPO) et les normes ISO 8294 applicables.</p></div>`,
  },
  {
    code: 'exp_rapport_performance',
    name: "Rapport de performance export",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Rapport d'évaluation des performances à l'exportation d'une entreprise ou d'un secteur, incluant analyse des volumes, marchés et écarts.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise / entité concernée", type: 'text', required: true },
      { key: 'periode', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'volumes_exportes', label: "Volumes exportés par marché", type: 'textarea', required: true },
      { key: 'chiffre_affaires_export', label: "Chiffre d'affaires export réalisé", type: 'text', required: true },
      { key: 'analyse_ecarts', label: "Analyse des écarts et recommandations", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE EXPORT</h1><p>Entreprise : <strong>{{entreprise}}</strong> — Période : {{periode}}</p><h2>1. Volumes exportés</h2><p>{{volumes_exportes}}</p><h2>2. Chiffre d'affaires export</h2><p>{{chiffre_affaires_export}}</p><h2>3. Analyse des écarts et recommandations</h2><p>{{analyse_ecarts}}</p><h2>4. Conclusion</h2><p>Ce rapport de performance constitue un outil de pilotage stratégique de l'activité export conforme aux bonnes pratiques du commerce international.</p></div>`,
  },
  {
    code: 'exp_plan_developpement',
    name: "Plan de développement des exportations",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 20000,
    description: "Document stratégique définissant le plan de développement des exportations d'une entreprise ivoirienne ou OHADA sur un horizon de 3 à 5 ans.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise et secteur d'activité", type: 'text', required: true },
      { key: 'produits_cibles', label: "Produits / services à exporter", type: 'textarea', required: true },
      { key: 'marches_vises', label: "Marchés visés (pays et régions)", type: 'text', required: true },
      { key: 'objectifs_export', label: "Objectifs quantitatifs sur 3-5 ans", type: 'textarea', required: true },
      { key: 'actions_prioritaires', label: "Actions prioritaires et calendrier", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT DES EXPORTATIONS</h1><p>Entreprise : <strong>{{entreprise}}</strong></p><h2>1. Produits à exporter</h2><p>{{produits_cibles}}</p><h2>2. Marchés visés</h2><p>{{marches_vises}}</p><h2>3. Objectifs</h2><p>{{objectifs_export}}</p><h2>4. Plan d'actions</h2><p>{{actions_prioritaires}}</p><h2>5. Suivi et évaluation</h2><p>Un tableau de bord mensuel permettra de suivre l'avancement du plan et d'ajuster les actions selon les résultats obtenus.</p></div>`,
  },

  // ─── COMMERCE ÉLECTRONIQUE / MARKETPLACE (25 templates) ───
  {
    code: 'ecom_cgv',
    name: "Conditions générales de vente (CGV) e-commerce",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "CGV pour boutique en ligne conforme au droit ivoirien (loi sur la cybercriminalité, ARTCI) et aux bonnes pratiques du commerce électronique en Afrique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'vendeur', label: "Vendeur (raison sociale, RCCM, adresse)", type: 'text', required: true },
      { key: 'site_web', label: "URL du site e-commerce", type: 'text', required: true },
      { key: 'produits_services', label: "Catégories de produits / services vendus", type: 'textarea', required: true },
      { key: 'modes_paiement', label: "Modes de paiement acceptés", type: 'text', required: true },
      { key: 'delai_livraison', label: "Délai de livraison standard", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONDITIONS GÉNÉRALES DE VENTE (CGV)</h1><p>Vendeur : <strong>{{vendeur}}</strong> — Site : {{site_web}}</p><h2>Article 1 – Objet</h2><p>Les présentes CGV régissent les ventes de produits et services proposés sur {{site_web}}.</p><h2>Article 2 – Produits et prix</h2><p>{{produits_services}}. Les prix sont indiqués en FCFA, TTC.</p><h2>Article 3 – Paiement</h2><p>Modes de paiement acceptés : {{modes_paiement}}. Le paiement est exigible à la commande.</p><h2>Article 4 – Livraison</h2><p>Délai de livraison standard : {{delai_livraison}}.</p><h2>Article 5 – Droit de rétractation</h2><p>Conformément aux lois en vigueur, l'acheteur dispose d'un délai de 7 jours ouvrables pour exercer son droit de rétractation.</p></div>`,
  },
  {
    code: 'ecom_cgu',
    name: "Conditions générales d'utilisation (CGU) plateforme",
    category: 'commercial_financier',
    price: 6500,
    priceMax: 19000,
    description: "CGU pour plateforme digitale ou marketplace, conformes à la loi ivoirienne sur la cybercriminalité et à la réglementation ARTCI.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'editeur', label: "Éditeur de la plateforme (nom, RCCM)", type: 'text', required: true },
      { key: 'nom_plateforme', label: "Nom de la plateforme / application", type: 'text', required: true },
      { key: 'services_offerts', label: "Services offerts aux utilisateurs", type: 'textarea', required: true },
      { key: 'obligations_utilisateur', label: "Obligations et interdictions de l'utilisateur", type: 'textarea', required: true },
      { key: 'contact_juridique', label: "Contact pour questions juridiques", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONDITIONS GÉNÉRALES D'UTILISATION (CGU)</h1><p>Plateforme : <strong>{{nom_plateforme}}</strong> — Éditeur : {{editeur}}</p><h2>Article 1 – Acceptation</h2><p>L'accès et l'utilisation de {{nom_plateforme}} impliquent l'acceptation pleine et entière des présentes CGU.</p><h2>Article 2 – Services</h2><p>{{services_offerts}}</p><h2>Article 3 – Obligations de l'utilisateur</h2><p>{{obligations_utilisateur}}</p><h2>Article 4 – Responsabilité</h2><p>L'éditeur ne saurait être tenu responsable des dommages résultant de l'utilisation de la plateforme, sauf faute lourde de sa part.</p><h2>Article 5 – Contact</h2><p>{{contact_juridique}}</p></div>`,
  },
  {
    code: 'ecom_politique_confidentialite',
    name: "Politique de confidentialité site e-commerce",
    category: 'commercial_financier',
    price: 5500,
    priceMax: 16000,
    description: "Politique de protection des données personnelles pour site e-commerce, conforme à la loi ivoirienne sur la protection des données (loi ARTCI) et aux standards RGPD.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'responsable_traitement', label: "Responsable du traitement (société)", type: 'text', required: true },
      { key: 'donnees_collectees', label: "Types de données personnelles collectées", type: 'textarea', required: true },
      { key: 'finalites_traitement', label: "Finalités du traitement des données", type: 'textarea', required: true },
      { key: 'duree_conservation', label: "Durée de conservation des données", type: 'text', required: true },
      { key: 'contact_dpo', label: "Contact DPO / délégué à la protection", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE CONFIDENTIALITÉ</h1><p>Responsable du traitement : <strong>{{responsable_traitement}}</strong></p><h2>1. Données collectées</h2><p>{{donnees_collectees}}</p><h2>2. Finalités</h2><p>{{finalites_traitement}}</p><h2>3. Durée de conservation</h2><p>{{duree_conservation}}</p><h2>4. Vos droits</h2><p>Vous disposez d'un droit d'accès, de rectification, d'effacement et de portabilité de vos données. Pour exercer ces droits, contactez : {{contact_dpo}}.</p><h2>5. Sécurité</h2><p>Nous mettons en oeuvre des mesures techniques et organisationnelles appropriées pour protéger vos données contre toute violation.</p></div>`,
  },
  {
    code: 'ecom_politique_retours',
    name: "Politique de retours et remboursements",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Politique de retours, échanges et remboursements pour boutique e-commerce opérant en Afrique francophone, claire et conforme aux droits des consommateurs.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'boutique', label: "Nom de la boutique en ligne", type: 'text', required: true },
      { key: 'delai_retour', label: "Délai de retour accepté (jours)", type: 'text', required: true },
      { key: 'conditions_retour', label: "Conditions d'acceptation des retours", type: 'textarea', required: true },
      { key: 'procedure_remboursement', label: "Procédure de remboursement", type: 'textarea', required: true },
      { key: 'contact_service_client', label: "Contact service client", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE RETOURS ET REMBOURSEMENTS</h1><p>Boutique : <strong>{{boutique}}</strong></p><h2>Délai de retour</h2><p>Vous disposez de {{delai_retour}} jours à compter de la réception pour retourner un article.</p><h2>Conditions de retour</h2><p>{{conditions_retour}}</p><h2>Procédure de remboursement</h2><p>{{procedure_remboursement}}</p><h2>Contact</h2><p>Pour toute demande de retour : {{contact_service_client}}</p></div>`,
  },
  {
    code: 'ecom_marketplace_vendeur',
    name: "Contrat de marketplace (vendeur tiers)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Contrat encadrant l'accès d'un vendeur tiers à une marketplace africaine, définissant les droits, obligations et commissions applicables.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'operateur_marketplace', label: "Opérateur de la marketplace", type: 'text', required: true },
      { key: 'vendeur_tiers', label: "Vendeur tiers (nom, RCCM)", type: 'text', required: true },
      { key: 'categories_produits', label: "Catégories de produits autorisées", type: 'textarea', required: true },
      { key: 'commission', label: "Taux de commission de la plateforme (%)", type: 'text', required: true },
      { key: 'obligations_vendeur', label: "Obligations du vendeur tiers", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARKETPLACE — VENDEUR TIERS</h1><p>Opérateur : <strong>{{operateur_marketplace}}</strong> — Vendeur : <strong>{{vendeur_tiers}}</strong></p><h2>Article 1 – Accès à la plateforme</h2><p>L'opérateur autorise le vendeur à proposer les catégories suivantes : {{categories_produits}}.</p><h2>Article 2 – Commission</h2><p>Commission prélevée par la plateforme : {{commission}} sur chaque transaction réalisée.</p><h2>Article 3 – Obligations du vendeur</h2><p>{{obligations_vendeur}}</p><h2>Article 4 – Responsabilités</h2><p>Le vendeur tiers reste seul responsable de la conformité de ses produits, de la qualité des livraisons et du service après-vente.</p></div>`,
  },
  {
    code: 'ecom_paiement_psp',
    name: "Accord de service de paiement en ligne (PSP)",
    category: 'commercial_financier',
    price: 9000,
    priceMax: 27000,
    description: "Accord entre un marchand e-commerce et un prestataire de services de paiement (PSP / Mobile Money) pour les paiements en ligne en Afrique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'marchand', label: "Marchand e-commerce (nom, RCCM)", type: 'text', required: true },
      { key: 'psp', label: "Prestataire PSP (nom, agrément BCEAO)", type: 'text', required: true },
      { key: 'moyens_paiement', label: "Moyens de paiement intégrés (Mobile Money, carte, etc.)", type: 'text', required: true },
      { key: 'frais_transaction', label: "Frais de transaction (%)", type: 'text', required: true },
      { key: 'delai_virement', label: "Délai de reversement des fonds au marchand", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PAIEMENT EN LIGNE (PSP)</h1><p>Marchand : <strong>{{marchand}}</strong> — PSP : <strong>{{psp}}</strong></p><h2>Article 1 – Services de paiement</h2><p>Moyens de paiement intégrés : {{moyens_paiement}}.</p><h2>Article 2 – Frais</h2><p>Frais de transaction : {{frais_transaction}} sur chaque paiement traité.</p><h2>Article 3 – Reversement</h2><p>Les fonds collectés seront reversés au marchand dans un délai de {{delai_virement}}.</p><h2>Article 4 – Sécurité et conformité</h2><p>Le PSP s'engage à respecter les normes PCI-DSS et les instructions de la BCEAO relatives à la monnaie électronique.</p></div>`,
  },
  {
    code: 'ecom_dropshipping',
    name: "Contrat de dropshipping fournisseur",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 21000,
    description: "Contrat de dropshipping définissant les relations entre une boutique en ligne et son fournisseur-expéditeur direct pour le marché africain.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'revendeur', label: "Revendeur e-commerce (dropshippeur)", type: 'text', required: true },
      { key: 'fournisseur', label: "Fournisseur / expéditeur direct", type: 'text', required: true },
      { key: 'produits', label: "Gamme de produits en dropshipping", type: 'textarea', required: true },
      { key: 'prix_achat', label: "Prix d'achat fournisseur et conditions", type: 'text', required: true },
      { key: 'delai_expedition', label: "Délai d'expédition garanti", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE DROPSHIPPING</h1><p>Revendeur : <strong>{{revendeur}}</strong> — Fournisseur : <strong>{{fournisseur}}</strong></p><h2>Article 1 – Fonctionnement</h2><p>Le fournisseur expédie directement les commandes passées sur la boutique du revendeur, sans que ce dernier ne gère de stock physique.</p><h2>Article 2 – Produits</h2><p>{{produits}}</p><h2>Article 3 – Prix et marges</h2><p>{{prix_achat}}</p><h2>Article 4 – Expédition</h2><p>Délai d'expédition garanti : {{delai_expedition}}. En cas de retard, le fournisseur s'engage à informer le revendeur sans délai.</p></div>`,
  },
  {
    code: 'ecom_affiliation',
    name: "Accord d'affiliation marketing digital",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord d'affiliation entre une marque ou boutique e-commerce et un affilié digital (blogueur, influenceur, site comparateur) pour la génération de leads ou ventes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'annonceur', label: "Annonceur (marque ou boutique)", type: 'text', required: true },
      { key: 'affilie', label: "Affilié (nom, site ou réseau)", type: 'text', required: true },
      { key: 'programme', label: "Description du programme d'affiliation", type: 'textarea', required: true },
      { key: 'commission_affiliation', label: "Commission par vente ou lead (% ou montant fixe)", type: 'text', required: true },
      { key: 'tracking', label: "Outil de tracking utilisé", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'AFFILIATION MARKETING DIGITAL</h1><p>Annonceur : <strong>{{annonceur}}</strong> — Affilié : <strong>{{affilie}}</strong></p><h2>Article 1 – Programme</h2><p>{{programme}}</p><h2>Article 2 – Rémunération</h2><p>{{commission_affiliation}} par vente / lead qualifié attribué à l'affilié via le système de tracking.</p><h2>Article 3 – Tracking</h2><p>Outil utilisé : {{tracking}}. Les statistiques du système de tracking font foi en cas de litige.</p><h2>Article 4 – Obligations de l'affilié</h2><p>L'affilié s'interdit tout trafic artificiel, toute publicité mensongère et toute utilisation non autorisée de la marque de l'annonceur.</p></div>`,
  },
  {
    code: 'ecom_fulfillment',
    name: "Contrat de service d'entrepôt e-commerce (fulfillment)",
    category: 'commercial_financier',
    price: 9000,
    priceMax: 27000,
    description: "Contrat de fulfillment (stockage, préparation, expédition) entre un marchand e-commerce et un prestataire logistique en Afrique francophone.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'marchand', label: "Marchand e-commerce", type: 'text', required: true },
      { key: 'prestataire_fulfillment', label: "Prestataire de fulfillment (entrepôt)", type: 'text', required: true },
      { key: 'volume_sku', label: "Volume de SKU et capacité de stockage", type: 'text', required: true },
      { key: 'services_inclus', label: "Services inclus (réception, stockage, picking, expédition)", type: 'textarea', required: true },
      { key: 'tarification', label: "Tarification (par unité stockée, par commande préparée)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE FULFILLMENT E-COMMERCE</h1><p>Marchand : <strong>{{marchand}}</strong> — Prestataire : <strong>{{prestataire_fulfillment}}</strong></p><h2>Article 1 – Volume</h2><p>{{volume_sku}}</p><h2>Article 2 – Services</h2><p>{{services_inclus}}</p><h2>Article 3 – Tarification</h2><p>{{tarification}}</p><h2>Article 4 – Responsabilité</h2><p>Le prestataire est responsable des stocks confiés à compter de leur réception en entrepôt. Une assurance couvrant la valeur des stocks doit être maintenue en permanence.</p></div>`,
  },
  {
    code: 'ecom_livraison_last_mile',
    name: "Accord de service de livraison last mile",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 21000,
    description: "Accord de livraison du dernier kilomètre entre une plateforme e-commerce et un transporteur local en Afrique francophone (moto-coursiers, camionnettes).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'plateforme', label: "Plateforme e-commerce / expéditeur", type: 'text', required: true },
      { key: 'transporteur', label: "Transporteur last mile (nom, agrément)", type: 'text', required: true },
      { key: 'zone_couverture', label: "Zone géographique de couverture", type: 'text', required: true },
      { key: 'delai_livraison', label: "Délai de livraison garanti (heures / jours)", type: 'text', required: true },
      { key: 'tarif_livraison', label: "Tarif de livraison par colis", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE LIVRAISON LAST MILE</h1><p>Expéditeur : <strong>{{plateforme}}</strong> — Transporteur : <strong>{{transporteur}}</strong></p><h2>Article 1 – Zone</h2><p>Zone couverte : {{zone_couverture}}</p><h2>Article 2 – Délais</h2><p>Délai de livraison garanti : {{delai_livraison}} à compter de la prise en charge du colis.</p><h2>Article 3 – Tarifs</h2><p>{{tarif_livraison}}</p><h2>Article 4 – Responsabilité</h2><p>Le transporteur est responsable des colis à compter de leur prise en charge jusqu'à la remise effective au destinataire.</p></div>`,
  },
  {
    code: 'ecom_colisage',
    name: "Contrat de service de colisage e-commerce",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de sous-traitance du conditionnement et colisage des commandes e-commerce à un prestataire spécialisé en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'donneur_ordre', label: "Donneur d'ordre (e-commerçant)", type: 'text', required: true },
      { key: 'prestataire_colisage', label: "Prestataire de colisage", type: 'text', required: true },
      { key: 'types_emballages', label: "Types d'emballages utilisés", type: 'text', required: true },
      { key: 'volume_commandes', label: "Volume mensuel estimé de commandes", type: 'text', required: true },
      { key: 'prix_unitaire', label: "Prix unitaire par colis préparé", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE COLISAGE E-COMMERCE</h1><p>Donneur d'ordre : <strong>{{donneur_ordre}}</strong> — Prestataire : <strong>{{prestataire_colisage}}</strong></p><h2>Article 1 – Emballages</h2><p>Types d'emballages : {{types_emballages}}</p><h2>Article 2 – Volume</h2><p>Volume mensuel estimé : {{volume_commandes}}</p><h2>Article 3 – Tarification</h2><p>Prix unitaire : {{prix_unitaire}} par colis conditionné.</p><h2>Article 4 – Qualité</h2><p>Le prestataire s'engage à respecter les standards d'emballage définis par le donneur d'ordre et à garantir l'intégrité des produits conditionnés.</p></div>`,
  },
  {
    code: 'ecom_suivi_colis',
    name: "Accord de service de suivi colis",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Accord pour l'intégration d'un service de suivi des colis en temps réel sur une plateforme e-commerce africaine (tracking API).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'plateforme_ecommerce', label: "Plateforme e-commerce cliente", type: 'text', required: true },
      { key: 'fournisseur_tracking', label: "Fournisseur de solution de tracking", type: 'text', required: true },
      { key: 'fonctionnalites', label: "Fonctionnalités de suivi incluses", type: 'textarea', required: true },
      { key: 'sla_disponibilite', label: "SLA de disponibilité de l'API (%)", type: 'text', required: true },
      { key: 'tarif_mensuel', label: "Tarif mensuel ou par requête", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SUIVI COLIS</h1><p>Client : <strong>{{plateforme_ecommerce}}</strong> — Fournisseur : <strong>{{fournisseur_tracking}}</strong></p><h2>Article 1 – Fonctionnalités</h2><p>{{fonctionnalites}}</p><h2>Article 2 – Niveau de service</h2><p>Disponibilité garantie de l'API : {{sla_disponibilite}}. Toute indisponibilité supérieure à 4 heures consécutives donne droit à un avoir.</p><h2>Article 3 – Tarification</h2><p>{{tarif_mensuel}}</p></div>`,
  },
  {
    code: 'ecom_influenceur',
    name: "Accord de partenariat influenceur-marque",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de partenariat entre une marque e-commerce et un influenceur digital africain pour des campagnes de promotion sur les réseaux sociaux.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'marque', label: "Marque / annonceur", type: 'text', required: true },
      { key: 'influenceur', label: "Influenceur (nom, plateforme, nombre d'abonnés)", type: 'text', required: true },
      { key: 'campagne', label: "Description de la campagne et contenus attendus", type: 'textarea', required: true },
      { key: 'remuneration', label: "Rémunération (cachet, produits offerts, commission)", type: 'text', required: true },
      { key: 'duree_campagne', label: "Durée de la campagne", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT INFLUENCEUR-MARQUE</h1><p>Marque : <strong>{{marque}}</strong> — Influenceur : <strong>{{influenceur}}</strong></p><h2>Article 1 – Campagne</h2><p>{{campagne}}</p><h2>Article 2 – Rémunération</h2><p>{{remuneration}}</p><h2>Article 3 – Durée</h2><p>{{duree_campagne}}</p><h2>Article 4 – Droits et mentions légales</h2><p>L'influenceur s'engage à mentionner explicitement le caractère sponsorisé de tout contenu publié (#partenariat, #publiée). La marque conserve les droits d'utilisation des contenus produits pour une durée d'un an.</p></div>`,
  },
  {
    code: 'ecom_avis_clients',
    name: "Contrat de service de gestion des avis clients",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Contrat de service pour la collecte, modération et affichage des avis clients sur une boutique e-commerce africaine, conforme aux bonnes pratiques anti-fraude.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'marchand', label: "Marchand e-commerce", type: 'text', required: true },
      { key: 'prestataire_avis', label: "Prestataire de solution d'avis", type: 'text', required: true },
      { key: 'fonctionnalites_avis', label: "Fonctionnalités (collecte, modération, réponse)", type: 'textarea', required: true },
      { key: 'tarif_avis', label: "Tarif mensuel du service", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE GESTION DES AVIS CLIENTS</h1><p>Marchand : <strong>{{marchand}}</strong> — Prestataire : <strong>{{prestataire_avis}}</strong></p><h2>Article 1 – Fonctionnalités</h2><p>{{fonctionnalites_avis}}</p><h2>Article 2 – Tarification</h2><p>{{tarif_avis}}</p><h2>Article 3 – Intégrité des avis</h2><p>Le prestataire s'engage à ne diffuser que des avis vérifiés provenant d'acheteurs authentiques. Toute falsification d'avis est strictement interdite et engage la responsabilité du prestataire.</p></div>`,
  },
  {
    code: 'ecom_traduction',
    name: "Accord de service de traduction site e-commerce",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Accord de traduction multilingue du contenu d'un site e-commerce (français, anglais, portugais, langues locales) pour couvrir les marchés africains ciblés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'client', label: "Client (site e-commerce)", type: 'text', required: true },
      { key: 'prestataire_traduction', label: "Prestataire de traduction", type: 'text', required: true },
      { key: 'langues', label: "Langues source et cibles", type: 'text', required: true },
      { key: 'volume_contenu', label: "Volume de contenu à traduire (mots / pages)", type: 'text', required: true },
      { key: 'tarif_traduction', label: "Tarif (par mot ou forfait)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TRADUCTION — SITE E-COMMERCE</h1><p>Client : <strong>{{client}}</strong> — Prestataire : <strong>{{prestataire_traduction}}</strong></p><h2>Article 1 – Langues</h2><p>Langues concernées : {{langues}}</p><h2>Article 2 – Volume</h2><p>{{volume_contenu}}</p><h2>Article 3 – Tarification</h2><p>{{tarif_traduction}}</p><h2>Article 4 – Qualité</h2><p>Le prestataire garantit des traductions réalisées par des traducteurs natifs certifiés. Toute erreur significative sera corrigée sans frais supplémentaires.</p></div>`,
  },
  {
    code: 'ecom_seo',
    name: "Contrat de service de référencement SEO boutique",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Contrat de prestation SEO pour améliorer le positionnement d'une boutique e-commerce africaine sur les moteurs de recherche (Google, Bing).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'boutique', label: "Boutique e-commerce (URL)", type: 'text', required: true },
      { key: 'agence_seo', label: "Agence / prestataire SEO", type: 'text', required: true },
      { key: 'mots_cles_cibles', label: "Mots-clés cibles principaux", type: 'textarea', required: true },
      { key: 'prestations_seo', label: "Prestations incluses (audit, optimisation on-page, netlinking)", type: 'textarea', required: true },
      { key: 'tarif_mensuel_seo', label: "Tarif mensuel de la prestation", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE RÉFÉRENCEMENT SEO</h1><p>Boutique : <strong>{{boutique}}</strong> — Agence : <strong>{{agence_seo}}</strong></p><h2>Article 1 – Mots-clés cibles</h2><p>{{mots_cles_cibles}}</p><h2>Article 2 – Prestations</h2><p>{{prestations_seo}}</p><h2>Article 3 – Tarification</h2><p>{{tarif_mensuel_seo}}</p><h2>Article 4 – Reporting</h2><p>L'agence s'engage à fournir un rapport mensuel de positionnement et de trafic organique. Les résultats SEO ne peuvent être garantis en raison des algorithmes des moteurs de recherche.</p></div>`,
  },
  {
    code: 'ecom_email_marketing',
    name: "Accord de service d'email marketing automatisé",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord pour la mise en place et la gestion de campagnes d'email marketing automatisées pour une boutique e-commerce africaine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'client_ecommerce', label: "Client e-commerce", type: 'text', required: true },
      { key: 'prestataire_emailing', label: "Prestataire d'emailing", type: 'text', required: true },
      { key: 'scenarios_automatises', label: "Scénarios automatisés (panier abandonné, bienvenue, relance)", type: 'textarea', required: true },
      { key: 'volume_contacts', label: "Volume de contacts / abonnés", type: 'text', required: true },
      { key: 'tarif_emailing', label: "Tarif mensuel", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'EMAIL MARKETING AUTOMATISÉ</h1><p>Client : <strong>{{client_ecommerce}}</strong> — Prestataire : <strong>{{prestataire_emailing}}</strong></p><h2>Article 1 – Scénarios</h2><p>{{scenarios_automatises}}</p><h2>Article 2 – Volume</h2><p>{{volume_contacts}}</p><h2>Article 3 – Tarification</h2><p>{{tarif_emailing}}</p><h2>Article 4 – Conformité</h2><p>Le prestataire s'engage à respecter les lois anti-spam applicables et à intégrer un lien de désinscription dans chaque email envoyé.</p></div>`,
  },
  {
    code: 'ecom_publicite_ligne',
    name: "Accord de service de publicité en ligne (Google Ads/Meta)",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de gestion de campagnes publicitaires en ligne (Google Ads, Facebook/Instagram Ads) pour une boutique e-commerce opérant en Afrique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'annonceur', label: "Annonceur / boutique e-commerce", type: 'text', required: true },
      { key: 'agence_pub', label: "Agence de publicité digitale", type: 'text', required: true },
      { key: 'plateformes_pub', label: "Plateformes publicitaires (Google, Meta, TikTok)", type: 'text', required: true },
      { key: 'budget_mensuel', label: "Budget publicitaire mensuel alloué", type: 'text', required: true },
      { key: 'honoraires_gestion', label: "Honoraires de gestion de l'agence", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PUBLICITÉ EN LIGNE</h1><p>Annonceur : <strong>{{annonceur}}</strong> — Agence : <strong>{{agence_pub}}</strong></p><h2>Article 1 – Plateformes</h2><p>Plateformes concernées : {{plateformes_pub}}</p><h2>Article 2 – Budget</h2><p>Budget publicitaire mensuel : {{budget_mensuel}}. Ce budget est facturé directement par les plateformes à l'annonceur.</p><h2>Article 3 – Honoraires</h2><p>{{honoraires_gestion}}</p><h2>Article 4 – Reporting</h2><p>L'agence fournit un rapport bimensuel de performance des campagnes (CPM, CPC, ROAS, conversions).</p></div>`,
  },
  {
    code: 'ecom_photo_produits',
    name: "Contrat de service de photographie produits e-commerce",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13000,
    description: "Contrat de prestation photographique pour la réalisation de photos produits de qualité e-commerce, incluant retouches et livraison des fichiers numériques.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'client', label: "Client (boutique e-commerce)", type: 'text', required: true },
      { key: 'photographe', label: "Photographe / studio", type: 'text', required: true },
      { key: 'nombre_produits', label: "Nombre de produits à photographier", type: 'text', required: true },
      { key: 'types_prises', label: "Types de prises de vue (fond blanc, ambiance, 360°)", type: 'text', required: true },
      { key: 'tarif_photo', label: "Tarif par produit ou forfait global", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PHOTOGRAPHIE PRODUITS E-COMMERCE</h1><p>Client : <strong>{{client}}</strong> — Photographe : <strong>{{photographe}}</strong></p><h2>Article 1 – Volume</h2><p>Nombre de produits : {{nombre_produits}}</p><h2>Article 2 – Prises de vue</h2><p>Types de prises : {{types_prises}}</p><h2>Article 3 – Tarification</h2><p>{{tarif_photo}}</p><h2>Article 4 – Droits d'auteur</h2><p>À la livraison et après paiement intégral, le client dispose d'une licence exclusive et permanente d'utilisation des images sur tous supports numériques et physiques.</p></div>`,
  },
  {
    code: 'ecom_encheres_ligne',
    name: "Accord de plateforme d'enchères en ligne",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Accord encadrant l'exploitation d'une plateforme d'enchères en ligne en Afrique francophone, définissant les règles applicables aux vendeurs et acheteurs.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 54,
    fieldsJson: F([
      { key: 'operateur_encheres', label: "Opérateur de la plateforme d'enchères", type: 'text', required: true },
      { key: 'utilisateur', label: "Utilisateur (vendeur ou acheteur)", type: 'text', required: true },
      { key: 'regles_encheres', label: "Règles de fonctionnement des enchères", type: 'textarea', required: true },
      { key: 'commission_enchere', label: "Commission prélevée sur les ventes réalisées", type: 'text', required: true },
      { key: 'litiges_encheres', label: "Procédure de résolution des litiges", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PLATEFORME D'ENCHÈRES EN LIGNE</h1><p>Opérateur : <strong>{{operateur_encheres}}</strong> — Utilisateur : <strong>{{utilisateur}}</strong></p><h2>Article 1 – Règles des enchères</h2><p>{{regles_encheres}}</p><h2>Article 2 – Commission</h2><p>{{commission_enchere}}</p><h2>Article 3 – Résolution des litiges</h2><p>{{litiges_encheres}}</p><h2>Article 4 – Responsabilité</h2><p>L'opérateur agit en tant qu'intermédiaire technique. La transaction est conclue directement entre vendeur et acheteur. L'opérateur ne saurait être tenu pour responsable de la qualité des biens vendus.</p></div>`,
  },
  {
    code: 'ecom_comparateur_prix',
    name: "Contrat de service de comparateurs de prix",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Contrat d'intégration d'une boutique e-commerce à un comparateur de prix en ligne actif sur le marché africain francophone.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'marchand', label: "Marchand e-commerce partenaire", type: 'text', required: true },
      { key: 'comparateur', label: "Plateforme comparateur de prix", type: 'text', required: true },
      { key: 'flux_produits', label: "Format et fréquence du flux produits", type: 'text', required: true },
      { key: 'cout_clic', label: "Coût par clic (CPC) ou abonnement mensuel", type: 'text', required: true },
      { key: 'categories_integrees', label: "Catégories de produits intégrées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE — COMPARATEUR DE PRIX</h1><p>Marchand : <strong>{{marchand}}</strong> — Comparateur : <strong>{{comparateur}}</strong></p><h2>Article 1 – Flux produits</h2><p>Format et fréquence : {{flux_produits}}</p><h2>Article 2 – Catégories</h2><p>{{categories_integrees}}</p><h2>Article 3 – Facturation</h2><p>{{cout_clic}}</p><h2>Article 4 – Exactitude des données</h2><p>Le marchand est responsable de l'exactitude et de la mise à jour des prix et des disponibilités dans le flux transmis. Le comparateur n'est pas responsable des erreurs de prix affichées résultant d'un flux obsolète.</p></div>`,
  },
  {
    code: 'ecom_chat_support',
    name: "Accord de service de chat support client",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Accord pour l'intégration et la gestion d'un service de chat en ligne (live chat ou chatbot) pour une boutique e-commerce africaine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'boutique', label: "Boutique e-commerce cliente", type: 'text', required: true },
      { key: 'fournisseur_chat', label: "Fournisseur de solution de chat", type: 'text', required: true },
      { key: 'type_chat', label: "Type de chat (live, chatbot IA, hybride)", type: 'text', required: true },
      { key: 'plages_horaires', label: "Plages horaires de disponibilité", type: 'text', required: true },
      { key: 'tarif_chat', label: "Tarif mensuel de la solution", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CHAT SUPPORT CLIENT</h1><p>Boutique : <strong>{{boutique}}</strong> — Fournisseur : <strong>{{fournisseur_chat}}</strong></p><h2>Article 1 – Solution</h2><p>Type de chat : {{type_chat}}</p><h2>Article 2 – Disponibilité</h2><p>Plages horaires : {{plages_horaires}}</p><h2>Article 3 – Tarif</h2><p>{{tarif_chat}}</p><h2>Article 4 – Données et confidentialité</h2><p>Les conversations sont traitées conformément à la politique de confidentialité du fournisseur et aux lois de protection des données applicables en Côte d'Ivoire.</p></div>`,
  },
  {
    code: 'ecom_plan_developpement',
    name: "Plan de développement e-commerce Afrique",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Document stratégique planifiant le lancement ou l'expansion d'une activité e-commerce sur les marchés africains francophones sur 2 à 3 ans.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise porteur du projet", type: 'text', required: true },
      { key: 'marches_cibles', label: "Marchés africains cibles", type: 'text', required: true },
      { key: 'offre_ecommerce', label: "Offre e-commerce (produits / services)", type: 'textarea', required: true },
      { key: 'investissements_prevus', label: "Investissements prévus (technologie, marketing, logistique)", type: 'textarea', required: true },
      { key: 'objectifs_ca', label: "Objectifs de chiffre d'affaires sur 3 ans", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT E-COMMERCE AFRIQUE</h1><p>Entreprise : <strong>{{entreprise}}</strong></p><h2>1. Marchés cibles</h2><p>{{marches_cibles}}</p><h2>2. Offre</h2><p>{{offre_ecommerce}}</p><h2>3. Investissements</h2><p>{{investissements_prevus}}</p><h2>4. Objectifs financiers</h2><p>{{objectifs_ca}}</p><h2>5. Facteurs clés de succès</h2><p>Adoption du Mobile Money, pénétration smartphone, partenariats logistiques locaux, confiance client et politique de retours claire.</p></div>`,
  },
  {
    code: 'ecom_rapport_performance',
    name: "Rapport de performance boutique en ligne",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Rapport d'analyse des performances d'une boutique e-commerce africaine : trafic, conversions, panier moyen, taux de retour et recommandations.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'boutique', label: "Boutique en ligne analysée", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte", type: 'text', required: true },
      { key: 'kpis_cles', label: "KPIs clés (trafic, taux de conversion, CA, panier moyen)", type: 'textarea', required: true },
      { key: 'analyse_performances', label: "Analyse des performances et points d'amélioration", type: 'textarea', required: true },
      { key: 'recommandations', label: "Recommandations stratégiques", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE — BOUTIQUE EN LIGNE</h1><p>Boutique : <strong>{{boutique}}</strong> — Période : {{periode_rapport}}</p><h2>1. KPIs clés</h2><p>{{kpis_cles}}</p><h2>2. Analyse</h2><p>{{analyse_performances}}</p><h2>3. Recommandations</h2><p>{{recommandations}}</p><h2>4. Prochaines étapes</h2><p>Un plan d'actions priorisé sera établi sur la base de ces recommandations pour le trimestre suivant.</p></div>`,
  },
  {
    code: 'ecom_charte_responsable',
    name: "Charte du e-commerce responsable",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Charte définissant les engagements d'une plateforme e-commerce africaine en matière de pratiques commerciales responsables, éthiques et durables.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'plateforme', label: "Nom de la plateforme e-commerce", type: 'text', required: true },
      { key: 'engagements_ethiques', label: "Engagements éthiques envers les clients", type: 'textarea', required: true },
      { key: 'engagements_vendeurs', label: "Engagements envers les vendeurs partenaires", type: 'textarea', required: true },
      { key: 'engagements_environnementaux', label: "Engagements environnementaux (emballages, carbon)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DU E-COMMERCE RESPONSABLE</h1><p>Plateforme : <strong>{{plateforme}}</strong></p><h2>1. Engagements envers nos clients</h2><p>{{engagements_ethiques}}</p><h2>2. Engagements envers nos vendeurs</h2><p>{{engagements_vendeurs}}</p><h2>3. Engagements environnementaux</h2><p>{{engagements_environnementaux}}</p><h2>4. Gouvernance</h2><p>Un comité d'éthique annuel évaluera le respect de cette charte et publiera un rapport de transparence accessible à tous les utilisateurs de la plateforme.</p></div>`,
  },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 47a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
