import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── 25 TEMPLATES EAU / ASSAINISSEMENT ───────────────────────────────────
  {
    code: 'eau_branchement_reseau',
    name: "Contrat de branchement au réseau eau potable",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat officiel de raccordement d'un abonné au réseau d'eau potable, conforme aux exigences SODECI/ONEP et droit OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_abonne', label: "Nom complet de l'abonné", type: 'text', required: true },
      { key: 'adresse_branchement', label: "Adresse du point de branchement", type: 'text', required: true },
      { key: 'date_contrat', label: "Date de signature", type: 'date', required: true },
      { key: 'numero_compteur', label: "Numéro de compteur", type: 'text', required: true },
      { key: 'observations', label: "Observations techniques", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE BRANCHEMENT AU RÉSEAU EAU POTABLE</h1><p>Entre la société distributrice d'eau et <strong>{{nom_abonne}}</strong>, il est convenu ce qui suit :</p><h2>Article 1 – Objet</h2><p>Le présent contrat a pour objet le raccordement de l'abonné au réseau d'eau potable à l'adresse suivante : {{adresse_branchement}}.</p><h2>Article 2 – Compteur</h2><p>Un compteur portant le numéro <strong>{{numero_compteur}}</strong> sera installé au point de branchement.</p><h2>Article 3 – Obligations des parties</h2><p>L'abonné s'engage à respecter les conditions générales de distribution et à payer les factures dans les délais prescrits.</p><h2>Article 4 – Observations</h2><p>{{observations}}</p><p>Fait à Abidjan, le {{date_contrat}}</p><p>Signature abonné : _______________&nbsp;&nbsp;&nbsp; Cachet distributeur : _______________</p></div>`,
  },
  {
    code: 'eau_abonnement_sodeci',
    name: "Contrat abonnement eau SODECI (modèle)",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 10000,
    description: "Modèle de contrat d'abonnement au service de l'eau de la SODECI pour particuliers et entreprises, Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_abonne', label: "Nom / Raison sociale", type: 'text', required: true },
      { key: 'numero_abonnement', label: "Numéro d'abonnement", type: 'text', required: true },
      { key: 'categorie_abonne', label: "Catégorie (domestique/professionnel)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début d'abonnement", type: 'date', required: true },
      { key: 'commune', label: "Commune", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ABONNEMENT EAU – SODECI</h1><p>La Société de Distribution d'Eau de Côte d'Ivoire (SODECI) et <strong>{{nom_abonne}}</strong> concluent le présent contrat d'abonnement.</p><h2>Article 1 – Identification</h2><p>Numéro d'abonnement : <strong>{{numero_abonnement}}</strong> – Catégorie : {{categorie_abonne}} – Commune : {{commune}}.</p><h2>Article 2 – Prise d'effet</h2><p>Le présent abonnement prend effet le {{date_debut}} et est soumis au tarif en vigueur de la SODECI.</p><h2>Article 3 – Obligations de l'abonné</h2><p>L'abonné s'engage à utiliser l'eau exclusivement pour l'usage déclaré, à entretenir les installations intérieures et à régler les factures à échéance.</p><h2>Article 4 – Résiliation</h2><p>Le contrat peut être résilié par l'une ou l'autre des parties moyennant un préavis de 30 jours.</p><p>Fait à {{commune}}, le {{date_debut}}</p></div>`,
  },
  {
    code: 'eau_forage_potable',
    name: "Accord de service de forage d'eau potable",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 25000,
    description: "Accord entre un maître d'ouvrage et un prestataire de forage pour la réalisation d'un puits ou forage d'eau potable en zone rurale ou périurbaine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'entreprise_forage', label: "Entreprise de forage", type: 'text', required: true },
      { key: 'localite', label: "Localité / Village", type: 'text', required: true },
      { key: 'profondeur_prevue', label: "Profondeur prévue (mètres)", type: 'text', required: true },
      { key: 'date_debut_travaux', label: "Date de début des travaux", type: 'date', required: true },
      { key: 'montant_contrat', label: "Montant du contrat (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE FORAGE D'EAU POTABLE</h1><p>Entre <strong>{{maitre_ouvrage}}</strong> (Maître d'ouvrage) et <strong>{{entreprise_forage}}</strong> (Prestataire), il est convenu :</p><h2>Article 1 – Objet</h2><p>Réalisation d'un forage d'eau potable à <strong>{{localite}}</strong> jusqu'à une profondeur prévue de {{profondeur_prevue}} mètres.</p><h2>Article 2 – Délai et démarrage</h2><p>Les travaux débutent le {{date_debut_travaux}} et seront exécutés conformément aux normes en vigueur.</p><h2>Article 3 – Prix</h2><p>Le montant total du contrat est de <strong>{{montant_contrat}} FCFA</strong> TTC, payable selon l'échéancier annexé.</p><h2>Article 4 – Garantie</h2><p>Le prestataire garantit le bon fonctionnement du forage pendant une durée de 12 mois à compter de la réception.</p><p>Fait à {{localite}}, le {{date_debut_travaux}}</p></div>`,
  },
  {
    code: 'eau_pompe_solaire',
    name: "Contrat de service de pompe à eau solaire",
    category: 'agro_environnement',
    price: 7000,
    priceMax: 20000,
    description: "Contrat de fourniture, installation et maintenance d'une pompe à eau solaire pour alimentation en eau potable hors réseau.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'client', label: "Nom du client / collectivité", type: 'text', required: true },
      { key: 'fournisseur', label: "Fournisseur / Installateur", type: 'text', required: true },
      { key: 'puissance_pompe', label: "Puissance de la pompe (Watts)", type: 'text', required: true },
      { key: 'lieu_installation', label: "Lieu d'installation", type: 'text', required: true },
      { key: 'date_installation', label: "Date d'installation prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE POMPE À EAU SOLAIRE</h1><p>Entre <strong>{{fournisseur}}</strong> et <strong>{{client}}</strong>, le présent contrat porte sur la fourniture et l'installation d'une pompe à eau solaire.</p><h2>Article 1 – Spécifications techniques</h2><p>Puissance : {{puissance_pompe}} W – Lieu : {{lieu_installation}}.</p><h2>Article 2 – Installation</h2><p>L'installation sera réalisée le {{date_installation}} par une équipe qualifiée du fournisseur.</p><h2>Article 3 – Maintenance</h2><p>Une maintenance préventive annuelle est incluse dans le présent contrat pour une durée de 3 ans.</p><h2>Article 4 – Garantie</h2><p>Le matériel est garanti 2 ans pièces et main-d'œuvre.</p><p>Signatures des parties : _______________</p></div>`,
  },
  {
    code: 'eau_chateau_communautaire',
    name: "Accord de gestion d'un château d'eau communautaire",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Accord entre une collectivité locale et un comité de gestion pour l'exploitation et la maintenance d'un château d'eau communautaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité / Mairie", type: 'text', required: true },
      { key: 'comite_gestion', label: "Nom du comité de gestion", type: 'text', required: true },
      { key: 'capacite_chateau', label: "Capacité du château (m³)", type: 'text', required: true },
      { key: 'localite', label: "Localité", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION D'UN CHÂTEAU D'EAU COMMUNAUTAIRE</h1><p>La <strong>{{collectivite}}</strong> et le <strong>{{comite_gestion}}</strong> conviennent de la gestion partagée du château d'eau situé à <strong>{{localite}}</strong>.</p><h2>Article 1 – Capacité</h2><p>Le château d'eau a une capacité de {{capacite_chateau}} m³ et alimente les ménages de la localité.</p><h2>Article 2 – Responsabilités du comité</h2><p>Le comité assure l'exploitation quotidienne, la collecte des redevances et la maintenance de premier niveau.</p><h2>Article 3 – Redevances</h2><p>Les tarifs de vente d'eau sont fixés en accord avec la collectivité et affichés publiquement.</p><h2>Article 4 – Contrôle</h2><p>La collectivité effectue un audit semestriel de la gestion financière et technique.</p><p>Fait à {{localite}}, le {{date_accord}}</p></div>`,
  },
  {
    code: 'eau_analyse_qualite',
    name: "Contrat de service d'analyse qualité eau",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 14000,
    description: "Contrat de prestation de services d'analyse physicochimique et bactériologique de la qualité de l'eau pour conformité aux normes OMS et nationales.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'client', label: "Client / Commanditaire", type: 'text', required: true },
      { key: 'laboratoire', label: "Laboratoire prestataire", type: 'text', required: true },
      { key: 'point_prelevement', label: "Point de prélèvement", type: 'text', required: true },
      { key: 'parametres_analyses', label: "Paramètres à analyser", type: 'textarea', required: true },
      { key: 'date_prelevement', label: "Date de prélèvement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D'ANALYSE QUALITÉ EAU</h1><p>Le laboratoire <strong>{{laboratoire}}</strong> s'engage à réaliser les analyses de qualité de l'eau pour le compte de <strong>{{client}}</strong>.</p><h2>Article 1 – Prélèvement</h2><p>Le prélèvement sera effectué le {{date_prelevement}} au point suivant : {{point_prelevement}}.</p><h2>Article 2 – Paramètres analysés</h2><p>{{parametres_analyses}}</p><h2>Article 3 – Normes de référence</h2><p>Les analyses seront réalisées conformément aux normes OMS et aux directives nationales de qualité de l'eau potable.</p><h2>Article 4 – Rapport</h2><p>Un rapport d'analyse sera remis sous 10 jours ouvrables après prélèvement.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_traitement_station',
    name: "Accord de traitement de l'eau (station de traitement)",
    category: 'agro_environnement',
    price: 9000,
    priceMax: 28000,
    description: "Accord pour la conception, construction ou exploitation d'une station de traitement d'eau potable conforme aux normes OHADA et environnementales.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur / Exploitant", type: 'text', required: true },
      { key: 'capacite_traitement', label: "Capacité de traitement (m³/jour)", type: 'text', required: true },
      { key: 'localisation', label: "Localisation de la station", type: 'text', required: true },
      { key: 'date_mise_service', label: "Date de mise en service prévue", type: 'date', required: true },
      { key: 'duree_accord', label: "Durée de l'accord (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRAITEMENT DE L'EAU</h1><p>Entre <strong>{{maitre_ouvrage}}</strong> et <strong>{{operateur}}</strong>, le présent accord porte sur l'exploitation d'une station de traitement d'eau potable.</p><h2>Article 1 – Capacité</h2><p>La station, située à <strong>{{localisation}}</strong>, traite jusqu'à {{capacite_traitement}} m³/jour.</p><h2>Article 2 – Mise en service</h2><p>La mise en service est prévue le {{date_mise_service}} pour une durée de {{duree_accord}} ans.</p><h2>Article 3 – Qualité</h2><p>L'eau traitée devra respecter en permanence les normes de potabilité en vigueur.</p><h2>Article 4 – Rapports</h2><p>L'opérateur soumet un rapport mensuel au maître d'ouvrage sur la qualité et les volumes traités.</p><p>Fait le {{date_mise_service}}</p></div>`,
  },
  {
    code: 'eau_distribution_rurale',
    name: "Contrat de service de distribution eau en zone rurale",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat régissant la distribution d'eau potable dans les zones rurales non desservies par le réseau national, incluant la gestion des bornes fontaines.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'operateur', label: "Opérateur distributeur", type: 'text', required: true },
      { key: 'village_beneficiaire', label: "Village / Zone bénéficiaire", type: 'text', required: true },
      { key: 'nombre_bornes', label: "Nombre de bornes fontaines", type: 'text', required: true },
      { key: 'tarif_m3', label: "Tarif au m³ (FCFA)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE DISTRIBUTION D'EAU EN ZONE RURALE</h1><p><strong>{{operateur}}</strong> s'engage à assurer la distribution d'eau potable dans la zone de <strong>{{village_beneficiaire}}</strong>.</p><h2>Article 1 – Infrastructure</h2><p>Le service sera assuré par {{nombre_bornes}} bornes fontaines implantées dans la zone.</p><h2>Article 2 – Tarification</h2><p>Le tarif appliqué aux usagers est de {{tarif_m3}} FCFA/m³, révisable annuellement.</p><h2>Article 3 – Continuité du service</h2><p>L'opérateur garantit la continuité du service 7 jours/7, sauf cas de force majeure dûment notifiée.</p><h2>Article 4 – Prise d'effet</h2><p>Le présent contrat prend effet le {{date_debut}}.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_reseau_communautaire',
    name: "Accord de réseau d'eau communautaire (comité de gestion)",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 14000,
    description: "Accord de création et de gouvernance d'un comité de gestion d'un réseau d'eau communautaire villageois en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'nom_comite', label: "Nom du comité de gestion", type: 'text', required: true },
      { key: 'village', label: "Village / Communauté", type: 'text', required: true },
      { key: 'nombre_membres', label: "Nombre de membres du comité", type: 'text', required: true },
      { key: 'president_comite', label: "Président du comité", type: 'text', required: true },
      { key: 'date_creation', label: "Date de création", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉSEAU D'EAU COMMUNAUTAIRE</h1><p>Le <strong>{{nom_comite}}</strong>, représentant la communauté de <strong>{{village}}</strong>, est créé ce jour pour gérer le réseau d'eau communautaire.</p><h2>Article 1 – Composition</h2><p>Le comité est composé de {{nombre_membres}} membres élus par la communauté, sous la présidence de <strong>{{president_comite}}</strong>.</p><h2>Article 2 – Missions</h2><p>Le comité gère l'exploitation technique, la collecte des redevances, la maintenance et les relations avec les autorités.</p><h2>Article 3 – Transparence</h2><p>Les comptes sont présentés à la communauté lors d'une assemblée générale semestrielle.</p><h2>Article 4 – Durée</h2><p>Le mandat du comité est de 2 ans, renouvelable par élection communautaire.</p><p>Fait à {{village}}, le {{date_creation}}</p></div>`,
  },
  {
    code: 'eau_canalisation_plomberie',
    name: "Contrat de service de canalisation et plomberie",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 12000,
    description: "Contrat de prestation de services de plomberie, pose de canalisations et travaux d'hydraulique pour particuliers, entreprises ou collectivités.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'client', label: "Client", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire plombier", type: 'text', required: true },
      { key: 'nature_travaux', label: "Nature des travaux", type: 'textarea', required: true },
      { key: 'adresse_chantier', label: "Adresse du chantier", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
      { key: 'montant_ttc', label: "Montant TTC (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE CANALISATION ET PLOMBERIE</h1><p>Entre <strong>{{prestataire}}</strong> et <strong>{{client}}</strong>, il est convenu d'effectuer des travaux de plomberie et canalisation.</p><h2>Article 1 – Travaux</h2><p>{{nature_travaux}}</p><h2>Article 2 – Chantier et délai</h2><p>Les travaux se dérouleront à {{adresse_chantier}} à compter du {{date_debut}}.</p><h2>Article 3 – Prix</h2><p>Montant total TTC : <strong>{{montant_ttc}} FCFA</strong>.</p><h2>Article 4 – Garantie</h2><p>Garantie de parfait achèvement : 1 an à compter de la réception des travaux.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_construction_step',
    name: "Contrat de construction d'une station d'épuration (STEP)",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 35000,
    description: "Contrat de maîtrise d'œuvre pour la conception et construction d'une station d'épuration des eaux usées conforme aux normes environnementales OHADA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'entreprise', label: "Entreprise de construction", type: 'text', required: true },
      { key: 'capacite_step', label: "Capacité (équivalent-habitants)", type: 'text', required: true },
      { key: 'localisation', label: "Localisation de la STEP", type: 'text', required: true },
      { key: 'date_debut_travaux', label: "Date de début des travaux", type: 'date', required: true },
      { key: 'delai_execution', label: "Délai d'exécution (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE CONSTRUCTION D'UNE STATION D'ÉPURATION (STEP)</h1><p>Le présent contrat est conclu entre <strong>{{maitre_ouvrage}}</strong> et <strong>{{entreprise}}</strong> pour la construction d'une STEP.</p><h2>Article 1 – Objet</h2><p>Construction d'une station d'épuration d'une capacité de {{capacite_step}} équivalents-habitants, à {{localisation}}.</p><h2>Article 2 – Délai</h2><p>Les travaux débutent le {{date_debut_travaux}} pour une durée de {{delai_execution}} mois.</p><h2>Article 3 – Normes</h2><p>La STEP sera construite conformément aux normes environnementales nationales et aux standards de l'UEMOA.</p><h2>Article 4 – Réception</h2><p>Une réception provisoire puis définitive sera organisée à l'issue des travaux.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_traitement_boues',
    name: "Accord de service de traitement des boues",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Accord de prestation pour la collecte, le transport et le traitement des boues de vidange issues des fosses septiques et stations d'épuration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'client', label: "Client / Générateur de boues", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire de traitement", type: 'text', required: true },
      { key: 'volume_estime', label: "Volume estimé (m³/mois)", type: 'text', required: true },
      { key: 'site_traitement', label: "Site de traitement", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TRAITEMENT DES BOUES</h1><p>Entre <strong>{{prestataire}}</strong> et <strong>{{client}}</strong>, le présent accord porte sur la gestion des boues de vidange.</p><h2>Article 1 – Prestations</h2><p>Collecte, transport et traitement des boues au site de <strong>{{site_traitement}}</strong>, pour un volume estimé de {{volume_estime}} m³/mois.</p><h2>Article 2 – Conformité environnementale</h2><p>Le traitement est réalisé conformément aux normes environnementales nationales et aux directives de l'OMS.</p><h2>Article 3 – Valorisation</h2><p>Les boues traitées peuvent être valorisées comme amendement organique agricole dans les conditions réglementaires.</p><p>Fait le {{date_debut}}</p></div>`,
  },
  {
    code: 'eau_curage_reseau',
    name: "Contrat de service de curage de réseau d'assainissement",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 15000,
    description: "Contrat de prestation pour le curage, nettoyage et débouchage des réseaux d'assainissement collectifs et privés.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'client', label: "Client / Bénéficiaire", type: 'text', required: true },
      { key: 'prestataire', label: "Entreprise de curage", type: 'text', required: true },
      { key: 'lineaire_reseau', label: "Linéaire de réseau à curer (ml)", type: 'text', required: true },
      { key: 'localisation', label: "Zone / Commune", type: 'text', required: true },
      { key: 'date_intervention', label: "Date d'intervention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE CURAGE DE RÉSEAU D'ASSAINISSEMENT</h1><p><strong>{{prestataire}}</strong> s'engage à réaliser le curage du réseau d'assainissement pour le compte de <strong>{{client}}</strong>.</p><h2>Article 1 – Prestations</h2><p>Curage et nettoyage de {{lineaire_reseau}} mètres linéaires de réseau dans la zone de <strong>{{localisation}}</strong>.</p><h2>Article 2 – Méthodes</h2><p>Les opérations seront réalisées par hydrocurage haute pression et aspiration des dépôts.</p><h2>Article 3 – Gestion des déchets</h2><p>Les matières extraites seront évacuées et traitées conformément à la réglementation environnementale.</p><p>Date d'intervention : {{date_intervention}}</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_gestion_pluviales',
    name: "Accord de gestion des eaux pluviales",
    category: 'agro_environnement',
    price: 7000,
    priceMax: 20000,
    description: "Accord de gestion et d'entretien du réseau de collecte des eaux pluviales entre une collectivité et un opérateur technique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité / Mairie", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur technique", type: 'text', required: true },
      { key: 'zone_intervention', label: "Zone d'intervention", type: 'text', required: true },
      { key: 'lineaire_caniveaux', label: "Linéaire de caniveaux (km)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DES EAUX PLUVIALES</h1><p>La <strong>{{collectivite}}</strong> confie à <strong>{{operateur}}</strong> la gestion du réseau d'eaux pluviales de la zone de {{zone_intervention}}.</p><h2>Article 1 – Périmètre</h2><p>Le périmètre d'intervention couvre {{lineaire_caniveaux}} km de caniveaux et ouvrages de collecte associés.</p><h2>Article 2 – Prestations</h2><p>L'opérateur assure le curage régulier, l'entretien des ouvrages et le débroussaillage des berges.</p><h2>Article 3 – Rapport</h2><p>Un rapport trimestriel d'activité est transmis à la collectivité.</p><p>Fait le {{date_accord}}</p></div>`,
  },
  {
    code: 'eau_fosse_septique',
    name: "Contrat de service de fosse septique",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de construction, vidange et maintenance de fosse septique pour habitations individuelles ou immeubles collectifs.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'proprietaire', label: "Propriétaire / Client", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien", type: 'text', required: true },
      { key: 'type_service', label: "Type de service (construction/vidange/maintenance)", type: 'text', required: true },
      { key: 'date_intervention', label: "Date d'intervention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE FOSSE SEPTIQUE</h1><p>Entre <strong>{{prestataire}}</strong> et <strong>{{proprietaire}}</strong>, il est convenu du service suivant concernant la fosse septique sise à {{adresse_bien}}.</p><h2>Article 1 – Nature du service</h2><p>Service demandé : <strong>{{type_service}}</strong></p><h2>Article 2 – Intervention</h2><p>L'intervention est planifiée le {{date_intervention}} par une équipe agréée.</p><h2>Article 3 – Évacuation</h2><p>Les matières de vidange seront évacuées vers un site de traitement agréé.</p><h2>Article 4 – Attestation</h2><p>Un bon de vidange certifié sera remis au client après chaque opération.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_collecte_eaux_usees',
    name: "Accord de service de collecte d'eaux usées",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Accord entre un générateur d'eaux usées industrielles ou domestiques et un opérateur de collecte agréé, conforme à la réglementation environnementale.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'generateur', label: "Générateur d'eaux usées", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur de collecte", type: 'text', required: true },
      { key: 'volume_mensuel', label: "Volume mensuel estimé (m³)", type: 'text', required: true },
      { key: 'type_eaux', label: "Type d'eaux usées (domestiques/industrielles)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE COLLECTE D'EAUX USÉES</h1><p><strong>{{operateur}}</strong> assure la collecte des eaux usées pour le compte de <strong>{{generateur}}</strong>.</p><h2>Article 1 – Volume et nature</h2><p>Volume estimé : {{volume_mensuel}} m³/mois – Type : {{type_eaux}}.</p><h2>Article 2 – Fréquence</h2><p>La collecte est réalisée selon un calendrier convenu entre les parties.</p><h2>Article 3 – Traçabilité</h2><p>Chaque collecte fait l'objet d'un bon de transport signé par les deux parties.</p><p>Prise d'effet : {{date_debut}}</p></div>`,
  },
  {
    code: 'eau_plan_wash',
    name: "Plan de développement eau et assainissement (WASH)",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Document-cadre de planification WASH (Water, Sanitation and Hygiene) pour une commune ou une ONG, conforme aux indicateurs ODD 6.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 47,
    fieldsJson: F([
      { key: 'entite', label: "Entité porteuse du plan", type: 'text', required: true },
      { key: 'zone_couverture', label: "Zone de couverture", type: 'text', required: true },
      { key: 'population_cible', label: "Population cible", type: 'text', required: true },
      { key: 'periode_plan', label: "Période du plan (ex: 2025-2030)", type: 'text', required: true },
      { key: 'date_validation', label: "Date de validation du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT EAU ET ASSAINISSEMENT (WASH)</h1><p>Entité porteuse : <strong>{{entite}}</strong> – Zone : {{zone_couverture}} – Population cible : {{population_cible}}</p><h2>1. Diagnostic WASH</h2><p>Analyse de la situation actuelle de l'accès à l'eau potable, l'assainissement et l'hygiène dans la zone.</p><h2>2. Objectifs stratégiques</h2><p>Alignés sur l'ODD 6 : accès universel à l'eau potable et à l'assainissement d'ici la fin de la période {{periode_plan}}.</p><h2>3. Plan d'actions prioritaires</h2><p>Construction de points d'eau, latrines, sessions d'hygiène et formation des comités de gestion.</p><h2>4. Budget et financement</h2><p>Budget global et sources de financement identifiées (État, bailleurs, communautés).</p><p>Validé le {{date_validation}}</p></div>`,
  },
  {
    code: 'eau_rapport_audit_qualite',
    name: "Rapport d'audit qualité eau et assainissement",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 22000,
    description: "Modèle de rapport d'audit de la qualité de l'eau et des services d'assainissement pour une collectivité, une entreprise ou un projet de développement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 44,
    fieldsJson: F([
      { key: 'auditeur', label: "Cabinet / Auditeur", type: 'text', required: true },
      { key: 'entite_auditee', label: "Entité auditée", type: 'text', required: true },
      { key: 'periode_audit', label: "Période auditée", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'conclusions', label: "Conclusions principales", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'AUDIT QUALITÉ EAU ET ASSAINISSEMENT</h1><p>Auditeur : <strong>{{auditeur}}</strong> – Entité auditée : <strong>{{entite_auditee}}</strong> – Période : {{periode_audit}}</p><h2>1. Méthodologie</h2><p>L'audit a été conduit par prélèvements, analyses laboratoire, visites de terrain et entretiens avec les parties prenantes.</p><h2>2. Résultats</h2><p>Évaluation de la conformité des paramètres physico-chimiques et bactériologiques aux normes nationales et OMS.</p><h2>3. Conclusions</h2><p>{{conclusions}}</p><h2>4. Recommandations</h2><p>Plan d'amélioration à mettre en œuvre dans les 6 mois suivant la réception du rapport.</p><p>Établi le {{date_rapport}}</p></div>`,
  },
  {
    code: 'eau_hydrologie_hydrométrie',
    name: "Accord de service d'hydrologie et hydrométrie",
    category: 'agro_environnement',
    price: 9000,
    priceMax: 25000,
    description: "Accord de prestation pour les études hydrologiques, la pose de stations hydrométriques et le suivi des ressources en eau superficielle.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'client', label: "Client / Commanditaire", type: 'text', required: true },
      { key: 'bureau_etudes', label: "Bureau d'études hydrologique", type: 'text', required: true },
      { key: 'bassin_versant', label: "Bassin versant / cours d'eau", type: 'text', required: true },
      { key: 'duree_mission', label: "Durée de la mission", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de mission", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'HYDROLOGIE ET HYDROMÉTRIE</h1><p>Entre <strong>{{bureau_etudes}}</strong> et <strong>{{client}}</strong>, portant sur des études hydrologiques du bassin versant de <strong>{{bassin_versant}}</strong>.</p><h2>Article 1 – Prestations</h2><p>Pose de stations hydrométriques, mesures de débits, analyse des données pluviométriques et établissement des courbes de tarage.</p><h2>Article 2 – Durée</h2><p>Mission d'une durée de {{duree_mission}} à compter du {{date_debut}}.</p><h2>Article 3 – Livrables</h2><p>Rapport hydrologique, banque de données, et recommandations pour la gestion durable des ressources.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_barrage_irrigation',
    name: "Contrat de service de gestion de barrage d'irrigation",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de délégation de service pour la gestion, l'exploitation et la maintenance d'un barrage d'irrigation au profit d'une communauté agricole.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 42,
    fieldsJson: F([
      { key: 'delegant', label: "Autorité délégante", type: 'text', required: true },
      { key: 'gestionnaire', label: "Gestionnaire délégué", type: 'text', required: true },
      { key: 'nom_barrage', label: "Nom / Identification du barrage", type: 'text', required: true },
      { key: 'superficie_irriguee', label: "Superficie irriguée (ha)", type: 'text', required: true },
      { key: 'date_prise_gestion', label: "Date de prise en gestion", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE GESTION DE BARRAGE D'IRRIGATION</h1><p>La <strong>{{delegant}}</strong> délègue à <strong>{{gestionnaire}}</strong> la gestion du barrage d'irrigation <strong>{{nom_barrage}}</strong>.</p><h2>Article 1 – Périmètre</h2><p>Surface irriguée : {{superficie_irriguee}} hectares desservis par le barrage.</p><h2>Article 2 – Obligations du gestionnaire</h2><p>Exploitation optimale du barrage, distribution équitable de l'eau, entretien des ouvrages et tenue de la comptabilité de l'eau.</p><h2>Article 3 – Redevance hydraulique</h2><p>Les irrigants s'acquittent d'une redevance fixée par arrêté, collectée par le gestionnaire.</p><p>Prise de gestion le {{date_prise_gestion}}</p></div>`,
  },
  {
    code: 'eau_partenariat_onep_commune',
    name: "Accord de partenariat ONEP/SODECI-Commune",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 22000,
    description: "Accord de partenariat entre l'opérateur national de l'eau (SODECI/ONEP) et une commune pour l'extension du réseau d'eau potable en zone périurbaine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 46,
    fieldsJson: F([
      { key: 'operateur_eau', label: "Opérateur eau (SODECI/ONEP)", type: 'text', required: true },
      { key: 'commune', label: "Commune partenaire", type: 'text', required: true },
      { key: 'zone_extension', label: "Zone d'extension du réseau", type: 'text', required: true },
      { key: 'investissement_prevu', label: "Investissement prévu (FCFA)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT OPÉRATEUR EAU – COMMUNE</h1><p>Entre <strong>{{operateur_eau}}</strong> et la Commune de <strong>{{commune}}</strong>, il est établi le présent accord de partenariat.</p><h2>Article 1 – Objet</h2><p>Extension du réseau d'eau potable dans la zone de {{zone_extension}} pour améliorer l'accès à l'eau des populations.</p><h2>Article 2 – Investissements</h2><p>Investissement global prévu : {{investissement_prevu}} FCFA, cofinancé selon la clé de répartition annexée.</p><h2>Article 3 – Engagements</h2><p>L'opérateur prend en charge l'exploitation ; la commune facilite les fonciers et les raccordements sociaux.</p><p>Signé le {{date_accord}}</p></div>`,
  },
  {
    code: 'eau_dessalement',
    name: "Contrat de service de dessalement d'eau de mer",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 35000,
    description: "Contrat de conception, construction et exploitation d'une unité de dessalement d'eau de mer pour zones côtières ou îles en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 35,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur / Constructeur", type: 'text', required: true },
      { key: 'capacite_journaliere', label: "Capacité journalière (m³/jour)", type: 'text', required: true },
      { key: 'localisation', label: "Localisation de l'unité", type: 'text', required: true },
      { key: 'date_mise_service', label: "Date de mise en service prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE DESSALEMENT D'EAU DE MER</h1><p>Entre <strong>{{maitre_ouvrage}}</strong> et <strong>{{operateur}}</strong>, portant sur la réalisation d'une unité de dessalement à <strong>{{localisation}}</strong>.</p><h2>Article 1 – Capacité</h2><p>Capacité de production : {{capacite_journaliere}} m³/jour d'eau potable par osmose inverse.</p><h2>Article 2 – Mise en service</h2><p>La mise en service commerciale est prévue le {{date_mise_service}}.</p><h2>Article 3 – Qualité</h2><p>L'eau produite respectera les normes OMS de potabilité et les exigences nationales.</p><h2>Article 4 – Environnement</h2><p>Un plan de gestion des rejets de saumure sera annexé au présent contrat.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'eau_rapport_wash',
    name: "Rapport WASH (Water Sanitation and Hygiene)",
    category: 'agro_environnement',
    price: 7000,
    priceMax: 20000,
    description: "Modèle de rapport de situation et de performance des services WASH destiné aux ONG, bailleurs de fonds et autorités publiques.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'organisation', label: "Organisation rédactrice", type: 'text', required: true },
      { key: 'zone_couverte', label: "Zone couverte", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'indicateurs_cles', label: "Indicateurs clés atteints", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT WASH – WATER, SANITATION AND HYGIENE</h1><p>Organisation : <strong>{{organisation}}</strong> – Zone : {{zone_couverte}} – Période : {{periode_rapport}}</p><h2>1. Eau potable</h2><p>Taux d'accès à l'eau potable, nombre de points d'eau fonctionnels, qualité mesurée.</p><h2>2. Assainissement</h2><p>Couverture en latrines améliorées, pratiques de défécation à l'air libre (DAL), villages FDAL certifiés.</p><h2>3. Hygiène</h2><p>Taux de lavage des mains, sessions d'éducation à l'hygiène réalisées.</p><h2>4. Indicateurs clés</h2><p>{{indicateurs_cles}}</p><p>Établi le {{date_rapport}} par {{organisation}}</p></div>`,
  },
  {
    code: 'eau_plan_action_rural',
    name: "Plan d'action eau et assainissement rural",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 22000,
    description: "Plan d'action opérationnel pour l'amélioration de l'accès à l'eau et l'assainissement en milieu rural, conforme aux stratégies nationales WASH.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'commune_rurale', label: "Commune / Département rural", type: 'text', required: true },
      { key: 'population_rurale', label: "Population rurale concernée", type: 'text', required: true },
      { key: 'horizon_plan', label: "Horizon du plan (ex: 2025-2030)", type: 'text', required: true },
      { key: 'budget_total', label: "Budget total (FCFA)", type: 'text', required: true },
      { key: 'date_validation', label: "Date de validation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D'ACTION EAU ET ASSAINISSEMENT RURAL</h1><p>Commune : <strong>{{commune_rurale}}</strong> – Population : {{population_rurale}} – Horizon : {{horizon_plan}}</p><h2>1. Diagnostic</h2><p>Analyse de la couverture actuelle, des gaps et des besoins prioritaires en eau et assainissement.</p><h2>2. Axes stratégiques</h2><p>Extension des systèmes d'adduction, réhabilitation des ouvrages existants, renforcement de la gouvernance locale.</p><h2>3. Plan d'investissements</h2><p>Budget total : <strong>{{budget_total}} FCFA</strong> sur la période {{horizon_plan}}, décomposé par composante.</p><h2>4. Suivi-évaluation</h2><p>Indicateurs de résultats, calendrier de revues semestrielles et mécanisme de redevabilité.</p><p>Validé le {{date_validation}}</p></div>`,
  },
  {
    code: 'eau_charte_durable',
    name: "Charte de l'eau durable en Afrique",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 18000,
    description: "Charte d'engagement pour la gestion durable et équitable des ressources en eau en Afrique, destinée aux collectivités, entreprises et organisations.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 43,
    fieldsJson: F([
      { key: 'signataire', label: "Signataire (entité ou personne)", type: 'text', required: true },
      { key: 'pays', label: "Pays", type: 'text', required: true },
      { key: 'secteur', label: "Secteur d'activité", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'engagements_specifiques', label: "Engagements spécifiques", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE L'EAU DURABLE EN AFRIQUE</h1><p><strong>{{signataire}}</strong>, acteur du secteur {{secteur}} au <strong>{{pays}}</strong>, souscrit aux engagements de la présente charte.</p><h2>Principe 1 – Accès universel</h2><p>S'engager à contribuer à l'accès universel à l'eau potable et à l'assainissement conformément à l'ODD 6.</p><h2>Principe 2 – Gestion durable</h2><p>Adopter des pratiques de gestion rationnelle, de préservation des ressources et de réduction des pertes.</p><h2>Principe 3 – Équité</h2><p>Garantir un accès équitable à l'eau sans discrimination, avec des tarifs sociaux pour les populations vulnérables.</p><h2>Principe 4 – Gouvernance</h2><p>Promouvoir la transparence, la participation communautaire et la redevabilité dans la gestion de l'eau.</p><h2>Engagements spécifiques</h2><p>{{engagements_specifiques}}</p><p>Signé le {{date_signature}} par {{signataire}}</p></div>`,
  },

  // ─── 25 TEMPLATES URBANISME / AMÉNAGEMENT DU TERRITOIRE ──────────────────
  {
    code: 'amen_plan_urbanisme_directeur',
    name: "Plan d'urbanisme directeur (PUD)",
    category: 'btp_construction',
    price: 12000,
    priceMax: 35000,
    description: "Document-cadre du Plan d'Urbanisme Directeur pour une commune ivoirienne, conforme au Code de l'Urbanisme et aux orientations nationales d'aménagement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'commune', label: "Commune concernée", type: 'text', required: true },
      { key: 'bureau_etudes', label: "Bureau d'études urbanistique", type: 'text', required: true },
      { key: 'horizon_plan', label: "Horizon du PUD (ex: 2035)", type: 'text', required: true },
      { key: 'population_projetee', label: "Population projetée à l'horizon", type: 'text', required: true },
      { key: 'date_approbation', label: "Date d'approbation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D'URBANISME DIRECTEUR (PUD) – {{commune}}</h1><p>Établi par <strong>{{bureau_etudes}}</strong> – Horizon : {{horizon_plan}} – Population projetée : {{population_projetee}}</p><h2>1. Diagnostic territorial</h2><p>Analyse de la situation démographique, foncière, des équipements et des infrastructures existantes.</p><h2>2. Orientations d'aménagement</h2><p>Zonage du territoire : zones résidentielles, commerciales, industrielles, espaces verts et équipements publics.</p><h2>3. Règlement d'urbanisme</h2><p>Règles de constructibilité, hauteurs, reculs, coefficients d'occupation des sols (COS) par zone.</p><h2>4. Programme d'investissements prioritaires</h2><p>Infrastructure routière, réseaux divers, équipements collectifs planifiés sur la période.</p><p>Approuvé le {{date_approbation}}</p></div>`,
  },
  {
    code: 'amen_zone_activite_zac',
    name: "Plan d'aménagement de zone d'activité (ZAC)",
    category: 'btp_construction',
    price: 10000,
    priceMax: 28000,
    description: "Plan d'aménagement d'une Zone d'Aménagement Concerté (ZAC) industrielle ou commerciale, conforme à la législation foncière OHADA et ivoirienne.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'promoteur', label: "Promoteur / Aménageur", type: 'text', required: true },
      { key: 'nom_zac', label: "Nom de la ZAC", type: 'text', required: true },
      { key: 'superficie', label: "Superficie totale (ha)", type: 'text', required: true },
      { key: 'localisation', label: "Localisation / Commune", type: 'text', required: true },
      { key: 'date_creation', label: "Date de création de la ZAC", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D'AMÉNAGEMENT – ZONE D'ACTIVITÉ (ZAC) {{nom_zac}}</h1><p>Promoteur : <strong>{{promoteur}}</strong> – Superficie : {{superficie}} ha – Localisation : {{localisation}}</p><h2>1. Programme prévisionnel</h2><p>Répartition des lots : industriels, tertiaires, services, voiries et espaces verts.</p><h2>2. Équipements</h2><p>Réseaux eau, électricité, assainissement, télécoms et voirie interne à la charge du promoteur.</p><h2>3. Cahier des charges</h2><p>Conditions de cession des lots, obligations architecturales et délais de construction imposés aux acquéreurs.</p><h2>4. Gestion de la ZAC</h2><p>Association syndicale de gestion constituée entre les entreprises installées.</p><p>Créé le {{date_creation}}</p></div>`,
  },
  {
    code: 'amen_amenagement_quartier',
    name: "Contrat de service d'aménagement de quartier",
    category: 'btp_construction',
    price: 8000,
    priceMax: 22000,
    description: "Contrat de maîtrise d'œuvre pour l'aménagement et la viabilisation d'un nouveau quartier résidentiel ou mixte dans une agglomération africaine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'maitre_oeuvre', label: "Maître d'œuvre", type: 'text', required: true },
      { key: 'nom_quartier', label: "Nom du quartier", type: 'text', required: true },
      { key: 'nombre_lots', label: "Nombre de lots prévus", type: 'text', required: true },
      { key: 'date_debut_travaux', label: "Date de début des travaux", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'AMÉNAGEMENT DE QUARTIER – {{nom_quartier}}</h1><p>Entre <strong>{{maitre_ouvrage}}</strong> et <strong>{{maitre_oeuvre}}</strong>, portant sur l'aménagement du quartier <strong>{{nom_quartier}}</strong>.</p><h2>Article 1 – Programme</h2><p>Viabilisation de {{nombre_lots}} lots résidentiels incluant voirie, réseaux et espaces collectifs.</p><h2>Article 2 – Démarrage</h2><p>Les travaux débutent le {{date_debut_travaux}} selon le planning joint en annexe.</p><h2>Article 3 – Normes</h2><p>Travaux réalisés conformément aux normes techniques nationales et aux prescriptions du plan de lotissement approuvé.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'amen_rehabilitation_bidonville',
    name: "Accord de réhabilitation de bidonville (quartier précaire)",
    category: 'btp_construction',
    price: 10000,
    priceMax: 30000,
    description: "Accord de restructuration et de réhabilitation d'un quartier précaire intégrant relogement, viabilisation et accompagnement social des populations.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité / État", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur de réhabilitation", type: 'text', required: true },
      { key: 'nom_quartier', label: "Nom du quartier précaire", type: 'text', required: true },
      { key: 'nombre_menages', label: "Nombre de ménages concernés", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de l'opération", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉHABILITATION DE QUARTIER PRÉCAIRE – {{nom_quartier}}</h1><p>Entre la <strong>{{collectivite}}</strong> et <strong>{{operateur}}</strong>, le présent accord porte sur la restructuration de <strong>{{nom_quartier}}</strong>.</p><h2>Article 1 – Population</h2><p>{{nombre_menages}} ménages sont concernés par l'opération et bénéficieront d'un accompagnement social.</p><h2>Article 2 – Composantes</h2><p>Régularisation foncière, viabilisation en réseaux, construction de logements de relogement transitoire.</p><h2>Article 3 – Participation communautaire</h2><p>Les habitants sont associés aux décisions d'aménagement via un comité de quartier représentatif.</p><p>Lancement le {{date_debut}}</p></div>`,
  },
  {
    code: 'amen_plan_deplacement_urbain',
    name: "Plan de déplacement urbain (PDU)",
    category: 'btp_construction',
    price: 12000,
    priceMax: 35000,
    description: "Document de planification stratégique des déplacements urbains pour une agglomération africaine : transports collectifs, mobilité douce, stationnement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 42,
    fieldsJson: F([
      { key: 'agglomeration', label: "Agglomération concernée", type: 'text', required: true },
      { key: 'autorite_organisatrice', label: "Autorité organisatrice des transports", type: 'text', required: true },
      { key: 'horizon_pdu', label: "Horizon du PDU", type: 'text', required: true },
      { key: 'date_approbation', label: "Date d'approbation", type: 'date', required: true },
      { key: 'objectifs_mobilite', label: "Objectifs de mobilité", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉPLACEMENT URBAIN (PDU) – {{agglomeration}}</h1><p>Autorité organisatrice : <strong>{{autorite_organisatrice}}</strong> – Horizon : {{horizon_pdu}}</p><h2>1. Diagnostic des déplacements</h2><p>Enquête ménages-déplacements, volumes de trafic, parts modales, points noirs de congestion.</p><h2>2. Objectifs</h2><p>{{objectifs_mobilite}}</p><h2>3. Plan d'actions</h2><p>Développement des transports collectifs, infrastructures cyclables et piétonnes, régulation du stationnement.</p><h2>4. Financement</h2><p>Sources de financement identifiées : budget de l'État, collectivités, PTF.</p><p>Approuvé le {{date_approbation}}</p></div>`,
  },
  {
    code: 'amen_contrat_transport_sotra',
    name: "Contrat de service de transport urbain (SOTRA modèle)",
    category: 'btp_construction',
    price: 8000,
    priceMax: 22000,
    description: "Modèle de contrat de service public de transport urbain de personnes, inspiré de la convention SOTRA d'Abidjan, applicable aux agglomérations africaines.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'autorite', label: "Autorité organisatrice", type: 'text', required: true },
      { key: 'operateur_transport', label: "Opérateur de transport", type: 'text', required: true },
      { key: 'reseau_lignes', label: "Réseau / Lignes concernées", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (années)", type: 'text', required: true },
      { key: 'date_prise_effet', label: "Date de prise d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE TRANSPORT URBAIN</h1><p>Entre <strong>{{autorite}}</strong> et <strong>{{operateur_transport}}</strong>, portant sur l'exploitation du réseau de transport urbain.</p><h2>Article 1 – Réseau</h2><p>L'opérateur exploite les lignes suivantes : {{reseau_lignes}} pour une durée de {{duree_contrat}} ans.</p><h2>Article 2 – Obligations de service public</h2><p>Fréquences minimales, accessibilité PMR, tarifs sociaux et couverture géographique des quartiers défavorisés.</p><h2>Article 3 – Compensation</h2><p>L'autorité verse une compensation de service public calculée sur les charges nettes d'exploitation.</p><p>Prise d'effet : {{date_prise_effet}}</p></div>`,
  },
  {
    code: 'amen_accord_gbaka',
    name: "Accord de service de taxi-bus (gbaka contractuel)",
    category: 'btp_construction',
    price: 4000,
    priceMax: 12000,
    description: "Accord contractuel entre une coopérative de gbakas (minibus) et l'autorité de transport pour l'encadrement du transport artisanal urbain en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'cooperative', label: "Coopérative / Syndicat de gbakas", type: 'text', required: true },
      { key: 'autorite', label: "Autorité de transport / Mairie", type: 'text', required: true },
      { key: 'ligne_desservie', label: "Ligne / Itinéraire desservi", type: 'text', required: true },
      { key: 'nombre_vehicules', label: "Nombre de véhicules", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TAXI-BUS (GBAKA)</h1><p>Entre la <strong>{{cooperative}}</strong> et <strong>{{autorite}}</strong>, le présent accord encadre l'exploitation des gbakas sur la ligne {{ligne_desservie}}.</p><h2>Article 1 – Parc autorisé</h2><p>{{nombre_vehicules}} véhicules de la coopérative sont autorisés à opérer sur cet itinéraire.</p><h2>Article 2 – Conditions d'exploitation</h2><p>Respect des arrêts désignés, tarifs en vigueur, état mécanique des véhicules et comportement des conducteurs.</p><h2>Article 3 – Sanctions</h2><p>Tout manquement grave peut entraîner le retrait de l'autorisation d'exploitation.</p><p>Signé le {{date_accord}}</p></div>`,
  },
  {
    code: 'amen_plan_mobilite_durable',
    name: "Plan de mobilité durable",
    category: 'btp_construction',
    price: 9000,
    priceMax: 25000,
    description: "Plan de mobilité urbaine durable intégrant transports bas-carbone, véhicules électriques et infrastructure cyclable pour villes africaines en croissance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'ville', label: "Ville / Agglomération", type: 'text', required: true },
      { key: 'porteur_plan', label: "Porteur du plan", type: 'text', required: true },
      { key: 'periode', label: "Période du plan", type: 'text', required: true },
      { key: 'objectif_reduction_co2', label: "Objectif de réduction CO2 (%)", type: 'text', required: true },
      { key: 'date_lancement', label: "Date de lancement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE MOBILITÉ DURABLE – {{ville}}</h1><p>Porteur : <strong>{{porteur_plan}}</strong> – Période : {{periode}} – Objectif CO2 : -{{objectif_reduction_co2}}%</p><h2>1. État des lieux</h2><p>Cartographie des modes de transport, émissions GES du secteur transport, besoins de mobilité.</p><h2>2. Axes d'intervention</h2><p>Électrification du parc de transports collectifs, développement du vélo et de la marche, covoiturage organisé.</p><h2>3. Investissements</h2><p>Bornes de recharge, pistes cyclables, zones piétonnes et parcs-relais en périphérie.</p><p>Lancé le {{date_lancement}}</p></div>`,
  },
  {
    code: 'amen_accord_parking_public',
    name: "Accord de service de parking public",
    category: 'btp_construction',
    price: 5000,
    priceMax: 14000,
    description: "Accord de concession ou de gestion d'un parking public municipal entre une collectivité locale et un opérateur privé en zone urbaine africaine.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité / Mairie", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur de parking", type: 'text', required: true },
      { key: 'nom_parking', label: "Nom / Localisation du parking", type: 'text', required: true },
      { key: 'capacite', label: "Capacité (nombre de places)", type: 'text', required: true },
      { key: 'duree_concession', label: "Durée de la concession", type: 'text', required: true },
      { key: 'date_prise_service', label: "Date de prise en service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PARKING PUBLIC – {{nom_parking}}</h1><p>Entre la <strong>{{collectivite}}</strong> et <strong>{{operateur}}</strong>, portant sur la gestion du parking {{nom_parking}}.</p><h2>Article 1 – Capacité et durée</h2><p>Parking de {{capacite}} places concédé pour {{duree_concession}} à compter du {{date_prise_service}}.</p><h2>Article 2 – Tarification</h2><p>Les tarifs sont fixés en accord avec la collectivité et affichés à l'entrée du parking.</p><h2>Article 3 – Redevance</h2><p>L'opérateur verse à la collectivité une redevance mensuelle selon la formule convenue en annexe.</p><p>Signatures : _______________</p></div>`,
  },
  {
    code: 'amen_eclairage_public',
    name: "Contrat de service d'éclairage public",
    category: 'btp_construction',
    price: 7000,
    priceMax: 20000,
    description: "Contrat de concession ou de maintenance du réseau d'éclairage public entre une mairie et un opérateur technique, incluant transition vers LED.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie / Collectivité", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire d'éclairage", type: 'text', required: true },
      { key: 'nombre_points_lumineux', label: "Nombre de points lumineux", type: 'text', required: true },
      { key: 'type_technologie', label: "Technologie (LED/solaire/mixte)", type: 'text', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D'ÉCLAIRAGE PUBLIC</h1><p>Entre la <strong>{{mairie}}</strong> et <strong>{{prestataire}}</strong>, portant sur la gestion de l'éclairage public.</p><h2>Article 1 – Périmètre</h2><p>{{nombre_points_lumineux}} points lumineux de technologie {{type_technologie}} sur le territoire communal.</p><h2>Article 2 – Obligations</h2><p>Le prestataire assure l'allumage automatique au coucher du soleil, la maintenance préventive et corrective sous 48h.</p><h2>Article 3 – Performance</h2><p>Taux de disponibilité garanti : 95% sur l'ensemble du réseau.</p><p>Signé le {{date_contrat}}</p></div>`,
  },
  {
    code: 'amen_signalisation_urbaine',
    name: "Accord de service de signalisation urbaine",
    category: 'btp_construction',
    price: 5000,
    priceMax: 15000,
    description: "Accord de pose, maintenance et renouvellement de la signalisation horizontale et verticale en zone urbaine entre une collectivité et un prestataire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité / Mairie", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire de signalisation", type: 'text', required: true },
      { key: 'lineaire_traite', label: "Linéaire traité (km)", type: 'text', required: true },
      { key: 'type_signalisation', label: "Type (horizontale/verticale/feux)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SIGNALISATION URBAINE</h1><p>Entre la <strong>{{collectivite}}</strong> et <strong>{{prestataire}}</strong>, portant sur la signalisation routière urbaine.</p><h2>Article 1 – Périmètre</h2><p>{{lineaire_traite}} km de voiries concernées – Type : {{type_signalisation}}.</p><h2>Article 2 – Prestations</h2><p>Pose des panneaux, marquage au sol, installation et maintenance des feux tricolores.</p><h2>Article 3 – Conformité</h2><p>Tous les dispositifs respectent les normes CEDEAO et le Code de la route national.</p><p>Début des travaux : {{date_debut}}</p></div>`,
  },
  {
    code: 'amen_entretien_voirie',
    name: "Contrat d'entretien de voirie urbaine",
    category: 'btp_construction',
    price: 6000,
    priceMax: 18000,
    description: "Contrat d'entretien courant et périodique de la voirie communale entre une mairie et une entreprise de travaux publics.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie / Collectivité", type: 'text', required: true },
      { key: 'entreprise_tp', label: "Entreprise de TP", type: 'text', required: true },
      { key: 'lineaire_voirie', label: "Linéaire de voirie (km)", type: 'text', required: true },
      { key: 'budget_annuel', label: "Budget annuel (FCFA)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ENTRETIEN DE VOIRIE URBAINE</h1><p>Entre la <strong>{{mairie}}</strong> et <strong>{{entreprise_tp}}</strong>, portant sur l'entretien de {{lineaire_voirie}} km de voirie communale.</p><h2>Article 1 – Prestations</h2><p>Entretien courant : reprofilage, rebouchage des nids-de-poule, curage des caniveaux, fauchage des accotements.</p><h2>Article 2 – Budget</h2><p>Budget annuel alloué : <strong>{{budget_annuel}} FCFA</strong>, versé en tranches trimestrielles.</p><h2>Article 3 – Contrôle</h2><p>La mairie dispose d'un droit de contrôle permanent et peut demander des états d'avancement mensuels.</p><p>Prise d'effet : {{date_debut}}</p></div>`,
  },
  {
    code: 'amen_gestion_cimetiere',
    name: "Accord de service de gestion de cimetière municipal",
    category: 'btp_construction',
    price: 5000,
    priceMax: 14000,
    description: "Accord de délégation de la gestion, de l'entretien et de l'aménagement d'un cimetière municipal entre une mairie et un opérateur funéraire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur funéraire / gestionnaire", type: 'text', required: true },
      { key: 'nom_cimetiere', label: "Nom du cimetière", type: 'text', required: true },
      { key: 'superficie', label: "Superficie (ha)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DE CIMETIÈRE MUNICIPAL – {{nom_cimetiere}}</h1><p>La <strong>{{mairie}}</strong> délègue à <strong>{{operateur}}</strong> la gestion du cimetière {{nom_cimetiere}} ({{superficie}} ha).</p><h2>Article 1 – Missions déléguées</h2><p>Accueil des familles, attribution des concessions, creusement des fosses, entretien des allées et espaces verts.</p><h2>Article 2 – Registre</h2><p>L'opérateur tient à jour le registre des inhumations et le transmet mensuellement à la mairie.</p><h2>Article 3 – Tarifs</h2><p>Les tarifs des concessions sont fixés par délibération du conseil municipal.</p><p>Signé le {{date_accord}}</p></div>`,
  },
  {
    code: 'amen_marche_municipal',
    name: "Contrat de service de marché public municipal",
    category: 'btp_construction',
    price: 6000,
    priceMax: 18000,
    description: "Contrat de concession pour la gestion, l'exploitation et la maintenance d'un marché public municipal entre une mairie et un gestionnaire délégué.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie concédante", type: 'text', required: true },
      { key: 'gestionnaire', label: "Gestionnaire concessionnaire", type: 'text', required: true },
      { key: 'nom_marche', label: "Nom du marché", type: 'text', required: true },
      { key: 'nombre_stands', label: "Nombre de stands / boutiques", type: 'text', required: true },
      { key: 'date_prise_gestion', label: "Date de prise en gestion", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE MARCHÉ PUBLIC MUNICIPAL – {{nom_marche}}</h1><p>La <strong>{{mairie}}</strong> concède à <strong>{{gestionnaire}}</strong> la gestion du marché <strong>{{nom_marche}}</strong> comprenant {{nombre_stands}} stands.</p><h2>Article 1 – Missions</h2><p>Attribution des emplacements, collecte des droits de place, entretien sanitaire, sécurité et gestion des conflits.</p><h2>Article 2 – Redevance</h2><p>Le gestionnaire verse à la mairie une redevance mensuelle forfaitaire selon le tableau annexé.</p><h2>Article 3 – Hygiène</h2><p>Nettoyage quotidien, collecte des ordures ménagères et contrôle sanitaire des denrées alimentaires.</p><p>Prise de gestion : {{date_prise_gestion}}</p></div>`,
  },
  {
    code: 'amen_jardin_public',
    name: "Accord de service de jardin public",
    category: 'btp_construction',
    price: 4000,
    priceMax: 12000,
    description: "Accord d'entretien et de gestion d'un jardin ou parc public municipal entre une collectivité et un prestataire d'espaces verts.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire espaces verts", type: 'text', required: true },
      { key: 'nom_jardin', label: "Nom du jardin / parc", type: 'text', required: true },
      { key: 'superficie_jardin', label: "Superficie (m²)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE JARDIN PUBLIC – {{nom_jardin}}</h1><p>Entre la <strong>{{collectivite}}</strong> et <strong>{{prestataire}}</strong>, portant sur l'entretien du jardin public <strong>{{nom_jardin}}</strong> ({{superficie_jardin}} m²).</p><h2>Article 1 – Prestations</h2><p>Tonte des pelouses, taille des haies et arbustes, arrosage, désherbage et nettoyage quotidien.</p><h2>Article 2 – Fréquence</h2><p>Interventions hebdomadaires, avec passage quotidien pour le nettoyage des allées.</p><h2>Article 3 – Matériel</h2><p>Le prestataire fournit l'ensemble des équipements et produits nécessaires.</p><p>Début du contrat : {{date_debut}}</p></div>`,
  },
  {
    code: 'amen_fontaine_publique',
    name: "Contrat de service de fontaine publique",
    category: 'btp_construction',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de fourniture d'eau potable via fontaine publique municipale et de gestion du préposé de fontaine dans les quartiers non raccordés.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie", type: 'text', required: true },
      { key: 'gestionnaire_fontaine', label: "Gestionnaire / Préposé de fontaine", type: 'text', required: true },
      { key: 'localisation_fontaine', label: "Localisation de la fontaine", type: 'text', required: true },
      { key: 'tarif_eau', label: "Tarif de l'eau (FCFA/bidon)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE FONTAINE PUBLIQUE</h1><p>La <strong>{{mairie}}</strong> confie à <strong>{{gestionnaire_fontaine}}</strong> la gestion de la fontaine publique sise à <strong>{{localisation_fontaine}}</strong>.</p><h2>Article 1 – Missions</h2><p>Ouverture et fermeture quotidiennes, vente de l'eau au tarif de {{tarif_eau}} FCFA/bidon et entretien de la fontaine.</p><h2>Article 2 – Reversement</h2><p>Le gestionnaire reverse à la mairie 70% des recettes et conserve 30% à titre de rémunération.</p><h2>Article 3 – Comptabilité</h2><p>Un cahier de caisse quotidien est tenu et transmis à la mairie en fin de mois.</p><p>Prise d'effet : {{date_debut}}</p></div>`,
  },
  {
    code: 'amen_collecte_dechets_anasur',
    name: "Accord de service de collecte des déchets ménagers (ANASUR modèle)",
    category: 'btp_construction',
    price: 6000,
    priceMax: 18000,
    description: "Modèle d'accord de service de collecte des ordures ménagères inspiré du cadre ANASUR de Côte d'Ivoire, applicable aux communes africaines.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie / Collectivité", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur de collecte", type: 'text', required: true },
      { key: 'zone_collecte', label: "Zone de collecte", type: 'text', required: true },
      { key: 'frequence_collecte', label: "Fréquence de collecte (fois/semaine)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE COLLECTE DES DÉCHETS MÉNAGERS</h1><p>Entre la <strong>{{mairie}}</strong> et <strong>{{operateur}}</strong>, portant sur la collecte des ordures ménagères dans la zone de {{zone_collecte}}.</p><h2>Article 1 – Service</h2><p>Collecte {{frequence_collecte}} fois par semaine, transport et dépôt des déchets en décharge agréée.</p><h2>Article 2 – Matériel</h2><p>L'opérateur met à disposition les bennes, équipements de protection et uniformes des agents.</p><h2>Article 3 – Paiement</h2><p>La rémunération est calculée sur la base des tonnages collectés, selon le bordereau de prix annexé.</p><p>Début du service : {{date_debut}}</p></div>`,
  },
  {
    code: 'amen_plan_dechets_solides',
    name: "Plan de gestion des déchets solides urbains",
    category: 'btp_construction',
    price: 10000,
    priceMax: 28000,
    description: "Plan stratégique de gestion des déchets solides pour une agglomération africaine, de la collecte au traitement final, intégrant le recyclage et la valorisation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'ville', label: "Ville / Agglomération", type: 'text', required: true },
      { key: 'autorite', label: "Autorité compétente", type: 'text', required: true },
      { key: 'production_dechets', label: "Production de déchets (t/jour)", type: 'text', required: true },
      { key: 'horizon_plan', label: "Horizon du plan", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE GESTION DES DÉCHETS SOLIDES URBAINS – {{ville}}</h1><p>Autorité : <strong>{{autorite}}</strong> – Production actuelle : {{production_dechets}} t/jour – Horizon : {{horizon_plan}}</p><h2>1. Diagnostic</h2><p>Caractérisation des déchets, taux de collecte actuel, identification des points noirs et décharges sauvages.</p><h2>2. Stratégie</h2><p>Hiérarchie : réduction à la source, réutilisation, recyclage, valorisation énergétique, mise en décharge contrôlée.</p><h2>3. Plan d'investissements</h2><p>Centres de tri, compostage, décharge contrôlée et équipements de collecte.</p><p>Adopté le {{date_adoption}}</p></div>`,
  },
  {
    code: 'amen_centre_tri_recyclage',
    name: "Accord de centre de tri et recyclage urbain",
    category: 'btp_construction',
    price: 8000,
    priceMax: 22000,
    description: "Accord de création et d'exploitation d'un centre de tri et de valorisation des déchets urbains recyclables entre une collectivité et un opérateur privé.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 43,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur de recyclage", type: 'text', required: true },
      { key: 'localisation_centre', label: "Localisation du centre", type: 'text', required: true },
      { key: 'capacite_traitement', label: "Capacité de traitement (t/jour)", type: 'text', required: true },
      { key: 'date_ouverture', label: "Date d'ouverture", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CENTRE DE TRI ET RECYCLAGE URBAIN</h1><p>Entre la <strong>{{collectivite}}</strong> et <strong>{{operateur}}</strong>, portant sur l'exploitation d'un centre de tri à <strong>{{localisation_centre}}</strong>.</p><h2>Article 1 – Capacité</h2><p>Capacité de traitement : {{capacite_traitement}} t/jour de déchets recyclables triés.</p><h2>Article 2 – Filières</h2><p>Tri et valorisation des plastiques, papier-carton, métaux, verre et matières organiques (compostage).</p><h2>Article 3 – Emploi local</h2><p>L'opérateur s'engage à recruter en priorité des trieurs et récupérateurs informels de la zone.</p><p>Ouverture prévue le {{date_ouverture}}</p></div>`,
  },
  {
    code: 'amen_decharge_controlee',
    name: "Contrat de service de décharge contrôlée",
    category: 'btp_construction',
    price: 9000,
    priceMax: 25000,
    description: "Contrat de concession pour l'exploitation d'une décharge contrôlée ou d'un centre d'enfouissement technique (CET) entre une autorité publique et un opérateur.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'autorite', label: "Autorité concédante", type: 'text', required: true },
      { key: 'operateur', label: "Opérateur concessionnaire", type: 'text', required: true },
      { key: 'localisation', label: "Localisation de la décharge", type: 'text', required: true },
      { key: 'capacite_annuelle', label: "Capacité annuelle (tonnes)", type: 'text', required: true },
      { key: 'date_prise_exploitation', label: "Date de prise d'exploitation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE DÉCHARGE CONTRÔLÉE</h1><p>Entre <strong>{{autorite}}</strong> et <strong>{{operateur}}</strong>, portant sur l'exploitation de la décharge de <strong>{{localisation}}</strong>.</p><h2>Article 1 – Capacité</h2><p>Capacité d'accueil : {{capacite_annuelle}} tonnes/an de déchets ménagers et assimilés.</p><h2>Article 2 – Exploitation</h2><p>Régalage, compactage et couverture quotidienne des déchets ; drainage des lixiviats ; captage du biogaz.</p><h2>Article 3 – Environnement</h2><p>Plan de gestion environnementale et sociale (PGES) obligatoire, avec surveillance annuelle des eaux souterraines.</p><p>Prise d'exploitation : {{date_prise_exploitation}}</p></div>`,
  },
  {
    code: 'amen_rehabilitation_site_pollue',
    name: "Accord de réhabilitation de site pollué urbain",
    category: 'btp_construction',
    price: 10000,
    priceMax: 30000,
    description: "Accord de dépollution et de réhabilitation d'un site urbain contaminé (ancienne décharge, site industriel abandonné) pour reconversion en espace utile.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 37,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'bureau_dépollution', label: "Bureau / Entreprise de dépollution", type: 'text', required: true },
      { key: 'adresse_site', label: "Adresse du site", type: 'text', required: true },
      { key: 'superficie_site', label: "Superficie du site (ha)", type: 'text', required: true },
      { key: 'date_debut_travaux', label: "Date de début des travaux", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉHABILITATION DE SITE POLLUÉ URBAIN</h1><p>Entre <strong>{{maitre_ouvrage}}</strong> et <strong>{{bureau_dépollution}}</strong>, portant sur la réhabilitation du site sis à <strong>{{adresse_site}}</strong> ({{superficie_site}} ha).</p><h2>Article 1 – Diagnostic</h2><p>Étude de caractérisation des pollutions (sols, eaux souterraines, air) préalable aux travaux de dépollution.</p><h2>Article 2 – Travaux</h2><p>Excavation des terres contaminées, traitement in situ ou hors site, remblaiement et végétalisation.</p><h2>Article 3 – Contrôle post-travaux</h2><p>Surveillance environnementale sur 5 ans après réhabilitation pour vérifier l'efficacité du traitement.</p><p>Début des travaux : {{date_debut_travaux}}</p></div>`,
  },
  {
    code: 'amen_lutte_inondations',
    name: "Plan de lutte contre les inondations urbaines",
    category: 'btp_construction',
    price: 10000,
    priceMax: 28000,
    description: "Plan d'action contre les inondations urbaines intégrant aménagements hydrologiques, bassins de rétention et gestion des eaux pluviales pour villes africaines.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'ville', label: "Ville / Commune", type: 'text', required: true },
      { key: 'autorite', label: "Autorité compétente", type: 'text', required: true },
      { key: 'zones_risque', label: "Zones à risque d'inondation", type: 'textarea', required: true },
      { key: 'budget_plan', label: "Budget du plan (FCFA)", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE LUTTE CONTRE LES INONDATIONS URBAINES – {{ville}}</h1><p>Autorité : <strong>{{autorite}}</strong> – Budget : {{budget_plan}} FCFA</p><h2>1. Cartographie des risques</h2><p>Zones à risque : {{zones_risque}}</p><h2>2. Mesures structurelles</h2><p>Construction de bassins de rétention, reprofilage et curage des drains, renforcement des berges des cours d'eau.</p><h2>3. Mesures non structurelles</h2><p>Système d'alerte précoce, plans d'évacuation, sensibilisation des populations et interdiction de construire en zones inondables.</p><h2>4. Gouvernance</h2><p>Comité de pilotage inter-services coordonné par la mairie avec appui technique de l'État.</p><p>Adopté le {{date_adoption}}</p></div>`,
  },
  {
    code: 'amen_rapport_performance_urbain',
    name: "Rapport de performance services urbains",
    category: 'btp_construction',
    price: 7000,
    priceMax: 20000,
    description: "Rapport annuel de performance des services urbains d'une collectivité (eau, déchets, voirie, transport, éclairage) destiné aux élus et aux bailleurs.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité", type: 'text', required: true },
      { key: 'exercice', label: "Exercice (année)", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'redacteur', label: "Service rédacteur", type: 'text', required: true },
      { key: 'faits_marquants', label: "Faits marquants de l'exercice", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE DES SERVICES URBAINS – {{collectivite}}</h1><p>Exercice {{exercice}} – Établi par : {{redacteur}} – Date : {{date_rapport}}</p><h2>1. Service eau et assainissement</h2><p>Taux de desserte, qualité de l'eau distribuée, continuité du service, incidents majeurs.</p><h2>2. Collecte des déchets</h2><p>Tonnages collectés, taux de couverture, coût par habitant, incidents de service.</p><h2>3. Voirie et mobilité</h2><p>Linéaire entretenu, état du réseau, interventions réalisées, taux de satisfaction usagers.</p><h2>4. Faits marquants</h2><p>{{faits_marquants}}</p><p>Établi le {{date_rapport}}</p></div>`,
  },
  {
    code: 'amen_smart_city',
    name: "Accord de smart city africaine",
    category: 'btp_construction',
    price: 12000,
    priceMax: 35000,
    description: "Accord-cadre pour le déploiement d'une solution de ville intelligente (smart city) dans une agglomération africaine : gestion numérique des services urbains.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 38,
    fieldsJson: F([
      { key: 'ville', label: "Ville / Collectivité", type: 'text', required: true },
      { key: 'fournisseur_tech', label: "Fournisseur de solutions technologiques", type: 'text', required: true },
      { key: 'services_couverts', label: "Services couverts (éclairage/trafic/déchets...)", type: 'textarea', required: true },
      { key: 'investissement', label: "Investissement total (FCFA)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SMART CITY AFRICAINE – {{ville}}</h1><p>Entre la <strong>{{ville}}</strong> et <strong>{{fournisseur_tech}}</strong>, portant sur le déploiement de solutions de ville intelligente.</p><h2>Article 1 – Services couverts</h2><p>{{services_couverts}}</p><h2>Article 2 – Investissement</h2><p>Investissement total : <strong>{{investissement}} FCFA</strong> incluant matériel, logiciels et formation.</p><h2>Article 3 – Données et souveraineté</h2><p>Les données collectées restent la propriété de la ville ; hébergement sur serveurs locaux ou souverains.</p><h2>Article 4 – Formation</h2><p>Le fournisseur assure la formation des agents municipaux à l'exploitation de la plateforme.</p><p>Signé le {{date_accord}}</p></div>`,
  },
  {
    code: 'amen_charte_ville_durable',
    name: "Charte de la ville durable africaine",
    category: 'btp_construction',
    price: 6000,
    priceMax: 18000,
    description: "Charte d'engagement pour le développement urbain durable, inclusif et résilient en Afrique, destinée aux collectivités locales et partenaires du développement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 42,
    fieldsJson: F([
      { key: 'ville_signataire', label: "Ville signataire", type: 'text', required: true },
      { key: 'representant', label: "Représentant légal (Maire)", type: 'text', required: true },
      { key: 'pays', label: "Pays", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'engagements_locaux', label: "Engagements locaux spécifiques", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE LA VILLE DURABLE AFRICAINE</h1><p>La ville de <strong>{{ville_signataire}}</strong> ({{pays}}), représentée par <strong>{{representant}}</strong>, souscrit aux engagements de la présente charte.</p><h2>Axe 1 – Aménagement durable</h2><p>Planifier l'urbanisation en préservant les espaces naturels, en intégrant les risques climatiques et en favorisant la mixité sociale.</p><h2>Axe 2 – Services urbains de qualité</h2><p>Garantir l'accès universel à l'eau, l'assainissement, les transports et la gestion des déchets.</h2><h2>Axe 3 – Gouvernance participative</h2><p>Associer les citoyens aux décisions d'urbanisme et rendre compte publiquement de l'utilisation des ressources.</p><h2>Axe 4 – Résilience climatique</h2><p>Intégrer l'adaptation au changement climatique dans tous les projets d'aménagement urbain.</p><h2>Engagements locaux</h2><p>{{engagements_locaux}}</p><p>Signé le {{date_signature}} par {{representant}}</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 49a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
