import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ── MARCHÉS PUBLICS (25) ──────────────────────────────────────────────────
  {
    code: 'mp_dao_travaux', name: "Dossier d'Appel d'Offres (DAO) Travaux", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "DAO complet pour la passation d'un marché public de travaux selon le Code des Marchés Publics de Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 88,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'text', required: true },
      { key: 'numero_dao', label: "Numéro du DAO", type: 'text', required: true },
      { key: 'date_limite_depot', label: "Date limite de dépôt des offres", type: 'date', required: true },
      { key: 'montant_caution', label: "Montant de la caution de soumission (FCFA)", type: 'text', required: true },
      { key: 'description_travaux', label: "Description des travaux", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER D'APPEL D'OFFRES — TRAVAUX</h1><h2>{{autorite_contractante}}</h2><p><strong>Numéro DAO :</strong> {{numero_dao}}</p><p><strong>Objet :</strong> {{objet_marche}}</p><p><strong>Date limite de dépôt :</strong> {{date_limite_depot}}</p><p><strong>Caution de soumission :</strong> {{montant_caution}} FCFA</p><h3>Description des travaux</h3><p>{{description_travaux}}</p><p>Conformément au Code des Marchés Publics de Côte d'Ivoire et aux directives de la DGBF.</p></div>`,
  },
  {
    code: 'mp_dao_fournitures', name: "Dossier d'Appel d'Offres (DAO) Fournitures", category: 'juridique_admin',
    price: 12000, priceMax: 36000, description: "DAO pour l'acquisition de fournitures dans le cadre de la commande publique en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 82,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'objet_fournitures', label: "Nature des fournitures", type: 'text', required: true },
      { key: 'numero_dao', label: "Numéro du DAO", type: 'text', required: true },
      { key: 'date_limite_depot', label: "Date limite de dépôt", type: 'date', required: true },
      { key: 'specifications_techniques', label: "Spécifications techniques", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER D'APPEL D'OFFRES — FOURNITURES</h1><h2>{{autorite_contractante}}</h2><p><strong>Numéro DAO :</strong> {{numero_dao}}</p><p><strong>Objet :</strong> {{objet_fournitures}}</p><p><strong>Date limite de dépôt :</strong> {{date_limite_depot}}</p><h3>Spécifications techniques</h3><p>{{specifications_techniques}}</p></div>`,
  },
  {
    code: 'mp_dao_services', name: "Dossier d'Appel d'Offres (DAO) Services", category: 'juridique_admin',
    price: 12000, priceMax: 36000, description: "DAO pour la passation d'un marché public de prestations intellectuelles ou de services courants.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 79,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'objet_services', label: "Nature des services", type: 'text', required: true },
      { key: 'numero_dao', label: "Numéro du DAO", type: 'text', required: true },
      { key: 'date_limite_depot', label: "Date limite de dépôt", type: 'date', required: true },
      { key: 'termes_reference', label: "Termes de référence", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER D'APPEL D'OFFRES — SERVICES</h1><h2>{{autorite_contractante}}</h2><p><strong>Numéro DAO :</strong> {{numero_dao}}</p><p><strong>Objet :</strong> {{objet_services}}</p><p><strong>Date limite de dépôt :</strong> {{date_limite_depot}}</p><h3>Termes de référence</h3><p>{{termes_reference}}</p></div>`,
  },
  {
    code: 'mp_dcr', name: "Dossier de Consultation Restreinte (DCR)", category: 'juridique_admin',
    price: 10000, priceMax: 30000, description: "Dossier de consultation restreinte pour marchés de gré à gré ou appel d'offres restreint selon le CMP-CI.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 74,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'objet_consultation', label: "Objet de la consultation", type: 'text', required: true },
      { key: 'liste_fournisseurs', label: "Liste des fournisseurs consultés", type: 'textarea', required: true },
      { key: 'date_remise_offres', label: "Date de remise des offres", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER DE CONSULTATION RESTREINTE</h1><h2>{{autorite_contractante}}</h2><p><strong>Objet :</strong> {{objet_consultation}}</p><p><strong>Date de remise des offres :</strong> {{date_remise_offres}}</p><h3>Fournisseurs consultés</h3><p>{{liste_fournisseurs}}</p></div>`,
  },
  {
    code: 'mp_offre_technique', name: "Offre technique de soumissionnaire", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Modèle d'offre technique pour répondre à un appel d'offres public en Côte d'Ivoire (travaux, fournitures ou services).",
    templateType: 'pdf', classe: 'A', active: true, popularity: 85,
    fieldsJson: F([
      { key: 'nom_soumissionnaire', label: "Nom / Raison sociale du soumissionnaire", type: 'text', required: true },
      { key: 'numero_dao_ref', label: "Référence du DAO", type: 'text', required: true },
      { key: 'methodologie', label: "Méthodologie et approche technique", type: 'textarea', required: true },
      { key: 'planning_execution', label: "Planning d'exécution", type: 'textarea', required: true },
      { key: 'date_soumission', label: "Date de soumission", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>OFFRE TECHNIQUE</h1><p><strong>Soumissionnaire :</strong> {{nom_soumissionnaire}}</p><p><strong>Référence DAO :</strong> {{numero_dao_ref}}</p><p><strong>Date :</strong> {{date_soumission}}</p><h3>Méthodologie</h3><p>{{methodologie}}</p><h3>Planning d'exécution</h3><p>{{planning_execution}}</p></div>`,
  },
  {
    code: 'mp_offre_financiere', name: "Offre financière de soumissionnaire", category: 'juridique_admin',
    price: 7000, priceMax: 21000, description: "Modèle d'offre financière (bordereau des prix, sous-détail) pour soumission à un marché public.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 83,
    fieldsJson: F([
      { key: 'nom_soumissionnaire', label: "Nom / Raison sociale du soumissionnaire", type: 'text', required: true },
      { key: 'numero_dao_ref', label: "Référence du DAO", type: 'text', required: true },
      { key: 'montant_offre_ht', label: "Montant total de l'offre HT (FCFA)", type: 'text', required: true },
      { key: 'montant_offre_ttc', label: "Montant total TTC (FCFA)", type: 'text', required: true },
      { key: 'delai_execution', label: "Délai d'exécution proposé", type: 'text', required: true },
      { key: 'date_validite', label: "Date de validité de l'offre", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>OFFRE FINANCIÈRE</h1><p><strong>Soumissionnaire :</strong> {{nom_soumissionnaire}}</p><p><strong>Référence DAO :</strong> {{numero_dao_ref}}</p><p><strong>Montant HT :</strong> {{montant_offre_ht}} FCFA</p><p><strong>Montant TTC :</strong> {{montant_offre_ttc}} FCFA</p><p><strong>Délai d'exécution :</strong> {{delai_execution}}</p><p><strong>Validité de l'offre jusqu'au :</strong> {{date_validite}}</p></div>`,
  },
  {
    code: 'mp_accord_groupement', name: "Accord de candidature groupement momentané (co-traitance)", category: 'juridique_admin',
    price: 9000, priceMax: 27000, description: "Accord constitutif d'un groupement momentané d'entreprises (GME) pour soumissionner ensemble à un marché public.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 70,
    fieldsJson: F([
      { key: 'mandataire', label: "Entreprise mandataire du groupement", type: 'text', required: true },
      { key: 'membres_groupement', label: "Membres du groupement (noms et rôles)", type: 'textarea', required: true },
      { key: 'objet_marche', label: "Objet du marché visé", type: 'text', required: true },
      { key: 'repartition_prestations', label: "Répartition des prestations entre membres", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GROUPEMENT MOMENTANÉ D'ENTREPRISES</h1><p><strong>Mandataire :</strong> {{mandataire}}</p><p><strong>Objet du marché :</strong> {{objet_marche}}</p><p><strong>Date :</strong> {{date_accord}}</p><h3>Membres et rôles</h3><p>{{membres_groupement}}</p><h3>Répartition des prestations</h3><p>{{repartition_prestations}}</p></div>`,
  },
  {
    code: 'mp_accord_sous_traitance', name: "Accord de sous-traitance marché public", category: 'juridique_admin',
    price: 9000, priceMax: 27000, description: "Convention de sous-traitance pour l'exécution partielle d'un marché public, soumise à agrément de l'autorité contractante.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 72,
    fieldsJson: F([
      { key: 'entreprise_titulaire', label: "Entreprise titulaire du marché", type: 'text', required: true },
      { key: 'sous_traitant', label: "Sous-traitant", type: 'text', required: true },
      { key: 'prestations_sous_traitees', label: "Prestations sous-traitées", type: 'textarea', required: true },
      { key: 'montant_sous_traitance', label: "Montant de la sous-traitance (FCFA)", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SOUS-TRAITANCE — MARCHÉ PUBLIC</h1><p><strong>Titulaire :</strong> {{entreprise_titulaire}}</p><p><strong>Sous-traitant :</strong> {{sous_traitant}}</p><p><strong>Montant :</strong> {{montant_sous_traitance}} FCFA</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Prestations sous-traitées</h3><p>{{prestations_sous_traitees}}</p></div>`,
  },
  {
    code: 'mp_contrat_travaux_bnetd', name: "Contrat de marché public de travaux (BNETD)", category: 'juridique_admin',
    price: 20000, priceMax: 60000, description: "Contrat-type de marché public de travaux élaboré selon les normes BNETD et le Code des Marchés Publics de Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 90,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'titulaire', label: "Entreprise titulaire", type: 'text', required: true },
      { key: 'objet_travaux', label: "Objet des travaux", type: 'textarea', required: true },
      { key: 'montant_marche', label: "Montant du marché (FCFA TTC)", type: 'text', required: true },
      { key: 'delai_execution', label: "Délai d'exécution (jours)", type: 'text', required: true },
      { key: 'date_notification', label: "Date de notification du marché", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARCHÉ PUBLIC DE TRAVAUX</h1><p>Entre : <strong>{{autorite_contractante}}</strong> (Autorité contractante) et <strong>{{titulaire}}</strong> (Titulaire).</p><p><strong>Objet :</strong> {{objet_travaux}}</p><p><strong>Montant TTC :</strong> {{montant_marche}} FCFA</p><p><strong>Délai d'exécution :</strong> {{delai_execution}} jours</p><p><strong>Date de notification :</strong> {{date_notification}}</p><p>Établi conformément au Code des Marchés Publics de Côte d'Ivoire et aux cahiers des charges BNETD.</p></div>`,
  },
  {
    code: 'mp_contrat_fournitures', name: "Contrat de marché public de fournitures", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "Contrat de marché public pour l'acquisition de biens et fournitures conformément au CMP-CI.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 78,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'fournisseur', label: "Fournisseur titulaire", type: 'text', required: true },
      { key: 'designation_fournitures', label: "Désignation des fournitures", type: 'textarea', required: true },
      { key: 'montant_marche', label: "Montant du marché (FCFA TTC)", type: 'text', required: true },
      { key: 'delai_livraison', label: "Délai de livraison", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARCHÉ PUBLIC DE FOURNITURES</h1><p>Entre : <strong>{{autorite_contractante}}</strong> et <strong>{{fournisseur}}</strong>.</p><p><strong>Fournitures :</strong> {{designation_fournitures}}</p><p><strong>Montant TTC :</strong> {{montant_marche}} FCFA</p><p><strong>Délai de livraison :</strong> {{delai_livraison}}</p></div>`,
  },
  {
    code: 'mp_contrat_services', name: "Contrat de marché public de services", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "Contrat de prestation de services (études, conseil, assistance technique) pour marchés publics en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 76,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire titulaire", type: 'text', required: true },
      { key: 'objet_services', label: "Objet des services", type: 'textarea', required: true },
      { key: 'montant_marche', label: "Montant du marché (FCFA HT)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat", type: 'text', required: true },
      { key: 'date_demarrage', label: "Date de démarrage", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARCHÉ PUBLIC DE SERVICES</h1><p>Entre : <strong>{{autorite_contractante}}</strong> et <strong>{{prestataire}}</strong>.</p><p><strong>Objet :</strong> {{objet_services}}</p><p><strong>Montant HT :</strong> {{montant_marche}} FCFA</p><p><strong>Durée :</strong> {{duree_contrat}}</p><p><strong>Démarrage :</strong> {{date_demarrage}}</p></div>`,
  },
  {
    code: 'mp_bon_commande', name: "Contrat de marché sur commandes (bon de commande)", category: 'juridique_admin',
    price: 6000, priceMax: 18000, description: "Bon de commande pour marchés à commandes ou marchés de faible montant selon le CMP-CI.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 86,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Service demandeur", type: 'text', required: true },
      { key: 'fournisseur', label: "Fournisseur", type: 'text', required: true },
      { key: 'designation_commande', label: "Désignation de la commande", type: 'textarea', required: true },
      { key: 'montant_commande', label: "Montant de la commande (FCFA TTC)", type: 'text', required: true },
      { key: 'date_commande', label: "Date du bon de commande", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>BON DE COMMANDE</h1><p><strong>Service demandeur :</strong> {{autorite_contractante}}</p><p><strong>Fournisseur :</strong> {{fournisseur}}</p><p><strong>Date :</strong> {{date_commande}}</p><h3>Commande</h3><p>{{designation_commande}}</p><p><strong>Montant TTC :</strong> {{montant_commande}} FCFA</p></div>`,
  },
  {
    code: 'mp_avenant', name: "Avenant au marché public", category: 'juridique_admin',
    price: 10000, priceMax: 30000, description: "Avenant modificatif à un marché public (modification du montant, délai ou périmètre) conformément au CMP-CI.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 80,
    fieldsJson: F([
      { key: 'numero_marche', label: "Numéro et référence du marché initial", type: 'text', required: true },
      { key: 'numero_avenant', label: "Numéro de l'avenant", type: 'text', required: true },
      { key: 'objet_avenant', label: "Objet de l'avenant", type: 'textarea', required: true },
      { key: 'nouveau_montant', label: "Nouveau montant du marché (FCFA TTC)", type: 'text', required: true },
      { key: 'date_avenant', label: "Date de l'avenant", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>AVENANT N° {{numero_avenant}} AU MARCHÉ PUBLIC</h1><p><strong>Marché de référence :</strong> {{numero_marche}}</p><p><strong>Date :</strong> {{date_avenant}}</p><h3>Objet de l'avenant</h3><p>{{objet_avenant}}</p><p><strong>Nouveau montant TTC :</strong> {{nouveau_montant}} FCFA</p></div>`,
  },
  {
    code: 'mp_pv_reception_provisoire', name: "Procès-verbal de réception provisoire travaux", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "PV de réception provisoire des travaux établi par la commission de réception conformément aux CCAG travaux CI.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 84,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'titulaire', label: "Entreprise titulaire", type: 'text', required: true },
      { key: 'objet_travaux', label: "Objet des travaux", type: 'text', required: true },
      { key: 'date_reception', label: "Date de réception provisoire", type: 'date', required: true },
      { key: 'reserves', label: "Réserves émises (ou néant)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÈS-VERBAL DE RÉCEPTION PROVISOIRE</h1><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Objet :</strong> {{objet_travaux}}</p><p><strong>Date :</strong> {{date_reception}}</p><h3>Réserves</h3><p>{{reserves}}</p><p>La réception définitive interviendra après levée de toutes les réserves dans le délai contractuel.</p></div>`,
  },
  {
    code: 'mp_pv_reception_definitive', name: "Procès-verbal de réception définitive travaux", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "PV de réception définitive constatant la levée des réserves et libérant la caution de bonne fin.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 81,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'titulaire', label: "Entreprise titulaire", type: 'text', required: true },
      { key: 'objet_travaux', label: "Objet des travaux", type: 'text', required: true },
      { key: 'date_reception_provisoire', label: "Date de réception provisoire", type: 'date', required: true },
      { key: 'date_reception_definitive', label: "Date de réception définitive", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÈS-VERBAL DE RÉCEPTION DÉFINITIVE</h1><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Objet :</strong> {{objet_travaux}}</p><p><strong>Réception provisoire :</strong> {{date_reception_provisoire}}</p><p><strong>Réception définitive :</strong> {{date_reception_definitive}}</p><p>Toutes les réserves ont été levées. La caution de bonne fin est libérée.</p></div>`,
  },
  {
    code: 'mp_caution_soumission', name: "Accord de cautionnement de soumission", category: 'juridique_admin',
    price: 7000, priceMax: 21000, description: "Lettre de cautionnement bancaire de soumission garantissant la validité de l'offre du soumissionnaire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 75,
    fieldsJson: F([
      { key: 'banque_garante', label: "Banque garante", type: 'text', required: true },
      { key: 'soumissionnaire', label: "Soumissionnaire", type: 'text', required: true },
      { key: 'montant_caution', label: "Montant de la caution (FCFA)", type: 'text', required: true },
      { key: 'date_expiration', label: "Date d'expiration de la caution", type: 'date', required: true },
      { key: 'reference_dao', label: "Référence du DAO", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CAUTION DE SOUMISSION</h1><p><strong>Banque garante :</strong> {{banque_garante}}</p><p><strong>Soumissionnaire :</strong> {{soumissionnaire}}</p><p><strong>Référence DAO :</strong> {{reference_dao}}</p><p><strong>Montant garanti :</strong> {{montant_caution}} FCFA</p><p><strong>Valide jusqu'au :</strong> {{date_expiration}}</p><p>La présente caution est irrévocable et payable à première demande.</p></div>`,
  },
  {
    code: 'mp_caution_bonne_fin', name: "Accord de cautionnement de bonne fin", category: 'juridique_admin',
    price: 7000, priceMax: 21000, description: "Caution bancaire de bonne exécution garantissant la bonne fin d'un marché public en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 73,
    fieldsJson: F([
      { key: 'banque_garante', label: "Banque garante", type: 'text', required: true },
      { key: 'titulaire_marche', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'numero_marche', label: "Numéro du marché", type: 'text', required: true },
      { key: 'montant_caution', label: "Montant de la caution (FCFA)", type: 'text', required: true },
      { key: 'date_expiration', label: "Date d'expiration", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CAUTION DE BONNE FIN</h1><p><strong>Banque garante :</strong> {{banque_garante}}</p><p><strong>Titulaire :</strong> {{titulaire_marche}}</p><p><strong>Marché :</strong> {{numero_marche}}</p><p><strong>Montant garanti :</strong> {{montant_caution}} FCFA</p><p><strong>Valide jusqu'au :</strong> {{date_expiration}}</p><p>Garantie de bonne exécution payable à première demande écrite.</p></div>`,
  },
  {
    code: 'mp_caution_restitution_avance', name: "Accord de cautionnement de restitution d'avance", category: 'juridique_admin',
    price: 7000, priceMax: 21000, description: "Caution bancaire garantissant la restitution de l'avance de démarrage accordée au titulaire d'un marché public.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 71,
    fieldsJson: F([
      { key: 'banque_garante', label: "Banque garante", type: 'text', required: true },
      { key: 'titulaire_marche', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'montant_avance', label: "Montant de l'avance (FCFA)", type: 'text', required: true },
      { key: 'date_remboursement', label: "Date limite de remboursement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CAUTION DE RESTITUTION D'AVANCE</h1><p><strong>Banque garante :</strong> {{banque_garante}}</p><p><strong>Titulaire :</strong> {{titulaire_marche}}</p><p><strong>Montant de l'avance :</strong> {{montant_avance}} FCFA</p><p><strong>Remboursement avant le :</strong> {{date_remboursement}}</p><p>La présente garantie couvre intégralement l'avance de démarrage accordée.</p></div>`,
  },
  {
    code: 'mp_retenue_garantie', name: "Accord de retenue de garantie", category: 'juridique_admin',
    price: 6000, priceMax: 18000, description: "Attestation de retenue de garantie sur les décomptes d'un marché public de travaux (5% du montant).",
    templateType: 'pdf', classe: 'A', active: true, popularity: 68,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'titulaire', label: "Entreprise titulaire", type: 'text', required: true },
      { key: 'numero_marche', label: "Numéro du marché", type: 'text', required: true },
      { key: 'montant_retenu', label: "Montant total retenu (FCFA)", type: 'text', required: true },
      { key: 'date_liberation', label: "Date prévue de libération", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RETENUE DE GARANTIE</h1><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Marché :</strong> {{numero_marche}}</p><p><strong>Montant retenu (5%) :</strong> {{montant_retenu}} FCFA</p><p><strong>Libération prévue le :</strong> {{date_liberation}}</p></div>`,
  },
  {
    code: 'mp_reglement_differend_anrmp', name: "Accord de règlement de différend marché public (ANRMP CI)", category: 'juridique_admin',
    price: 12000, priceMax: 36000, description: "Accord de règlement amiable d'un différend relatif à un marché public devant l'ANRMP de Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 66,
    fieldsJson: F([
      { key: 'soumissionnaire_plaignant', label: "Soumissionnaire plaignant", type: 'text', required: true },
      { key: 'autorite_contractante', label: "Autorité contractante mise en cause", type: 'text', required: true },
      { key: 'objet_differend', label: "Objet du différend", type: 'textarea', required: true },
      { key: 'numero_recours', label: "Numéro de recours ANRMP", type: 'text', required: true },
      { key: 'date_saisine', label: "Date de saisine de l'ANRMP", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÈGLEMENT DE DIFFÉREND — ANRMP</h1><p><strong>Plaignant :</strong> {{soumissionnaire_plaignant}}</p><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Numéro de recours :</strong> {{numero_recours}}</p><p><strong>Date de saisine :</strong> {{date_saisine}}</p><h3>Objet du différend</h3><p>{{objet_differend}}</p></div>`,
  },
  {
    code: 'mp_rapport_controle_interne', name: "Rapport de contrôle interne marché public", category: 'juridique_admin',
    price: 10000, priceMax: 30000, description: "Rapport de contrôle interne a priori ou a posteriori sur la passation d'un marché public (IGF, ANRMP).",
    templateType: 'pdf', classe: 'A', active: true, popularity: 64,
    fieldsJson: F([
      { key: 'organe_controle', label: "Organe de contrôle", type: 'text', required: true },
      { key: 'entite_controlee', label: "Entité contrôlée", type: 'text', required: true },
      { key: 'marches_controles', label: "Marchés contrôlés (références)", type: 'textarea', required: true },
      { key: 'constats_irregularites', label: "Constats et irrégularités relevées", type: 'textarea', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE CONTRÔLE INTERNE — MARCHÉS PUBLICS</h1><p><strong>Organe de contrôle :</strong> {{organe_controle}}</p><p><strong>Entité contrôlée :</strong> {{entite_controlee}}</p><p><strong>Date :</strong> {{date_rapport}}</p><h3>Marchés contrôlés</h3><p>{{marches_controles}}</p><h3>Constats et irrégularités</h3><p>{{constats_irregularites}}</p></div>`,
  },
  {
    code: 'mp_plan_passation', name: "Plan de passation des marchés publics", category: 'juridique_admin',
    price: 12000, priceMax: 36000, description: "Plan annuel de passation des marchés publics d'une autorité contractante, soumis à approbation DGBF/ANRMP.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 77,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'exercice_budgetaire', label: "Exercice budgétaire", type: 'text', required: true },
      { key: 'montant_budget_prevu', label: "Montant total du budget prévu (FCFA)", type: 'text', required: true },
      { key: 'liste_marches_prevus', label: "Liste des marchés prévus", type: 'textarea', required: true },
      { key: 'date_approbation', label: "Date d'approbation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE PASSATION DES MARCHÉS PUBLICS</h1><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Exercice :</strong> {{exercice_budgetaire}}</p><p><strong>Budget total prévu :</strong> {{montant_budget_prevu}} FCFA</p><p><strong>Date d'approbation :</strong> {{date_approbation}}</p><h3>Marchés prévus</h3><p>{{liste_marches_prevus}}</p></div>`,
  },
  {
    code: 'mp_accord_dsp', name: "Accord de délégation de service public (DSP)", category: 'juridique_admin',
    price: 20000, priceMax: 60000, description: "Convention de délégation de service public (affermage, régie intéressée) selon le droit OHADA et le CMP-CI.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 69,
    fieldsJson: F([
      { key: 'autorite_delegante', label: "Autorité délégante", type: 'text', required: true },
      { key: 'delégataire', label: "Délégataire", type: 'text', required: true },
      { key: 'service_delegue', label: "Service public délégué", type: 'text', required: true },
      { key: 'duree_delegation', label: "Durée de la délégation", type: 'text', required: true },
      { key: 'obligations_delegataire', label: "Obligations du délégataire", type: 'textarea', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DÉLÉGATION DE SERVICE PUBLIC</h1><p>Entre <strong>{{autorite_delegante}}</strong> (Autorité délégante) et <strong>{{delégataire}}</strong> (Délégataire).</p><p><strong>Service délégué :</strong> {{service_delegue}}</p><p><strong>Durée :</strong> {{duree_delegation}}</p><p><strong>Date :</strong> {{date_contrat}}</p><h3>Obligations du délégataire</h3><p>{{obligations_delegataire}}</p></div>`,
  },
  {
    code: 'mp_accord_concession', name: "Accord de concession de service public (eau, électricité)", category: 'juridique_admin',
    price: 25000, priceMax: 75000, description: "Contrat de concession de service public pour la production et la distribution d'eau potable ou d'électricité en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'autorite_concedante', label: "Autorité concédante (État / collectivité)", type: 'text', required: true },
      { key: 'concessionnaire', label: "Concessionnaire", type: 'text', required: true },
      { key: 'type_service', label: "Type de service (eau / électricité / autre)", type: 'text', required: true },
      { key: 'zone_concession', label: "Zone géographique de la concession", type: 'text', required: true },
      { key: 'duree_concession', label: "Durée de la concession", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONCESSION DE SERVICE PUBLIC</h1><p><strong>Autorité concédante :</strong> {{autorite_concedante}}</p><p><strong>Concessionnaire :</strong> {{concessionnaire}}</p><p><strong>Service :</strong> {{type_service}}</p><p><strong>Zone :</strong> {{zone_concession}}</p><p><strong>Durée :</strong> {{duree_concession}}</p><p><strong>Date :</strong> {{date_signature}}</p></div>`,
  },
  {
    code: 'mp_charte_transparence', name: "Charte de transparence et d'intégrité dans les marchés publics", category: 'juridique_admin',
    price: 6000, priceMax: 18000, description: "Charte d'engagement sur la transparence, l'intégrité et la lutte contre la corruption dans la commande publique (CI).",
    templateType: 'pdf', classe: 'A', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'entite_signataire', label: "Entité signataire", type: 'text', required: true },
      { key: 'representant_legal', label: "Représentant légal", type: 'text', required: true },
      { key: 'engagements_specifiques', label: "Engagements spécifiques de l'entité", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE TRANSPARENCE ET D'INTÉGRITÉ — MARCHÉS PUBLICS</h1><p><strong>Signataire :</strong> {{entite_signataire}}, représenté par <strong>{{representant_legal}}</strong>.</p><p>En signant la présente charte, le signataire s'engage à respecter les principes de transparence, d'équité et de lutte contre la corruption dans toute opération de commande publique.</p><h3>Engagements spécifiques</h3><p>{{engagements_specifiques}}</p><p><strong>Signé le :</strong> {{date_signature}}</p></div>`,
  },

  // ── ADMINISTRATION PUBLIQUE / COLLECTIVITÉS (25) ──────────────────────────
  {
    code: 'adm2_acte_creation_ep', name: "Acte de création d'un établissement public (EP)", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "Décret ou arrêté portant création d'un établissement public (EP) en Côte d'Ivoire, conformément à la loi sur les EP.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 72,
    fieldsJson: F([
      { key: 'denomination_ep', label: "Dénomination de l'établissement public", type: 'text', required: true },
      { key: 'siege_ep', label: "Siège de l'établissement", type: 'text', required: true },
      { key: 'mission_ep', label: "Mission et objet de l'établissement", type: 'textarea', required: true },
      { key: 'autorite_tutelle', label: "Ministère de tutelle", type: 'text', required: true },
      { key: 'date_acte', label: "Date de l'acte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DÉCRET PORTANT CRÉATION D'UN ÉTABLISSEMENT PUBLIC</h1><p><strong>Dénomination :</strong> {{denomination_ep}}</p><p><strong>Siège :</strong> {{siege_ep}}</p><p><strong>Tutelle :</strong> {{autorite_tutelle}}</p><p><strong>Date :</strong> {{date_acte}}</p><h3>Mission</h3><p>{{mission_ep}}</p></div>`,
  },
  {
    code: 'adm2_acte_creation_societe_etat', name: "Acte de création d'une société d'État", category: 'juridique_admin',
    price: 18000, priceMax: 54000, description: "Statuts et acte fondateur d'une société d'État (SE) ou société à participation financière de l'État en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 68,
    fieldsJson: F([
      { key: 'denomination_se', label: "Dénomination de la société", type: 'text', required: true },
      { key: 'capital_social', label: "Capital social (FCFA)", type: 'text', required: true },
      { key: 'objet_social', label: "Objet social", type: 'textarea', required: true },
      { key: 'actionnaire_etat', label: "Part de l'État dans le capital (%)", type: 'text', required: true },
      { key: 'date_creation', label: "Date de création", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE CRÉATION — SOCIÉTÉ D'ÉTAT</h1><p><strong>Dénomination :</strong> {{denomination_se}}</p><p><strong>Capital social :</strong> {{capital_social}} FCFA</p><p><strong>Part de l'État :</strong> {{actionnaire_etat}} %</p><p><strong>Date :</strong> {{date_creation}}</p><h3>Objet social</h3><p>{{objet_social}}</p></div>`,
  },
  {
    code: 'adm2_convention_performance', name: "Accord de convention de performance État-entreprise publique", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "Convention de performance liant l'État et une entreprise publique fixant objectifs, indicateurs et ressources allouées.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'ministere_tutelle', label: "Ministère de tutelle", type: 'text', required: true },
      { key: 'entreprise_publique', label: "Entreprise publique", type: 'text', required: true },
      { key: 'objectifs_performance', label: "Objectifs de performance", type: 'textarea', required: true },
      { key: 'indicateurs_cles', label: "Indicateurs clés de performance (KPI)", type: 'textarea', required: true },
      { key: 'periode_convention', label: "Période de la convention", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PERFORMANCE ÉTAT — ENTREPRISE PUBLIQUE</h1><p><strong>Tutelle :</strong> {{ministere_tutelle}}</p><p><strong>Entreprise :</strong> {{entreprise_publique}}</p><p><strong>Période :</strong> {{periode_convention}}</p><h3>Objectifs de performance</h3><p>{{objectifs_performance}}</p><h3>Indicateurs KPI</h3><p>{{indicateurs_cles}}</p></div>`,
  },
  {
    code: 'adm2_plan_redressement_ep', name: "Accord de plan de redressement entreprise publique", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "Plan de redressement économique et financier d'une entreprise publique en difficulté, approuvé par l'État actionnaire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'entreprise_en_difficulte', label: "Entreprise publique en difficulté", type: 'text', required: true },
      { key: 'diagnostic_situation', label: "Diagnostic de la situation", type: 'textarea', required: true },
      { key: 'mesures_redressement', label: "Mesures de redressement prévues", type: 'textarea', required: true },
      { key: 'apport_etat', label: "Apport de l'État / restructuration financière", type: 'text', required: true },
      { key: 'date_approbation', label: "Date d'approbation du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE REDRESSEMENT — ENTREPRISE PUBLIQUE</h1><p><strong>Entreprise :</strong> {{entreprise_en_difficulte}}</p><p><strong>Apport de l'État :</strong> {{apport_etat}}</p><p><strong>Approuvé le :</strong> {{date_approbation}}</p><h3>Diagnostic</h3><p>{{diagnostic_situation}}</p><h3>Mesures de redressement</h3><p>{{mesures_redressement}}</p></div>`,
  },
  {
    code: 'adm2_accord_privatisation', name: "Accord de privatisation d'entreprise publique", category: 'juridique_admin',
    price: 20000, priceMax: 60000, description: "Accord encadrant le processus de privatisation totale ou partielle d'une entreprise publique ivoirienne.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'entreprise_privatisee', label: "Entreprise à privatiser", type: 'text', required: true },
      { key: 'acquereur', label: "Acquéreur", type: 'text', required: true },
      { key: 'pourcentage_cede', label: "Pourcentage du capital cédé (%)", type: 'text', required: true },
      { key: 'prix_cession', label: "Prix de cession (FCFA)", type: 'text', required: true },
      { key: 'date_transfert', label: "Date de transfert de propriété", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRIVATISATION</h1><p><strong>Entreprise :</strong> {{entreprise_privatisee}}</p><p><strong>Acquéreur :</strong> {{acquereur}}</p><p><strong>Part cédée :</strong> {{pourcentage_cede}} %</p><p><strong>Prix de cession :</strong> {{prix_cession}} FCFA</p><p><strong>Date de transfert :</strong> {{date_transfert}}</p></div>`,
  },
  {
    code: 'adm2_deliberation_conseil_municipal', name: "Délibération du conseil municipal (modèle)", category: 'juridique_admin',
    price: 6000, priceMax: 18000, description: "Modèle de délibération du conseil municipal pour toute décision relevant des compétences du conseil (CI).",
    templateType: 'pdf', classe: 'A', active: true, popularity: 84,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'numero_deliberation', label: "Numéro de la délibération", type: 'text', required: true },
      { key: 'objet_deliberation', label: "Objet de la délibération", type: 'text', required: true },
      { key: 'decision_adoptee', label: "Décision adoptée par le conseil", type: 'textarea', required: true },
      { key: 'date_seance', label: "Date de la séance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DÉLIBÉRATION DU CONSEIL MUNICIPAL</h1><h2>COMMUNE DE {{commune}}</h2><p><strong>Délibération N° :</strong> {{numero_deliberation}}</p><p><strong>Objet :</strong> {{objet_deliberation}}</p><p><strong>Séance du :</strong> {{date_seance}}</p><h3>Le conseil municipal délibère</h3><p>{{decision_adoptee}}</p></div>`,
  },
  {
    code: 'adm2_arrete_municipal', name: "Arrêté municipal", category: 'juridique_admin',
    price: 5000, priceMax: 15000, description: "Arrêté du maire portant réglementation sur toute matière relevant des pouvoirs de police administrative municipale.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 86,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'numero_arrete', label: "Numéro de l'arrêté", type: 'text', required: true },
      { key: 'objet_arrete', label: "Objet de l'arrêté", type: 'text', required: true },
      { key: 'dispositions', label: "Dispositions réglementaires", type: 'textarea', required: true },
      { key: 'date_arrete', label: "Date de l'arrêté", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ARRÊTÉ MUNICIPAL N° {{numero_arrete}}</h1><h2>MAIRIE DE {{commune}}</h2><p><strong>Objet :</strong> {{objet_arrete}}</p><p><strong>Date :</strong> {{date_arrete}}</p><h3>Article 1 et suivants</h3><p>{{dispositions}}</p><p>Le présent arrêté sera affiché et exécuté.</p></div>`,
  },
  {
    code: 'adm2_delegation_competences', name: "Acte de délégation de compétences (État-collectivité)", category: 'juridique_admin',
    price: 10000, priceMax: 30000, description: "Acte par lequel l'État transfère ou délègue des compétences à une collectivité territoriale en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 66,
    fieldsJson: F([
      { key: 'ministere_delegant', label: "Ministère délégant", type: 'text', required: true },
      { key: 'collectivite_beneficiaire', label: "Collectivité bénéficiaire", type: 'text', required: true },
      { key: 'competences_transferees', label: "Compétences transférées", type: 'textarea', required: true },
      { key: 'ressources_allouees', label: "Ressources allouées (financières, humaines)", type: 'textarea', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entrée en vigueur", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE DÉLÉGATION DE COMPÉTENCES</h1><p><strong>Ministère délégant :</strong> {{ministere_delegant}}</p><p><strong>Collectivité bénéficiaire :</strong> {{collectivite_beneficiaire}}</p><p><strong>Entrée en vigueur :</strong> {{date_entree_vigueur}}</p><h3>Compétences transférées</h3><p>{{competences_transferees}}</p><h3>Ressources allouées</h3><p>{{ressources_allouees}}</p></div>`,
  },
  {
    code: 'adm2_convention_intercommunale', name: "Convention de partenariat intercommunal", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Convention de coopération entre plusieurs communes pour la mutualisation de services ou la réalisation d'équipements communs.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 64,
    fieldsJson: F([
      { key: 'commune_chef_file', label: "Commune chef de file", type: 'text', required: true },
      { key: 'communes_partenaires', label: "Communes partenaires", type: 'textarea', required: true },
      { key: 'objet_cooperation', label: "Objet de la coopération", type: 'text', required: true },
      { key: 'contributions_financieres', label: "Contributions financières de chaque commune", type: 'textarea', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PARTENARIAT INTERCOMMUNAL</h1><p><strong>Commune chef de file :</strong> {{commune_chef_file}}</p><p><strong>Communes partenaires :</strong> {{communes_partenaires}}</p><p><strong>Objet :</strong> {{objet_cooperation}}</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Contributions financières</h3><p>{{contributions_financieres}}</p></div>`,
  },
  {
    code: 'adm2_accord_fdl', name: "Accord de financement projet communal (FDL CI)", category: 'juridique_admin',
    price: 10000, priceMax: 30000, description: "Convention de financement entre le Fonds de Développement Local (FDL) et une commune bénéficiaire en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 70,
    fieldsJson: F([
      { key: 'commune_beneficiaire', label: "Commune bénéficiaire", type: 'text', required: true },
      { key: 'projet_finance', label: "Projet à financer", type: 'text', required: true },
      { key: 'montant_fdl', label: "Montant accordé par le FDL (FCFA)", type: 'text', required: true },
      { key: 'contrepartie_commune', label: "Contrepartie de la commune (FCFA)", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FINANCEMENT FDL — PROJET COMMUNAL</h1><p><strong>Commune :</strong> {{commune_beneficiaire}}</p><p><strong>Projet :</strong> {{projet_finance}}</p><p><strong>Subvention FDL :</strong> {{montant_fdl}} FCFA</p><p><strong>Contrepartie commune :</strong> {{contrepartie_commune}} FCFA</p><p><strong>Date :</strong> {{date_convention}}</p></div>`,
  },
  {
    code: 'adm2_accord_maitrise_ouvrage_communale', name: "Accord de service de maîtrise d'ouvrage communale", category: 'juridique_admin',
    price: 10000, priceMax: 30000, description: "Convention de maîtrise d'ouvrage déléguée (MOD) confiée à une agence ou à une commune pour la réalisation d'infrastructures locales.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 67,
    fieldsJson: F([
      { key: 'maitre_ouvrage_delegant', label: "Maître d'ouvrage délégant", type: 'text', required: true },
      { key: 'maitre_ouvrage_delegue', label: "Maître d'ouvrage délégué (MOD)", type: 'text', required: true },
      { key: 'objet_mission', label: "Objet de la mission MOD", type: 'textarea', required: true },
      { key: 'enveloppe_projet', label: "Enveloppe financière du projet (FCFA)", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE MAÎTRISE D'OUVRAGE DÉLÉGUÉE COMMUNALE</h1><p><strong>Maître d'ouvrage délégant :</strong> {{maitre_ouvrage_delegant}}</p><p><strong>MOD :</strong> {{maitre_ouvrage_delegue}}</p><p><strong>Enveloppe :</strong> {{enveloppe_projet}} FCFA</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Objet de la mission</h3><p>{{objet_mission}}</p></div>`,
  },
  {
    code: 'adm2_accord_gestion_deleguee_local', name: "Accord de gestion déléguée service public local", category: 'juridique_admin',
    price: 12000, priceMax: 36000, description: "Convention de gestion déléguée d'un service public local (eau, assainissement, marchés) par un opérateur privé.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([
      { key: 'collectivite_delegante', label: "Collectivité délégante", type: 'text', required: true },
      { key: 'operateur_prive', label: "Opérateur privé délégué", type: 'text', required: true },
      { key: 'service_concerne', label: "Service public local concerné", type: 'text', required: true },
      { key: 'duree_gestion', label: "Durée de la gestion déléguée", type: 'text', required: true },
      { key: 'redevance_collectivite', label: "Redevance due à la collectivité", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DÉLÉGUÉE — SERVICE PUBLIC LOCAL</h1><p><strong>Collectivité :</strong> {{collectivite_delegante}}</p><p><strong>Opérateur délégué :</strong> {{operateur_prive}}</p><p><strong>Service :</strong> {{service_concerne}}</p><p><strong>Durée :</strong> {{duree_gestion}}</p><p><strong>Redevance :</strong> {{redevance_collectivite}}</p></div>`,
  },
  {
    code: 'adm2_accord_regie_municipale', name: "Accord de régie municipale (eau, déchets)", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Cadre organisationnel et financier d'une régie municipale directe pour la gestion de l'eau ou des déchets solides.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 63,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'type_regie', label: "Type de régie (eau / déchets / autre)", type: 'text', required: true },
      { key: 'budget_annuel_regie', label: "Budget annuel de la régie (FCFA)", type: 'text', required: true },
      { key: 'tarification', label: "Tarification appliquée aux usagers", type: 'textarea', required: true },
      { key: 'date_creation_regie', label: "Date de création de la régie", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉGIE MUNICIPALE</h1><p><strong>Commune :</strong> {{commune}}</p><p><strong>Type :</strong> {{type_regie}}</p><p><strong>Budget annuel :</strong> {{budget_annuel_regie}} FCFA</p><p><strong>Date de création :</strong> {{date_creation_regie}}</p><h3>Tarification</h3><p>{{tarification}}</p></div>`,
  },
  {
    code: 'adm2_accord_ppp_local', name: "Accord de partenariat mairie-secteur privé (PPP local)", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "Convention de partenariat public-privé local (PPP) pour la réalisation ou la gestion d'infrastructures communales.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 68,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie partenaire", type: 'text', required: true },
      { key: 'partenaire_prive', label: "Partenaire privé", type: 'text', required: true },
      { key: 'objet_ppp', label: "Objet du PPP", type: 'textarea', required: true },
      { key: 'partage_risques', label: "Répartition des risques et responsabilités", type: 'textarea', required: true },
      { key: 'duree_ppp', label: "Durée du partenariat", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT PUBLIC-PRIVÉ LOCAL</h1><p><strong>Mairie :</strong> {{mairie}}</p><p><strong>Partenaire privé :</strong> {{partenaire_prive}}</p><p><strong>Durée :</strong> {{duree_ppp}}</p><h3>Objet du PPP</h3><p>{{objet_ppp}}</p><h3>Répartition des risques</h3><p>{{partage_risques}}</p></div>`,
  },
  {
    code: 'adm2_accord_cooperation_decentralisee', name: "Accord de convention de coopération décentralisée (jumelage)", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Convention de jumelage ou coopération décentralisée entre une commune ivoirienne et une collectivité étrangère.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 62,
    fieldsJson: F([
      { key: 'commune_ivoirienne', label: "Commune ivoirienne", type: 'text', required: true },
      { key: 'collectivite_etrangere', label: "Collectivité étrangère partenaire", type: 'text', required: true },
      { key: 'domaines_cooperation', label: "Domaines de coopération", type: 'textarea', required: true },
      { key: 'programme_echanges', label: "Programme d'échanges et d'actions", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE COOPÉRATION DÉCENTRALISÉE</h1><p><strong>Commune CI :</strong> {{commune_ivoirienne}}</p><p><strong>Partenaire étranger :</strong> {{collectivite_etrangere}}</p><p><strong>Signée le :</strong> {{date_signature}}</p><h3>Domaines de coopération</h3><p>{{domaines_cooperation}}</p><h3>Programme d'échanges</h3><p>{{programme_echanges}}</p></div>`,
  },
  {
    code: 'adm2_accord_recensement', name: "Accord de service de recensement de population", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Convention organisant le déroulement du recensement de la population au niveau d'une commune ou d'un district en Côte d'Ivoire.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 60,
    fieldsJson: F([
      { key: 'autorite_commanditaire', label: "Autorité commanditaire (INS / Mairie)", type: 'text', required: true },
      { key: 'zone_recensement', label: "Zone géographique du recensement", type: 'text', required: true },
      { key: 'methodologie_recensement', label: "Méthodologie de recensement", type: 'textarea', required: true },
      { key: 'budget_operation', label: "Budget de l'opération (FCFA)", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du recensement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE RECENSEMENT DE POPULATION</h1><p><strong>Commanditaire :</strong> {{autorite_commanditaire}}</p><p><strong>Zone :</strong> {{zone_recensement}}</p><p><strong>Budget :</strong> {{budget_operation}} FCFA</p><p><strong>Début :</strong> {{date_debut}}</p><h3>Méthodologie</h3><p>{{methodologie_recensement}}</p></div>`,
  },
  {
    code: 'adm2_accord_etat_civil', name: "Accord de service de délivrance d'actes d'état civil", category: 'juridique_admin',
    price: 6000, priceMax: 18000, description: "Convention encadrant la délivrance et la numérisation des actes d'état civil (naissance, mariage, décès) par une mairie.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 74,
    fieldsJson: F([
      { key: 'mairie', label: "Mairie concernée", type: 'text', required: true },
      { key: 'prestataire_numerisation', label: "Prestataire de numérisation (si applicable)", type: 'text', required: false },
      { key: 'types_actes', label: "Types d'actes concernés", type: 'text', required: true },
      { key: 'objectif_actes', label: "Objectif annuel de délivrance d'actes", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — ÉTAT CIVIL</h1><p><strong>Mairie :</strong> {{mairie}}</p><p><strong>Prestataire de numérisation :</strong> {{prestataire_numerisation}}</p><p><strong>Actes concernés :</strong> {{types_actes}}</p><p><strong>Objectif annuel :</strong> {{objectif_actes}} actes</p><p><strong>Date :</strong> {{date_convention}}</p></div>`,
  },
  {
    code: 'adm2_accord_cadastre', name: "Accord de service de cadastre communal", category: 'juridique_admin',
    price: 12000, priceMax: 36000, description: "Convention de mise en place ou de mise à jour du cadastre communal entre une mairie et le service du cadastre de l'État.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 63,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'service_cadastre_etat', label: "Service du cadastre de l'État", type: 'text', required: true },
      { key: 'perimetre_cadastral', label: "Périmètre cadastral à lever", type: 'textarea', required: true },
      { key: 'budget_operation', label: "Budget de l'opération (FCFA)", type: 'text', required: true },
      { key: 'date_demarrage', label: "Date de démarrage", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CADASTRE COMMUNAL</h1><p><strong>Commune :</strong> {{commune}}</p><p><strong>Service cadastral :</strong> {{service_cadastre_etat}}</p><p><strong>Budget :</strong> {{budget_operation}} FCFA</p><p><strong>Démarrage :</strong> {{date_demarrage}}</p><h3>Périmètre cadastral</h3><p>{{perimetre_cadastral}}</p></div>`,
  },
  {
    code: 'adm2_accord_recouvrement_taxes', name: "Accord de recouvrement de taxes communales", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Convention fixant les modalités de recouvrement des taxes et impôts locaux (patente, taxe foncière, droits de marché) par la commune.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 71,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'agent_recouvrement', label: "Agent ou service de recouvrement", type: 'text', required: true },
      { key: 'types_taxes', label: "Types de taxes concernées", type: 'textarea', required: true },
      { key: 'objectif_recettes', label: "Objectif de recettes annuelles (FCFA)", type: 'text', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RECOUVREMENT DE TAXES COMMUNALES</h1><p><strong>Commune :</strong> {{commune}}</p><p><strong>Agent de recouvrement :</strong> {{agent_recouvrement}}</p><p><strong>Objectif recettes :</strong> {{objectif_recettes}} FCFA</p><p><strong>Date :</strong> {{date_convention}}</p><h3>Taxes concernées</h3><p>{{types_taxes}}</p></div>`,
  },
  {
    code: 'adm2_accord_police_municipale', name: "Accord de service de police municipale", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Convention organisant le service de police municipale (missions, effectifs, équipements) au sein d'une commune ivoirienne.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 66,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'missions_police', label: "Missions de la police municipale", type: 'textarea', required: true },
      { key: 'effectif_agents', label: "Effectif d'agents prévu", type: 'text', required: true },
      { key: 'budget_fonctionnement', label: "Budget de fonctionnement annuel (FCFA)", type: 'text', required: true },
      { key: 'date_creation', label: "Date de création du service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE POLICE MUNICIPALE</h1><p><strong>Commune :</strong> {{commune}}</p><p><strong>Effectif :</strong> {{effectif_agents}} agents</p><p><strong>Budget :</strong> {{budget_fonctionnement}} FCFA/an</p><p><strong>Date de création :</strong> {{date_creation}}</p><h3>Missions</h3><p>{{missions_police}}</p></div>`,
  },
  {
    code: 'adm2_rapport_activite_mairie', name: "Rapport d'activité annuel mairie", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Rapport annuel d'activités de la mairie présenté au conseil municipal, rendant compte de l'exécution du budget et des réalisations.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 78,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'exercice', label: "Exercice concerné", type: 'text', required: true },
      { key: 'bilan_realisations', label: "Bilan des réalisations", type: 'textarea', required: true },
      { key: 'execution_budgetaire', label: "Exécution budgétaire (recettes et dépenses)", type: 'textarea', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'ACTIVITÉ ANNUEL — MAIRIE DE {{commune}}</h1><p><strong>Exercice :</strong> {{exercice}}</p><p><strong>Date :</strong> {{date_rapport}}</p><h3>Bilan des réalisations</h3><p>{{bilan_realisations}}</p><h3>Exécution budgétaire</h3><p>{{execution_budgetaire}}</p></div>`,
  },
  {
    code: 'adm2_plan_developpement_communal', name: "Plan de développement communal (PDC)", category: 'juridique_admin',
    price: 15000, priceMax: 45000, description: "Plan quinquennal de développement communal fixant la vision, les axes stratégiques et le programme d'investissement de la commune.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 75,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'periode_pdc', label: "Période du PDC (ex: 2026-2030)", type: 'text', required: true },
      { key: 'vision_commune', label: "Vision de la commune", type: 'textarea', required: true },
      { key: 'axes_strategiques', label: "Axes stratégiques de développement", type: 'textarea', required: true },
      { key: 'programme_investissement', label: "Programme d'investissement prioritaire", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT COMMUNAL</h1><h2>COMMUNE DE {{commune}} — {{periode_pdc}}</h2><h3>Vision</h3><p>{{vision_commune}}</p><h3>Axes stratégiques</h3><p>{{axes_strategiques}}</p><h3>Programme d'investissement</h3><p>{{programme_investissement}}</p></div>`,
  },
  {
    code: 'adm2_plan_investissement_triennal', name: "Accord de plan d'investissement triennal collectivité", category: 'juridique_admin',
    price: 12000, priceMax: 36000, description: "Plan d'investissement sur trois ans d'une collectivité territoriale, validé par le conseil et soumis à l'autorité de tutelle.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 67,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivité territoriale", type: 'text', required: true },
      { key: 'periode', label: "Période (3 ans)", type: 'text', required: true },
      { key: 'projets_prioritaires', label: "Projets prioritaires d'investissement", type: 'textarea', required: true },
      { key: 'budget_total_triennal', label: "Budget total triennal (FCFA)", type: 'text', required: true },
      { key: 'sources_financement', label: "Sources de financement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D'INVESTISSEMENT TRIENNAL</h1><p><strong>Collectivité :</strong> {{collectivite}}</p><p><strong>Période :</strong> {{periode}}</p><p><strong>Budget total :</strong> {{budget_total_triennal}} FCFA</p><h3>Projets prioritaires</h3><p>{{projets_prioritaires}}</p><h3>Sources de financement</h3><p>{{sources_financement}}</p></div>`,
  },
  {
    code: 'adm2_accord_gestion_crise', name: "Accord de gestion de crise communale (catastrophe)", category: 'juridique_admin',
    price: 8000, priceMax: 24000, description: "Plan communal de gestion des risques et catastrophes (inondations, épidémies) et accord de coordination interservices.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 61,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'type_catastrophe', label: "Type de catastrophe visée", type: 'text', required: true },
      { key: 'acteurs_impliques', label: "Acteurs impliqués dans la gestion de crise", type: 'textarea', required: true },
      { key: 'plan_evacuation', label: "Plan d'évacuation et de secours", type: 'textarea', required: true },
      { key: 'date_adoption', label: "Date d'adoption du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DE CRISE COMMUNALE</h1><p><strong>Commune :</strong> {{commune}}</p><p><strong>Type de catastrophe :</strong> {{type_catastrophe}}</p><p><strong>Adopté le :</strong> {{date_adoption}}</p><h3>Acteurs impliqués</h3><p>{{acteurs_impliques}}</p><h3>Plan d'évacuation et de secours</h3><p>{{plan_evacuation}}</p></div>`,
  },
  {
    code: 'adm2_charte_service_public_local', name: "Charte du service public local de qualité", category: 'juridique_admin',
    price: 6000, priceMax: 18000, description: "Charte d'engagement de la mairie envers les usagers fixant les standards de qualité des services publics locaux.",
    templateType: 'pdf', classe: 'A', active: true, popularity: 69,
    fieldsJson: F([
      { key: 'commune', label: "Commune", type: 'text', required: true },
      { key: 'services_concernes', label: "Services publics concernés par la charte", type: 'textarea', required: true },
      { key: 'engagements_mairie', label: "Engagements de la mairie envers les usagers", type: 'textarea', required: true },
      { key: 'mecanisme_reclamation', label: "Mécanisme de réclamation des usagers", type: 'textarea', required: true },
      { key: 'date_adoption', label: "Date d'adoption de la charte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DU SERVICE PUBLIC LOCAL DE QUALITÉ</h1><h2>MAIRIE DE {{commune}}</h2><p><strong>Adoptée le :</strong> {{date_adoption}}</p><h3>Services concernés</h3><p>{{services_concernes}}</p><h3>Engagements de la mairie</h3><p>{{engagements_mairie}}</p><h3>Mécanisme de réclamation</h3><p>{{mecanisme_reclamation}}</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 70b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
