import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  { code: 'pi_brevet_depot', name: "Demande de dépôt de brevet OAPI", category: 'juridique_admin', price: 12000, priceMax: 36000,
    description: "Formulaire officiel de demande de dépôt de brevet auprès de l'OAPI pour les inventions en Afrique francophone.", templateType: 'pdf', classe: 'B', active: true, popularity: 82,
    fieldsJson: F([{key:'nom_inventeur',label:"Nom complet de l'inventeur",type:'text',required:true},{key:'titre_invention',label:"Titre de l'invention",type:'text',required:true},{key:'date_depot',label:"Date de dépôt souhaitée",type:'date',required:true},{key:'description_invention',label:"Description technique de l'invention",type:'textarea',required:true},{key:'revendications',label:"Revendications principales",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>DEMANDE DE DÉPÔT DE BREVET OAPI</h1><p><strong>Inventeur :</strong> {{nom_inventeur}}</p><p><strong>Titre de l'invention :</strong> {{titre_invention}}</p><p><strong>Date de dépôt :</strong> {{date_depot}}</p><h2>Description technique</h2><p>{{description_invention}}</p><h2>Revendications</h2><p>{{revendications}}</p><p>Déposé auprès de l'Organisation Africaine de la Propriété Intellectuelle (OAPI) conformément à l'Accord de Bangui révisé.</p></div>` },

  { code: 'pi_rapport_anteriorites', name: "Rapport de recherche en antériorités", category: 'juridique_admin', price: 8000, priceMax: 24000,
    description: "Rapport professionnel d'analyse des antériorités brevets avant dépôt, conforme aux standards OAPI.", templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([{key:'nom_mandataire',label:"Nom du mandataire en PI",type:'text',required:true},{key:'objet_recherche',label:"Objet de la recherche",type:'text',required:true},{key:'date_rapport',label:"Date du rapport",type:'date',required:true},{key:'resultats',label:"Résultats des recherches",type:'textarea',required:true},{key:'conclusion',label:"Conclusion et recommandations",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>RAPPORT DE RECHERCHE EN ANTÉRIORITÉS</h1><p><strong>Mandataire :</strong> {{nom_mandataire}}</p><p><strong>Objet :</strong> {{objet_recherche}}</p><p><strong>Date :</strong> {{date_rapport}}</p><h2>Résultats</h2><p>{{resultats}}</p><h2>Conclusion</h2><p>{{conclusion}}</p></div>` },

  { code: 'pi_cession_brevet', name: "Contrat de cession de brevet", category: 'juridique_admin', price: 15000, priceMax: 45000,
    description: "Contrat de transfert de propriété d'un brevet entre le cédant et le cessionnaire, conforme au droit OHADA et à l'Accord de Bangui.", templateType: 'pdf', classe: 'B', active: true, popularity: 75,
    fieldsJson: F([{key:'nom_cedant',label:"Nom/Raison sociale du cédant",type:'text',required:true},{key:'nom_cessionnaire',label:"Nom/Raison sociale du cessionnaire",type:'text',required:true},{key:'numero_brevet',label:"Numéro du brevet OAPI",type:'text',required:true},{key:'prix_cession',label:"Prix de cession (FCFA)",type:'text',required:true},{key:'date_signature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE CESSION DE BREVET</h1><p>Entre <strong>{{nom_cedant}}</strong> (le Cédant) et <strong>{{nom_cessionnaire}}</strong> (le Cessionnaire).</p><p><strong>Brevet OAPI N° :</strong> {{numero_brevet}}</p><p><strong>Prix de cession :</strong> {{prix_cession}} FCFA</p><p>Le Cédant transfère irrévocablement tous ses droits sur le brevet susvisé au Cessionnaire à compter de la date de signature.</p><p><strong>Signé le :</strong> {{date_signature}}</p></div>` },

  { code: 'pi_licence_brevet', name: "Contrat de licence de brevet", category: 'juridique_admin', price: 12000, priceMax: 36000,
    description: "Contrat d'autorisation d'exploitation d'un brevet OAPI avec définition des redevances et du territoire d'exploitation.", templateType: 'pdf', classe: 'B', active: true, popularity: 73,
    fieldsJson: F([{key:'donneur_licence',label:"Donneur de licence",type:'text',required:true},{key:'preneur_licence',label:"Preneur de licence",type:'text',required:true},{key:'numero_brevet',label:"Numéro du brevet",type:'text',required:true},{key:'taux_redevance',label:"Taux de redevance (%)",type:'text',required:true},{key:'duree_licence',label:"Durée de la licence",type:'text',required:true},{key:'date_effet',label:"Date de prise d'effet",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LICENCE DE BREVET</h1><p><strong>Donneur de licence :</strong> {{donneur_licence}}</p><p><strong>Preneur de licence :</strong> {{preneur_licence}}</p><p><strong>Brevet N° :</strong> {{numero_brevet}}</p><p><strong>Redevance :</strong> {{taux_redevance}}% du chiffre d'affaires net</p><p><strong>Durée :</strong> {{duree_licence}}</p><p><strong>Prise d'effet :</strong> {{date_effet}}</p></div>` },

  { code: 'pi_accord_licence_tech', name: "Accord de licence technologique", category: 'juridique_admin', price: 14000, priceMax: 42000,
    description: "Accord encadrant la concession de droits sur une technologie protégée incluant brevets, savoir-faire et documents techniques.", templateType: 'pdf', classe: 'B', active: true, popularity: 68,
    fieldsJson: F([{key:'concedant',label:"Concédant de la technologie",type:'text',required:true},{key:'concessionnaire',label:"Concessionnaire",type:'text',required:true},{key:'description_technologie',label:"Description de la technologie",type:'textarea',required:true},{key:'territoire',label:"Territoire d'exploitation",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE LICENCE TECHNOLOGIQUE</h1><p><strong>Concédant :</strong> {{concedant}}</p><p><strong>Concessionnaire :</strong> {{concessionnaire}}</p><h2>Technologie concernée</h2><p>{{description_technologie}}</p><p><strong>Territoire :</strong> {{territoire}}</p><p><strong>Entrée en vigueur :</strong> {{date_debut}}</p></div>` },

  { code: 'pi_transfert_technologie', name: "Contrat de transfert de technologie", category: 'juridique_admin', price: 16000, priceMax: 48000,
    description: "Contrat organisant le transfert complet d'une technologie incluant formation, documentation et assistance technique.", templateType: 'pdf', classe: 'B', active: true, popularity: 71,
    fieldsJson: F([{key:'transfereur',label:"Entité transférant la technologie",type:'text',required:true},{key:'beneficiaire',label:"Bénéficiaire du transfert",type:'text',required:true},{key:'objet_transfert',label:"Objet du transfert de technologie",type:'textarea',required:true},{key:'montant_contrat',label:"Montant du contrat (FCFA)",type:'text',required:true},{key:'date_signature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE TRANSFERT DE TECHNOLOGIE</h1><p><strong>Transféreur :</strong> {{transfereur}}</p><p><strong>Bénéficiaire :</strong> {{beneficiaire}}</p><h2>Objet du transfert</h2><p>{{objet_transfert}}</p><p><strong>Montant :</strong> {{montant_contrat}} FCFA</p><p><strong>Date :</strong> {{date_signature}}</p></div>` },

  { code: 'pi_accord_know_how', name: "Accord de know-how (savoir-faire)", category: 'juridique_admin', price: 10000, priceMax: 30000,
    description: "Accord de communication et d'exploitation d'un savoir-faire industriel confidentiel entre partenaires commerciaux.", templateType: 'pdf', classe: 'B', active: true, popularity: 66,
    fieldsJson: F([{key:'fournisseur_kh',label:"Fournisseur du savoir-faire",type:'text',required:true},{key:'recepteur_kh',label:"Récepteur du savoir-faire",type:'text',required:true},{key:'description_savoir',label:"Description du savoir-faire",type:'textarea',required:true},{key:'obligations_confidentialite',label:"Obligations de confidentialité",type:'textarea',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE SAVOIR-FAIRE (KNOW-HOW)</h1><p><strong>Fournisseur :</strong> {{fournisseur_kh}}</p><p><strong>Récepteur :</strong> {{recepteur_kh}}</p><h2>Savoir-faire communiqué</h2><p>{{description_savoir}}</p><h2>Confidentialité</h2><p>{{obligations_confidentialite}}</p><p><strong>Date :</strong> {{date_accord}}</p></div>` },

  { code: 'pi_depot_marque_oapi', name: "Demande d'enregistrement de marque OAPI", category: 'juridique_admin', price: 9000, priceMax: 27000,
    description: "Dossier de demande d'enregistrement d'une marque commerciale auprès de l'OAPI pour les pays membres.", templateType: 'pdf', classe: 'B', active: true, popularity: 85,
    fieldsJson: F([{key:'deposant',label:"Nom du déposant",type:'text',required:true},{key:'marque',label:"Dénomination de la marque",type:'text',required:true},{key:'classes_nice',label:"Classes de Nice concernées",type:'text',required:true},{key:'produits_services',label:"Produits ou services désignés",type:'textarea',required:true},{key:'date_depot',label:"Date de dépôt",type:'date',required:true}]),
    body: `<div class="doc"><h1>DEMANDE D'ENREGISTREMENT DE MARQUE OAPI</h1><p><strong>Déposant :</strong> {{deposant}}</p><p><strong>Marque :</strong> {{marque}}</p><p><strong>Classes de Nice :</strong> {{classes_nice}}</p><h2>Produits et services</h2><p>{{produits_services}}</p><p><strong>Date de dépôt :</strong> {{date_depot}}</p></div>` },

  { code: 'pi_cession_marque', name: "Contrat de cession de marque", category: 'juridique_admin', price: 13000, priceMax: 39000,
    description: "Contrat de transfert de propriété d'une marque enregistrée à l'OAPI, avec garanties d'éviction et modalités de paiement.", templateType: 'pdf', classe: 'B', active: true, popularity: 72,
    fieldsJson: F([{key:'cedant_marque',label:"Cédant de la marque",type:'text',required:true},{key:'cessionnaire_marque',label:"Cessionnaire de la marque",type:'text',required:true},{key:'denomination_marque',label:"Dénomination de la marque",type:'text',required:true},{key:'numero_enregistrement',label:"Numéro d'enregistrement OAPI",type:'text',required:true},{key:'prix_cession',label:"Prix de cession (FCFA)",type:'text',required:true},{key:'date_acte',label:"Date de l'acte",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE CESSION DE MARQUE</h1><p><strong>Cédant :</strong> {{cedant_marque}}</p><p><strong>Cessionnaire :</strong> {{cessionnaire_marque}}</p><p><strong>Marque :</strong> {{denomination_marque}} — N° OAPI : {{numero_enregistrement}}</p><p><strong>Prix :</strong> {{prix_cession}} FCFA</p><p><strong>Date :</strong> {{date_acte}}</p></div>` },

  { code: 'pi_licence_marque', name: "Contrat de licence de marque", category: 'juridique_admin', price: 11000, priceMax: 33000,
    description: "Contrat autorisant un tiers à utiliser une marque enregistrée sous conditions définies, avec contrôle de qualité.", templateType: 'pdf', classe: 'B', active: true, popularity: 69,
    fieldsJson: F([{key:'proprietaire_marque',label:"Propriétaire de la marque",type:'text',required:true},{key:'licencie',label:"Licencié",type:'text',required:true},{key:'marque_licenciee',label:"Marque licenciée",type:'text',required:true},{key:'redevance_mensuelle',label:"Redevance mensuelle (FCFA)",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LICENCE DE MARQUE</h1><p><strong>Propriétaire :</strong> {{proprietaire_marque}}</p><p><strong>Licencié :</strong> {{licencie}}</p><p><strong>Marque :</strong> {{marque_licenciee}}</p><p><strong>Redevance mensuelle :</strong> {{redevance_mensuelle}} FCFA</p><p><strong>Début :</strong> {{date_debut}}</p></div>` },

  { code: 'pi_accord_cobranding', name: "Accord de co-branding", category: 'juridique_admin', price: 10000, priceMax: 30000,
    description: "Accord de co-marquage entre deux entités pour l'exploitation commune de leurs marques sur des produits ou services co-développés.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'partenaire_a',label:"Partenaire A",type:'text',required:true},{key:'partenaire_b',label:"Partenaire B",type:'text',required:true},{key:'produit_cobrande',label:"Produit ou service co-brandé",type:'text',required:true},{key:'modalites',label:"Modalités d'utilisation des marques",type:'textarea',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE CO-BRANDING</h1><p><strong>Partenaire A :</strong> {{partenaire_a}}</p><p><strong>Partenaire B :</strong> {{partenaire_b}}</p><p><strong>Produit co-brandé :</strong> {{produit_cobrande}}</p><h2>Modalités</h2><p>{{modalites}}</p><p><strong>Date :</strong> {{date_accord}}</p></div>` },

  { code: 'pi_contrat_franchise', name: "Contrat de franchise de marque", category: 'juridique_admin', price: 18000, priceMax: 54000,
    description: "Contrat de franchise commerciale encadrant l'utilisation d'une marque et d'un concept par un franchisé en zone OHADA.", templateType: 'pdf', classe: 'B', active: true, popularity: 78,
    fieldsJson: F([{key:'franchiseur',label:"Franchiseur",type:'text',required:true},{key:'franchise',label:"Franchisé",type:'text',required:true},{key:'marque_franchise',label:"Marque franchisée",type:'text',required:true},{key:'droit_entree',label:"Droit d'entrée (FCFA)",type:'text',required:true},{key:'taux_royalties',label:"Taux de royalties (%)",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE FRANCHISE DE MARQUE</h1><p><strong>Franchiseur :</strong> {{franchiseur}}</p><p><strong>Franchisé :</strong> {{franchise}}</p><p><strong>Marque :</strong> {{marque_franchise}}</p><p><strong>Droit d'entrée :</strong> {{droit_entree}} FCFA</p><p><strong>Royalties :</strong> {{taux_royalties}}%</p><p><strong>Début :</strong> {{date_debut}}</p></div>` },

  { code: 'pi_depot_dessin_industriel', name: "Demande de protection de dessin industriel", category: 'juridique_admin', price: 8000, priceMax: 24000,
    description: "Dossier de demande de protection d'un dessin ou modèle industriel auprès de l'OAPI selon l'Accord de Bangui révisé.", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'deposant_dessin',label:"Déposant",type:'text',required:true},{key:'titre_dessin',label:"Titre du dessin industriel",type:'text',required:true},{key:'description_dessin',label:"Description du dessin",type:'textarea',required:true},{key:'secteur_produit',label:"Secteur d'application du produit",type:'text',required:true},{key:'date_depot',label:"Date de dépôt",type:'date',required:true}]),
    body: `<div class="doc"><h1>DEMANDE DE PROTECTION DE DESSIN INDUSTRIEL — OAPI</h1><p><strong>Déposant :</strong> {{deposant_dessin}}</p><p><strong>Titre :</strong> {{titre_dessin}}</p><p><strong>Secteur :</strong> {{secteur_produit}}</p><h2>Description</h2><p>{{description_dessin}}</p><p><strong>Date de dépôt :</strong> {{date_depot}}</p></div>` },

  { code: 'pi_depot_droit_auteur', name: "Dépôt droit d'auteur OAPI/BURIDA", category: 'juridique_admin', price: 6000, priceMax: 18000,
    description: "Formulaire de dépôt et déclaration d'une oeuvre protégée par le droit d'auteur auprès de l'OAPI ou du BURIDA (Côte d'Ivoire).", templateType: 'pdf', classe: 'B', active: true, popularity: 74,
    fieldsJson: F([{key:'auteur',label:"Nom de l'auteur",type:'text',required:true},{key:'titre_oeuvre',label:"Titre de l'oeuvre",type:'text',required:true},{key:'nature_oeuvre',label:"Nature de l'oeuvre (littéraire, musicale, etc.)",type:'text',required:true},{key:'date_creation',label:"Date de création",type:'date',required:true},{key:'description_oeuvre',label:"Description sommaire",type:'textarea',required:true}]),
    body: `<div class="doc"><h1>DÉCLARATION DE DÉPÔT — DROIT D'AUTEUR</h1><p><strong>Auteur :</strong> {{auteur}}</p><p><strong>Oeuvre :</strong> {{titre_oeuvre}}</p><p><strong>Nature :</strong> {{nature_oeuvre}}</p><p><strong>Date de création :</strong> {{date_creation}}</p><h2>Description</h2><p>{{description_oeuvre}}</p></div>` },

  { code: 'pi_cession_oeuvre_av', name: "Contrat de cession d'oeuvre audiovisuelle", category: 'juridique_admin', price: 11000, priceMax: 33000,
    description: "Contrat de cession des droits patrimoniaux sur une oeuvre audiovisuelle entre producteur et auteur, conforme au droit d'auteur OHADA.", templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([{key:'auteur_av',label:"Auteur/Réalisateur",type:'text',required:true},{key:'producteur',label:"Producteur cessionnaire",type:'text',required:true},{key:'titre_oeuvre',label:"Titre de l'oeuvre",type:'text',required:true},{key:'droits_cedes',label:"Droits cédés (diffusion, distribution, etc.)",type:'textarea',required:true},{key:'remuneration',label:"Rémunération (FCFA)",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE CESSION D'OEUVRE AUDIOVISUELLE</h1><p><strong>Auteur :</strong> {{auteur_av}}</p><p><strong>Producteur :</strong> {{producteur}}</p><p><strong>Titre :</strong> {{titre_oeuvre}}</p><h2>Droits cédés</h2><p>{{droits_cedes}}</p><p><strong>Rémunération :</strong> {{remuneration}} FCFA</p></div>` },

  { code: 'pi_contrat_edition_logiciel', name: "Contrat d'édition logicielle", category: 'juridique_admin', price: 13000, priceMax: 39000,
    description: "Contrat entre un développeur et un éditeur pour la commercialisation d'un logiciel, incluant droits de reproduction et de distribution.", templateType: 'pdf', classe: 'B', active: true, popularity: 71,
    fieldsJson: F([{key:'developpeur',label:"Développeur",type:'text',required:true},{key:'editeur',label:"Éditeur",type:'text',required:true},{key:'nom_logiciel',label:"Nom du logiciel",type:'text',required:true},{key:'version',label:"Version du logiciel",type:'text',required:true},{key:'redevances',label:"Taux de redevances (%)",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT D'ÉDITION LOGICIELLE</h1><p><strong>Développeur :</strong> {{developpeur}}</p><p><strong>Éditeur :</strong> {{editeur}}</p><p><strong>Logiciel :</strong> {{nom_logiciel}} — Version {{version}}</p><p><strong>Redevances :</strong> {{redevances}}%</p><p><strong>Date :</strong> {{date_contrat}}</p></div>` },

  { code: 'pi_licence_open_source', name: "Contrat de licence open source", category: 'juridique_admin', price: 5000, priceMax: 15000,
    description: "Accord de mise à disposition d'un logiciel sous licence open source avec définition des droits d'utilisation, modification et redistribution.", templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([{key:'auteur_logiciel',label:"Auteur du logiciel",type:'text',required:true},{key:'nom_logiciel',label:"Nom du logiciel",type:'text',required:true},{key:'type_licence',label:"Type de licence (MIT, GPL, Apache, etc.)",type:'text',required:true},{key:'conditions',label:"Conditions d'utilisation spécifiques",type:'textarea',required:true},{key:'date_publication',label:"Date de publication",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LICENCE OPEN SOURCE</h1><p><strong>Auteur :</strong> {{auteur_logiciel}}</p><p><strong>Logiciel :</strong> {{nom_logiciel}}</p><p><strong>Licence :</strong> {{type_licence}}</p><h2>Conditions spécifiques</h2><p>{{conditions}}</p><p><strong>Date :</strong> {{date_publication}}</p></div>` },

  { code: 'pi_accord_secret_industriel', name: "Accord de protection du secret industriel", category: 'juridique_admin', price: 9000, priceMax: 27000,
    description: "Accord juridique de protection des secrets industriels et commerciaux d'une entreprise contre toute divulgation non autorisée.", templateType: 'pdf', classe: 'B', active: true, popularity: 76,
    fieldsJson: F([{key:'entreprise',label:"Entreprise propriétaire",type:'text',required:true},{key:'recepteur',label:"Personne ou entité réceptrice",type:'text',required:true},{key:'nature_secret',label:"Nature du secret industriel",type:'textarea',required:true},{key:'duree_protection',label:"Durée de protection",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE PROTECTION DU SECRET INDUSTRIEL</h1><p><strong>Propriétaire :</strong> {{entreprise}}</p><p><strong>Récepteur :</strong> {{recepteur}}</p><h2>Nature du secret</h2><p>{{nature_secret}}</p><p><strong>Durée :</strong> {{duree_protection}}</p><p><strong>Date :</strong> {{date_accord}}</p></div>` },

  { code: 'pi_nda_technique', name: "Clause de non-divulgation (NDA) technique", category: 'juridique_admin', price: 7000, priceMax: 21000,
    description: "Accord de non-divulgation spécialisé pour les informations techniques, formules, procédés et données confidentielles entre entreprises.", templateType: 'pdf', classe: 'B', active: true, popularity: 88,
    fieldsJson: F([{key:'partie_divulgatrice',label:"Partie divulgatrice",type:'text',required:true},{key:'partie_receptrice',label:"Partie réceptrice",type:'text',required:true},{key:'informations_confidentielles',label:"Informations confidentielles concernées",type:'textarea',required:true},{key:'duree_nda',label:"Durée du NDA",type:'text',required:true},{key:'date_signature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE NON-DIVULGATION TECHNIQUE (NDA)</h1><p><strong>Partie divulgatrice :</strong> {{partie_divulgatrice}}</p><p><strong>Partie réceptrice :</strong> {{partie_receptrice}}</p><h2>Informations confidentielles</h2><p>{{informations_confidentielles}}</p><p><strong>Durée :</strong> {{duree_nda}}</p><p><strong>Signé le :</strong> {{date_signature}}</p></div>` },

  { code: 'pi_accord_recherche_conjointe', name: "Accord de recherche conjointe", category: 'juridique_admin', price: 12000, priceMax: 36000,
    description: "Convention organisant la collaboration entre deux entités pour mener des activités de recherche communes avec partage des résultats.", templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([{key:'entite_a',label:"Entité A",type:'text',required:true},{key:'entite_b',label:"Entité B",type:'text',required:true},{key:'objet_recherche',label:"Objet de la recherche conjointe",type:'textarea',required:true},{key:'partage_resultats',label:"Modalités de partage des résultats",type:'textarea',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE RECHERCHE CONJOINTE</h1><p><strong>Entité A :</strong> {{entite_a}}</p><p><strong>Entité B :</strong> {{entite_b}}</p><h2>Objet de la recherche</h2><p>{{objet_recherche}}</p><h2>Partage des résultats</h2><p>{{partage_resultats}}</p><p><strong>Début :</strong> {{date_debut}}</p></div>` },

  { code: 'pi_convention_consortium_rd', name: "Convention de consortium R&D", category: 'juridique_admin', price: 14000, priceMax: 42000,
    description: "Convention multi-parties établissant un consortium de recherche et développement avec gouvernance, financement et propriété intellectuelle partagée.", templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([{key:'membres_consortium',label:"Membres du consortium",type:'textarea',required:true},{key:'objet_consortium',label:"Objet du consortium R&D",type:'textarea',required:true},{key:'budget_total',label:"Budget total (FCFA)",type:'text',required:true},{key:'chef_file',label:"Membre chef de file",type:'text',required:true},{key:'date_constitution',label:"Date de constitution",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE CONSORTIUM R&D</h1><h2>Membres</h2><p>{{membres_consortium}}</p><h2>Objet</h2><p>{{objet_consortium}}</p><p><strong>Budget total :</strong> {{budget_total}} FCFA</p><p><strong>Chef de file :</strong> {{chef_file}}</p><p><strong>Date de constitution :</strong> {{date_constitution}}</p></div>` },

  { code: 'pi_contrat_recherche_soustraitee', name: "Contrat de recherche sous-traitée", category: 'juridique_admin', price: 10000, priceMax: 30000,
    description: "Contrat confiant à un prestataire spécialisé des travaux de recherche définis, avec transfert des résultats au donneur d'ordre.", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'donneur_ordre',label:"Donneur d'ordre",type:'text',required:true},{key:'prestataire',label:"Prestataire de recherche",type:'text',required:true},{key:'programme_recherche',label:"Programme de recherche",type:'textarea',required:true},{key:'budget',label:"Budget alloué (FCFA)",type:'text',required:true},{key:'date_fin',label:"Date de fin prévue",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE RECHERCHE SOUS-TRAITÉE</h1><p><strong>Donneur d'ordre :</strong> {{donneur_ordre}}</p><p><strong>Prestataire :</strong> {{prestataire}}</p><h2>Programme</h2><p>{{programme_recherche}}</p><p><strong>Budget :</strong> {{budget}} FCFA</p><p><strong>Date de fin :</strong> {{date_fin}}</p></div>` },

  { code: 'pi_accord_materiel_biologique', name: "Accord de transfert de matériel biologique", category: 'juridique_admin', price: 11000, priceMax: 33000,
    description: "Accord encadrant le transfert de matériel biologique entre institutions à des fins de recherche, conforme au Protocole de Nagoya.", templateType: 'pdf', classe: 'B', active: true, popularity: 55,
    fieldsJson: F([{key:'fournisseur_materiel',label:"Fournisseur du matériel",type:'text',required:true},{key:'destinataire',label:"Destinataire",type:'text',required:true},{key:'description_materiel',label:"Description du matériel biologique",type:'textarea',required:true},{key:'usage_autorise',label:"Usage autorisé",type:'textarea',required:true},{key:'date_transfert',label:"Date de transfert",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE TRANSFERT DE MATÉRIEL BIOLOGIQUE</h1><p><strong>Fournisseur :</strong> {{fournisseur_materiel}}</p><p><strong>Destinataire :</strong> {{destinataire}}</p><h2>Matériel concerné</h2><p>{{description_materiel}}</p><h2>Usage autorisé</h2><p>{{usage_autorise}}</p><p><strong>Date :</strong> {{date_transfert}}</p></div>` },

  { code: 'pi_rapport_valorisation', name: "Rapport de valorisation de propriété intellectuelle", category: 'juridique_admin', price: 15000, priceMax: 45000,
    description: "Rapport d'évaluation économique d'un portefeuille de propriété intellectuelle pour cession, licence ou apport en société.", templateType: 'pdf', classe: 'B', active: true, popularity: 69,
    fieldsJson: F([{key:'expert_evaluateur',label:"Expert évaluateur",type:'text',required:true},{key:'titulaire_pi',label:"Titulaire des droits PI",type:'text',required:true},{key:'actifs_evalues',label:"Actifs PI évalués",type:'textarea',required:true},{key:'valeur_estimee',label:"Valeur estimée (FCFA)",type:'text',required:true},{key:'date_rapport',label:"Date du rapport",type:'date',required:true}]),
    body: `<div class="doc"><h1>RAPPORT DE VALORISATION — PROPRIÉTÉ INTELLECTUELLE</h1><p><strong>Expert :</strong> {{expert_evaluateur}}</p><p><strong>Titulaire :</strong> {{titulaire_pi}}</p><h2>Actifs évalués</h2><p>{{actifs_evalues}}</p><p><strong>Valeur estimée :</strong> {{valeur_estimee}} FCFA</p><p><strong>Date :</strong> {{date_rapport}}</p></div>` },

  { code: 'pi_audit_portefeuille_brevets', name: "Audit de portefeuille brevets", category: 'juridique_admin', price: 18000, priceMax: 54000,
    description: "Rapport d'audit complet du portefeuille de brevets d'une entreprise : validité, exploitation, risques et recommandations stratégiques.", templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([{key:'auditeur',label:"Cabinet auditeur",type:'text',required:true},{key:'entreprise_auditee',label:"Entreprise auditée",type:'text',required:true},{key:'nombre_brevets',label:"Nombre de brevets audités",type:'text',required:true},{key:'constats',label:"Constats principaux",type:'textarea',required:true},{key:'date_audit',label:"Date de l'audit",type:'date',required:true}]),
    body: `<div class="doc"><h1>AUDIT DE PORTEFEUILLE BREVETS</h1><p><strong>Auditeur :</strong> {{auditeur}}</p><p><strong>Entreprise :</strong> {{entreprise_auditee}}</p><p><strong>Brevets audités :</strong> {{nombre_brevets}}</p><h2>Constats</h2><p>{{constats}}</p><p><strong>Date :</strong> {{date_audit}}</p></div>` },

  // ─── INNOVATION / R&D (innov_) ────────────────────────────────────────────

  { code: 'innov_partenariat_innovation', name: "Accord de partenariat innovation", category: 'commercial_financier', price: 10000, priceMax: 30000,
    description: "Accord cadre de partenariat entre deux entités pour développer conjointement des projets innovants avec partage des coûts et bénéfices.", templateType: 'pdf', classe: 'B', active: true, popularity: 80,
    fieldsJson: F([{key:'partenaire_1',label:"Partenaire 1",type:'text',required:true},{key:'partenaire_2',label:"Partenaire 2",type:'text',required:true},{key:'domaine_innovation',label:"Domaine d'innovation",type:'text',required:true},{key:'objectifs',label:"Objectifs du partenariat",type:'textarea',required:true},{key:'date_signature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT INNOVATION</h1><p><strong>Partenaire 1 :</strong> {{partenaire_1}}</p><p><strong>Partenaire 2 :</strong> {{partenaire_2}}</p><p><strong>Domaine :</strong> {{domaine_innovation}}</p><h2>Objectifs</h2><p>{{objectifs}}</p><p><strong>Signé le :</strong> {{date_signature}}</p></div>` },

  { code: 'innov_contrat_incubation', name: "Contrat d'incubation startup", category: 'commercial_financier', price: 8000, priceMax: 24000,
    description: "Contrat entre un incubateur et une startup définissant les services d'accompagnement, la durée, les conditions financières et la contrepartie.", templateType: 'pdf', classe: 'B', active: true, popularity: 82,
    fieldsJson: F([{key:'incubateur',label:"Incubateur",type:'text',required:true},{key:'startup',label:"Startup incubée",type:'text',required:true},{key:'services_offerts',label:"Services offerts par l'incubateur",type:'textarea',required:true},{key:'contrepartie',label:"Contrepartie (frais ou participation au capital)",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT D'INCUBATION STARTUP</h1><p><strong>Incubateur :</strong> {{incubateur}}</p><p><strong>Startup :</strong> {{startup}}</p><h2>Services</h2><p>{{services_offerts}}</p><p><strong>Contrepartie :</strong> {{contrepartie}}</p><p><strong>Début :</strong> {{date_debut}}</p></div>` },

  { code: 'innov_convention_pepiniere', name: "Convention de pépinière d'entreprises", category: 'commercial_financier', price: 7000, priceMax: 21000,
    description: "Convention d'hébergement et d'accompagnement d'une jeune entreprise au sein d'une pépinière, avec accès aux ressources mutualisées.", templateType: 'pdf', classe: 'B', active: true, popularity: 73,
    fieldsJson: F([{key:'pepiniere',label:"Pépinière d'entreprises",type:'text',required:true},{key:'entreprise_hebergee',label:"Entreprise hébergée",type:'text',required:true},{key:'loyer_mensuel',label:"Loyer mensuel (FCFA)",type:'text',required:true},{key:'services_inclus',label:"Services inclus",type:'textarea',required:true},{key:'date_entree',label:"Date d'entrée",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE PÉPINIÈRE D'ENTREPRISES</h1><p><strong>Pépinière :</strong> {{pepiniere}}</p><p><strong>Entreprise :</strong> {{entreprise_hebergee}}</p><p><strong>Loyer mensuel :</strong> {{loyer_mensuel}} FCFA</p><h2>Services inclus</h2><p>{{services_inclus}}</p><p><strong>Date d'entrée :</strong> {{date_entree}}</p></div>` },

  { code: 'innov_codeveloppement_produit', name: "Contrat de co-développement produit", category: 'commercial_financier', price: 12000, priceMax: 36000,
    description: "Contrat organisant le développement collaboratif d'un nouveau produit entre deux entreprises avec partage des investissements et des droits.", templateType: 'pdf', classe: 'B', active: true, popularity: 75,
    fieldsJson: F([{key:'codev_a',label:"Partenaire co-développeur A",type:'text',required:true},{key:'codev_b',label:"Partenaire co-développeur B",type:'text',required:true},{key:'description_produit',label:"Description du produit à développer",type:'textarea',required:true},{key:'apport_chaque_partie',label:"Apport de chaque partie",type:'textarea',required:true},{key:'date_lancement',label:"Date de lancement prévu",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE CO-DÉVELOPPEMENT PRODUIT</h1><p><strong>Partenaire A :</strong> {{codev_a}}</p><p><strong>Partenaire B :</strong> {{codev_b}}</p><h2>Produit</h2><p>{{description_produit}}</p><h2>Apports</h2><p>{{apport_chaque_partie}}</p><p><strong>Lancement prévu :</strong> {{date_lancement}}</p></div>` },

  { code: 'innov_partenariat_univ_entreprise', name: "Accord de partenariat université-entreprise", category: 'commercial_financier', price: 11000, priceMax: 33000,
    description: "Accord de collaboration entre une université et une entreprise pour des projets de recherche appliquée et de transfert de connaissances.", templateType: 'pdf', classe: 'B', active: true, popularity: 72,
    fieldsJson: F([{key:'universite',label:"Université partenaire",type:'text',required:true},{key:'entreprise',label:"Entreprise partenaire",type:'text',required:true},{key:'programme_collaboration',label:"Programme de collaboration",type:'textarea',required:true},{key:'financement_entreprise',label:"Financement de l'entreprise (FCFA)",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD UNIVERSITÉ-ENTREPRISE</h1><p><strong>Université :</strong> {{universite}}</p><p><strong>Entreprise :</strong> {{entreprise}}</p><h2>Programme</h2><p>{{programme_collaboration}}</p><p><strong>Financement entreprise :</strong> {{financement_entreprise}} FCFA</p><p><strong>Date :</strong> {{date_accord}}</p></div>` },

  { code: 'innov_these_cifre_locale', name: "Contrat de thèse CIFRE locale", category: 'commercial_financier', price: 9000, priceMax: 27000,
    description: "Contrat de thèse en entreprise (CIFRE adapté) associant un doctorant, une université et une entreprise en Afrique francophone.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'doctorant',label:"Doctorant",type:'text',required:true},{key:'universite_these',label:"Université d'accueil",type:'text',required:true},{key:'entreprise_these',label:"Entreprise d'accueil",type:'text',required:true},{key:'sujet_these',label:"Sujet de thèse",type:'textarea',required:true},{key:'date_debut_these',label:"Date de début de thèse",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE THÈSE EN ENTREPRISE (CIFRE)</h1><p><strong>Doctorant :</strong> {{doctorant}}</p><p><strong>Université :</strong> {{universite_these}}</p><p><strong>Entreprise :</strong> {{entreprise_these}}</p><h2>Sujet de thèse</h2><p>{{sujet_these}}</p><p><strong>Début :</strong> {{date_debut_these}}</p></div>` },

  { code: 'innov_convention_collab_scientifique', name: "Convention de collaboration scientifique", category: 'commercial_financier', price: 10000, priceMax: 30000,
    description: "Convention formalisant une collaboration scientifique entre deux institutions de recherche avec partage des publications et des données.", templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([{key:'institution_1',label:"Institution 1",type:'text',required:true},{key:'institution_2',label:"Institution 2",type:'text',required:true},{key:'domaine_scientifique',label:"Domaine scientifique",type:'text',required:true},{key:'plan_collaboration',label:"Plan de collaboration",type:'textarea',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE COLLABORATION SCIENTIFIQUE</h1><p><strong>Institution 1 :</strong> {{institution_1}}</p><p><strong>Institution 2 :</strong> {{institution_2}}</p><p><strong>Domaine :</strong> {{domaine_scientifique}}</p><h2>Plan de collaboration</h2><p>{{plan_collaboration}}</p><p><strong>Début :</strong> {{date_debut}}</p></div>` },

  { code: 'innov_accord_acceleration', name: "Accord de programme d'accélération", category: 'commercial_financier', price: 8000, priceMax: 24000,
    description: "Accord entre un accélérateur de startups et une entreprise sélectionnée définissant les services, le mentorat et la prise de participation.", templateType: 'pdf', classe: 'B', active: true, popularity: 77,
    fieldsJson: F([{key:'accelerateur',label:"Programme accélérateur",type:'text',required:true},{key:'startup_acceleree',label:"Startup accélérée",type:'text',required:true},{key:'services_acceleration',label:"Services d'accélération fournis",type:'textarea',required:true},{key:'participation_capital',label:"Participation au capital (%)",type:'text',required:true},{key:'date_entree',label:"Date d'entrée dans le programme",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE PROGRAMME D'ACCÉLÉRATION</h1><p><strong>Accélérateur :</strong> {{accelerateur}}</p><p><strong>Startup :</strong> {{startup_acceleree}}</p><h2>Services</h2><p>{{services_acceleration}}</p><p><strong>Participation au capital :</strong> {{participation_capital}}%</p><p><strong>Entrée :</strong> {{date_entree}}</p></div>` },

  { code: 'innov_contrat_mentor_startup', name: "Contrat de mentor startup", category: 'commercial_financier', price: 5000, priceMax: 15000,
    description: "Contrat de mentorat entre un entrepreneur expérimenté et une startup définissant les objectifs, la fréquence et les modalités de l'accompagnement.", templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([{key:'mentor',label:"Mentor",type:'text',required:true},{key:'startup_mentoree',label:"Startup mentoree",type:'text',required:true},{key:'objectifs_mentorat',label:"Objectifs du mentorat",type:'textarea',required:true},{key:'remuneration_mentor',label:"Rémunération du mentor (FCFA/mois)",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE MENTORAT STARTUP</h1><p><strong>Mentor :</strong> {{mentor}}</p><p><strong>Startup :</strong> {{startup_mentoree}}</p><h2>Objectifs</h2><p>{{objectifs_mentorat}}</p><p><strong>Rémunération :</strong> {{remuneration_mentor}} FCFA/mois</p><p><strong>Début :</strong> {{date_debut}}</p></div>` },

  { code: 'innov_convention_lab_ouvert', name: "Convention de lab d'innovation ouverte", category: 'commercial_financier', price: 9000, priceMax: 27000,
    description: "Convention d'accès et de participation à un laboratoire d'innovation ouverte (open lab) pour des partenaires externes.", templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([{key:'gestionnaire_lab',label:"Gestionnaire du lab",type:'text',required:true},{key:'partenaire_externe',label:"Partenaire externe",type:'text',required:true},{key:'ressources_partagees',label:"Ressources partagées",type:'textarea',required:true},{key:'contribution_partenaire',label:"Contribution du partenaire",type:'text',required:true},{key:'date_adhesion',label:"Date d'adhésion",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE LAB D'INNOVATION OUVERTE</h1><p><strong>Gestionnaire :</strong> {{gestionnaire_lab}}</p><p><strong>Partenaire :</strong> {{partenaire_externe}}</p><h2>Ressources partagées</h2><p>{{ressources_partagees}}</p><p><strong>Contribution :</strong> {{contribution_partenaire}}</p><p><strong>Adhésion :</strong> {{date_adhesion}}</p></div>` },

  { code: 'innov_accord_hackathon', name: "Accord de hackathon", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Accord de participation à un hackathon définissant les droits sur les créations, les prix et les conditions d'utilisation des résultats.", templateType: 'pdf', classe: 'B', active: true, popularity: 68,
    fieldsJson: F([{key:'organisateur',label:"Organisateur du hackathon",type:'text',required:true},{key:'participant',label:"Équipe participante",type:'text',required:true},{key:'theme_hackathon',label:"Thème du hackathon",type:'text',required:true},{key:'droits_creations',label:"Droits sur les créations",type:'textarea',required:true},{key:'date_evenement',label:"Date de l'événement",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE HACKATHON</h1><p><strong>Organisateur :</strong> {{organisateur}}</p><p><strong>Participant :</strong> {{participant}}</p><p><strong>Thème :</strong> {{theme_hackathon}}</p><h2>Droits sur les créations</h2><p>{{droits_creations}}</p><p><strong>Date :</strong> {{date_evenement}}</p></div>` },

  { code: 'innov_contrat_poc', name: "Contrat de pilote (POC)", category: 'commercial_financier', price: 7000, priceMax: 21000,
    description: "Contrat encadrant un projet pilote (Proof of Concept) entre un fournisseur technologique et un client, avec critères de succès et budget.", templateType: 'pdf', classe: 'B', active: true, popularity: 74,
    fieldsJson: F([{key:'fournisseur_tech',label:"Fournisseur technologique",type:'text',required:true},{key:'client_poc',label:"Client pilote",type:'text',required:true},{key:'description_poc',label:"Description du POC",type:'textarea',required:true},{key:'criteres_succes',label:"Critères de succès",type:'textarea',required:true},{key:'date_fin_poc',label:"Date de fin du POC",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT PILOTE (POC)</h1><p><strong>Fournisseur :</strong> {{fournisseur_tech}}</p><p><strong>Client :</strong> {{client_poc}}</p><h2>Description</h2><p>{{description_poc}}</p><h2>Critères de succès</h2><p>{{criteres_succes}}</p><p><strong>Fin prévue :</strong> {{date_fin_poc}}</p></div>` },

  { code: 'innov_accord_test_utilisateur', name: "Accord de test utilisateur", category: 'commercial_financier', price: 4000, priceMax: 12000,
    description: "Accord de participation à des tests utilisateurs pour un produit ou service, avec clauses de confidentialité et de collecte de données.", templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([{key:'entreprise_test',label:"Entreprise organisant les tests",type:'text',required:true},{key:'testeur',label:"Testeur participant",type:'text',required:true},{key:'produit_teste',label:"Produit ou service testé",type:'text',required:true},{key:'conditions_participation',label:"Conditions de participation",type:'textarea',required:true},{key:'date_test',label:"Date des tests",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE TEST UTILISATEUR</h1><p><strong>Entreprise :</strong> {{entreprise_test}}</p><p><strong>Testeur :</strong> {{testeur}}</p><p><strong>Produit testé :</strong> {{produit_teste}}</p><h2>Conditions</h2><p>{{conditions_participation}}</p><p><strong>Date :</strong> {{date_test}}</p></div>` },

  { code: 'innov_contrat_developpement_agile', name: "Contrat de développement agile", category: 'commercial_financier', price: 10000, priceMax: 30000,
    description: "Contrat de développement logiciel en mode agile avec définition des sprints, de la vélocité et des conditions de livraison itérative.", templateType: 'pdf', classe: 'B', active: true, popularity: 79,
    fieldsJson: F([{key:'client_agile',label:"Client",type:'text',required:true},{key:'prestataire_agile',label:"Prestataire développement",type:'text',required:true},{key:'backlog_produit',label:"Description du backlog produit",type:'textarea',required:true},{key:'budget_sprints',label:"Budget (FCFA/sprint)",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE DÉVELOPPEMENT AGILE</h1><p><strong>Client :</strong> {{client_agile}}</p><p><strong>Prestataire :</strong> {{prestataire_agile}}</p><h2>Backlog produit</h2><p>{{backlog_produit}}</p><p><strong>Budget/sprint :</strong> {{budget_sprints}} FCFA</p><p><strong>Début :</strong> {{date_debut}}</p></div>` },

  { code: 'innov_convention_design_thinking', name: "Convention de design thinking", category: 'commercial_financier', price: 6000, priceMax: 18000,
    description: "Convention organisant des ateliers de design thinking entre une entreprise et un cabinet spécialisé pour l'innovation centrée utilisateur.", templateType: 'pdf', classe: 'B', active: true, popularity: 66,
    fieldsJson: F([{key:'facilitateur',label:"Facilitateur design thinking",type:'text',required:true},{key:'entreprise_cliente',label:"Entreprise cliente",type:'text',required:true},{key:'problematique',label:"Problématique à résoudre",type:'textarea',required:true},{key:'nombre_ateliers',label:"Nombre d'ateliers prévus",type:'text',required:true},{key:'date_premier_atelier',label:"Date du premier atelier",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE DESIGN THINKING</h1><p><strong>Facilitateur :</strong> {{facilitateur}}</p><p><strong>Entreprise :</strong> {{entreprise_cliente}}</p><h2>Problématique</h2><p>{{problematique}}</p><p><strong>Nombre d'ateliers :</strong> {{nombre_ateliers}}</p><p><strong>Premier atelier :</strong> {{date_premier_atelier}}</p></div>` },

  { code: 'innov_accord_cocreation_client', name: "Accord de co-création avec client", category: 'commercial_financier', price: 8000, priceMax: 24000,
    description: "Accord de co-innovation associant un client à la conception et au développement d'une solution adaptée à ses besoins spécifiques.", templateType: 'pdf', classe: 'B', active: true, popularity: 72,
    fieldsJson: F([{key:'entreprise_innovante',label:"Entreprise innovante",type:'text',required:true},{key:'client_cocreateur',label:"Client co-créateur",type:'text',required:true},{key:'solution_cocreee',label:"Solution à co-créer",type:'textarea',required:true},{key:'droits_solution',label:"Droits sur la solution créée",type:'textarea',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE CO-CRÉATION AVEC CLIENT</h1><p><strong>Entreprise :</strong> {{entreprise_innovante}}</p><p><strong>Client co-créateur :</strong> {{client_cocreateur}}</p><h2>Solution</h2><p>{{solution_cocreee}}</p><h2>Droits</h2><p>{{droits_solution}}</p><p><strong>Date :</strong> {{date_accord}}</p></div>` },

  { code: 'innov_contrat_licences_innovation', name: "Contrat de licences innovation", category: 'commercial_financier', price: 11000, priceMax: 33000,
    description: "Contrat de mise à disposition sous licence d'un ensemble de droits PI liés à une innovation pour commercialisation par un partenaire.", templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([{key:'detenteur_innovation',label:"Détenteur de l'innovation",type:'text',required:true},{key:'licensie_innovation',label:"Licencié",type:'text',required:true},{key:'innovation_licenciee',label:"Innovation licenciée",type:'textarea',required:true},{key:'modele_redevances',label:"Modèle de redevances",type:'text',required:true},{key:'date_effet',label:"Date de prise d'effet",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LICENCES INNOVATION</h1><p><strong>Détenteur :</strong> {{detenteur_innovation}}</p><p><strong>Licencié :</strong> {{licensie_innovation}}</p><h2>Innovation</h2><p>{{innovation_licenciee}}</p><p><strong>Redevances :</strong> {{modele_redevances}}</p><p><strong>Prise d'effet :</strong> {{date_effet}}</p></div>` },

  { code: 'innov_accord_spinoff_universitaire', name: "Accord de spin-off universitaire", category: 'commercial_financier', price: 13000, priceMax: 39000,
    description: "Accord encadrant la création d'une entreprise spin-off issue d'une université avec transfert de technologie et participation au capital.", templateType: 'pdf', classe: 'B', active: true, popularity: 68,
    fieldsJson: F([{key:'universite_spinoff',label:"Université fondatrice",type:'text',required:true},{key:'fondateurs',label:"Fondateurs de la spin-off",type:'text',required:true},{key:'technologie_transferee',label:"Technologie transférée",type:'textarea',required:true},{key:'participation_universite',label:"Participation de l'université (%)",type:'text',required:true},{key:'date_creation',label:"Date de création",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE SPIN-OFF UNIVERSITAIRE</h1><p><strong>Université :</strong> {{universite_spinoff}}</p><p><strong>Fondateurs :</strong> {{fondateurs}}</p><h2>Technologie transférée</h2><p>{{technologie_transferee}}</p><p><strong>Participation université :</strong> {{participation_universite}}%</p><p><strong>Date de création :</strong> {{date_creation}}</p></div>` },

  { code: 'innov_convention_valorisation_recherche', name: "Convention de valorisation recherche", category: 'commercial_financier', price: 12000, priceMax: 36000,
    description: "Convention entre un organisme de recherche et un service de valorisation pour l'exploitation commerciale des résultats de recherche.", templateType: 'pdf', classe: 'B', active: true, popularity: 64,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire ou équipe de recherche",type:'text',required:true},{key:'service_valorisation',label:"Service de valorisation",type:'text',required:true},{key:'resultats_valoriser',label:"Résultats à valoriser",type:'textarea',required:true},{key:'plan_valorisation',label:"Plan de valorisation",type:'textarea',required:true},{key:'date_convention',label:"Date de la convention",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE VALORISATION DE LA RECHERCHE</h1><p><strong>Laboratoire :</strong> {{laboratoire}}</p><p><strong>Service de valorisation :</strong> {{service_valorisation}}</p><h2>Résultats</h2><p>{{resultats_valoriser}}</p><h2>Plan</h2><p>{{plan_valorisation}}</p><p><strong>Date :</strong> {{date_convention}}</p></div>` },

  { code: 'innov_accord_partage_revenus', name: "Accord de partage de revenus innovation", category: 'commercial_financier', price: 9000, priceMax: 27000,
    description: "Accord définissant les modalités de partage des revenus générés par une innovation entre ses différents contributeurs.", templateType: 'pdf', classe: 'B', active: true, popularity: 74,
    fieldsJson: F([{key:'contributeur_principal',label:"Contributeur principal",type:'text',required:true},{key:'autres_contributeurs',label:"Autres contributeurs",type:'textarea',required:true},{key:'innovation_source',label:"Innovation génératrice de revenus",type:'text',required:true},{key:'cles_repartition',label:"Clés de répartition des revenus",type:'textarea',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE PARTAGE DE REVENUS INNOVATION</h1><p><strong>Contributeur principal :</strong> {{contributeur_principal}}</p><h2>Autres contributeurs</h2><p>{{autres_contributeurs}}</p><p><strong>Innovation :</strong> {{innovation_source}}</p><h2>Clés de répartition</h2><p>{{cles_repartition}}</p><p><strong>Date :</strong> {{date_accord}}</p></div>` },

  { code: 'innov_contrat_service_rd', name: "Contrat de service de R&D", category: 'commercial_financier', price: 11000, priceMax: 33000,
    description: "Contrat de prestation de services de recherche et développement entre un client et un organisme spécialisé avec livrables et jalons définis.", templateType: 'pdf', classe: 'B', active: true, popularity: 71,
    fieldsJson: F([{key:'client_rd',label:"Client",type:'text',required:true},{key:'organisme_rd',label:"Organisme R&D prestataire",type:'text',required:true},{key:'programme_rd',label:"Programme R&D",type:'textarea',required:true},{key:'budget_rd',label:"Budget R&D (FCFA)",type:'text',required:true},{key:'date_fin',label:"Date de fin",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE R&D</h1><p><strong>Client :</strong> {{client_rd}}</p><p><strong>Prestataire R&D :</strong> {{organisme_rd}}</p><h2>Programme</h2><p>{{programme_rd}}</p><p><strong>Budget :</strong> {{budget_rd}} FCFA</p><p><strong>Fin :</strong> {{date_fin}}</p></div>` },

  { code: 'innov_convention_cluster_tech', name: "Convention de cluster technologique", category: 'commercial_financier', price: 10000, priceMax: 30000,
    description: "Convention d'adhésion et de participation à un cluster technologique sectoriel pour bénéficier des ressources mutualisées et des synergies.", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'cluster',label:"Cluster technologique",type:'text',required:true},{key:'membre_adherent',label:"Membre adhérent",type:'text',required:true},{key:'secteur_cluster',label:"Secteur du cluster",type:'text',required:true},{key:'cotisation_annuelle',label:"Cotisation annuelle (FCFA)",type:'text',required:true},{key:'date_adhesion',label:"Date d'adhésion",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE CLUSTER TECHNOLOGIQUE</h1><p><strong>Cluster :</strong> {{cluster}}</p><p><strong>Adhérent :</strong> {{membre_adherent}}</p><p><strong>Secteur :</strong> {{secteur_cluster}}</p><p><strong>Cotisation :</strong> {{cotisation_annuelle}} FCFA/an</p><p><strong>Adhésion :</strong> {{date_adhesion}}</p></div>` },

  { code: 'innov_accord_zone_franche_tech', name: "Accord de zone franche technologique", category: 'commercial_financier', price: 14000, priceMax: 42000,
    description: "Accord d'installation et d'exploitation d'une entreprise tech dans une zone franche technologique avec avantages fiscaux et douaniers.", templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([{key:'autorite_zone',label:"Autorité de la zone franche",type:'text',required:true},{key:'entreprise_installante',label:"Entreprise s'installant",type:'text',required:true},{key:'activite_tech',label:"Activité technologique exercée",type:'textarea',required:true},{key:'avantages_accordes',label:"Avantages accordés",type:'textarea',required:true},{key:'date_installation',label:"Date d'installation",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE ZONE FRANCHE TECHNOLOGIQUE</h1><p><strong>Autorité :</strong> {{autorite_zone}}</p><p><strong>Entreprise :</strong> {{entreprise_installante}}</p><h2>Activité</h2><p>{{activite_tech}}</p><h2>Avantages</h2><p>{{avantages_accordes}}</p><p><strong>Installation :</strong> {{date_installation}}</p></div>` },

  { code: 'innov_rapport_annuel_innovation', name: "Rapport d'innovation annuel", category: 'commercial_financier', price: 12000, priceMax: 36000,
    description: "Rapport annuel structuré présentant les activités d'innovation, les investissements R&D et les résultats d'une entreprise ou institution.", templateType: 'pdf', classe: 'B', active: true, popularity: 76,
    fieldsJson: F([{key:'entite_rapportante',label:"Entité rapportante",type:'text',required:true},{key:'annee_rapport',label:"Année du rapport",type:'text',required:true},{key:'projets_innovation',label:"Projets d'innovation réalisés",type:'textarea',required:true},{key:'budget_rd_annuel',label:"Budget R&D annuel (FCFA)",type:'text',required:true},{key:'date_rapport',label:"Date du rapport",type:'date',required:true}]),
    body: `<div class="doc"><h1>RAPPORT D'INNOVATION ANNUEL {{annee_rapport}}</h1><p><strong>Entité :</strong> {{entite_rapportante}}</p><h2>Projets d'innovation</h2><p>{{projets_innovation}}</p><p><strong>Budget R&D :</strong> {{budget_rd_annuel}} FCFA</p><p><strong>Établi le :</strong> {{date_rapport}}</p></div>` },

  { code: 'innov_charte_innovateur', name: "Charte de l'innovateur", category: 'commercial_financier', price: 3000, priceMax: 9000,
    description: "Charte définissant les valeurs, principes et engagements des membres d'une communauté d'innovateurs au sein d'une organisation.", templateType: 'pdf', classe: 'B', active: true, popularity: 78,
    fieldsJson: F([{key:'organisation',label:"Organisation émettrice",type:'text',required:true},{key:'signataire',label:"Nom du signataire",type:'text',required:true},{key:'valeurs_innovation',label:"Valeurs d'innovation de l'organisation",type:'textarea',required:true},{key:'engagements',label:"Engagements de l'innovateur",type:'textarea',required:true},{key:'date_signature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>CHARTE DE L'INNOVATEUR</h1><p><strong>Organisation :</strong> {{organisation}}</p><p><strong>Signataire :</strong> {{signataire}}</p><h2>Nos valeurs</h2><p>{{valeurs_innovation}}</p><h2>Mes engagements</h2><p>{{engagements}}</p><p><strong>Signé le :</strong> {{date_signature}}</p></div>` },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 22b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
