import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  {
    code: 'paie_bulletin_standard',
    name: "Bulletin de paie standard (SYSCOHADA)",
    category: 'rh_emploi',
    price: 3000,
    priceMax: 9000,
    description: "Bulletin de paie conforme au plan comptable SYSCOHADA pour salaries en Cote d'Ivoire, avec calcul CNPS et IRPP.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 90,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'matricule', label: "Matricule", type: 'text', required: true },
      { key: 'periode_paie', label: "Periode de paie", type: 'text', required: true },
      { key: 'salaire_base', label: "Salaire de base (FCFA)", type: 'text', required: true },
      { key: 'nom_employeur', label: "Raison sociale employeur", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>BULLETIN DE PAIE</h1><p><strong>Employeur :</strong> {{nom_employeur}}</p><p><strong>Employe :</strong> {{nom_employe}} | Matricule : {{matricule}}</p><p><strong>Periode :</strong> {{periode_paie}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Libelle</th><th>Base</th><th>Taux</th><th>Montant</th></tr><tr><td>Salaire de base</td><td>{{salaire_base}}</td><td>-</td><td>{{salaire_base}}</td></tr><tr><td>Cotisation CNPS (employe 6,3%)</td><td>{{salaire_base}}</td><td>6,3%</td><td>-</td></tr><tr><td>IRPP (calcul progressif)</td><td>-</td><td>-</td><td>-</td></tr></table><p>Document etabli conformement au droit du travail ivoirien et au referentiel SYSCOHADA.</p></div>`,
  },
  {
    code: 'paie_bulletin_cadre_expatrie',
    name: "Bulletin de paie cadre expatrie",
    category: 'rh_emploi',
    price: 5000,
    priceMax: 15000,
    description: "Bulletin de paie pour cadre expatrie avec traitement des avantages en nature, frais de logement, billet d'avion et fiscalite specifique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_expatrie', label: "Nom et prenoms du cadre expatrie", type: 'text', required: true },
      { key: 'nationalite', label: "Nationalite", type: 'text', required: true },
      { key: 'salaire_base_devise', label: "Salaire de base (devise et montant)", type: 'text', required: true },
      { key: 'avantages_nature', label: "Avantages en nature (logement, vehicule...)", type: 'textarea', required: false },
      { key: 'periode_paie', label: "Periode de paie", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>BULLETIN DE PAIE - CADRE EXPATRIE</h1><p><strong>Employe :</strong> {{nom_expatrie}} | Nationalite : {{nationalite}}</p><p><strong>Periode :</strong> {{periode_paie}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Rubrique</th><th>Montant</th></tr><tr><td>Salaire de base</td><td>{{salaire_base_devise}}</td></tr><tr><td>Avantages en nature</td><td>{{avantages_nature}}</td></tr><tr><td>Indemnite d'expatriation</td><td>A calculer</td></tr><tr><td>Retenues fiscales (convention fiscale applicable)</td><td>A calculer</td></tr></table><p>Etabli conformement aux conventions fiscales bilaterales et au Code du Travail ivoirien.</p></div>`,
  },
  {
    code: 'paie_fiche_irpp',
    name: "Fiche de calcul de l'IRPP salarie",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7500,
    description: "Fiche de calcul detaille de l'Impot sur le Revenu des Personnes Physiques (IRPP) pour salaries, avec bareme progressif ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_salarie', label: "Nom et prenoms du salarie", type: 'text', required: true },
      { key: 'salaire_brut_imposable', label: "Salaire brut imposable (FCFA)", type: 'text', required: true },
      { key: 'nombre_parts', label: "Nombre de parts fiscales", type: 'text', required: true },
      { key: 'annee_fiscale', label: "Annee fiscale", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE CALCUL IRPP SALARIE</h1><p><strong>Salarie :</strong> {{nom_salarie}} | Annee : {{annee_fiscale}}</p><p><strong>Salaire brut imposable :</strong> {{salaire_brut_imposable}} FCFA</p><p><strong>Nombre de parts :</strong> {{nombre_parts}}</p><h2>Bareme progressif IRPP (Cote d'Ivoire)</h2><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Tranche de revenu</th><th>Taux</th><th>Impot</th></tr><tr><td>0 - 600 000</td><td>0%</td><td>0</td></tr><tr><td>600 001 - 1 500 000</td><td>10%</td><td>A calculer</td></tr><tr><td>1 500 001 - 4 000 000</td><td>20%</td><td>A calculer</td></tr><tr><td>Au-dela de 4 000 000</td><td>35%</td><td>A calculer</td></tr></table><p>Calcul effectue conformement au Code General des Impots de Cote d'Ivoire.</p></div>`,
  },
  {
    code: 'paie_declaration_mensuelle_dgi',
    name: "Declaration mensuelle employeur DGI (retenues a la source)",
    category: 'rh_emploi',
    price: 3500,
    priceMax: 10000,
    description: "Declaration mensuelle des retenues a la source effectuees par l'employeur a remettre a la Direction Generale des Impots (DGI).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'employeur", type: 'text', required: true },
      { key: 'numero_contribuable', label: "Numero de contribuable DGI", type: 'text', required: true },
      { key: 'mois_declaration', label: "Mois de declaration (MM/AAAA)", type: 'text', required: true },
      { key: 'total_irpp', label: "Total IRPP retenu (FCFA)", type: 'text', required: true },
      { key: 'effectif_salarie', label: "Effectif salarie du mois", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>DECLARATION MENSUELLE EMPLOYEUR - DGI</h1><p><strong>Employeur :</strong> {{raison_sociale}}</p><p><strong>Numero contribuable :</strong> {{numero_contribuable}}</p><p><strong>Mois :</strong> {{mois_declaration}} | <strong>Effectif :</strong> {{effectif_salarie}} salaries</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Nature de la retenue</th><th>Montant (FCFA)</th></tr><tr><td>IRPP retenu a la source</td><td>{{total_irpp}}</td></tr><tr><td>IMF (Impot Minimum Forfaitaire)</td><td>A renseigner</td></tr><tr><td>Total verse a la DGI</td><td>A calculer</td></tr></table><p>Declaration etablie conformement au Code General des Impots de Cote d'Ivoire.</p></div>`,
  },
  {
    code: 'paie_etat_mensuel_journal',
    name: "Etats de paie mensuel (journal de paie)",
    category: 'rh_emploi',
    price: 3000,
    priceMax: 9000,
    description: "Journal de paie mensuel recapitulant l'ensemble des remunerations, cotisations et charges sociales de l'entreprise pour le mois.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'mois_paie', label: "Mois de paie", type: 'text', required: true },
      { key: 'masse_salariale_brute', label: "Masse salariale brute totale (FCFA)", type: 'text', required: true },
      { key: 'nombre_employes', label: "Nombre total d'employes payes", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>JOURNAL DE PAIE MENSUEL</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>Mois :</strong> {{mois_paie}}</p><p><strong>Effectif paye :</strong> {{nombre_employes}} | <strong>Masse salariale brute :</strong> {{masse_salariale_brute}} FCFA</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>N</th><th>Nom et Prenoms</th><th>Categorie</th><th>Salaire Brut</th><th>Cotisations Salariales</th><th>IRPP</th><th>Net a Payer</th></tr><tr><td>1</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table><p>Ce journal constitue la base comptable pour l'enregistrement des charges de personnel.</p></div>`,
  },
  {
    code: 'paie_bordereau_cnps',
    name: "Bordereau de versement des cotisations CNPS",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7000,
    description: "Bordereau officiel de versement des cotisations sociales a la Caisse Nationale de Prevoyance Sociale (CNPS) de Cote d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'employeur", type: 'text', required: true },
      { key: 'numero_cnps', label: "Numero d'immatriculation CNPS", type: 'text', required: true },
      { key: 'periode_cotisation', label: "Periode de cotisation (MM/AAAA)", type: 'text', required: true },
      { key: 'salaire_brut_total', label: "Masse salariale brute soumise a cotisation (FCFA)", type: 'text', required: true },
      { key: 'total_cotisations', label: "Total cotisations dues (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>BORDEREAU DE VERSEMENT CNPS</h1><p><strong>Employeur :</strong> {{raison_sociale}}</p><p><strong>N CNPS :</strong> {{numero_cnps}} | <strong>Periode :</strong> {{periode_cotisation}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Nature de cotisation</th><th>Taux patronal</th><th>Taux salarial</th><th>Assiette</th><th>Montant</th></tr><tr><td>Accident du travail</td><td>2% a 5%</td><td>-</td><td>{{salaire_brut_total}}</td><td>A calculer</td></tr><tr><td>Retraite</td><td>7,7%</td><td>6,3%</td><td>{{salaire_brut_total}}</td><td>A calculer</td></tr><tr><td>Prestations familiales</td><td>5,75%</td><td>-</td><td>{{salaire_brut_total}}</td><td>A calculer</td></tr><tr><td><strong>TOTAL</strong></td><td>-</td><td>-</td><td>-</td><td><strong>{{total_cotisations}}</strong></td></tr></table></div>`,
  },
  {
    code: 'paie_livre_paie',
    name: "Livre de paie de l'entreprise",
    category: 'rh_emploi',
    price: 4000,
    priceMax: 12000,
    description: "Livre de paie annuel de l'entreprise, registre obligatoire retraçant l'ensemble des bulletins de paie emis conformement au Code du Travail ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'annee_exercice', label: "Annee d'exercice", type: 'text', required: true },
      { key: 'responsable_paie', label: "Responsable paie", type: 'text', required: true },
      { key: 'adresse_siege', label: "Adresse du siege social", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>LIVRE DE PAIE</h1><p><strong>Entreprise :</strong> {{raison_sociale}}</p><p><strong>Adresse :</strong> {{adresse_siege}}</p><p><strong>Annee :</strong> {{annee_exercice}} | <strong>Responsable paie :</strong> {{responsable_paie}}</p><p>Ce registre est tenu conformement a l'article 31.1 du Code du Travail de Cote d'Ivoire. Il recense chronologiquement tous les paiements effectues au profit des salaries.</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Mois</th><th>N Bulletin</th><th>Nom Salarie</th><th>Salaire Brut</th><th>Charges Sociales</th><th>Net Paye</th><th>Mode Paiement</th></tr><tr><td>Janvier</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td><td>...</td></tr></table></div>`,
  },
  {
    code: 'paie_fiche_absences_conges',
    name: "Fiche de suivi des absences et conges",
    category: 'rh_emploi',
    price: 2000,
    priceMax: 6000,
    description: "Fiche individuelle de suivi des absences, conges payes, conges maladie et autres indisponibilites du salarie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'poste', label: "Poste occupe", type: 'text', required: true },
      { key: 'annee_suivi', label: "Annee de suivi", type: 'text', required: true },
      { key: 'solde_conges_ouverts', label: "Solde de conges payes ouverts (jours)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE SUIVI DES ABSENCES ET CONGES</h1><p><strong>Employe :</strong> {{nom_employe}} | <strong>Poste :</strong> {{poste}}</p><p><strong>Annee :</strong> {{annee_suivi}} | <strong>Solde initial :</strong> {{solde_conges_ouverts}} jours</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Date debut</th><th>Date fin</th><th>Nb jours</th><th>Type d'absence</th><th>Justificatif</th><th>Solde restant</th></tr><tr><td>-</td><td>-</td><td>-</td><td>Conge paye / Maladie / Evenement familial</td><td>-</td><td>-</td></tr></table><p>Conges payes acquis : 2,5 jours par mois de travail effectif (30 jours par an).</p></div>`,
  },
  {
    code: 'paie_note_frais_pro',
    name: "Note de frais professionnels",
    category: 'rh_emploi',
    price: 1500,
    priceMax: 5000,
    description: "Formulaire de note de frais professionnels pour remboursement des depenses engagees par un salarie dans le cadre de son activite.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'nom_salarie', label: "Nom et prenoms du salarie", type: 'text', required: true },
      { key: 'service', label: "Service / Departement", type: 'text', required: true },
      { key: 'periode_frais', label: "Periode concernee", type: 'text', required: true },
      { key: 'objet_mission', label: "Objet de la mission", type: 'textarea', required: true },
      { key: 'total_reclame', label: "Total reclame (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>NOTE DE FRAIS PROFESSIONNELS</h1><p><strong>Salarie :</strong> {{nom_salarie}} | <strong>Service :</strong> {{service}}</p><p><strong>Periode :</strong> {{periode_frais}} | <strong>Mission :</strong> {{objet_mission}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Date</th><th>Nature de la depense</th><th>Beneficiaire</th><th>Justificatif</th><th>Montant (FCFA)</th></tr><tr><td>-</td><td>Transport / Repas / Hebergement / Autre</td><td>-</td><td>Facture / Recu</td><td>-</td></tr></table><p><strong>Total reclame : {{total_reclame}} FCFA</strong></p><p>Signature du salarie : _________________ | Visa du responsable : _________________</p></div>`,
  },
  {
    code: 'paie_remboursement_frais',
    name: "Fiche de remboursement de frais",
    category: 'rh_emploi',
    price: 1500,
    priceMax: 4500,
    description: "Ordre de remboursement officiel des frais professionnels valides, avec autorisation de virement sur le compte du salarie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_salarie', label: "Nom et prenoms du beneficiaire", type: 'text', required: true },
      { key: 'rib_banque', label: "RIB / Banque du salarie", type: 'text', required: true },
      { key: 'montant_rembourse', label: "Montant a rembourser (FCFA)", type: 'text', required: true },
      { key: 'date_paiement', label: "Date de paiement prevue", type: 'date', required: true },
      { key: 'reference_note_frais', label: "Reference de la note de frais", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ORDRE DE REMBOURSEMENT DE FRAIS</h1><p><strong>Beneficiaire :</strong> {{nom_salarie}}</p><p><strong>Banque / RIB :</strong> {{rib_banque}}</p><p><strong>Montant :</strong> {{montant_rembourse}} FCFA</p><p><strong>Reference note de frais :</strong> {{reference_note_frais}}</p><p><strong>Date de paiement :</strong> {{date_paiement}}</p><p>Autorise par la Direction Administrative et Financiere.</p><p>Signature DAF : _________________ | Date : _________________</p></div>`,
  },
  {
    code: 'paie_pret_employe',
    name: "Accord de pret a un employe (avance sur salaire)",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7000,
    description: "Contrat d'avance sur salaire ou de pret interne accorde par l'employeur a un salarie, avec conditions de remboursement par deductions sur paie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'montant_pret', label: "Montant du pret (FCFA)", type: 'text', required: true },
      { key: 'nombre_echeances', label: "Nombre d'echeances de remboursement", type: 'text', required: true },
      { key: 'date_premier_prelevement', label: "Date du premier prelevement", type: 'date', required: true },
      { key: 'motif_pret', label: "Motif du pret", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRET EMPLOYEUR - SALARIE</h1><p>Entre l'entreprise, ci-apres denominee "l'Employeur", et <strong>{{nom_employe}}</strong>, ci-apres denomme "l'Employe".</p><h2>Article 1 - Montant du pret</h2><p>L'Employeur accorde a l'Employe un pret de <strong>{{montant_pret}} FCFA</strong>.</p><h2>Article 2 - Remboursement</h2><p>Le remboursement s'effectuera en <strong>{{nombre_echeances}}</strong> echeances mensuelles egalees, par deduction sur le bulletin de paie a compter du <strong>{{date_premier_prelevement}}</strong>.</p><h2>Article 3 - Motif</h2><p>{{motif_pret}}</p><p>Fait en double exemplaire. Signature Employeur : _________________ | Signature Employe : _________________</p></div>`,
  },
  {
    code: 'paie_attestation_salaire_banque',
    name: "Attestation de salaire pour banque",
    category: 'rh_emploi',
    price: 1500,
    priceMax: 4500,
    description: "Attestation officielle de salaire destinee aux etablissements bancaires pour ouverture de compte, credit ou autres demarches financieres.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 92,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'poste', label: "Poste et qualite", type: 'text', required: true },
      { key: 'salaire_net', label: "Salaire net mensuel (FCFA)", type: 'text', required: true },
      { key: 'date_embauche', label: "Date d'embauche", type: 'date', required: true },
      { key: 'nom_banque_destinataire', label: "Banque destinataire", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ATTESTATION DE SALAIRE</h1><p>Je soussigne(e), representant legal de la societe, atteste par la presente que :</p><p><strong>{{nom_employe}}</strong>, occupe le poste de <strong>{{poste}}</strong> au sein de notre entreprise depuis le <strong>{{date_embauche}}</strong>.</p><p>Sa remuneration nette mensuelle est de <strong>{{salaire_net}} FCFA</strong>.</p><p>Cette attestation est delivree a la demande de l'interesse(e) pour etre produite aupres de <strong>{{nom_banque_destinataire}}</strong> et ne vaut que pour ce qu'elle porte.</p><p>Fait a Abidjan, le ___________</p><p>Le Directeur General</p><p>Signature et cachet : _________________</p></div>`,
  },
  {
    code: 'paie_attestation_salaire_bail',
    name: "Attestation de salaire pour bail locatif",
    category: 'rh_emploi',
    price: 1500,
    priceMax: 4500,
    description: "Attestation de salaire pour justifier la solvabilite d'un salarie aupres d'un bailleur dans le cadre d'une location immobiliere.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'poste', label: "Poste occupe", type: 'text', required: true },
      { key: 'salaire_net', label: "Salaire net mensuel (FCFA)", type: 'text', required: true },
      { key: 'type_contrat', label: "Type de contrat (CDI/CDD)", type: 'text', required: true },
      { key: 'nom_bailleur', label: "Nom du bailleur / agence immobiliere", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ATTESTATION DE SALAIRE - BAIL LOCATIF</h1><p>La societe soussignee certifie que <strong>{{nom_employe}}</strong>, employe(e) en qualite de <strong>{{poste}}</strong> sous contrat <strong>{{type_contrat}}</strong>, percoit une remuneration nette mensuelle de <strong>{{salaire_net}} FCFA</strong>.</p><p>Cette attestation est delivree a la demande de l'interesse(e) pour etre remise a <strong>{{nom_bailleur}}</strong> dans le cadre de sa recherche de logement.</p><p>La societe ne saurait etre tenue responsable des engagements prises par le salarie au titre de son bail locatif.</p><p>Fait a Abidjan, le ___________</p><p>Le Directeur des Ressources Humaines : _________________</p></div>`,
  },
  {
    code: 'paie_calcul_13eme_mois',
    name: "Fiche de calcul du 13eme mois",
    category: 'rh_emploi',
    price: 2000,
    priceMax: 6000,
    description: "Fiche de calcul de la prime de 13eme mois (gratification annuelle) par salarie, avec proratisation en cas d'annee incomplete.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'salaire_base_mensuel', label: "Salaire de base mensuel (FCFA)", type: 'text', required: true },
      { key: 'mois_presence', label: "Nombre de mois de presence dans l'annee", type: 'text', required: true },
      { key: 'annee_calcul', label: "Annee de calcul", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE CALCUL DU 13EME MOIS</h1><p><strong>Employe :</strong> {{nom_employe}} | <strong>Annee :</strong> {{annee_calcul}}</p><p><strong>Salaire de base mensuel :</strong> {{salaire_base_mensuel}} FCFA</p><p><strong>Mois de presence :</strong> {{mois_presence}} / 12</p><h2>Formule de calcul</h2><p>13eme mois = Salaire de base mensuel x (Mois de presence / 12)</p><p>Montant du 13eme mois = {{salaire_base_mensuel}} x ({{mois_presence}} / 12) = <strong>A calculer</strong> FCFA</p><p>Note : la prime de 13eme mois n'est pas legalement obligatoire mais peut etre prevue par convention collective ou accord d'entreprise.</p><p>Visa DRH : _________________ | Visa DAF : _________________</p></div>`,
  },
  {
    code: 'paie_calcul_heures_sup',
    name: "Fiche de calcul des heures supplementaires",
    category: 'rh_emploi',
    price: 2000,
    priceMax: 6000,
    description: "Fiche de calcul des majorations pour heures supplementaires conformement au Code du Travail ivoirien (41h a 48h : +15%, au-dela : +50%, nuit et dimanche : majorations specifiques).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'taux_horaire', label: "Taux horaire de base (FCFA)", type: 'text', required: true },
      { key: 'heures_sup_semaine', label: "Heures supplementaires effectuees", type: 'text', required: true },
      { key: 'periode', label: "Periode concernee", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE CALCUL DES HEURES SUPPLEMENTAIRES</h1><p><strong>Employe :</strong> {{nom_employe}} | <strong>Periode :</strong> {{periode}}</p><p><strong>Taux horaire de base :</strong> {{taux_horaire}} FCFA/h</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Type d'heures</th><th>Nombre d'heures</th><th>Majoration</th><th>Montant</th></tr><tr><td>41h a 48h (semaine)</td><td>{{heures_sup_semaine}}</td><td>+15%</td><td>A calculer</td></tr><tr><td>Au-dela de 48h</td><td>-</td><td>+50%</td><td>A calculer</td></tr><tr><td>Heures de nuit</td><td>-</td><td>+75%</td><td>A calculer</td></tr><tr><td>Dimanche et jours feries</td><td>-</td><td>+100%</td><td>A calculer</td></tr></table><p>Durée légale de travail : 40h/semaine (art. 21.1 Code du Travail CI).</p></div>`,
  },
  {
    code: 'paie_calcul_icrp',
    name: "Fiche de calcul de l'indemnite de depart (ICRP)",
    category: 'rh_emploi',
    price: 3000,
    priceMax: 9000,
    description: "Fiche de calcul de l'Indemnite Compensatrice de Rupture du contrat de travail (ICRP) et de l'indemnite de licenciement conformement au Code du Travail OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'date_embauche', label: "Date d'embauche", type: 'date', required: true },
      { key: 'date_depart', label: "Date de depart", type: 'date', required: true },
      { key: 'salaire_moyen_12mois', label: "Salaire moyen des 12 derniers mois (FCFA)", type: 'text', required: true },
      { key: 'motif_rupture', label: "Motif de la rupture du contrat", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE CALCUL - INDEMNITE DE DEPART (ICRP)</h1><p><strong>Employe :</strong> {{nom_employe}}</p><p><strong>Date d'embauche :</strong> {{date_embauche}} | <strong>Date de depart :</strong> {{date_depart}}</p><p><strong>Motif :</strong> {{motif_rupture}}</p><p><strong>Salaire de reference (moyenne 12 mois) :</strong> {{salaire_moyen_12mois}} FCFA</p><h2>Calcul de l'anciennete</h2><p>Anciennete = Date de depart - Date d'embauche = A calculer (annees, mois)</p><h2>Barème ICRP (Cote d'Ivoire)</h2><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Tranche d'anciennete</th><th>Taux/an</th></tr><tr><td>1 a 5 ans</td><td>30% du salaire mensuel</td></tr><tr><td>6 a 10 ans</td><td>35% du salaire mensuel</td></tr><tr><td>Au-dela de 10 ans</td><td>40% du salaire mensuel</td></tr></table><p>ICRP totale = A calculer sur la base du bareme applicable.</p></div>`,
  },
  {
    code: 'paie_calcul_conges_payes',
    name: "Fiche de calcul des conges payes",
    category: 'rh_emploi',
    price: 2000,
    priceMax: 6000,
    description: "Fiche de calcul des droits aux conges payes et de l'indemnite compensatrice de conges, conformement au Code du Travail de Cote d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'date_reference', label: "Periode de reference (du/au)", type: 'text', required: true },
      { key: 'jours_acquis', label: "Nombre de jours de conges acquis", type: 'text', required: true },
      { key: 'salaire_moyen', label: "Salaire moyen mensuel de reference (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE CALCUL DES CONGES PAYES</h1><p><strong>Employe :</strong> {{nom_employe}} | <strong>Periode de reference :</strong> {{date_reference}}</p><p><strong>Jours de conges acquis :</strong> {{jours_acquis}} jours</p><p><strong>Salaire moyen mensuel :</strong> {{salaire_moyen}} FCFA</p><h2>Calcul de l'indemnite de conges payes</h2><p>Regles applicables en CI : 2,5 jours ouvrables par mois de travail effectif, soit 30 jours par an.</p><p>Methode : 1/10 des remunerations perçues pendant la periode de reference, ou salaire journalier x nombre de jours (la plus favorable est retenue).</p><p>Indemnite de conges = A calculer</p><p>Visa DRH : _________________ Date de depart en conge : _________________</p></div>`,
  },
  {
    code: 'paie_bulletin_saisie_arret',
    name: "Bulletin de paie en cas de saisie-arret",
    category: 'rh_emploi',
    price: 3000,
    priceMax: 9000,
    description: "Bulletin de paie specifique integrant le traitement d'une saisie-arret sur salaire notifiee par voie judiciaire, avec calcul de la quotite saisissable.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'reference_saisie', label: "Reference de l'ordonnance de saisie-arret", type: 'text', required: true },
      { key: 'montant_saisie', label: "Montant de la saisie (FCFA)", type: 'text', required: true },
      { key: 'salaire_net_avant_saisie', label: "Salaire net avant saisie (FCFA)", type: 'text', required: true },
      { key: 'periode_paie', label: "Periode de paie", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>BULLETIN DE PAIE - SAISIE-ARRET</h1><p><strong>Employe :</strong> {{nom_employe}} | <strong>Periode :</strong> {{periode_paie}}</p><p><strong>Reference ordonnance :</strong> {{reference_saisie}}</p><p><strong>Salaire net avant saisie :</strong> {{salaire_net_avant_saisie}} FCFA</p><h2>Calcul de la quotite saisissable</h2><p>Conformement aux dispositions legales, une fraction du salaire est insaisissable pour garantir un minimum vital.</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Element</th><th>Montant</th></tr><tr><td>Salaire net</td><td>{{salaire_net_avant_saisie}}</td></tr><tr><td>Quotite saisissable (calculee)</td><td>A calculer</td></tr><tr><td>Montant retenu au titre de la saisie</td><td>{{montant_saisie}}</td></tr><tr><td>Net verse a l'employe</td><td>A calculer</td></tr></table></div>`,
  },
  {
    code: 'paie_recap_annuel_fiscal',
    name: "Recapitulatif annuel de paie (attestation fiscale)",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7500,
    description: "Recapitulatif annuel des remunerations et retenues fiscales servant d'attestation pour la declaration d'impot du salarie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'annee_fiscale', label: "Annee fiscale", type: 'text', required: true },
      { key: 'total_brut_annuel', label: "Total salaire brut annuel (FCFA)", type: 'text', required: true },
      { key: 'total_irpp_preleve', label: "Total IRPP preleve sur l'annee (FCFA)", type: 'text', required: true },
      { key: 'total_cnps_salarie', label: "Total cotisations CNPS salariales (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RECAPITULATIF ANNUEL DE PAIE - ATTESTATION FISCALE</h1><p><strong>Salarie :</strong> {{nom_employe}} | <strong>Annee :</strong> {{annee_fiscale}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Rubrique</th><th>Montant annuel (FCFA)</th></tr><tr><td>Salaire brut total</td><td>{{total_brut_annuel}}</td></tr><tr><td>Cotisations CNPS (part salariale)</td><td>{{total_cnps_salarie}}</td></tr><tr><td>IRPP preleve</td><td>{{total_irpp_preleve}}</td></tr><tr><td>Salaire net total verse</td><td>A calculer</td></tr></table><p>Le present document vaut attestation de revenus salariaux aupres de l'administration fiscale ivoirienne.</p><p>Fait par l'employeur, cachet et signature : _________________</p></div>`,
  },
  {
    code: 'paie_fiche_temps_partiel',
    name: "Fiche de paie contrat a temps partiel",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7000,
    description: "Bulletin de paie adapte aux salaries a temps partiel avec calcul proporitionnel des cotisations et verification du SMIG minimum.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'duree_hebdomadaire', label: "Duree hebdomadaire contractuelle (heures)", type: 'text', required: true },
      { key: 'salaire_base_temps_partiel', label: "Salaire de base temps partiel (FCFA)", type: 'text', required: true },
      { key: 'periode_paie', label: "Periode de paie", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>BULLETIN DE PAIE - TEMPS PARTIEL</h1><p><strong>Employe :</strong> {{nom_employe}} | <strong>Periode :</strong> {{periode_paie}}</p><p><strong>Duree contractuelle :</strong> {{duree_hebdomadaire}} h/semaine (temps partiel)</p><p><strong>Salaire de base :</strong> {{salaire_base_temps_partiel}} FCFA</p><p>Proratisation : salaire = SMIG ou taux plein x (heures contractuelles / 40h)</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Rubrique</th><th>Montant</th></tr><tr><td>Salaire de base</td><td>{{salaire_base_temps_partiel}}</td></tr><tr><td>Cotisations CNPS (proportionnelles)</td><td>A calculer</td></tr><tr><td>IRPP</td><td>A calculer</td></tr><tr><td>Net a payer</td><td>A calculer</td></tr></table></div>`,
  },
  {
    code: 'paie_rapport_cout_masse_salariale',
    name: "Rapport de cout de la masse salariale",
    category: 'rh_emploi',
    price: 4000,
    priceMax: 12000,
    description: "Rapport mensuel ou annuel d'analyse du cout total de la masse salariale pour la Direction Generale, incluant charges directes et indirectes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'periode_rapport', label: "Periode du rapport", type: 'text', required: true },
      { key: 'effectif_moyen', label: "Effectif moyen sur la periode", type: 'text', required: true },
      { key: 'masse_salariale_brute', label: "Masse salariale brute totale (FCFA)", type: 'text', required: true },
      { key: 'charges_patronales_total', label: "Total charges patronales CNPS (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE COUT DE LA MASSE SALARIALE</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>Periode :</strong> {{periode_rapport}}</p><p><strong>Effectif moyen :</strong> {{effectif_moyen}} | <strong>Masse salariale brute :</strong> {{masse_salariale_brute}} FCFA</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Composante</th><th>Montant (FCFA)</th><th>% Masse salariale</th></tr><tr><td>Salaires bruts</td><td>{{masse_salariale_brute}}</td><td>100%</td></tr><tr><td>Charges CNPS patronales</td><td>{{charges_patronales_total}}</td><td>A calculer</td></tr><tr><td>Cout total personnel</td><td>A calculer</td><td>A calculer</td></tr></table><p>Ratio masse salariale / chiffre d'affaires : A calculer. Coût moyen par employe : A calculer.</p></div>`,
  },
  {
    code: 'paie_plan_controle_paie',
    name: "Plan de controle de la paie",
    category: 'rh_emploi',
    price: 3500,
    priceMax: 10000,
    description: "Grille de controle interne de la paie listant les verifications obligatoires avant emission des bulletins pour minimiser les erreurs et risques de non-conformite.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale", type: 'text', required: true },
      { key: 'mois_controle', label: "Mois controle", type: 'text', required: true },
      { key: 'responsable_controle', label: "Responsable du controle", type: 'text', required: true },
      { key: 'date_controle', label: "Date du controle", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE CONTROLE DE LA PAIE</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>Mois :</strong> {{mois_controle}}</p><p><strong>Responsable :</strong> {{responsable_controle}} | <strong>Date :</strong> {{date_controle}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Point de controle</th><th>Statut</th><th>Observations</th></tr><tr><td>Coherence effectifs paye vs RH</td><td>OK / NOK</td><td>-</td></tr><tr><td>Application des augmentations et decisions</td><td>OK / NOK</td><td>-</td></tr><tr><td>Calcul IRPP conforme bareme DGI</td><td>OK / NOK</td><td>-</td></tr><tr><td>Taux CNPS correct et a jour</td><td>OK / NOK</td><td>-</td></tr><tr><td>Heures supplementaires validees</td><td>OK / NOK</td><td>-</td></tr><tr><td>Retenues et avances correctement deduites</td><td>OK / NOK</td><td>-</td></tr></table><p>Conclusion : Visa du controleur : _________________</p></div>`,
  },
  {
    code: 'paie_accord_externalisation',
    name: "Accord de prestataire de paie externalisee",
    category: 'rh_emploi',
    price: 5000,
    priceMax: 15000,
    description: "Convention d'externalisation du traitement de la paie a un cabinet ou prestataire specialise, avec engagements de service, delais et confidentialite.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom de l'entreprise cliente", type: 'text', required: true },
      { key: 'nom_prestataire', label: "Nom du prestataire de paie", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut de la prestation", type: 'date', required: true },
      { key: 'effectif_gere', label: "Effectif salaries gere", type: 'text', required: true },
      { key: 'honoraires_mensuels', label: "Honoraires mensuels convenus (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRESTATION DE PAIE EXTERNALISEE</h1><p>Entre <strong>{{nom_client}}</strong> (le Client) et <strong>{{nom_prestataire}}</strong> (le Prestataire).</p><h2>Article 1 - Objet</h2><p>Le Prestataire prend en charge le traitement mensuel de la paie pour un effectif de <strong>{{effectif_gere}}</strong> salaries, a compter du <strong>{{date_debut}}</strong>.</p><h2>Article 2 - Prestations</h2><p>Etablissement des bulletins de paie, declarations CNPS et DGI, journal de paie, fichiers de virement, conseil en droit du travail.</p><h2>Article 3 - Honoraires</h2><p>Honoraires mensuels : <strong>{{honoraires_mensuels}} FCFA</strong> HT, reajustables annuellement.</p><h2>Article 4 - Confidentialite</h2><p>Le Prestataire s'engage a la stricte confidentialite des donnees salariales conformement a la loi ivoirienne sur la protection des donnees.</p><p>Signatures des parties : _________________</p></div>`,
  },
  {
    code: 'paie_convention_audit_paie',
    name: "Convention d'audit de la paie",
    category: 'rh_emploi',
    price: 6000,
    priceMax: 18000,
    description: "Convention de mission d'audit de la paie menee par un cabinet externe pour verifier la conformite des pratiques de remuneration et des declarations sociales et fiscales.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_entreprise', label: "Nom de l'entreprise auditee", type: 'text', required: true },
      { key: 'nom_cabinet_audit', label: "Nom du cabinet d'audit", type: 'text', required: true },
      { key: 'periode_auditee', label: "Periode auditee", type: 'text', required: true },
      { key: 'date_debut_mission', label: "Date de debut de la mission", type: 'date', required: true },
      { key: 'honoraires_audit', label: "Honoraires de la mission (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D'AUDIT DE LA PAIE</h1><p>Entre <strong>{{nom_entreprise}}</strong> et le cabinet <strong>{{nom_cabinet_audit}}</strong>.</p><h2>Objet de la mission</h2><p>Audit de conformite de la paie pour la periode <strong>{{periode_auditee}}</strong>, incluant : verification des calculs IRPP et CNPS, conformite avec la convention collective applicable, adequation des contrats de travail, conge payes, heures supplementaires et indemnites.</p><h2>Calendrier</h2><p>Debut de mission : <strong>{{date_debut_mission}}</strong>. Livraison du rapport : dans les 30 jours ouvrables suivants.</p><h2>Honoraires</h2><p>Honoraires convenus : <strong>{{honoraires_audit}} FCFA</strong> HT.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'paie_charte_confidentialite_donnees',
    name: "Charte de confidentialite des donnees de paie",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7500,
    description: "Charte interne definissant les regles d'acces, de traitement et de protection des donnees de paie et de remuneration des salaries.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'responsable_traitement', label: "Responsable du traitement des donnees (DRH/DAF)", type: 'text', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entree en vigueur", type: 'date', required: true },
      { key: 'version', label: "Numero de version", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE CONFIDENTIALITE DES DONNEES DE PAIE</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>Version :</strong> {{version}} | <strong>En vigueur le :</strong> {{date_entree_vigueur}}</p><p><strong>Responsable du traitement :</strong> {{responsable_traitement}}</p><h2>1. Perimetre</h2><p>La presente charte s'applique a toutes les donnees de remuneration, bulletins de paie, etats de paie et informations personnelles des salaries traitees dans le cadre de la gestion de la paie.</p><h2>2. Acces aux donnees</h2><p>L'acces aux donnees de paie est strictement limite aux personnes habilitees (DRH, DAF, paie externalisee sous contrat). Tout acces non autorise constitue une faute grave.</p><h2>3. Conservation</h2><p>Les donnees de paie sont conservees pendant 5 ans conformement aux prescriptions legales ivoiriennes.</p><h2>4. Engagement des signataires</h2><p>Signature du salarie habilite : _________________ | Date : _________________</p></div>`,
  },

  // ===== REC_ TEMPLATES (25) =====
  {
    code: 'rec_annonce_recrutement',
    name: "Annonce de recrutement (offre d'emploi)",
    category: 'rh_emploi',
    price: 1500,
    priceMax: 4500,
    description: "Modele d'offre d'emploi structuree pour diffusion sur les plateformes de recrutement en Afrique francophone, conforme aux pratiques OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 92,
    fieldsJson: F([
      { key: 'titre_poste', label: "Titre du poste", type: 'text', required: true },
      { key: 'nom_entreprise', label: "Nom de l'entreprise", type: 'text', required: true },
      { key: 'lieu_poste', label: "Lieu du poste", type: 'text', required: true },
      { key: 'description_poste', label: "Description du poste et missions principales", type: 'textarea', required: true },
      { key: 'profil_recherche', label: "Profil recherche (formation, experience, competences)", type: 'textarea', required: true },
      { key: 'date_limite', label: "Date limite de candidature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>OFFRE D'EMPLOI : {{titre_poste}}</h1><p><strong>Entreprise :</strong> {{nom_entreprise}} | <strong>Lieu :</strong> {{lieu_poste}}</p><h2>Description du poste</h2><p>{{description_poste}}</p><h2>Profil recherche</h2><p>{{profil_recherche}}</p><h2>Comment postuler</h2><p>Envoyer CV et lettre de motivation avant le <strong>{{date_limite}}</strong> a l'adresse indiquee. Seuls les candidats retenus seront contactes.</p></div>`,
  },
  {
    code: 'rec_fiche_poste_detaillee',
    name: "Fiche de poste detaillee",
    category: 'rh_emploi',
    price: 2000,
    priceMax: 6000,
    description: "Fiche de poste complete incluant missions, responsabilites, relations hierarchiques, competences requises et indicateurs de performance.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'intitule_poste', label: "Intitule du poste", type: 'text', required: true },
      { key: 'departement', label: "Departement / Direction", type: 'text', required: true },
      { key: 'superieur_hierarchique', label: "Superieur hierarchique direct", type: 'text', required: true },
      { key: 'missions_principales', label: "Missions et responsabilites principales", type: 'textarea', required: true },
      { key: 'competences_requises', label: "Competences et qualifications requises", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE POSTE</h1><p><strong>Intitule :</strong> {{intitule_poste}} | <strong>Departement :</strong> {{departement}}</p><p><strong>Responsable hierarchique :</strong> {{superieur_hierarchique}}</p><h2>Missions et responsabilites</h2><p>{{missions_principales}}</p><h2>Competences et qualifications</h2><p>{{competences_requises}}</p><h2>Indicateurs de performance (KPI)</h2><p>A definir avec le manager lors de la prise de poste.</p><p>Date de creation / revision : _________________ | Visa DRH : _________________</p></div>`,
  },
  {
    code: 'rec_grille_evaluation_candidats',
    name: "Grille d'evaluation des candidats",
    category: 'rh_emploi',
    price: 2000,
    priceMax: 6000,
    description: "Grille d'evaluation objective des candidats pour standardiser le processus de selection et garantir l'equite du recrutement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'titre_poste', label: "Titre du poste a pourvoir", type: 'text', required: true },
      { key: 'nom_candidat', label: "Nom et prenoms du candidat", type: 'text', required: true },
      { key: 'date_evaluation', label: "Date de l'evaluation", type: 'date', required: true },
      { key: 'nom_evaluateur', label: "Nom de l'evaluateur", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>GRILLE D'EVALUATION DES CANDIDATS</h1><p><strong>Poste :</strong> {{titre_poste}} | <strong>Candidat :</strong> {{nom_candidat}}</p><p><strong>Date :</strong> {{date_evaluation}} | <strong>Evaluateur :</strong> {{nom_evaluateur}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Critere</th><th>Poids</th><th>Note /5</th><th>Commentaires</th></tr><tr><td>Formation et diplomes</td><td>20%</td><td>-</td><td>-</td></tr><tr><td>Experience professionnelle</td><td>25%</td><td>-</td><td>-</td></tr><tr><td>Competences techniques</td><td>25%</td><td>-</td><td>-</td></tr><tr><td>Competences comportementales</td><td>20%</td><td>-</td><td>-</td></tr><tr><td>Motivation et projet professionnel</td><td>10%</td><td>-</td><td>-</td></tr></table><p><strong>Note finale : /5 | Decision : Retenu / En attente / Non retenu</strong></p></div>`,
  },
  {
    code: 'rec_guide_entretien_structure',
    name: "Guide d'entretien structure de recrutement",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7000,
    description: "Guide d'entretien structuré avec questions comportementales (methode STAR) pour evaluer les candidats de maniere objective et reproductible.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'titre_poste', label: "Titre du poste", type: 'text', required: true },
      { key: 'competences_cibles', label: "Competences behaviorales a evaluer", type: 'textarea', required: true },
      { key: 'duree_entretien', label: "Duree prevue de l'entretien", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>GUIDE D'ENTRETIEN STRUCTURE</h1><p><strong>Poste :</strong> {{titre_poste}} | <strong>Duree :</strong> {{duree_entretien}}</p><p><strong>Competences evaluees :</strong> {{competences_cibles}}</p><h2>Structure de l'entretien (methode STAR)</h2><ol><li><strong>Accueil et presentation</strong> (5 min) : Presentation de l'entreprise et du poste.</li><li><strong>Parcours du candidat</strong> (15 min) : "Pouvez-vous me decrire votre parcours ?"</li><li><strong>Questions comportementales</strong> (20 min) : "Decrivez une Situation, la Tache, l'Action menee et le Resultat obtenu."</li><li><strong>Questions techniques</strong> (10 min) : Specifiques au poste.</li><li><strong>Questions du candidat</strong> (10 min)</li></ol><p>Notes de l'evaluateur : _________________</p></div>`,
  },
  {
    code: 'rec_rapport_tri_cv',
    name: "Rapport de tri de CV",
    category: 'rh_emploi',
    price: 2000,
    priceMax: 6000,
    description: "Rapport de pre-selection des candidatures reçues apres publication d'une offre d'emploi, avec classement et justification des decisions.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'titre_poste', label: "Titre du poste", type: 'text', required: true },
      { key: 'nombre_candidatures_reçues', label: "Nombre de candidatures reçues", type: 'text', required: true },
      { key: 'nombre_retenus', label: "Nombre de candidats retenus pour entretien", type: 'text', required: true },
      { key: 'redacteur', label: "Redacteur du rapport", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE TRI DE CV</h1><p><strong>Poste :</strong> {{titre_poste}} | <strong>Date :</strong> {{date_rapport}}</p><p><strong>Redacteur :</strong> {{redacteur}}</p><p><strong>Candidatures reçues :</strong> {{nombre_candidatures_reçues}} | <strong>Retenus :</strong> {{nombre_retenus}}</p><h2>Criteres de tri</h2><ul><li>Formation minimale requise</li><li>Experience pertinente</li><li>Disponibilite</li><li>Adequation salariale</li></ul><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Nom candidat</th><th>Formation</th><th>Experience</th><th>Decision</th><th>Motif</th></tr><tr><td>-</td><td>-</td><td>-</td><td>Retenu / Refuse</td><td>-</td></tr></table></div>`,
  },
  {
    code: 'rec_compte_rendu_entretien',
    name: "Compte rendu d'entretien de recrutement",
    category: 'rh_emploi',
    price: 1500,
    priceMax: 4500,
    description: "Document de compte rendu detaille d'un entretien de recrutement, servant de reference pour la decision finale d'embauche.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'nom_candidat', label: "Nom et prenoms du candidat", type: 'text', required: true },
      { key: 'titre_poste', label: "Poste vise", type: 'text', required: true },
      { key: 'date_entretien', label: "Date de l'entretien", type: 'date', required: true },
      { key: 'evaluateurs', label: "Noms des evaluateurs", type: 'text', required: true },
      { key: 'synthese_evaluation', label: "Synthese de l'evaluation", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>COMPTE RENDU D'ENTRETIEN</h1><p><strong>Candidat :</strong> {{nom_candidat}} | <strong>Poste :</strong> {{titre_poste}}</p><p><strong>Date :</strong> {{date_entretien}} | <strong>Evaluateurs :</strong> {{evaluateurs}}</p><h2>Synthese</h2><p>{{synthese_evaluation}}</p><h2>Points forts</h2><p>A renseigner</p><h2>Points d'attention</h2><p>A renseigner</p><h2>Decision</h2><p>[ ] Retenu pour la phase suivante [ ] Embauche propose [ ] Non retenu</p><p>Signatures evaluateurs : _________________</p></div>`,
  },
  {
    code: 'rec_accord_mission_cabinet',
    name: "Accord de mission de cabinet de recrutement",
    category: 'rh_emploi',
    price: 5000,
    priceMax: 15000,
    description: "Convention de mission de recrutement confiee a un cabinet specialise, avec definition du mandat, des honoraires et de la garantie de remplacement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_client', label: "Nom de l'entreprise cliente", type: 'text', required: true },
      { key: 'nom_cabinet', label: "Nom du cabinet de recrutement", type: 'text', required: true },
      { key: 'titre_poste_recherche', label: "Titre du poste a pourvoir", type: 'text', required: true },
      { key: 'honoraires', label: "Honoraires convenus (FCFA ou % salaire annuel)", type: 'text', required: true },
      { key: 'delai_mission', label: "Delai de presentation des candidats (jours)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE MISSION DE RECRUTEMENT</h1><p>Entre <strong>{{nom_client}}</strong> (le Client) et <strong>{{nom_cabinet}}</strong> (le Cabinet).</p><h2>Article 1 - Objet</h2><p>Le Cabinet est mandate pour identifier et presenter des candidats qualifies pour le poste de <strong>{{titre_poste_recherche}}</strong>.</p><h2>Article 2 - Delai</h2><p>Le Cabinet s'engage a presenter des candidats dans un delai de <strong>{{delai_mission}}</strong> jours ouvrables.</p><h2>Article 3 - Honoraires</h2><p>Honoraires : <strong>{{honoraires}}</strong>. Factures a l'embauche effective du candidat.</p><h2>Article 4 - Garantie</h2><p>En cas de depart du candidat dans les 3 mois, le Cabinet s'engage a presenter de nouveaux candidats sans frais supplementaires.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_contrat_head_hunting',
    name: "Contrat de chasseur de tetes (head hunting)",
    category: 'rh_emploi',
    price: 6000,
    priceMax: 18000,
    description: "Contrat de mission de chasse de tetes pour profils rares ou postes de direction, avec honoraires au succes et clause de non-debauchage.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_entreprise', label: "Nom de l'entreprise", type: 'text', required: true },
      { key: 'nom_chasseur', label: "Nom du chasseur de tetes / cabinet", type: 'text', required: true },
      { key: 'profil_cible', label: "Profil cible (titre, secteur, experience)", type: 'textarea', required: true },
      { key: 'remuneration_cible', label: "Fourchette de remuneration cible (FCFA/an)", type: 'text', required: true },
      { key: 'honoraires_succes', label: "Honoraires au succes (% salaire annuel brut)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MISSION - HEAD HUNTING</h1><p>Entre <strong>{{nom_entreprise}}</strong> et <strong>{{nom_chasseur}}</strong>.</p><h2>Profil recherche</h2><p>{{profil_cible}}</p><p><strong>Remuneration cible :</strong> {{remuneration_cible}} FCFA/an</p><h2>Honoraires</h2><p>Honoraires au succes : <strong>{{honoraires_succes}}</strong> du salaire annuel brut du candidat embauche, payables a la prise de poste.</p><h2>Clause de non-debauchage</h2><p>Le Chasseur s'interdit de placer dans une autre societe les employes de l'entreprise cliente pendant 24 mois suivant la mission.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_accord_portage_salarial',
    name: "Accord de portage salarial",
    category: 'rh_emploi',
    price: 4000,
    priceMax: 12000,
    description: "Convention de portage salarial entre une entreprise de portage, un consultant independant et l'entreprise cliente, securisant le statut du consultant.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'nom_societe_portage', label: "Nom de la societe de portage", type: 'text', required: true },
      { key: 'nom_consultant', label: "Nom du consultant porte", type: 'text', required: true },
      { key: 'nom_client', label: "Nom de l'entreprise cliente", type: 'text', required: true },
      { key: 'duree_mission', label: "Duree de la mission", type: 'text', required: true },
      { key: 'taux_journalier', label: "Taux journalier moyen (TJM) en FCFA", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PORTAGE SALARIAL</h1><p>Tripartite entre <strong>{{nom_societe_portage}}</strong> (Societe de portage), <strong>{{nom_consultant}}</strong> (Consultant porte) et <strong>{{nom_client}}</strong> (Client).</p><h2>Mission</h2><p>Duree : <strong>{{duree_mission}}</strong> | TJM : <strong>{{taux_journalier}} FCFA</strong></p><h2>Fonctionnement</h2><p>Le Client verse les honoraires a la Societe de portage, qui les reverse au Consultant sous forme de salaire apres deduction des charges sociales et frais de gestion.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_contrat_freelance',
    name: "Contrat de freelance / independant",
    category: 'rh_emploi',
    price: 3500,
    priceMax: 10000,
    description: "Contrat de prestation de service avec un travailleur independant (freelance), fixant les termes de la mission et evitant la requalification en contrat de travail.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'nom_freelance', label: "Nom / raison sociale du freelance", type: 'text', required: true },
      { key: 'nom_client', label: "Nom de l'entreprise cliente", type: 'text', required: true },
      { key: 'objet_mission', label: "Objet et perimetre de la mission", type: 'textarea', required: true },
      { key: 'tarif_mission', label: "Tarif convenu (FCFA, forfait ou TJM)", type: 'text', required: true },
      { key: 'date_livraison', label: "Date de livraison prevue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PRESTATION FREELANCE</h1><p>Entre <strong>{{nom_client}}</strong> (le Client) et <strong>{{nom_freelance}}</strong> (le Prestataire independant).</p><h2>Objet</h2><p>{{objet_mission}}</p><h2>Tarif et paiement</h2><p>Tarif : <strong>{{tarif_mission}} FCFA</strong>. Paiement a la livraison ou selon echeancier convenu.</p><h2>Date de livraison</h2><p>{{date_livraison}}</p><h2>Independance</h2><p>Le Prestataire agit en qualite d'independant. Le present contrat ne saurait etre qualifie de contrat de travail. Il conserve la liberte d'organisation de son travail.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_accord_prestation_rh_externalisee',
    name: "Accord de prestation de service RH externalisee",
    category: 'rh_emploi',
    price: 4500,
    priceMax: 13000,
    description: "Convention de sous-traitance des fonctions RH (recrutement, formation, gestion admin) a un prestataire specialise externe.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'nom_entreprise', label: "Nom de l'entreprise", type: 'text', required: true },
      { key: 'nom_prestataire_rh', label: "Nom du prestataire RH", type: 'text', required: true },
      { key: 'prestations_externalisees', label: "Liste des prestations externalisees", type: 'textarea', required: true },
      { key: 'honoraires_mensuels', label: "Honoraires mensuels (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Duree du contrat (mois / ans)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRESTATION RH EXTERNALISEE</h1><p>Entre <strong>{{nom_entreprise}}</strong> et <strong>{{nom_prestataire_rh}}</strong>.</p><h2>Prestations externalisees</h2><p>{{prestations_externalisees}}</p><h2>Honoraires</h2><p>{{honoraires_mensuels}} FCFA / mois HT | Duree : {{duree_contrat}}</p><h2>Niveaux de service (SLA)</h2><p>Les parties conviennent d'indicateurs de performance mesurables (delais de recrutement, taux de presence, conformite declarations sociales).</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_plan_succession',
    name: "Plan de succession pour postes cles",
    category: 'rh_emploi',
    price: 4000,
    priceMax: 12000,
    description: "Plan de succession identifiant les successeurs potentiels pour les postes strategiques de l'entreprise et les plans de developpement associes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'poste_cle', label: "Poste cle concerne", type: 'text', required: true },
      { key: 'titulaire_actuel', label: "Titulaire actuel", type: 'text', required: true },
      { key: 'successeurs_identifies', label: "Successeurs potentiels identifies (noms et evaluation)", type: 'textarea', required: true },
      { key: 'horizon_succession', label: "Horizon de succession (court/moyen/long terme)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE SUCCESSION - POSTES CLES</h1><p><strong>Entreprise :</strong> {{raison_sociale}}</p><p><strong>Poste :</strong> {{poste_cle}} | <strong>Titulaire :</strong> {{titulaire_actuel}}</p><p><strong>Horizon :</strong> {{horizon_succession}}</p><h2>Successeurs identifies</h2><p>{{successeurs_identifies}}</p><h2>Plan de developpement</h2><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Successeur</th><th>Ecarts de competences</th><th>Actions de developpement</th><th>Delai</th></tr><tr><td>-</td><td>-</td><td>Formation / Coaching / Mobilite</td><td>-</td></tr></table><p>Revue annuelle par le CODIR. Confidentialite stricte.</p></div>`,
  },
  {
    code: 'rec_accord_mobilite_interne',
    name: "Accord de mobilite interne",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7500,
    description: "Avenant au contrat de travail formalisant une mobilite interne (changement de poste, de site ou de departement) en accord entre l'employeur et le salarie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'ancien_poste', label: "Poste d'origine", type: 'text', required: true },
      { key: 'nouveau_poste', label: "Nouveau poste", type: 'text', required: true },
      { key: 'date_prise_poste', label: "Date de prise du nouveau poste", type: 'date', required: true },
      { key: 'modification_remuneration', label: "Modification eventuelle de la remuneration", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE MOBILITE INTERNE</h1><p><strong>Employe :</strong> {{nom_employe}}</p><p><strong>Poste d'origine :</strong> {{ancien_poste}}</p><p><strong>Nouveau poste :</strong> {{nouveau_poste}}</p><p><strong>Date de prise de fonction :</strong> {{date_prise_poste}}</p><p><strong>Remuneration :</strong> {{modification_remuneration}}</p><p>Les autres clauses du contrat de travail initial demeurent inchangees. Le salarie reconnait avoir accepte cette mobilite librement et sans contrainte.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_accord_promotion_interne',
    name: "Accord de promotion interne",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7500,
    description: "Lettre et avenant de promotion interne officialisant l'elevation d'un salarie a un poste de niveau superieur avec revision de la remuneration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe promu", type: 'text', required: true },
      { key: 'ancien_titre', label: "Titre / grade anterieur", type: 'text', required: true },
      { key: 'nouveau_titre', label: "Nouveau titre / grade", type: 'text', required: true },
      { key: 'nouveau_salaire', label: "Nouveau salaire de base (FCFA)", type: 'text', required: true },
      { key: 'date_effet', label: "Date d'effet de la promotion", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>LETTRE DE PROMOTION INTERNE</h1><p>Nous avons le plaisir de vous informer de votre promotion au poste de <strong>{{nouveau_titre}}</strong>, en reconnaissance de vos performances et de votre contribution.</p><p><strong>Employe :</strong> {{nom_employe}}</p><p><strong>Ancien titre :</strong> {{ancien_titre}} -> <strong>Nouveau titre :</strong> {{nouveau_titre}}</p><p><strong>Nouveau salaire de base :</strong> {{nouveau_salaire}} FCFA, a compter du <strong>{{date_effet}}</strong>.</p><p>Nous vous faisons confiance pour relever avec succes les nouveaux defis qui vous attendent.</p><p>Signature Direction : _________________ | Signature Employe (pour acceptation) : _________________</p></div>`,
  },
  {
    code: 'rec_contrat_embauche',
    name: "Contrat d'embauche (offre formelle)",
    category: 'rh_emploi',
    price: 3000,
    priceMax: 9000,
    description: "Offre d'embauche formelle adressee au candidat retenu, precisant les conditions d'emploi avant signature du contrat de travail definitif.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_candidat', label: "Nom et prenoms du candidat", type: 'text', required: true },
      { key: 'titre_poste', label: "Titre du poste propose", type: 'text', required: true },
      { key: 'date_prise_poste', label: "Date de prise de poste proposee", type: 'date', required: true },
      { key: 'salaire_propose', label: "Salaire de base propose (FCFA/mois)", type: 'text', required: true },
      { key: 'avantages', label: "Avantages et benefices (transport, assurance, etc.)", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>OFFRE D'EMBAUCHE</h1><p>Madame / Monsieur <strong>{{nom_candidat}}</strong>,</p><p>Nous avons le plaisir de vous proposer de rejoindre notre equipe en qualite de <strong>{{titre_poste}}</strong>.</p><h2>Conditions proposees</h2><ul><li><strong>Date de debut :</strong> {{date_prise_poste}}</li><li><strong>Salaire de base :</strong> {{salaire_propose}} FCFA brut/mois</li><li><strong>Avantages :</strong> {{avantages}}</li></ul><p>Cette offre est soumise a la validation de vos references et documents justificatifs. Merci de nous confirmer votre acceptation par ecrit dans un delai de 5 jours ouvrables.</p><p>Signature Direction RH : _________________</p></div>`,
  },
  {
    code: 'rec_accord_periode_essai',
    name: "Accord de periode d'essai",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7000,
    description: "Avenant fixant les modalites de la periode d'essai (duree, conditions de renouvellement, evaluation) conformement au Code du Travail ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms de l'employe", type: 'text', required: true },
      { key: 'duree_essai', label: "Duree de la periode d'essai", type: 'text', required: true },
      { key: 'date_debut_essai', label: "Date de debut de la periode d'essai", type: 'date', required: true },
      { key: 'objectifs_essai', label: "Objectifs et criteres d'evaluation durant l'essai", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>MODALITES DE LA PERIODE D'ESSAI</h1><p><strong>Employe :</strong> {{nom_employe}}</p><p><strong>Duree :</strong> {{duree_essai}} | <strong>Debut :</strong> {{date_debut_essai}}</p><p>Conformement aux dispositions du Code du Travail ivoirien (art. 14.1 et suivants), la periode d'essai permet a chaque partie d'evaluer la compatibilite de la relation de travail.</p><h2>Conditions de renouvellement</h2><p>La periode d'essai peut etre renouvelee une fois avec l'accord ecrit des deux parties, sans depasser les durees maximales legales.</p><h2>Objectifs d'evaluation</h2><p>{{objectifs_essai}}</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_plan_gestion_talents',
    name: "Plan de gestion des talents (talent review)",
    category: 'rh_emploi',
    price: 5000,
    priceMax: 15000,
    description: "Document de talent review annuel classant les employes selon la matrice performance/potentiel et definissant les plans de developpement individuels.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'departement_concerne', label: "Departement ou perimetre concerne", type: 'text', required: true },
      { key: 'annee_review', label: "Annee du talent review", type: 'text', required: true },
      { key: 'animateur_session', label: "Animateur de la session talent review", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>TALENT REVIEW - PLAN DE GESTION DES TALENTS</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>Perimetre :</strong> {{departement_concerne}}</p><p><strong>Annee :</strong> {{annee_review}} | <strong>Animateur :</strong> {{animateur_session}}</p><h2>Matrice Performance / Potentiel (9 boxes)</h2><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Categorie</th><th>Description</th><th>Actions RH</th></tr><tr><td>Talent cle (Haut/Haut)</td><td>Excellente performance ET fort potentiel</td><td>Retention, acceleration, succession</td></tr><tr><td>Performeur confirme (Haut/Moyen)</td><td>Tres bonne performance, potentiel moyen</td><td>Reconnaissance, developpement cible</td></tr><tr><td>Potentiel a developper (Moyen/Haut)</td><td>Potentiel eleve, performance a ameliorer</td><td>Coaching, plan de developpement</td></tr></table><p>Confidentialite stricte. Ce document est reserve a la Direction.</p></div>`,
  },
  {
    code: 'rec_accord_retention_talents',
    name: "Accord de retention des talents (retention package)",
    category: 'rh_emploi',
    price: 4000,
    priceMax: 12000,
    description: "Accord de retention propose a un talent cle incluant prime de fidelite, avantages additionnels et engagement de maintien en poste.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'nom_employe', label: "Nom et prenoms du talent concerne", type: 'text', required: true },
      { key: 'prime_fidelite', label: "Prime de fidelite proposee (FCFA)", type: 'text', required: true },
      { key: 'duree_engagement', label: "Duree d'engagement demandee (mois)", type: 'text', required: true },
      { key: 'autres_avantages', label: "Autres avantages inclus (formation, voiture, etc.)", type: 'textarea', required: false },
      { key: 'date_signature', label: "Date de signature de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RETENTION - TALENT KEY</h1><p><strong>Beneficiaire :</strong> {{nom_employe}}</p><p><strong>Date :</strong> {{date_signature}}</p><h2>Package de retention</h2><ul><li><strong>Prime de fidelite :</strong> {{prime_fidelite}} FCFA, versee a l'issue de la periode d'engagement.</li><li><strong>Duree d'engagement :</strong> {{duree_engagement}} mois a compter de la date de signature.</li><li><strong>Avantages additionnels :</strong> {{autres_avantages}}</li></ul><h2>Conditions de versement</h2><p>La prime sera versee si le beneficiaire est toujours en poste et n'a pas remis sa demission a la date d'echeance.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_accord_management_transition',
    name: "Accord de management de transition",
    category: 'rh_emploi',
    price: 5000,
    priceMax: 15000,
    description: "Convention de mission de management de transition confiant temporairement la direction d'une fonction a un manager externe specialise.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'nom_entreprise', label: "Nom de l'entreprise", type: 'text', required: true },
      { key: 'nom_manager_transition', label: "Nom du manager de transition", type: 'text', required: true },
      { key: 'fonction_confiee', label: "Fonction confiee (ex : DRH par interim)", type: 'text', required: true },
      { key: 'duree_mission', label: "Duree de la mission", type: 'text', required: true },
      { key: 'tjm', label: "Taux journalier de la mission (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE MANAGEMENT DE TRANSITION</h1><p>Entre <strong>{{nom_entreprise}}</strong> et <strong>{{nom_manager_transition}}</strong>.</p><h2>Objet</h2><p>Confier a titre transitoire la fonction de <strong>{{fonction_confiee}}</strong> pendant <strong>{{duree_mission}}</strong>.</p><h2>Remuneration</h2><p>TJM : <strong>{{tjm}} FCFA</strong>. Facturation mensuelle sur la base des jours travailles.</p><h2>Missions</h2><p>Assurer la continuite operationnelle de la fonction, mener les projets en cours et preparer la transition vers un titulaire permanent.</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_rapport_turnover',
    name: "Rapport de turnover et analyse",
    category: 'rh_emploi',
    price: 3500,
    priceMax: 10000,
    description: "Rapport d'analyse du taux de rotation du personnel (turnover) avec identification des causes et recommandations d'actions correctives.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale", type: 'text', required: true },
      { key: 'periode_analyse', label: "Periode analysee", type: 'text', required: true },
      { key: 'effectif_debut', label: "Effectif en debut de periode", type: 'text', required: true },
      { key: 'nombre_departs', label: "Nombre de departs sur la periode", type: 'text', required: true },
      { key: 'analyse_causes', label: "Analyse des principales causes de depart", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE TURNOVER DU PERSONNEL</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>Periode :</strong> {{periode_analyse}}</p><p><strong>Effectif debut :</strong> {{effectif_debut}} | <strong>Departs :</strong> {{nombre_departs}}</p><p><strong>Taux de turnover = (Departs / Effectif moyen) x 100 = A calculer %</strong></p><h2>Analyse des causes</h2><p>{{analyse_causes}}</p><h2>Recommandations</h2><ul><li>Actions sur la remuneration et la competitivite salariale</li><li>Amelioration des conditions de travail et du management</li><li>Renforcement de l'engagement et de la marque employeur</li></ul><p>Redacteur : _________________ | Date : _________________</p></div>`,
  },
  {
    code: 'rec_plan_marque_employeur',
    name: "Plan de marque employeur (employer branding)",
    category: 'rh_emploi',
    price: 5000,
    priceMax: 15000,
    description: "Plan strategique de developpement de la marque employeur pour attirer les meilleurs talents en Afrique francophone et fidéliser les collaborateurs.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'positionnement_cible', label: "Positionnement employeur cible", type: 'textarea', required: true },
      { key: 'cibles_recrutement', label: "Cibles de recrutement prioritaires", type: 'textarea', required: true },
      { key: 'budget_marque_employeur', label: "Budget annuel alloue (FCFA)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>PLAN DE MARQUE EMPLOYEUR</h1><p><strong>Entreprise :</strong> {{raison_sociale}}</p><h2>Positionnement cible</h2><p>{{positionnement_cible}}</p><h2>Cibles prioritaires</h2><p>{{cibles_recrutement}}</p><h2>Axes du plan</h2><ol><li><strong>Presence digitale :</strong> LinkedIn, jobboards, site carrieres</li><li><strong>Temoignages employes :</strong> videos, articles, evenements campus</li><li><strong>Partenariats ecoles :</strong> forums, stages, alternances</li><li><strong>Experience candidat :</strong> processus de recrutement fluide et respectueux</li></ol><p>Budget : {{budget_marque_employeur}} FCFA | Responsable : DRH</p></div>`,
  },
  {
    code: 'rec_accord_partenariat_ecole',
    name: "Accord de partenariat ecole-entreprise pour recrutement",
    category: 'rh_emploi',
    price: 3500,
    priceMax: 10000,
    description: "Convention de partenariat entre une entreprise et une institution academique pour l'accueil de stagiaires, l'organisation de forums et le recrutement de jeunes diplomes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_entreprise', label: "Nom de l'entreprise", type: 'text', required: true },
      { key: 'nom_ecole', label: "Nom de l'institution academique", type: 'text', required: true },
      { key: 'objet_partenariat', label: "Objet et modalites du partenariat", type: 'textarea', required: true },
      { key: 'duree_partenariat', label: "Duree du partenariat", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT ECOLE-ENTREPRISE</h1><p>Entre <strong>{{nom_entreprise}}</strong> et <strong>{{nom_ecole}}</strong>.</p><h2>Objet</h2><p>{{objet_partenariat}}</p><h2>Engagements de l'entreprise</h2><ul><li>Accueil de stagiaires en fin d'annee</li><li>Participation aux forums emploi de l'ecole</li><li>Priorite de recrutement aux diplomes de l'ecole</li></ul><h2>Engagements de l'ecole</h2><ul><li>Transmission des CV des meilleurs etudiants</li><li>Organisation de rencontres avec les etudiants</li></ul><p>Duree : {{duree_partenariat}} | Signe le : {{date_signature}}</p><p>Signatures : _________________</p></div>`,
  },
  {
    code: 'rec_rapport_cout_recrutement',
    name: "Rapport de cout de recrutement par poste",
    category: 'rh_emploi',
    price: 3000,
    priceMax: 9000,
    description: "Rapport d'analyse du cout complet d'un recrutement (annonce, cabinet, temps interne, integration) pour piloter l'efficience RH.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'titre_poste', label: "Titre du poste recrute", type: 'text', required: true },
      { key: 'date_ouverture_poste', label: "Date d'ouverture du poste", type: 'date', required: true },
      { key: 'date_prise_poste', label: "Date de prise de poste du candidat retenu", type: 'date', required: true },
      { key: 'cout_total_recrutement', label: "Cout total du recrutement (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE COUT DE RECRUTEMENT</h1><p><strong>Poste :</strong> {{titre_poste}}</p><p><strong>Ouverture :</strong> {{date_ouverture_poste}} | <strong>Prise de poste :</strong> {{date_prise_poste}}</p><table border="1" style="width:100%;border-collapse:collapse"><tr><th>Composante du cout</th><th>Montant (FCFA)</th></tr><tr><td>Diffusion des annonces (jobboards, presse)</td><td>A renseigner</td></tr><tr><td>Honoraires cabinet de recrutement</td><td>A renseigner</td></tr><tr><td>Temps interne DRH (valorise)</td><td>A renseigner</td></tr><tr><td>Tests et evaluations</td><td>A renseigner</td></tr><tr><td>Integration / onboarding</td><td>A renseigner</td></tr><tr><td><strong>TOTAL</strong></td><td><strong>{{cout_total_recrutement}}</strong></td></tr></table><p>Delai de recrutement (time-to-hire) : A calculer jours.</p></div>`,
  },
  {
    code: 'rec_plan_diversite_inclusion',
    name: "Plan de diversite et inclusion (D&I)",
    category: 'rh_emploi',
    price: 4000,
    priceMax: 12000,
    description: "Plan d'action pour promouvoir la diversite et l'inclusion dans les processus de recrutement et de gestion des carrieres de l'entreprise.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'axes_diversite', label: "Axes de diversite prioritaires (genre, handicap, origine...)", type: 'textarea', required: true },
      { key: 'objectifs_mesurables', label: "Objectifs mesurables a 3 ans", type: 'textarea', required: true },
      { key: 'responsable_programme', label: "Responsable du programme D&I", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DIVERSITE ET INCLUSION (D&I)</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>Responsable :</strong> {{responsable_programme}}</p><h2>Axes prioritaires</h2><p>{{axes_diversite}}</p><h2>Objectifs a 3 ans</h2><p>{{objectifs_mesurables}}</p><h2>Actions cles</h2><ul><li>Revue des offres d'emploi pour eliminer les biais implicites</li><li>Formation des recruteurs aux biais inconscients</li><li>Indicateurs de suivi (taux de feminisation, taux emploi handicap)</li><li>Sensibilisation interne via campagnes et temoignages</li></ul><p>Ce plan est revu annuellement lors du bilan social.</p></div>`,
  },
  {
    code: 'rec_charte_recrutement_equitable',
    name: "Charte de recrutement equitable et non-discriminatoire",
    category: 'rh_emploi',
    price: 2500,
    priceMax: 7500,
    description: "Charte definissant les engagements de l'entreprise pour un recrutement juste, transparent et non-discriminatoire, conforme aux lois ivoiriennes et aux principes OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'directeur_rh', label: "Directeur des Ressources Humaines", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption de la charte", type: 'date', required: true },
      { key: 'perimetre_application', label: "Perimetre d'application (toutes entites, un pays...)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE RECRUTEMENT EQUITABLE ET NON-DISCRIMINATOIRE</h1><p><strong>Entreprise :</strong> {{raison_sociale}} | <strong>DRH :</strong> {{directeur_rh}}</p><p><strong>Date d'adoption :</strong> {{date_adoption}} | <strong>Perimetre :</strong> {{perimetre_application}}</p><h2>Nos engagements</h2><ol><li><strong>Egalite de traitement :</strong> Tout candidat est evalue sur ses competences, qualifications et experience, sans consideration de sexe, age, origine ethnique, religion ou situation familiale.</li><li><strong>Transparence :</strong> Les criteres de selection sont definis objectivement avant le debut du processus.</li><li><strong>Confidentialite :</strong> Les donnees des candidats sont traitees conformement a la legislation sur la protection des donnees personnelles.</li><li><strong>Respect :</strong> Tout candidat reçoit une reponse, retenu ou non.</li></ol><p>Signature DRH : _________________ | Signature DG : _________________</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 45b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
