import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  { code: 'indphar_contract_mfg', name: "Accord de Fabrication sous Licence (Contract Manufacturing)", category: 'sante', price: 15000, priceMax: 45000,
    description: "Accord encadrant la fabrication d'un médicament sous licence par un tiers fabricant agréé.", templateType: 'pdf', classe: 'A', active: true, popularity: 72,
    fieldsJson: F([{key:'donneur_licence',label:"Donneur de licence",type:'text',required:true},{key:'fabricant',label:"Fabricant sous licence",type:'text',required:true},{key:'produit',label:"Dénomination du produit",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true},{key:'territoire',label:"Territoire couvert",type:'text',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE FABRICATION SOUS LICENCE</h1><p>Entre <strong>{{donneur_licence}}</strong> (donneur de licence) et <strong>{{fabricant}}</strong> (fabricant sous licence), il est convenu ce qui suit concernant la fabrication du produit <strong>{{produit}}</strong> sur le territoire : {{territoire}}, à compter du {{date_debut}}.</p><h2>Article 1 – Objet</h2><p>Le présent accord a pour objet de définir les conditions dans lesquelles le fabricant est autorisé à produire le médicament visé conformément aux Bonnes Pratiques de Fabrication (BPF) en vigueur.</p><h2>Article 2 – Obligations du fabricant</h2><p>Le fabricant s'engage à respecter les spécifications techniques, les procédures de contrôle qualité et les normes réglementaires applicables.</p><h2>Article 3 – Redevances</h2><p>Les modalités de redevances et de rémunération sont définies en annexe au présent accord.</p></div>` },

  { code: 'indphar_sous_traitance_fab', name: "Contrat de Sous-Traitance Fabrication Médicaments", category: 'sante', price: 12000, priceMax: 36000,
    description: "Contrat de sous-traitance pour la fabrication de médicaments conforme aux exigences BPF et réglementaires.", templateType: 'pdf', classe: 'A', active: true, popularity: 68,
    fieldsJson: F([{key:'donneur_ordre',label:"Donneur d'ordre",type:'text',required:true},{key:'sous_traitant',label:"Sous-traitant",type:'text',required:true},{key:'medicament',label:"Médicament concerné",type:'text',required:true},{key:'volume_annuel',label:"Volume annuel estimé",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE SOUS-TRAITANCE – FABRICATION DE MÉDICAMENTS</h1><p><strong>{{donneur_ordre}}</strong> (donneur d'ordre) confie à <strong>{{sous_traitant}}</strong> (sous-traitant) la fabrication du médicament <strong>{{medicament}}</strong>, pour un volume annuel estimé à {{volume_annuel}}, selon les termes du présent contrat en date du {{date_contrat}}.</p><h2>Article 1 – Périmètre de la sous-traitance</h2><p>La sous-traitance porte sur les opérations de fabrication, de conditionnement primaire et secondaire du médicament visé.</p><h2>Article 2 – Conformité réglementaire</h2><p>Le sous-traitant s'engage à maintenir son autorisation de fabrication en cours de validité et à se soumettre aux audits qualité du donneur d'ordre.</p></div>` },

  { code: 'indphar_comarketing', name: "Accord de Co-Marketing Pharmaceutique", category: 'sante', price: 10000, priceMax: 30000,
    description: "Accord de co-marketing entre deux laboratoires pour la promotion conjointe d'un médicament.", templateType: 'pdf', classe: 'B', active: true, popularity: 55,
    fieldsJson: F([{key:'partenaire_a',label:"Partenaire A",type:'text',required:true},{key:'partenaire_b',label:"Partenaire B",type:'text',required:true},{key:'produit',label:"Produit concerné",type:'text',required:true},{key:'zone',label:"Zone géographique",type:'text',required:true},{key:'duree',label:"Durée de l'accord",type:'text',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE CO-MARKETING PHARMACEUTIQUE</h1><p><strong>{{partenaire_a}}</strong> et <strong>{{partenaire_b}}</strong> conviennent d'un partenariat de co-marketing pour le produit <strong>{{produit}}</strong> sur la zone géographique : {{zone}}, pour une durée de {{duree}}.</p><h2>Article 1 – Partage des responsabilités</h2><p>Chaque partenaire prend en charge les activités promotionnelles définies en annexe, en respectant le code de déontologie pharmaceutique.</p><h2>Article 2 – Propriété intellectuelle</h2><p>Chaque partenaire conserve la propriété de ses éléments apportés. Les éléments co-créés appartiennent conjointement aux deux parties.</p></div>` },

  { code: 'indphar_distrib_nationale', name: "Contrat de Distribution Nationale Médicaments", category: 'sante', price: 9000, priceMax: 27000,
    description: "Contrat encadrant la distribution nationale de médicaments entre un laboratoire et un distributeur agréé.", templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire pharmaceutique",type:'text',required:true},{key:'distributeur',label:"Distributeur national",type:'text',required:true},{key:'gamme',label:"Gamme de produits",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true},{key:'objectif',label:"Objectif de vente annuel",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE DISTRIBUTION NATIONALE – MÉDICAMENTS</h1><p><strong>{{laboratoire}}</strong> confie à <strong>{{distributeur}}</strong> la distribution nationale de la gamme <strong>{{gamme}}</strong>, à compter du {{date_debut}}, avec un objectif de vente annuel de {{objectif}}.</p><h2>Article 1 – Territoire</h2><p>Le présent contrat couvre l'ensemble du territoire national.</p><h2>Article 2 – Conditions de stockage</h2><p>Le distributeur garantit des conditions de stockage conformes aux exigences réglementaires et aux instructions du laboratoire.</p><h2>Article 3 – Pharmacovigilance</h2><p>Le distributeur remonte tout signalement d'effets indésirables au laboratoire dans les délais réglementaires.</p></div>` },

  { code: 'indphar_distrib_uemoa', name: "Accord de Distribution Exclusive Zone UEMOA", category: 'sante', price: 14000, priceMax: 42000,
    description: "Accord de distribution exclusive couvrant la zone UEMOA pour des produits pharmaceutiques.", templateType: 'pdf', classe: 'A', active: true, popularity: 60,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur",type:'text',required:true},{key:'distributeur',label:"Distributeur exclusif",type:'text',required:true},{key:'produits',label:"Produits concernés",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true},{key:'pays_exclusion',label:"Pays exclus le cas échéant",type:'text',required:false}]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTION EXCLUSIVE – ZONE UEMOA</h1><p><strong>{{fournisseur}}</strong> accorde à <strong>{{distributeur}}</strong> l'exclusivité de distribution des produits <strong>{{produits}}</strong> sur la zone UEMOA, à compter du {{date_debut}}.</p><h2>Article 1 – Exclusivité</h2><p>Le fournisseur s'engage à ne pas nommer d'autre distributeur dans la zone UEMOA pour les produits visés pendant la durée du présent accord.</p><h2>Article 2 – Obligations du distributeur</h2><p>Le distributeur s'engage à couvrir l'ensemble des pays de la zone UEMOA et à maintenir des stocks de sécurité.</p></div>` },

  { code: 'indphar_promo_vm', name: "Contrat de Promotion Médicaments (Visiteur Médical)", category: 'sante', price: 7000, priceMax: 21000,
    description: "Contrat de travail ou de prestation pour visiteur médical chargé de la promotion de médicaments auprès des professionnels de santé.", templateType: 'pdf', classe: 'B', active: true, popularity: 70,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire",type:'text',required:true},{key:'visiteur',label:"Nom du visiteur médical",type:'text',required:true},{key:'zone',label:"Zone géographique assignée",type:'text',required:true},{key:'date_prise_fonction',label:"Date de prise de fonction",type:'date',required:true},{key:'produits',label:"Produits à promouvoir",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE PROMOTION MÉDICAMENTS – VISITEUR MÉDICAL</h1><p><strong>{{laboratoire}}</strong> confie à <strong>{{visiteur}}</strong> la mission de promotion des produits <strong>{{produits}}</strong> sur la zone {{zone}}, à compter du {{date_prise_fonction}}.</p><h2>Article 1 – Mission</h2><p>Le visiteur médical assure la présentation des produits auprès des médecins, pharmaciens et autres professionnels de santé de sa zone.</p><h2>Article 2 – Déontologie</h2><p>Le visiteur médical s'engage à respecter le code de déontologie pharmaceutique et à ne délivrer que des informations scientifiquement validées.</p></div>` },

  { code: 'indphar_delegation_medicale', name: "Accord de Délégation Médicale", category: 'sante', price: 8000, priceMax: 24000,
    description: "Accord définissant les termes d'une délégation médicale pour la promotion d'une gamme de médicaments.", templateType: 'pdf', classe: 'B', active: true, popularity: 58,
    fieldsJson: F([{key:'mandant',label:"Laboratoire mandant",type:'text',required:true},{key:'mandataire',label:"Entité mandataire",type:'text',required:true},{key:'gamme',label:"Gamme médicaments",type:'text',required:true},{key:'duree',label:"Durée de la délégation",type:'text',required:true},{key:'date_signature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE DÉLÉGATION MÉDICALE</h1><p><strong>{{mandant}}</strong> délègue à <strong>{{mandataire}}</strong> la mission de promotion médicale de la gamme <strong>{{gamme}}</strong> pour une durée de {{duree}}, à compter du {{date_signature}}.</p><h2>Article 1 – Étendue de la délégation</h2><p>La délégation porte sur les activités de promotion auprès des prescripteurs et des établissements de santé.</p><h2>Article 2 – Rapports d'activité</h2><p>Le mandataire transmet mensuellement un rapport d'activité détaillé au mandant.</p></div>` },

  { code: 'indphar_pharmacovigilance_conv', name: "Convention de Pharmacovigilance avec Autorité", category: 'sante', price: 11000, priceMax: 33000,
    description: "Convention établissant les modalités de collaboration en matière de pharmacovigilance entre un laboratoire et l'autorité compétente.", templateType: 'pdf', classe: 'A', active: true, popularity: 62,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire",type:'text',required:true},{key:'autorite',label:"Autorité compétente",type:'text',required:true},{key:'produits',label:"Produits concernés",type:'text',required:true},{key:'date_convention',label:"Date de la convention",type:'date',required:true},{key:'responsable',label:"Responsable pharmacovigilance",type:'text',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE PHARMACOVIGILANCE</h1><p><strong>{{laboratoire}}</strong> et <strong>{{autorite}}</strong> concluent la présente convention de pharmacovigilance relative aux produits <strong>{{produits}}</strong>, en date du {{date_convention}}, sous la responsabilité de {{responsable}}.</p><h2>Article 1 – Objet</h2><p>La présente convention définit les obligations réciproques en matière de collecte, d'analyse et de transmission des signalements d'effets indésirables.</p><h2>Article 2 – Délais de notification</h2><p>Tout effet indésirable grave et inattendu est notifié dans les 15 jours calendaires.</p></div>` },

  { code: 'indphar_partage_donnees_cliniques', name: "Accord de Partage des Données Cliniques", category: 'sante', price: 13000, priceMax: 39000,
    description: "Accord encadrant le partage sécurisé de données cliniques entre institutions de recherche ou laboratoires.", templateType: 'pdf', classe: 'A', active: true, popularity: 55,
    fieldsJson: F([{key:'institution_a',label:"Institution A",type:'text',required:true},{key:'institution_b',label:"Institution B",type:'text',required:true},{key:'etude',label:"Étude concernée",type:'text',required:true},{key:'type_donnees',label:"Type de données partagées",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE PARTAGE DES DONNÉES CLINIQUES</h1><p><strong>{{institution_a}}</strong> et <strong>{{institution_b}}</strong> conviennent du présent accord de partage des données de l'étude <strong>{{etude}}</strong>, portant sur les données de type : {{type_donnees}}, en date du {{date_accord}}.</p><h2>Article 1 – Données concernées</h2><p>Les données partagées sont anonymisées conformément à la réglementation en vigueur sur la protection des données de santé.</p><h2>Article 2 – Sécurité</h2><p>Chaque partie met en place les mesures techniques et organisationnelles nécessaires à la sécurisation des données reçues.</p></div>` },

  { code: 'indphar_essai_clinique', name: "Contrat d'Essai Clinique", category: 'sante', price: 18000, priceMax: 54000,
    description: "Contrat régissant la réalisation d'un essai clinique entre un promoteur et un établissement investigateur.", templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([{key:'promoteur',label:"Promoteur",type:'text',required:true},{key:'investigateur',label:"Investigateur principal",type:'text',required:true},{key:'etablissement',label:"Établissement de santé",type:'text',required:true},{key:'titre_essai',label:"Titre de l'essai",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT D'ESSAI CLINIQUE</h1><p><strong>{{promoteur}}</strong> confie à <strong>{{investigateur}}</strong>, au sein de <strong>{{etablissement}}</strong>, la réalisation de l'essai clinique intitulé <strong>{{titre_essai}}</strong>, devant débuter le {{date_debut}}.</p><h2>Article 1 – Protocole</h2><p>L'essai est mené conformément au protocole approuvé, aux Bonnes Pratiques Cliniques (BPC) et aux dispositions réglementaires en vigueur.</p><h2>Article 2 – Responsabilités</h2><p>L'investigateur principal est responsable de la conduite scientifique de l'essai et de la sécurité des participants.</p><h2>Article 3 – Financement</h2><p>Le promoteur prend en charge les coûts liés à la réalisation de l'essai selon le budget annexé.</p></div>` },

  { code: 'indphar_convention_site_essai', name: "Convention de Site d'Essai Clinique", category: 'sante', price: 14000, priceMax: 42000,
    description: "Convention établissant les conditions d'accueil et de réalisation d'un essai clinique sur un site investigateur.", templateType: 'pdf', classe: 'A', active: true, popularity: 58,
    fieldsJson: F([{key:'promoteur',label:"Promoteur",type:'text',required:true},{key:'site',label:"Site investigateur",type:'text',required:true},{key:'essai',label:"Référence de l'essai",type:'text',required:true},{key:'nombre_patients',label:"Nombre de patients prévus",type:'text',required:true},{key:'date_convention',label:"Date de la convention",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE SITE D'ESSAI CLINIQUE</h1><p><strong>{{promoteur}}</strong> et le site investigateur <strong>{{site}}</strong> conviennent des modalités de réalisation de l'essai <strong>{{essai}}</strong> pour un nombre prévu de {{nombre_patients}} patients, en date du {{date_convention}}.</p><h2>Article 1 – Mise à disposition des locaux</h2><p>Le site met à disposition les locaux, équipements et personnels nécessaires à la réalisation de l'essai.</p><h2>Article 2 – Archivage</h2><p>Les documents essentiels de l'essai sont archivés sur le site pendant la durée minimale requise par la réglementation.</p></div>` },

  { code: 'indphar_cro', name: "Accord CRO (Contrat de Recherche Clinique)", category: 'sante', price: 16000, priceMax: 48000,
    description: "Accord de prestation entre un promoteur et un organisme de recherche clinique sous contrat (CRO).", templateType: 'pdf', classe: 'A', active: true, popularity: 60,
    fieldsJson: F([{key:'promoteur',label:"Promoteur",type:'text',required:true},{key:'cro',label:"Organisme CRO",type:'text',required:true},{key:'etude',label:"Étude clinique",type:'text',required:true},{key:'prestations',label:"Prestations déléguées",type:'textarea',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD CRO – CONTRAT DE RECHERCHE CLINIQUE</h1><p><strong>{{promoteur}}</strong> délègue à <strong>{{cro}}</strong> les prestations suivantes pour l'étude <strong>{{etude}}</strong> : {{prestations}}, selon les termes du présent contrat en date du {{date_contrat}}.</p><h2>Article 1 – Délégation de responsabilités</h2><p>Les responsabilités déléguées au CRO sont listées en annexe. Le promoteur conserve la responsabilité globale de l'essai.</p><h2>Article 2 – Audit</h2><p>Le promoteur se réserve le droit d'auditer les activités du CRO à tout moment.</p></div>` },

  { code: 'indphar_bioequivalence', name: "Convention de Bioéquivalence", category: 'sante', price: 12000, priceMax: 36000,
    description: "Convention organisant la réalisation d'une étude de bioéquivalence pour un médicament générique.", templateType: 'pdf', classe: 'A', active: true, popularity: 52,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire demandeur",type:'text',required:true},{key:'centre',label:"Centre de bioéquivalence",type:'text',required:true},{key:'produit_teste',label:"Produit testé",type:'text',required:true},{key:'produit_reference',label:"Produit de référence",type:'text',required:true},{key:'date_debut',label:"Date de début de l'étude",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE BIOÉQUIVALENCE</h1><p><strong>{{laboratoire}}</strong> confie au centre <strong>{{centre}}</strong> la réalisation d'une étude de bioéquivalence entre le produit testé <strong>{{produit_teste}}</strong> et le produit de référence <strong>{{produit_reference}}</strong>, débutant le {{date_debut}}.</p><h2>Article 1 – Protocole</h2><p>L'étude est réalisée conformément aux lignes directrices de l'EMA et aux exigences des autorités réglementaires locales.</p><h2>Article 2 – Rapport</h2><p>Le centre remet un rapport complet de bioéquivalence dans les délais convenus.</p></div>` },

  { code: 'indphar_fab_generiques', name: "Accord de Fabrication de Génériques", category: 'sante', price: 13000, priceMax: 39000,
    description: "Accord autorisant et organisant la fabrication de médicaments génériques par un laboratoire.", templateType: 'pdf', classe: 'A', active: true, popularity: 63,
    fieldsJson: F([{key:'titulaire_amm',label:"Titulaire de l'AMM générique",type:'text',required:true},{key:'fabricant',label:"Site de fabrication",type:'text',required:true},{key:'molecule',label:"Molécule / DCI",type:'text',required:true},{key:'dosage',label:"Dosage et forme pharmaceutique",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE FABRICATION DE GÉNÉRIQUES</h1><p><strong>{{titulaire_amm}}</strong> et le site de fabrication <strong>{{fabricant}}</strong> concluent le présent accord pour la fabrication du générique à base de <strong>{{molecule}}</strong>, dosage et forme : {{dosage}}, en date du {{date_accord}}.</p><h2>Article 1 – Conformité réglementaire</h2><p>La fabrication est réalisée conformément à l'AMM et aux BPF applicables.</p><h2>Article 2 – Contrôle qualité</h2><p>Chaque lot est soumis aux contrôles qualité définis dans le dossier de lot.</p></div>` },

  { code: 'indphar_licence_brevet', name: "Contrat de Licence Brevet Pharmaceutique", category: 'sante', price: 20000, priceMax: 60000,
    description: "Contrat de licence d'exploitation d'un brevet pharmaceutique entre titulaire et licencié.", templateType: 'pdf', classe: 'A', active: true, popularity: 58,
    fieldsJson: F([{key:'titulaire',label:"Titulaire du brevet",type:'text',required:true},{key:'licencie',label:"Licencié",type:'text',required:true},{key:'brevet',label:"Numéro et titre du brevet",type:'text',required:true},{key:'territoire',label:"Territoire de la licence",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LICENCE BREVET PHARMACEUTIQUE</h1><p><strong>{{titulaire}}</strong> accorde à <strong>{{licencie}}</strong> une licence d'exploitation du brevet <strong>{{brevet}}</strong> sur le territoire : {{territoire}}, selon les termes du présent contrat en date du {{date_contrat}}.</p><h2>Article 1 – Étendue de la licence</h2><p>La licence est non exclusive / exclusive (préciser) pour les activités de fabrication, d'importation et de commercialisation.</p><h2>Article 2 – Redevances</h2><p>Le licencié verse au titulaire une redevance calculée sur le chiffre d'affaires net selon le taux défini en annexe.</p></div>` },

  { code: 'indphar_transfert_techno', name: "Accord de Transfert de Technologie Pharmaceutique", category: 'sante', price: 18000, priceMax: 54000,
    description: "Accord organisant le transfert d'une technologie pharmaceutique d'une entité vers une autre.", templateType: 'pdf', classe: 'A', active: true, popularity: 55,
    fieldsJson: F([{key:'cedant',label:"Entité cédante",type:'text',required:true},{key:'beneficiaire',label:"Entité bénéficiaire",type:'text',required:true},{key:'technologie',label:"Technologie transférée",type:'text',required:true},{key:'calendrier',label:"Calendrier de transfert",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE TRANSFERT DE TECHNOLOGIE PHARMACEUTIQUE</h1><p><strong>{{cedant}}</strong> transfère à <strong>{{beneficiaire}}</strong> la technologie <strong>{{technologie}}</strong> selon le calendrier suivant : {{calendrier}}, en date du {{date_accord}}.</p><h2>Article 1 – Périmètre du transfert</h2><p>Le transfert inclut le savoir-faire, les procédures de fabrication, les méthodes analytiques et la documentation technique associée.</p><h2>Article 2 – Formation</h2><p>Le cédant assure la formation du personnel du bénéficiaire pendant la durée du transfert.</p></div>` },

  { code: 'indphar_distrib_otc', name: "Contrat de Distribution Produits OTC", category: 'sante', price: 8000, priceMax: 24000,
    description: "Contrat de distribution de produits pharmaceutiques en vente libre (Over The Counter) sur un territoire défini.", templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur",type:'text',required:true},{key:'distributeur',label:"Distributeur OTC",type:'text',required:true},{key:'produits',label:"Gamme OTC",type:'text',required:true},{key:'canaux',label:"Canaux de distribution",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE DISTRIBUTION PRODUITS OTC</h1><p><strong>{{fournisseur}}</strong> confie à <strong>{{distributeur}}</strong> la distribution de la gamme OTC <strong>{{produits}}</strong> via les canaux : {{canaux}}, à compter du {{date_debut}}.</p><h2>Article 1 – Conditions commerciales</h2><p>Les prix, remises et conditions de paiement sont définis dans la grille tarifaire annexée au présent contrat.</p><h2>Article 2 – Merchandising</h2><p>Le distributeur assure la visibilité des produits selon les standards du fournisseur.</p></div>` },

  { code: 'indphar_enregistrement_anrp', name: "Accord d'Enregistrement Produit auprès de l'ANRP", category: 'sante', price: 9000, priceMax: 27000,
    description: "Accord définissant les modalités d'enregistrement d'un médicament auprès de l'Autorité Nationale de Réglementation Pharmaceutique.", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire demandeur",type:'text',required:true},{key:'produit',label:"Dénomination du produit",type:'text',required:true},{key:'dci',label:"DCI (Dénomination Commune Internationale)",type:'text',required:true},{key:'pays',label:"Pays d'enregistrement",type:'text',required:true},{key:'date_depot',label:"Date de dépôt du dossier",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD D'ENREGISTREMENT PRODUIT – ANRP</h1><p><strong>{{laboratoire}}</strong> soumet le présent dossier d'enregistrement pour le produit <strong>{{produit}}</strong> (DCI : {{dci}}) auprès de l'Autorité Nationale de Réglementation Pharmaceutique du pays : {{pays}}, en date du {{date_depot}}.</p><h2>Article 1 – Dossier de demande</h2><p>Le dossier est constitué selon le format CTD (Common Technical Document) adapté aux exigences locales.</p><h2>Article 2 – Engagements du demandeur</h2><p>Le laboratoire s'engage à fournir toute information complémentaire demandée par l'autorité dans les délais impartis.</p></div>` },

  { code: 'indphar_convention_pharmacie', name: "Convention avec Direction de la Pharmacie", category: 'sante', price: 10000, priceMax: 30000,
    description: "Convention de collaboration entre un opérateur pharmaceutique et la Direction Nationale de la Pharmacie.", templateType: 'pdf', classe: 'B', active: true, popularity: 57,
    fieldsJson: F([{key:'operateur',label:"Opérateur pharmaceutique",type:'text',required:true},{key:'direction',label:"Direction de la Pharmacie",type:'text',required:true},{key:'objet',label:"Objet de la convention",type:'textarea',required:true},{key:'date_signature',label:"Date de signature",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION AVEC LA DIRECTION DE LA PHARMACIE</h1><p><strong>{{operateur}}</strong> et la <strong>{{direction}}</strong> concluent la présente convention ayant pour objet : {{objet}}, signée le {{date_signature}}.</p><h2>Article 1 – Engagements réciproques</h2><p>Chaque partie s'engage à respecter les termes de la présente convention et à informer l'autre partie de tout changement susceptible d'affecter son exécution.</p><h2>Article 2 – Durée</h2><p>La présente convention est conclue pour une durée d'un an renouvelable par tacite reconduction.</p></div>` },

  { code: 'indphar_rapport_pv', name: "Rapport de Pharmacovigilance Périodique", category: 'sante', price: 7000, priceMax: 21000,
    description: "Rapport périodique de pharmacovigilance (PSUR/PBRER) synthétisant les signalements d'effets indésirables.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire titulaire",type:'text',required:true},{key:'produit',label:"Produit concerné",type:'text',required:true},{key:'periode',label:"Période de rapport",type:'text',required:true},{key:'responsable_pv',label:"Responsable pharmacovigilance",type:'text',required:true},{key:'date_rapport',label:"Date du rapport",type:'date',required:true}]),
    body: `<div class="doc"><h1>RAPPORT PÉRIODIQUE DE PHARMACOVIGILANCE</h1><p>Laboratoire : <strong>{{laboratoire}}</strong> | Produit : <strong>{{produit}}</strong> | Période : {{periode}} | Date : {{date_rapport}}</p><p>Responsable pharmacovigilance : {{responsable_pv}}</p><h2>1. Résumé des données de sécurité</h2><p>Ce rapport présente une analyse des effets indésirables collectés durant la période de référence.</p><h2>2. Analyse bénéfice/risque</h2><p>L'analyse globale confirme un profil bénéfice/risque favorable pour le produit.</p><h2>3. Conclusion</h2><p>Aucune mesure corrective urgente n'est requise sur la base des données de la période.</p></div>` },

  { code: 'indphar_pgr', name: "Plan de Gestion des Risques Pharmaceutiques", category: 'sante', price: 11000, priceMax: 33000,
    description: "Plan de gestion des risques (PGR) documentant les mesures de minimisation des risques d'un médicament.", templateType: 'pdf', classe: 'A', active: true, popularity: 55,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire",type:'text',required:true},{key:'medicament',label:"Médicament",type:'text',required:true},{key:'version',label:"Version du plan",type:'text',required:true},{key:'risques_importants',label:"Risques importants identifiés",type:'textarea',required:true},{key:'date_plan',label:"Date du plan",type:'date',required:true}]),
    body: `<div class="doc"><h1>PLAN DE GESTION DES RISQUES PHARMACEUTIQUES</h1><p>Laboratoire : <strong>{{laboratoire}}</strong> | Médicament : <strong>{{medicament}}</strong> | Version : {{version}} | Date : {{date_plan}}</p><h2>Partie I – Spécifications de sécurité</h2><p>Risques importants identifiés : {{risques_importants}}</p><h2>Partie II – Plan de pharmacovigilance</h2><p>Les activités de pharmacovigilance additionnelles sont définies en annexe.</p><h2>Partie III – Mesures de minimisation des risques</h2><p>Les mesures de minimisation des risques incluent les mentions légales, les matériels éducationnels et les programmes de suivi.</p></div>` },

  { code: 'indphar_rappel_lot', name: "Accord de Rappel de Lot National", category: 'sante', price: 9000, priceMax: 27000,
    description: "Accord et procédure encadrant le rappel d'un lot de médicament défectueux à l'échelle nationale.", templateType: 'pdf', classe: 'A', active: true, popularity: 58,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire",type:'text',required:true},{key:'produit',label:"Produit rappelé",type:'text',required:true},{key:'numero_lot',label:"Numéro de lot",type:'text',required:true},{key:'motif',label:"Motif du rappel",type:'textarea',required:true},{key:'date_rappel',label:"Date de déclenchement du rappel",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE RAPPEL DE LOT NATIONAL</h1><p>Laboratoire : <strong>{{laboratoire}}</strong> | Produit : <strong>{{produit}}</strong> | Lot n° : {{numero_lot}}</p><p>Date de déclenchement : {{date_rappel}}</p><h2>1. Motif du rappel</h2><p>{{motif}}</p><h2>2. Périmètre du rappel</h2><p>Le rappel concerne l'ensemble du territoire national pour le lot identifié.</p><h2>3. Procédure de retour</h2><p>Les produits rappelés doivent être retournés au laboratoire dans les 72 heures suivant la notification.</p><h2>4. Information des autorités</h2><p>L'autorité compétente a été informée conformément à la réglementation.</p></div>` },

  { code: 'indphar_stockage_froid', name: "Contrat de Stockage Médicaments en Chaîne du Froid", category: 'sante', price: 10000, priceMax: 30000,
    description: "Contrat de prestation de stockage sous température contrôlée pour médicaments thermosensibles.", templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([{key:'proprietaire',label:"Propriétaire des médicaments",type:'text',required:true},{key:'prestataire',label:"Prestataire de stockage",type:'text',required:true},{key:'produits',label:"Produits concernés",type:'text',required:true},{key:'temperature',label:"Plage de température requise",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE STOCKAGE MÉDICAMENTS – CHAÎNE DU FROID</h1><p><strong>{{proprietaire}}</strong> confie à <strong>{{prestataire}}</strong> le stockage des produits <strong>{{produits}}</strong> sous une température de {{temperature}}, selon les termes du présent contrat en date du {{date_contrat}}.</p><h2>Article 1 – Conditions de stockage</h2><p>Le prestataire garantit le maintien continu de la chaîne du froid et dispose d'une alimentation électrique de secours.</p><h2>Article 2 – Monitoring</h2><p>La température est enregistrée en continu et un rapport mensuel est transmis au propriétaire.</p><h2>Article 3 – Responsabilité</h2><p>Le prestataire est responsable de toute perte liée à une rupture de la chaîne du froid imputable à sa négligence.</p></div>` },

  { code: 'indphar_transport_sensible', name: "Accord de Transport Médicaments Sensibles", category: 'sante', price: 8000, priceMax: 24000,
    description: "Accord encadrant le transport de médicaments sensibles (thermosensibles, stupéfiants, biologiques).", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'expediteur',label:"Expéditeur",type:'text',required:true},{key:'transporteur',label:"Transporteur",type:'text',required:true},{key:'nature_produits',label:"Nature des produits",type:'text',required:true},{key:'conditions_transport',label:"Conditions de transport requises",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE TRANSPORT MÉDICAMENTS SENSIBLES</h1><p><strong>{{expediteur}}</strong> confie à <strong>{{transporteur}}</strong> le transport de médicaments sensibles de nature : <strong>{{nature_produits}}</strong>, sous les conditions : {{conditions_transport}}, en date du {{date_accord}}.</p><h2>Article 1 – Véhicules et équipements</h2><p>Le transporteur utilise des véhicules homologués et équipements adaptés au transport de médicaments sensibles.</p><h2>Article 2 – Traçabilité</h2><p>Un bordereau de transport traçable est émis pour chaque expédition.</p></div>` },

  { code: 'indphar_rapport_bpf', name: "Rapport d'Inspection BPF (Bonnes Pratiques de Fabrication)", category: 'sante', price: 6000, priceMax: 18000,
    description: "Rapport d'inspection des Bonnes Pratiques de Fabrication (BPF) d'un site pharmaceutique.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'site_inspecte',label:"Site inspecté",type:'text',required:true},{key:'inspecteur',label:"Inspecteur(s)",type:'text',required:true},{key:'date_inspection',label:"Date d'inspection",type:'date',required:true},{key:'conclusion',label:"Conclusion générale",type:'textarea',required:true},{key:'ecarts',label:"Écarts identifiés",type:'textarea',required:false}]),
    body: `<div class="doc"><h1>RAPPORT D'INSPECTION BPF</h1><p>Site inspecté : <strong>{{site_inspecte}}</strong> | Inspecteur(s) : {{inspecteur}} | Date : {{date_inspection}}</p><h2>1. Objet de l'inspection</h2><p>La présente inspection a pour objet d'évaluer la conformité du site aux Bonnes Pratiques de Fabrication.</p><h2>2. Constats</h2><p>Écarts identifiés : {{ecarts}}</p><h2>3. Conclusion</h2><p>{{conclusion}}</p><h2>4. Plan d'actions correctives</h2><p>Le site est tenu de soumettre un plan d'actions correctives dans les 30 jours suivant la réception du présent rapport.</p></div>` },

  // ===== DISPOSITIFS MÉDICAUX / ÉQUIPEMENTS (dmed_) =====

  { code: 'dmed_fourniture_equipements', name: "Contrat de Fourniture Équipements Médicaux", category: 'sante', price: 14000, priceMax: 42000,
    description: "Contrat de fourniture et de livraison d'équipements médicaux à un établissement de santé.", templateType: 'pdf', classe: 'A', active: true, popularity: 70,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur",type:'text',required:true},{key:'acheteur',label:"Établissement acheteur",type:'text',required:true},{key:'equipements',label:"Équipements fournis",type:'textarea',required:true},{key:'montant',label:"Montant total HT",type:'text',required:true},{key:'date_livraison',label:"Date de livraison prévue",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE FOURNITURE ÉQUIPEMENTS MÉDICAUX</h1><p><strong>{{fournisseur}}</strong> s'engage à fournir à <strong>{{acheteur}}</strong> les équipements médicaux suivants : {{equipements}}, pour un montant total HT de {{montant}}, avec une livraison prévue le {{date_livraison}}.</p><h2>Article 1 – Spécifications techniques</h2><p>Les équipements fournis sont conformes aux spécifications techniques définies en annexe et portent le marquage CE ou équivalent.</p><h2>Article 2 – Installation et mise en service</h2><p>Le fournisseur assure l'installation, la mise en service et la formation des utilisateurs.</p><h2>Article 3 – Garantie</h2><p>Une garantie de 12 mois minimum est accordée à compter de la réception définitive.</p></div>` },

  { code: 'dmed_maintenance_imagerie', name: "Accord de Maintenance Équipement Imagerie", category: 'sante', price: 11000, priceMax: 33000,
    description: "Accord de maintenance préventive et curative pour équipements d'imagerie médicale.", templateType: 'pdf', classe: 'B', active: true, popularity: 67,
    fieldsJson: F([{key:'prestataire',label:"Prestataire de maintenance",type:'text',required:true},{key:'client',label:"Établissement client",type:'text',required:true},{key:'equipement',label:"Équipement d'imagerie",type:'text',required:true},{key:'niveau_service',label:"Niveau de service (SLA)",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE MAINTENANCE ÉQUIPEMENT IMAGERIE MÉDICALE</h1><p><strong>{{prestataire}}</strong> assure la maintenance de l'équipement d'imagerie <strong>{{equipement}}</strong> pour le compte de <strong>{{client}}</strong>, avec un niveau de service : {{niveau_service}}, selon le contrat en date du {{date_contrat}}.</p><h2>Article 1 – Maintenance préventive</h2><p>Des visites préventives sont programmées trimestriellement selon le plan joint en annexe.</p><h2>Article 2 – Maintenance curative</h2><p>Le prestataire intervient dans les délais définis par le SLA en cas de panne.</p><h2>Article 3 – Pièces de rechange</h2><p>Le prestataire garantit la disponibilité des pièces critiques pendant toute la durée du contrat.</p></div>` },

  { code: 'dmed_maintenance_scanner_irm', name: "Contrat de Maintenance Scanner/IRM", category: 'sante', price: 16000, priceMax: 48000,
    description: "Contrat de maintenance spécialisé pour scanner et IRM incluant la radioprotection et la qualimétrie.", templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([{key:'prestataire',label:"Prestataire",type:'text',required:true},{key:'hopital',label:"Hôpital / Clinique",type:'text',required:true},{key:'type_equipement',label:"Type d'équipement (Scanner/IRM)",type:'text',required:true},{key:'marque_modele',label:"Marque et modèle",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE MAINTENANCE SCANNER / IRM</h1><p><strong>{{prestataire}}</strong> prend en charge la maintenance du <strong>{{type_equipement}}</strong> de marque et modèle <strong>{{marque_modele}}</strong>, installé chez <strong>{{hopital}}</strong>, selon les termes du contrat en date du {{date_contrat}}.</p><h2>Article 1 – Prestations incluses</h2><p>Le contrat couvre la maintenance préventive, curative, les mises à jour logicielles et le contrôle qualité dosimétrique.</p><h2>Article 2 – Radioprotection</h2><p>Les interventions sont réalisées par des techniciens habilités en radioprotection.</p><h2>Article 3 – Disponibilité garantie</h2><p>La disponibilité de l'équipement est garantie à 95% minimum sur une période mensuelle.</p></div>` },

  { code: 'dmed_service_biomedical', name: "Convention de Service Biomédical", category: 'sante', price: 10000, priceMax: 30000,
    description: "Convention organisant le service biomédical externalisé d'un établissement de santé.", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'prestataire',label:"Prestataire biomédical",type:'text',required:true},{key:'etablissement',label:"Établissement de santé",type:'text',required:true},{key:'parc_equipements',label:"Parc d'équipements géré",type:'textarea',required:true},{key:'effectif',label:"Effectif dédié",type:'text',required:true},{key:'date_debut',label:"Date de début",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE SERVICE BIOMÉDICAL</h1><p><strong>{{prestataire}}</strong> assure le service biomédical externalisé de <strong>{{etablissement}}</strong>, couvrant le parc d'équipements suivant : {{parc_equipements}}, avec un effectif dédié de {{effectif}}, à compter du {{date_debut}}.</p><h2>Article 1 – Périmètre de la prestation</h2><p>Le prestataire assure la gestion du parc, la maintenance, la formation des utilisateurs et le suivi réglementaire.</p><h2>Article 2 – Rapports</h2><p>Un rapport mensuel d'activité est transmis à la direction de l'établissement.</p></div>` },

  { code: 'dmed_location_equipement', name: "Accord de Location Équipement Médical", category: 'sante', price: 9000, priceMax: 27000,
    description: "Accord de location d'équipement médical entre un bailleur et un établissement de santé.", templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([{key:'bailleur',label:"Bailleur",type:'text',required:true},{key:'locataire',label:"Locataire",type:'text',required:true},{key:'equipement',label:"Équipement loué",type:'text',required:true},{key:'loyer',label:"Loyer mensuel HT",type:'text',required:true},{key:'date_debut',label:"Date de début de location",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE LOCATION ÉQUIPEMENT MÉDICAL</h1><p><strong>{{bailleur}}</strong> met à la disposition de <strong>{{locataire}}</strong> l'équipement médical <strong>{{equipement}}</strong> pour un loyer mensuel HT de {{loyer}}, à compter du {{date_debut}}.</p><h2>Article 1 – Conditions d'utilisation</h2><p>Le locataire utilise l'équipement conformément à sa destination médicale et aux instructions du fabricant.</p><h2>Article 2 – Entretien</h2><p>La maintenance est assurée par le bailleur sauf détérioration due à une mauvaise utilisation du locataire.</p></div>` },

  { code: 'dmed_lease_chirurgical', name: "Contrat de Lease Équipement Chirurgical", category: 'sante', price: 14000, priceMax: 42000,
    description: "Contrat de crédit-bail (lease) pour l'acquisition d'équipements chirurgicaux par un établissement de santé.", templateType: 'pdf', classe: 'A', active: true, popularity: 60,
    fieldsJson: F([{key:'bailleur',label:"Établissement bailleur (société de leasing)",type:'text',required:true},{key:'preneur',label:"Preneur (établissement de santé)",type:'text',required:true},{key:'equipement',label:"Équipement chirurgical",type:'text',required:true},{key:'valeur',label:"Valeur du bien",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LEASE ÉQUIPEMENT CHIRURGICAL</h1><p><strong>{{bailleur}}</strong> consent à <strong>{{preneur}}</strong> un lease portant sur l'équipement chirurgical <strong>{{equipement}}</strong> d'une valeur de {{valeur}}, selon les termes du présent contrat en date du {{date_contrat}}.</p><h2>Article 1 – Durée et loyers</h2><p>La durée du lease et l'échéancier des loyers sont définis en annexe financière.</p><h2>Article 2 – Option d'achat</h2><p>À l'échéance, le preneur dispose d'une option d'achat au prix résiduel défini dans le contrat.</p><h2>Article 3 – Assurance</h2><p>Le preneur est tenu d'assurer le bien dès la livraison.</p></div>` },

  { code: 'dmed_formation_equipement', name: "Accord de Formation Utilisation Équipement Médical", category: 'sante', price: 6000, priceMax: 18000,
    description: "Accord de formation des utilisateurs à l'utilisation d'un équipement médical spécifique.", templateType: 'pdf', classe: 'B', active: true, popularity: 68,
    fieldsJson: F([{key:'formateur',label:"Organisme formateur",type:'text',required:true},{key:'etablissement',label:"Établissement bénéficiaire",type:'text',required:true},{key:'equipement',label:"Équipement concerné",type:'text',required:true},{key:'nombre_stagiaires',label:"Nombre de stagiaires",type:'text',required:true},{key:'date_formation',label:"Date de formation",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE FORMATION – UTILISATION ÉQUIPEMENT MÉDICAL</h1><p><strong>{{formateur}}</strong> assure la formation de <strong>{{nombre_stagiaires}}</strong> agents de <strong>{{etablissement}}</strong> à l'utilisation de l'équipement <strong>{{equipement}}</strong>, prévue le {{date_formation}}.</p><h2>Article 1 – Programme de formation</h2><p>Le programme couvre la prise en main, les procédures d'utilisation, la maintenance de premier niveau et la gestion des alarmes.</p><h2>Article 2 – Attestation</h2><p>Une attestation de formation est remise à chaque stagiaire ayant suivi l'intégralité du programme.</p></div>` },

  { code: 'dmed_sav_equipement', name: "Convention de SAV Équipement Médical", category: 'sante', price: 8000, priceMax: 24000,
    description: "Convention de service après-vente pour équipements médicaux incluant hotline et interventions sur site.", templateType: 'pdf', classe: 'B', active: true, popularity: 66,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur / SAV",type:'text',required:true},{key:'client',label:"Client",type:'text',required:true},{key:'equipements',label:"Équipements couverts",type:'text',required:true},{key:'delai_intervention',label:"Délai d'intervention garanti",type:'text',required:true},{key:'date_convention',label:"Date de la convention",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE SAV ÉQUIPEMENT MÉDICAL</h1><p><strong>{{fournisseur}}</strong> s'engage à assurer le service après-vente des équipements <strong>{{equipements}}</strong> de <strong>{{client}}</strong>, avec un délai d'intervention garanti de {{delai_intervention}}, selon la convention en date du {{date_convention}}.</p><h2>Article 1 – Hotline technique</h2><p>Une hotline technique est disponible 24h/24, 7j/7 pour les équipements critiques.</p><h2>Article 2 – Pièces détachées</h2><p>Le fournisseur garantit la disponibilité des pièces de rechange pendant 10 ans après l'achat.</p></div>` },

  { code: 'dmed_qualification_equipement', name: "Rapport de Qualification Équipement Médical", category: 'sante', price: 9000, priceMax: 27000,
    description: "Rapport de qualification (QI/QO/QP) d'un équipement médical pour la mise en service réglementaire.", templateType: 'pdf', classe: 'A', active: true, popularity: 57,
    fieldsJson: F([{key:'equipement',label:"Équipement qualifié",type:'text',required:true},{key:'etablissement',label:"Établissement",type:'text',required:true},{key:'type_qualification',label:"Type de qualification (QI/QO/QP)",type:'text',required:true},{key:'resultats',label:"Résultats et conformité",type:'textarea',required:true},{key:'date_qualification',label:"Date de qualification",type:'date',required:true}]),
    body: `<div class="doc"><h1>RAPPORT DE QUALIFICATION ÉQUIPEMENT MÉDICAL</h1><p>Équipement : <strong>{{equipement}}</strong> | Établissement : {{etablissement}} | Type : {{type_qualification}} | Date : {{date_qualification}}</p><h2>1. Qualification de l'installation (QI)</h2><p>Vérification de la conformité de l'installation aux spécifications du fournisseur.</p><h2>2. Qualification opérationnelle (QO)</h2><p>Vérification du fonctionnement de l'équipement dans les conditions d'utilisation prévues.</p><h2>3. Qualification des performances (QP)</h2><p>Vérification des performances de l'équipement dans les conditions réelles d'utilisation.</p><h2>4. Conclusion</h2><p>{{resultats}}</p></div>` },

  { code: 'dmed_validation_equipement', name: "Protocole de Validation Équipement Médical", category: 'sante', price: 8000, priceMax: 24000,
    description: "Protocole de validation d'un procédé ou équipement médical pour garantir la reproductibilité des résultats.", templateType: 'pdf', classe: 'A', active: true, popularity: 55,
    fieldsJson: F([{key:'equipement',label:"Équipement / Procédé validé",type:'text',required:true},{key:'responsable',label:"Responsable de validation",type:'text',required:true},{key:'criteres',label:"Critères d'acceptation",type:'textarea',required:true},{key:'methode',label:"Méthode de validation",type:'text',required:true},{key:'date_protocole',label:"Date du protocole",type:'date',required:true}]),
    body: `<div class="doc"><h1>PROTOCOLE DE VALIDATION ÉQUIPEMENT MÉDICAL</h1><p>Équipement / Procédé : <strong>{{equipement}}</strong> | Responsable : {{responsable}} | Date : {{date_protocole}}</p><h2>1. Objectif</h2><p>Le présent protocole définit les étapes de validation de l'équipement selon la méthode : {{methode}}.</p><h2>2. Critères d'acceptation</h2><p>{{criteres}}</p><h2>3. Plan d'exécution</h2><p>Les tests sont réalisés selon le calendrier défini en annexe avec enregistrement des résultats dans le logiciel de traçabilité.</p><h2>4. Actions en cas de non-conformité</h2><p>Toute non-conformité déclenche une investigation et une action corrective documentée.</p></div>` },

  { code: 'dmed_sterilisation', name: "Contrat de Stérilisation Instruments Médicaux", category: 'sante', price: 7000, priceMax: 21000,
    description: "Contrat de prestation de stérilisation d'instruments médicaux pour un établissement de santé.", templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([{key:'prestataire',label:"Prestataire de stérilisation",type:'text',required:true},{key:'client',label:"Établissement client",type:'text',required:true},{key:'types_instruments',label:"Types d'instruments traités",type:'text',required:true},{key:'methode',label:"Méthode de stérilisation",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE STÉRILISATION INSTRUMENTS MÉDICAUX</h1><p><strong>{{prestataire}}</strong> assure la stérilisation des instruments de type <strong>{{types_instruments}}</strong> pour le compte de <strong>{{client}}</strong>, selon la méthode {{methode}}, en vertu du présent contrat en date du {{date_contrat}}.</p><h2>Article 1 – Processus de stérilisation</h2><p>Chaque cycle de stérilisation est documenté et les paramètres critiques sont enregistrés et archivés.</p><h2>Article 2 – Traçabilité</h2><p>Un numéro de lot est attribué à chaque charge de stérilisation et consigné dans le registre de traçabilité.</p></div>` },

  { code: 'dmed_duu', name: "Accord de Gestion des Dispositifs à Usage Unique", category: 'sante', price: 8000, priceMax: 24000,
    description: "Accord encadrant la gestion, l'approvisionnement et l'élimination des dispositifs médicaux à usage unique.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur",type:'text',required:true},{key:'etablissement',label:"Établissement de santé",type:'text',required:true},{key:'gamme_duu',label:"Gamme de dispositifs à usage unique",type:'text',required:true},{key:'volume_annuel',label:"Volume annuel estimé",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DES DISPOSITIFS À USAGE UNIQUE</h1><p><strong>{{fournisseur}}</strong> et <strong>{{etablissement}}</strong> concluent le présent accord portant sur la gamme de dispositifs à usage unique <strong>{{gamme_duu}}</strong>, pour un volume annuel estimé à {{volume_annuel}}, en date du {{date_accord}}.</p><h2>Article 1 – Approvisionnement</h2><p>Le fournisseur garantit un approvisionnement régulier avec un délai de livraison maximum de 5 jours ouvrables.</p><h2>Article 2 – Élimination</h2><p>L'établissement s'engage à éliminer les dispositifs usagés selon la réglementation sur les déchets d'activités de soins à risques infectieux (DASRI).</p></div>` },

  { code: 'dmed_tracabilite_dm', name: "Convention de Traçabilité Dispositif Médical", category: 'sante', price: 9000, priceMax: 27000,
    description: "Convention établissant le système de traçabilité des dispositifs médicaux tout au long de la chaîne de distribution.", templateType: 'pdf', classe: 'A', active: true, popularity: 58,
    fieldsJson: F([{key:'fabricant',label:"Fabricant / Importateur",type:'text',required:true},{key:'distributeur',label:"Distributeur",type:'text',required:true},{key:'dispositifs',label:"Dispositifs concernés",type:'text',required:true},{key:'systeme_tracabilite',label:"Système de traçabilité utilisé",type:'text',required:true},{key:'date_convention',label:"Date de la convention",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE TRAÇABILITÉ DISPOSITIF MÉDICAL</h1><p><strong>{{fabricant}}</strong> et <strong>{{distributeur}}</strong> conviennent du présent système de traçabilité pour les dispositifs <strong>{{dispositifs}}</strong>, basé sur : {{systeme_tracabilite}}, en date du {{date_convention}}.</p><h2>Article 1 – Identifiant unique des dispositifs (IUD)</h2><p>Chaque dispositif médical est identifié par un IUD conforme aux standards internationaux (GS1, HIBCC).</p><h2>Article 2 – Base de données</h2><p>Les données de traçabilité sont conservées dans une base sécurisée pendant une durée minimale de 15 ans.</p></div>` },

  { code: 'dmed_materiovigilance', name: "Accord de Vigilance Dispositif Médical (Matériovigilance)", category: 'sante', price: 10000, priceMax: 30000,
    description: "Accord de matériovigilance définissant les obligations de signalement des incidents liés aux dispositifs médicaux.", templateType: 'pdf', classe: 'A', active: true, popularity: 60,
    fieldsJson: F([{key:'fabricant',label:"Fabricant / Mandataire",type:'text',required:true},{key:'autorite',label:"Autorité compétente",type:'text',required:true},{key:'correspondant',label:"Correspondant local de matériovigilance",type:'text',required:true},{key:'dispositifs',label:"Dispositifs couverts",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE MATÉRIOVIGILANCE – DISPOSITIFS MÉDICAUX</h1><p><strong>{{fabricant}}</strong> et <strong>{{autorite}}</strong> concluent le présent accord de matériovigilance, avec pour correspondant local <strong>{{correspondant}}</strong>, couvrant les dispositifs <strong>{{dispositifs}}</strong>, en date du {{date_accord}}.</p><h2>Article 1 – Obligations de signalement</h2><p>Tout incident grave ou risque d'incident grave lié à un dispositif médical est signalé à l'autorité compétente dans les délais réglementaires.</p><h2>Article 2 – Investigations</h2><p>Le fabricant mène les investigations nécessaires et transmet les résultats à l'autorité dans les 30 jours.</p></div>` },

  { code: 'dmed_implant', name: "Contrat d'Implant Médical", category: 'sante', price: 16000, priceMax: 48000,
    description: "Contrat encadrant la fourniture et le suivi d'implants médicaux pour un établissement chirurgical.", templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur d'implants",type:'text',required:true},{key:'etablissement',label:"Établissement chirurgical",type:'text',required:true},{key:'type_implant',label:"Type d'implant",type:'text',required:true},{key:'registre',label:"Registre des implants prévu",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT D'IMPLANT MÉDICAL</h1><p><strong>{{fournisseur}}</strong> fournit à <strong>{{etablissement}}</strong> des implants médicaux de type <strong>{{type_implant}}</strong>, avec un suivi via le registre : {{registre}}, selon le contrat en date du {{date_contrat}}.</p><h2>Article 1 – Traçabilité des implants</h2><p>Chaque implant posé est enregistré dans le registre national des implants avec les informations d'identification du patient et du dispositif.</p><h2>Article 2 – Suivi post-implantation</h2><p>Le fournisseur assure un suivi des performances des implants et notifie tout problème de sécurité dans les plus brefs délais.</p></div>` },

  { code: 'dmed_prothese_ortho', name: "Accord de Prothèse Orthopédique", category: 'sante', price: 13000, priceMax: 39000,
    description: "Accord de fourniture et de prise en charge de prothèses orthopédiques entre un fournisseur et un établissement.", templateType: 'pdf', classe: 'A', active: true, popularity: 62,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur de prothèses",type:'text',required:true},{key:'etablissement',label:"Établissement orthopédique",type:'text',required:true},{key:'types_protheses',label:"Types de prothèses couvertes",type:'text',required:true},{key:'prix_unitaire',label:"Prix unitaire indicatif",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE PROTHÈSE ORTHOPÉDIQUE</h1><p><strong>{{fournisseur}}</strong> et <strong>{{etablissement}}</strong> concluent le présent accord portant sur la fourniture de prothèses <strong>{{types_protheses}}</strong>, au prix unitaire indicatif de {{prix_unitaire}}, en date du {{date_accord}}.</p><h2>Article 1 – Conditions techniques</h2><p>Les prothèses sont certifiées conformément aux exigences de la directive européenne ou des normes équivalentes applicables.</p><h2>Article 2 – Stock consigné</h2><p>Le fournisseur peut mettre en place un stock consigné au sein de l'établissement pour les références les plus courantes.</p></div>` },

  { code: 'dmed_lunetterie', name: "Contrat de Lunetterie Médicale", category: 'sante', price: 5000, priceMax: 15000,
    description: "Contrat de fourniture de lunetteries médicales et d'équipements optiques pour un établissement ou un opticien.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur optique",type:'text',required:true},{key:'client',label:"Opticien / Établissement",type:'text',required:true},{key:'gamme',label:"Gamme de produits",type:'text',required:true},{key:'remise',label:"Taux de remise consenti",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE LUNETTERIE MÉDICALE</h1><p><strong>{{fournisseur}}</strong> et <strong>{{client}}</strong> concluent le présent contrat portant sur la gamme de lunetterie médicale <strong>{{gamme}}</strong>, avec une remise de {{remise}}, en date du {{date_contrat}}.</p><h2>Article 1 – Produits</h2><p>Les produits fournis sont conformes aux normes CE et aux prescriptions médicales applicables.</p><h2>Article 2 – Conditions commerciales</h2><p>Les conditions de paiement, de retour et de garantie sont définies en annexe commerciale.</p></div>` },

  { code: 'dmed_labo_analyse', name: "Accord de Laboratoire d'Analyse Médicale", category: 'sante', price: 10000, priceMax: 30000,
    description: "Accord encadrant les prestations d'analyses médicales entre un laboratoire et un prescripteur ou établissement.", templateType: 'pdf', classe: 'B', active: true, popularity: 65,
    fieldsJson: F([{key:'laboratoire',label:"Laboratoire d'analyses",type:'text',required:true},{key:'client',label:"Établissement / Prescripteur",type:'text',required:true},{key:'analyses',label:"Types d'analyses couvertes",type:'text',required:true},{key:'delai',label:"Délai de rendu des résultats",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE LABORATOIRE D'ANALYSE MÉDICALE</h1><p><strong>{{laboratoire}}</strong> réalise les analyses de type <strong>{{analyses}}</strong> pour le compte de <strong>{{client}}</strong>, avec un délai de rendu des résultats de {{delai}}, selon l'accord en date du {{date_accord}}.</p><h2>Article 1 – Accréditation</h2><p>Le laboratoire est accrédité COFRAC ou équivalent pour les analyses réalisées dans le cadre du présent accord.</p><h2>Article 2 – Transmission des résultats</h2><p>Les résultats sont transmis par voie électronique sécurisée dans les délais convenus.</p></div>` },

  { code: 'dmed_telemedecine', name: "Convention de Télémédecine", category: 'sante', price: 12000, priceMax: 36000,
    description: "Convention organisant la mise en place et le fonctionnement d'un service de télémédecine entre établissements.", templateType: 'pdf', classe: 'A', active: true, popularity: 68,
    fieldsJson: F([{key:'centre_expert',label:"Centre expert (téléconsultant)",type:'text',required:true},{key:'site_patient',label:"Site patient (demandeur)",type:'text',required:true},{key:'specialite',label:"Spécialité médicale concernée",type:'text',required:true},{key:'plateforme',label:"Plateforme technique utilisée",type:'text',required:true},{key:'date_convention',label:"Date de la convention",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE TÉLÉMÉDECINE</h1><p><strong>{{centre_expert}}</strong> et <strong>{{site_patient}}</strong> établissent la présente convention de télémédecine en spécialité <strong>{{specialite}}</strong>, via la plateforme <strong>{{plateforme}}</strong>, en date du {{date_convention}}.</p><h2>Article 1 – Actes de télémédecine</h2><p>Les actes couverts incluent la téléconsultation, la téléexpertise et la téléassistance médicale selon les indications convenues.</p><h2>Article 2 – Sécurité des données</h2><p>Toutes les communications sont chiffrées et les données de santé sont hébergées par un Hébergeur Agréé de Données de Santé (HDS).</p></div>` },

  { code: 'dmed_esante_equipement', name: "Accord de e-Santé Équipement", category: 'sante', price: 11000, priceMax: 33000,
    description: "Accord de déploiement et d'utilisation de solutions e-santé et équipements connectés en santé.", templateType: 'pdf', classe: 'B', active: true, popularity: 63,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur e-santé",type:'text',required:true},{key:'etablissement',label:"Établissement de santé",type:'text',required:true},{key:'solution',label:"Solution e-santé déployée",type:'text',required:true},{key:'nombre_utilisateurs',label:"Nombre d'utilisateurs",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE E-SANTÉ ÉQUIPEMENT</h1><p><strong>{{fournisseur}}</strong> déploie la solution e-santé <strong>{{solution}}</strong> auprès de <strong>{{etablissement}}</strong> pour {{nombre_utilisateurs}} utilisateurs, selon l'accord en date du {{date_accord}}.</p><h2>Article 1 – Formation et accompagnement</h2><p>Le fournisseur assure la formation initiale et un accompagnement pendant les 3 premiers mois d'utilisation.</p><h2>Article 2 – Interopérabilité</h2><p>La solution est compatible avec les standards d'interopérabilité HL7 FHIR et s'intègre avec les systèmes d'information existants.</p></div>` },

  { code: 'dmed_radiologie_externalisee', name: "Contrat de Radiologie Externalisée", category: 'sante', price: 13000, priceMax: 39000,
    description: "Contrat de prestation de radiologie externalisée entre un centre d'imagerie et un établissement de santé.", templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([{key:'centre_imagerie',label:"Centre d'imagerie prestataire",type:'text',required:true},{key:'etablissement',label:"Établissement demandeur",type:'text',required:true},{key:'actes',label:"Actes radiologiques couverts",type:'text',required:true},{key:'delai_compte_rendu',label:"Délai de compte rendu",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE RADIOLOGIE EXTERNALISÉE</h1><p><strong>{{centre_imagerie}}</strong> assure les prestations de radiologie <strong>{{actes}}</strong> pour <strong>{{etablissement}}</strong>, avec un délai de rendu des comptes rendus de {{delai_compte_rendu}}, selon le contrat en date du {{date_contrat}}.</p><h2>Article 1 – Organisation des examens</h2><p>Les examens sont réalisés au sein du centre d'imagerie ou, le cas échéant, par télé-radiologie.</p><h2>Article 2 – Responsabilité médicale</h2><p>Chaque compte rendu radiologique est signé par un radiologue diplômé.</p></div>` },

  { code: 'dmed_poct', name: "Accord de Biologie Délocalisée (POCT)", category: 'sante', price: 9000, priceMax: 27000,
    description: "Accord encadrant le déploiement et l'utilisation de la biologie délocalisée (Point Of Care Testing - POCT) dans un établissement.", templateType: 'pdf', classe: 'B', active: true, popularity: 60,
    fieldsJson: F([{key:'fournisseur',label:"Fournisseur POCT",type:'text',required:true},{key:'etablissement',label:"Établissement de santé",type:'text',required:true},{key:'analyseurs',label:"Analyseurs déployés",type:'text',required:true},{key:'unites',label:"Unités de soins concernées",type:'text',required:true},{key:'date_accord',label:"Date de l'accord",type:'date',required:true}]),
    body: `<div class="doc"><h1>ACCORD DE BIOLOGIE DÉLOCALISÉE (POCT)</h1><p><strong>{{fournisseur}}</strong> déploie les analyseurs <strong>{{analyseurs}}</strong> dans les unités {{unites}} de <strong>{{etablissement}}</strong>, selon l'accord en date du {{date_accord}}.</p><h2>Article 1 – Formation des opérateurs</h2><p>Le fournisseur assure la formation de tous les opérateurs (infirmiers, aide-soignants) avant la mise en service.</p><h2>Article 2 – Contrôle de qualité</h2><p>Des contrôles de qualité internes et externes sont réalisés selon la fréquence définie en annexe technique.</p></div>` },

  { code: 'dmed_dialyse', name: "Contrat de Dialyse Centre Externe", category: 'sante', price: 16000, priceMax: 48000,
    description: "Contrat organisant la prise en charge de patients insuffisants rénaux dans un centre de dialyse externe.", templateType: 'pdf', classe: 'A', active: true, popularity: 65,
    fieldsJson: F([{key:'centre_dialyse',label:"Centre de dialyse",type:'text',required:true},{key:'etablissement_envoyeur',label:"Établissement envoyeur",type:'text',required:true},{key:'nombre_patients',label:"Nombre de patients concernés",type:'text',required:true},{key:'tarif_seance',label:"Tarif par séance",type:'text',required:true},{key:'date_contrat',label:"Date du contrat",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONTRAT DE DIALYSE – CENTRE EXTERNE</h1><p><strong>{{centre_dialyse}}</strong> prend en charge les patients de <strong>{{etablissement_envoyeur}}</strong> au nombre de {{nombre_patients}}, au tarif de {{tarif_seance}} par séance, selon le contrat en date du {{date_contrat}}.</p><h2>Article 1 – Protocoles de soins</h2><p>Les protocoles de dialyse sont définis conjointement par les équipes médicales des deux établissements.</p><h2>Article 2 – Coordination médicale</h2><p>Une réunion de coordination médicale est organisée trimestriellement pour faire le point sur les patients.</p></div>` },

  { code: 'dmed_readaptation', name: "Convention de Réadaptation Fonctionnelle", category: 'sante', price: 10000, priceMax: 30000,
    description: "Convention de prise en charge de patients en réadaptation fonctionnelle entre un hôpital et un centre de rééducation.", templateType: 'pdf', classe: 'B', active: true, popularity: 62,
    fieldsJson: F([{key:'hopital',label:"Hôpital prescripteur",type:'text',required:true},{key:'centre_reeducation',label:"Centre de rééducation",type:'text',required:true},{key:'specialites',label:"Spécialités de réadaptation",type:'text',required:true},{key:'criteres_admission',label:"Critères d'admission",type:'textarea',required:true},{key:'date_convention',label:"Date de la convention",type:'date',required:true}]),
    body: `<div class="doc"><h1>CONVENTION DE RÉADAPTATION FONCTIONNELLE</h1><p><strong>{{hopital}}</strong> et le centre de rééducation <strong>{{centre_reeducation}}</strong> établissent la présente convention pour les spécialités : <strong>{{specialites}}</strong>, en date du {{date_convention}}.</p><h2>Article 1 – Critères d'admission</h2><p>{{criteres_admission}}</p><h2>Article 2 – Projet thérapeutique individualisé</h2><p>Un projet thérapeutique individualisé est élaboré pour chaque patient dans les 48h suivant l'admission.</p><h2>Article 3 – Continuité des soins</h2><p>Un compte rendu de réadaptation est transmis à l'hôpital prescripteur à la sortie du patient.</p></div>` },

  { code: 'dmed_eval_techno_medicale', name: "Rapport d'Évaluation Technologie Médicale", category: 'sante', price: 11000, priceMax: 33000,
    description: "Rapport d'évaluation des technologies médicales (HTA) pour l'aide à la décision d'acquisition ou de remboursement.", templateType: 'pdf', classe: 'A', active: true, popularity: 58,
    fieldsJson: F([{key:'technologie',label:"Technologie évaluée",type:'text',required:true},{key:'institution',label:"Institution évaluatrice",type:'text',required:true},{key:'indication',label:"Indication clinique évaluée",type:'text',required:true},{key:'conclusion_hta',label:"Conclusion de l'évaluation",type:'textarea',required:true},{key:'date_rapport',label:"Date du rapport",type:'date',required:true}]),
    body: `<div class="doc"><h1>RAPPORT D'ÉVALUATION TECHNOLOGIE MÉDICALE (HTA)</h1><p>Technologie : <strong>{{technologie}}</strong> | Institution : {{institution}} | Indication : {{indication}} | Date : {{date_rapport}}</p><h2>1. Description de la technologie</h2><p>Présentation de la technologie, de son mode d'action et de ses indications revendiquées.</p><h2>2. Efficacité clinique</h2><p>Analyse des données cliniques disponibles : études randomisées, méta-analyses, données de vie réelle.</p><h2>3. Sécurité</h2><p>Analyse du profil de sécurité et comparaison avec les alternatives thérapeutiques.</p><h2>4. Coût-efficacité</h2><p>Analyse médico-économique comparative.</p><h2>5. Conclusion</h2><p>{{conclusion_hta}}</p></div>` },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 25b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
