import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  {
    code: 'mp_dao_ouvert',
    name: "Dossier d'Appel d'Offres Ouvert",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 50000,
    description: "Dossier complet pour la procédure d'appel d'offres ouvert conforme au Code des marchés publics OHADA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 92,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'numero_dao', label: "Numéro du DAO", type: 'text', required: true },
      { key: 'date_limite_depot', label: "Date limite de dépôt des offres", type: 'date', required: true },
      { key: 'budget_previsionnel', label: "Budget prévisionnel (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER D'APPEL D'OFFRES OUVERT</h1><h2>N° {{numero_dao}}</h2><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Objet du marché :</strong> {{objet_marche}}</p><p><strong>Budget prévisionnel :</strong> {{budget_previsionnel}} FCFA</p><p><strong>Date limite de dépôt des offres :</strong> {{date_limite_depot}}</p><h3>SECTION I — AVIS D'APPEL D'OFFRES</h3><p>Le présent dossier d'appel d'offres est lancé en application des dispositions du Code des marchés publics en vigueur.</p></div>`,
  },
  {
    code: 'mp_dao_restreint',
    name: "Dossier d'Appel d'Offres Restreint",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 40000,
    description: "Dossier pour appel d'offres restreint avec liste restreinte de candidats présélectionnés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'numero_dao', label: "Numéro du DAO restreint", type: 'text', required: true },
      { key: 'date_seance_ouverture', label: "Date de séance d'ouverture", type: 'date', required: true },
      { key: 'nombre_candidats', label: "Nombre de candidats présélectionnés", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER D'APPEL D'OFFRES RESTREINT</h1><h2>N° {{numero_dao}}</h2><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Objet du marché :</strong> {{objet_marche}}</p><p><strong>Nombre de candidats invités :</strong> {{nombre_candidats}}</p><p><strong>Date d'ouverture des plis :</strong> {{date_seance_ouverture}}</p><h3>SECTION I — INSTRUCTIONS AUX SOUMISSIONNAIRES</h3><p>La présente procédure restreinte est réservée aux candidats figurant sur la liste restreinte établie par l'autorité contractante.</p></div>`,
  },
  {
    code: 'mp_ccag',
    name: "Cahier des Clauses Administratives Générales (CCAG)",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 35000,
    description: "CCAG définissant les dispositions administratives communes applicables aux marchés publics.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'ministere', label: "Ministère concerné", type: 'text', required: true },
      { key: 'annee_edition', label: "Année d'édition", type: 'text', required: true },
      { key: 'type_marche', label: "Type de marché (travaux / fournitures / services)", type: 'text', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entrée en vigueur", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CAHIER DES CLAUSES ADMINISTRATIVES GÉNÉRALES</h1><h2>{{type_marche}} — Édition {{annee_edition}}</h2><p><strong>Ministère :</strong> {{ministere}}</p><p><strong>Date d'entrée en vigueur :</strong> {{date_entree_vigueur}}</p><h3>TITRE I — DISPOSITIONS GÉNÉRALES</h3><p>Le présent CCAG fixe les dispositions administratives générales applicables aux marchés publics passés pour le compte de l'État.</p></div>`,
  },
  {
    code: 'mp_cctp',
    name: "Cahier des Clauses Techniques Particulières (CCTP)",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 35000,
    description: "CCTP précisant les prescriptions techniques spécifiques applicables à un marché donné.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'normes_applicables', label: "Normes techniques applicables", type: 'textarea', required: true },
      { key: 'delai_execution', label: "Délai d'exécution (jours)", type: 'text', required: true },
      { key: 'date_etablissement', label: "Date d'établissement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CAHIER DES CLAUSES TECHNIQUES PARTICULIÈRES</h1><p><strong>Objet :</strong> {{objet_marche}}</p><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Normes applicables :</strong> {{normes_applicables}}</p><p><strong>Délai d'exécution :</strong> {{delai_execution}} jours</p><p><strong>Date d'établissement :</strong> {{date_etablissement}}</p><h3>ARTICLE 1 — OBJET ET CHAMP D'APPLICATION</h3><p>Le présent CCTP définit les prescriptions techniques particulières applicables aux prestations objet du marché.</p></div>`,
  },
  {
    code: 'mp_reglement_consultation',
    name: "Règlement de Consultation",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 25000,
    description: "Document fixant les règles de la consultation, les conditions de participation et les critères de sélection.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'objet_consultation', label: "Objet de la consultation", type: 'textarea', required: true },
      { key: 'date_remise_offres', label: "Date de remise des offres", type: 'date', required: true },
      { key: 'criteres_selection', label: "Critères de sélection principaux", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RÈGLEMENT DE CONSULTATION</h1><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Objet de la consultation :</strong> {{objet_consultation}}</p><p><strong>Date de remise des offres :</strong> {{date_remise_offres}}</p><h3>ARTICLE 1 — CONDITIONS DE PARTICIPATION</h3><p>Peuvent participer à la présente consultation toutes les personnes physiques ou morales répondant aux conditions définies ci-après.</p><h3>ARTICLE 2 — CRITÈRES DE SÉLECTION</h3><p>{{criteres_selection}}</p></div>`,
  },
  {
    code: 'mp_lettre_candidature',
    name: "Lettre de Candidature",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Lettre officielle de manifestation de candidature à un appel d'offres public.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_entreprise', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'representant_legal', label: "Nom du représentant légal", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'numero_dao', label: "Référence du DAO", type: 'text', required: true },
      { key: 'date_lettre', label: "Date de la lettre", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>LETTRE DE CANDIDATURE</h1><p>{{date_lettre}}</p><p>La société <strong>{{nom_entreprise}}</strong>, représentée par <strong>{{representant_legal}}</strong>, a l'honneur de soumettre sa candidature dans le cadre de l'appel d'offres N° {{numero_dao}} portant sur : <em>{{objet_marche}}</em>.</p><p>Nous certifions que notre entreprise satisfait à toutes les conditions d'éligibilité requises et que les informations fournies sont exactes et sincères.</p><p>Veuillez agréer, Monsieur/Madame le Président de la Commission, l'expression de nos salutations distinguées.</p><p><strong>{{representant_legal}}</strong></p></div>`,
  },
  {
    code: 'mp_dossier_candidature_pme',
    name: "Dossier de Candidature PME",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Dossier de candidature adapté aux petites et moyennes entreprises pour les marchés publics.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'nom_pme', label: "Dénomination sociale de la PME", type: 'text', required: true },
      { key: 'numero_rccm', label: "Numéro RCCM", type: 'text', required: true },
      { key: 'effectif_personnel', label: "Effectif du personnel", type: 'text', required: true },
      { key: 'chiffre_affaires', label: "Chiffre d'affaires annuel (FCFA)", type: 'text', required: true },
      { key: 'references_similaires', label: "Références de marchés similaires", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>DOSSIER DE CANDIDATURE — PME</h1><h2>{{nom_pme}}</h2><p><strong>N° RCCM :</strong> {{numero_rccm}}</p><p><strong>Effectif :</strong> {{effectif_personnel}} salariés</p><p><strong>Chiffre d'affaires :</strong> {{chiffre_affaires}} FCFA</p><h3>RÉFÉRENCES DE MARCHÉS SIMILAIRES</h3><p>{{references_similaires}}</p><h3>DÉCLARATION SUR L'HONNEUR</h3><p>Je soussigné, représentant légal de la PME sus-désignée, certifie l'exactitude des informations fournies dans le présent dossier.</p></div>`,
  },
  {
    code: 'mp_offre_technique',
    name: "Offre Technique",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Document présentant la proposition technique du soumissionnaire en réponse à un appel d'offres.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'nom_soumissionnaire', label: "Nom du soumissionnaire", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'methodologie', label: "Méthodologie proposée", type: 'textarea', required: true },
      { key: 'calendrier_execution', label: "Calendrier d'exécution proposé", type: 'textarea', required: true },
      { key: 'moyens_humains', label: "Moyens humains mobilisés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>OFFRE TECHNIQUE</h1><p><strong>Soumissionnaire :</strong> {{nom_soumissionnaire}}</p><p><strong>Objet du marché :</strong> {{objet_marche}}</p><h3>1. COMPRÉHENSION DE LA MISSION</h3><p>{{methodologie}}</p><h3>2. CALENDRIER D'EXÉCUTION</h3><p>{{calendrier_execution}}</p><h3>3. MOYENS HUMAINS</h3><p>{{moyens_humains}}</p></div>`,
  },
  {
    code: 'mp_offre_financiere',
    name: "Offre Financière",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 25000,
    description: "Document de soumission financière précisant le montant global et le détail des prix proposés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 87,
    fieldsJson: F([
      { key: 'nom_soumissionnaire', label: "Nom du soumissionnaire", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'montant_ht', label: "Montant total HT (FCFA)", type: 'text', required: true },
      { key: 'montant_ttc', label: "Montant total TTC (FCFA)", type: 'text', required: true },
      { key: 'delai_validite', label: "Délai de validité de l'offre (jours)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>OFFRE FINANCIÈRE</h1><p><strong>Soumissionnaire :</strong> {{nom_soumissionnaire}}</p><p><strong>Objet du marché :</strong> {{objet_marche}}</p><h3>MONTANT DE L'OFFRE</h3><table><tr><td>Montant HT</td><td>{{montant_ht}} FCFA</td></tr><tr><td>TVA (18%)</td><td>incluse</td></tr><tr><td><strong>Montant TTC</strong></td><td><strong>{{montant_ttc}} FCFA</strong></td></tr></table><p>La présente offre est valable pendant <strong>{{delai_validite}} jours</strong> à compter de la date limite de dépôt des offres.</p></div>`,
  },
  {
    code: 'mp_memoire_technique',
    name: "Mémoire Technique",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Mémoire technique détaillant l'approche, les moyens et les qualifications du soumissionnaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'nom_entreprise', label: "Nom de l'entreprise", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'organisation_chantier', label: "Organisation du chantier / de la mission", type: 'textarea', required: true },
      { key: 'mesures_qualite', label: "Mesures de qualité et de contrôle", type: 'textarea', required: true },
      { key: 'date_redaction', label: "Date de rédaction", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>MÉMOIRE TECHNIQUE</h1><h2>{{nom_entreprise}}</h2><p><strong>Marché :</strong> {{objet_marche}}</p><p><strong>Date :</strong> {{date_redaction}}</p><h3>1. ORGANISATION ET MOYENS</h3><p>{{organisation_chantier}}</p><h3>2. DÉMARCHE QUALITÉ</h3><p>{{mesures_qualite}}</p></div>`,
  },
  {
    code: 'mp_rapport_evaluation_offres',
    name: "Rapport d'Évaluation des Offres",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 40000,
    description: "Rapport de la commission d'évaluation analysant et classant les offres reçues.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'numero_dao', label: "Référence du DAO", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'nombre_offres_recues', label: "Nombre d'offres reçues", type: 'text', required: true },
      { key: 'date_evaluation', label: "Date d'évaluation", type: 'date', required: true },
      { key: 'attributaire_propose', label: "Attributaire proposé", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'ÉVALUATION DES OFFRES</h1><p><strong>DAO N° :</strong> {{numero_dao}}</p><p><strong>Objet :</strong> {{objet_marche}}</p><p><strong>Date d'évaluation :</strong> {{date_evaluation}}</p><p><strong>Nombre d'offres reçues :</strong> {{nombre_offres_recues}}</p><h3>RÉSULTAT DE L'ÉVALUATION</h3><p>Après analyse comparative des offres techniques et financières, la commission propose d'attribuer le marché à : <strong>{{attributaire_propose}}</strong>.</p></div>`,
  },
  {
    code: 'mp_pv_ouverture_plis',
    name: "Procès-Verbal d'Ouverture des Plis",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 20000,
    description: "PV officiel constatant l'ouverture publique des plis en séance de la commission.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'numero_dao', label: "Référence du DAO", type: 'text', required: true },
      { key: 'date_seance', label: "Date et heure de la séance", type: 'date', required: true },
      { key: 'lieu_seance', label: "Lieu de la séance", type: 'text', required: true },
      { key: 'president_commission', label: "Président de la commission", type: 'text', required: true },
      { key: 'liste_soumissionnaires', label: "Liste des soumissionnaires", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÈS-VERBAL D'OUVERTURE DES PLIS</h1><p><strong>Séance du :</strong> {{date_seance}}</p><p><strong>Lieu :</strong> {{lieu_seance}}</p><p><strong>Président de la commission :</strong> {{president_commission}}</p><p><strong>Objet DAO N° :</strong> {{numero_dao}}</p><h3>DÉROULEMENT DE LA SÉANCE</h3><p>La commission a procédé à l'ouverture des plis en séance publique. Les soumissionnaires suivants ont déposé des offres :</p><p>{{liste_soumissionnaires}}</p></div>`,
  },
  {
    code: 'mp_rapport_commission_attribution',
    name: "Rapport de la Commission d'Attribution",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 38000,
    description: "Rapport final de la commission d'attribution recommandant l'attribution du marché.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 81,
    fieldsJson: F([
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'attributaire', label: "Entreprise attributaire", type: 'text', required: true },
      { key: 'montant_marche', label: "Montant du marché (FCFA)", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'justification_attribution', label: "Justification de l'attribution", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE LA COMMISSION D'ATTRIBUTION</h1><p><strong>Date :</strong> {{date_rapport}}</p><p><strong>Objet du marché :</strong> {{objet_marche}}</p><h3>DÉCISION D'ATTRIBUTION</h3><p>La commission d'attribution recommande d'attribuer le marché à <strong>{{attributaire}}</strong> pour un montant de <strong>{{montant_marche}} FCFA</strong>.</p><h3>JUSTIFICATION</h3><p>{{justification_attribution}}</p></div>`,
  },
  {
    code: 'mp_lettre_notification_attribution',
    name: "Lettre de Notification d'Attribution",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Lettre officielle notifiant l'attributaire de la décision d'attribution du marché.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 90,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'nom_attributaire', label: "Nom de l'attributaire", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'montant_marche', label: "Montant du marché (FCFA)", type: 'text', required: true },
      { key: 'date_notification', label: "Date de notification", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>LETTRE DE NOTIFICATION D'ATTRIBUTION</h1><p>{{date_notification}}</p><p>À : <strong>{{nom_attributaire}}</strong></p><p>Objet : <em>Notification d'attribution — {{objet_marche}}</em></p><p>Monsieur/Madame,</p><p>Nous avons l'honneur de vous informer que le marché portant sur <strong>{{objet_marche}}</strong> vous a été attribué pour un montant de <strong>{{montant_marche}} FCFA</strong>.</p><p>Nous vous invitons à prendre contact avec nos services pour la signature du contrat.</p><p><strong>{{autorite_contractante}}</strong></p></div>`,
  },
  {
    code: 'mp_lettre_rejet_offre',
    name: "Lettre de Rejet d'Offre",
    category: 'juridique_admin',
    price: 4000,
    priceMax: 12000,
    description: "Lettre officielle informant un soumissionnaire du rejet de son offre avec motivation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'nom_soumissionnaire', label: "Nom du soumissionnaire", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'motif_rejet', label: "Motif du rejet", type: 'textarea', required: true },
      { key: 'date_lettre', label: "Date de la lettre", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>LETTRE DE REJET D'OFFRE</h1><p>{{date_lettre}}</p><p>À : <strong>{{nom_soumissionnaire}}</strong></p><p>Objet : <em>Rejet de votre offre — {{objet_marche}}</em></p><p>Monsieur/Madame,</p><p>Nous vous informons que votre offre soumise dans le cadre du marché portant sur <strong>{{objet_marche}}</strong> n'a pas été retenue.</p><h3>MOTIF DU REJET</h3><p>{{motif_rejet}}</p><p>Conformément à la réglementation en vigueur, vous disposez d'un délai de recours auprès des instances compétentes.</p><p><strong>{{autorite_contractante}}</strong></p></div>`,
  },
  {
    code: 'mp_contrat_travaux',
    name: "Contrat de Marché Public de Travaux",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 65000,
    description: "Contrat de marché public de travaux conformément au droit OHADA et au Code des marchés publics.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 93,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'objet_travaux', label: "Objet des travaux", type: 'textarea', required: true },
      { key: 'montant_ttc', label: "Montant TTC (FCFA)", type: 'text', required: true },
      { key: 'delai_execution', label: "Délai d'exécution (mois)", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARCHÉ PUBLIC DE TRAVAUX</h1><p>Entre : <strong>{{autorite_contractante}}</strong> (le Maître d'ouvrage)</p><p>Et : <strong>{{titulaire}}</strong> (le Titulaire)</p><h3>ARTICLE 1 — OBJET DU MARCHÉ</h3><p>Le présent contrat a pour objet : {{objet_travaux}}</p><h3>ARTICLE 2 — MONTANT DU MARCHÉ</h3><p>Le montant TTC du marché est fixé à <strong>{{montant_ttc}} FCFA</strong>.</p><h3>ARTICLE 3 — DÉLAI D'EXÉCUTION</h3><p>Les travaux doivent être achevés dans un délai de <strong>{{delai_execution}} mois</strong> à compter de la date de l'ordre de service de démarrage.</p><p>Fait à _____________, le {{date_signature}}</p></div>`,
  },
  {
    code: 'mp_contrat_fournitures',
    name: "Contrat de Marché Public de Fournitures",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 50000,
    description: "Contrat de marché public pour l'acquisition de fournitures, équipements et matériels.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'fournisseur', label: "Fournisseur titulaire", type: 'text', required: true },
      { key: 'designation_fournitures', label: "Désignation des fournitures", type: 'textarea', required: true },
      { key: 'montant_ttc', label: "Montant TTC (FCFA)", type: 'text', required: true },
      { key: 'delai_livraison', label: "Délai de livraison (jours)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARCHÉ PUBLIC DE FOURNITURES</h1><p><strong>Maître d'ouvrage :</strong> {{autorite_contractante}}</p><p><strong>Fournisseur :</strong> {{fournisseur}}</p><h3>ARTICLE 1 — OBJET</h3><p>Le présent marché porte sur la fourniture de : {{designation_fournitures}}</p><h3>ARTICLE 2 — PRIX ET PAIEMENT</h3><p>Montant total TTC : <strong>{{montant_ttc}} FCFA</strong></p><h3>ARTICLE 3 — DÉLAI DE LIVRAISON</h3><p>La livraison devra intervenir dans un délai de <strong>{{delai_livraison}} jours</strong> à compter de la notification de l'ordre de commande.</p></div>`,
  },
  {
    code: 'mp_contrat_services',
    name: "Contrat de Marché de Services",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 50000,
    description: "Contrat de marché public de prestations intellectuelles et de services.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 86,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire de services", type: 'text', required: true },
      { key: 'nature_services', label: "Nature des services", type: 'textarea', required: true },
      { key: 'montant_honoraires', label: "Montant des honoraires (FCFA)", type: 'text', required: true },
      { key: 'duree_mission', label: "Durée de la mission (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MARCHÉ DE SERVICES</h1><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Prestataire :</strong> {{prestataire}}</p><h3>ARTICLE 1 — OBJET DE LA MISSION</h3><p>{{nature_services}}</p><h3>ARTICLE 2 — RÉMUNÉRATION</h3><p>Honoraires convenus : <strong>{{montant_honoraires}} FCFA</strong></p><h3>ARTICLE 3 — DURÉE</h3><p>La mission s'étend sur une durée de <strong>{{duree_mission}} mois</strong>.</p></div>`,
  },
  {
    code: 'mp_avenant',
    name: "Avenant à Marché Public",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Avenant modifiant les clauses d'un marché public en cours d'exécution.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'numero_marche', label: "Numéro du marché initial", type: 'text', required: true },
      { key: 'numero_avenant', label: "Numéro de l'avenant", type: 'text', required: true },
      { key: 'objet_avenant', label: "Objet de l'avenant", type: 'textarea', required: true },
      { key: 'impact_financier', label: "Impact financier (FCFA)", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature de l'avenant", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>AVENANT N° {{numero_avenant}} AU MARCHÉ N° {{numero_marche}}</h1><p><strong>Date :</strong> {{date_signature}}</p><h3>OBJET DE L'AVENANT</h3><p>{{objet_avenant}}</p><h3>IMPACT FINANCIER</h3><p>Le présent avenant entraîne une modification du montant du marché de : <strong>{{impact_financier}} FCFA</strong>.</p><h3>APPROBATION</h3><p>Le présent avenant est approuvé et signé par les deux parties en présence des témoins désignés.</p></div>`,
  },
  {
    code: 'mp_ordre_service',
    name: "Ordre de Service Marché Public",
    category: 'juridique_admin',
    price: 4000,
    priceMax: 12000,
    description: "Ordre de service prescrivant au titulaire le commencement ou la modification des prestations.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'numero_os', label: "Numéro de l'ordre de service", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'objet_os', label: "Objet de l'ordre de service", type: 'textarea', required: true },
      { key: 'date_prise_effet', label: "Date de prise d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ORDRE DE SERVICE N° {{numero_os}}</h1><p>À : <strong>{{titulaire}}</strong></p><p><strong>Date de prise d'effet :</strong> {{date_prise_effet}}</p><h3>OBJET</h3><p>{{objet_os}}</p><p>Le titulaire est tenu d'exécuter les instructions contenues dans le présent ordre de service dans les délais impartis.</p><p>Fait en deux exemplaires.</p></div>`,
  },
  {
    code: 'mp_rapport_suivi_execution',
    name: "Rapport de Suivi d'Exécution",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 25000,
    description: "Rapport périodique de suivi de l'exécution physique et financière d'un marché public.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'numero_marche', label: "Numéro du marché", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'taux_execution_physique', label: "Taux d'exécution physique (%)", type: 'text', required: true },
      { key: 'observations', label: "Observations et recommandations", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE SUIVI D'EXÉCUTION</h1><p><strong>Marché N° :</strong> {{numero_marche}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Période :</strong> {{periode_rapport}}</p><h3>ÉTAT D'AVANCEMENT</h3><p>Taux d'exécution physique : <strong>{{taux_execution_physique}}%</strong></p><h3>OBSERVATIONS ET RECOMMANDATIONS</h3><p>{{observations}}</p></div>`,
  },
  {
    code: 'mp_pv_reception_provisoire',
    name: "Procès-Verbal de Réception Provisoire",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 25000,
    description: "PV constatant la réception provisoire des travaux ou prestations avec réserves éventuelles.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 89,
    fieldsJson: F([
      { key: 'numero_marche', label: "Numéro du marché", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'date_reception', label: "Date de la réception provisoire", type: 'date', required: true },
      { key: 'reserves_formulees', label: "Réserves formulées (le cas échéant)", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>PROCÈS-VERBAL DE RÉCEPTION PROVISOIRE</h1><p><strong>Marché N° :</strong> {{numero_marche}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Objet :</strong> {{objet_marche}}</p><p><strong>Date de réception :</strong> {{date_reception}}</p><h3>CONSTAT</h3><p>La commission de réception a procédé ce jour à la visite des ouvrages/prestations et constate que ceux-ci sont conformes aux prescriptions du marché.</p><h3>RÉSERVES</h3><p>{{reserves_formulees}}</p></div>`,
  },
  {
    code: 'mp_pv_reception_definitive',
    name: "Procès-Verbal de Réception Définitive",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 25000,
    description: "PV de réception définitive clôturant le marché après levée de toutes les réserves.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 87,
    fieldsJson: F([
      { key: 'numero_marche', label: "Numéro du marché", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché", type: 'textarea', required: true },
      { key: 'date_reception_definitive', label: "Date de la réception définitive", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÈS-VERBAL DE RÉCEPTION DÉFINITIVE</h1><p><strong>Marché N° :</strong> {{numero_marche}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Objet :</strong> {{objet_marche}}</p><p><strong>Date :</strong> {{date_reception_definitive}}</p><h3>CONSTAT DÉFINITIF</h3><p>La commission de réception constate que toutes les réserves formulées lors de la réception provisoire ont été levées et que les ouvrages/prestations sont conformes à toutes les exigences du marché.</p><p>Le présent PV emporte libération définitive de la caution de bonne exécution.</p></div>`,
  },
  {
    code: 'mp_decompte_general_definitif',
    name: "Décompte Général et Définitif",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 35000,
    description: "Document de règlement final arrêtant le montant définitif des sommes dues au titulaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'numero_marche', label: "Numéro du marché", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du marché", type: 'text', required: true },
      { key: 'montant_initial', label: "Montant initial du marché (FCFA)", type: 'text', required: true },
      { key: 'montant_definitif', label: "Montant définitif (FCFA)", type: 'text', required: true },
      { key: 'date_etablissement', label: "Date d'établissement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DÉCOMPTE GÉNÉRAL ET DÉFINITIF</h1><p><strong>Marché N° :</strong> {{numero_marche}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Date :</strong> {{date_etablissement}}</p><h3>RÉCAPITULATION FINANCIÈRE</h3><table><tr><td>Montant initial du marché</td><td>{{montant_initial}} FCFA</td></tr><tr><td><strong>Montant définitif arrêté</strong></td><td><strong>{{montant_definitif}} FCFA</strong></td></tr></table><p>Le présent décompte est établi en accord entre les parties et vaut solde de tout compte.</p></div>`,
  },
  {
    code: 'mp_contrat_cadre_bdc',
    name: "Contrat-Cadre avec Bons de Commande",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 55000,
    description: "Contrat-cadre établissant les conditions générales d'achat avec émission de bons de commande successifs.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'autorite_contractante', label: "Autorité contractante", type: 'text', required: true },
      { key: 'titulaire', label: "Titulaire du contrat-cadre", type: 'text', required: true },
      { key: 'objet_contrat', label: "Objet du contrat-cadre", type: 'textarea', required: true },
      { key: 'montant_maximum', label: "Montant maximum annuel (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (ans)", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT-CADRE AVEC BONS DE COMMANDE</h1><p><strong>Autorité contractante :</strong> {{autorite_contractante}}</p><p><strong>Titulaire :</strong> {{titulaire}}</p><h3>ARTICLE 1 — OBJET</h3><p>{{objet_contrat}}</p><h3>ARTICLE 2 — MONTANT ET DURÉE</h3><p>Montant maximum annuel : <strong>{{montant_maximum}} FCFA</strong></p><p>Durée du contrat-cadre : <strong>{{duree_contrat}} an(s)</strong></p><h3>ARTICLE 3 — BONS DE COMMANDE</h3><p>Les commandes seront passées par émission de bons de commande individuels dans la limite du montant maximum fixé ci-dessus.</p><p>Signé le {{date_signature}}</p></div>`,
  },
  {
    code: 'ppp_concession_service_public',
    name: "Convention de Concession de Service Public",
    category: 'commercial_financier',
    price: 25000,
    priceMax: 80000,
    description: "Convention confiant à un opérateur privé la gestion d'un service public pour une durée déterminée.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'autorite_concedante', label: "Autorité concédante", type: 'text', required: true },
      { key: 'concessionnaire', label: "Concessionnaire", type: 'text', required: true },
      { key: 'objet_concession', label: "Objet de la concession", type: 'textarea', required: true },
      { key: 'duree_concession', label: "Durée de la concession (ans)", type: 'text', required: true },
      { key: 'date_prise_effet', label: "Date de prise d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE CONCESSION DE SERVICE PUBLIC</h1><p><strong>Autorité concédante :</strong> {{autorite_concedante}}</p><p><strong>Concessionnaire :</strong> {{concessionnaire}}</p><h3>ARTICLE 1 — OBJET DE LA CONCESSION</h3><p>{{objet_concession}}</p><h3>ARTICLE 2 — DURÉE</h3><p>La présente convention est conclue pour une durée de <strong>{{duree_concession}} ans</strong> à compter du {{date_prise_effet}}.</p><h3>ARTICLE 3 — OBLIGATIONS DU CONCESSIONNAIRE</h3><p>Le concessionnaire s'engage à assurer la continuité, l'égalité et l'adaptabilité du service public concédé.</p></div>`,
  },
  {
    code: 'ppp_contrat_bot',
    name: "Contrat BOT (Build-Operate-Transfer)",
    category: 'commercial_financier',
    price: 25000,
    priceMax: 80000,
    description: "Contrat de partenariat pour la construction, l'exploitation et le transfert d'une infrastructure publique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'autorite_publique', label: "Autorité publique contractante", type: 'text', required: true },
      { key: 'operateur_prive', label: "Opérateur privé", type: 'text', required: true },
      { key: 'infrastructure', label: "Infrastructure à réaliser", type: 'textarea', required: true },
      { key: 'duree_exploitation', label: "Durée d'exploitation avant transfert (ans)", type: 'text', required: true },
      { key: 'investissement_total', label: "Investissement total prévu (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT BOT — BUILD-OPERATE-TRANSFER</h1><p><strong>Autorité publique :</strong> {{autorite_publique}}</p><p><strong>Opérateur privé :</strong> {{operateur_prive}}</p><h3>ARTICLE 1 — INFRASTRUCTURE</h3><p>{{infrastructure}}</p><h3>ARTICLE 2 — PHASES DU PROJET</h3><p><strong>Phase 1 — BUILD :</strong> Construction par l'opérateur privé à ses frais.</p><p><strong>Phase 2 — OPERATE :</strong> Exploitation pendant {{duree_exploitation}} ans.</p><p><strong>Phase 3 — TRANSFER :</strong> Transfert à l'État à terme.</p><h3>ARTICLE 3 — INVESTISSEMENT</h3><p>Investissement total : <strong>{{investissement_total}} FCFA</strong></p></div>`,
  },
  {
    code: 'ppp_contrat_boo',
    name: "Contrat BOO (Build-Own-Operate)",
    category: 'commercial_financier',
    price: 22000,
    priceMax: 70000,
    description: "Contrat de partenariat pour la construction, la propriété permanente et l'exploitation d'une infrastructure.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'autorite_publique', label: "Autorité publique partenaire", type: 'text', required: true },
      { key: 'investisseur_prive', label: "Investisseur privé", type: 'text', required: true },
      { key: 'infrastructure', label: "Nature de l'infrastructure", type: 'textarea', required: true },
      { key: 'montant_investissement', label: "Montant de l'investissement (FCFA)", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT BOO — BUILD-OWN-OPERATE</h1><p><strong>Autorité publique :</strong> {{autorite_publique}}</p><p><strong>Investisseur privé :</strong> {{investisseur_prive}}</p><h3>ARTICLE 1 — OBJET</h3><p>{{infrastructure}}</p><h3>ARTICLE 2 — PROPRIÉTÉ</h3><p>L'investisseur privé reste propriétaire de l'infrastructure qu'il finance, construit et exploite à ses risques et périls.</p><h3>ARTICLE 3 — FINANCEMENT</h3><p>Montant total de l'investissement : <strong>{{montant_investissement}} FCFA</strong></p><p>Signé le : {{date_signature}}</p></div>`,
  },
  {
    code: 'ppp_accord_partenariat_strategique',
    name: "Accord de Partenariat Stratégique Public-Privé",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 65000,
    description: "Accord cadre définissant les modalités d'un partenariat stratégique entre entité publique et partenaire privé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'partenaire_public', label: "Partenaire public", type: 'text', required: true },
      { key: 'partenaire_prive', label: "Partenaire privé", type: 'text', required: true },
      { key: 'axes_partenariat', label: "Axes stratégiques du partenariat", type: 'textarea', required: true },
      { key: 'duree_accord', label: "Durée de l'accord (ans)", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT STRATÉGIQUE PUBLIC-PRIVÉ</h1><p><strong>Partenaire public :</strong> {{partenaire_public}}</p><p><strong>Partenaire privé :</strong> {{partenaire_prive}}</p><h3>ARTICLE 1 — AXES STRATÉGIQUES</h3><p>{{axes_partenariat}}</p><h3>ARTICLE 2 — GOUVERNANCE</h3><p>Un comité de pilotage mixte se réunit trimestriellement pour suivre la mise en oeuvre du partenariat.</p><h3>ARTICLE 3 — DURÉE</h3><p>Le présent accord est conclu pour une durée de <strong>{{duree_accord}} ans</strong> renouvelable.</p><p>Fait le {{date_signature}}</p></div>`,
  },
  {
    code: 'ppp_delegation_service_public',
    name: "Convention de Délégation de Service Public",
    category: 'commercial_financier',
    price: 22000,
    priceMax: 70000,
    description: "Convention par laquelle une personne publique confie à un délégataire privé la gestion d'un service public.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'delegant', label: "Personne publique délégante", type: 'text', required: true },
      { key: 'delegataire', label: "Délégataire privé", type: 'text', required: true },
      { key: 'service_concerne', label: "Service public concerné", type: 'textarea', required: true },
      { key: 'duree_delegation', label: "Durée de la délégation (ans)", type: 'text', required: true },
      { key: 'redevance_annuelle', label: "Redevance annuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE DÉLÉGATION DE SERVICE PUBLIC</h1><p><strong>Délégant :</strong> {{delegant}}</p><p><strong>Délégataire :</strong> {{delegataire}}</p><h3>ARTICLE 1 — OBJET DE LA DÉLÉGATION</h3><p>{{service_concerne}}</p><h3>ARTICLE 2 — DURÉE</h3><p>La présente délégation est accordée pour une période de <strong>{{duree_delegation}} ans</strong>.</p><h3>ARTICLE 3 — REDEVANCE</h3><p>Le délégataire versera au délégant une redevance annuelle de <strong>{{redevance_annuelle}} FCFA</strong>.</p></div>`,
  },
  {
    code: 'ppp_contrat_gestion_deleguee',
    name: "Contrat de Gestion Déléguée",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 58000,
    description: "Contrat confiant la gestion opérationnelle d'un actif ou service public à un opérateur privé spécialisé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'mandant_public', label: "Mandant public", type: 'text', required: true },
      { key: 'gestionnaire_delegue', label: "Gestionnaire délégué", type: 'text', required: true },
      { key: 'actif_gere', label: "Actif ou service à gérer", type: 'textarea', required: true },
      { key: 'honoraires_gestion', label: "Honoraires de gestion annuels (FCFA)", type: 'text', required: true },
      { key: 'date_demarrage', label: "Date de démarrage", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GESTION DÉLÉGUÉE</h1><p><strong>Mandant :</strong> {{mandant_public}}</p><p><strong>Gestionnaire délégué :</strong> {{gestionnaire_delegue}}</p><h3>ARTICLE 1 — PÉRIMÈTRE DE GESTION</h3><p>{{actif_gere}}</p><h3>ARTICLE 2 — RÉMUNÉRATION</h3><p>Honoraires de gestion annuels : <strong>{{honoraires_gestion}} FCFA</strong></p><h3>ARTICLE 3 — PRISE D'EFFET</h3><p>Le présent contrat prend effet le {{date_demarrage}}.</p></div>`,
  },
  {
    code: 'ppp_accord_performance',
    name: "Accord de Performance PPP",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 55000,
    description: "Accord fixant les objectifs de performance mesurables auxquels est soumis le partenaire privé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'autorite_publique', label: "Autorité publique", type: 'text', required: true },
      { key: 'partenaire_prive', label: "Partenaire privé", type: 'text', required: true },
      { key: 'indicateurs_performance', label: "Indicateurs clés de performance", type: 'textarea', required: true },
      { key: 'penalites_non_atteinte', label: "Pénalités en cas de non-atteinte", type: 'textarea', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entrée en vigueur", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PERFORMANCE PPP</h1><p><strong>Autorité publique :</strong> {{autorite_publique}}</p><p><strong>Partenaire privé :</strong> {{partenaire_prive}}</p><h3>ARTICLE 1 — INDICATEURS DE PERFORMANCE</h3><p>{{indicateurs_performance}}</p><h3>ARTICLE 2 — PÉNALITÉS</h3><p>{{penalites_non_atteinte}}</p><h3>ARTICLE 3 — RÉVISION ANNUELLE</h3><p>Les indicateurs sont révisés annuellement par le comité de suivi conjoint.</p><p>En vigueur le : {{date_entree_vigueur}}</p></div>`,
  },
  {
    code: 'ppp_contrat_affermage',
    name: "Contrat d'Affermage",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 65000,
    description: "Contrat par lequel une personne publique confie l'exploitation d'un service à un fermier privé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'affermant', label: "Collectivité affermante", type: 'text', required: true },
      { key: 'fermier', label: "Fermier (opérateur privé)", type: 'text', required: true },
      { key: 'service_affermage', label: "Service objet de l'affermage", type: 'textarea', required: true },
      { key: 'duree_affermage', label: "Durée du contrat (ans)", type: 'text', required: true },
      { key: 'redevance_affermage', label: "Redevance d'affermage annuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'AFFERMAGE</h1><p><strong>Collectivité affermante :</strong> {{affermant}}</p><p><strong>Fermier :</strong> {{fermier}}</p><h3>ARTICLE 1 — OBJET</h3><p>{{service_affermage}}</p><h3>ARTICLE 2 — DURÉE</h3><p>Le contrat est conclu pour <strong>{{duree_affermage}} ans</strong>.</p><h3>ARTICLE 3 — REDEVANCE D'AFFERMAGE</h3><p>Le fermier s'acquitte d'une redevance annuelle de <strong>{{redevance_affermage}} FCFA</strong> auprès de la collectivité affermante.</p></div>`,
  },
  {
    code: 'ppp_convention_exploitation_reseau',
    name: "Convention d'Exploitation de Réseau",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 65000,
    description: "Convention autorisant un opérateur privé à exploiter un réseau d'infrastructure publique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'autorite_concedante', label: "Autorité concédante", type: 'text', required: true },
      { key: 'exploitant', label: "Exploitant du réseau", type: 'text', required: true },
      { key: 'reseau_concerne', label: "Réseau concerné", type: 'textarea', required: true },
      { key: 'perimetre_exploitation', label: "Périmètre géographique d'exploitation", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début d'exploitation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D'EXPLOITATION DE RÉSEAU</h1><p><strong>Autorité concédante :</strong> {{autorite_concedante}}</p><p><strong>Exploitant :</strong> {{exploitant}}</p><h3>ARTICLE 1 — RÉSEAU CONCERNÉ</h3><p>{{reseau_concerne}}</p><h3>ARTICLE 2 — PÉRIMÈTRE</h3><p>Zone d'exploitation : <strong>{{perimetre_exploitation}}</strong></p><h3>ARTICLE 3 — PRISE D'EFFET</h3><p>L'exploitation du réseau débute le {{date_debut}}.</p></div>`,
  },
  {
    code: 'ppp_accord_financement_projet',
    name: "Accord de Financement de Projet (Project Finance)",
    category: 'commercial_financier',
    price: 25000,
    priceMax: 80000,
    description: "Accord structurant le financement hors bilan d'un projet d'infrastructure par des flux futurs.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'porteur_projet', label: "Porteur de projet (SPV)", type: 'text', required: true },
      { key: 'preteurs', label: "Prêteurs (banques / bailleurs)", type: 'text', required: true },
      { key: 'description_projet', label: "Description du projet", type: 'textarea', required: true },
      { key: 'montant_financement', label: "Montant total du financement (FCFA)", type: 'text', required: true },
      { key: 'duree_remboursement', label: "Durée de remboursement (ans)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FINANCEMENT DE PROJET — PROJECT FINANCE</h1><p><strong>Véhicule de projet (SPV) :</strong> {{porteur_projet}}</p><p><strong>Prêteurs :</strong> {{preteurs}}</p><h3>ARTICLE 1 — DESCRIPTION DU PROJET</h3><p>{{description_projet}}</p><h3>ARTICLE 2 — STRUCTURE FINANCIÈRE</h3><p>Montant total du financement : <strong>{{montant_financement}} FCFA</strong></p><p>Durée de remboursement : <strong>{{duree_remboursement}} ans</strong></p><h3>ARTICLE 3 — RECOURS AUX FLUX DE TRÉSORERIE</h3><p>Le remboursement est exclusivement assuré par les flux de trésorerie générés par le projet.</p></div>`,
  },
  {
    code: 'ppp_contrat_garantie_souveraine',
    name: "Contrat de Garantie Souveraine",
    category: 'commercial_financier',
    price: 22000,
    priceMax: 70000,
    description: "Contrat par lequel l'État accorde sa garantie souveraine pour sécuriser un financement privé de projet.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'etat_garant', label: "État garant", type: 'text', required: true },
      { key: 'beneficiaire_garantie', label: "Bénéficiaire de la garantie", type: 'text', required: true },
      { key: 'objet_garantie', label: "Obligation garantie", type: 'textarea', required: true },
      { key: 'montant_garanti', label: "Montant garanti (FCFA)", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GARANTIE SOUVERAINE</h1><p><strong>État garant :</strong> {{etat_garant}}</p><p><strong>Bénéficiaire :</strong> {{beneficiaire_garantie}}</p><h3>ARTICLE 1 — OBJET DE LA GARANTIE</h3><p>{{objet_garantie}}</p><h3>ARTICLE 2 — MONTANT GARANTI</h3><p>Le présent engagement de garantie porte sur un montant maximum de <strong>{{montant_garanti}} FCFA</strong>.</p><p>Signé le : {{date_signature}}</p></div>`,
  },
  {
    code: 'ppp_accord_partage_risques',
    name: "Accord de Partage des Risques PPP",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 55000,
    description: "Accord définissant la répartition des risques entre partenaire public et partenaire privé dans un PPP.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'partenaire_public', label: "Partenaire public", type: 'text', required: true },
      { key: 'partenaire_prive', label: "Partenaire privé", type: 'text', required: true },
      { key: 'risques_secteur_public', label: "Risques assumés par le secteur public", type: 'textarea', required: true },
      { key: 'risques_secteur_prive', label: "Risques assumés par le secteur privé", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTAGE DES RISQUES PPP</h1><p><strong>Partenaire public :</strong> {{partenaire_public}}</p><p><strong>Partenaire privé :</strong> {{partenaire_prive}}</p><h3>ARTICLE 1 — RISQUES SECTEUR PUBLIC</h3><p>{{risques_secteur_public}}</p><h3>ARTICLE 2 — RISQUES SECTEUR PRIVÉ</h3><p>{{risques_secteur_prive}}</p><h3>ARTICLE 3 — REVUE PÉRIODIQUE</h3><p>La matrice des risques est révisée tous les deux ans ou en cas de changement significatif du contexte.</p><p>Accord signé le : {{date_accord}}</p></div>`,
  },
  {
    code: 'ppp_convention_etablissement',
    name: "Convention d'Établissement",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 65000,
    description: "Convention accordant à un investisseur privé des garanties et avantages spécifiques pour son établissement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 81,
    fieldsJson: F([
      { key: 'etat_hote', label: "État hôte", type: 'text', required: true },
      { key: 'investisseur', label: "Investisseur", type: 'text', required: true },
      { key: 'secteur_activite', label: "Secteur d'activité", type: 'textarea', required: true },
      { key: 'avantages_accordes', label: "Avantages et garanties accordés", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D'ÉTABLISSEMENT</h1><p><strong>État hôte :</strong> {{etat_hote}}</p><p><strong>Investisseur :</strong> {{investisseur}}</p><h3>ARTICLE 1 — SECTEUR D'ACTIVITÉ</h3><p>{{secteur_activite}}</p><h3>ARTICLE 2 — AVANTAGES ET GARANTIES</h3><p>{{avantages_accordes}}</p><h3>ARTICLE 3 — STABILITÉ</h3><p>Les avantages accordés sont garantis pour la durée de la convention et ne peuvent être remis en cause par des modifications législatives ou réglementaires ultérieures.</p><p>Signé le : {{date_signature}}</p></div>`,
  },
  {
    code: 'ppp_protocole_investissement',
    name: "Protocole d'Investissement Direct",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 58000,
    description: "Protocole encadrant un investissement direct d'un opérateur privé dans un projet public majeur.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'autorite_publique', label: "Autorité publique", type: 'text', required: true },
      { key: 'investisseur', label: "Investisseur direct", type: 'text', required: true },
      { key: 'projet_investissement', label: "Projet d'investissement", type: 'textarea', required: true },
      { key: 'montant_investissement', label: "Montant de l'investissement (FCFA)", type: 'text', required: true },
      { key: 'date_protocole', label: "Date du protocole", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PROTOCOLE D'INVESTISSEMENT DIRECT</h1><p><strong>Autorité publique :</strong> {{autorite_publique}}</p><p><strong>Investisseur :</strong> {{investisseur}}</p><h3>ARTICLE 1 — PROJET</h3><p>{{projet_investissement}}</p><h3>ARTICLE 2 — MONTANT DE L'INVESTISSEMENT</h3><p>Engagement financier total : <strong>{{montant_investissement}} FCFA</strong></p><h3>ARTICLE 3 — CALENDRIER</h3><p>Les parties conviennent d'un plan de mobilisation des fonds et d'un calendrier de mise en oeuvre détaillé en annexe.</p><p>Signé le : {{date_protocole}}</p></div>`,
  },
  {
    code: 'ppp_accord_zes',
    name: "Accord de Zone Économique Spéciale",
    category: 'commercial_financier',
    price: 22000,
    priceMax: 70000,
    description: "Accord régissant l'implantation et les avantages des investisseurs dans une zone économique spéciale.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'gestionnaire_zes', label: "Gestionnaire de la ZES", type: 'text', required: true },
      { key: 'entreprise_beneficiaire', label: "Entreprise bénéficiaire", type: 'text', required: true },
      { key: 'localisation_zes', label: "Localisation de la ZES", type: 'text', required: true },
      { key: 'avantages_fiscaux', label: "Avantages fiscaux et douaniers", type: 'textarea', required: true },
      { key: 'duree_accord', label: "Durée de l'accord (ans)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE ZONE ÉCONOMIQUE SPÉCIALE</h1><p><strong>Gestionnaire ZES :</strong> {{gestionnaire_zes}}</p><p><strong>Entreprise bénéficiaire :</strong> {{entreprise_beneficiaire}}</p><p><strong>Localisation :</strong> {{localisation_zes}}</p><h3>ARTICLE 1 — AVANTAGES ACCORDÉS</h3><p>{{avantages_fiscaux}}</p><h3>ARTICLE 2 — DURÉE</h3><p>Le présent accord est valable pour une durée de <strong>{{duree_accord}} ans</strong>.</p></div>`,
  },
  {
    code: 'ppp_convention_fiscale_investissement',
    name: "Convention Fiscale d'Investissement",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 65000,
    description: "Convention accordant des avantages fiscaux spécifiques à un investisseur dans le cadre d'un PPP.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'etat', label: "État contractant", type: 'text', required: true },
      { key: 'investisseur', label: "Investisseur bénéficiaire", type: 'text', required: true },
      { key: 'nature_investissement', label: "Nature de l'investissement", type: 'textarea', required: true },
      { key: 'avantages_fiscaux', label: "Avantages fiscaux consentis", type: 'textarea', required: true },
      { key: 'duree_convention', label: "Durée de la convention (ans)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION FISCALE D'INVESTISSEMENT</h1><p><strong>État :</strong> {{etat}}</p><p><strong>Investisseur :</strong> {{investisseur}}</p><h3>ARTICLE 1 — NATURE DE L'INVESTISSEMENT</h3><p>{{nature_investissement}}</p><h3>ARTICLE 2 — AVANTAGES FISCAUX</h3><p>{{avantages_fiscaux}}</p><h3>ARTICLE 3 — DURÉE ET CONDITIONS DE RENOUVELLEMENT</h3><p>La présente convention est valable pour <strong>{{duree_convention}} ans</strong> à compter de sa signature.</p></div>`,
  },
  {
    code: 'ppp_accord_code_investissements',
    name: "Accord de Code des Investissements",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 58000,
    description: "Accord accordant à un investisseur les avantages prévus par le Code des investissements national.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'centre_promotion_investissements', label: "Centre de promotion des investissements", type: 'text', required: true },
      { key: 'entreprise_agreee', label: "Entreprise agréée", type: 'text', required: true },
      { key: 'secteur_eligible', label: "Secteur éligible", type: 'text', required: true },
      { key: 'regime_agree', label: "Régime d'agrément accordé", type: 'textarea', required: true },
      { key: 'date_agrement', label: "Date d'agrément", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CODE DES INVESTISSEMENTS</h1><p><strong>Organisme :</strong> {{centre_promotion_investissements}}</p><p><strong>Entreprise agréée :</strong> {{entreprise_agreee}}</p><p><strong>Secteur :</strong> {{secteur_eligible}}</p><h3>RÉGIME D'AGRÉMENT</h3><p>{{regime_agree}}</p><p>Date d'agrément : <strong>{{date_agrement}}</strong></p></div>`,
  },
  {
    code: 'ppp_contrat_service_long_terme',
    name: "Contrat de Service à Long Terme",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 55000,
    description: "Contrat pluriannuel de prestation de service couvrant la maintenance et l'exploitation d'actifs publics.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'donneur_ordre_public', label: "Donneur d'ordre public", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire de service", type: 'text', required: true },
      { key: 'prestations_couvertes', label: "Prestations couvertes", type: 'textarea', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (ans)", type: 'text', required: true },
      { key: 'valeur_contractuelle', label: "Valeur contractuelle totale (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE À LONG TERME</h1><p><strong>Donneur d'ordre :</strong> {{donneur_ordre_public}}</p><p><strong>Prestataire :</strong> {{prestataire}}</p><h3>ARTICLE 1 — PÉRIMÈTRE DES PRESTATIONS</h3><p>{{prestations_couvertes}}</p><h3>ARTICLE 2 — DURÉE ET VALEUR</h3><p>Durée : <strong>{{duree_contrat}} ans</strong> — Valeur totale : <strong>{{valeur_contractuelle}} FCFA</strong></p></div>`,
  },
  {
    code: 'ppp_accord_niveau_service_public',
    name: "Accord de Niveau de Service Public",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 48000,
    description: "Accord (SLA public) définissant les niveaux minimaux de service à garantir dans un PPP.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'autorite_regulatrice', label: "Autorité régulatrice", type: 'text', required: true },
      { key: 'operateur_prive', label: "Opérateur privé", type: 'text', required: true },
      { key: 'niveaux_service', label: "Niveaux de service garantis", type: 'textarea', required: true },
      { key: 'mecanisme_sanction', label: "Mécanisme de sanction en cas de défaillance", type: 'textarea', required: true },
      { key: 'date_prise_effet', label: "Date de prise d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE NIVEAU DE SERVICE PUBLIC</h1><p><strong>Autorité régulatrice :</strong> {{autorite_regulatrice}}</p><p><strong>Opérateur privé :</strong> {{operateur_prive}}</p><h3>ARTICLE 1 — NIVEAUX DE SERVICE</h3><p>{{niveaux_service}}</p><h3>ARTICLE 2 — SANCTIONS</h3><p>{{mecanisme_sanction}}</p><h3>ARTICLE 3 — SUIVI</h3><p>Un rapport de conformité aux niveaux de service est produit mensuellement.</p><p>En vigueur le : {{date_prise_effet}}</p></div>`,
  },
  {
    code: 'ppp_convention_acces_infrastructures',
    name: "Convention d'Accès aux Infrastructures",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 48000,
    description: "Convention réglementant l'accès des tiers aux infrastructures publiques exploitées en PPP.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'proprietaire_infrastructure', label: "Propriétaire de l'infrastructure", type: 'text', required: true },
      { key: 'utilisateur_acces', label: "Utilisateur demandant l'accès", type: 'text', required: true },
      { key: 'infrastructure_concernee', label: "Infrastructure concernée", type: 'textarea', required: true },
      { key: 'conditions_acces', label: "Conditions techniques et tarifaires d'accès", type: 'textarea', required: true },
      { key: 'date_convention', label: "Date de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION D'ACCÈS AUX INFRASTRUCTURES</h1><p><strong>Propriétaire de l'infrastructure :</strong> {{proprietaire_infrastructure}}</p><p><strong>Utilisateur :</strong> {{utilisateur_acces}}</p><h3>ARTICLE 1 — INFRASTRUCTURE CONCERNÉE</h3><p>{{infrastructure_concernee}}</p><h3>ARTICLE 2 — CONDITIONS D'ACCÈS</h3><p>{{conditions_acces}}</p><p>Signé le : {{date_convention}}</p></div>`,
  },
  {
    code: 'ppp_accord_remuneration_variable',
    name: "Accord de Rémunération Variable (Shadow Toll)",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 65000,
    description: "Accord de rémunération indexée sur la fréquentation d'une infrastructure (péage virtuel / shadow toll).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'autorite_publique', label: "Autorité publique payeuse", type: 'text', required: true },
      { key: 'operateur_infrastructure', label: "Opérateur de l'infrastructure", type: 'text', required: true },
      { key: 'infrastructure', label: "Infrastructure concernée", type: 'textarea', required: true },
      { key: 'tarif_unitaire', label: "Tarif unitaire de rémunération (FCFA/passage)", type: 'text', required: true },
      { key: 'plafond_annuel', label: "Plafond de rémunération annuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉMUNÉRATION VARIABLE — SHADOW TOLL</h1><p><strong>Autorité publique :</strong> {{autorite_publique}}</p><p><strong>Opérateur :</strong> {{operateur_infrastructure}}</p><h3>ARTICLE 1 — INFRASTRUCTURE</h3><p>{{infrastructure}}</p><h3>ARTICLE 2 — MODALITÉS DE RÉMUNÉRATION</h3><p>Tarif unitaire : <strong>{{tarif_unitaire}} FCFA par passage</strong></p><p>Plafond annuel : <strong>{{plafond_annuel}} FCFA</strong></p><h3>ARTICLE 3 — COMPTAGE</h3><p>Un système de comptage certifié et indépendant enregistre les données servant de base à la facturation mensuelle.</p></div>`,
  },
  {
    code: 'ppp_contrat_maintenance_infrastructure',
    name: "Contrat de Maintenance d'Infrastructure Publique",
    category: 'commercial_financier',
    price: 15000,
    priceMax: 48000,
    description: "Contrat de maintenance préventive et corrective d'infrastructures publiques confié à un opérateur privé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 81,
    fieldsJson: F([
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage public", type: 'text', required: true },
      { key: 'mainteneur', label: "Entreprise de maintenance", type: 'text', required: true },
      { key: 'infrastructure_maintenue', label: "Infrastructure à maintenir", type: 'textarea', required: true },
      { key: 'perimetre_maintenance', label: "Périmètre des interventions", type: 'textarea', required: true },
      { key: 'budget_annuel_maintenance', label: "Budget annuel de maintenance (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MAINTENANCE D'INFRASTRUCTURE PUBLIQUE</h1><p><strong>Maître d'ouvrage :</strong> {{maitre_ouvrage}}</p><p><strong>Mainteneur :</strong> {{mainteneur}}</p><h3>ARTICLE 1 — INFRASTRUCTURE</h3><p>{{infrastructure_maintenue}}</p><h3>ARTICLE 2 — PÉRIMÈTRE DES INTERVENTIONS</h3><p>{{perimetre_maintenance}}</p><h3>ARTICLE 3 — FINANCEMENT</h3><p>Budget annuel alloué : <strong>{{budget_annuel_maintenance}} FCFA</strong></p></div>`,
  },
  {
    code: 'ppp_convention_rehabilitation',
    name: "Convention de Réhabilitation d'Infrastructure",
    category: 'commercial_financier',
    price: 20000,
    priceMax: 65000,
    description: "Convention encadrant la réhabilitation d'une infrastructure existante par un partenaire privé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'autorite_publique', label: "Autorité publique", type: 'text', required: true },
      { key: 'partenaire_rehabilitant', label: "Partenaire chargé de la réhabilitation", type: 'text', required: true },
      { key: 'infrastructure_rehabiliter', label: "Infrastructure à réhabiliter", type: 'textarea', required: true },
      { key: 'cout_rehabilitation', label: "Coût total de réhabilitation (FCFA)", type: 'text', required: true },
      { key: 'date_debut_travaux', label: "Date de début des travaux", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE RÉHABILITATION D'INFRASTRUCTURE</h1><p><strong>Autorité publique :</strong> {{autorite_publique}}</p><p><strong>Partenaire rehabilitant :</strong> {{partenaire_rehabilitant}}</p><h3>ARTICLE 1 — INFRASTRUCTURE CONCERNÉE</h3><p>{{infrastructure_rehabiliter}}</p><h3>ARTICLE 2 — COÛT ET FINANCEMENT</h3><p>Coût total estimé : <strong>{{cout_rehabilitation}} FCFA</strong></p><h3>ARTICLE 3 — CALENDRIER</h3><p>Les travaux de réhabilitation démarrent le {{date_debut_travaux}} conformément au calendrier d'exécution annexé.</p></div>`,
  },
  {
    code: 'ppp_accord_transfert_technologique',
    name: "Accord de Transfert Technologique Public-Privé",
    category: 'commercial_financier',
    price: 18000,
    priceMax: 58000,
    description: "Accord organisant le transfert de technologie d'un partenaire privé vers une entité publique dans le cadre d'un PPP.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'entite_publique', label: "Entité publique bénéficiaire", type: 'text', required: true },
      { key: 'detenteur_technologie', label: "Détenteur de la technologie", type: 'text', required: true },
      { key: 'technologie_transferee', label: "Technologie objet du transfert", type: 'textarea', required: true },
      { key: 'modalites_formation', label: "Modalités de formation du personnel", type: 'textarea', required: true },
      { key: 'duree_accord', label: "Durée de l'accord (ans)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSFERT TECHNOLOGIQUE PUBLIC-PRIVÉ</h1><p><strong>Entité publique bénéficiaire :</strong> {{entite_publique}}</p><p><strong>Détenteur de la technologie :</strong> {{detenteur_technologie}}</p><h3>ARTICLE 1 — TECHNOLOGIE TRANSFÉRÉE</h3><p>{{technologie_transferee}}</p><h3>ARTICLE 2 — FORMATION</h3><p>{{modalites_formation}}</p><h3>ARTICLE 3 — DURÉE DE L'ACCORD</h3><p>Le présent accord est conclu pour <strong>{{duree_accord}} ans</strong> à compter de sa signature.</p></div>`,
  },
  {
    code: 'ppp_rapport_performance',
    name: "Rapport de Performance PPP",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 38000,
    description: "Rapport périodique évaluant la performance globale d'un projet PPP par rapport aux objectifs contractuels.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'nom_projet_ppp', label: "Nom du projet PPP", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'indicateurs_atteints', label: "Indicateurs de performance atteints", type: 'textarea', required: true },
      { key: 'ecarts_constates', label: "Écarts et explications", type: 'textarea', required: true },
      { key: 'date_rapport', label: "Date d'établissement du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE PPP</h1><h2>{{nom_projet_ppp}}</h2><p><strong>Période :</strong> {{periode_rapport}}</p><p><strong>Date du rapport :</strong> {{date_rapport}}</p><h3>1. INDICATEURS ATTEINTS</h3><p>{{indicateurs_atteints}}</p><h3>2. ÉCARTS ET ANALYSE</h3><p>{{ecarts_constates}}</p><h3>3. RECOMMANDATIONS</h3><p>Le comité de suivi PPP formule les recommandations nécessaires pour la période à venir.</p></div>`,
  },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 23b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
