import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();

async function main() {
  let created = 0, updated = 0;

  const templates = [
    // â”€â”€â”€ entr_001..015 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      code: 'entr_001',
      name: 'Business Plan Complet',
      description: 'Business plan structurÃ© pour toute nouvelle entreprise ou projet de crÃ©ation.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 15000,
      body: '<h2>{{titre_document}}</h2><p>Entreprise : {{nom_entreprise}}</p><p>Secteur : {{secteur_activite}}</p><p>Date : {{date_redaction}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_entreprise', label: 'Nom de l\'entreprise', type: 'text', required: true },
        { name: 'secteur_activite', label: 'Secteur d\'activitÃ©', type: 'text', required: true },
        { name: 'date_redaction', label: 'Date de rÃ©daction', type: 'date', required: true },
        { name: 'description_projet', label: 'Description du projet', type: 'textarea', required: true },
        { name: 'vision_mission', label: 'Vision et mission', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_002',
      name: 'Ã‰tude de MarchÃ© Startup',
      description: 'Analyse complÃ¨te du marchÃ© cible pour une startup en phase de lancement.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 12000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>MarchÃ© cible : {{marche_cible}}</p><p>Date d\'analyse : {{date_analyse}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'marche_cible', label: 'MarchÃ© cible', type: 'text', required: true },
        { name: 'date_analyse', label: 'Date de l\'analyse', type: 'date', required: true },
        { name: 'analyse_concurrence', label: 'Analyse de la concurrence', type: 'textarea', required: true },
        { name: 'segments_clients', label: 'Segments de clients', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_003',
      name: 'Dossier de LevÃ©e de Fonds',
      description: 'Dossier complet pour une levÃ©e de fonds auprÃ¨s d\'investisseurs.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 20000,
      body: '<h2>{{titre_document}}</h2><p>SociÃ©tÃ© : {{nom_societe}}</p><p>Montant recherchÃ© : {{montant_leve}}</p><p>Date : {{date_dossier}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_societe', label: 'Nom de la sociÃ©tÃ©', type: 'text', required: true },
        { name: 'montant_leve', label: 'Montant Ã  lever', type: 'text', required: true },
        { name: 'date_dossier', label: 'Date du dossier', type: 'date', required: true },
        { name: 'utilisation_fonds', label: 'Utilisation des fonds', type: 'textarea', required: true },
        { name: 'retour_investissement', label: 'Retour sur investissement attendu', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_004',
      name: 'Dossier Incubation / AccÃ©lÃ©ration',
      description: 'Dossier de candidature pour intÃ©grer un programme d\'incubation ou d\'accÃ©lÃ©ration.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 8000,
      body: '<h2>{{titre_document}}</h2><p>Projet : {{nom_projet}}</p><p>Programme visÃ© : {{programme_vise}}</p><p>Date de candidature : {{date_candidature}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_projet', label: 'Nom du projet', type: 'text', required: true },
        { name: 'programme_vise', label: 'Programme visÃ©', type: 'text', required: true },
        { name: 'date_candidature', label: 'Date de candidature', type: 'date', required: true },
        { name: 'probleme_resolu', label: 'ProblÃ¨me rÃ©solu', type: 'textarea', required: true },
        { name: 'equipe_fondatrice', label: 'Ã‰quipe fondatrice', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_005',
      name: 'Plan Financier PrÃ©visionnel',
      description: 'Projection financiÃ¨re sur 3 Ã  5 ans pour une entreprise en crÃ©ation ou en croissance.',
      category: 'entrepreneuriat',
      templateType: 'excel',
      classe: 'A',
      active: true,
      price: 18000,
      body: '<h2>{{titre_document}}</h2><p>Entreprise : {{nom_entreprise}}</p><p>PÃ©riode : {{periode_prevision}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_entreprise', label: 'Nom de l\'entreprise', type: 'text', required: true },
        { name: 'periode_prevision', label: 'PÃ©riode de prÃ©vision', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'hypotheses_financieres', label: 'HypothÃ¨ses financiÃ¨res', type: 'textarea', required: true },
      ],
    },
    {
      code: 'entr_006',
      name: 'Demande de Financement BOAD',
      description: 'Dossier de financement structurÃ© pour soumission Ã  la BOAD ou fonds africains.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 20000,
      body: '<h2>{{titre_document}}</h2><p>Entreprise : {{nom_entreprise}}</p><p>Montant demandÃ© : {{montant_demande}}</p><p>Date de soumission : {{date_soumission}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_entreprise', label: 'Nom de l\'entreprise', type: 'text', required: true },
        { name: 'montant_demande', label: 'Montant demandÃ©', type: 'text', required: true },
        { name: 'date_soumission', label: 'Date de soumission', type: 'date', required: true },
        { name: 'description_projet', label: 'Description du projet', type: 'textarea', required: true },
        { name: 'impact_socioeconomique', label: 'Impact socio-Ã©conomique', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_007',
      name: 'Plan de Franchise',
      description: 'Document structurant le modÃ¨le de franchise : conditions, territoire et redevances.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 14000,
      body: '<h2>{{titre_document}}</h2><p>Franchiseur : {{nom_franchiseur}}</p><p>RÃ©seau : {{nom_reseau}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_franchiseur', label: 'Nom du franchiseur', type: 'text', required: true },
        { name: 'nom_reseau', label: 'Nom du rÃ©seau', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'conditions_franchise', label: 'Conditions de la franchise', type: 'textarea', required: true },
      ],
    },
    {
      code: 'entr_008',
      name: 'Contrat de Franchise',
      description: 'Contrat juridique rÃ©gissant la relation entre franchiseur et franchisÃ©.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 16000,
      body: '<h2>{{titre_document}}</h2><p>Franchiseur : {{nom_franchiseur}}</p><p>FranchisÃ© : {{nom_franchise}}</p><p>Date de signature : {{date_signature}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_franchiseur', label: 'Nom du franchiseur', type: 'text', required: true },
        { name: 'nom_franchise', label: 'Nom du franchisÃ©', type: 'text', required: true },
        { name: 'date_signature', label: 'Date de signature', type: 'date', required: true },
        { name: 'territoire_exclusif', label: 'Territoire exclusif', type: 'text', required: false },
        { name: 'clauses_specifiques', label: 'Clauses spÃ©cifiques', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_009',
      name: 'Pacte d\'AssociÃ©s',
      description: 'Accord entre associÃ©s dÃ©finissant les droits, obligations et rÃ¨gles de gouvernance.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 18000,
      body: '<h2>{{titre_document}}</h2><p>SociÃ©tÃ© : {{nom_societe}}</p><p>AssociÃ©s : {{noms_associes}}</p><p>Date : {{date_signature}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_societe', label: 'Nom de la sociÃ©tÃ©', type: 'text', required: true },
        { name: 'noms_associes', label: 'Noms des associÃ©s', type: 'textarea', required: true },
        { name: 'date_signature', label: 'Date de signature', type: 'date', required: true },
        { name: 'repartition_parts', label: 'RÃ©partition des parts', type: 'textarea', required: true },
      ],
    },
    {
      code: 'entr_010',
      name: 'Plan de Croissance Startup',
      description: 'Feuille de route stratÃ©gique pour accÃ©lÃ©rer la croissance d\'une startup.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 10000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Objectif de croissance : {{objectif_croissance}}</p><p>PÃ©riode : {{periode_plan}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'objectif_croissance', label: 'Objectif de croissance', type: 'text', required: true },
        { name: 'periode_plan', label: 'PÃ©riode du plan', type: 'text', required: true },
        { name: 'axes_strategiques', label: 'Axes stratÃ©giques', type: 'textarea', required: true },
        { name: 'kpis_cibles', label: 'KPIs cibles', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_011',
      name: 'Fiche Produit / Service',
      description: 'PrÃ©sentation dÃ©taillÃ©e d\'un produit ou service destinÃ©e aux prospects et partenaires.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 5000,
      body: '<h2>{{titre_document}}</h2><p>Produit/Service : {{nom_produit}}</p><p>Entreprise : {{nom_entreprise}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_produit', label: 'Nom du produit/service', type: 'text', required: true },
        { name: 'nom_entreprise', label: 'Nom de l\'entreprise', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'description_produit', label: 'Description dÃ©taillÃ©e', type: 'textarea', required: true },
        { name: 'avantages_cles', label: 'Avantages clÃ©s', type: 'textarea', required: false },
      ],
    },
    {
      code: 'entr_012',
      name: 'Ã‰tude de FaisabilitÃ©',
      description: 'Analyse de viabilitÃ© technique, commerciale et financiÃ¨re d\'un projet.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 13000,
      body: '<h2>{{titre_document}}</h2><p>Projet : {{nom_projet}}</p><p>Porteur : {{nom_porteur}}</p><p>Date : {{date_etude}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_projet', label: 'Nom du projet', type: 'text', required: true },
        { name: 'nom_porteur', label: 'Porteur de projet', type: 'text', required: true },
        { name: 'date_etude', label: 'Date de l\'Ã©tude', type: 'date', required: true },
        { name: 'analyse_technique', label: 'Analyse technique', type: 'textarea', required: true },
        { name: 'analyse_commerciale', label: 'Analyse commerciale', type: 'textarea', required: true },
      ],
    },
    {
      code: 'entr_013',
      name: 'Plan Options Actions BSPCE',
      description: 'Plan d\'attribution de Bons de Souscription de Parts de CrÃ©ateur d\'Entreprise.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 19000,
      body: '<h2>{{titre_document}}</h2><p>SociÃ©tÃ© : {{nom_societe}}</p><p>BÃ©nÃ©ficiaires : {{nombre_beneficiaires}}</p><p>Date d\'attribution : {{date_attribution}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_societe', label: 'Nom de la sociÃ©tÃ©', type: 'text', required: true },
        { name: 'nombre_beneficiaires', label: 'Nombre de bÃ©nÃ©ficiaires', type: 'text', required: true },
        { name: 'date_attribution', label: 'Date d\'attribution', type: 'date', required: true },
        { name: 'conditions_exercice', label: 'Conditions d\'exercice', type: 'textarea', required: true },
      ],
    },
    {
      code: 'entr_014',
      name: 'Statuts SARL',
      description: 'Statuts constitutifs pour la crÃ©ation d\'une SociÃ©tÃ© Ã  ResponsabilitÃ© LimitÃ©e.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 17000,
      body: '<h2>{{titre_document}}</h2><p>DÃ©nomination sociale : {{denomination_sociale}}</p><p>Capital social : {{capital_social}}</p><p>Date de constitution : {{date_constitution}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'denomination_sociale', label: 'DÃ©nomination sociale', type: 'text', required: true },
        { name: 'capital_social', label: 'Capital social', type: 'text', required: true },
        { name: 'date_constitution', label: 'Date de constitution', type: 'date', required: true },
        { name: 'siege_social', label: 'SiÃ¨ge social', type: 'text', required: true },
        { name: 'objet_social', label: 'Objet social', type: 'textarea', required: true },
      ],
    },
    {
      code: 'entr_015',
      name: 'DÃ©claration d\'ActivitÃ©',
      description: 'Formulaire de dÃ©claration officielle de dÃ©but ou de modification d\'activitÃ©.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 3000,
      body: '<h2>{{titre_document}}</h2><p>DÃ©clarant : {{nom_declarant}}</p><p>Nature de l\'activitÃ© : {{nature_activite}}</p><p>Date de dÃ©but : {{date_debut}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_declarant', label: 'Nom du dÃ©clarant', type: 'text', required: true },
        { name: 'nature_activite', label: 'Nature de l\'activitÃ©', type: 'text', required: true },
        { name: 'date_debut', label: 'Date de dÃ©but d\'activitÃ©', type: 'date', required: true },
        { name: 'adresse_etablissement', label: 'Adresse de l\'Ã©tablissement', type: 'textarea', required: true },
      ],
    },

    // â”€â”€â”€ lean_canvas_001..010 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      code: 'lean_canvas_001',
      name: 'Lean Canvas Standard',
      description: 'ModÃ¨le Lean Canvas pour valider rapidement une idÃ©e de startup.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 7000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>ProblÃ¨me central : {{probleme_central}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'probleme_central', label: 'ProblÃ¨me central', type: 'textarea', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'solution_proposee', label: 'Solution proposÃ©e', type: 'textarea', required: true },
        { name: 'proposition_valeur', label: 'Proposition de valeur unique', type: 'textarea', required: true },
      ],
    },
    {
      code: 'lean_canvas_002',
      name: 'Lean Canvas â€” Segment Clients',
      description: 'Lean Canvas centrÃ© sur l\'identification et la segmentation des clients cibles.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 7000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Segments clients : {{segments_clients}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'segments_clients', label: 'Segments de clients', type: 'textarea', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'canaux_acquisition', label: 'Canaux d\'acquisition', type: 'textarea', required: false },
      ],
    },
    {
      code: 'lean_canvas_003',
      name: 'Lean Canvas â€” Revenus et CoÃ»ts',
      description: 'Lean Canvas axÃ© sur les flux de revenus et la structure des coÃ»ts.',
      category: 'entrepreneuriat',
      templateType: 'excel',
      classe: 'B',
      active: true,
      price: 8000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Sources de revenus : {{sources_revenus}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'sources_revenus', label: 'Sources de revenus', type: 'textarea', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'structure_couts', label: 'Structure des coÃ»ts', type: 'textarea', required: true },
      ],
    },
    {
      code: 'lean_canvas_004',
      name: 'Lean Canvas â€” Avantage Concurrentiel',
      description: 'Lean Canvas mettant en avant l\'avantage concurrentiel et les mÃ©triques clÃ©s.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 7500,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Avantage concurrentiel : {{avantage_concurrentiel}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'avantage_concurrentiel', label: 'Avantage concurrentiel', type: 'textarea', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'metriques_cles', label: 'MÃ©triques clÃ©s', type: 'textarea', required: false },
      ],
    },
    {
      code: 'lean_canvas_005',
      name: 'Lean Canvas Agro-startup',
      description: 'Lean Canvas adaptÃ© aux startups du secteur agricole et agroalimentaire africain.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 6000,
      body: '<h2>{{titre_document}}</h2><p>Agro-startup : {{nom_startup}}</p><p>FiliÃ¨re : {{filiere_agricole}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'filiere_agricole', label: 'FiliÃ¨re agricole', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'probleme_agricole', label: 'ProblÃ¨me agricole rÃ©solu', type: 'textarea', required: true },
      ],
    },
    {
      code: 'lean_canvas_006',
      name: 'Lean Canvas FinTech Afrique',
      description: 'Lean Canvas spÃ©cialisÃ© pour les startups FinTech opÃ©rant sur les marchÃ©s africains.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 8500,
      body: '<h2>{{titre_document}}</h2><p>FinTech : {{nom_startup}}</p><p>Service financier : {{service_financier}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'service_financier', label: 'Service financier proposÃ©', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'population_cible', label: 'Population cible', type: 'textarea', required: true },
      ],
    },
    {
      code: 'lean_canvas_007',
      name: 'Lean Canvas â€” MVP Validation',
      description: 'Lean Canvas orientÃ© validation du produit minimum viable (MVP).',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 6500,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>MVP : {{description_mvp}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'description_mvp', label: 'Description du MVP', type: 'textarea', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'hypotheses_cles', label: 'HypothÃ¨ses clÃ©s Ã  valider', type: 'textarea', required: true },
      ],
    },
    {
      code: 'lean_canvas_008',
      name: 'Lean Canvas E-commerce',
      description: 'Lean Canvas pour une startup de commerce en ligne ou marketplace.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 6000,
      body: '<h2>{{titre_document}}</h2><p>Plateforme : {{nom_plateforme}}</p><p>CatÃ©gorie : {{categorie_produits}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_plateforme', label: 'Nom de la plateforme', type: 'text', required: true },
        { name: 'categorie_produits', label: 'CatÃ©gorie de produits', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'modele_monetisation', label: 'ModÃ¨le de monÃ©tisation', type: 'textarea', required: true },
      ],
    },
    {
      code: 'lean_canvas_009',
      name: 'Lean Canvas HealthTech',
      description: 'Lean Canvas dÃ©diÃ© aux startups de santÃ© numÃ©rique et mÃ©decine mobile.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 9000,
      body: '<h2>{{titre_document}}</h2><p>HealthTech : {{nom_startup}}</p><p>Solution santÃ© : {{solution_sante}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'solution_sante', label: 'Solution santÃ© proposÃ©e', type: 'textarea', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'partenaires_medicaux', label: 'Partenaires mÃ©dicaux', type: 'textarea', required: false },
      ],
    },
    {
      code: 'lean_canvas_010',
      name: 'Lean Canvas EdTech',
      description: 'Lean Canvas pour les startups d\'Ã©ducation numÃ©rique et e-learning.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 6000,
      body: '<h2>{{titre_document}}</h2><p>EdTech : {{nom_startup}}</p><p>Public cible : {{public_cible}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'public_cible', label: 'Public cible', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'contenu_propose', label: 'Contenu proposÃ©', type: 'textarea', required: true },
      ],
    },

    // â”€â”€â”€ pitch2_001..010 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      code: 'pitch2_001',
      name: 'Pitch Deck Investisseurs',
      description: 'PrÃ©sentation de pitch destinÃ©e aux investisseurs en capital-risque.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 15000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Secteur : {{secteur_activite}}</p><p>Date : {{date_pitch}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'secteur_activite', label: 'Secteur d\'activitÃ©', type: 'text', required: true },
        { name: 'date_pitch', label: 'Date du pitch', type: 'date', required: true },
        { name: 'valeur_ajoutee', label: 'Valeur ajoutÃ©e unique', type: 'textarea', required: true },
        { name: 'montant_recherche', label: 'Montant recherchÃ©', type: 'text', required: true },
      ],
    },
    {
      code: 'pitch2_002',
      name: 'Pitch Deck Concours Startup',
      description: 'Pitch deck optimisÃ© pour les concours et prix de l\'entrepreneuriat.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 10000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Concours : {{nom_concours}}</p><p>Date : {{date_concours}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'nom_concours', label: 'Nom du concours', type: 'text', required: true },
        { name: 'date_concours', label: 'Date du concours', type: 'date', required: true },
        { name: 'impact_attendu', label: 'Impact attendu', type: 'textarea', required: true },
      ],
    },
    {
      code: 'pitch2_003',
      name: 'Pitch Deck Partenaires StratÃ©giques',
      description: 'PrÃ©sentation pour convaincre des partenaires stratÃ©giques ou commerciaux.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 11000,
      body: '<h2>{{titre_document}}</h2><p>Entreprise : {{nom_entreprise}}</p><p>Partenaire visÃ© : {{nom_partenaire}}</p><p>Date : {{date_presentation}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_entreprise', label: 'Nom de l\'entreprise', type: 'text', required: true },
        { name: 'nom_partenaire', label: 'Partenaire visÃ©', type: 'text', required: true },
        { name: 'date_presentation', label: 'Date de prÃ©sentation', type: 'date', required: true },
        { name: 'synergies_proposees', label: 'Synergies proposÃ©es', type: 'textarea', required: true },
      ],
    },
    {
      code: 'pitch2_004',
      name: 'Pitch Deck SÃ©rie A',
      description: 'Pitch deck de SÃ©rie A pour une startup en croissance cherchant un financement majeur.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 18000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Traction actuelle : {{traction_actuelle}}</p><p>Date : {{date_pitch}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'traction_actuelle', label: 'Traction actuelle', type: 'textarea', required: true },
        { name: 'date_pitch', label: 'Date du pitch', type: 'date', required: true },
        { name: 'plan_utilisation_fonds', label: 'Plan d\'utilisation des fonds', type: 'textarea', required: true },
      ],
    },
    {
      code: 'pitch2_005',
      name: 'Pitch Deck Seed Round',
      description: 'Pitch deck pour un tour d\'amorÃ§age (Seed) destinÃ© aux business angels.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 12000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Concept : {{concept_produit}}</p><p>Date : {{date_pitch}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'concept_produit', label: 'Concept produit', type: 'textarea', required: true },
        { name: 'date_pitch', label: 'Date du pitch', type: 'date', required: true },
        { name: 'equipe_fondatrice', label: 'Ã‰quipe fondatrice', type: 'textarea', required: true },
      ],
    },
    {
      code: 'pitch2_006',
      name: 'Pitch Deck Impact Social',
      description: 'Pitch deck pour entreprises Ã  impact social ou projets d\'entrepreneuriat social.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 8000,
      body: '<h2>{{titre_document}}</h2><p>Organisation : {{nom_organisation}}</p><p>Impact visÃ© : {{impact_social}}</p><p>Date : {{date_pitch}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_organisation', label: 'Nom de l\'organisation', type: 'text', required: true },
        { name: 'impact_social', label: 'Impact social visÃ©', type: 'textarea', required: true },
        { name: 'date_pitch', label: 'Date du pitch', type: 'date', required: true },
        { name: 'beneficiaires', label: 'BÃ©nÃ©ficiaires', type: 'textarea', required: false },
      ],
    },
    {
      code: 'pitch2_007',
      name: 'Pitch Deck Fonds Africains',
      description: 'Pitch deck adaptÃ© aux exigences des fonds d\'investissement africains.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 16000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Pays d\'opÃ©ration : {{pays_operation}}</p><p>Date : {{date_pitch}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'pays_operation', label: 'Pays d\'opÃ©ration', type: 'text', required: true },
        { name: 'date_pitch', label: 'Date du pitch', type: 'date', required: true },
        { name: 'modele_economique', label: 'ModÃ¨le Ã©conomique', type: 'textarea', required: true },
      ],
    },
    {
      code: 'pitch2_008',
      name: 'One-Pager Startup',
      description: 'RÃ©sumÃ© exÃ©cutif en une page pour prÃ©senter rapidement une startup.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 5000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>Proposition de valeur : {{proposition_valeur}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'proposition_valeur', label: 'Proposition de valeur', type: 'textarea', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
      ],
    },
    {
      code: 'pitch2_009',
      name: 'Pitch Deck Agri-Entrepreneuriat',
      description: 'Pitch deck pour projets entrepreneuriaux dans le secteur agricole africain.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 9000,
      body: '<h2>{{titre_document}}</h2><p>Projet agricole : {{nom_projet}}</p><p>Zone gÃ©ographique : {{zone_geographique}}</p><p>Date : {{date_pitch}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_projet', label: 'Nom du projet', type: 'text', required: true },
        { name: 'zone_geographique', label: 'Zone gÃ©ographique', type: 'text', required: true },
        { name: 'date_pitch', label: 'Date du pitch', type: 'date', required: true },
        { name: 'produits_agricoles', label: 'Produits agricoles concernÃ©s', type: 'textarea', required: true },
      ],
    },
    {
      code: 'pitch2_010',
      name: 'Pitch Deck Diaspora Invest',
      description: 'Pitch deck ciblant les investisseurs de la diaspora africaine.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 13000,
      body: '<h2>{{titre_document}}</h2><p>Startup : {{nom_startup}}</p><p>OpportunitÃ© : {{opportunite_marche}}</p><p>Date : {{date_pitch}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'opportunite_marche', label: 'OpportunitÃ© de marchÃ©', type: 'textarea', required: true },
        { name: 'date_pitch', label: 'Date du pitch', type: 'date', required: true },
        { name: 'connexion_diaspora', label: 'Connexion avec la diaspora', type: 'textarea', required: false },
      ],
    },

    // â”€â”€â”€ bplan_001..010 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      code: 'bplan_001',
      name: 'Business Plan Restauration',
      description: 'Business plan sectoriel pour un projet de restauration ou de food service.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 12000,
      body: '<h2>{{titre_document}}</h2><p>Restaurant : {{nom_restaurant}}</p><p>Type de cuisine : {{type_cuisine}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_restaurant', label: 'Nom du restaurant', type: 'text', required: true },
        { name: 'type_cuisine', label: 'Type de cuisine', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'concept_restauration', label: 'Concept de restauration', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_002',
      name: 'Business Plan Commerce de DÃ©tail',
      description: 'Business plan pour l\'ouverture d\'un commerce de dÃ©tail ou d\'une boutique.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 11000,
      body: '<h2>{{titre_document}}</h2><p>Commerce : {{nom_commerce}}</p><p>Localisation : {{localisation}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_commerce', label: 'Nom du commerce', type: 'text', required: true },
        { name: 'localisation', label: 'Localisation', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'gamme_produits', label: 'Gamme de produits', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_003',
      name: 'Business Plan Agribusiness',
      description: 'Business plan pour une entreprise agricole, agro-industrielle ou d\'Ã©levage.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 15000,
      body: '<h2>{{titre_document}}</h2><p>Exploitation : {{nom_exploitation}}</p><p>Production : {{type_production}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_exploitation', label: 'Nom de l\'exploitation', type: 'text', required: true },
        { name: 'type_production', label: 'Type de production', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'superficie_exploitation', label: 'Superficie de l\'exploitation', type: 'text', required: false },
        { name: 'marches_cibles', label: 'MarchÃ©s cibles', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_004',
      name: 'Business Plan Technologie / SaaS',
      description: 'Business plan pour une entreprise tech ou un produit SaaS en Afrique.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 17000,
      body: '<h2>{{titre_document}}</h2><p>Startup SaaS : {{nom_startup}}</p><p>Produit : {{nom_produit}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_startup', label: 'Nom de la startup', type: 'text', required: true },
        { name: 'nom_produit', label: 'Nom du produit', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'fonctionnalites_cles', label: 'FonctionnalitÃ©s clÃ©s', type: 'textarea', required: true },
        { name: 'modele_abonnement', label: 'ModÃ¨le d\'abonnement', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_005',
      name: 'Business Plan Immobilier',
      description: 'Business plan pour une activitÃ© immobiliÃ¨re : promotion, location ou gestion.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 18000,
      body: '<h2>{{titre_document}}</h2><p>SociÃ©tÃ© : {{nom_societe}}</p><p>ActivitÃ© : {{type_activite_immo}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_societe', label: 'Nom de la sociÃ©tÃ©', type: 'text', required: true },
        { name: 'type_activite_immo', label: 'Type d\'activitÃ© immobiliÃ¨re', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'localisation_projets', label: 'Localisation des projets', type: 'text', required: false },
        { name: 'strategie_commerciale', label: 'StratÃ©gie commerciale', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_006',
      name: 'Business Plan SantÃ© / Clinique',
      description: 'Business plan pour l\'ouverture d\'une clinique, pharmacie ou cabinet mÃ©dical.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 16000,
      body: '<h2>{{titre_document}}</h2><p>Structure : {{nom_structure}}</p><p>SpÃ©cialitÃ© : {{specialite_medicale}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_structure', label: 'Nom de la structure', type: 'text', required: true },
        { name: 'specialite_medicale', label: 'SpÃ©cialitÃ© mÃ©dicale', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'zone_implantation', label: 'Zone d\'implantation', type: 'text', required: false },
        { name: 'services_offerts', label: 'Services offerts', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_007',
      name: 'Business Plan Transport / Logistique',
      description: 'Business plan pour une activitÃ© de transport, logistique ou livraison.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 13000,
      body: '<h2>{{titre_document}}</h2><p>SociÃ©tÃ© : {{nom_societe}}</p><p>Type de transport : {{type_transport}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_societe', label: 'Nom de la sociÃ©tÃ©', type: 'text', required: true },
        { name: 'type_transport', label: 'Type de transport', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'zone_couverture', label: 'Zone de couverture', type: 'text', required: false },
        { name: 'flotte_prevue', label: 'Flotte prÃ©vue', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_008',
      name: 'Business Plan Ã‰ducation / Formation',
      description: 'Business plan pour un centre de formation, Ã©cole privÃ©e ou plateforme e-learning.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 12000,
      body: '<h2>{{titre_document}}</h2><p>Ã‰tablissement : {{nom_etablissement}}</p><p>Formations : {{types_formations}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_etablissement', label: 'Nom de l\'Ã©tablissement', type: 'text', required: true },
        { name: 'types_formations', label: 'Types de formations', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'public_cible', label: 'Public cible', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_009',
      name: 'Business Plan Ã‰nergie Renouvelable',
      description: 'Business plan pour un projet d\'Ã©nergie solaire, Ã©olienne ou bioÃ©nergie.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 19000,
      body: '<h2>{{titre_document}}</h2><p>Projet : {{nom_projet}}</p><p>Type d\'Ã©nergie : {{type_energie}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_projet', label: 'Nom du projet', type: 'text', required: true },
        { name: 'type_energie', label: 'Type d\'Ã©nergie renouvelable', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'capacite_installee', label: 'CapacitÃ© installÃ©e prÃ©vue', type: 'text', required: false },
        { name: 'impact_environnemental', label: 'Impact environnemental', type: 'textarea', required: true },
      ],
    },
    {
      code: 'bplan_010',
      name: 'Business Model Canvas',
      description: 'ReprÃ©sentation complÃ¨te du modÃ¨le Ã©conomique via le Business Model Canvas.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'B',
      active: true,
      price: 9000,
      body: '<h2>{{titre_document}}</h2><p>Entreprise : {{nom_entreprise}}</p><p>Segment principal : {{segment_principal}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_entreprise', label: 'Nom de l\'entreprise', type: 'text', required: true },
        { name: 'segment_principal', label: 'Segment de clients principal', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'partenaires_cles', label: 'Partenaires clÃ©s', type: 'textarea', required: false },
        { name: 'ressources_cles', label: 'Ressources clÃ©s', type: 'textarea', required: true },
      ],
    },

    // â”€â”€â”€ creation_ent_001..005 â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
    {
      code: 'creation_ent_001',
      name: 'Plan de DÃ©marrage d\'ActivitÃ©',
      description: 'Plan opÃ©rationnel dÃ©taillant les Ã©tapes de lancement d\'une nouvelle activitÃ©.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 5000,
      body: '<h2>{{titre_document}}</h2><p>Porteur de projet : {{nom_porteur}}</p><p>ActivitÃ© : {{nom_activite}}</p><p>Date de dÃ©marrage : {{date_demarrage}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_porteur', label: 'Porteur de projet', type: 'text', required: true },
        { name: 'nom_activite', label: 'Nom de l\'activitÃ©', type: 'text', required: true },
        { name: 'date_demarrage', label: 'Date de dÃ©marrage', type: 'date', required: true },
        { name: 'etapes_lancement', label: 'Ã‰tapes de lancement', type: 'textarea', required: true },
        { name: 'ressources_necessaires', label: 'Ressources nÃ©cessaires', type: 'textarea', required: false },
      ],
    },
    {
      code: 'creation_ent_002',
      name: 'Statuts SAS / SA',
      description: 'Statuts constitutifs pour une SociÃ©tÃ© par Actions SimplifiÃ©e ou SociÃ©tÃ© Anonyme.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 18000,
      body: '<h2>{{titre_document}}</h2><p>DÃ©nomination : {{denomination_sociale}}</p><p>Forme juridique : {{forme_juridique}}</p><p>Date : {{date_constitution}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'denomination_sociale', label: 'DÃ©nomination sociale', type: 'text', required: true },
        { name: 'forme_juridique', label: 'Forme juridique (SAS/SA)', type: 'text', required: true },
        { name: 'date_constitution', label: 'Date de constitution', type: 'date', required: true },
        { name: 'capital_social', label: 'Capital social', type: 'text', required: true },
        { name: 'objet_social', label: 'Objet social', type: 'textarea', required: true },
      ],
    },
    {
      code: 'creation_ent_003',
      name: 'Feuille de Route Produit',
      description: 'Roadmap produit planifiant les jalons et fonctionnalitÃ©s sur 12-24 mois.',
      category: 'entrepreneuriat',
      templateType: 'excel',
      classe: 'B',
      active: true,
      price: 8000,
      body: '<h2>{{titre_document}}</h2><p>Produit : {{nom_produit}}</p><p>Version actuelle : {{version_actuelle}}</p><p>Date : {{date_document}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_produit', label: 'Nom du produit', type: 'text', required: true },
        { name: 'version_actuelle', label: 'Version actuelle', type: 'text', required: true },
        { name: 'date_document', label: 'Date du document', type: 'date', required: true },
        { name: 'fonctionnalites_q1', label: 'FonctionnalitÃ©s Q1', type: 'textarea', required: false },
        { name: 'objectifs_annuels', label: 'Objectifs annuels', type: 'textarea', required: true },
      ],
    },
    {
      code: 'creation_ent_004',
      name: 'Dossier Financement Fonds Africains',
      description: 'Dossier de financement adaptÃ© aux critÃ¨res des fonds panafricains et rÃ©gionaux.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'A',
      active: true,
      price: 20000,
      body: '<h2>{{titre_document}}</h2><p>Entreprise : {{nom_entreprise}}</p><p>Fonds ciblÃ© : {{fonds_cible}}</p><p>Date : {{date_soumission}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_entreprise', label: 'Nom de l\'entreprise', type: 'text', required: true },
        { name: 'fonds_cible', label: 'Fonds ciblÃ©', type: 'text', required: true },
        { name: 'date_soumission', label: 'Date de soumission', type: 'date', required: true },
        { name: 'description_projet', label: 'Description du projet', type: 'textarea', required: true },
        { name: 'criteres_eligibilite', label: 'CritÃ¨res d\'Ã©ligibilitÃ© remplis', type: 'textarea', required: true },
      ],
    },
    {
      code: 'creation_ent_005',
      name: 'Plan de DÃ©marrage Micro-Entreprise',
      description: 'Plan simplifiÃ© de dÃ©marrage adaptÃ© aux micro-entreprises et auto-entrepreneurs.',
      category: 'entrepreneuriat',
      templateType: 'pdf',
      classe: 'C',
      active: true,
      price: 3000,
      body: '<h2>{{titre_document}}</h2><p>Auto-entrepreneur : {{nom_entrepreneur}}</p><p>ActivitÃ© : {{nature_activite}}</p><p>Date de dÃ©but : {{date_debut}}</p>',
      fieldsJson: [
        { name: 'titre_document', label: 'Titre du document', type: 'text', required: true },
        { name: 'nom_entrepreneur', label: 'Nom de l\'entrepreneur', type: 'text', required: true },
        { name: 'nature_activite', label: 'Nature de l\'activitÃ©', type: 'text', required: true },
        { name: 'date_debut', label: 'Date de dÃ©but', type: 'date', required: true },
        { name: 'investissement_initial', label: 'Investissement initial', type: 'text', required: false },
        { name: 'objectifs_premiers_mois', label: 'Objectifs des premiers mois', type: 'textarea', required: true },
      ],
    },
  ];

  for (const t of templates) {
    if (Array.isArray(t.fieldsJson)) (t as any).fieldsJson = JSON.stringify(t.fieldsJson);
    const existing = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    const r = await prisma.documentTemplate.upsert({
      where: { code: t.code },
      update: t,
      create: t,
    });
    if (!existing) {
      created++;
    } else {
      updated++;
    }
  }

  const total = await prisma.documentTemplate.count();
  console.log(`Batch entr-01 OK â€” crÃ©Ã©s:${created} maj:${updated} TOTAL:${total}`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());


