import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── MINES ARTISANALES / ORPAILLAGE (artis2_) ───────────────────────────────
  {
    code: 'artis2_autorisation_sodemi',
    name: "Accord de service d'orpaillage artisanal (autorisation SODEMI)",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 18000,
    description: "Convention de service encadrant l'orpaillage artisanal dans le cadre d'une autorisation SODEMI en Côte d'Ivoire, conforme au Code Minier OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'nom_artisan', label: "Nom complet de l'orpailleur", type: 'text', required: true },
      { key: 'numero_autorisation', label: 'Numéro autorisation SODEMI', type: 'text', required: true },
      { key: 'localite_site', label: 'Localité / site d\'orpaillage', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début d\'exploitation', type: 'date', required: true },
      { key: 'date_fin', label: 'Date d\'expiration de l\'autorisation', type: 'date', required: true },
      { key: 'conditions_particulieres', label: 'Conditions particulières SODEMI', type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ORPAILLAGE ARTISANAL</h1><h2>Autorisation SODEMI</h2><p>Entre la Société pour le Développement Minier de la Côte d'Ivoire (SODEMI) et l'artisan minier <strong>{{nom_artisan}}</strong>, titulaire de l'autorisation n° <strong>{{numero_autorisation}}</strong>.</p><h3>Article 1 – Objet</h3><p>Le présent accord encadre l'exploitation artisanale de l'or sur le site de <strong>{{localite_site}}</strong> pour la période du <strong>{{date_debut}}</strong> au <strong>{{date_fin}}</strong>.</p><h3>Article 2 – Obligations de l'artisan</h3><p>L'artisan s'engage à respecter les normes environnementales, à déclarer toute production et à s'acquitter des redevances dues à l'État.</p><h3>Article 3 – Conditions particulières</h3><p>{{conditions_particulieres}}</p><h3>Article 4 – Droit applicable</h3><p>Le présent accord est régi par le Code Minier de la Côte d'Ivoire et les règlements OHADA applicables.</p><p class="signature">Fait à Abidjan, le {{date_debut}}</p></div>`,
  },
  {
    code: 'artis2_extraction_diamants',
    name: "Accord de service d'extraction artisanale de diamants",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 22000,
    description: "Contrat d'extraction artisanale de diamants encadré par le processus de Kimberley et le Code Minier ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'nom_extracteur', label: "Nom de l'extracteur artisanal", type: 'text', required: true },
      { key: 'zone_extraction', label: "Zone d'extraction (département)", type: 'text', required: true },
      { key: 'date_autorisation', label: "Date d'autorisation", type: 'date', required: true },
      { key: 'quota_mensuel', label: 'Quota mensuel estimé (carats)', type: 'text', required: true },
      { key: 'acheteur_agree', label: 'Acheteur agréé désigné', type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXTRACTION ARTISANALE DE DIAMANTS</h1><p>Le présent accord est conclu entre <strong>{{nom_extracteur}}</strong> et l'acheteur agréé <strong>{{acheteur_agree}}</strong> pour l'exploitation de la zone de <strong>{{zone_extraction}}</strong>.</p><h3>Article 1 – Cadre réglementaire</h3><p>L'extraction est autorisée depuis le <strong>{{date_autorisation}}</strong> dans le respect du Processus de Kimberley et du Code Minier de Côte d'Ivoire.</p><h3>Article 2 – Production</h3><p>Le quota mensuel est estimé à <strong>{{quota_mensuel}}</strong> carats. Toute vente hors circuit agréé est strictement interdite.</p><h3>Article 3 – Traçabilité</h3><p>Chaque lot sera accompagné d'un certificat Kimberley délivré par les autorités compétentes.</p><p class="signature">Signatures des parties</p></div>`,
  },
  {
    code: 'artis2_extraction_manganese',
    name: "Accord de service d'extraction de manganèse artisanal",
    category: 'agro_environnement',
    price: 4500,
    priceMax: 15000,
    description: "Convention d'extraction artisanale de manganèse conforme aux exigences du ministère des Mines de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 54,
    fieldsJson: F([
      { key: 'nom_operateur', label: "Nom de l'opérateur", type: 'text', required: true },
      { key: 'site_extraction', label: "Site d'extraction", type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début', type: 'date', required: true },
      { key: 'tonnage_prevu', label: 'Tonnage mensuel prévu (tonnes)', type: 'text', required: true },
      { key: 'modalites_transport', label: 'Modalités de transport du minerai', type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXTRACTION ARTISANALE DE MANGANÈSE</h1><p>Opérateur : <strong>{{nom_operateur}}</strong> — Site : <strong>{{site_extraction}}</strong></p><h3>Article 1 – Objet</h3><p>Le présent accord autorise l'extraction artisanale de manganèse à compter du <strong>{{date_debut}}</strong> pour un tonnage mensuel prévisionnel de <strong>{{tonnage_prevu}}</strong> tonnes.</p><h3>Article 2 – Transport et commercialisation</h3><p>{{modalites_transport}}</p><h3>Article 3 – Redevances</h3><p>L'opérateur s'acquitte des redevances minières conformément au barème en vigueur du Code Minier ivoirien.</p><p class="signature">Fait à Abidjan</p></div>`,
  },
  {
    code: 'artis2_extraction_coltan',
    name: "Accord de service d'extraction de coltan artisanal",
    category: 'agro_environnement',
    price: 5500,
    priceMax: 20000,
    description: "Contrat d'extraction artisanale de coltan (colombo-tantalite) avec clauses de diligence raisonnable conformes aux normes OCDE.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 49,
    fieldsJson: F([
      { key: 'nom_artisan', label: "Nom de l'artisan minier", type: 'text', required: true },
      { key: 'localisation_site', label: 'Localisation du site', type: 'text', required: true },
      { key: 'date_contrat', label: 'Date du contrat', type: 'date', required: true },
      { key: 'acheteur_international', label: 'Acheteur international désigné', type: 'text', required: true },
      { key: 'mesures_diligence', label: 'Mesures de diligence raisonnable', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXTRACTION ARTISANALE DE COLTAN</h1><p>Artisan : <strong>{{nom_artisan}}</strong> | Site : <strong>{{localisation_site}}</strong> | Date : <strong>{{date_contrat}}</strong></p><h3>Article 1 – Objet et cadre légal</h3><p>Le présent accord encadre l'extraction artisanale de coltan destiné à <strong>{{acheteur_international}}</strong> dans le respect des normes OCDE sur les minerais de conflit.</p><h3>Article 2 – Diligence raisonnable</h3><p>{{mesures_diligence}}</p><h3>Article 3 – Interdictions</h3><p>Toute extraction dans des zones de conflit armé ou impliquant des enfants est formellement proscrite sous peine de résiliation immédiate.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_vente_or_bsdf',
    name: "Accord de vente d'or artisanal (BSDF)",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 14000,
    description: "Contrat de vente d'or artisanal via le Bureau de Suivi et de Développement des Filières (BSDF) en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'vendeur', label: "Nom du vendeur (orpailleur)", type: 'text', required: true },
      { key: 'poids_or', label: "Poids d'or vendu (grammes)", type: 'text', required: true },
      { key: 'prix_gramme', label: 'Prix au gramme (FCFA)', type: 'text', required: true },
      { key: 'date_transaction', label: 'Date de la transaction', type: 'date', required: true },
      { key: 'numero_bsdf', label: 'Numéro de suivi BSDF', type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE VENTE D'OR ARTISANAL</h1><h2>Bureau de Suivi et de Développement des Filières (BSDF)</h2><p>Vendeur : <strong>{{vendeur}}</strong> | Référence BSDF : <strong>{{numero_bsdf}}</strong></p><h3>Article 1 – Objet de la vente</h3><p>Le vendeur cède à l'acheteur agréé <strong>{{poids_or}}</strong> grammes d'or artisanal au prix unitaire de <strong>{{prix_gramme}}</strong> FCFA le gramme, soit un montant total calculé à la date du <strong>{{date_transaction}}</strong>.</p><h3>Article 2 – Conformité</h3><p>L'or vendu est déclaré exempt de toute origine frauduleuse. Le vendeur assume l'entière responsabilité de cette déclaration.</p><h3>Article 3 – Paiement</h3><p>Le paiement intervient immédiatement après pesée contradictoire par l'acheteur agréé BSDF.</p><p class="signature">Signatures parties</p></div>`,
  },
  {
    code: 'artis2_bureau_achat_or',
    name: "Accord de service de bureau d'achat d'or",
    category: 'agro_environnement',
    price: 7000,
    priceMax: 25000,
    description: "Convention régissant les opérations d'un bureau d'achat d'or agréé par l'État ivoirien, avec obligations de traçabilité et de lutte anti-blanchiment.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_bureau', label: "Dénomination du bureau d'achat", type: 'text', required: true },
      { key: 'numero_agrement', label: "Numéro d'agrément ministériel", type: 'text', required: true },
      { key: 'responsable', label: 'Nom du responsable', type: 'text', required: true },
      { key: 'adresse_bureau', label: 'Adresse du bureau', type: 'text', required: true },
      { key: 'date_agrement', label: "Date d'agrément", type: 'date', required: true },
      { key: 'obligations_lbc', label: 'Obligations LBC/FT spécifiques', type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — BUREAU D'ACHAT D'OR AGRÉÉ</h1><p>Bureau : <strong>{{nom_bureau}}</strong> | Agrément n° <strong>{{numero_agrement}}</strong> | Responsable : <strong>{{responsable}}</strong></p><h3>Article 1 – Agrément et siège</h3><p>Le bureau est établi à <strong>{{adresse_bureau}}</strong> et opère depuis le <strong>{{date_agrement}}</strong> en vertu de l'agrément du Ministère des Mines.</p><h3>Article 2 – Obligations de traçabilité</h3><p>Tout achat doit être enregistré dans le registre électronique BSDF avec indication de l'origine, du poids et de l'identité du vendeur.</p><h3>Article 3 – Lutte contre le blanchiment</h3><p>{{obligations_lbc}}</p><h3>Article 4 – Sanctions</h3><p>Tout manquement aux obligations de traçabilité expose le bureau au retrait de son agrément.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_fonderie_or',
    name: "Accord de service de fonderie d'or artisanal",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 28000,
    description: "Contrat de prestation de fonderie pour la transformation de l'or artisanal brut en lingots certifiés, conforme aux normes LBMA adaptées au contexte ASGM.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'nom_fonderie', label: 'Dénomination de la fonderie', type: 'text', required: true },
      { key: 'client_producteur', label: "Nom du producteur d'or brut", type: 'text', required: true },
      { key: 'quantite_brut', label: 'Quantité d\'or brut à fondre (grammes)', type: 'text', required: true },
      { key: 'date_traitement', label: 'Date prévue de traitement', type: 'date', required: true },
      { key: 'teneur_attendue', label: 'Teneur attendue (%)', type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE FONDERIE D'OR ARTISANAL</h1><p>Fonderie : <strong>{{nom_fonderie}}</strong> | Producteur : <strong>{{client_producteur}}</strong></p><h3>Article 1 – Prestation</h3><p>La fonderie s'engage à traiter <strong>{{quantite_brut}}</strong> grammes d'or brut le <strong>{{date_traitement}}</strong> pour obtenir une teneur cible de <strong>{{teneur_attendue}}</strong>%.</p><h3>Article 2 – Responsabilité</h3><p>La fonderie certifie l'origine légale de l'or traité et délivre un certificat d'analyse pour chaque lot.</p><h3>Article 3 – Tarification</h3><p>Les frais de fonderie sont calculés sur la base du poids d'or produit, selon le tarif en vigueur communiqué au producteur.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_certification_asgm',
    name: "Accord de certification or responsable (ASGM)",
    category: 'agro_environnement',
    price: 6500,
    priceMax: 22000,
    description: "Convention de certification de l'or issu de l'exploitation artisanale et à petite échelle (ASGM) selon les standards Fairmined ou équivalents reconnus en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'cooperative_miniere', label: 'Nom de la coopérative minière', type: 'text', required: true },
      { key: 'organisme_certification', label: 'Organisme certificateur', type: 'text', required: true },
      { key: 'zone_exploitation', label: "Zone d'exploitation certifiée", type: 'text', required: true },
      { key: 'date_audit', label: 'Date du premier audit', type: 'date', required: true },
      { key: 'engagements_environnementaux', label: 'Engagements environnementaux spécifiques', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION OR RESPONSABLE — ASGM</h1><p>Coopérative : <strong>{{cooperative_miniere}}</strong> | Certificateur : <strong>{{organisme_certification}}</strong></p><h3>Article 1 – Objet</h3><p>Le présent accord établit les conditions de certification de l'or produit dans la zone de <strong>{{zone_exploitation}}</strong> selon les standards ASGM reconnus.</p><h3>Article 2 – Audit initial</h3><p>Le premier audit de certification aura lieu le <strong>{{date_audit}}</strong>. La coopérative s'engage à fournir tous documents requis.</p><h3>Article 3 – Engagements environnementaux</h3><p>{{engagements_environnementaux}}</p><h3>Article 4 – Prime</h3><p>La certification ouvre droit à une prime commerciale négociée sur le cours de l'or LBMA.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_securite_site',
    name: "Accord de service de sécurité site d'orpaillage",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 13000,
    description: "Contrat de prestation de service de sécurisation d'un site d'orpaillage artisanal, incluant gardiennage, contrôle d'accès et gestion des conflits.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'societe_securite', label: 'Société de sécurité prestataire', type: 'text', required: true },
      { key: 'client_site', label: 'Gestionnaire du site', type: 'text', required: true },
      { key: 'nom_site', label: 'Nom / localisation du site', type: 'text', required: true },
      { key: 'date_debut_mission', label: 'Date de début de mission', type: 'date', required: true },
      { key: 'effectif_agents', label: "Nombre d'agents déployés", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SÉCURITÉ — SITE D'ORPAILLAGE</h1><p>Prestataire : <strong>{{societe_securite}}</strong> | Client : <strong>{{client_site}}</strong> | Site : <strong>{{nom_site}}</strong></p><h3>Article 1 – Mission</h3><p>À compter du <strong>{{date_debut_mission}}</strong>, la société de sécurité déploie <strong>{{effectif_agents}}</strong> agents pour assurer la sécurité du site 24h/24.</p><h3>Article 2 – Périmètre de sécurité</h3><p>Le prestataire contrôle les accès au site, patrouille le périmètre et rédige des rapports d'incidents quotidiens.</p><h3>Article 3 – Coordination</h3><p>En cas d'incident grave, le prestataire alerte immédiatement les forces de l'ordre et le gestionnaire du site.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_sante_site_minier',
    name: "Accord de service de santé site minier artisanal",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 17000,
    description: "Convention de prestation de services de santé sur un site d'extraction artisanale, couvrant soins primaires, prévention du paludisme et gestion des accidents du travail.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'prestataire_sante', label: 'Prestataire de santé (clinique/ONG)', type: 'text', required: true },
      { key: 'gestionnaire_site', label: 'Gestionnaire du site minier', type: 'text', required: true },
      { key: 'localisation_site', label: 'Localisation du site', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début du contrat', type: 'date', required: true },
      { key: 'effectif_couverts', label: 'Effectif de travailleurs couverts', type: 'text', required: true },
      { key: 'prestations_incluses', label: 'Prestations médicales incluses', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SANTÉ — SITE MINIER ARTISANAL</h1><p>Prestataire : <strong>{{prestataire_sante}}</strong> | Site : <strong>{{localisation_site}}</strong></p><h3>Article 1 – Objet</h3><p>À compter du <strong>{{date_debut}}</strong>, le prestataire assure la couverture médicale de <strong>{{effectif_couverts}}</strong> travailleurs du site géré par <strong>{{gestionnaire_site}}</strong>.</p><h3>Article 2 – Prestations</h3><p>{{prestations_incluses}}</p><h3>Article 3 – Urgences</h3><p>Le prestataire maintient un poste de premiers secours opérationnel 24h/24 et assure l'évacuation sanitaire en cas d'urgence grave.</p><h3>Article 4 – Rapports</h3><p>Un rapport mensuel de santé est transmis au gestionnaire du site et aux autorités sanitaires.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_gestion_environnementale',
    name: "Accord de service de gestion environnementale site artisanal",
    category: 'agro_environnement',
    price: 5500,
    priceMax: 19000,
    description: "Contrat de gestion environnementale d'un site d'orpaillage artisanal incluant surveillance, réduction de l'utilisation du mercure et reboisement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'expert_environnement', label: 'Expert ou bureau d\'études environnement', type: 'text', required: true },
      { key: 'operateur_site', label: "Opérateur du site", type: 'text', required: true },
      { key: 'site_concerne', label: 'Site concerné', type: 'text', required: true },
      { key: 'date_debut_mission', label: 'Date de début de mission', type: 'date', required: true },
      { key: 'mesures_mercure', label: 'Mesures de réduction du mercure', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION ENVIRONNEMENTALE — SITE D'ORPAILLAGE ARTISANAL</h1><p>Expert : <strong>{{expert_environnement}}</strong> | Opérateur : <strong>{{operateur_site}}</strong> | Site : <strong>{{site_concerne}}</strong></p><h3>Article 1 – Mission</h3><p>Depuis le <strong>{{date_debut_mission}}</strong>, l'expert assure le suivi environnemental du site conformément aux exigences de la Convention de Minamata sur le mercure.</p><h3>Article 2 – Réduction du mercure</h3><p>{{mesures_mercure}}</p><h3>Article 3 – Reboisement</h3><p>L'opérateur s'engage à replanter un arbre pour chaque arbre abattu lors des opérations minières.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_rehabilitation_site',
    name: "Accord de réhabilitation de site d'orpaillage",
    category: 'agro_environnement',
    price: 7000,
    priceMax: 24000,
    description: "Convention de réhabilitation environnementale post-exploitation d'un site d'orpaillage artisanal, incluant remblaiement, dépollution et revégétalisation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'entreprise_rehabilitation', label: 'Entreprise de réhabilitation', type: 'text', required: true },
      { key: 'proprietaire_site', label: 'Propriétaire / exploitant du site', type: 'text', required: true },
      { key: 'localisation', label: 'Localisation du site à réhabiliter', type: 'text', required: true },
      { key: 'date_debut_travaux', label: 'Date de début des travaux', type: 'date', required: true },
      { key: 'date_fin_travaux', label: 'Date de fin des travaux prévue', type: 'date', required: true },
      { key: 'plan_rehabilitation', label: 'Plan de réhabilitation (description)', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉHABILITATION DE SITE D'ORPAILLAGE</h1><p>Entreprise : <strong>{{entreprise_rehabilitation}}</strong> | Mandant : <strong>{{proprietaire_site}}</strong></p><h3>Article 1 – Site concerné</h3><p>Le site de <strong>{{localisation}}</strong> fera l'objet de travaux de réhabilitation du <strong>{{date_debut_travaux}}</strong> au <strong>{{date_fin_travaux}}</strong>.</p><h3>Article 2 – Plan de réhabilitation</h3><p>{{plan_rehabilitation}}</p><h3>Article 3 – Conformité</h3><p>Les travaux respectent l'Arrêté minier sur la réhabilitation des sites et le cahier des charges du Ministère des Mines.</p><h3>Article 4 – Réception</h3><p>La réception des travaux est prononcée par un expert indépendant agréé par le Ministère de l'Environnement.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_cooperative_orpailleurs',
    name: "Accord de coopérative d'orpailleurs",
    category: 'agro_environnement',
    price: 4500,
    priceMax: 15000,
    description: "Statuts et accord constitutif d'une coopérative d'orpailleurs artisanaux conforme à la loi ivoirienne sur les coopératives et au Code Minier.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'nom_cooperative', label: 'Dénomination de la coopérative', type: 'text', required: true },
      { key: 'president', label: 'Nom du président', type: 'text', required: true },
      { key: 'siege_social', label: 'Siège social', type: 'text', required: true },
      { key: 'nombre_membres', label: 'Nombre de membres fondateurs', type: 'text', required: true },
      { key: 'date_constitution', label: 'Date de constitution', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD CONSTITUTIF DE COOPÉRATIVE D'ORPAILLEURS</h1><p>Dénomination : <strong>{{nom_cooperative}}</strong> | Siège : <strong>{{siege_social}}</strong></p><h3>Article 1 – Constitution</h3><p>Les <strong>{{nombre_membres}}</strong> membres fondateurs se réunissent le <strong>{{date_constitution}}</strong> pour constituer la coopérative sous la présidence de <strong>{{president}}</strong>.</p><h3>Article 2 – Objet</h3><p>La coopérative a pour objet l'organisation, l'encadrement et la commercialisation collective de la production d'or artisanal de ses membres.</p><h3>Article 3 – Gouvernance</h3><p>Les décisions sont prises à la majorité des membres actifs réunis en assemblée générale annuelle.</p><h3>Article 4 – Cadre légal</h3><p>La coopérative est régie par la loi ivoirienne n° 97-721 relative aux sociétés coopératives.</p><p class="signature">Signatures des membres fondateurs</p></div>`,
  },
  {
    code: 'artis2_formalisation_orpaillage',
    name: "Accord de formalisation de l'orpaillage artisanal",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 11000,
    description: "Protocole de formalisation d'activités d'orpaillage artisanal informel, facilitant l'intégration des orpailleurs dans le circuit légal ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'nom_orpailleur', label: "Nom de l'orpailleur", type: 'text', required: true },
      { key: 'autorite_accompagnement', label: "Autorité d'accompagnement (SODEMI/Préfecture)", type: 'text', required: true },
      { key: 'zone_activite', label: "Zone d'activité déclarée", type: 'text', required: true },
      { key: 'date_engagement', label: "Date d'engagement dans la formalisation", type: 'date', required: true },
      { key: 'etapes_formalisation', label: 'Étapes de formalisation convenues', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FORMALISATION DE L'ORPAILLAGE ARTISANAL</h1><p>Bénéficiaire : <strong>{{nom_orpailleur}}</strong> | Autorité accompagnatrice : <strong>{{autorite_accompagnement}}</strong></p><h3>Article 1 – Engagement</h3><p>L'orpailleur s'engage depuis le <strong>{{date_engagement}}</strong> à intégrer le circuit légal pour ses activités dans la zone de <strong>{{zone_activite}}</strong>.</p><h3>Article 2 – Plan de formalisation</h3><p>{{etapes_formalisation}}</p><h3>Article 3 – Accompagnement</h3><p>L'autorité accompagnatrice s'engage à faciliter les démarches administratives et à ne pas sanctionner l'orpailleur pendant la période de transition.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_financement_imf',
    name: "Accord de service de financement minier artisanal (IMF)",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 17000,
    description: "Convention de financement d'activités minières artisanales par une institution de microfinance (IMF), avec remboursement indexé sur la production d'or.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'institution_microfinance', label: 'Institution de microfinance', type: 'text', required: true },
      { key: 'nom_emprunteur', label: "Nom de l'emprunteur", type: 'text', required: true },
      { key: 'montant_financement', label: 'Montant du financement (FCFA)', type: 'text', required: true },
      { key: 'taux_interet', label: "Taux d'intérêt mensuel (%)", type: 'text', required: true },
      { key: 'date_decaissement', label: 'Date de décaissement', type: 'date', required: true },
      { key: 'modalites_remboursement', label: 'Modalités de remboursement', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FINANCEMENT MINIER ARTISANAL</h1><p>IMF : <strong>{{institution_microfinance}}</strong> | Emprunteur : <strong>{{nom_emprunteur}}</strong></p><h3>Article 1 – Financement</h3><p>L'IMF octroie un financement de <strong>{{montant_financement}}</strong> FCFA, décaissé le <strong>{{date_decaissement}}</strong>, au taux mensuel de <strong>{{taux_interet}}</strong>%.</p><h3>Article 2 – Remboursement</h3><p>{{modalites_remboursement}}</p><h3>Article 3 – Garantie</h3><p>Le remboursement est garanti par la cession partielle de la production d'or de l'emprunteur à l'acheteur agréé désigné par l'IMF.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_formation_mercure_zero',
    name: "Accord de service de formation orpailleurs (mercure zéro)",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Contrat de formation des orpailleurs artisanaux aux techniques sans mercure, dans le cadre de la mise en oeuvre de la Convention de Minamata en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'organisme_formation', label: 'Organisme de formation', type: 'text', required: true },
      { key: 'coordinateur', label: 'Coordinateur du programme', type: 'text', required: true },
      { key: 'nombre_beneficiaires', label: 'Nombre de bénéficiaires', type: 'text', required: true },
      { key: 'date_formation', label: 'Date de début de la formation', type: 'date', required: true },
      { key: 'techniques_enseignees', label: 'Techniques alternatives enseignées', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FORMATION ORPAILLEURS — MERCURE ZÉRO</h1><p>Formateur : <strong>{{organisme_formation}}</strong> | Coordinateur : <strong>{{coordinateur}}</strong></p><h3>Article 1 – Programme</h3><p>À compter du <strong>{{date_formation}}</strong>, <strong>{{nombre_beneficiaires}}</strong> orpailleurs bénéficient d'une formation aux techniques d'extraction sans mercure.</p><h3>Article 2 – Techniques enseignées</h3><p>{{techniques_enseignees}}</p><h3>Article 3 – Certification</h3><p>Les participants reçoivent une attestation de formation reconnue par le Ministère des Mines et le PNUE dans le cadre de la Convention de Minamata.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_traitement_dechets',
    name: "Accord de service de traitement des déchets miniers artisanaux",
    category: 'agro_environnement',
    price: 6000,
    priceMax: 20000,
    description: "Convention de collecte, traitement et élimination sécurisée des déchets issus de l'exploitation minière artisanale, notamment les résidus de cyanuration et amalgames de mercure.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 51,
    fieldsJson: F([
      { key: 'prestataire_dechets', label: 'Prestataire de traitement des déchets', type: 'text', required: true },
      { key: 'producteur_dechets', label: 'Producteur des déchets (opérateur minier)', type: 'text', required: true },
      { key: 'type_dechets', label: 'Type de déchets à traiter', type: 'text', required: true },
      { key: 'volume_mensuel', label: 'Volume mensuel estimé (kg)', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début du contrat', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRAITEMENT DES DÉCHETS MINIERS ARTISANAUX</h1><p>Prestataire : <strong>{{prestataire_dechets}}</strong> | Producteur : <strong>{{producteur_dechets}}</strong></p><h3>Article 1 – Objet</h3><p>Le prestataire collecte et traite <strong>{{type_dechets}}</strong> à raison de <strong>{{volume_mensuel}}</strong> kg par mois à compter du <strong>{{date_debut}}</strong>.</p><h3>Article 2 – Méthodes de traitement</h3><p>Les déchets sont traités conformément aux normes de l'ANDE et du Code de l'environnement de Côte d'Ivoire.</p><h3>Article 3 – Traçabilité</h3><p>Un bordereau de suivi des déchets dangereux est émis pour chaque enlèvement.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_plan_developpement_minier',
    name: "Plan de développement minier artisanal",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 28000,
    description: "Document stratégique de planification du développement d'une zone d'exploitation minière artisanale, incluant objectifs de production, volets social et environnemental.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'zone_developpement', label: 'Zone de développement concernée', type: 'text', required: true },
      { key: 'responsable_plan', label: 'Responsable du plan', type: 'text', required: true },
      { key: 'periode_couverture', label: 'Période couverte (ex: 2025-2028)', type: 'text', required: true },
      { key: 'date_validation', label: 'Date de validation du plan', type: 'date', required: true },
      { key: 'objectifs_production', label: 'Objectifs de production détaillés', type: 'textarea', required: true },
      { key: 'volet_social', label: 'Volet social et communautaire', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT MINIER ARTISANAL</h1><p>Zone : <strong>{{zone_developpement}}</strong> | Responsable : <strong>{{responsable_plan}}</strong> | Période : <strong>{{periode_couverture}}</strong></p><h3>1. Introduction</h3><p>Le présent plan, validé le <strong>{{date_validation}}</strong>, définit la stratégie de développement durable de l'exploitation artisanale.</p><h3>2. Objectifs de production</h3><p>{{objectifs_production}}</p><h3>3. Volet social</h3><p>{{volet_social}}</p><h3>4. Volet environnemental</h3><p>Des mesures de réhabilitation progressive sont intégrées dès la phase d'exploitation conformément aux exigences de l'ANDE.</p><p class="signature">Validation par les autorités compétentes</p></div>`,
  },
  {
    code: 'artis2_partenariat_sodemi',
    name: "Accord de partenariat SODEMI-artisans miniers",
    category: 'agro_environnement',
    price: 7500,
    priceMax: 26000,
    description: "Convention de partenariat structuré entre la SODEMI et des groupements d'artisans miniers pour l'exploitation légale et encadrée de zones aurifères désignées.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'groupement_artisans', label: 'Dénomination du groupement d\'artisans', type: 'text', required: true },
      { key: 'representant_groupement', label: 'Représentant légal du groupement', type: 'text', required: true },
      { key: 'zone_attribuee', label: 'Zone aurifère attribuée', type: 'text', required: true },
      { key: 'date_signature', label: 'Date de signature du partenariat', type: 'date', required: true },
      { key: 'redevances_sodemi', label: 'Structure des redevances SODEMI', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT SODEMI — ARTISANS MINIERS</h1><p>Entre la SODEMI et le groupement <strong>{{groupement_artisans}}</strong> représenté par <strong>{{representant_groupement}}</strong>.</p><h3>Article 1 – Attribution de zone</h3><p>La SODEMI attribue au groupement la zone aurifère de <strong>{{zone_attribuee}}</strong> pour une exploitation artisanale encadrée à compter du <strong>{{date_signature}}</strong>.</p><h3>Article 2 – Obligations du groupement</h3><p>Le groupement s'engage à opérer exclusivement dans la zone attribuée, à déclarer toute production et à respecter les normes environnementales SODEMI.</p><h3>Article 3 – Redevances</h3><p>{{redevances_sodemi}}</p><h3>Article 4 – Résiliation</h3><p>Tout manquement grave entraîne la résiliation immédiate du présent accord.</p><p class="signature">Fait à Abidjan, le <strong>{{date_signature}}</strong></p></div>`,
  },
  {
    code: 'artis2_cartographie_zones',
    name: "Accord de service de cartographie zones aurifères",
    category: 'agro_environnement',
    price: 9000,
    priceMax: 30000,
    description: "Contrat de prestation de cartographie géologique et aurifère pour délimiter et caractériser les zones d'exploitation artisanale en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 54,
    fieldsJson: F([
      { key: 'bureau_cartographie', label: 'Bureau de cartographie géologique', type: 'text', required: true },
      { key: 'client', label: 'Client (SODEMI / opérateur)', type: 'text', required: true },
      { key: 'region_cible', label: 'Région cible de la cartographie', type: 'text', required: true },
      { key: 'date_debut_mission', label: 'Date de début de mission', type: 'date', required: true },
      { key: 'livrables', label: 'Livrables attendus (cartes, rapports)', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CARTOGRAPHIE ZONES AURIFÈRES</h1><p>Bureau : <strong>{{bureau_cartographie}}</strong> | Client : <strong>{{client}}</strong> | Région : <strong>{{region_cible}}</strong></p><h3>Article 1 – Mission</h3><p>Depuis le <strong>{{date_debut_mission}}</strong>, le bureau réalise la cartographie géologique et aurifère de la région cible.</p><h3>Article 2 – Livrables</h3><p>{{livrables}}</p><h3>Article 3 – Droits sur les données</h3><p>Les données collectées sont la propriété exclusive du client et ne peuvent être divulguées sans autorisation préalable écrite.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_surveillance_anti_intrusion',
    name: "Accord de service de surveillance anti-intrusion site minier",
    category: 'agro_environnement',
    price: 5000,
    priceMax: 16000,
    description: "Convention de surveillance électronique et physique anti-intrusion d'un site minier artisanal, avec systèmes d'alerte et protocoles d'intervention.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'prestataire_surveillance', label: 'Prestataire de surveillance', type: 'text', required: true },
      { key: 'operateur_site', label: "Opérateur du site minier", type: 'text', required: true },
      { key: 'site_surveille', label: 'Site à surveiller', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début du contrat', type: 'date', required: true },
      { key: 'dispositifs_deployes', label: 'Dispositifs de surveillance déployés', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SURVEILLANCE ANTI-INTRUSION — SITE MINIER</h1><p>Prestataire : <strong>{{prestataire_surveillance}}</strong> | Site : <strong>{{site_surveille}}</strong></p><h3>Article 1 – Périmètre</h3><p>Depuis le <strong>{{date_debut}}</strong>, le prestataire assure la surveillance du site de <strong>{{operateur_site}}</strong> contre toute intrusion non autorisée.</p><h3>Article 2 – Dispositifs</h3><p>{{dispositifs_deployes}}</p><h3>Article 3 – Réponse aux incidents</h3><p>En cas d'intrusion détectée, le prestataire intervient dans un délai maximal de 15 minutes et alerte simultanément les forces de l'ordre.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_rapport_performance_site',
    name: "Rapport de performance site d'orpaillage",
    category: 'agro_environnement',
    price: 3000,
    priceMax: 9000,
    description: "Modèle de rapport périodique de performance d'un site d'orpaillage artisanal couvrant production, sécurité, environnement et aspects sociaux.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'nom_site', label: 'Nom du site d\'orpaillage', type: 'text', required: true },
      { key: 'responsable_rapport', label: 'Responsable du rapport', type: 'text', required: true },
      { key: 'periode_rapport', label: 'Période couverte', type: 'text', required: true },
      { key: 'date_rapport', label: 'Date du rapport', type: 'date', required: true },
      { key: 'indicateurs_production', label: 'Indicateurs de production (grammes, incidents)', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE — SITE D'ORPAILLAGE</h1><p>Site : <strong>{{nom_site}}</strong> | Période : <strong>{{periode_rapport}}</strong> | Date : <strong>{{date_rapport}}</strong></p><p>Responsable : <strong>{{responsable_rapport}}</strong></p><h3>1. Indicateurs de production</h3><p>{{indicateurs_production}}</p><h3>2. Sécurité</h3><p>Nombre d'accidents : à renseigner. Taux de fréquence : à calculer selon les heures travaillées.</p><h3>3. Environnement</h3><p>Suivi des paramètres : turbidité des eaux, utilisation de mercure, superficie réhabilitée.</p><h3>4. Social</h3><p>Nombre de travailleurs actifs, conflits communautaires résolus, formations dispensées.</p><p class="signature">Signé par le responsable du site</p></div>`,
  },
  {
    code: 'artis2_partenariat_ong',
    name: "Accord de partenariat ONG-artisans miniers",
    category: 'agro_environnement',
    price: 3500,
    priceMax: 11000,
    description: "Convention de partenariat entre une ONG de développement et un groupement d'artisans miniers pour l'amélioration des pratiques et des conditions de vie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_ong', label: 'Nom de l\'ONG partenaire', type: 'text', required: true },
      { key: 'groupement_artisans', label: 'Groupement d\'artisans miniers', type: 'text', required: true },
      { key: 'objet_partenariat', label: 'Objet du partenariat', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début', type: 'date', required: true },
      { key: 'activites_prevues', label: 'Activités prévues', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT ONG — ARTISANS MINIERS</h1><p>ONG : <strong>{{nom_ong}}</strong> | Groupement : <strong>{{groupement_artisans}}</strong></p><h3>Article 1 – Objet</h3><p>Depuis le <strong>{{date_debut}}</strong>, les parties s'associent pour <strong>{{objet_partenariat}}</strong>.</p><h3>Article 2 – Activités</h3><p>{{activites_prevues}}</p><h3>Article 3 – Financement</h3><p>L'ONG mobilise les ressources nécessaires auprès de bailleurs de fonds internationaux. Le groupement apporte sa contribution en nature et en main-d'oeuvre.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_conversion_agriculture',
    name: "Accord de conversion orpailleurs vers agriculture",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 13000,
    description: "Convention d'appui à la reconversion professionnelle des orpailleurs vers des activités agricoles durables, dans le cadre des politiques de réduction de l'orpaillage illégal.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'structure_appui', label: "Structure d'appui à la reconversion", type: 'text', required: true },
      { key: 'nom_beneficiaire', label: 'Nom du bénéficiaire (orpailleur)', type: 'text', required: true },
      { key: 'filiere_cible', label: 'Filière agricole cible', type: 'text', required: true },
      { key: 'date_debut_programme', label: 'Date de début du programme', type: 'date', required: true },
      { key: 'appuis_prevus', label: 'Appuis et formations prévus', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RECONVERSION — ORPAILLEUR VERS AGRICULTURE</h1><p>Structure d'appui : <strong>{{structure_appui}}</strong> | Bénéficiaire : <strong>{{nom_beneficiaire}}</strong></p><h3>Article 1 – Engagement</h3><p>Le bénéficiaire s'engage à abandonner l'orpaillage illégal et à intégrer la filière agricole <strong>{{filiere_cible}}</strong> à compter du <strong>{{date_debut_programme}}</strong>.</p><h3>Article 2 – Appuis</h3><p>{{appuis_prevus}}</p><h3>Article 3 – Suivi</h3><p>La structure d'appui assure un suivi mensuel pendant les 12 premiers mois pour garantir la durabilité de la reconversion.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'artis2_charte_orpaillage_responsable',
    name: "Charte de l'orpaillage responsable en Afrique",
    category: 'agro_environnement',
    price: 4000,
    priceMax: 14000,
    description: "Charte d'engagement volontaire des acteurs de l'orpaillage artisanal africain pour des pratiques responsables sur les plans environnemental, social et de gouvernance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'signataire', label: 'Nom du signataire / organisation', type: 'text', required: true },
      { key: 'pays_operation', label: "Pays d'opération", type: 'text', required: true },
      { key: 'date_signature', label: 'Date de signature', type: 'date', required: true },
      { key: 'engagements_specifiques', label: 'Engagements spécifiques du signataire', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE L'ORPAILLAGE RESPONSABLE EN AFRIQUE</h1><p>Signataire : <strong>{{signataire}}</strong> | Pays : <strong>{{pays_operation}}</strong> | Date : <strong>{{date_signature}}</strong></p><h3>Préambule</h3><p>Convaincus que l'orpaillage artisanal peut constituer un moteur de développement local lorsqu'il est pratiqué de manière responsable, les signataires s'engagent solennellement à respecter les principes de la présente charte.</p><h3>Principe 1 – Légalité</h3><p>N'opérer que dans le cadre légal en vigueur dans le pays concerné.</p><h3>Principe 2 – Environnement</h3><p>Minimiser l'impact environnemental et s'engager dans la réhabilitation progressive des sites.</p><h3>Principe 3 – Droits humains</h3><p>Refuser le travail des enfants et garantir des conditions de travail dignes à tous les opérateurs.</p><h3>Engagements spécifiques</h3><p>{{engagements_specifiques}}</p><p class="signature">Signature du souscripteur</p></div>`,
  },

  // ─── CARRIÈRES / MATÉRIAUX (carr_) ──────────────────────────────────────────
  {
    code: 'carr_permis_exploitation_oser',
    name: "Permis d'exploitation de carrière (OSER)",
    category: 'btp_construction',
    price: 10000,
    priceMax: 35000,
    description: "Dossier de demande et modèle de permis d'exploitation de carrière délivré par l'Office de Sécurité Routière (OSER) et le Ministère des Mines de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'nom_exploitant', label: "Dénomination de l'exploitant", type: 'text', required: true },
      { key: 'localisation_carriere', label: 'Localisation de la carrière', type: 'text', required: true },
      { key: 'type_materiau', label: 'Type de matériau extrait', type: 'text', required: true },
      { key: 'date_delivrance', label: 'Date de délivrance du permis', type: 'date', required: true },
      { key: 'date_expiration', label: "Date d'expiration", type: 'date', required: true },
      { key: 'superficie_ha', label: 'Superficie concédée (hectares)', type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PERMIS D'EXPLOITATION DE CARRIÈRE</h1><h2>République de Côte d'Ivoire — Ministère des Mines et de la Géologie</h2><p>Le présent permis est accordé à <strong>{{nom_exploitant}}</strong> pour l'exploitation d'une carrière de <strong>{{type_materiau}}</strong> sise à <strong>{{localisation_carriere}}</strong>.</p><h3>Article 1 – Validité</h3><p>Permis valable du <strong>{{date_delivrance}}</strong> au <strong>{{date_expiration}}</strong> sur une superficie de <strong>{{superficie_ha}}</strong> hectares.</p><h3>Article 2 – Obligations</h3><p>L'exploitant respecte le Code Minier, les normes environnementales de l'ANDE et les prescriptions de l'OSER relatives à la qualité des matériaux routiers.</p><h3>Article 3 – Renouvellement</h3><p>La demande de renouvellement doit être déposée 6 mois avant l'expiration du présent permis.</p><p class="signature">Le Ministre des Mines et de la Géologie</p></div>`,
  },
  {
    code: 'carr_extraction_granite',
    name: "Contrat de service d'extraction de granite",
    category: 'btp_construction',
    price: 8000,
    priceMax: 28000,
    description: "Convention d'extraction de granite en carrière pour la fourniture de matériaux de construction de qualité BTP, avec contrôle qualité et traçabilité.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'extracteur', label: "Société extractrice", type: 'text', required: true },
      { key: 'client', label: 'Client donneur d\'ordre', type: 'text', required: true },
      { key: 'localisation_carriere', label: 'Localisation de la carrière', type: 'text', required: true },
      { key: 'volume_mensuel', label: 'Volume mensuel commandé (m3)', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début du contrat', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'EXTRACTION DE GRANITE</h1><p>Extracteur : <strong>{{extracteur}}</strong> | Client : <strong>{{client}}</strong> | Carrière : <strong>{{localisation_carriere}}</strong></p><h3>Article 1 – Objet</h3><p>L'extracteur s'engage à fournir <strong>{{volume_mensuel}}</strong> m3 de granite par mois à compter du <strong>{{date_debut}}</strong>.</p><h3>Article 2 – Qualité</h3><p>Le granite livré doit satisfaire aux spécifications NI-CI pour les granulats de voirie et bâtiment.</p><h3>Article 3 – Livraison</h3><p>La livraison s'effectue franco chantier, les frais de transport étant à la charge du client.</p><p class="signature">Signatures parties</p></div>`,
  },
  {
    code: 'carr_extraction_basalte',
    name: "Accord de service d'extraction de basalte",
    category: 'btp_construction',
    price: 7500,
    priceMax: 26000,
    description: "Contrat d'extraction de basalte pour la production de granulats routiers et béton, avec spécifications techniques conformes aux normes BNETD.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'societe_extraction', label: "Société d'extraction", type: 'text', required: true },
      { key: 'maitre_ouvrage', label: 'Maître d\'ouvrage / client', type: 'text', required: true },
      { key: 'site_carriere', label: 'Site de la carrière de basalte', type: 'text', required: true },
      { key: 'tonnage_mensuel', label: 'Tonnage mensuel (tonnes)', type: 'text', required: true },
      { key: 'date_demarrage', label: 'Date de démarrage', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXTRACTION DE BASALTE</h1><p>Extracteur : <strong>{{societe_extraction}}</strong> | Client : <strong>{{maitre_ouvrage}}</strong> | Site : <strong>{{site_carriere}}</strong></p><h3>Article 1 – Fourniture</h3><p>Depuis le <strong>{{date_demarrage}}</strong>, l'extracteur fournit <strong>{{tonnage_mensuel}}</strong> tonnes de basalte concassé par mois.</p><h3>Article 2 – Spécifications</h3><p>Les granulats satisfont aux exigences du BNETD pour les chaussées et ouvrages d'art.</p><h3>Article 3 – Contrôle qualité</h3><p>Des essais Los Angeles et Micro-Deval sont réalisés mensuellement par un laboratoire agréé.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_extraction_calcaire',
    name: "Accord de service d'extraction de calcaire",
    category: 'btp_construction',
    price: 7000,
    priceMax: 24000,
    description: "Convention d'extraction de calcaire pour usage industriel (cimenterie) ou construction, avec plan de gestion environnementale intégré.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'extracteur', label: 'Société extractrice', type: 'text', required: true },
      { key: 'acheteur_industriel', label: 'Acheteur industriel (cimenterie/client)', type: 'text', required: true },
      { key: 'localisation', label: 'Localisation de la carrière', type: 'text', required: true },
      { key: 'tonnage_annuel', label: 'Tonnage annuel convenu (tonnes)', type: 'text', required: true },
      { key: 'date_contrat', label: 'Date du contrat', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXTRACTION DE CALCAIRE</h1><p>Extracteur : <strong>{{extracteur}}</strong> | Acheteur : <strong>{{acheteur_industriel}}</strong> | Site : <strong>{{localisation}}</strong></p><h3>Article 1 – Volume</h3><p>L'extracteur s'engage à fournir <strong>{{tonnage_annuel}}</strong> tonnes de calcaire par an, sur la durée du présent contrat signé le <strong>{{date_contrat}}</strong>.</p><h3>Article 2 – Qualité</h3><p>Le calcaire livré respecte les spécifications chimiques et granulométriques définies par l'acheteur industriel.</p><h3>Article 3 – Environnement</h3><p>L'extracteur dispose d'un plan de gestion environnementale approuvé par l'ANDE.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_extraction_sable_riviere',
    name: "Accord de service d'extraction de sable de rivière",
    category: 'btp_construction',
    price: 5000,
    priceMax: 16000,
    description: "Convention d'extraction de sable alluvionnaire en lit mineur ou majeur de rivière, conforme aux autorisations du Ministère de l'Environnement et des Eaux et Forêts.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'extracteur_sable', label: 'Extracteur de sable', type: 'text', required: true },
      { key: 'cours_eau', label: 'Cours d\'eau concerné', type: 'text', required: true },
      { key: 'numero_autorisation', label: "Numéro d'autorisation environnementale", type: 'text', required: true },
      { key: 'volume_mensuel', label: 'Volume mensuel autorisé (m3)', type: 'text', required: true },
      { key: 'date_autorisation', label: "Date d'autorisation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXTRACTION DE SABLE DE RIVIÈRE</h1><p>Extracteur : <strong>{{extracteur_sable}}</strong> | Cours d'eau : <strong>{{cours_eau}}</strong> | Autorisation : <strong>{{numero_autorisation}}</strong></p><h3>Article 1 – Autorisation</h3><p>L'extraction est autorisée depuis le <strong>{{date_autorisation}}</strong> pour un volume maximum de <strong>{{volume_mensuel}}</strong> m3 par mois.</p><h3>Article 2 – Restrictions</h3><p>L'extraction est interdite à moins de 50 m des berges habitées et pendant la saison de reproduction piscicole.</p><h3>Article 3 – Surveillance</h3><p>Le Ministère des Eaux et Forêts procède à des contrôles trimestriels du site d'extraction.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_extraction_argile',
    name: "Accord de service d'extraction d'argile (briqueterie)",
    category: 'btp_construction',
    price: 4500,
    priceMax: 15000,
    description: "Convention d'extraction d'argile plastique destinée à la fabrication de briques et tuiles, avec spécifications pétrographiques et plan de remise en état.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'extracteur_argile', label: "Extracteur d'argile", type: 'text', required: true },
      { key: 'briqueterie_cliente', label: 'Briqueterie cliente', type: 'text', required: true },
      { key: 'site_extraction', label: "Site d'extraction", type: 'text', required: true },
      { key: 'tonnage_mensuel', label: 'Tonnage mensuel d\'argile (tonnes)', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'EXTRACTION D'ARGILE — BRIQUETERIE</h1><p>Extracteur : <strong>{{extracteur_argile}}</strong> | Client : <strong>{{briqueterie_cliente}}</strong> | Site : <strong>{{site_extraction}}</strong></p><h3>Article 1 – Fourniture</h3><p>Depuis le <strong>{{date_debut}}</strong>, l'extracteur livre <strong>{{tonnage_mensuel}}</strong> tonnes d'argile par mois conforme aux spécifications de la briqueterie.</p><h3>Article 2 – Qualité</h3><p>L'argile doit avoir un indice de plasticité adapté à la fabrication de briques cuites, déterminé par essais Atterberg.</p><h3>Article 3 – Remise en état</h3><p>L'extracteur remet le site en état après exploitation conformément au cahier des charges environnementales.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_concassage_granulats',
    name: "Accord de service de concassage et granulats",
    category: 'btp_construction',
    price: 7000,
    priceMax: 24000,
    description: "Contrat de prestation de concassage de roche dure pour la production de granulats calibrés destinés aux travaux de BTP, avec contrôle granulométrique continu.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'prestataire_concassage', label: 'Prestataire de concassage', type: 'text', required: true },
      { key: 'client', label: 'Client donneur d\'ordre', type: 'text', required: true },
      { key: 'type_roche', label: 'Type de roche à concasser', type: 'text', required: true },
      { key: 'granulometries', label: 'Granulométries requises (ex: 0/4, 6/10, 10/14)', type: 'text', required: true },
      { key: 'date_debut_production', label: 'Date de début de production', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CONCASSAGE ET GRANULATS</h1><p>Prestataire : <strong>{{prestataire_concassage}}</strong> | Client : <strong>{{client}}</strong></p><h3>Article 1 – Prestation</h3><p>Depuis le <strong>{{date_debut_production}}</strong>, le prestataire concasse de la <strong>{{type_roche}}</strong> pour produire des granulats aux coupures <strong>{{granulometries}}</strong>.</p><h3>Article 2 – Contrôle qualité</h3><p>Des courbes granulométriques sont établies chaque semaine et mises à la disposition du client.</p><h3>Article 3 – Capacité</h3><p>Le prestataire garantit une capacité de production continue conforme au planning de chantier du client.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_sable_manufacture',
    name: "Accord de service de production de sable manufacturé",
    category: 'btp_construction',
    price: 6500,
    priceMax: 22000,
    description: "Convention de production de sable de roche (sable manufacturé) par broyage de granite ou basalte, en substitution au sable de rivière dans les bétons.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'producteur_sable', label: 'Producteur de sable manufacturé', type: 'text', required: true },
      { key: 'client_beton', label: 'Client (centrale béton / entreprise BTP)', type: 'text', required: true },
      { key: 'roche_source', label: 'Roche source utilisée', type: 'text', required: true },
      { key: 'volume_mensuel', label: 'Volume mensuel (m3)', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PRODUCTION DE SABLE MANUFACTURÉ</h1><p>Producteur : <strong>{{producteur_sable}}</strong> | Client : <strong>{{client_beton}}</strong></p><h3>Article 1 – Production</h3><p>Depuis le <strong>{{date_debut}}</strong>, le producteur fournit <strong>{{volume_mensuel}}</strong> m3 par mois de sable manufacturé issu du broyage de <strong>{{roche_source}}</strong>.</p><h3>Article 2 – Conformité</h3><p>Le sable répond aux spécifications NF EN 12620 adaptées aux bétons courants ivoiriens.</p><h3>Article 3 – Avantage environnemental</h3><p>Le recours au sable manufacturé contribue à la préservation des cours d'eau et est favorisé dans les marchés publics.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_vente_graviers_sables',
    name: "Contrat de vente de graviers et sables",
    category: 'btp_construction',
    price: 4000,
    priceMax: 13000,
    description: "Contrat commercial de vente de granulats (graviers, sables) entre un exploitant de carrière et une entreprise de BTP, avec conditions de livraison et de paiement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'vendeur_carriere', label: 'Exploitant de carrière (vendeur)', type: 'text', required: true },
      { key: 'acheteur', label: "Entreprise acheteuse", type: 'text', required: true },
      { key: 'produits', label: 'Produits vendus (description)', type: 'text', required: true },
      { key: 'prix_unitaire', label: 'Prix unitaire par m3 (FCFA)', type: 'text', required: true },
      { key: 'date_contrat', label: 'Date du contrat', type: 'date', required: true },
      { key: 'conditions_paiement', label: 'Conditions de paiement', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE DE GRAVIERS ET SABLES</h1><p>Vendeur : <strong>{{vendeur_carriere}}</strong> | Acheteur : <strong>{{acheteur}}</strong></p><h3>Article 1 – Objet</h3><p>Le vendeur s'engage à fournir à l'acheteur les produits suivants : <strong>{{produits}}</strong> au prix de <strong>{{prix_unitaire}}</strong> FCFA le m3.</p><h3>Article 2 – Conditions de paiement</h3><p>{{conditions_paiement}}</p><h3>Article 3 – Livraison</h3><p>Les matériaux sont livrés franco chantier, pesée à la bascule de la carrière faisant foi.</p><h3>Article 4 – Litige</h3><p>Tout litige est soumis à la juridiction commerciale d'Abidjan, droit OHADA applicable.</p><p class="signature">Fait le <strong>{{date_contrat}}</strong> — Signatures</p></div>`,
  },
  {
    code: 'carr_transport_materiaux',
    name: "Accord de service de transport de matériaux de carrière",
    category: 'btp_construction',
    price: 5000,
    priceMax: 16000,
    description: "Convention de transport de matériaux de carrière (granulats, sables) entre le site d'extraction et les chantiers clients, incluant gestion des bons de pesée.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'transporteur', label: 'Société de transport', type: 'text', required: true },
      { key: 'carriere_client', label: 'Carrière cliente (expéditeur)', type: 'text', required: true },
      { key: 'zone_livraison', label: 'Zone(s) de livraison', type: 'text', required: true },
      { key: 'prix_km_tonne', label: 'Prix par tonne-km (FCFA)', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSPORT DE MATÉRIAUX DE CARRIÈRE</h1><p>Transporteur : <strong>{{transporteur}}</strong> | Carrière : <strong>{{carriere_client}}</strong></p><h3>Article 1 – Prestations</h3><p>Depuis le <strong>{{date_debut}}</strong>, le transporteur achemine les matériaux de la carrière vers <strong>{{zone_livraison}}</strong> au tarif de <strong>{{prix_km_tonne}}</strong> FCFA par tonne-km.</p><h3>Article 2 – Bons de pesée</h3><p>Chaque camion est pesé à la bascule de la carrière. Le bon de pesée est le document de référence pour la facturation.</p><h3>Article 3 – Responsabilité</h3><p>Le transporteur est responsable des matériaux dès la sortie de la bascule jusqu'à la livraison sur chantier.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_centrale_beton_bac',
    name: "Accord de service de centrale à béton (BAC)",
    category: 'btp_construction',
    price: 12000,
    priceMax: 42000,
    description: "Contrat de prestation de centrale à béton armé confectionné (BAC) pour chantiers de construction, avec formulations béton certifiées BNETD.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'exploitant_centrale', label: 'Exploitant de la centrale à béton', type: 'text', required: true },
      { key: 'client_chantier', label: 'Client (entreprise de BTP / MO)', type: 'text', required: true },
      { key: 'localisation_chantier', label: 'Localisation du chantier', type: 'text', required: true },
      { key: 'classes_beton', label: 'Classes de béton requises (ex: C25/30, C30/37)', type: 'text', required: true },
      { key: 'date_debut_fourniture', label: 'Date de début de fourniture', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — CENTRALE À BÉTON (BAC)</h1><p>Centrale : <strong>{{exploitant_centrale}}</strong> | Client : <strong>{{client_chantier}}</strong> | Chantier : <strong>{{localisation_chantier}}</strong></p><h3>Article 1 – Fourniture</h3><p>Depuis le <strong>{{date_debut_fourniture}}</strong>, la centrale fournit du béton armé confectionné de classes <strong>{{classes_beton}}</strong>.</p><h3>Article 2 – Formulation</h3><p>Les formulations béton sont validées par le BNETD et accompagnées de fiches techniques pour chaque gâchée.</p><h3>Article 3 – Livraison</h3><p>Le béton est livré par toupies sur chantier. Le délai de livraison ne doit pas excéder 90 minutes après malaxage.</p><h3>Article 4 – Contrôle</h3><p>Des éprouvettes cylindriques sont prélevées à chaque livraison pour essais de résistance à 7 et 28 jours.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_fabrication_parpaings',
    name: "Accord de service de fabrication de parpaings/agglos",
    category: 'btp_construction',
    price: 4500,
    priceMax: 15000,
    description: "Contrat de fabrication de parpaings et agglomérés béton pour la construction, conformes aux normes NI-CI sur les produits en béton.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'fabricant', label: 'Fabricant de parpaings', type: 'text', required: true },
      { key: 'client', label: 'Client (entrepreneur / particulier)', type: 'text', required: true },
      { key: 'type_produits', label: 'Types de produits (ex: 15x20x40 plein)', type: 'text', required: true },
      { key: 'quantite', label: 'Quantité commandée (unités)', type: 'text', required: true },
      { key: 'date_livraison', label: 'Date de livraison prévue', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FABRICATION DE PARPAINGS / AGGLOS</h1><p>Fabricant : <strong>{{fabricant}}</strong> | Client : <strong>{{client}}</strong></p><h3>Article 1 – Commande</h3><p>Le client commande <strong>{{quantite}}</strong> unités de <strong>{{type_produits}}</strong>, à livrer le <strong>{{date_livraison}}</strong>.</p><h3>Article 2 – Conformité</h3><p>Les parpaings satisfont aux normes NI-CI sur la résistance à la compression (min. 3,5 MPa pour les parpaings courants).</p><h3>Article 3 – Paiement</h3><p>Acompte de 30% à la commande, solde à la livraison.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_fabrication_tuiles_briques',
    name: "Accord de service de fabrication de tuiles et briques",
    category: 'btp_construction',
    price: 5000,
    priceMax: 17000,
    description: "Convention de fabrication de tuiles céramiques et briques cuites pour la construction, avec contrôle qualité et conformité aux normes ivoiriennes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'tuilerie_fabricant', label: 'Tuilerie / fabricant', type: 'text', required: true },
      { key: 'client', label: 'Client', type: 'text', required: true },
      { key: 'produits_commandes', label: 'Produits commandés (tuiles / briques)', type: 'text', required: true },
      { key: 'quantite', label: 'Quantité (unités)', type: 'text', required: true },
      { key: 'date_livraison', label: 'Date de livraison', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FABRICATION DE TUILES ET BRIQUES</h1><p>Fabricant : <strong>{{tuilerie_fabricant}}</strong> | Client : <strong>{{client}}</strong></p><h3>Article 1 – Commande</h3><p>Le client passe commande de <strong>{{quantite}}</strong> unités de <strong>{{produits_commandes}}</strong>, livraison prévue le <strong>{{date_livraison}}</strong>.</p><h3>Article 2 – Qualité</h3><p>Les produits sont conformes aux normes NF EN sur la résistance au gel et la perméabilité des tuiles céramiques, adaptées au climat ivoirien.</p><h3>Article 3 – Conditions</h3><p>Paiement: 40% à la commande, 60% à la livraison. Retour des produits défectueux accepté sous 10 jours.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_fabrication_paves_beton',
    name: "Accord de service de fabrication de pavés en béton",
    category: 'btp_construction',
    price: 5500,
    priceMax: 18000,
    description: "Contrat de fabrication de pavés autobloquants en béton pour voirie urbaine et aménagements paysagers, conformes aux normes LBTP de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'fabricant_paves', label: 'Fabricant de pavés', type: 'text', required: true },
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage ou entrepreneur", type: 'text', required: true },
      { key: 'format_paves', label: 'Format des pavés (ex: 10x20x8 cm)', type: 'text', required: true },
      { key: 'quantite_m2', label: 'Quantité commandée (m2)', type: 'text', required: true },
      { key: 'date_livraison', label: 'Date de livraison', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE FABRICATION DE PAVÉS EN BÉTON</h1><p>Fabricant : <strong>{{fabricant_paves}}</strong> | Client : <strong>{{maitre_ouvrage}}</strong></p><h3>Article 1 – Commande</h3><p>Le client commande <strong>{{quantite_m2}}</strong> m2 de pavés autobloquants format <strong>{{format_paves}}</strong>, livraison le <strong>{{date_livraison}}</strong>.</p><h3>Article 2 – Résistance</h3><p>Les pavés béton présentent une résistance minimale à la compression de 50 MPa conformément aux normes LBTP pour voirie urbaine.</p><h3>Article 3 – Garantie</h3><p>Le fabricant garantit les pavés 2 ans contre tout défaut de fabrication.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_distribution_ciment',
    name: "Accord de service de production de ciment (distributeur)",
    category: 'btp_construction',
    price: 9000,
    priceMax: 32000,
    description: "Convention de distribution de ciment entre un cimentier agréé et un réseau de distributeurs régionaux en Côte d'Ivoire, avec quotas et prix homologués.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'cimentier', label: 'Cimentier producteur', type: 'text', required: true },
      { key: 'distributeur', label: 'Distributeur agréé', type: 'text', required: true },
      { key: 'zone_distribution', label: 'Zone de distribution exclusive', type: 'text', required: true },
      { key: 'quota_mensuel', label: 'Quota mensuel (tonnes)', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début', type: 'date', required: true },
      { key: 'prix_sortie_usine', label: 'Prix sortie usine (FCFA/sac)', type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTION DE CIMENT</h1><p>Cimentier : <strong>{{cimentier}}</strong> | Distributeur : <strong>{{distributeur}}</strong> | Zone : <strong>{{zone_distribution}}</strong></p><h3>Article 1 – Exclusivité</h3><p>Le distributeur bénéficie d'une exclusivité de distribution dans sa zone depuis le <strong>{{date_debut}}</strong>.</p><h3>Article 2 – Quota et prix</h3><p>Quota mensuel : <strong>{{quota_mensuel}}</strong> tonnes. Prix sortie usine : <strong>{{prix_sortie_usine}}</strong> FCFA par sac de 50 kg.</p><h3>Article 3 – Prix de revente</h3><p>Le prix de revente au détail est plafonné conformément aux homologations du Ministère du Commerce.</p><h3>Article 4 – Obligations</h3><p>Le distributeur s'engage à maintenir un stock minimum de 15 jours et à ne pas exporter hors de sa zone.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_controle_qualite_btp',
    name: "Accord de service de contrôle qualité matériaux BTP",
    category: 'btp_construction',
    price: 8000,
    priceMax: 28000,
    description: "Convention de prestation de laboratoire pour le contrôle qualité des matériaux de construction (granulats, béton, sols, bitume), agréé LBTP.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'laboratoire', label: 'Laboratoire de contrôle (agréé LBTP)', type: 'text', required: true },
      { key: 'client_chantier', label: 'Client (maître d\'ouvrage / entreprise)', type: 'text', required: true },
      { key: 'chantier', label: 'Désignation du chantier', type: 'text', required: true },
      { key: 'materiaux_controles', label: 'Matériaux soumis au contrôle', type: 'textarea', required: true },
      { key: 'date_debut_mission', label: 'Date de début de mission', type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONTRÔLE QUALITÉ MATÉRIAUX BTP</h1><p>Laboratoire : <strong>{{laboratoire}}</strong> | Client : <strong>{{client_chantier}}</strong> | Chantier : <strong>{{chantier}}</strong></p><h3>Article 1 – Mission</h3><p>Depuis le <strong>{{date_debut_mission}}</strong>, le laboratoire agréé LBTP assure le contrôle qualité des matériaux suivants :</p><p>{{materiaux_controles}}</p><h3>Article 2 – Rapports</h3><p>Un rapport d'essais est émis dans les 72 heures suivant chaque prélèvement.</p><h3>Article 3 – Non-conformités</h3><p>Tout résultat non conforme est signalé immédiatement au client et au bureau de contrôle du chantier.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_rehabilitation_carriere',
    name: "Accord de service de réhabilitation de carrière (remise en état)",
    category: 'btp_construction',
    price: 9000,
    priceMax: 32000,
    description: "Contrat de réhabilitation et de remise en état environnementale d'une carrière en fin d'exploitation, incluant revégétalisation et stabilisation des fronts de taille.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'entreprise_rehab', label: 'Entreprise de réhabilitation', type: 'text', required: true },
      { key: 'exploitant_carriere', label: 'Exploitant de la carrière', type: 'text', required: true },
      { key: 'localisation', label: 'Localisation de la carrière', type: 'text', required: true },
      { key: 'superficie_ha', label: 'Superficie à réhabiliter (ha)', type: 'text', required: true },
      { key: 'date_debut_travaux', label: 'Date de début des travaux', type: 'date', required: true },
      { key: 'plan_travaux', label: 'Plan de réhabilitation détaillé', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉHABILITATION DE CARRIÈRE</h1><p>Entreprise : <strong>{{entreprise_rehab}}</strong> | Exploitant : <strong>{{exploitant_carriere}}</strong> | Site : <strong>{{localisation}}</strong></p><h3>Article 1 – Périmètre</h3><p>Les travaux débutent le <strong>{{date_debut_travaux}}</strong> sur <strong>{{superficie_ha}}</strong> hectares.</p><h3>Article 2 – Plan de réhabilitation</h3><p>{{plan_travaux}}</p><h3>Article 3 – Réception</h3><p>La réception définitive est prononcée par un expert ANDE après vérification de la végétalisation et de la stabilité des talus.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_securite_carriere',
    name: "Accord de service de sécurité carrière",
    category: 'btp_construction',
    price: 5500,
    priceMax: 18000,
    description: "Convention de sécurité industrielle pour exploitation de carrière incluant sécurisation des fronts de taille, gestion des tirs de mines et plan de prévention.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'responsable_securite', label: 'Responsable sécurité / prestataire', type: 'text', required: true },
      { key: 'exploitant', label: 'Exploitant de la carrière', type: 'text', required: true },
      { key: 'nom_carriere', label: 'Nom de la carrière', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de prise en charge', type: 'date', required: true },
      { key: 'plan_prevention', label: 'Éléments du plan de prévention', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SÉCURITÉ — CARRIÈRE</h1><p>Responsable sécurité : <strong>{{responsable_securite}}</strong> | Carrière : <strong>{{nom_carriere}}</strong> | Exploitant : <strong>{{exploitant}}</strong></p><h3>Article 1 – Mission</h3><p>Depuis le <strong>{{date_debut}}</strong>, le responsable assure la sécurité industrielle de la carrière, notamment lors des tirs de mines.</p><h3>Article 2 – Plan de prévention</h3><p>{{plan_prevention}}</p><h3>Article 3 – Tirs de mines</h3><p>Toute opération de tir est soumise à autorisation préalable de l'Inspection du travail et conduite exclusivement par un artificier agréé.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_environnement_carrieres',
    name: "Accord de service d'environnement carrière (poussières, bruit)",
    category: 'btp_construction',
    price: 6000,
    priceMax: 20000,
    description: "Convention de suivi et de maîtrise des impacts environnementaux d'une carrière: gestion des poussières, contrôle du bruit, surveillance de la qualité de l'eau.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'bureau_environnement', label: "Bureau d'études environnement", type: 'text', required: true },
      { key: 'exploitant_carriere', label: 'Exploitant de la carrière', type: 'text', required: true },
      { key: 'nom_carriere', label: 'Nom de la carrière', type: 'text', required: true },
      { key: 'date_mission', label: 'Date de début de mission', type: 'date', required: true },
      { key: 'parametres_surveilles', label: 'Paramètres environnementaux surveillés', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SUIVI ENVIRONNEMENTAL — CARRIÈRE</h1><p>Bureau d'études : <strong>{{bureau_environnement}}</strong> | Exploitant : <strong>{{exploitant_carriere}}</strong> | Carrière : <strong>{{nom_carriere}}</strong></p><h3>Article 1 – Mission</h3><p>Depuis le <strong>{{date_mission}}</strong>, le bureau assure le suivi environnemental de la carrière.</p><h3>Article 2 – Paramètres surveillés</h3><p>{{parametres_surveilles}}</p><h3>Article 3 – Seuils</h3><p>Bruit : limite de 70 dB(A) en limite de propriété. Poussières : PM10 inférieur à 150 µg/m3 en moyenne journalière.</p><h3>Article 4 – Rapport</h3><p>Un rapport trimestriel est transmis à l'ANDE et à l'exploitant.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_partenariat_entreprise_btp',
    name: "Accord de partenariat carrière-entreprise BTP",
    category: 'btp_construction',
    price: 7000,
    priceMax: 24000,
    description: "Convention de partenariat stratégique et commercial entre une carrière et une entreprise de BTP pour l'approvisionnement exclusif en matériaux sur plusieurs projets.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'carriere', label: 'Exploitant de carrière', type: 'text', required: true },
      { key: 'entreprise_btp', label: 'Entreprise de BTP partenaire', type: 'text', required: true },
      { key: 'projets_concernes', label: 'Projets BTP concernés', type: 'textarea', required: true },
      { key: 'date_debut', label: 'Date de début du partenariat', type: 'date', required: true },
      { key: 'remise_accordee', label: 'Remise commerciale accordée (%)', type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT CARRIÈRE — ENTREPRISE BTP</h1><p>Carrière : <strong>{{carriere}}</strong> | Entreprise BTP : <strong>{{entreprise_btp}}</strong></p><h3>Article 1 – Partenariat</h3><p>Depuis le <strong>{{date_debut}}</strong>, la carrière est le fournisseur prioritaire de l'entreprise pour les projets suivants :</p><p>{{projets_concernes}}</p><h3>Article 2 – Conditions commerciales</h3><p>Une remise de <strong>{{remise_accordee}}</strong>% est consentie sur les tarifs carrière en vigueur.</p><h3>Article 3 – Engagement de volume</h3><p>L'entreprise BTP s'engage à s'approvisionner prioritairement auprès de la carrière partenaire sous réserve de disponibilité et de qualité.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_rapport_performance_carriere',
    name: "Rapport de performance exploitation de carrière",
    category: 'btp_construction',
    price: 4000,
    priceMax: 13000,
    description: "Modèle de rapport périodique de performance d'une exploitation de carrière couvrant production, qualité, sécurité, environnement et indicateurs financiers.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_carriere', label: 'Nom de la carrière', type: 'text', required: true },
      { key: 'responsable', label: 'Directeur / responsable de site', type: 'text', required: true },
      { key: 'periode', label: 'Période du rapport', type: 'text', required: true },
      { key: 'date_rapport', label: 'Date du rapport', type: 'date', required: true },
      { key: 'indicateurs_cles', label: 'Indicateurs clés de performance (production, qualité, sécurité)', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE — EXPLOITATION DE CARRIÈRE</h1><p>Carrière : <strong>{{nom_carriere}}</strong> | Responsable : <strong>{{responsable}}</strong> | Période : <strong>{{periode}}</strong> | Date : <strong>{{date_rapport}}</strong></p><h3>1. Production</h3><p>Volumes extraits et vendus par produit par rapport aux objectifs fixés.</p><h3>2. Qualité</h3><p>Résultats des essais laboratoire — conformités et non-conformités détectées.</p><h3>3. Sécurité</h3><p>Nombre d'accidents, taux de fréquence, actions correctives en cours.</p><h3>4. Environnement</h3><p>Mesures de bruit et poussières, incidents environnementaux, avancement réhabilitation.</p><h3>5. Indicateurs clés</h3><p>{{indicateurs_cles}}</p><p class="signature">Signé par le responsable de site</p></div>`,
  },
  {
    code: 'carr_plan_developpement_carriere',
    name: "Plan de développement exploitation de carrière",
    category: 'btp_construction',
    price: 10000,
    priceMax: 35000,
    description: "Document de planification stratégique du développement d'une exploitation de carrière sur 3 à 5 ans, incluant investissements, production, marché et volet environnemental.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'nom_carriere', label: 'Nom de la carrière', type: 'text', required: true },
      { key: 'directeur_general', label: 'Directeur général', type: 'text', required: true },
      { key: 'periode_plan', label: 'Période couverte (ex: 2025-2029)', type: 'text', required: true },
      { key: 'date_validation', label: 'Date de validation', type: 'date', required: true },
      { key: 'objectifs_strategiques', label: 'Objectifs stratégiques', type: 'textarea', required: true },
      { key: 'investissements_prevus', label: 'Investissements prévus', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT — EXPLOITATION DE CARRIÈRE</h1><p>Carrière : <strong>{{nom_carriere}}</strong> | DG : <strong>{{directeur_general}}</strong> | Période : <strong>{{periode_plan}}</strong></p><h3>1. Contexte</h3><p>Le présent plan, validé le <strong>{{date_validation}}</strong>, définit la stratégie de développement de la carrière pour les prochaines années.</p><h3>2. Objectifs stratégiques</h3><p>{{objectifs_strategiques}}</p><h3>3. Plan d'investissement</h3><p>{{investissements_prevus}}</p><h3>4. Volet environnemental</h3><p>Le plan intègre un budget de réhabilitation progressive et les objectifs de réduction des nuisances conformément aux engagements ANDE.</p><p class="signature">Validation du Conseil d'Administration</p></div>`,
  },
  {
    code: 'carr_certification_materiaux_ni_ci',
    name: "Accord de service de certification matériaux (NI-CI)",
    category: 'btp_construction',
    price: 8000,
    priceMax: 28000,
    description: "Convention de certification des matériaux de construction selon les Normes Ivoiriennes (NI-CI) avec essais en laboratoire agréé CODINORM.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'organisme_certification', label: 'Organisme certificateur (CODINORM/agréé)', type: 'text', required: true },
      { key: 'fabricant', label: 'Fabricant demandeur', type: 'text', required: true },
      { key: 'produits_certifies', label: 'Produits soumis à certification', type: 'text', required: true },
      { key: 'norme_applicable', label: 'Norme NI-CI applicable', type: 'text', required: true },
      { key: 'date_audit', label: "Date de l'audit de certification", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION MATÉRIAUX — NI-CI</h1><p>Organisme : <strong>{{organisme_certification}}</strong> | Fabricant : <strong>{{fabricant}}</strong></p><h3>Article 1 – Objet</h3><p>Le fabricant soumet ses produits <strong>{{produits_certifies}}</strong> à la certification selon la norme <strong>{{norme_applicable}}</strong>.</p><h3>Article 2 – Audit</h3><p>L'audit de certification est planifié le <strong>{{date_audit}}</strong>. Le fabricant s'engage à donner accès à ses installations et à fournir tous les documents requis.</p><h3>Article 3 – Marquage</h3><p>En cas de résultat positif, le fabricant est autorisé à apposer le marquage NI-CI sur ses produits certifiés.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_laboratoire_materiaux_btp',
    name: "Accord de service de laboratoire matériaux BTP",
    category: 'btp_construction',
    price: 7500,
    priceMax: 26000,
    description: "Contrat de prestation de services de laboratoire géotechnique et matériaux pour projets BTP en Côte d'Ivoire, incluant essais sols, béton, bitume et granulats.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'laboratoire', label: 'Laboratoire prestataire', type: 'text', required: true },
      { key: 'client', label: 'Client (MO / entreprise)', type: 'text', required: true },
      { key: 'projet', label: 'Projet concerné', type: 'text', required: true },
      { key: 'date_debut', label: 'Date de début des essais', type: 'date', required: true },
      { key: 'catalogue_essais', label: 'Catalogue des essais commandés', type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE LABORATOIRE MATÉRIAUX BTP</h1><p>Laboratoire : <strong>{{laboratoire}}</strong> | Client : <strong>{{client}}</strong> | Projet : <strong>{{projet}}</strong></p><h3>Article 1 – Prestations</h3><p>Depuis le <strong>{{date_debut}}</strong>, le laboratoire réalise les essais suivants :</p><p>{{catalogue_essais}}</p><h3>Article 2 – Délais</h3><p>Les résultats d'essais sont communiqués dans les délais convenus pour chaque type d'essai (24h à 28 jours selon nature).</p><h3>Article 3 – Accréditation</h3><p>Le laboratoire est accrédité par COFRAC / LBTP et ses résultats sont opposables aux tiers.</p><p class="signature">Signatures</p></div>`,
  },
  {
    code: 'carr_charte_exploitation_responsable',
    name: "Charte de l'exploitation responsable de carrière",
    category: 'btp_construction',
    price: 4500,
    priceMax: 15000,
    description: "Charte d'engagement volontaire des exploitants de carrières ivoiriennes pour des pratiques durables: environnement, sécurité, relations communautaires et gouvernance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'signataire', label: 'Exploitant signataire', type: 'text', required: true },
      { key: 'nom_carriere', label: 'Nom de la carrière', type: 'text', required: true },
      { key: 'date_signature', label: 'Date de signature', type: 'date', required: true },
      { key: 'engagements_additionnels', label: 'Engagements additionnels spécifiques', type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE L'EXPLOITATION RESPONSABLE DE CARRIÈRE</h1><h2>Côte d'Ivoire — Secteur BTP</h2><p>Signataire : <strong>{{signataire}}</strong> | Carrière : <strong>{{nom_carriere}}</strong> | Date : <strong>{{date_signature}}</strong></p><h3>Préambule</h3><p>Conscients de l'impact de leurs activités sur l'environnement et les communautés riveraines, les exploitants signataires s'engagent à adopter des pratiques responsables.</p><h3>Engagement 1 – Environnement</h3><p>Respecter les seuils de bruit et de poussières. Réhabiliter progressivement les zones exploitées. Ne pas extraire dans les zones humides protégées.</p><h3>Engagement 2 – Sécurité</h3><p>Former tous les travailleurs aux risques spécifiques des carrières. Respecter les procédures de tir de mines. Maintenir les équipements de protection.</p><h3>Engagement 3 – Communautés</h3><p>Consulter les communautés riveraines avant l'extension des opérations. Contribuer au développement local.</p><h3>Engagements additionnels</h3><p>{{engagements_additionnels}}</p><p class="signature">Signature de l'exploitant</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 62a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
