import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);

const templates = [
  // ─── 25 ADMINISTRATION (adm3_ / adm4_) ───────────────────────────────────
  {
    code: 'adm3_memo_interne',
    name: "Mémo Interne",
    category: 'juridique_admin',
    price: 1500,
    priceMax: 4500,
    description: "Mémo interne pour communication officielle entre services ou directions.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'destinataire', label: "Destinataire", type: 'text', required: true },
      { key: 'expediteur', label: "Expéditeur", type: 'text', required: true },
      { key: 'objet', label: "Objet du mémo", type: 'text', required: true },
      { key: 'date_memo', label: "Date", type: 'date', required: true },
      { key: 'contenu', label: "Contenu du mémo", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>MÉMO INTERNE</h1><p><strong>À :</strong> {{destinataire}}</p><p><strong>De :</strong> {{expediteur}}</p><p><strong>Objet :</strong> {{objet}}</p><p><strong>Date :</strong> {{date_memo}}</p><hr/><p>{{contenu}}</p></div>`,
  },
  {
    code: 'adm3_instruction_travail',
    name: "Instruction de Travail",
    category: 'juridique_admin',
    price: 2000,
    priceMax: 6000,
    description: "Document décrivant les procédures et étapes à suivre pour réaliser une tâche spécifique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'titre_instruction', label: "Titre de l'instruction", type: 'text', required: true },
      { key: 'service_concerne', label: "Service concerné", type: 'text', required: true },
      { key: 'redacteur', label: "Rédacteur", type: 'text', required: true },
      { key: 'version', label: "Version", type: 'text', required: true },
      { key: 'etapes', label: "Étapes de la procédure", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>INSTRUCTION DE TRAVAIL</h1><p><strong>Titre :</strong> {{titre_instruction}}</p><p><strong>Service :</strong> {{service_concerne}}</p><p><strong>Rédacteur :</strong> {{redacteur}} — Version : {{version}}</p><hr/><p>{{etapes}}</p></div>`,
  },
  {
    code: 'adm3_note_frais_voyage',
    name: "Note de Frais Voyage",
    category: 'juridique_admin',
    price: 1200,
    priceMax: 3600,
    description: "Formulaire de déclaration et remboursement des frais engagés lors d'un déplacement professionnel.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_agent', label: "Nom de l'agent", type: 'text', required: true },
      { key: 'destination', label: "Destination", type: 'text', required: true },
      { key: 'date_depart', label: "Date de départ", type: 'date', required: true },
      { key: 'date_retour', label: "Date de retour", type: 'date', required: true },
      { key: 'montant_total', label: "Montant total (FCFA)", type: 'number', required: true },
      { key: 'detail_frais', label: "Détail des frais", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>NOTE DE FRAIS VOYAGE</h1><p><strong>Agent :</strong> {{nom_agent}}</p><p><strong>Destination :</strong> {{destination}}</p><p><strong>Départ :</strong> {{date_depart}} — <strong>Retour :</strong> {{date_retour}}</p><p><strong>Montant total :</strong> {{montant_total}} FCFA</p><hr/><p>{{detail_frais}}</p></div>`,
  },
  {
    code: 'adm3_registre_courrier',
    name: "Registre de Courrier",
    category: 'juridique_admin',
    price: 1000,
    priceMax: 3000,
    description: "Registre officiel d'enregistrement du courrier entrant et sortant d'une administration.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'structure', label: "Structure", type: 'text', required: true },
      { key: 'annee', label: "Année", type: 'text', required: true },
      { key: 'type_courrier', label: "Type de courrier", type: 'select', required: true },
      { key: 'numero', label: "Numéro d'ordre", type: 'text', required: true },
      { key: 'expediteur_dest', label: "Expéditeur / Destinataire", type: 'text', required: true },
      { key: 'objet_courrier', label: "Objet", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>REGISTRE DE COURRIER</h1><p><strong>Structure :</strong> {{structure}} — <strong>Année :</strong> {{annee}}</p><p><strong>Type :</strong> {{type_courrier}} — <strong>N° :</strong> {{numero}}</p><p><strong>Expéditeur/Dest. :</strong> {{expediteur_dest}}</p><p><strong>Objet :</strong> {{objet_courrier}}</p></div>`,
  },
  {
    code: 'adm3_fiche_transmission',
    name: "Fiche de Transmission",
    category: 'juridique_admin',
    price: 800,
    priceMax: 2400,
    description: "Fiche accompagnant le transfert de documents entre services ou entités administratives.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'service_emetteur', label: "Service émetteur", type: 'text', required: true },
      { key: 'service_recepteur', label: "Service récepteur", type: 'text', required: true },
      { key: 'liste_documents', label: "Liste des documents transmis", type: 'textarea', required: true },
      { key: 'date_transmission', label: "Date de transmission", type: 'date', required: true },
      { key: 'signature_emetteur', label: "Signature émetteur", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>FICHE DE TRANSMISSION</h1><p><strong>De :</strong> {{service_emetteur}} — <strong>À :</strong> {{service_recepteur}}</p><p><strong>Date :</strong> {{date_transmission}}</p><hr/><p><strong>Documents transmis :</strong><br/>{{liste_documents}}</p><p><strong>Signature :</strong> {{signature_emetteur}}</p></div>`,
  },
  {
    code: 'adm3_rapport_reunion_direction',
    name: "Rapport de Réunion de Direction",
    category: 'juridique_admin',
    price: 3000,
    priceMax: 9000,
    description: "Rapport formel consignant les délibérations et décisions des réunions de direction.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'date_reunion', label: "Date de la réunion", type: 'date', required: true },
      { key: 'president_seance', label: "Président de séance", type: 'text', required: true },
      { key: 'participants', label: "Participants", type: 'textarea', required: true },
      { key: 'ordre_du_jour', label: "Ordre du jour", type: 'textarea', required: true },
      { key: 'deliberations', label: "Délibérations", type: 'textarea', required: true },
      { key: 'decisions', label: "Décisions prises", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE RÉUNION DE DIRECTION</h1><p><strong>Date :</strong> {{date_reunion}}</p><p><strong>Président :</strong> {{president_seance}}</p><p><strong>Participants :</strong><br/>{{participants}}</p><p><strong>Ordre du jour :</strong><br/>{{ordre_du_jour}}</p><p><strong>Délibérations :</strong><br/>{{deliberations}}</p><p><strong>Décisions :</strong><br/>{{decisions}}</p></div>`,
  },
  {
    code: 'adm3_compte_rendu_visite',
    name: "Compte Rendu de Visite",
    category: 'juridique_admin',
    price: 1800,
    priceMax: 5400,
    description: "Compte rendu rédigé à l'issue d'une visite de terrain, d'inspection ou de contrôle.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'lieu_visite', label: "Lieu visité", type: 'text', required: true },
      { key: 'date_visite', label: "Date de visite", type: 'date', required: true },
      { key: 'visiteurs', label: "Membres de l'équipe de visite", type: 'textarea', required: true },
      { key: 'observations', label: "Observations", type: 'textarea', required: true },
      { key: 'recommandations', label: "Recommandations", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>COMPTE RENDU DE VISITE</h1><p><strong>Lieu :</strong> {{lieu_visite}} — <strong>Date :</strong> {{date_visite}}</p><p><strong>Équipe :</strong><br/>{{visiteurs}}</p><hr/><p><strong>Observations :</strong><br/>{{observations}}</p><p><strong>Recommandations :</strong><br/>{{recommandations}}</p></div>`,
  },
  {
    code: 'adm3_bilan_formation',
    name: "Bilan de Formation",
    category: 'juridique_admin',
    price: 2500,
    priceMax: 7500,
    description: "Document de synthèse évaluant les résultats et l'impact d'une session de formation professionnelle.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'intitule_formation', label: "Intitulé de la formation", type: 'text', required: true },
      { key: 'formateur', label: "Formateur", type: 'text', required: true },
      { key: 'periode', label: "Période", type: 'text', required: true },
      { key: 'effectif', label: "Effectif formé", type: 'number', required: true },
      { key: 'objectifs_atteints', label: "Objectifs atteints", type: 'textarea', required: true },
      { key: 'points_amelioration', label: "Points d'amélioration", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>BILAN DE FORMATION</h1><p><strong>Formation :</strong> {{intitule_formation}}</p><p><strong>Formateur :</strong> {{formateur}} — <strong>Période :</strong> {{periode}}</p><p><strong>Effectif :</strong> {{effectif}} participants</p><hr/><p><strong>Objectifs atteints :</strong><br/>{{objectifs_atteints}}</p><p><strong>Améliorations :</strong><br/>{{points_amelioration}}</p></div>`,
  },
  {
    code: 'adm3_procedure_administrative',
    name: "Procédure Administrative",
    category: 'juridique_admin',
    price: 3500,
    priceMax: 10500,
    description: "Document décrivant formellement les procédures internes d'un service ou d'une administration.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'reference_procedure', label: "Référence de la procédure", type: 'text', required: true },
      { key: 'domaine', label: "Domaine d'application", type: 'text', required: true },
      { key: 'responsable', label: "Responsable", type: 'text', required: true },
      { key: 'description_procedure', label: "Description de la procédure", type: 'textarea', required: true },
      { key: 'documents_associes', label: "Documents associés", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE ADMINISTRATIVE</h1><p><strong>Référence :</strong> {{reference_procedure}} — <strong>Domaine :</strong> {{domaine}}</p><p><strong>Responsable :</strong> {{responsable}}</p><hr/><p><strong>Procédure :</strong><br/>{{description_procedure}}</p><p><strong>Documents associés :</strong><br/>{{documents_associes}}</p></div>`,
  },
  {
    code: 'adm3_demande_materiel',
    name: "Formulaire de Demande de Matériel",
    category: 'juridique_admin',
    price: 700,
    priceMax: 2100,
    description: "Formulaire officiel de demande d'approvisionnement en matériel ou fournitures de bureau.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'service_demandeur', label: "Service demandeur", type: 'text', required: true },
      { key: 'responsable_service', label: "Responsable du service", type: 'text', required: true },
      { key: 'liste_materiel', label: "Liste du matériel demandé", type: 'textarea', required: true },
      { key: 'justification', label: "Justification de la demande", type: 'textarea', required: true },
      { key: 'date_besoin', label: "Date de besoin", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>FORMULAIRE DE DEMANDE DE MATÉRIEL</h1><p><strong>Service :</strong> {{service_demandeur}} — <strong>Responsable :</strong> {{responsable_service}}</p><p><strong>Date de besoin :</strong> {{date_besoin}}</p><hr/><p><strong>Matériel demandé :</strong><br/>{{liste_materiel}}</p><p><strong>Justification :</strong><br/>{{justification}}</p></div>`,
  },
  {
    code: 'adm3_fiche_archivage',
    name: "Fiche d'Archivage",
    category: 'juridique_admin',
    price: 900,
    priceMax: 2700,
    description: "Fiche de référencement et de classement des documents archivés dans un service.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 40,
    fieldsJson: F([
      { key: 'reference_archive', label: "Référence d'archive", type: 'text', required: true },
      { key: 'intitule_dossier', label: "Intitulé du dossier", type: 'text', required: true },
      { key: 'date_creation', label: "Date de création", type: 'date', required: true },
      { key: 'date_archivage', label: "Date d'archivage", type: 'date', required: true },
      { key: 'lieu_conservation', label: "Lieu de conservation", type: 'text', required: true },
      { key: 'duree_conservation', label: "Durée de conservation", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE D'ARCHIVAGE</h1><p><strong>Référence :</strong> {{reference_archive}}</p><p><strong>Dossier :</strong> {{intitule_dossier}}</p><p><strong>Créé le :</strong> {{date_creation}} — <strong>Archivé le :</strong> {{date_archivage}}</p><p><strong>Conservation :</strong> {{lieu_conservation}} — Durée : {{duree_conservation}}</p></div>`,
  },
  {
    code: 'adm3_lettre_relance_admin',
    name: "Lettre de Relance Administrative",
    category: 'juridique_admin',
    price: 1100,
    priceMax: 3300,
    description: "Lettre officielle de relance adressée à un service ou une entité pour obtenir une réponse ou un document.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'expediteur_admin', label: "Expéditeur (administration)", type: 'text', required: true },
      { key: 'destinataire_admin', label: "Destinataire", type: 'text', required: true },
      { key: 'reference_initiale', label: "Référence du courrier initial", type: 'text', required: true },
      { key: 'date_initiale', label: "Date du courrier initial", type: 'date', required: true },
      { key: 'objet_relance', label: "Objet de la relance", type: 'text', required: true },
      { key: 'contenu_relance', label: "Corps de la lettre", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>LETTRE DE RELANCE ADMINISTRATIVE</h1><p><strong>De :</strong> {{expediteur_admin}}</p><p><strong>À :</strong> {{destinataire_admin}}</p><p><strong>Réf. initiale :</strong> {{reference_initiale}} du {{date_initiale}}</p><p><strong>Objet :</strong> {{objet_relance}}</p><hr/><p>{{contenu_relance}}</p></div>`,
  },
  {
    code: 'adm3_avis_reunion',
    name: "Avis de Réunion",
    category: 'juridique_admin',
    price: 600,
    priceMax: 1800,
    description: "Convocation officielle à une réunion interne ou interservices.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'objet_reunion', label: "Objet de la réunion", type: 'text', required: true },
      { key: 'date_heure', label: "Date et heure", type: 'text', required: true },
      { key: 'lieu_reunion', label: "Lieu", type: 'text', required: true },
      { key: 'personnes_convoquees', label: "Personnes convoquées", type: 'textarea', required: true },
      { key: 'ordre_du_jour_avis', label: "Ordre du jour", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>AVIS DE RÉUNION</h1><p><strong>Objet :</strong> {{objet_reunion}}</p><p><strong>Date et heure :</strong> {{date_heure}} — <strong>Lieu :</strong> {{lieu_reunion}}</p><p><strong>Convoqués :</strong><br/>{{personnes_convoquees}}</p><p><strong>Ordre du jour :</strong><br/>{{ordre_du_jour_avis}}</p></div>`,
  },
  {
    code: 'adm4_inventaire_bureau',
    name: "Fiche d'Inventaire de Bureau",
    category: 'juridique_admin',
    price: 1300,
    priceMax: 3900,
    description: "Fiche de recensement et d'inventaire des équipements et mobiliers d'un bureau ou service.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 43,
    fieldsJson: F([
      { key: 'service_inventorie', label: "Service inventorié", type: 'text', required: true },
      { key: 'date_inventaire', label: "Date d'inventaire", type: 'date', required: true },
      { key: 'responsable_inventaire', label: "Responsable", type: 'text', required: true },
      { key: 'liste_biens', label: "Liste des biens", type: 'textarea', required: true },
      { key: 'observations_inventaire', label: "Observations", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>FICHE D'INVENTAIRE DE BUREAU</h1><p><strong>Service :</strong> {{service_inventorie}}</p><p><strong>Date :</strong> {{date_inventaire}} — <strong>Responsable :</strong> {{responsable_inventaire}}</p><hr/><p><strong>Biens inventoriés :</strong><br/>{{liste_biens}}</p><p><strong>Observations :</strong><br/>{{observations_inventaire}}</p></div>`,
  },
  {
    code: 'adm4_rapport_fin_mission',
    name: "Rapport de Fin de Mission",
    category: 'juridique_admin',
    price: 4000,
    priceMax: 12000,
    description: "Rapport de synthèse rédigé à la clôture d'une mission officielle ou d'une affectation temporaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'agent_mission', label: "Agent en mission", type: 'text', required: true },
      { key: 'intitule_mission', label: "Intitulé de la mission", type: 'text', required: true },
      { key: 'periode_mission', label: "Période de la mission", type: 'text', required: true },
      { key: 'resultats', label: "Résultats obtenus", type: 'textarea', required: true },
      { key: 'difficultes', label: "Difficultés rencontrées", type: 'textarea', required: false },
      { key: 'recommandations_mission', label: "Recommandations", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE FIN DE MISSION</h1><p><strong>Agent :</strong> {{agent_mission}}</p><p><strong>Mission :</strong> {{intitule_mission}} — <strong>Période :</strong> {{periode_mission}}</p><hr/><p><strong>Résultats :</strong><br/>{{resultats}}</p><p><strong>Difficultés :</strong><br/>{{difficultes}}</p><p><strong>Recommandations :</strong><br/>{{recommandations_mission}}</p></div>`,
  },
  {
    code: 'adm4_attestation_presence',
    name: "Attestation de Présence",
    category: 'juridique_admin',
    price: 800,
    priceMax: 2400,
    description: "Attestation officielle certifiant la présence d'un agent ou participant à un événement ou poste.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'nom_beneficiaire', label: "Nom du bénéficiaire", type: 'text', required: true },
      { key: 'qualite', label: "Qualité / Fonction", type: 'text', required: true },
      { key: 'evenement', label: "Événement ou poste", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
      { key: 'date_fin', label: "Date de fin", type: 'date', required: true },
      { key: 'autorite_signataire', label: "Autorité signataire", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ATTESTATION DE PRÉSENCE</h1><p>Je soussigné(e), <strong>{{autorite_signataire}}</strong>, atteste que :</p><p><strong>{{nom_beneficiaire}}</strong>, {{qualite}}, a été présent(e) à : <strong>{{evenement}}</strong></p><p>Du <strong>{{date_debut}}</strong> au <strong>{{date_fin}}</strong>.</p><p>En foi de quoi, la présente attestation lui est délivrée pour servir et valoir ce que de droit.</p></div>`,
  },
  {
    code: 'adm4_releve_decisions',
    name: "Relevé de Décisions",
    category: 'juridique_admin',
    price: 1700,
    priceMax: 5100,
    description: "Document synthétisant les décisions prises lors d'une séance ou réunion institutionnelle.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'instance', label: "Instance de décision", type: 'text', required: true },
      { key: 'date_seance', label: "Date de séance", type: 'date', required: true },
      { key: 'decisions_prises', label: "Décisions prises", type: 'textarea', required: true },
      { key: 'responsables_execution', label: "Responsables d'exécution", type: 'textarea', required: true },
      { key: 'delais', label: "Délais d'exécution", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RELEVÉ DE DÉCISIONS</h1><p><strong>Instance :</strong> {{instance}} — <strong>Date :</strong> {{date_seance}}</p><hr/><p><strong>Décisions :</strong><br/>{{decisions_prises}}</p><p><strong>Responsables :</strong><br/>{{responsables_execution}}</p><p><strong>Délais :</strong><br/>{{delais}}</p></div>`,
  },
  {
    code: 'adm4_planning_hebdomadaire',
    name: "Planning de Travail Hebdomadaire",
    category: 'juridique_admin',
    price: 500,
    priceMax: 1500,
    description: "Planning hebdomadaire de répartition des tâches et activités d'un service ou agent.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 38,
    fieldsJson: F([
      { key: 'service_planning', label: "Service", type: 'text', required: true },
      { key: 'semaine', label: "Semaine du", type: 'text', required: true },
      { key: 'responsable_planning', label: "Responsable", type: 'text', required: true },
      { key: 'taches_lundi', label: "Lundi", type: 'textarea', required: false },
      { key: 'taches_mardi', label: "Mardi", type: 'textarea', required: false },
      { key: 'taches_mercredi', label: "Mercredi", type: 'textarea', required: false },
      { key: 'taches_jeudi', label: "Jeudi", type: 'textarea', required: false },
      { key: 'taches_vendredi', label: "Vendredi", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>PLANNING DE TRAVAIL HEBDOMADAIRE</h1><p><strong>Service :</strong> {{service_planning}} — <strong>Semaine du :</strong> {{semaine}}</p><p><strong>Responsable :</strong> {{responsable_planning}}</p><hr/><p><strong>Lundi :</strong> {{taches_lundi}}</p><p><strong>Mardi :</strong> {{taches_mardi}}</p><p><strong>Mercredi :</strong> {{taches_mercredi}}</p><p><strong>Jeudi :</strong> {{taches_jeudi}}</p><p><strong>Vendredi :</strong> {{taches_vendredi}}</p></div>`,
  },
  {
    code: 'adm4_tableau_bord_service',
    name: "Tableau de Bord de Service",
    category: 'juridique_admin',
    price: 4500,
    priceMax: 13500,
    description: "Outil de pilotage synthétique des indicateurs de performance d'un service administratif.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'service_tb', label: "Service", type: 'text', required: true },
      { key: 'periode_tb', label: "Période de reporting", type: 'text', required: true },
      { key: 'indicateurs', label: "Indicateurs clés", type: 'textarea', required: true },
      { key: 'objectifs', label: "Objectifs fixés", type: 'textarea', required: true },
      { key: 'realisations', label: "Réalisations", type: 'textarea', required: true },
      { key: 'plan_action', label: "Plan d'action", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>TABLEAU DE BORD DE SERVICE</h1><p><strong>Service :</strong> {{service_tb}} — <strong>Période :</strong> {{periode_tb}}</p><hr/><p><strong>Indicateurs :</strong><br/>{{indicateurs}}</p><p><strong>Objectifs :</strong><br/>{{objectifs}}</p><p><strong>Réalisations :</strong><br/>{{realisations}}</p><p><strong>Plan d'action :</strong><br/>{{plan_action}}</p></div>`,
  },
  {
    code: 'adm4_cr_reunion_direction',
    name: "Compte Rendu de Réunion de Direction",
    category: 'juridique_admin',
    price: 2800,
    priceMax: 8400,
    description: "Compte rendu formel et structuré d'une réunion de direction avec les points discutés et décisions.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'date_reunion_dir', label: "Date de la réunion", type: 'date', required: true },
      { key: 'heure', label: "Heure", type: 'text', required: true },
      { key: 'lieu_reunion_dir', label: "Lieu", type: 'text', required: true },
      { key: 'membres_presents', label: "Membres présents", type: 'textarea', required: true },
      { key: 'points_discutes', label: "Points discutés", type: 'textarea', required: true },
      { key: 'decisions_dir', label: "Décisions arrêtées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>COMPTE RENDU DE RÉUNION DE DIRECTION</h1><p><strong>Date :</strong> {{date_reunion_dir}} à {{heure}} — <strong>Lieu :</strong> {{lieu_reunion_dir}}</p><p><strong>Présents :</strong><br/>{{membres_presents}}</p><hr/><p><strong>Points discutés :</strong><br/>{{points_discutes}}</p><p><strong>Décisions :</strong><br/>{{decisions_dir}}</p></div>`,
  },
  {
    code: 'adm4_note_info_interne',
    name: "Note d'Information Interne",
    category: 'juridique_admin',
    price: 700,
    priceMax: 2100,
    description: "Note diffusée en interne pour informer le personnel d'une décision, d'une procédure ou d'un événement.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'emetteur_note', label: "Émetteur", type: 'text', required: true },
      { key: 'destinataires_note', label: "Destinataires", type: 'text', required: true },
      { key: 'objet_note', label: "Objet", type: 'text', required: true },
      { key: 'date_note', label: "Date", type: 'date', required: true },
      { key: 'corps_note', label: "Contenu de la note", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>NOTE D'INFORMATION INTERNE</h1><p><strong>De :</strong> {{emetteur_note}} — <strong>À :</strong> {{destinataires_note}}</p><p><strong>Objet :</strong> {{objet_note}} — <strong>Date :</strong> {{date_note}}</p><hr/><p>{{corps_note}}</p></div>`,
  },
  {
    code: 'adm4_lettre_intention_admin',
    name: "Lettre d'Intention Administrative",
    category: 'juridique_admin',
    price: 2200,
    priceMax: 6600,
    description: "Lettre formelle exprimant l'intention d'une administration de s'engager dans un partenariat ou une démarche.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'administration_emettrice', label: "Administration émettrice", type: 'text', required: true },
      { key: 'organisation_destinataire', label: "Organisation destinataire", type: 'text', required: true },
      { key: 'objet_intention', label: "Objet de l'intention", type: 'text', required: true },
      { key: 'description_intention', label: "Description de l'intention", type: 'textarea', required: true },
      { key: 'conditions', label: "Conditions préalables", type: 'textarea', required: false },
      { key: 'signataire', label: "Signataire", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>LETTRE D'INTENTION ADMINISTRATIVE</h1><p><strong>Émetteur :</strong> {{administration_emettrice}}</p><p><strong>Destinataire :</strong> {{organisation_destinataire}}</p><p><strong>Objet :</strong> {{objet_intention}}</p><hr/><p>{{description_intention}}</p><p><strong>Conditions :</strong><br/>{{conditions}}</p><p><strong>Signataire :</strong> {{signataire}}</p></div>`,
  },
  {
    code: 'adm4_acte_certification_admin',
    name: "Acte de Certification Administrative",
    category: 'juridique_admin',
    price: 3200,
    priceMax: 9600,
    description: "Acte officiel par lequel une autorité administrative certifie un fait, un document ou une qualité.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'autorite_certifiante', label: "Autorité certifiante", type: 'text', required: true },
      { key: 'beneficiaire_cert', label: "Bénéficiaire", type: 'text', required: true },
      { key: 'objet_certification', label: "Objet de la certification", type: 'text', required: true },
      { key: 'details_certification', label: "Détails de la certification", type: 'textarea', required: true },
      { key: 'date_emission', label: "Date d'émission", type: 'date', required: true },
      { key: 'validite', label: "Durée de validité", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACTE DE CERTIFICATION ADMINISTRATIVE</h1><p>L'autorité soussignée : <strong>{{autorite_certifiante}}</strong></p><p>Certifie par le présent acte que <strong>{{beneficiaire_cert}}</strong> remplit les conditions relatives à : <strong>{{objet_certification}}</strong></p><p>{{details_certification}}</p><p><strong>Date d'émission :</strong> {{date_emission}} — <strong>Validité :</strong> {{validite}}</p></div>`,
  },
  {
    code: 'adm4_suivi_dossier',
    name: "Fiche de Suivi de Dossier",
    category: 'juridique_admin',
    price: 1000,
    priceMax: 3000,
    description: "Fiche permettant de tracer et suivre l'avancement d'un dossier administratif en cours de traitement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'reference_dossier', label: "Référence du dossier", type: 'text', required: true },
      { key: 'intitule_dossier_suivi', label: "Intitulé du dossier", type: 'text', required: true },
      { key: 'responsable_dossier', label: "Responsable", type: 'text', required: true },
      { key: 'date_ouverture', label: "Date d'ouverture", type: 'date', required: true },
      { key: 'etapes_suivi', label: "Étapes de suivi", type: 'textarea', required: true },
      { key: 'statut_actuel', label: "Statut actuel", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE SUIVI DE DOSSIER</h1><p><strong>Réf. :</strong> {{reference_dossier}} — <strong>Dossier :</strong> {{intitule_dossier_suivi}}</p><p><strong>Responsable :</strong> {{responsable_dossier}} — <strong>Ouvert le :</strong> {{date_ouverture}}</p><p><strong>Statut :</strong> {{statut_actuel}}</p><hr/><p><strong>Étapes de suivi :</strong><br/>{{etapes_suivi}}</p></div>`,
  },
  {
    code: 'adm4_rapport_hebdo_service',
    name: "Rapport Hebdomadaire de Service",
    category: 'juridique_admin',
    price: 1500,
    priceMax: 4500,
    description: "Rapport de synthèse hebdomadaire sur les activités et résultats d'un service administratif.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'service_rapport', label: "Service", type: 'text', required: true },
      { key: 'chef_service', label: "Chef de service", type: 'text', required: true },
      { key: 'semaine_rapport', label: "Semaine du", type: 'text', required: true },
      { key: 'activites_realisees', label: "Activités réalisées", type: 'textarea', required: true },
      { key: 'resultats_semaine', label: "Résultats de la semaine", type: 'textarea', required: true },
      { key: 'problemes', label: "Problèmes rencontrés", type: 'textarea', required: false },
      { key: 'previsions', label: "Prévisions semaine suivante", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT HEBDOMADAIRE DE SERVICE</h1><p><strong>Service :</strong> {{service_rapport}} — <strong>Chef :</strong> {{chef_service}}</p><p><strong>Semaine du :</strong> {{semaine_rapport}}</p><hr/><p><strong>Activités réalisées :</strong><br/>{{activites_realisees}}</p><p><strong>Résultats :</strong><br/>{{resultats_semaine}}</p><p><strong>Problèmes :</strong><br/>{{problemes}}</p><p><strong>Prévisions :</strong><br/>{{previsions}}</p></div>`,
  },

  // ─── 25 JURIDIQUE AVANCÉ (jur3_) ─────────────────────────────────────────
  {
    code: 'jur3_accord_non_concurrence',
    name: "Accord de Non-Concurrence",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Accord contractuel par lequel une partie s'engage à ne pas exercer d'activité concurrente pendant une période définie.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'partie_engagee', label: "Partie engagée", type: 'text', required: true },
      { key: 'beneficiaire_clause', label: "Bénéficiaire de la clause", type: 'text', required: true },
      { key: 'secteur_activite', label: "Secteur d'activité concerné", type: 'text', required: true },
      { key: 'zone_geographique', label: "Zone géographique", type: 'text', required: true },
      { key: 'duree_clause', label: "Durée de la clause", type: 'text', required: true },
      { key: 'contrepartie_financiere', label: "Contrepartie financière (FCFA)", type: 'number', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE NON-CONCURRENCE</h1><p>Entre <strong>{{partie_engagee}}</strong> (ci-après "la Partie engagée") et <strong>{{beneficiaire_clause}}</strong> (ci-après "le Bénéficiaire").</p><p><strong>Secteur :</strong> {{secteur_activite}} — <strong>Zone :</strong> {{zone_geographique}}</p><p><strong>Durée :</strong> {{duree_clause}} — <strong>Contrepartie :</strong> {{contrepartie_financiere}} FCFA</p><p>La Partie engagée s'interdit formellement d'exercer toute activité concurrente dans le secteur et la zone définis ci-dessus pendant la durée indiquée.</p></div>`,
  },
  {
    code: 'jur3_contrat_mandat_special',
    name: "Contrat de Mandat Spécial",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Contrat par lequel un mandant confère à un mandataire des pouvoirs spéciaux pour accomplir des actes juridiques déterminés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'mandant', label: "Mandant", type: 'text', required: true },
      { key: 'mandataire', label: "Mandataire", type: 'text', required: true },
      { key: 'objet_mandat', label: "Objet du mandat", type: 'textarea', required: true },
      { key: 'pouvoirs_conferes', label: "Pouvoirs conférés", type: 'textarea', required: true },
      { key: 'duree_mandat', label: "Durée du mandat", type: 'text', required: true },
      { key: 'remuneration_mandat', label: "Rémunération (FCFA)", type: 'number', required: false },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MANDAT SPÉCIAL</h1><p><strong>Mandant :</strong> {{mandant}}</p><p><strong>Mandataire :</strong> {{mandataire}}</p><p><strong>Objet :</strong><br/>{{objet_mandat}}</p><p><strong>Pouvoirs conférés :</strong><br/>{{pouvoirs_conferes}}</p><p><strong>Durée :</strong> {{duree_mandat}} — <strong>Rémunération :</strong> {{remuneration_mandat}} FCFA</p></div>`,
  },
  {
    code: 'jur3_pv_ag_extraordinaire',
    name: "Procès-Verbal AGE",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 54000,
    description: "Procès-verbal de l'Assemblée Générale Extraordinaire conforme aux exigences de l'Acte Uniforme OHADA sur les sociétés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'denomination_sociale', label: "Dénomination sociale", type: 'text', required: true },
      { key: 'capital_social', label: "Capital social (FCFA)", type: 'number', required: true },
      { key: 'date_age', label: "Date de l'AGE", type: 'date', required: true },
      { key: 'lieu_age', label: "Lieu de l'AGE", type: 'text', required: true },
      { key: 'president_age', label: "Président de séance", type: 'text', required: true },
      { key: 'resolutions', label: "Résolutions adoptées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÈS-VERBAL D'ASSEMBLÉE GÉNÉRALE EXTRAORDINAIRE</h1><p><strong>Société :</strong> {{denomination_sociale}} — Capital : {{capital_social}} FCFA</p><p><strong>Date :</strong> {{date_age}} — <strong>Lieu :</strong> {{lieu_age}}</p><p><strong>Président :</strong> {{president_age}}</p><hr/><p><strong>Résolutions adoptées :</strong><br/>{{resolutions}}</p><p>De tout ce que dessus, il a été dressé le présent procès-verbal signé par le Président de séance.</p></div>`,
  },
  {
    code: 'jur3_accord_garantie_autonome',
    name: "Accord de Garantie Autonome",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 60000,
    description: "Instrument de garantie indépendant du contrat de base, par lequel le garant s'engage à payer à première demande.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'donneur_garantie', label: "Donneur de garantie", type: 'text', required: true },
      { key: 'beneficiaire_garantie', label: "Bénéficiaire", type: 'text', required: true },
      { key: 'montant_garantie', label: "Montant garanti (FCFA)", type: 'number', required: true },
      { key: 'objet_garantie', label: "Objet de la garantie", type: 'text', required: true },
      { key: 'duree_garantie', label: "Durée de la garantie", type: 'text', required: true },
      { key: 'conditions_appel', label: "Conditions d'appel en garantie", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GARANTIE AUTONOME</h1><p><strong>Garant :</strong> {{donneur_garantie}}</p><p><strong>Bénéficiaire :</strong> {{beneficiaire_garantie}}</p><p><strong>Montant :</strong> {{montant_garantie}} FCFA — <strong>Objet :</strong> {{objet_garantie}}</p><p><strong>Durée :</strong> {{duree_garantie}}</p><p><strong>Conditions d'appel :</strong><br/>{{conditions_appel}}</p></div>`,
  },
  {
    code: 'jur3_lettre_change_ohada',
    name: "Lettre de Change OHADA",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Titre cambiaire réglementé par l'Acte Uniforme OHADA relatif aux effets de commerce.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'tireur', label: "Tireur", type: 'text', required: true },
      { key: 'tire', label: "Tiré", type: 'text', required: true },
      { key: 'beneficiaire_lc', label: "Bénéficiaire", type: 'text', required: true },
      { key: 'montant_lettre', label: "Montant (FCFA)", type: 'number', required: true },
      { key: 'echeance', label: "Échéance", type: 'date', required: true },
      { key: 'lieu_paiement', label: "Lieu de paiement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>LETTRE DE CHANGE</h1><p>Veuillez payer à l'ordre de <strong>{{beneficiaire_lc}}</strong> la somme de <strong>{{montant_lettre}} FCFA</strong>.</p><p><strong>Tireur :</strong> {{tireur}} — <strong>Tiré :</strong> {{tire}}</p><p><strong>Échéance :</strong> {{echeance}} — <strong>Lieu de paiement :</strong> {{lieu_paiement}}</p><p><em>Conforme à l'Acte Uniforme OHADA relatif aux effets de commerce.</em></p></div>`,
  },
  {
    code: 'jur3_billet_ordre',
    name: "Billet à Ordre",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Titre cambiaire par lequel le souscripteur s'engage à payer une somme déterminée à l'ordre du bénéficiaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'souscripteur', label: "Souscripteur", type: 'text', required: true },
      { key: 'beneficiaire_bo', label: "Bénéficiaire", type: 'text', required: true },
      { key: 'montant_bo', label: "Montant (FCFA)", type: 'number', required: true },
      { key: 'echeance_bo', label: "Échéance", type: 'date', required: true },
      { key: 'lieu_paiement_bo', label: "Lieu de paiement", type: 'text', required: true },
      { key: 'date_emission_bo', label: "Date d'émission", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>BILLET À ORDRE</h1><p>Je soussigné(e), <strong>{{souscripteur}}</strong>, m'engage à payer à l'ordre de <strong>{{beneficiaire_bo}}</strong> la somme de <strong>{{montant_bo}} FCFA</strong>.</p><p><strong>Échéance :</strong> {{echeance_bo}} — <strong>Lieu :</strong> {{lieu_paiement_bo}}</p><p><strong>Émis le :</strong> {{date_emission_bo}}</p></div>`,
  },
  {
    code: 'jur3_aval_bancaire',
    name: "Aval Bancaire",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Engagement d'une banque de garantir le paiement d'un effet de commerce à l'échéance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'banque_avaliste', label: "Banque avaliste", type: 'text', required: true },
      { key: 'avale', label: "Avalé (personne cautionnée)", type: 'text', required: true },
      { key: 'effet_concerne', label: "Effet de commerce concerné", type: 'text', required: true },
      { key: 'montant_aval', label: "Montant avalisé (FCFA)", type: 'number', required: true },
      { key: 'echeance_aval', label: "Échéance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>AVAL BANCAIRE</h1><p><strong>Banque avaliste :</strong> {{banque_avaliste}}</p><p>Bon pour aval de <strong>{{avale}}</strong> sur l'effet : {{effet_concerne}}</p><p><strong>Montant avalisé :</strong> {{montant_aval}} FCFA — <strong>Échéance :</strong> {{echeance_aval}}</p><p>La présente mention d'aval rend la banque garante solidaire du paiement à l'échéance.</p></div>`,
  },
  {
    code: 'jur3_assignation_paiement',
    name: "Assignation en Paiement",
    category: 'juridique_admin',
    price: 25000,
    priceMax: 75000,
    description: "Acte juridique par lequel un créancier cite son débiteur devant une juridiction compétente pour obtenir le paiement d'une créance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'creancier', label: "Créancier demandeur", type: 'text', required: true },
      { key: 'debiteur', label: "Débiteur défendeur", type: 'text', required: true },
      { key: 'montant_creance', label: "Montant de la créance (FCFA)", type: 'number', required: true },
      { key: 'origine_creance', label: "Origine de la créance", type: 'textarea', required: true },
      { key: 'juridiction', label: "Juridiction compétente", type: 'text', required: true },
      { key: 'date_audience', label: "Date d'audience", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ASSIGNATION EN PAIEMENT</h1><p>À la requête de <strong>{{creancier}}</strong>,</p><p>Il est fait assignation à <strong>{{debiteur}}</strong> à comparaître devant <strong>{{juridiction}}</strong> le <strong>{{date_audience}}</strong>.</p><p><strong>Montant réclamé :</strong> {{montant_creance}} FCFA</p><p><strong>Origine :</strong><br/>{{origine_creance}}</p></div>`,
  },
  {
    code: 'jur3_mainlevee_saisie',
    name: "Acte de Mainlevée de Saisie",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Acte par lequel un créancier donne mainlevée d'une mesure de saisie pratiquée sur les biens d'un débiteur.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'creancier_mainlevee', label: "Créancier", type: 'text', required: true },
      { key: 'debiteur_mainlevee', label: "Débiteur", type: 'text', required: true },
      { key: 'type_saisie', label: "Type de saisie levée", type: 'text', required: true },
      { key: 'reference_saisie', label: "Référence de l'acte de saisie", type: 'text', required: true },
      { key: 'motif_mainlevee', label: "Motif de la mainlevée", type: 'textarea', required: true },
      { key: 'date_mainlevee', label: "Date de la mainlevée", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE MAINLEVÉE DE SAISIE</h1><p><strong>Créancier :</strong> {{creancier_mainlevee}}</p><p><strong>Débiteur :</strong> {{debiteur_mainlevee}}</p><p><strong>Saisie levée :</strong> {{type_saisie}} — <strong>Réf. :</strong> {{reference_saisie}}</p><p><strong>Motif :</strong><br/>{{motif_mainlevee}}</p><p>Le créancier donne bonne et valable mainlevée de la saisie susvisée à la date du : <strong>{{date_mainlevee}}</strong>.</p></div>`,
  },
  {
    code: 'jur3_declaration_creances_ohada',
    name: "Déclaration de Créances OHADA",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Déclaration formelle de créances dans le cadre d'une procédure collective OHADA (redressement ou liquidation).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'creancier_declarant', label: "Créancier déclarant", type: 'text', required: true },
      { key: 'entreprise_procedure', label: "Entreprise en procédure collective", type: 'text', required: true },
      { key: 'montant_creance_dc', label: "Montant de la créance (FCFA)", type: 'number', required: true },
      { key: 'nature_creance', label: "Nature de la créance", type: 'text', required: true },
      { key: 'pieces_justificatives', label: "Pièces justificatives jointes", type: 'textarea', required: true },
      { key: 'syndic', label: "Syndic / Administrateur", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>DÉCLARATION DE CRÉANCES OHADA</h1><p>Le créancier <strong>{{creancier_declarant}}</strong> déclare auprès du syndic <strong>{{syndic}}</strong> une créance sur <strong>{{entreprise_procedure}}</strong>.</p><p><strong>Montant :</strong> {{montant_creance_dc}} FCFA — <strong>Nature :</strong> {{nature_creance}}</p><p><strong>Pièces jointes :</strong><br/>{{pieces_justificatives}}</p></div>`,
  },
  {
    code: 'jur3_accord_transactionnel',
    name: "Accord Transactionnel",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 60000,
    description: "Convention par laquelle des parties mettent fin à un litige existant ou préviennent un litige à naître par des concessions réciproques.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'partie_a', label: "Partie A", type: 'text', required: true },
      { key: 'partie_b', label: "Partie B", type: 'text', required: true },
      { key: 'litige_objet', label: "Objet du litige", type: 'textarea', required: true },
      { key: 'concessions_a', label: "Concessions de la Partie A", type: 'textarea', required: true },
      { key: 'concessions_b', label: "Concessions de la Partie B", type: 'textarea', required: true },
      { key: 'montant_transaction', label: "Indemnité transactionnelle (FCFA)", type: 'number', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD TRANSACTIONNEL</h1><p>Entre <strong>{{partie_a}}</strong> et <strong>{{partie_b}}</strong>.</p><p><strong>Litige :</strong><br/>{{litige_objet}}</p><p><strong>Concessions A :</strong><br/>{{concessions_a}}</p><p><strong>Concessions B :</strong><br/>{{concessions_b}}</p><p><strong>Indemnité :</strong> {{montant_transaction}} FCFA</p><p>Les parties s'interdisent toute action judiciaire ultérieure relative au présent litige.</p></div>`,
  },
  {
    code: 'jur3_pacte_preference',
    name: "Pacte de Préférence",
    category: 'juridique_admin',
    price: 14000,
    priceMax: 42000,
    description: "Contrat par lequel une personne s'engage à offrir à une autre personne la priorité d'acquisition d'un bien en cas de cession.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'promettant', label: "Promettant (propriétaire)", type: 'text', required: true },
      { key: 'beneficiaire_pacte', label: "Bénéficiaire du pacte", type: 'text', required: true },
      { key: 'bien_concerne', label: "Bien concerné", type: 'text', required: true },
      { key: 'duree_pacte', label: "Durée du pacte", type: 'text', required: true },
      { key: 'conditions_exercice', label: "Conditions d'exercice du droit", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PACTE DE PRÉFÉRENCE</h1><p><strong>Promettant :</strong> {{promettant}}</p><p><strong>Bénéficiaire :</strong> {{beneficiaire_pacte}}</p><p><strong>Bien :</strong> {{bien_concerne}} — <strong>Durée :</strong> {{duree_pacte}}</p><p>En cas de cession du bien, le promettant s'engage à offrir prioritairement au bénéficiaire la possibilité de l'acquérir.</p><p><strong>Conditions :</strong><br/>{{conditions_exercice}}</p></div>`,
  },
  {
    code: 'jur3_accord_substitution',
    name: "Accord de Substitution",
    category: 'juridique_admin',
    price: 11000,
    priceMax: 33000,
    description: "Accord par lequel une partie se substitue à une autre dans ses droits et obligations contractuels.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'cedant_subst', label: "Partie cédante", type: 'text', required: true },
      { key: 'substitut', label: "Partie substituée", type: 'text', required: true },
      { key: 'cocontractant', label: "Cocontractant", type: 'text', required: true },
      { key: 'contrat_initial', label: "Contrat initial (réf.)", type: 'text', required: true },
      { key: 'droits_obligations', label: "Droits et obligations transférés", type: 'textarea', required: true },
      { key: 'date_effet_subst', label: "Date d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SUBSTITUTION</h1><p><strong>Cédant :</strong> {{cedant_subst}} — <strong>Substitut :</strong> {{substitut}}</p><p><strong>Cocontractant :</strong> {{cocontractant}}</p><p><strong>Contrat initial :</strong> {{contrat_initial}} — <strong>Effet au :</strong> {{date_effet_subst}}</p><p><strong>Droits et obligations transférés :</strong><br/>{{droits_obligations}}</p></div>`,
  },
  {
    code: 'jur3_contrat_fiducie',
    name: "Contrat de Fiducie Simplifié",
    category: 'juridique_admin',
    price: 22000,
    priceMax: 66000,
    description: "Contrat simplifié de fiducie par lequel le constituant transfère des biens au fiduciaire dans un but déterminé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'constituant', label: "Constituant", type: 'text', required: true },
      { key: 'fiduciaire', label: "Fiduciaire", type: 'text', required: true },
      { key: 'beneficiaire_fiducie', label: "Bénéficiaire", type: 'text', required: true },
      { key: 'biens_transferes', label: "Biens transférés", type: 'textarea', required: true },
      { key: 'mission_fiduciaire', label: "Mission du fiduciaire", type: 'textarea', required: true },
      { key: 'duree_fiducie', label: "Durée de la fiducie", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE FIDUCIE SIMPLIFIÉ</h1><p><strong>Constituant :</strong> {{constituant}} — <strong>Fiduciaire :</strong> {{fiduciaire}}</p><p><strong>Bénéficiaire :</strong> {{beneficiaire_fiducie}} — <strong>Durée :</strong> {{duree_fiducie}}</p><p><strong>Biens transférés :</strong><br/>{{biens_transferes}}</p><p><strong>Mission :</strong><br/>{{mission_fiduciaire}}</p></div>`,
  },
  {
    code: 'jur3_garantie_premiere_demande',
    name: "Garantie à Première Demande Bancaire",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 54000,
    description: "Garantie bancaire autonome par laquelle la banque s'engage à payer à première demande du bénéficiaire sans condition.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'banque_garante', label: "Banque garante", type: 'text', required: true },
      { key: 'donneur_ordre', label: "Donneur d'ordre", type: 'text', required: true },
      { key: 'beneficiaire_gpd', label: "Bénéficiaire", type: 'text', required: true },
      { key: 'montant_gpd', label: "Montant garanti (FCFA)", type: 'number', required: true },
      { key: 'contrat_garanti', label: "Contrat garanti", type: 'text', required: true },
      { key: 'validite_gpd', label: "Validité de la garantie", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>GARANTIE À PREMIÈRE DEMANDE BANCAIRE</h1><p><strong>Banque :</strong> {{banque_garante}}</p><p><strong>Donneur d'ordre :</strong> {{donneur_ordre}} — <strong>Bénéficiaire :</strong> {{beneficiaire_gpd}}</p><p><strong>Montant :</strong> {{montant_gpd}} FCFA — <strong>Contrat :</strong> {{contrat_garanti}}</p><p><strong>Validité :</strong> {{validite_gpd}}</p><p>La banque s'engage irrévocablement à payer le montant garanti à la première demande du bénéficiaire, sans pouvoir opposer aucune exception tirée du contrat de base.</p></div>`,
  },
  {
    code: 'jur3_acte_reconnaissance_droit',
    name: "Acte de Reconnaissance de Droit",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Acte par lequel une partie reconnaît formellement l'existence d'un droit détenu par une autre partie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'partie_reconnaissante', label: "Partie reconnaissante", type: 'text', required: true },
      { key: 'titulaire_droit', label: "Titulaire du droit", type: 'text', required: true },
      { key: 'droit_reconnu', label: "Droit reconnu", type: 'textarea', required: true },
      { key: 'fondement_juridique', label: "Fondement juridique", type: 'text', required: true },
      { key: 'date_reconnaissance', label: "Date de la reconnaissance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE RECONNAISSANCE DE DROIT</h1><p>Je soussigné(e), <strong>{{partie_reconnaissante}}</strong>, reconnais expressément que <strong>{{titulaire_droit}}</strong> est titulaire du droit suivant :</p><p>{{droit_reconnu}}</p><p><strong>Fondement :</strong> {{fondement_juridique}}</p><p><strong>Fait le :</strong> {{date_reconnaissance}}</p></div>`,
  },
  {
    code: 'jur3_protocole_separation_amiable',
    name: "Protocole de Séparation Amiable",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 60000,
    description: "Protocole organisant la séparation amiable de deux parties associées, avec répartition des droits et obligations.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'partie_a_sep', label: "Partie A", type: 'text', required: true },
      { key: 'partie_b_sep', label: "Partie B", type: 'text', required: true },
      { key: 'contexte_separation', label: "Contexte de la séparation", type: 'textarea', required: true },
      { key: 'repartition_actifs', label: "Répartition des actifs", type: 'textarea', required: true },
      { key: 'repartition_passifs', label: "Répartition des passifs", type: 'textarea', required: true },
      { key: 'date_effet_sep', label: "Date d'effet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PROTOCOLE DE SÉPARATION AMIABLE</h1><p>Entre <strong>{{partie_a_sep}}</strong> et <strong>{{partie_b_sep}}</strong>.</p><p><strong>Contexte :</strong><br/>{{contexte_separation}}</p><p><strong>Actifs :</strong><br/>{{repartition_actifs}}</p><p><strong>Passifs :</strong><br/>{{repartition_passifs}}</p><p><strong>Date d'effet :</strong> {{date_effet_sep}}</p></div>`,
  },
  {
    code: 'jur3_accord_reglement_amiable',
    name: "Accord de Règlement à l'Amiable",
    category: 'juridique_admin',
    price: 15000,
    priceMax: 45000,
    description: "Accord définissant les modalités de règlement amiable d'un différend entre les parties sans recours judiciaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'partie_1_ra', label: "Partie 1", type: 'text', required: true },
      { key: 'partie_2_ra', label: "Partie 2", type: 'text', required: true },
      { key: 'differend', label: "Nature du différend", type: 'textarea', required: true },
      { key: 'modalites_reglement', label: "Modalités de règlement", type: 'textarea', required: true },
      { key: 'montant_reglement', label: "Montant du règlement (FCFA)", type: 'number', required: false },
      { key: 'echeancier', label: "Échéancier de paiement", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÈGLEMENT À L'AMIABLE</h1><p>Entre <strong>{{partie_1_ra}}</strong> et <strong>{{partie_2_ra}}</strong>.</p><p><strong>Différend :</strong><br/>{{differend}}</p><p><strong>Modalités :</strong><br/>{{modalites_reglement}}</p><p><strong>Montant :</strong> {{montant_reglement}} FCFA</p><p><strong>Échéancier :</strong><br/>{{echeancier}}</p></div>`,
  },
  {
    code: 'jur3_contrat_licence_brevet',
    name: "Contrat de Licence de Brevet",
    category: 'juridique_admin',
    price: 25000,
    priceMax: 75000,
    description: "Contrat par lequel le titulaire d'un brevet accorde à un tiers le droit d'exploiter son invention.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'titulaire_brevet', label: "Titulaire du brevet", type: 'text', required: true },
      { key: 'licencie', label: "Licencié", type: 'text', required: true },
      { key: 'reference_brevet', label: "Référence du brevet", type: 'text', required: true },
      { key: 'objet_brevet', label: "Objet du brevet", type: 'text', required: true },
      { key: 'territoire', label: "Territoire d'exploitation", type: 'text', required: true },
      { key: 'redevances', label: "Redevances (FCFA)", type: 'number', required: true },
      { key: 'duree_licence', label: "Durée de la licence", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE LICENCE DE BREVET</h1><p><strong>Titulaire :</strong> {{titulaire_brevet}} — <strong>Licencié :</strong> {{licencie}}</p><p><strong>Brevet :</strong> {{reference_brevet}} — {{objet_brevet}}</p><p><strong>Territoire :</strong> {{territoire}} — <strong>Durée :</strong> {{duree_licence}}</p><p><strong>Redevances :</strong> {{redevances}} FCFA</p></div>`,
  },
  {
    code: 'jur3_partage_brevets',
    name: "Convention de Partage de Brevets",
    category: 'juridique_admin',
    price: 22000,
    priceMax: 66000,
    description: "Convention organisant le partage croisé de droits de brevet entre plusieurs titulaires.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'titulaire_1', label: "Titulaire 1", type: 'text', required: true },
      { key: 'titulaire_2', label: "Titulaire 2", type: 'text', required: true },
      { key: 'brevets_portefeuille', label: "Brevets du portefeuille commun", type: 'textarea', required: true },
      { key: 'conditions_partage', label: "Conditions de partage", type: 'textarea', required: true },
      { key: 'duree_convention', label: "Durée de la convention", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE PARTAGE DE BREVETS</h1><p>Entre <strong>{{titulaire_1}}</strong> et <strong>{{titulaire_2}}</strong>.</p><p><strong>Brevets :</strong><br/>{{brevets_portefeuille}}</p><p><strong>Conditions :</strong><br/>{{conditions_partage}}</p><p><strong>Durée :</strong> {{duree_convention}}</p></div>`,
  },
  {
    code: 'jur3_cession_clientele',
    name: "Accord de Cession de Clientèle",
    category: 'juridique_admin',
    price: 18000,
    priceMax: 54000,
    description: "Acte de cession d'un fichier clientèle avec garanties de non-détournement et obligations du cessionnaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'cedant_clientele', label: "Cédant", type: 'text', required: true },
      { key: 'cessionnaire_clientele', label: "Cessionnaire", type: 'text', required: true },
      { key: 'description_clientele', label: "Description de la clientèle cédée", type: 'textarea', required: true },
      { key: 'prix_cession_clientele', label: "Prix de cession (FCFA)", type: 'number', required: true },
      { key: 'clause_non_detournement', label: "Clause de non-détournement", type: 'textarea', required: true },
      { key: 'duree_garantie_clientele', label: "Durée de garantie", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CESSION DE CLIENTÈLE</h1><p><strong>Cédant :</strong> {{cedant_clientele}} — <strong>Cessionnaire :</strong> {{cessionnaire_clientele}}</p><p><strong>Clientèle :</strong><br/>{{description_clientele}}</p><p><strong>Prix :</strong> {{prix_cession_clientele}} FCFA — <strong>Garantie :</strong> {{duree_garantie_clientele}}</p><p><strong>Non-détournement :</strong><br/>{{clause_non_detournement}}</p></div>`,
  },
  {
    code: 'jur3_nantissement_fonds_commerce',
    name: "Acte de Nantissement de Fonds de Commerce",
    category: 'juridique_admin',
    price: 20000,
    priceMax: 60000,
    description: "Acte constitutif de nantissement portant sur un fonds de commerce comme garantie d'une créance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'debiteur_nantissement', label: "Débiteur constituant", type: 'text', required: true },
      { key: 'creancier_nantissement', label: "Créancier bénéficiaire", type: 'text', required: true },
      { key: 'fonds_designe', label: "Fonds de commerce désigné", type: 'text', required: true },
      { key: 'creance_garantie', label: "Créance garantie (FCFA)", type: 'number', required: true },
      { key: 'elements_nantis', label: "Éléments nantis du fonds", type: 'textarea', required: true },
      { key: 'inscription_rccm', label: "N° inscription RCCM", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACTE DE NANTISSEMENT DE FONDS DE COMMERCE</h1><p><strong>Débiteur :</strong> {{debiteur_nantissement}} — <strong>Créancier :</strong> {{creancier_nantissement}}</p><p><strong>Fonds :</strong> {{fonds_designe}} — <strong>RCCM :</strong> {{inscription_rccm}}</p><p><strong>Créance garantie :</strong> {{creance_garantie}} FCFA</p><p><strong>Éléments nantis :</strong><br/>{{elements_nantis}}</p></div>`,
  },
  {
    code: 'jur3_hypotheque_conventionnelle',
    name: "Hypothèque Conventionnelle",
    category: 'juridique_admin',
    price: 25000,
    priceMax: 75000,
    description: "Acte constitutif d'hypothèque conventionnelle sur un immeuble en garantie d'une obligation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'constituant_hyp', label: "Constituant de l'hypothèque", type: 'text', required: true },
      { key: 'beneficiaire_hyp', label: "Créancier hypothécaire", type: 'text', required: true },
      { key: 'immeuble', label: "Immeuble hypothéqué", type: 'textarea', required: true },
      { key: 'montant_garanti_hyp', label: "Montant garanti (FCFA)", type: 'number', required: true },
      { key: 'taux_interet', label: "Taux d'intérêt (%)", type: 'number', required: false },
      { key: 'duree_hypotheque', label: "Durée", type: 'text', required: true },
      { key: 'titre_foncier', label: "Titre foncier n°", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>HYPOTHÈQUE CONVENTIONNELLE</h1><p><strong>Constituant :</strong> {{constituant_hyp}} — <strong>Bénéficiaire :</strong> {{beneficiaire_hyp}}</p><p><strong>Immeuble :</strong><br/>{{immeuble}}</p><p><strong>Titre foncier :</strong> {{titre_foncier}}</p><p><strong>Montant garanti :</strong> {{montant_garanti_hyp}} FCFA — <strong>Taux :</strong> {{taux_interet}}% — <strong>Durée :</strong> {{duree_hypotheque}}</p></div>`,
  },
  {
    code: 'jur3_cautionnement_reel',
    name: "Cautionnement Réel",
    category: 'juridique_admin',
    price: 16000,
    priceMax: 48000,
    description: "Acte de cautionnement par lequel une caution affecte un de ses biens en garantie de la dette d'autrui.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'caution_reelle', label: "Caution réelle", type: 'text', required: true },
      { key: 'debiteur_principal', label: "Débiteur principal", type: 'text', required: true },
      { key: 'creancier_caution', label: "Créancier", type: 'text', required: true },
      { key: 'bien_affecte', label: "Bien affecté en garantie", type: 'textarea', required: true },
      { key: 'montant_dette', label: "Montant de la dette garantie (FCFA)", type: 'number', required: true },
      { key: 'limites_engagement', label: "Limites de l'engagement", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CAUTIONNEMENT RÉEL</h1><p><strong>Caution :</strong> {{caution_reelle}} — <strong>Débiteur :</strong> {{debiteur_principal}}</p><p><strong>Créancier :</strong> {{creancier_caution}}</p><p><strong>Bien affecté :</strong><br/>{{bien_affecte}}</p><p><strong>Dette garantie :</strong> {{montant_dette}} FCFA</p><p><strong>Limites :</strong><br/>{{limites_engagement}}</p></div>`,
  },
  {
    code: 'jur3_acte_subrogation',
    name: "Acte de Subrogation",
    category: 'juridique_admin',
    price: 14000,
    priceMax: 42000,
    description: "Acte par lequel un tiers qui paie la dette d'autrui est subrogé dans les droits du créancier initial.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'creancier_initial', label: "Créancier initial", type: 'text', required: true },
      { key: 'subrogateur', label: "Subrogateur (tiers payant)", type: 'text', required: true },
      { key: 'debiteur_subroge', label: "Débiteur", type: 'text', required: true },
      { key: 'montant_paye', label: "Montant payé (FCFA)", type: 'number', required: true },
      { key: 'droits_transferes', label: "Droits transférés au subrogé", type: 'textarea', required: true },
      { key: 'date_subrogation', label: "Date de subrogation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACTE DE SUBROGATION</h1><p>Le créancier <strong>{{creancier_initial}}</strong> subroge <strong>{{subrogateur}}</strong> dans tous ses droits contre <strong>{{debiteur_subroge}}</strong>.</p><p><strong>Montant payé :</strong> {{montant_paye}} FCFA — <strong>Date :</strong> {{date_subrogation}}</p><p><strong>Droits transférés :</strong><br/>{{droits_transferes}}</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 06a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
