import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── 25 templates Identité numérique / eGov ───────────────────────────────
  {
    code: 'digit_cni_biometrique_ci',
    name: "Accord de service d'identite numerique nationale (CNI biometrique CI)",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Accord encadrant la fourniture du service de carte nationale d'identite biometrique en Cote d'Ivoire selon les normes ARTCI et ONECI.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'nom_complet', label: "Nom et prenoms du titulaire", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'lieu_naissance', label: "Lieu de naissance", type: 'text', required: true },
      { key: 'numero_dossier', label: "Numero de dossier ONECI", type: 'text', required: true },
      { key: 'date_emission', label: "Date d'emission", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'IDENTITE NUMERIQUE NATIONALE</h1><h2>Carte Nationale d'Identite Biometrique — Republique de Cote d'Ivoire</h2><p>Entre l'Office National de l'Etat Civil et de l'Identification (ONECI) et le titulaire ci-apres designe.</p><p><strong>Titulaire :</strong> {{nom_complet}}</p><p><strong>Date de naissance :</strong> {{date_naissance}}</p><p><strong>Lieu de naissance :</strong> {{lieu_naissance}}</p><p><strong>Numero de dossier :</strong> {{numero_dossier}}</p><p><strong>Date d'emission :</strong> {{date_emission}}</p><p>Le present accord definit les conditions d'utilisation, de conservation et de protection des donnees biometriques collectees dans le cadre de l'emission de la CNI biometrique conformement a la loi n°2013-451 relative a la protection des donnees a caractere personnel.</p></div>`,
  },
  {
    code: 'digit_signature_electronique_artci',
    name: "Accord de service de signature electronique qualifiee (ARTCI CI)",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Accord de fourniture de certificat de signature electronique qualifiee delivre par un prestataire agree par l'ARTCI en Cote d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'titulaire_certificat', label: "Titulaire du certificat", type: 'text', required: true },
      { key: 'organisme', label: "Organisme / Entreprise", type: 'text', required: true },
      { key: 'date_emission', label: "Date d'emission du certificat", type: 'date', required: true },
      { key: 'date_expiration', label: "Date d'expiration", type: 'date', required: true },
      { key: 'numero_certificat', label: "Numero de certificat", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SIGNATURE ELECTRONIQUE QUALIFIEE</h1><h2>Autorite de Regulation des Telecommunications / TIC de Cote d'Ivoire — ARTCI</h2><p><strong>Titulaire du certificat :</strong> {{titulaire_certificat}}</p><p><strong>Organisme :</strong> {{organisme}}</p><p><strong>Date d'emission :</strong> {{date_emission}}</p><p><strong>Date d'expiration :</strong> {{date_expiration}}</p><p><strong>Numero de certificat :</strong> {{numero_certificat}}</p><p>La signature electronique qualifiee produite a l'aide du present certificat a la meme valeur juridique qu'une signature manuscrite conformement a la loi n°2017-675 sur les transactions electroniques.</p></div>`,
  },
  {
    code: 'digit_coffre_fort_numerique',
    name: "Accord de service de coffre-fort numerique de documents d'identite",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Accord encadrant l'hebergement securise de documents officiels numeriques dans un coffre-fort electronique certifie.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'nom_utilisateur', label: "Nom de l'utilisateur", type: 'text', required: true },
      { key: 'email', label: "Adresse email", type: 'text', required: true },
      { key: 'date_souscription', label: "Date de souscription", type: 'date', required: true },
      { key: 'type_abonnement', label: "Type d'abonnement (Individuel/Entreprise)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE COFFRE-FORT NUMERIQUE</h1><h2>Conservation securisee de documents d'identite officiels</h2><p><strong>Utilisateur :</strong> {{nom_utilisateur}}</p><p><strong>Email :</strong> {{email}}</p><p><strong>Date de souscription :</strong> {{date_souscription}}</p><p><strong>Abonnement :</strong> {{type_abonnement}}</p><p>Le present accord garantit la conservation integre, confidentielle et disponible des documents numeriques deposes, conformement aux normes ISO 27001 et aux exigences de l'ARTCI.</p></div>`,
  },
  {
    code: 'digit_ekyc_verification_identite',
    name: "Accord de service de verification d'identite en ligne (eKYC)",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Accord de service Know Your Customer electronique pour la verification d'identite des utilisateurs en ligne dans l'espace UEMOA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'prestataire', label: "Prestataire eKYC", type: 'text', required: true },
      { key: 'client', label: "Entite cliente", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'niveau_verification', label: "Niveau de verification (Basique/Avance)", type: 'text', required: true },
      { key: 'volume_mensuel', label: "Volume mensuel de verifications estimees", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE VERIFICATION D'IDENTITE EN LIGNE (eKYC)</h1><p><strong>Prestataire :</strong> {{prestataire}}</p><p><strong>Client :</strong> {{client}}</p><p><strong>Date :</strong> {{date_accord}}</p><p><strong>Niveau de verification :</strong> {{niveau_verification}}</p><p><strong>Volume mensuel estime :</strong> {{volume_mensuel}}</p><p>Le present accord encadre la verification electronique de l'identite des utilisateurs finaux conformement aux directives de la BCEAO sur la lutte contre le blanchiment d'argent et le financement du terrorisme (LCB-FT).</p></div>`,
  },
  {
    code: 'digit_reconnaissance_faciale_biometrique',
    name: "Accord de service de reconnaissance faciale biometrique",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Accord encadrant le deploiement et l'utilisation d'un systeme de reconnaissance faciale biometrique pour des services publics ou prives.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'fournisseur_solution', label: "Fournisseur de la solution", type: 'text', required: true },
      { key: 'entite_deploiement', label: "Entite de deploiement", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut du service", type: 'date', required: true },
      { key: 'perimetre_utilisation', label: "Perimetre d'utilisation", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE RECONNAISSANCE FACIALE BIOMETRIQUE</h1><p><strong>Fournisseur de la solution :</strong> {{fournisseur_solution}}</p><p><strong>Entite de deploiement :</strong> {{entite_deploiement}}</p><p><strong>Date de debut :</strong> {{date_debut}}</p><p><strong>Perimetre d'utilisation :</strong> {{perimetre_utilisation}}</p><p>Les parties s'engagent au respect strict de la loi n°2013-451 sur la protection des donnees personnelles et aux recommandations de l'Autorite de Protection des Donnees a Caractere Personnel (APDP).</p></div>`,
  },
  {
    code: 'digit_production_cni',
    name: "Accord de service de Carte Nationale d'Identite (production)",
    category: 'juridique_admin',
    price: 7500,
    priceMax: 22500,
    description: "Accord de sous-traitance ou de partenariat pour la production industrielle de cartes nationales d'identite biometriques.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'contractant', label: "Entreprise contractante", type: 'text', required: true },
      { key: 'volume_cartes', label: "Volume de cartes a produire", type: 'text', required: true },
      { key: 'date_debut_production', label: "Date de debut de production", type: 'date', required: true },
      { key: 'specifications_techniques', label: "Specifications techniques (resume)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PRODUCTION DE CARTE NATIONALE D'IDENTITE</h1><p><strong>Entreprise contractante :</strong> {{contractant}}</p><p><strong>Volume de production :</strong> {{volume_cartes}}</p><p><strong>Date de debut :</strong> {{date_debut_production}}</p><p><strong>Specifications techniques :</strong> {{specifications_techniques}}</p><p>La production devra respecter les normes ICAO 9303 et les specifications securitaires definies par le Ministere de l'Interieur de la Republique de Cote d'Ivoire.</p></div>`,
  },
  {
    code: 'digit_passeport_biometrique',
    name: "Accord de service de passeport biometrique",
    category: 'juridique_admin',
    price: 8500,
    priceMax: 25500,
    description: "Accord de service relatif a la production, personnalisation et delivrance de passeports biometriques conformes aux normes ICAO.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'titulaire', label: "Nom complet du titulaire", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'numero_passeport', label: "Numero de passeport", type: 'text', required: true },
      { key: 'date_delivrance', label: "Date de delivrance", type: 'date', required: true },
      { key: 'date_expiration', label: "Date d'expiration", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PASSEPORT BIOMETRIQUE</h1><h2>Republique de Cote d'Ivoire — Direction Generale de la Police Nationale</h2><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Date de naissance :</strong> {{date_naissance}}</p><p><strong>Numero de passeport :</strong> {{numero_passeport}}</p><p><strong>Date de delivrance :</strong> {{date_delivrance}}</p><p><strong>Date d'expiration :</strong> {{date_expiration}}</p><p>Le passeport biometrique est delivre conformement aux normes ICAO 9303 et integre une puce electronique contenant les donnees biometriques du titulaire.</p></div>`,
  },
  {
    code: 'digit_permis_conduire_biometrique',
    name: "Accord de service de permis de conduire biometrique",
    category: 'juridique_admin',
    price: 6500,
    priceMax: 19500,
    description: "Accord de service pour la delivrance du permis de conduire biometrique selon les normes de l'UEMOA et de la CEDEAO.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'titulaire', label: "Nom complet du conducteur", type: 'text', required: true },
      { key: 'categorie_permis', label: "Categorie(s) de permis", type: 'text', required: true },
      { key: 'date_obtention', label: "Date d'obtention", type: 'date', required: true },
      { key: 'numero_permis', label: "Numero du permis", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PERMIS DE CONDUIRE BIOMETRIQUE</h1><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Categorie(s) :</strong> {{categorie_permis}}</p><p><strong>Date d'obtention :</strong> {{date_obtention}}</p><p><strong>Numero :</strong> {{numero_permis}}</p><p>Le present permis est conforme aux directives de la CEDEAO sur l'harmonisation des permis de conduire en Afrique de l'Ouest et integre un composant electronique securise.</p></div>`,
  },
  {
    code: 'digit_carte_sante_biometrique',
    name: "Accord de service de carte de sante biometrique",
    category: 'juridique_admin',
    price: 5500,
    priceMax: 16500,
    description: "Accord de service pour la delivrance et la gestion de la carte de sante biometrique nationale permettant l'acces aux soins.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'beneficiaire', label: "Nom du beneficiaire", type: 'text', required: true },
      { key: 'numero_carte', label: "Numero de carte de sante", type: 'text', required: true },
      { key: 'date_emission', label: "Date d'emission", type: 'date', required: true },
      { key: 'regime_couverture', label: "Regime de couverture (CNAM, CMU, autre)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CARTE DE SANTE BIOMETRIQUE</h1><p><strong>Beneficiaire :</strong> {{beneficiaire}}</p><p><strong>Numero de carte :</strong> {{numero_carte}}</p><p><strong>Date d'emission :</strong> {{date_emission}}</p><p><strong>Regime de couverture :</strong> {{regime_couverture}}</p><p>La carte de sante biometrique permet l'identification securisee du patient et l'acces aux soins dans les etablissements agrees. Elle est liee au registre national de sante sous la supervision du Ministere de la Sante et de l'Hygiene Publique.</p></div>`,
  },
  {
    code: 'digit_etat_civil_naissance_numerique',
    name: "Accord de service d'enregistrement etat civil numerique (naissance)",
    category: 'juridique_admin',
    price: 5000,
    priceMax: 15000,
    description: "Accord de service pour la numerisation et la gestion electronique des actes de naissance dans le cadre de la reforme de l'etat civil.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'nom_enfant', label: "Nom et prenoms de l'enfant", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'lieu_naissance', label: "Lieu de naissance (commune)", type: 'text', required: true },
      { key: 'nom_pere', label: "Nom et prenoms du pere", type: 'text', required: true },
      { key: 'nom_mere', label: "Nom et prenoms de la mere", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — ENREGISTREMENT ETAT CIVIL NUMERIQUE</h1><h2>Acte de Naissance Numerique — Republique de Cote d'Ivoire</h2><p><strong>Enfant :</strong> {{nom_enfant}}</p><p><strong>Date de naissance :</strong> {{date_naissance}}</p><p><strong>Lieu de naissance :</strong> {{lieu_naissance}}</p><p><strong>Pere :</strong> {{nom_pere}}</p><p><strong>Mere :</strong> {{nom_mere}}</p><p>L'acte est enregistre dans le Registre National d'Etat Civil Numerique (RNECN) conformement aux dispositions de la loi sur l'etat civil et du decret d'application sur la numerisation des registres.</p></div>`,
  },
  {
    code: 'digit_egov_plateforme_ci',
    name: "Accord de service de plateforme d'administration en ligne (e-Gov CI)",
    category: 'juridique_admin',
    price: 9500,
    priceMax: 28500,
    description: "Accord de service pour l'acces et l'utilisation de la plateforme d'administration electronique unifiee de Cote d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'entite_abonnee', label: "Entite abonnee (ministere/collectivite)", type: 'text', required: true },
      { key: 'responsable_technique', label: "Responsable technique designe", type: 'text', required: true },
      { key: 'date_activation', label: "Date d'activation du service", type: 'date', required: true },
      { key: 'services_actives', label: "Services actives (liste)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PLATEFORME E-GOV COTE D'IVOIRE</h1><p><strong>Entite abonnee :</strong> {{entite_abonnee}}</p><p><strong>Responsable technique :</strong> {{responsable_technique}}</p><p><strong>Date d'activation :</strong> {{date_activation}}</p><p><strong>Services actives :</strong> {{services_actives}}</p><p>Le present accord est conclu dans le cadre de la Strategie Nationale d'Acceleration de la Transformation Numerique (SN@TN 2030) et engage les parties sur les niveaux de service, la securite des donnees et la continuite du service public numerique.</p></div>`,
  },
  {
    code: 'digit_teledeclaration_fiscale_dgi',
    name: "Accord de service de teledeclaration fiscale (DGI en ligne)",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Accord de service pour la teledeclaration et le telepaiement fiscaux via la plateforme en ligne de la Direction Generale des Impots de Cote d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'contribuable', label: "Nom / Raison sociale du contribuable", type: 'text', required: true },
      { key: 'numero_contribuable', label: "Numero de compte contribuable (NCC)", type: 'text', required: true },
      { key: 'regime_fiscal', label: "Regime fiscal", type: 'text', required: true },
      { key: 'date_adhesion', label: "Date d'adhesion au service en ligne", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TELEDECLARATION FISCALE</h1><h2>Direction Generale des Impots — Republique de Cote d'Ivoire</h2><p><strong>Contribuable :</strong> {{contribuable}}</p><p><strong>Numero contribuable :</strong> {{numero_contribuable}}</p><p><strong>Regime fiscal :</strong> {{regime_fiscal}}</p><p><strong>Date d'adhesion :</strong> {{date_adhesion}}</p><p>L'utilisation de la plateforme e-impots engage le contribuable au respect des echeances declaratives et du secret fiscal conformement au Code General des Impots de Cote d'Ivoire.</p></div>`,
  },
  {
    code: 'digit_ejustice_teleconsultation',
    name: "Accord de service de teleconsultation juridique (e-justice)",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Accord de service de teleconsultation juridique et d'acces aux services de justice en ligne dans le cadre de la modernisation judiciaire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'justiciable', label: "Nom du justiciable", type: 'text', required: true },
      { key: 'type_dossier', label: "Type de dossier juridique", type: 'text', required: true },
      { key: 'numero_dossier', label: "Numero de dossier judiciaire", type: 'text', required: false },
      { key: 'date_demande', label: "Date de la demande", type: 'date', required: true },
      { key: 'juridiction', label: "Juridiction concernee", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TELECONSULTATION JURIDIQUE (e-Justice)</h1><p><strong>Justiciable :</strong> {{justiciable}}</p><p><strong>Type de dossier :</strong> {{type_dossier}}</p><p><strong>Numero de dossier :</strong> {{numero_dossier}}</p><p><strong>Date de demande :</strong> {{date_demande}}</p><p><strong>Juridiction :</strong> {{juridiction}}</p><p>Le present accord encadre l'acces au service de justice electronique dans le respect du Code de Procedure Civile, Commerciale et Administrative (CPCCA) et des normes de securite informatique du Ministere de la Justice.</p></div>`,
  },
  {
    code: 'digit_teleservice_permis_construire',
    name: "Accord de service de teleservice permis de construire",
    category: 'juridique_admin',
    price: 7500,
    priceMax: 22500,
    description: "Accord de service pour la demande et le suivi en ligne du permis de construire via le guichet numerique de l'urbanisme.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'demandeur', label: "Nom du demandeur / Maitre d'ouvrage", type: 'text', required: true },
      { key: 'adresse_projet', label: "Adresse du projet de construction", type: 'text', required: true },
      { key: 'type_construction', label: "Type de construction", type: 'text', required: true },
      { key: 'date_depot', label: "Date de depot de la demande", type: 'date', required: true },
      { key: 'numero_demande', label: "Numero de demande en ligne", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — TELESERVICE PERMIS DE CONSTRUIRE</h1><p><strong>Demandeur :</strong> {{demandeur}}</p><p><strong>Adresse du projet :</strong> {{adresse_projet}}</p><p><strong>Type de construction :</strong> {{type_construction}}</p><p><strong>Date de depot :</strong> {{date_depot}}</p><p><strong>Numero de demande :</strong> {{numero_demande}}</p><p>La demande est traitee conformement au Code de la Construction et au Code de l'Urbanisme de Cote d'Ivoire. Le service en ligne permet le suivi en temps reel et la communication electronique avec les services instructeurs.</p></div>`,
  },
  {
    code: 'digit_cepici_guichet_unique',
    name: "Accord de service de guichet unique numerique entreprises (CEPICI)",
    category: 'juridique_admin',
    price: 8500,
    priceMax: 25500,
    description: "Accord de service pour la creation et la gestion electronique d'entreprises via le guichet unique numerique du CEPICI.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'forme_juridique', label: "Forme juridique (SARL, SA, SAS...)", type: 'text', required: true },
      { key: 'promoteur', label: "Nom du promoteur principal", type: 'text', required: true },
      { key: 'date_creation', label: "Date de creation souhaitee", type: 'date', required: true },
      { key: 'capital_social', label: "Capital social (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — GUICHET UNIQUE NUMERIQUE CEPICI</h1><h2>Centre de Promotion des Investissements en Cote d'Ivoire</h2><p><strong>Raison sociale :</strong> {{raison_sociale}}</p><p><strong>Forme juridique :</strong> {{forme_juridique}}</p><p><strong>Promoteur :</strong> {{promoteur}}</p><p><strong>Date de creation :</strong> {{date_creation}}</p><p><strong>Capital social :</strong> {{capital_social}} FCFA</p><p>La creation d'entreprise via le guichet unique numerique est realisee conformement a l'Acte Uniforme OHADA sur le droit des societes commerciales et des groupements d'interet economique (AUSCGIE).</p></div>`,
  },
  {
    code: 'digit_eprocurement_commande_publique',
    name: "Accord de service de plateforme de commande publique electronique (e-procurement)",
    category: 'juridique_admin',
    price: 11000,
    priceMax: 33000,
    description: "Accord de service pour l'acces et l'utilisation de la plateforme de commande publique electronique de Cote d'Ivoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'entite_contractante', label: "Entite contractante (acheteur public)", type: 'text', required: true },
      { key: 'attributaire', label: "Attributaire du marche", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marche", type: 'textarea', required: true },
      { key: 'date_notification', label: "Date de notification", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — COMMANDE PUBLIQUE ELECTRONIQUE (e-Procurement)</h1><p><strong>Entite contractante :</strong> {{entite_contractante}}</p><p><strong>Attributaire :</strong> {{attributaire}}</p><p><strong>Objet du marche :</strong> {{objet_marche}}</p><p><strong>Date de notification :</strong> {{date_notification}}</p><p>Le present accord est soumis au Code des Marches Publics de Cote d'Ivoire et aux directives de l'UEMOA sur la passation des marches. La plateforme e-procurement garantit la transparence, la tracabilite et l'accessibilite des procedures de passation.</p></div>`,
  },
  {
    code: 'digit_vote_electronique_securite',
    name: "Accord de service de vote electronique (securite)",
    category: 'juridique_admin',
    price: 14000,
    priceMax: 42000,
    description: "Accord de service encadrant le deploiement d'un systeme de vote electronique securise pour des elections ou consultations officielles.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'organisateur', label: "Organisme organisateur", type: 'text', required: true },
      { key: 'prestataire_systeme', label: "Prestataire du systeme de vote", type: 'text', required: true },
      { key: 'type_scrutin', label: "Type de scrutin / consultation", type: 'text', required: true },
      { key: 'date_vote', label: "Date du vote", type: 'date', required: true },
      { key: 'nombre_electeurs', label: "Nombre d'electeurs inscrits", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE VOTE ELECTRONIQUE SECURISE</h1><p><strong>Organisateur :</strong> {{organisateur}}</p><p><strong>Prestataire systeme :</strong> {{prestataire_systeme}}</p><p><strong>Type de scrutin :</strong> {{type_scrutin}}</p><p><strong>Date du vote :</strong> {{date_vote}}</p><p><strong>Nombre d'electeurs :</strong> {{nombre_electeurs}}</p><p>Le systeme de vote electronique doit satisfaire aux exigences d'integrite, de confidentialite, d'auditabilite et de disponibilite definies par les standards internationaux (CC EAL4+) et les recommandations de la Commission Electorale Independante (CEI).</p></div>`,
  },
  {
    code: 'digit_notification_officielle_electronique',
    name: "Accord de service de notification officielle electronique",
    category: 'juridique_admin',
    price: 5500,
    priceMax: 16500,
    description: "Accord de service pour la transmission et la preuve de reception de notifications officielles electroniques a valeur legale.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'emetteur', label: "Emetteur de la notification", type: 'text', required: true },
      { key: 'destinataire', label: "Destinataire", type: 'text', required: true },
      { key: 'objet_notification', label: "Objet de la notification", type: 'text', required: true },
      { key: 'date_notification', label: "Date et heure de notification", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE NOTIFICATION OFFICIELLE ELECTRONIQUE</h1><p><strong>Emetteur :</strong> {{emetteur}}</p><p><strong>Destinataire :</strong> {{destinataire}}</p><p><strong>Objet :</strong> {{objet_notification}}</p><p><strong>Date de notification :</strong> {{date_notification}}</p><p>La notification electronique certifiee produit les memes effets juridiques qu'une notification par voie postale recommandee avec avis de reception, conformement aux dispositions de la loi sur les transactions electroniques et du Code de Procedure Civile.</p></div>`,
  },
  {
    code: 'digit_partenariat_etat_operateur_identite',
    name: "Accord de partenariat Etat-operateur identite numerique",
    category: 'juridique_admin',
    price: 13000,
    priceMax: 39000,
    description: "Accord de partenariat public-prive pour le deploiement et la gestion d'une infrastructure nationale d'identite numerique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'ministere_tutelle', label: "Ministere de tutelle", type: 'text', required: true },
      { key: 'operateur_prive', label: "Operateur prive partenaire", type: 'text', required: true },
      { key: 'duree_partenariat', label: "Duree du partenariat", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'perimetre_services', label: "Perimetre des services deleguees", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT ETAT-OPERATEUR — IDENTITE NUMERIQUE</h1><p><strong>Ministere de tutelle :</strong> {{ministere_tutelle}}</p><p><strong>Operateur prive :</strong> {{operateur_prive}}</p><p><strong>Duree :</strong> {{duree_partenariat}}</p><p><strong>Date de signature :</strong> {{date_signature}}</p><p><strong>Perimetre des services :</strong> {{perimetre_services}}</p><p>Le present accord de partenariat public-prive (PPP) est regi par les dispositions du Code des PPP en Cote d'Ivoire et les directives de l'UEMOA sur les infrastructures numeriques critiques.</p></div>`,
  },
  {
    code: 'digit_controle_frontiere_abc_gate',
    name: "Accord de service de controle de frontiere automatise (ABC gate)",
    category: 'juridique_admin',
    price: 12000,
    priceMax: 36000,
    description: "Accord de service pour l'installation et l'exploitation de portiques de controle automatise des frontieres bases sur la biometrie.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'autorite_frontaliere', label: "Autorite frontaliere", type: 'text', required: true },
      { key: 'fournisseur_solution', label: "Fournisseur de la solution ABC", type: 'text', required: true },
      { key: 'site_deploiement', label: "Site de deploiement (aeroport/frontiere)", type: 'text', required: true },
      { key: 'date_mise_en_service', label: "Date de mise en service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — CONTROLE DE FRONTIERE AUTOMATISE (ABC GATE)</h1><p><strong>Autorite frontaliere :</strong> {{autorite_frontaliere}}</p><p><strong>Fournisseur :</strong> {{fournisseur_solution}}</p><p><strong>Site de deploiement :</strong> {{site_deploiement}}</p><p><strong>Date de mise en service :</strong> {{date_mise_en_service}}</p><p>Le systeme ABC Gate est conforme aux standards ICAO et INTERPOL en matiere de controle electronique des frontieres et integre la verification des documents de voyage electroniques (e-Passport) via les puces NFC.</p></div>`,
  },
  {
    code: 'digit_registre_foncier_numerique',
    name: "Accord de service de registre foncier numerique",
    category: 'juridique_admin',
    price: 10000,
    priceMax: 30000,
    description: "Accord de service pour la numerisation, la conservation et la consultation du registre foncier dans le cadre de la securisation fonciere.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'administration_fonciere', label: "Administration fonciere", type: 'text', required: true },
      { key: 'prestataire_numerisation', label: "Prestataire de numerisation", type: 'text', required: true },
      { key: 'region_concernee', label: "Region/Departement concerne", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut du projet", type: 'date', required: true },
      { key: 'nombre_parcelles', label: "Nombre de parcelles a numeriser", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — REGISTRE FONCIER NUMERIQUE</h1><p><strong>Administration fonciere :</strong> {{administration_fonciere}}</p><p><strong>Prestataire de numerisation :</strong> {{prestataire_numerisation}}</p><p><strong>Region concernee :</strong> {{region_concernee}}</p><p><strong>Date de debut :</strong> {{date_debut}}</p><p><strong>Parcelles a numeriser :</strong> {{nombre_parcelles}}</p><p>La numerisation du registre foncier s'inscrit dans le cadre de la politique fonciere de Cote d'Ivoire et du projet de modernisation du cadastre, garantissant la securite juridique des droits fonciers conformement au Code Foncier Rural.</p></div>`,
  },
  {
    code: 'digit_sante_connectee_carnet_numerique',
    name: "Accord de service de sante connectee (carnet de sante numerique)",
    category: 'juridique_admin',
    price: 6000,
    priceMax: 18000,
    description: "Accord de service pour l'acces et la gestion du carnet de sante numerique personnel securise.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'patient', label: "Nom du patient", type: 'text', required: true },
      { key: 'numero_carnet', label: "Numero de carnet de sante numerique", type: 'text', required: true },
      { key: 'medecin_referent', label: "Medecin referent", type: 'text', required: false },
      { key: 'date_creation', label: "Date de creation du dossier", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — CARNET DE SANTE NUMERIQUE</h1><p><strong>Patient :</strong> {{patient}}</p><p><strong>Numero de carnet :</strong> {{numero_carnet}}</p><p><strong>Medecin referent :</strong> {{medecin_referent}}</p><p><strong>Date de creation :</strong> {{date_creation}}</p><p>Le carnet de sante numerique est protege par les dispositions de la loi sur la protection des donnees de sante. L'acces est strictement controle et le patient conserve la maitrise de ses donnees medicales conformement aux recommandations de l'OMS et du Ministere de la Sante.</p></div>`,
  },
  {
    code: 'digit_rapport_transformation_digitale_publique',
    name: "Rapport de mise en oeuvre transformation digitale publique",
    category: 'juridique_admin',
    price: 8000,
    priceMax: 24000,
    description: "Rapport officiel de suivi et d'evaluation de la mise en oeuvre des projets de transformation digitale du secteur public.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'ministere', label: "Ministere ou entite publique", type: 'text', required: true },
      { key: 'periode_rapport', label: "Periode couverte par le rapport", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'responsable_redaction', label: "Responsable de la redaction", type: 'text', required: true },
      { key: 'bilan_projets', label: "Bilan des projets digitaux (resume)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE MISE EN OEUVRE — TRANSFORMATION DIGITALE PUBLIQUE</h1><p><strong>Entite :</strong> {{ministere}}</p><p><strong>Periode :</strong> {{periode_rapport}}</p><p><strong>Date :</strong> {{date_rapport}}</p><p><strong>Redige par :</strong> {{responsable_redaction}}</p><h2>Bilan des projets digitaux</h2><p>{{bilan_projets}}</p><p>Ce rapport est produit conformement aux exigences de transparence et de redevabilite de la Strategie Nationale d'Acceleration de la Transformation Numerique (SN@TN 2030) de Cote d'Ivoire.</p></div>`,
  },
  {
    code: 'digit_plan_developpement_egouvt',
    name: "Plan de developpement e-gouvernement",
    category: 'juridique_admin',
    price: 9000,
    priceMax: 27000,
    description: "Document de planification strategique pour le developpement des services d'e-gouvernement au niveau national ou local.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'entite_planificatrice', label: "Entite planificatrice", type: 'text', required: true },
      { key: 'horizon_temporel', label: "Horizon temporel du plan", type: 'text', required: true },
      { key: 'date_adoption', label: "Date d'adoption du plan", type: 'date', required: true },
      { key: 'axes_prioritaires', label: "Axes prioritaires identifies", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DEVELOPPEMENT E-GOUVERNEMENT</h1><p><strong>Entite planificatrice :</strong> {{entite_planificatrice}}</p><p><strong>Horizon temporel :</strong> {{horizon_temporel}}</p><p><strong>Date d'adoption :</strong> {{date_adoption}}</p><h2>Axes prioritaires</h2><p>{{axes_prioritaires}}</p><p>Le present plan de developpement e-gouvernement s'inscrit dans la vision de l'Union Africaine en matiere de transformation numerique (Agenda 2063) et integre les objectifs de developpement durable (ODD) des Nations Unies relatifs a l'innovation et aux infrastructures.</p></div>`,
  },
  {
    code: 'digit_charte_identite_numerique_droits',
    name: "Charte de l'identite numerique et des droits des citoyens en Afrique",
    category: 'juridique_admin',
    price: 7000,
    priceMax: 21000,
    description: "Charte definissant les principes fondamentaux de l'identite numerique et la protection des droits des citoyens africains dans l'espace numerique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'organisation_porteur', label: "Organisation porteuse de la charte", type: 'text', required: true },
      { key: 'pays_signataires', label: "Pays ou entites signataires", type: 'textarea', required: true },
      { key: 'date_adoption', label: "Date d'adoption", type: 'date', required: true },
      { key: 'contact_secretariat', label: "Contact du secretariat", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DE L'IDENTITE NUMERIQUE ET DES DROITS DES CITOYENS EN AFRIQUE</h1><p><strong>Organisation porteuse :</strong> {{organisation_porteur}}</p><p><strong>Signataires :</strong> {{pays_signataires}}</p><p><strong>Date d'adoption :</strong> {{date_adoption}}</p><p><strong>Secretariat :</strong> {{contact_secretariat}}</p><h2>Principes fondamentaux</h2><p>1. Droit a l'identite numerique pour tout citoyen africain. 2. Protection des donnees personnelles et vie privee. 3. Acces equitable aux services numeriques. 4. Souverainete numerique des Etats africains. 5. Interoperabilite des systemes d'identite dans l'espace continental.</p><p>La presente charte s'inspire des principes de la Convention de l'UA sur la cybersecurite et la protection des donnees a caractere personnel (Convention de Malabo) et de la Declaration de Principes de la SMSI.</p></div>`,
  },

  // ─── 25 templates Fintech / Paiements mobiles avancés ────────────────────
  {
    code: 'pay_mobile_money_orange_mtn_wave',
    name: "Accord de service de mobile money (Orange Money, MTN MoMo, Wave CI)",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de service pour l'acces et l'utilisation des services de mobile money des principaux operateurs en Cote d'Ivoire (Orange Money, MTN MoMo, Wave).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 92,
    fieldsJson: F([
      { key: 'titulaire_compte', label: "Nom du titulaire du compte", type: 'text', required: true },
      { key: 'numero_telephone', label: "Numero de telephone", type: 'text', required: true },
      { key: 'operateur', label: "Operateur (Orange Money / MTN MoMo / Wave)", type: 'text', required: true },
      { key: 'date_souscription', label: "Date de souscription", type: 'date', required: true },
      { key: 'plafond_transactions', label: "Plafond de transactions mensuel (FCFA)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE MOBILE MONEY</h1><h2>Orange Money / MTN MoMo / Wave — Cote d'Ivoire</h2><p><strong>Titulaire :</strong> {{titulaire_compte}}</p><p><strong>Telephone :</strong> {{numero_telephone}}</p><p><strong>Operateur :</strong> {{operateur}}</p><p><strong>Date de souscription :</strong> {{date_souscription}}</p><p><strong>Plafond mensuel :</strong> {{plafond_transactions}} FCFA</p><p>Le service de mobile money est soumis a la reglementation de la BCEAO sur les etablissements de monnaie electronique (Instruction n°008-05-2015) et aux conditions generales d'utilisation de l'operateur. Le client s'engage a utiliser le service a des fins licites et a proteger son code secret.</p></div>`,
  },
  {
    code: 'pay_paiement_en_ligne_gateway_ci',
    name: "Accord de service de paiement en ligne (gateway CI)",
    category: 'commercial_financier',
    price: 7500,
    priceMax: 22500,
    description: "Accord de service pour l'integration et l'utilisation d'une passerelle de paiement en ligne adapte au marche ivoirien et UEMOA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'marchand', label: "Nom du marchand / e-commercant", type: 'text', required: true },
      { key: 'prestataire_gateway', label: "Prestataire de la passerelle", type: 'text', required: true },
      { key: 'url_boutique', label: "URL de la boutique en ligne", type: 'text', required: true },
      { key: 'date_activation', label: "Date d'activation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PASSERELLE DE PAIEMENT EN LIGNE</h1><p><strong>Marchand :</strong> {{marchand}}</p><p><strong>Prestataire :</strong> {{prestataire_gateway}}</p><p><strong>Boutique en ligne :</strong> {{url_boutique}}</p><p><strong>Date d'activation :</strong> {{date_activation}}</p><p>La passerelle de paiement respecte les normes PCI-DSS pour la securite des donnees de paiement et les directives de la BCEAO sur les services de paiement electronique dans l'espace UEMOA. Les flux financiers sont reconcilies quotidiennement et les reglement effectues selon le calendrier convenu.</p></div>`,
  },
  {
    code: 'pay_paiement_qr_code',
    name: "Accord de service de paiement par code QR",
    category: 'commercial_financier',
    price: 5500,
    priceMax: 16500,
    description: "Accord de service pour le deploiement et l'utilisation du paiement par code QR au point de vente ou en ligne.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'commercant', label: "Nom du commercant", type: 'text', required: true },
      { key: 'fournisseur_solution', label: "Fournisseur de la solution QR", type: 'text', required: true },
      { key: 'date_deploiement', label: "Date de deploiement", type: 'date', required: true },
      { key: 'nombre_points_vente', label: "Nombre de points de vente", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PAIEMENT PAR CODE QR</h1><p><strong>Commercant :</strong> {{commercant}}</p><p><strong>Fournisseur :</strong> {{fournisseur_solution}}</p><p><strong>Date de deploiement :</strong> {{date_deploiement}}</p><p><strong>Nombre de points de vente :</strong> {{nombre_points_vente}}</p><p>Le systeme de paiement par code QR est conforme au standard EMVCo QR Code et aux specifications interoperables definies par la BCEAO pour les paiements de detail dans l'UEMOA. Il permet les paiements via les applications mobile money des principaux operateurs.</p></div>`,
  },
  {
    code: 'pay_paiement_nfc_sans_contact',
    name: "Accord de service de paiement NFC (sans contact)",
    category: 'commercial_financier',
    price: 6500,
    priceMax: 19500,
    description: "Accord de service pour le deploiement de solutions de paiement sans contact par technologie NFC en point de vente.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'commercant', label: "Nom du commercant", type: 'text', required: true },
      { key: 'fournisseur_terminal', label: "Fournisseur des terminaux NFC", type: 'text', required: true },
      { key: 'nombre_terminaux', label: "Nombre de terminaux deployes", type: 'text', required: true },
      { key: 'date_deploiement', label: "Date de deploiement", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PAIEMENT NFC SANS CONTACT</h1><p><strong>Commercant :</strong> {{commercant}}</p><p><strong>Fournisseur de terminaux :</strong> {{fournisseur_terminal}}</p><p><strong>Nombre de terminaux :</strong> {{nombre_terminaux}}</p><p><strong>Date de deploiement :</strong> {{date_deploiement}}</p><p>Les terminaux de paiement NFC sont certifies EMVCo et conformes aux standards ISO/IEC 14443 pour la communication sans contact. Le traitement des transactions respecte les regles PCI-PTS pour la securite des equipements de paiement.</p></div>`,
  },
  {
    code: 'pay_agregateur_paiement_mobile',
    name: "Accord de service d'agregateur de paiement mobile",
    category: 'commercial_financier',
    price: 8500,
    priceMax: 25500,
    description: "Accord de service avec un agregateur permettant d'accepter plusieurs moyens de paiement mobile via une interface unique.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'client_entreprise', label: "Entreprise cliente", type: 'text', required: true },
      { key: 'agregateur', label: "Nom de l'agregateur", type: 'text', required: true },
      { key: 'canaux_acceptes', label: "Canaux de paiement acceptes", type: 'textarea', required: true },
      { key: 'date_integration', label: "Date d'integration", type: 'date', required: true },
      { key: 'commission_taux', label: "Taux de commission convenu (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'AGREGATEUR DE PAIEMENT MOBILE</h1><p><strong>Entreprise cliente :</strong> {{client_entreprise}}</p><p><strong>Agregateur :</strong> {{agregateur}}</p><p><strong>Canaux acceptes :</strong> {{canaux_acceptes}}</p><p><strong>Date d'integration :</strong> {{date_integration}}</p><p><strong>Commission :</strong> {{commission_taux}}%</p><p>L'agregateur s'engage a fournir une API robuste, des tableaux de bord en temps reel et un support technique 24h/24. Les fonds collectes sont reverses selon le calendrier de reglement agree, deduction faite des commissions et taxes applicables.</p></div>`,
  },
  {
    code: 'pay_transfrontalier_uemoa',
    name: "Accord de service de paiement transfrontalier UEMOA",
    category: 'commercial_financier',
    price: 9000,
    priceMax: 27000,
    description: "Accord de service pour les paiements transfrontaliers entre pays de l'UEMOA via les systemes de paiement regionaux interoperables.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'expediteur', label: "Expediteur (entreprise/particulier)", type: 'text', required: true },
      { key: 'pays_origine', label: "Pays d'origine", type: 'text', required: true },
      { key: 'pays_destination', label: "Pays de destination", type: 'text', required: true },
      { key: 'prestataire_service', label: "Prestataire du service", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PAIEMENT TRANSFRONTALIER UEMOA</h1><p><strong>Expediteur :</strong> {{expediteur}}</p><p><strong>Pays d'origine :</strong> {{pays_origine}}</p><p><strong>Pays de destination :</strong> {{pays_destination}}</p><p><strong>Prestataire :</strong> {{prestataire_service}}</p><p><strong>Date de l'accord :</strong> {{date_accord}}</p><p>Les paiements transfrontaliers s'effectuent dans le cadre du Systeme de Paiement Interbancaire Regional de l'UEMOA (SPIRE) et des directives BCEAO n°008/2002 et n°001/2017/RB relatives aux services de paiement. Le taux de change applique est le cours officiel BCEAO.</p></div>`,
  },
  {
    code: 'pay_remise_fonds_diaspora',
    name: "Accord de service de remise de fonds international (transfert diaspora)",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de service pour le transfert international de fonds de la diaspora vers la Cote d'Ivoire et les pays de l'UEMOA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'operateur_transfert', label: "Operateur de transfert", type: 'text', required: true },
      { key: 'expediteur', label: "Nom de l'expediteur", type: 'text', required: true },
      { key: 'beneficiaire', label: "Nom du beneficiaire", type: 'text', required: true },
      { key: 'date_service', label: "Date de souscription au service", type: 'date', required: true },
      { key: 'pays_envoi', label: "Pays d'envoi", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — REMISE DE FONDS INTERNATIONALE (DIASPORA)</h1><p><strong>Operateur :</strong> {{operateur_transfert}}</p><p><strong>Expediteur :</strong> {{expediteur}}</p><p><strong>Beneficiaire :</strong> {{beneficiaire}}</p><p><strong>Date de souscription :</strong> {{date_service}}</p><p><strong>Pays d'envoi :</strong> {{pays_envoi}}</p><p>Le service de remise de fonds est agree par les autorites competentes (BCEAO et banque centrale du pays d'envoi) et respecte les obligations de declaration LCB-FT. Les fonds sont disponibles dans les delais convenus selon le canal de reception choisi (mobile money, retrait cash, virement bancaire).</p></div>`,
  },
  {
    code: 'pay_portefeuille_electronique_ewallet',
    name: "Accord de service de portefeuille electronique (e-wallet)",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de service pour l'ouverture et la gestion d'un portefeuille electronique (e-wallet) pour particuliers ou entreprises.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'titulaire', label: "Nom du titulaire", type: 'text', required: true },
      { key: 'type_wallet', label: "Type de wallet (Particulier / Entreprise)", type: 'text', required: true },
      { key: 'fournisseur', label: "Fournisseur du service", type: 'text', required: true },
      { key: 'date_creation', label: "Date de creation du wallet", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PORTEFEUILLE ELECTRONIQUE (e-Wallet)</h1><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Type de wallet :</strong> {{type_wallet}}</p><p><strong>Fournisseur :</strong> {{fournisseur}}</p><p><strong>Date de creation :</strong> {{date_creation}}</p><p>Le portefeuille electronique est emis conformement aux dispositions de la directive BCEAO relative a la monnaie electronique. Le titulaire beneficie d'une garantie de remboursement des fonds stockes et d'une protection contre la fraude selon les conditions generales du service.</p></div>`,
  },
  {
    code: 'pay_carte_prepayee_virtuelle',
    name: "Accord de service de carte prepayee virtuelle",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de service pour l'emission et l'utilisation d'une carte prepayee virtuelle pour les paiements en ligne et internationaux.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'titulaire', label: "Nom du titulaire", type: 'text', required: true },
      { key: 'emetteur', label: "Emetteur de la carte", type: 'text', required: true },
      { key: 'plafond_carte', label: "Plafond de la carte (FCFA ou USD)", type: 'text', required: true },
      { key: 'date_emission', label: "Date d'emission", type: 'date', required: true },
      { key: 'date_expiration', label: "Date d'expiration", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — CARTE PREPAYEE VIRTUELLE</h1><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Emetteur :</strong> {{emetteur}}</p><p><strong>Plafond :</strong> {{plafond_carte}}</p><p><strong>Date d'emission :</strong> {{date_emission}}</p><p><strong>Date d'expiration :</strong> {{date_expiration}}</p><p>La carte prepayee virtuelle est utilisable sur tous les sites acceptant les cartes de paiement internationaux (Visa/Mastercard). Elle ne peut etre rechargee au-dela du plafond reglementaire fixe par la BCEAO pour les instruments de paiement prepaye.</p></div>`,
  },
  {
    code: 'pay_pret_digital_bnpl',
    name: "Accord de service de pret digital instantane (BNPL)",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 21000,
    description: "Accord de service Buy Now Pay Later (BNPL) pour le financement instantane de petits achats via mobile en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'emprunteur', label: "Nom de l'emprunteur", type: 'text', required: true },
      { key: 'preteur', label: "Etablissement preteur", type: 'text', required: true },
      { key: 'montant_pret', label: "Montant du pret (FCFA)", type: 'text', required: true },
      { key: 'taux_interet', label: "Taux d'interet mensuel (%)", type: 'text', required: true },
      { key: 'date_octroi', label: "Date d'octroi", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PRET DIGITAL INSTANTANE (BNPL)</h1><p><strong>Emprunteur :</strong> {{emprunteur}}</p><p><strong>Preteur :</strong> {{preteur}}</p><p><strong>Montant :</strong> {{montant_pret}} FCFA</p><p><strong>Taux d'interet mensuel :</strong> {{taux_interet}}%</p><p><strong>Date d'octroi :</strong> {{date_octroi}}</p><p>Le present accord est soumis a la reglementation de l'UEMOA sur l'usure et aux dispositions de la loi sur le credit a la consommation. L'emprunteur beneficie d'un droit de retractation de 14 jours et d'informations transparentes sur le cout total du credit.</p></div>`,
  },
  {
    code: 'pay_credit_scoring_alternatif_mobile',
    name: "Accord de service de credit scoring alternatif (mobile data)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Accord de service pour l'utilisation de donnees mobiles et comportementales dans le calcul d'un score de credit alternatif.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'fournisseur_scoring', label: "Fournisseur du service de scoring", type: 'text', required: true },
      { key: 'entite_cliente', label: "Entite cliente (banque/fintech)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'sources_donnees', label: "Sources de donnees utilisees", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — CREDIT SCORING ALTERNATIF (MOBILE DATA)</h1><p><strong>Fournisseur :</strong> {{fournisseur_scoring}}</p><p><strong>Client :</strong> {{entite_cliente}}</p><p><strong>Date :</strong> {{date_accord}}</p><p><strong>Sources de donnees :</strong> {{sources_donnees}}</p><p>L'utilisation de donnees mobiles et comportementales pour le scoring de credit est encadree par les directives de la BCEAO sur l'utilisation des donnees alternatives en credit et la loi sur la protection des donnees personnelles. Le consentement explicite de l'utilisateur est requis.</p></div>`,
  },
  {
    code: 'pay_facturation_electronique_einvoice',
    name: "Accord de service de facturation electronique (e-invoice)",
    category: 'commercial_financier',
    price: 6500,
    priceMax: 19500,
    description: "Accord de service pour l'emission, la reception et la gestion de factures electroniques conformes aux normes fiscales ivoiriennes.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'entreprise_emettrice', label: "Entreprise emettrice", type: 'text', required: true },
      { key: 'prestataire_einvoice', label: "Prestataire e-invoice", type: 'text', required: true },
      { key: 'volume_mensuel_factures', label: "Volume mensuel de factures", type: 'text', required: false },
      { key: 'date_adhesion', label: "Date d'adhesion au service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — FACTURATION ELECTRONIQUE (e-Invoice)</h1><p><strong>Entreprise emettrice :</strong> {{entreprise_emettrice}}</p><p><strong>Prestataire :</strong> {{prestataire_einvoice}}</p><p><strong>Volume mensuel :</strong> {{volume_mensuel_factures}} factures</p><p><strong>Date d'adhesion :</strong> {{date_adhesion}}</p><p>La facture electronique emise via ce service a la meme valeur juridique et fiscale que la facture papier, conformement aux dispositions du Code General des Impots de Cote d'Ivoire et aux normes EDI/UBL applicables dans l'espace UEMOA.</p></div>`,
  },
  {
    code: 'pay_reconciliation_paiements',
    name: "Accord de service de reconciliation de paiements",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 21000,
    description: "Accord de service pour la reconciliation automatisee des transactions de paiement multi-canaux entre commercants et operateurs.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'entreprise_cliente', label: "Entreprise cliente", type: 'text', required: true },
      { key: 'prestataire_reconciliation', label: "Prestataire du service", type: 'text', required: true },
      { key: 'canaux_couverts', label: "Canaux de paiement couverts", type: 'textarea', required: true },
      { key: 'date_activation', label: "Date d'activation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — RECONCILIATION DE PAIEMENTS</h1><p><strong>Entreprise cliente :</strong> {{entreprise_cliente}}</p><p><strong>Prestataire :</strong> {{prestataire_reconciliation}}</p><p><strong>Canaux couverts :</strong> {{canaux_couverts}}</p><p><strong>Date d'activation :</strong> {{date_activation}}</p><p>Le service de reconciliation automatisee permet de rapprocher en temps reel les transactions provenant de multiples canaux de paiement (mobile money, carte, cash). Des rapports quotidiens, hebdomadaires et mensuels sont fournis avec des indicateurs de performance et des alertes sur les ecarts identifies.</p></div>`,
  },
  {
    code: 'pay_cash_pooling_digital',
    name: "Accord de service de tresorerie en temps reel (cash pooling digital)",
    category: 'commercial_financier',
    price: 11000,
    priceMax: 33000,
    description: "Accord de service pour la gestion centralisee et en temps reel de la tresorerie de groupe via des outils digitaux (cash pooling).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'groupe_entreprises', label: "Groupe d'entreprises", type: 'text', required: true },
      { key: 'banque_teneur', label: "Banque teneur de compte", type: 'text', required: true },
      { key: 'date_mise_en_place', label: "Date de mise en place", type: 'date', required: true },
      { key: 'entites_participants', label: "Entites participantes", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — TRESORERIE EN TEMPS REEL (CASH POOLING DIGITAL)</h1><p><strong>Groupe :</strong> {{groupe_entreprises}}</p><p><strong>Banque teneur :</strong> {{banque_teneur}}</p><p><strong>Date de mise en place :</strong> {{date_mise_en_place}}</p><p><strong>Entites participantes :</strong> {{entites_participants}}</p><p>Le mecanisme de cash pooling permet la centralisation automatique et en temps reel des soldes de tresorerie des filiales sur un compte maitre, optimisant ainsi l'utilisation des liquidites du groupe. Les mouvements intra-groupes respectent les regles de prix de transfert et les dispositions du droit des societes OHADA.</p></div>`,
  },
  {
    code: 'pay_salaire_mobile',
    name: "Accord de service de paiement de salaire par mobile",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de service pour le versement automatise des salaires et remuneration des employes via mobile money.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'employeur', label: "Nom de l'employeur", type: 'text', required: true },
      { key: 'operateur_paie', label: "Operateur de paiement mobile partenaire", type: 'text', required: true },
      { key: 'nombre_employes', label: "Nombre d'employes beneficiaires", type: 'text', required: true },
      { key: 'date_debut', label: "Date de debut du service", type: 'date', required: true },
      { key: 'frequence_paie', label: "Frequence de la paie (mensuelle/bimensuelle)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PAIEMENT DE SALAIRE PAR MOBILE</h1><p><strong>Employeur :</strong> {{employeur}}</p><p><strong>Operateur partenaire :</strong> {{operateur_paie}}</p><p><strong>Nombre d'employes :</strong> {{nombre_employes}}</p><p><strong>Date de debut :</strong> {{date_debut}}</p><p><strong>Frequence :</strong> {{frequence_paie}}</p><p>Le paiement des salaires via mobile money respecte les dispositions du Code du Travail de Cote d'Ivoire sur les modalites de paiement des remunerations et les obligations de l'employeur. Les preuves de paiement electroniques sont conservees conformement aux obligations legales.</p></div>`,
  },
  {
    code: 'pay_taxes_municipales_mobile',
    name: "Accord de service de collecte de taxes municipales (mobile)",
    category: 'commercial_financier',
    price: 7500,
    priceMax: 22500,
    description: "Accord de service pour la collecte electronique des taxes et redevances municipales via les canaux de paiement mobile.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'collectivite', label: "Collectivite territoriale", type: 'text', required: true },
      { key: 'prestataire_collecte', label: "Prestataire de la solution de collecte", type: 'text', required: true },
      { key: 'types_taxes', label: "Types de taxes/redevances concernees", type: 'textarea', required: true },
      { key: 'date_lancement', label: "Date de lancement du service", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — COLLECTE DE TAXES MUNICIPALES PAR MOBILE</h1><p><strong>Collectivite :</strong> {{collectivite}}</p><p><strong>Prestataire :</strong> {{prestataire_collecte}}</p><p><strong>Taxes concernees :</strong> {{types_taxes}}</p><p><strong>Date de lancement :</strong> {{date_lancement}}</p><p>Le service de collecte electronique des taxes municipales est mis en oeuvre conformement au Code General des Collectivites Territoriales de Cote d'Ivoire et a la loi de finances en vigueur. Les fonds collectes sont transferes sur le compte du Tresor Municipal selon le protocole de reglement convenu.</p></div>`,
  },
  {
    code: 'pay_assurance_par_mobile',
    name: "Accord de service de paiement d'assurance par mobile",
    category: 'commercial_financier',
    price: 5500,
    priceMax: 16500,
    description: "Accord de service pour la souscription et le paiement de primes d'assurance via le telephone mobile (microassurance incluse).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'assureur', label: "Compagnie d'assurance", type: 'text', required: true },
      { key: 'souscripteur', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'produit_assurance', label: "Produit d'assurance souscrit", type: 'text', required: true },
      { key: 'date_souscription', label: "Date de souscription", type: 'date', required: true },
      { key: 'prime_mensuelle', label: "Prime mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PAIEMENT D'ASSURANCE PAR MOBILE</h1><p><strong>Assureur :</strong> {{assureur}}</p><p><strong>Souscripteur :</strong> {{souscripteur}}</p><p><strong>Produit souscrit :</strong> {{produit_assurance}}</p><p><strong>Date de souscription :</strong> {{date_souscription}}</p><p><strong>Prime mensuelle :</strong> {{prime_mensuelle}} FCFA</p><p>La souscription et le paiement de la prime s'effectuent via mobile money et sont regis par le Code des Assurances CIMA (Conference Interafricaine des Marches d'Assurances). En cas de sinistre, la declaration peut egalement etre effectuee par voie electronique.</p></div>`,
  },
  {
    code: 'pay_utility_eau_electricite',
    name: "Accord de service de paiement d'eau/electricite (utility)",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13500,
    description: "Accord de service pour le paiement des factures d'eau et d'electricite via les plateformes de paiement mobile et en ligne.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 90,
    fieldsJson: F([
      { key: 'prestataire_paiement', label: "Prestataire de paiement", type: 'text', required: true },
      { key: 'operateur_utilite', label: "Operateur de service (CIE, SODECI, etc.)", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord de partenariat", type: 'date', required: true },
      { key: 'canaux_paiement', label: "Canaux de paiement disponibles", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — PAIEMENT FACTURES EAU ET ELECTRICITE</h1><p><strong>Prestataire de paiement :</strong> {{prestataire_paiement}}</p><p><strong>Operateur de service :</strong> {{operateur_utilite}}</p><p><strong>Date de l'accord :</strong> {{date_accord}}</p><p><strong>Canaux disponibles :</strong> {{canaux_paiement}}</p><p>Le service permet aux abonnes de payer leurs factures d'eau et d'electricite via mobile money, application web ou USSD, 24h/24 et 7j/7. La quittance electronique generee est valable comme justificatif de paiement aupres des services de la CIE et de la SODECI.</p></div>`,
  },
  {
    code: 'pay_marketplace_pret_p2p',
    name: "Accord de service de marketplace de pret P2P (plateforme)",
    category: 'commercial_financier',
    price: 9500,
    priceMax: 28500,
    description: "Accord de service encadrant l'acces et l'utilisation d'une plateforme de pret entre particuliers (P2P lending) en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'plateforme', label: "Nom de la plateforme P2P", type: 'text', required: true },
      { key: 'utilisateur', label: "Nom de l'utilisateur (preteur ou emprunteur)", type: 'text', required: true },
      { key: 'role', label: "Role (Preteur / Emprunteur)", type: 'text', required: true },
      { key: 'date_inscription', label: "Date d'inscription", type: 'date', required: true },
      { key: 'limite_exposition', label: "Limite d'exposition financiere (FCFA)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — MARKETPLACE DE PRET P2P</h1><p><strong>Plateforme :</strong> {{plateforme}}</p><p><strong>Utilisateur :</strong> {{utilisateur}}</p><p><strong>Role :</strong> {{role}}</p><p><strong>Date d'inscription :</strong> {{date_inscription}}</p><p><strong>Limite d'exposition :</strong> {{limite_exposition}} FCFA</p><p>La plateforme opere sous l'autorisation de la BCEAO et est soumise aux dispositions de la reglementation sur les etablissements de microfinance et les innovations financieres. Les risques de credit sont assumes par les preteurs individuels qui doivent etre informes de la nature non garantie des prets.</p></div>`,
  },
  {
    code: 'pay_stablecoin_xof_regulee',
    name: "Accord de service de cryptomonnaie regulee (stablecoin XOF)",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Accord de service pour l'emission, la distribution et l'utilisation d'un stablecoin adosse au Franc CFA (XOF) dans le cadre reglementaire UEMOA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'emetteur_stablecoin', label: "Emetteur du stablecoin", type: 'text', required: true },
      { key: 'utilisateur', label: "Utilisateur / institution", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'conditions_utilisation', label: "Conditions d'utilisation acceptees", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE — STABLECOIN XOF REGULEE</h1><p><strong>Emetteur :</strong> {{emetteur_stablecoin}}</p><p><strong>Utilisateur :</strong> {{utilisateur}}</p><p><strong>Date :</strong> {{date_accord}}</p><p><strong>Conditions :</strong> {{conditions_utilisation}}</p><p>L'emission et la circulation du stablecoin adosse au XOF sont soumises a l'autorisation prealable de la BCEAO et respectent le cadre reglementaire experimental sur les actifs numeriques defini par la Banque Centrale. La parite 1:1 avec le XOF est garantie par des reserves en monnaie fiduciaire auditees.</p></div>`,
  },
  {
    code: 'pay_conformite_bceao_fintech',
    name: "Accord de conformite BCEAO fintech (agrements)",
    category: 'commercial_financier',
    price: 11000,
    priceMax: 33000,
    description: "Accord et dossier de conformite pour l'obtention d'un agrement de la BCEAO en tant qu'etablissement de monnaie electronique ou prestataire de services de paiement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'entreprise_candidate', label: "Entreprise candidate", type: 'text', required: true },
      { key: 'type_agrement', label: "Type d'agrement sollicite", type: 'text', required: true },
      { key: 'date_depot_dossier', label: "Date de depot du dossier", type: 'date', required: true },
      { key: 'capital_minimum', label: "Capital minimum requis (FCFA)", type: 'text', required: true },
      { key: 'representant_legal', label: "Representant legal", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONFORMITE BCEAO — AGREMENT FINTECH</h1><p><strong>Entreprise candidate :</strong> {{entreprise_candidate}}</p><p><strong>Type d'agrement :</strong> {{type_agrement}}</p><p><strong>Date de depot :</strong> {{date_depot_dossier}}</p><p><strong>Capital minimum :</strong> {{capital_minimum}} FCFA</p><p><strong>Representant legal :</strong> {{representant_legal}}</p><p>La demande d'agrement est soumise conformement a l'Instruction n°008-05-2015 de la BCEAO relative aux conditions et modalites d'exercice des activites des systemes financiers decentralises et aux textes relatifs aux etablissements de monnaie electronique dans l'UEMOA.</p></div>`,
  },
  {
    code: 'pay_open_banking_banque_fintech',
    name: "Accord de partenariat banque-fintech (open banking)",
    category: 'commercial_financier',
    price: 13000,
    priceMax: 39000,
    description: "Accord de partenariat entre une banque traditionnelle et une fintech dans le cadre de l'open banking, definissant l'acces aux API bancaires et le partage de donnees.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'banque_partenaire', label: "Banque partenaire", type: 'text', required: true },
      { key: 'fintech_partenaire', label: "Fintech partenaire", type: 'text', required: true },
      { key: 'services_api', label: "Services API ouverts (liste)", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature du partenariat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT BANQUE-FINTECH — OPEN BANKING</h1><p><strong>Banque :</strong> {{banque_partenaire}}</p><p><strong>Fintech :</strong> {{fintech_partenaire}}</p><p><strong>Services API ouverts :</strong> {{services_api}}</p><p><strong>Date de signature :</strong> {{date_signature}}</p><p>Le present accord encadre les conditions d'acces aux interfaces de programmation (API) bancaires, la responsabilite des parties en matiere de securite des donnees, et les modalites de partage des revenus. Il est conforme aux orientations de la BCEAO sur l'open banking et la protection des donnees des clients bancaires.</p></div>`,
  },
  {
    code: 'pay_formation_fintech',
    name: "Accord de service de formation fintech",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de service pour la formation professionnelle aux metiers de la fintech et des paiements digitaux en Afrique francophone.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'organisme_formation', label: "Organisme de formation", type: 'text', required: true },
      { key: 'entreprise_cliente', label: "Entreprise cliente", type: 'text', required: true },
      { key: 'programme_formation', label: "Programme de formation", type: 'textarea', required: true },
      { key: 'date_debut_formation', label: "Date de debut de la formation", type: 'date', required: true },
      { key: 'nombre_apprenants', label: "Nombre d'apprenants", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE FORMATION FINTECH</h1><p><strong>Organisme de formation :</strong> {{organisme_formation}}</p><p><strong>Entreprise cliente :</strong> {{entreprise_cliente}}</p><p><strong>Programme :</strong> {{programme_formation}}</p><p><strong>Date de debut :</strong> {{date_debut_formation}}</p><p><strong>Nombre d'apprenants :</strong> {{nombre_apprenants}}</p><p>La formation est dispensee par des experts certifies du secteur fintech et couvre les domaines de la reglementation BCEAO, des technologies de paiement, de la cybersecurite financiere et de la conformite LCB-FT. Une attestation est delivree a l'issue de la formation.</p></div>`,
  },
  {
    code: 'pay_rapport_performance_operateur_mobile',
    name: "Rapport de performance operateur de paiement mobile",
    category: 'commercial_financier',
    price: 6500,
    priceMax: 19500,
    description: "Rapport standardise d'evaluation des performances d'un operateur de paiement mobile (volumes, disponibilite, incidents, satisfaction).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'operateur', label: "Nom de l'operateur", type: 'text', required: true },
      { key: 'periode_rapport', label: "Periode du rapport", type: 'text', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
      { key: 'indicateurs_cles', label: "Indicateurs cles de performance (resume)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE — OPERATEUR DE PAIEMENT MOBILE</h1><p><strong>Operateur :</strong> {{operateur}}</p><p><strong>Periode :</strong> {{periode_rapport}}</p><p><strong>Date :</strong> {{date_rapport}}</p><h2>Indicateurs cles de performance</h2><p>{{indicateurs_cles}}</p><p>Ce rapport est produit conformement aux obligations de reporting imposees par la BCEAO aux etablissements de monnaie electronique (Instruction n°008-05-2015) et permet le suivi de la qualite de service, de la disponibilite des systemes, des volumes de transactions et de la satisfaction des utilisateurs.</p></div>`,
  },
  {
    code: 'pay_charte_fintech_inclusive',
    name: "Charte de la fintech inclusive et de la protection du consommateur",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 21000,
    description: "Charte d'engagement des acteurs fintech de l'UEMOA en matiere d'inclusion financiere et de protection des droits des consommateurs de services financiers digitaux.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'organisation_porteuse', label: "Organisation porteuse de la charte", type: 'text', required: true },
      { key: 'signataires', label: "Acteurs fintech signataires", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'perimetre_geographique', label: "Perimetre geographique (pays)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE LA FINTECH INCLUSIVE ET DE LA PROTECTION DU CONSOMMATEUR</h1><p><strong>Organisation porteuse :</strong> {{organisation_porteuse}}</p><p><strong>Signataires :</strong> {{signataires}}</p><p><strong>Date de signature :</strong> {{date_signature}}</p><p><strong>Perimetre :</strong> {{perimetre_geographique}}</p><h2>Engagements fondamentaux</h2><p>1. Promouvoir l'acces aux services financiers pour les populations non bancarisees. 2. Assurer la transparence totale sur les frais et conditions de service. 3. Proteger les donnees personnelles et financieres des utilisateurs. 4. Garantir des mecanismes de recours accessibles et efficaces. 5. Contribuer a la stabilite financiere de l'espace UEMOA.</p><p>La presente charte s'aligne sur les Principes Directeurs pour la Protection des Consommateurs de Services Financiers Digitaux du G20 et les directives BCEAO sur l'inclusion financiere.</p></div>`,
  },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 101a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
