import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── MINES / RESSOURCES NATURELLES (25 templates) ───────────────────────────
  {
    code: 'mine_permis_recherche',
    name: "Permis de Recherche Minière",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Demande officielle de permis de recherche minière conforme au code minier OHADA.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'titulaire', label: "Nom du titulaire / société", type: 'text', required: true },
      { key: 'zone_recherche', label: "Zone géographique de recherche", type: 'text', required: true },
      { key: 'substances', label: "Substances minérales visées", type: 'text', required: true },
      { key: 'duree_permis', label: "Durée demandée du permis", type: 'text', required: true },
      { key: 'date_depot', label: "Date de dépôt de la demande", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>DEMANDE DE PERMIS DE RECHERCHE MINIÈRE</h1><p>Le soussigné <strong>{{titulaire}}</strong> sollicite, conformément au Code Minier en vigueur, l'octroi d'un permis de recherche minière sur la zone géographique désignée : <strong>{{zone_recherche}}</strong>.</p><p>Les substances minérales visées sont les suivantes : {{substances}}.</p><p>La durée sollicitée pour ce permis est de <strong>{{duree_permis}}</strong>.</p><p>Fait le {{date_depot}}.</p><p>Signature du demandeur : ____________________</p></div>`,
  },
  {
    code: 'mine_permis_exploitation',
    name: "Permis d\"Exploitation Minière",
    category: 'agro_environnement',
    price: 20000,
    priceMax: 60000,
    description: "Titre minier d\"exploitation accordé par l\"État pour l\"extraction de ressources minérales.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'societe', label: "Raison sociale de la société minière", type: 'text', required: true },
      { key: 'perimetre', label: "Périmètre d\"exploitation (coordonnées)", type: 'textarea', required: true },
      { key: 'minerai', label: "Minerai ou substance exploitée", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début d\"exploitation", type: 'date', required: true },
      { key: 'date_fin', label: "Date d\"expiration du permis", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PERMIS D"EXPLOITATION MINIÈRE</h1><p>Il est accordé à la société <strong>{{societe}}</strong> le présent permis d"exploitation minière portant sur le périmètre suivant : {{perimetre}}.</p><p>La substance exploitée est : <strong>{{minerai}}</strong>.</p><p>Le présent permis prend effet le <strong>{{date_debut}}</strong> et expire le <strong>{{date_fin}}</strong>.</p><p>Le titulaire s"engage à respecter les dispositions du Code Minier, les normes environnementales et les obligations fiscales applicables.</p><p>Autorité compétente : ____________________</p></div>`,
  },
  {
    code: 'mine_convention_etat',
    name: "Convention Minière avec l\"État",
    category: 'agro_environnement',
    price: 25000,
    priceMax: 75000,
    description: "Convention-cadre entre l\"État et une société minière fixant les droits et obligations des parties.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'etat', label: "État partie (pays)", type: 'text', required: true },
      { key: 'societe_miniere', label: "Société minière cocontractante", type: 'text', required: true },
      { key: 'projet', label: "Nom du projet minier", type: 'text', required: true },
      { key: 'redevances', label: "Taux des redevances et taxes convenus", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION MINIÈRE</h1><p>Entre <strong>l"État de {{etat}}</strong>, représenté par le Ministre en charge des Mines, et la société <strong>{{societe_miniere}}</strong>, il est convenu ce qui suit dans le cadre du projet minier <strong>{{projet}}</strong>.</p><p>Les parties définissent les droits d"exploitation, les redevances et taxes applicables : {{redevances}}.</p><p>La présente convention est signée le <strong>{{date_signature}}</strong> et régit l"ensemble des activités minières couvertes.</p><p>Pour l"État : ____________________<br/>Pour la Société : ____________________</p></div>`,
  },
  {
    code: 'mine_contrat_psc',
    name: "Contrat de Partage de Production Pétrolière (PSC)",
    category: 'agro_environnement',
    price: 25000,
    priceMax: 80000,
    description: "Contrat de partage de production entre l\"État et une compagnie pétrolière internationale.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'compagnie', label: "Compagnie pétrolière", type: 'text', required: true },
      { key: 'bloc_petrolier', label: "Numéro/nom du bloc pétrolier", type: 'text', required: true },
      { key: 'part_etat', label: "Part de production allouée à l\"État (%)", type: 'text', required: true },
      { key: 'part_compagnie', label: "Part de production allouée à la compagnie (%)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat", type: 'text', required: true },
      { key: 'date_entree', label: "Date d\"entrée en vigueur", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PARTAGE DE PRODUCTION PÉTROLIÈRE</h1><p>Le présent Contrat de Partage de Production (PSC) est conclu entre l"État et la compagnie <strong>{{compagnie}}</strong> pour le bloc pétrolier <strong>{{bloc_petrolier}}</strong>.</p><p>La production est répartie comme suit :<br/>- Part de l"État : <strong>{{part_etat}}</strong><br/>- Part de la compagnie : <strong>{{part_compagnie}}</strong></p><p>Durée du contrat : <strong>{{duree_contrat}}</strong>. Entrée en vigueur : <strong>{{date_entree}}</strong>.</p></div>`,
  },
  {
    code: 'mine_accord_concession_petroliere',
    name: "Accord de Concession Pétrolière",
    category: 'agro_environnement',
    price: 22000,
    priceMax: 66000,
    description: "Accord de concession accordant à un opérateur le droit d\"explorer et d\"exploiter des hydrocarbures.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'concessionnaire', label: "Concessionnaire (opérateur pétrolier)", type: 'text', required: true },
      { key: 'zone_concession', label: "Zone géographique de la concession", type: 'text', required: true },
      { key: 'type_hydrocarbure', label: "Type d\"hydrocarbure visé", type: 'text', required: true },
      { key: 'redevance_annuelle', label: "Redevance annuelle (FCFA)", type: 'text', required: true },
      { key: 'date_concession', label: "Date d\"octroi de la concession", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CONCESSION PÉTROLIÈRE</h1><p>Il est accordé à <strong>{{concessionnaire}}</strong> la concession pétrolière sur la zone : <strong>{{zone_concession}}</strong>.</p><p>Hydrocarbure visé : {{type_hydrocarbure}}. Redevance annuelle fixée à : <strong>{{redevance_annuelle}} FCFA</strong>.</p><p>Date d"octroi : <strong>{{date_concession}}</strong>.</p><p>Signature de l"autorité concédante : ____________________</p></div>`,
  },
  {
    code: 'mine_contrat_drilling',
    name: "Contrat de Service Pétrolier (Drilling)",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Contrat de prestation de services de forage pétrolier entre un opérateur et un prestataire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'operateur', label: "Opérateur pétrolier (donneur d\"ordre)", type: 'text', required: true },
      { key: 'prestataire_forage', label: "Société de forage (prestataire)", type: 'text', required: true },
      { key: 'puits', label: "Nom/référence du puits à forer", type: 'text', required: true },
      { key: 'cout_forage', label: "Coût total du forage (FCFA)", type: 'text', required: true },
      { key: 'date_debut_forage', label: "Date de début des travaux", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE PÉTROLIER - FORAGE</h1><p><strong>{{operateur}}</strong> confie à <strong>{{prestataire_forage}}</strong> la réalisation des travaux de forage du puits <strong>{{puits}}</strong>.</p><p>Coût convenu : <strong>{{cout_forage}} FCFA</strong>. Début des travaux : <strong>{{date_debut_forage}}</strong>.</p><p>Le prestataire s"engage à respecter les normes de sécurité HSE et les délais contractuels.</p></div>`,
  },
  {
    code: 'mine_contrat_vente_minerais',
    name: "Contrat de Vente de Minerais",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Contrat commercial de vente de minerais entre un producteur minier et un acheteur.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'vendeur_minerais', label: "Vendeur (société minière)", type: 'text', required: true },
      { key: 'acheteur_minerais', label: "Acheteur", type: 'text', required: true },
      { key: 'minerai_vendu', label: "Type et qualité du minerai", type: 'text', required: true },
      { key: 'quantite', label: "Quantité vendue (tonnes)", type: 'text', required: true },
      { key: 'prix_unitaire', label: "Prix unitaire convenu (USD ou FCFA/tonne)", type: 'text', required: true },
      { key: 'date_livraison', label: "Date de livraison prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE DE MINERAIS</h1><p><strong>{{vendeur_minerais}}</strong> cède à <strong>{{acheteur_minerais}}</strong> la quantité de <strong>{{quantite}} tonnes</strong> de <strong>{{minerai_vendu}}</strong>.</p><p>Prix unitaire : <strong>{{prix_unitaire}}</strong>. Livraison prévue le : <strong>{{date_livraison}}</strong>.</p><p>Vendeur : ____________________<br/>Acheteur : ____________________</p></div>`,
  },
  {
    code: 'mine_accord_transport',
    name: "Accord de Transport de Minerais",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Accord encadrant le transport de minerais entre le site d\"extraction et le port ou l\"usine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'expediteur', label: "Expéditeur (société minière)", type: 'text', required: true },
      { key: 'transporteur', label: "Transporteur", type: 'text', required: true },
      { key: 'itineraire', label: "Itinéraire (origine - destination)", type: 'text', required: true },
      { key: 'volume_transport', label: "Volume mensuel à transporter (tonnes)", type: 'text', required: true },
      { key: 'tarif_transport', label: "Tarif de transport (FCFA/tonne)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSPORT DE MINERAIS</h1><p><strong>{{expediteur}}</strong> confie à <strong>{{transporteur}}</strong> le transport de minerais selon l"itinéraire : <strong>{{itineraire}}</strong>.</p><p>Volume mensuel estimé : <strong>{{volume_transport}} tonnes</strong>. Tarif convenu : <strong>{{tarif_transport}} FCFA/tonne</strong>.</p><p>Expéditeur : ____________________<br/>Transporteur : ____________________</p></div>`,
  },
  {
    code: 'mine_convention_fonderie',
    name: "Convention de Fonderie et Traitement Minéral",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Convention entre une société minière et une fonderie pour le traitement et la transformation des minerais.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'societe_miniere_f', label: "Société minière (fournisseur)", type: 'text', required: true },
      { key: 'fonderie', label: "Fonderie / usine de traitement", type: 'text', required: true },
      { key: 'minerai_traite', label: "Minerai soumis au traitement", type: 'text', required: true },
      { key: 'frais_traitement', label: "Frais de traitement (FCFA/tonne)", type: 'text', required: true },
      { key: 'date_debut_conv', label: "Date de début de la convention", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE FONDERIE ET TRAITEMENT MINÉRAL</h1><p><strong>{{societe_miniere_f}}</strong> confie à <strong>{{fonderie}}</strong> le traitement de son minerai : <strong>{{minerai_traite}}</strong>.</p><p>Frais de traitement : <strong>{{frais_traitement}} FCFA/tonne</strong>. Convention en vigueur à compter du : <strong>{{date_debut_conv}}</strong>.</p></div>`,
  },
  {
    code: 'mine_accord_partenariat',
    name: "Accord de Partenariat Minier",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Accord de partenariat stratégique entre deux sociétés minières pour un projet commun.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'partenaire_a', label: "Partenaire A", type: 'text', required: true },
      { key: 'partenaire_b', label: "Partenaire B", type: 'text', required: true },
      { key: 'projet_commun', label: "Description du projet minier commun", type: 'textarea', required: true },
      { key: 'repartition_apports', label: "Répartition des apports et responsabilités", type: 'textarea', required: true },
      { key: 'date_accord', label: "Date de l\"accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT MINIER</h1><p><strong>{{partenaire_a}}</strong> et <strong>{{partenaire_b}}</strong> s"associent dans le cadre du projet minier suivant : {{projet_commun}}.</p><p>Répartition des apports et responsabilités : {{repartition_apports}}.</p><p>Accord conclu le : <strong>{{date_accord}}</strong>.</p></div>`,
  },
  {
    code: 'mine_contrat_sous_traitance',
    name: "Contrat de Sous-Traitance Minière",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de sous-traitance pour des travaux miniers spécialisés (forage, terrassement, sécurité).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'donneur_ordre_mine', label: "Donneur d\"ordre (société minière principale)", type: 'text', required: true },
      { key: 'sous_traitant_mine', label: "Sous-traitant", type: 'text', required: true },
      { key: 'travaux_confies', label: "Nature des travaux sous-traités", type: 'textarea', required: true },
      { key: 'montant_st', label: "Montant du contrat (FCFA)", type: 'text', required: true },
      { key: 'delai_execution', label: "Délai d\"exécution prévu", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SOUS-TRAITANCE MINIÈRE</h1><p><strong>{{donneur_ordre_mine}}</strong> confie à <strong>{{sous_traitant_mine}}</strong> les travaux suivants : {{travaux_confies}}.</p><p>Montant du contrat : <strong>{{montant_st}} FCFA</strong>. Délai d"exécution : <strong>{{delai_execution}}</strong>.</p><p>Donneur d"ordre : ____________________<br/>Sous-traitant : ____________________</p></div>`,
  },
  {
    code: 'mine_plan_developpement',
    name: "Plan de Développement de la Mine",
    category: 'agro_environnement',
    price: 20000,
    priceMax: 60000,
    description: "Document de planification stratégique du développement et de l\"exploitation d\"une mine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'nom_mine', label: "Nom de la mine", type: 'text', required: true },
      { key: 'localisation_mine', label: "Localisation géographique", type: 'text', required: true },
      { key: 'objectifs_production', label: "Objectifs de production annuelle", type: 'textarea', required: true },
      { key: 'investissements', label: "Investissements prévus (FCFA)", type: 'text', required: true },
      { key: 'horizon_plan', label: "Horizon du plan (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT DE LA MINE</h1><h2>{{nom_mine}} - {{localisation_mine}}</h2><p><strong>Objectifs de production :</strong> {{objectifs_production}}</p><p><strong>Investissements prévus :</strong> {{investissements}} FCFA</p><p><strong>Horizon du plan :</strong> {{horizon_plan}} ans</p><p>Ce plan constitue le document de référence pour le développement et l"exploitation de la mine.</p></div>`,
  },
  {
    code: 'mine_rapport_eie',
    name: "Rapport d\"Impact Environnemental Minier (EIE)",
    category: 'agro_environnement',
    price: 22000,
    priceMax: 66000,
    description: "Rapport d\"évaluation d\"impact environnemental requis avant tout projet minier.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'projet_minier', label: "Nom du projet minier", type: 'text', required: true },
      { key: 'promoteur', label: "Promoteur du projet", type: 'text', required: true },
      { key: 'zone_impact', label: "Zone d\"impact environnemental", type: 'text', required: true },
      { key: 'impacts_identifies', label: "Principaux impacts identifiés", type: 'textarea', required: true },
      { key: 'mesures_attenuation', label: "Mesures d\"atténuation proposées", type: 'textarea', required: true },
      { key: 'date_rapport', label: "Date du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D"IMPACT ENVIRONNEMENTAL MINIER (EIE)</h1><p><strong>Projet :</strong> {{projet_minier}}<br/><strong>Promoteur :</strong> {{promoteur}}<br/><strong>Zone d"impact :</strong> {{zone_impact}}</p><p><strong>Impacts identifiés :</strong> {{impacts_identifies}}</p><p><strong>Mesures d"atténuation :</strong> {{mesures_attenuation}}</p><p>Rapport établi le : <strong>{{date_rapport}}</strong></p></div>`,
  },
  {
    code: 'mine_plan_rehabilitation',
    name: "Plan de Réhabilitation de Site Minier",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Plan de réhabilitation environnementale du site minier après exploitation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'site_minier', label: "Nom/identification du site minier", type: 'text', required: true },
      { key: 'superficie_rehabiliter', label: "Superficie à réhabiliter (ha)", type: 'text', required: true },
      { key: 'actions_rehabilitation', label: "Actions de réhabilitation prévues", type: 'textarea', required: true },
      { key: 'cout_rehabilitation', label: "Coût estimé de la réhabilitation (FCFA)", type: 'text', required: true },
      { key: 'echeancier', label: "Échéancier de réhabilitation", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE RÉHABILITATION DE SITE MINIER</h1><p><strong>Site :</strong> {{site_minier}}<br/><strong>Superficie à réhabiliter :</strong> {{superficie_rehabiliter}} ha</p><p><strong>Actions de réhabilitation :</strong> {{actions_rehabilitation}}</p><p><strong>Coût estimé :</strong> {{cout_rehabilitation}} FCFA</p><p><strong>Échéancier :</strong> {{echeancier}}</p></div>`,
  },
  {
    code: 'mine_plan_securite_hse',
    name: "Plan de Sécurité Mine (HSE)",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Plan Hygiène Sécurité Environnement (HSE) pour les opérations minières.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'mine_hse', label: "Nom de la mine", type: 'text', required: true },
      { key: 'responsable_hse', label: "Responsable HSE désigné", type: 'text', required: true },
      { key: 'risques_identifies', label: "Risques identifiés", type: 'textarea', required: true },
      { key: 'procedures_securite', label: "Procédures de sécurité mises en place", type: 'textarea', required: true },
      { key: 'date_plan', label: "Date d\"élaboration du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE SÉCURITÉ MINE - HSE</h1><p><strong>Mine :</strong> {{mine_hse}}<br/><strong>Responsable HSE :</strong> {{responsable_hse}}</p><p><strong>Risques identifiés :</strong> {{risques_identifies}}</p><p><strong>Procédures de sécurité :</strong> {{procedures_securite}}</p><p>Plan établi le : <strong>{{date_plan}}</strong></p></div>`,
  },
  {
    code: 'mine_convention_eaux',
    name: "Convention de Gestion des Eaux Minières",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Convention fixant les modalités de gestion et de traitement des eaux issues des activités minières.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'operateur_eau', label: "Opérateur minier", type: 'text', required: true },
      { key: 'autorite_eau', label: "Autorité de gestion des eaux", type: 'text', required: true },
      { key: 'normes_rejet', label: "Normes de rejet des eaux (paramètres)", type: 'textarea', required: true },
      { key: 'systeme_traitement', label: "Système de traitement des eaux prévu", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE GESTION DES EAUX MINIÈRES</h1><p><strong>Opérateur minier :</strong> {{operateur_eau}}<br/><strong>Autorité de l"eau :</strong> {{autorite_eau}}</p><p><strong>Normes de rejet :</strong> {{normes_rejet}}</p><p><strong>Système de traitement :</strong> {{systeme_traitement}}</p><p>Signatures des parties : ____________________</p></div>`,
  },
  {
    code: 'mine_accord_csr',
    name: "Accord de Communauté Locale (CSR Minier)",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Accord de responsabilité sociale entre une société minière et les communautés locales affectées.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'societe_csr', label: "Société minière", type: 'text', required: true },
      { key: 'communaute', label: "Communauté / Village concerné", type: 'text', required: true },
      { key: 'engagements_sociaux', label: "Engagements sociaux de la société", type: 'textarea', required: true },
      { key: 'budget_csr', label: "Budget CSR annuel (FCFA)", type: 'text', required: true },
      { key: 'date_accord_csr', label: "Date de l\"accord", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RESPONSABILITÉ SOCIALE (CSR) - COMMUNAUTÉ LOCALE</h1><p><strong>{{societe_csr}}</strong> s"engage envers la communauté de <strong>{{communaute}}</strong> à réaliser les actions suivantes : {{engagements_sociaux}}.</p><p>Budget CSR annuel alloué : <strong>{{budget_csr}} FCFA</strong>.</p><p>Accord signé le : <strong>{{date_accord_csr}}</strong>.</p></div>`,
  },
  {
    code: 'mine_contrat_securite',
    name: "Contrat de Prestataire de Sécurité Mine",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de prestation de services de sécurité et gardiennage pour un site minier.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'client_mine', label: "Société minière cliente", type: 'text', required: true },
      { key: 'societe_securite', label: "Société de sécurité prestataire", type: 'text', required: true },
      { key: 'perimetre_securise', label: "Périmètre à sécuriser", type: 'text', required: true },
      { key: 'effectif_securite', label: "Effectif d\"agents de sécurité déployés", type: 'text', required: true },
      { key: 'cout_mensuel_sec', label: "Coût mensuel du service (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PRESTATAIRE DE SÉCURITÉ MINE</h1><p><strong>{{client_mine}}</strong> confie à <strong>{{societe_securite}}</strong> la sécurisation du périmètre : <strong>{{perimetre_securise}}</strong>.</p><p>Effectif déployé : <strong>{{effectif_securite}} agents</strong>. Coût mensuel : <strong>{{cout_mensuel_sec}} FCFA</strong>.</p></div>`,
  },
  {
    code: 'mine_rapport_production',
    name: "Rapport de Production Minière Mensuel",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 24000,
    description: "Rapport mensuel de production présenté aux autorités minières et aux actionnaires.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'mine_rapport', label: "Nom de la mine", type: 'text', required: true },
      { key: 'mois_rapport', label: "Mois et année du rapport", type: 'text', required: true },
      { key: 'production_realisee', label: "Production réalisée (tonnes / onces)", type: 'text', required: true },
      { key: 'production_objectif', label: "Production objectif du mois", type: 'text', required: true },
      { key: 'incidents_mois', label: "Incidents signalés durant le mois", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PRODUCTION MINIÈRE MENSUEL</h1><p><strong>Mine :</strong> {{mine_rapport}}<br/><strong>Période :</strong> {{mois_rapport}}</p><p><strong>Production réalisée :</strong> {{production_realisee}}<br/><strong>Objectif :</strong> {{production_objectif}}</p><p><strong>Incidents signalés :</strong> {{incidents_mois}}</p><p>Responsable de production : ____________________</p></div>`,
  },
  {
    code: 'mine_accord_eiti',
    name: "Accord de Certification Minière (EITI)",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Accord d\"adhésion et de conformité à l\"Initiative pour la Transparence des Industries Extractives (EITI).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'societe_eiti', label: "Société adhérente à l\"EITI", type: 'text', required: true },
      { key: 'pays_eiti', label: "Pays de mise en oeuvre", type: 'text', required: true },
      { key: 'paiements_declares', label: "Paiements déclarés à l\"État (FCFA)", type: 'text', required: true },
      { key: 'annee_rapport_eiti', label: "Année de référence du rapport", type: 'text', required: true },
      { key: 'date_soumission', label: "Date de soumission du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION MINIÈRE - EITI</h1><p><strong>{{societe_eiti}}</strong>, opérant en <strong>{{pays_eiti}}</strong>, déclare conformément aux exigences EITI les paiements suivants effectués à l"État : <strong>{{paiements_declares}} FCFA</strong>.</p><p>Année de référence : <strong>{{annee_rapport_eiti}}</strong>. Rapport soumis le : <strong>{{date_soumission}}</strong>.</p></div>`,
  },
  {
    code: 'mine_contrat_geologue',
    name: "Contrat de Géologue Conseil",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de mission d\"un géologue expert-conseil pour une société minière.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'geologue', label: "Nom du géologue conseil", type: 'text', required: true },
      { key: 'societe_cliente', label: "Société minière cliente", type: 'text', required: true },
      { key: 'mission_geo', label: "Description de la mission", type: 'textarea', required: true },
      { key: 'honoraires', label: "Honoraires convenus (FCFA)", type: 'text', required: true },
      { key: 'duree_mission', label: "Durée de la mission", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GÉOLOGUE CONSEIL</h1><p><strong>{{geologue}}</strong> est engagé par <strong>{{societe_cliente}}</strong> pour la mission suivante : {{mission_geo}}.</p><p>Honoraires : <strong>{{honoraires}} FCFA</strong>. Durée : <strong>{{duree_mission}}</strong>.</p><p>Géologue : ____________________<br/>Société : ____________________</p></div>`,
  },
  {
    code: 'mine_accord_orpaillage',
    name: "Accord de Prospection Artisanale (Orpaillage)",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 24000,
    description: "Accord encadrant les activités d\"orpaillage artisanal et de prospection aurifère.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'orpailleur', label: "Nom du groupement ou orpailleur", type: 'text', required: true },
      { key: 'zone_orpaillage', label: "Zone d\"orpaillage autorisée", type: 'text', required: true },
      { key: 'autorite_locale', label: "Autorité locale ayant délivré l\"autorisation", type: 'text', required: true },
      { key: 'redevance_orpaillage', label: "Redevance d\"exploitation (FCFA)", type: 'text', required: true },
      { key: 'date_autorisation', label: "Date de l\"autorisation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PROSPECTION ARTISANALE - ORPAILLAGE</h1><p><strong>{{orpailleur}}</strong> est autorisé par <strong>{{autorite_locale}}</strong> à exercer l"activité d"orpaillage dans la zone : <strong>{{zone_orpaillage}}</strong>.</p><p>Redevance applicable : <strong>{{redevance_orpaillage}} FCFA</strong>. Autorisation accordée le : <strong>{{date_autorisation}}</strong>.</p></div>`,
  },
  {
    code: 'mine_contrat_laboratoire',
    name: "Contrat de Service d\"Analyse de Laboratoire Minéral",
    category: 'agro_environnement',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de prestation d\"analyses géochimiques et minéralogiques en laboratoire.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'client_labo', label: "Client (société minière)", type: 'text', required: true },
      { key: 'laboratoire', label: "Laboratoire prestataire", type: 'text', required: true },
      { key: 'type_analyse', label: "Type d\"analyses requises", type: 'textarea', required: true },
      { key: 'nombre_echantillons', label: "Nombre d\"échantillons", type: 'text', required: true },
      { key: 'cout_analyse', label: "Coût total des analyses (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE D"ANALYSE DE LABORATOIRE MINÉRAL</h1><p><strong>{{client_labo}}</strong> confie à <strong>{{laboratoire}}</strong> la réalisation des analyses suivantes : {{type_analyse}}.</p><p>Nombre d"échantillons : <strong>{{nombre_echantillons}}</strong>. Coût total : <strong>{{cout_analyse}} FCFA</strong>.</p></div>`,
  },
  {
    code: 'mine_accord_joint_venture',
    name: "Accord de Joint Venture Minier",
    category: 'agro_environnement',
    price: 22000,
    priceMax: 66000,
    description: "Accord de coentreprise (joint venture) pour l\"exploration et l\"exploitation minières conjointes.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'jv_partenaire1', label: "Partenaire 1 (nom et nationalité)", type: 'text', required: true },
      { key: 'jv_partenaire2', label: "Partenaire 2 (nom et nationalité)", type: 'text', required: true },
      { key: 'jv_projet', label: "Projet minier objet du JV", type: 'text', required: true },
      { key: 'jv_participation', label: "Pourcentage de participation de chaque partie", type: 'text', required: true },
      { key: 'jv_gouvernance', label: "Modalités de gouvernance de la JV", type: 'textarea', required: true },
      { key: 'jv_date', label: "Date de constitution du JV", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE JOINT VENTURE MINIER</h1><p><strong>{{jv_partenaire1}}</strong> et <strong>{{jv_partenaire2}}</strong> constituent une joint venture pour le projet : <strong>{{jv_projet}}</strong>.</p><p>Participations : <strong>{{jv_participation}}</strong>.</p><p>Gouvernance : {{jv_gouvernance}}</p><p>Constitué le : <strong>{{jv_date}}</strong>.</p></div>`,
  },
  {
    code: 'mine_rapport_cloture',
    name: "Rapport de Clôture Exploration Minière",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Rapport de clôture d\"une campagne d\"exploration minière remis aux autorités.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'societe_exploration', label: "Société d\"exploration", type: 'text', required: true },
      { key: 'zone_exploree', label: "Zone explorée", type: 'text', required: true },
      { key: 'travaux_realises', label: "Travaux réalisés durant la campagne", type: 'textarea', required: true },
      { key: 'resultats_exploration', label: "Résultats et conclusions", type: 'textarea', required: true },
      { key: 'date_cloture', label: "Date de clôture de la campagne", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE CLÔTURE - EXPLORATION MINIÈRE</h1><p><strong>Société :</strong> {{societe_exploration}}<br/><strong>Zone explorée :</strong> {{zone_exploree}}</p><p><strong>Travaux réalisés :</strong> {{travaux_realises}}</p><p><strong>Résultats et conclusions :</strong> {{resultats_exploration}}</p><p>Campagne clôturée le : <strong>{{date_cloture}}</strong></p><p>Chef de projet : ____________________</p></div>`,
  },

  // ─── ENVIRONNEMENT / DÉVELOPPEMENT DURABLE (25 templates) ──────────────────
  {
    code: 'env_plan_gestion_environnementale',
    name: "Plan de Gestion Environnementale (PGE)",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Plan de Gestion Environnementale et Sociale (PGES) pour un projet industriel ou d\"infrastructure.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'projet_pge', label: "Nom du projet", type: 'text', required: true },
      { key: 'promoteur_pge', label: "Promoteur du projet", type: 'text', required: true },
      { key: 'composantes_environnementales', label: "Composantes environnementales affectées", type: 'textarea', required: true },
      { key: 'mesures_pge', label: "Mesures environnementales prévues", type: 'textarea', required: true },
      { key: 'budget_pge', label: "Budget PGES (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE GESTION ENVIRONNEMENTALE ET SOCIALE (PGES)</h1><p><strong>Projet :</strong> {{projet_pge}}<br/><strong>Promoteur :</strong> {{promoteur_pge}}</p><p><strong>Composantes environnementales affectées :</strong> {{composantes_environnementales}}</p><p><strong>Mesures prévues :</strong> {{mesures_pge}}</p><p><strong>Budget PGES :</strong> {{budget_pge}} FCFA</p></div>`,
  },
  {
    code: 'env_rapport_eie',
    name: "Rapport d\"Évaluation d\"Impact Environnemental (EIE)",
    category: 'agro_environnement',
    price: 22000,
    priceMax: 66000,
    description: "Rapport complet d\"évaluation d\"impact environnemental soumis aux autorités pour validation.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'projet_eie', label: "Projet soumis à l\"EIE", type: 'text', required: true },
      { key: 'maitre_ouvrage', label: "Maître d\"ouvrage", type: 'text', required: true },
      { key: 'consultant_eie', label: "Bureau d\"études consultant", type: 'text', required: true },
      { key: 'impacts_significatifs', label: "Impacts environnementaux significatifs", type: 'textarea', required: true },
      { key: 'plan_surveillance', label: "Plan de surveillance et de suivi", type: 'textarea', required: true },
      { key: 'date_soumission_eie', label: "Date de soumission du rapport", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D"ÉVALUATION D"IMPACT ENVIRONNEMENTAL (EIE)</h1><p><strong>Projet :</strong> {{projet_eie}}<br/><strong>Maître d"ouvrage :</strong> {{maitre_ouvrage}}<br/><strong>Consultant :</strong> {{consultant_eie}}</p><p><strong>Impacts significatifs :</strong> {{impacts_significatifs}}</p><p><strong>Plan de surveillance :</strong> {{plan_surveillance}}</p><p>Soumis le : <strong>{{date_soumission_eie}}</strong></p></div>`,
  },
  {
    code: 'env_accord_compensation_ecologique',
    name: "Accord de Compensation Écologique",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Accord définissant les mesures de compensation pour les atteintes à la biodiversité.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'entreprise_comp', label: "Entreprise redevable de compensation", type: 'text', required: true },
      { key: 'autorite_comp', label: "Autorité environnementale", type: 'text', required: true },
      { key: 'atteintes_biodiversite', label: "Atteintes à la biodiversité constatées", type: 'textarea', required: true },
      { key: 'mesures_compensation', label: "Mesures de compensation retenues", type: 'textarea', required: true },
      { key: 'montant_compensation', label: "Montant de la compensation (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE COMPENSATION ÉCOLOGIQUE</h1><p><strong>{{entreprise_comp}}</strong> s"engage envers <strong>{{autorite_comp}}</strong> à compenser les atteintes suivantes à la biodiversité : {{atteintes_biodiversite}}.</p><p><strong>Mesures de compensation :</strong> {{mesures_compensation}}</p><p><strong>Montant :</strong> {{montant_compensation}} FCFA</p></div>`,
  },
  {
    code: 'env_contrat_dechets_industriels',
    name: "Contrat de Service de Gestion des Déchets Industriels",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Contrat de collecte, transport et traitement des déchets industriels d\"une entreprise.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'generateur_dechets', label: "Entreprise génératrice de déchets", type: 'text', required: true },
      { key: 'prestataire_dechets', label: "Prestataire de gestion des déchets", type: 'text', required: true },
      { key: 'type_dechets', label: "Type et nature des déchets", type: 'text', required: true },
      { key: 'frequence_collecte', label: "Fréquence de collecte", type: 'text', required: true },
      { key: 'cout_service_dechets', label: "Coût mensuel du service (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GESTION DES DÉCHETS INDUSTRIELS</h1><p><strong>{{generateur_dechets}}</strong> confie à <strong>{{prestataire_dechets}}</strong> la gestion de ses déchets : <strong>{{type_dechets}}</strong>.</p><p>Fréquence de collecte : <strong>{{frequence_collecte}}</strong>. Coût mensuel : <strong>{{cout_service_dechets}} FCFA</strong>.</p></div>`,
  },
  {
    code: 'env_accord_eaux_usees',
    name: "Accord de Traitement des Eaux Usées Industrielles",
    category: 'agro_environnement',
    price: 14000,
    priceMax: 42000,
    description: "Accord entre une industrie et un opérateur pour le traitement de ses eaux usées.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'industrie_eau', label: "Entreprise industrielle", type: 'text', required: true },
      { key: 'operateur_eau_usee', label: "Opérateur de traitement des eaux", type: 'text', required: true },
      { key: 'volume_journalier', label: "Volume journalier d\"eaux usées (m3)", type: 'text', required: true },
      { key: 'normes_traitement', label: "Normes de traitement exigées", type: 'textarea', required: true },
      { key: 'cout_traitement_eau', label: "Coût de traitement (FCFA/m3)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRAITEMENT DES EAUX USÉES INDUSTRIELLES</h1><p><strong>{{industrie_eau}}</strong> confie à <strong>{{operateur_eau_usee}}</strong> le traitement de ses eaux usées.</p><p>Volume : <strong>{{volume_journalier}} m3/jour</strong>. Normes : {{normes_traitement}}. Coût : <strong>{{cout_traitement_eau}} FCFA/m3</strong>.</p></div>`,
  },
  {
    code: 'env_contrat_depollution',
    name: "Contrat de Dépollution de Site",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Contrat de prestation de services de dépollution et de réhabilitation d\"un site contaminé.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'proprietaire_site', label: "Propriétaire du site pollué", type: 'text', required: true },
      { key: 'prestataire_depollution', label: "Prestataire de dépollution", type: 'text', required: true },
      { key: 'nature_pollution', label: "Nature et étendue de la pollution", type: 'textarea', required: true },
      { key: 'techniques_depollution', label: "Techniques de dépollution retenues", type: 'textarea', required: true },
      { key: 'cout_depollution', label: "Coût total de la dépollution (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE DÉPOLLUTION DE SITE</h1><p><strong>{{proprietaire_site}}</strong> mandate <strong>{{prestataire_depollution}}</strong> pour la dépollution du site.</p><p><strong>Nature de la pollution :</strong> {{nature_pollution}}</p><p><strong>Techniques retenues :</strong> {{techniques_depollution}}</p><p><strong>Coût :</strong> {{cout_depollution}} FCFA</p></div>`,
  },
  {
    code: 'env_accord_bilan_carbone',
    name: "Accord de Bilan Carbone Entreprise",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Accord de prestation pour la réalisation du bilan des émissions de gaz à effet de serre.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'entreprise_carbone', label: "Entreprise (émettrice)", type: 'text', required: true },
      { key: 'consultant_carbone', label: "Consultant spécialisé carbone", type: 'text', required: true },
      { key: 'perimetre_bilan', label: "Périmètre du bilan (scopes 1, 2, 3)", type: 'text', required: true },
      { key: 'annee_reference', label: "Année de référence du bilan", type: 'text', required: true },
      { key: 'honoraires_carbone', label: "Honoraires de prestation (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE BILAN CARBONE</h1><p><strong>{{entreprise_carbone}}</strong> mandate <strong>{{consultant_carbone}}</strong> pour réaliser son bilan carbone.</p><p>Périmètre : <strong>{{perimetre_bilan}}</strong>. Année de référence : <strong>{{annee_reference}}</strong>. Honoraires : <strong>{{honoraires_carbone}} FCFA</strong>.</p></div>`,
  },
  {
    code: 'env_contrat_conseil_rse',
    name: "Contrat de Service de Conseil RSE",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de mission de conseil en Responsabilité Sociétale des Entreprises (RSE).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'entreprise_rse', label: "Entreprise cliente", type: 'text', required: true },
      { key: 'consultant_rse', label: "Consultant RSE", type: 'text', required: true },
      { key: 'mission_rse', label: "Objet de la mission RSE", type: 'textarea', required: true },
      { key: 'duree_mission_rse', label: "Durée de la mission", type: 'text', required: true },
      { key: 'honoraires_rse', label: "Honoraires (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE CONSEIL RSE</h1><p><strong>{{consultant_rse}}</strong> accompagne <strong>{{entreprise_rse}}</strong> dans la mise en oeuvre de sa démarche RSE : {{mission_rse}}.</p><p>Durée : <strong>{{duree_mission_rse}}</strong>. Honoraires : <strong>{{honoraires_rse}} FCFA</strong>.</p></div>`,
  },
  {
    code: 'env_rapport_developpement_durable',
    name: "Rapport de Développement Durable",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Rapport annuel de développement durable publié par une entreprise africaine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'entreprise_dd', label: "Nom de l\"entreprise", type: 'text', required: true },
      { key: 'annee_rapport_dd', label: "Année du rapport", type: 'text', required: true },
      { key: 'realisations_env', label: "Réalisations environnementales", type: 'textarea', required: true },
      { key: 'realisations_sociales', label: "Réalisations sociales", type: 'textarea', required: true },
      { key: 'objectifs_futurs', label: "Objectifs pour l\"année suivante", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE DÉVELOPPEMENT DURABLE {{annee_rapport_dd}}</h1><p><strong>{{entreprise_dd}}</strong></p><h2>Réalisations environnementales</h2><p>{{realisations_env}}</p><h2>Réalisations sociales</h2><p>{{realisations_sociales}}</p><h2>Objectifs futurs</h2><p>{{objectifs_futurs}}</p><p>Direction Générale : ____________________</p></div>`,
  },
  {
    code: 'env_accord_iso14001',
    name: "Accord de Certification ISO 14001",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Accord de prestation pour l\"accompagnement à la certification ISO 14001 (management environnemental).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'entreprise_iso', label: "Entreprise candidate à la certification", type: 'text', required: true },
      { key: 'organisme_cert', label: "Organisme de certification", type: 'text', required: true },
      { key: 'perimetre_iso', label: "Périmètre de la certification", type: 'text', required: true },
      { key: 'plan_actions_iso', label: "Plan d\"actions pour la certification", type: 'textarea', required: true },
      { key: 'date_audit', label: "Date prévue de l\"audit de certification", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION ISO 14001</h1><p><strong>{{entreprise_iso}}</strong> s"engage avec <strong>{{organisme_cert}}</strong> dans un processus de certification ISO 14001.</p><p>Périmètre : <strong>{{perimetre_iso}}</strong>.</p><p>Plan d"actions : {{plan_actions_iso}}</p><p>Audit de certification prévu le : <strong>{{date_audit}}</strong>.</p></div>`,
  },
  {
    code: 'env_plan_biodiversite',
    name: "Plan de Biodiversité Entreprise",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Plan stratégique d\"entreprise pour la protection et la restauration de la biodiversité.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'entreprise_bio', label: "Entreprise", type: 'text', required: true },
      { key: 'ecosystemes_cibles', label: "Écosystèmes et espèces ciblés", type: 'textarea', required: true },
      { key: 'actions_biodiversite', label: "Actions de protection et restauration", type: 'textarea', required: true },
      { key: 'budget_bio', label: "Budget biodiversité (FCFA)", type: 'text', required: true },
      { key: 'horizon_bio', label: "Horizon du plan (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE BIODIVERSITÉ ENTREPRISE</h1><p><strong>{{entreprise_bio}}</strong> s"engage dans la protection de la biodiversité sur un horizon de <strong>{{horizon_bio}} ans</strong>.</p><p><strong>Écosystèmes ciblés :</strong> {{ecosystemes_cibles}}</p><p><strong>Actions :</strong> {{actions_biodiversite}}</p><p><strong>Budget :</strong> {{budget_bio}} FCFA</p></div>`,
  },
  {
    code: 'env_accord_redd_plus',
    name: "Accord REDD+ (Forêts Carbone)",
    category: 'agro_environnement',
    price: 20000,
    priceMax: 60000,
    description: "Accord REDD+ pour la réduction des émissions liées à la déforestation et la gestion durable des forêts.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'pays_redd', label: "Pays bénéficiaire du programme REDD+", type: 'text', required: true },
      { key: 'bailleur_redd', label: "Bailleur de fonds / partenaire international", type: 'text', required: true },
      { key: 'superficie_foret', label: "Superficie forestière couverte (ha)", type: 'text', required: true },
      { key: 'credits_carbone', label: "Crédits carbone visés (tonnes CO2 eq.)", type: 'text', required: true },
      { key: 'duree_redd', label: "Durée du programme REDD+", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD REDD+ - FORÊTS CARBONE</h1><p><strong>{{pays_redd}}</strong> et <strong>{{bailleur_redd}}</strong> s"engagent dans un programme REDD+ couvrant <strong>{{superficie_foret}} ha</strong> de forêts.</p><p>Crédits carbone visés : <strong>{{credits_carbone}} tonnes CO2 éq.</strong>. Durée : <strong>{{duree_redd}}</strong>.</p></div>`,
  },
  {
    code: 'env_contrat_reforestation',
    name: "Contrat de Reforestation",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat pour la réalisation d\"une campagne de reforestation et de plantation d\"arbres.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'commanditaire_ref', label: "Commanditaire (entreprise ou État)", type: 'text', required: true },
      { key: 'prestataire_ref', label: "Prestataire de reforestation", type: 'text', required: true },
      { key: 'zone_ref', label: "Zone de reforestation", type: 'text', required: true },
      { key: 'nombre_plants', label: "Nombre de plants à mettre en terre", type: 'text', required: true },
      { key: 'cout_reforestation', label: "Coût total (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE REFORESTATION</h1><p><strong>{{commanditaire_ref}}</strong> confie à <strong>{{prestataire_ref}}</strong> la reforestation de la zone : <strong>{{zone_ref}}</strong>.</p><p>Objectif : <strong>{{nombre_plants}} plants</strong>. Coût total : <strong>{{cout_reforestation}} FCFA</strong>.</p></div>`,
  },
  {
    code: 'env_accord_zone_humide',
    name: "Accord de Protection de Zone Humide",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Accord de conservation et de gestion durable d\"une zone humide (marais, mangrove, lagune).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'zone_humide', label: "Nom et localisation de la zone humide", type: 'text', required: true },
      { key: 'gestionnaire_zh', label: "Gestionnaire désigné", type: 'text', required: true },
      { key: 'autorite_zh', label: "Autorité publique partenaire", type: 'text', required: true },
      { key: 'mesures_conservation', label: "Mesures de conservation retenues", type: 'textarea', required: true },
      { key: 'duree_accord_zh', label: "Durée de l\"accord (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PROTECTION DE ZONE HUMIDE</h1><p>La zone humide <strong>{{zone_humide}}</strong> est placée sous la gestion de <strong>{{gestionnaire_zh}}</strong> en partenariat avec <strong>{{autorite_zh}}</strong>.</p><p><strong>Mesures de conservation :</strong> {{mesures_conservation}}</p><p>Durée de l"accord : <strong>{{duree_accord_zh}} ans</strong>.</p></div>`,
  },
  {
    code: 'env_convention_reserve_naturelle',
    name: "Convention de Réserve Naturelle Privée",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Convention de création et de gestion d\"une réserve naturelle privée.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'proprietaire_reserve', label: "Propriétaire foncier", type: 'text', required: true },
      { key: 'autorite_reserve', label: "Ministère de l\"Environnement", type: 'text', required: true },
      { key: 'nom_reserve', label: "Nom de la réserve naturelle", type: 'text', required: true },
      { key: 'superficie_reserve', label: "Superficie (ha)", type: 'text', required: true },
      { key: 'regles_gestion', label: "Règles de gestion de la réserve", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE RÉSERVE NATURELLE PRIVÉE</h1><p><strong>{{proprietaire_reserve}}</strong> et <strong>{{autorite_reserve}}</strong> conviennent de la création de la réserve naturelle <strong>{{nom_reserve}}</strong> sur une superficie de <strong>{{superficie_reserve}} ha</strong>.</p><p><strong>Règles de gestion :</strong> {{regles_gestion}}</p></div>`,
  },
  {
    code: 'env_accord_fsc',
    name: "Accord de Certification FSC (Forêts)",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Accord pour l\"obtention de la certification FSC (Forest Stewardship Council) d\"une exploitation forestière.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'exploitant_fsc', label: "Exploitant forestier candidat", type: 'text', required: true },
      { key: 'cert_fsc', label: "Organisme certificateur FSC", type: 'text', required: true },
      { key: 'foret_fsc', label: "Unité forestière de gestion (UFG)", type: 'text', required: true },
      { key: 'superficie_fsc', label: "Superficie certifiée (ha)", type: 'text', required: true },
      { key: 'date_audit_fsc', label: "Date de l\"audit FSC", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CERTIFICATION FSC</h1><p><strong>{{exploitant_fsc}}</strong> engage le processus de certification FSC de l"unité forestière <strong>{{foret_fsc}}</strong> ({{superficie_fsc}} ha) avec l"organisme <strong>{{cert_fsc}}</strong>.</p><p>Audit prévu le : <strong>{{date_audit_fsc}}</strong>.</p></div>`,
  },
  {
    code: 'env_contrat_recyclage',
    name: "Contrat de Service de Recyclage",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de collecte et de recyclage des déchets recyclables d\"une entreprise.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'producteur_recyclage', label: "Producteur de déchets recyclables", type: 'text', required: true },
      { key: 'recycleur', label: "Société de recyclage", type: 'text', required: true },
      { key: 'matieres_recyclees', label: "Matières recyclables concernées", type: 'text', required: true },
      { key: 'volume_recyclage', label: "Volume mensuel estimé (tonnes)", type: 'text', required: true },
      { key: 'tarif_recyclage', label: "Tarif convenu (FCFA/tonne)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE SERVICE DE RECYCLAGE</h1><p><strong>{{producteur_recyclage}}</strong> confie à <strong>{{recycleur}}</strong> le recyclage de ses déchets : <strong>{{matieres_recyclees}}</strong>.</p><p>Volume mensuel : <strong>{{volume_recyclage}} tonnes</strong>. Tarif : <strong>{{tarif_recyclage}} FCFA/tonne</strong>.</p></div>`,
  },
  {
    code: 'env_accord_deee',
    name: "Accord de Gestion des Déchets Électroniques (DEEE)",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Accord de collecte et de traitement des déchets d\"équipements électriques et électroniques (DEEE).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'generateur_deee', label: "Générateur de DEEE (entreprise)", type: 'text', required: true },
      { key: 'collecteur_deee', label: "Collecteur / traiteur agréé DEEE", type: 'text', required: true },
      { key: 'types_equipements', label: "Types d\"équipements concernés", type: 'text', required: true },
      { key: 'volume_annuel_deee', label: "Volume annuel estimé (kg)", type: 'text', required: true },
      { key: 'cout_deee', label: "Coût de traitement (FCFA/kg)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DES DÉCHETS ÉLECTRONIQUES (DEEE)</h1><p><strong>{{generateur_deee}}</strong> confie à <strong>{{collecteur_deee}}</strong> le traitement de ses DEEE : <strong>{{types_equipements}}</strong>.</p><p>Volume annuel : <strong>{{volume_annuel_deee}} kg</strong>. Coût : <strong>{{cout_deee}} FCFA/kg</strong>.</p></div>`,
  },
  {
    code: 'env_plan_produits_chimiques',
    name: "Plan de Gestion des Produits Chimiques",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Plan de gestion sécuritaire des produits chimiques dangereux dans une entreprise.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'entreprise_chimiques', label: "Entreprise concernée", type: 'text', required: true },
      { key: 'liste_produits', label: "Liste des produits chimiques utilisés", type: 'textarea', required: true },
      { key: 'mesures_stockage', label: "Mesures de stockage et de manutention", type: 'textarea', required: true },
      { key: 'responsable_chimiques', label: "Responsable de la gestion des produits chimiques", type: 'text', required: true },
      { key: 'date_plan_chimiques', label: "Date d\"élaboration du plan", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE GESTION DES PRODUITS CHIMIQUES</h1><p><strong>{{entreprise_chimiques}}</strong> - Responsable : <strong>{{responsable_chimiques}}</strong></p><p><strong>Produits chimiques utilisés :</strong> {{liste_produits}}</p><p><strong>Mesures de stockage et manutention :</strong> {{mesures_stockage}}</p><p>Plan établi le : <strong>{{date_plan_chimiques}}</strong></p></div>`,
  },
  {
    code: 'env_accord_tracabilite',
    name: "Accord de Traçabilité Environnementale",
    category: 'agro_environnement',
    price: 12000,
    priceMax: 36000,
    description: "Accord pour la mise en place d\"un système de traçabilité des produits selon des critères environnementaux.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'entreprise_trace', label: "Entreprise concernée", type: 'text', required: true },
      { key: 'partenaire_trace', label: "Partenaire de traçabilité / acheteur", type: 'text', required: true },
      { key: 'produits_traces', label: "Produits soumis à la traçabilité", type: 'text', required: true },
      { key: 'criteres_env', label: "Critères environnementaux de traçabilité", type: 'textarea', required: true },
      { key: 'systeme_trace', label: "Système de traçabilité utilisé", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRAÇABILITÉ ENVIRONNEMENTALE</h1><p><strong>{{entreprise_trace}}</strong> et <strong>{{partenaire_trace}}</strong> conviennent d"un système de traçabilité pour : <strong>{{produits_traces}}</strong>.</p><p><strong>Critères environnementaux :</strong> {{criteres_env}}</p><p><strong>Système retenu :</strong> {{systeme_trace}}</p></div>`,
  },
  {
    code: 'env_contrat_audit_env',
    name: "Contrat de Service d\"Audit Environnemental",
    category: 'agro_environnement',
    price: 15000,
    priceMax: 45000,
    description: "Contrat de réalisation d\"un audit environnemental indépendant d\"une entreprise.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'client_audit_env', label: "Entreprise auditée", type: 'text', required: true },
      { key: 'auditeur_env', label: "Cabinet d\"audit environnemental", type: 'text', required: true },
      { key: 'perimetre_audit', label: "Périmètre de l\"audit", type: 'textarea', required: true },
      { key: 'honoraires_audit_env', label: "Honoraires d\"audit (FCFA)", type: 'text', required: true },
      { key: 'date_audit_env', label: "Date prévue de l\"audit", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D"AUDIT ENVIRONNEMENTAL</h1><p><strong>{{client_audit_env}}</strong> mandate <strong>{{auditeur_env}}</strong> pour réaliser un audit environnemental.</p><p><strong>Périmètre :</strong> {{perimetre_audit}}</p><p>Honoraires : <strong>{{honoraires_audit_env}} FCFA</strong>. Date d"audit : <strong>{{date_audit_env}}</strong>.</p></div>`,
  },
  {
    code: 'env_convention_zone_tampon',
    name: "Convention de Zone Tampon Industrielle",
    category: 'agro_environnement',
    price: 14000,
    priceMax: 42000,
    description: "Convention définissant et gérant une zone tampon entre un site industriel et les zones habitées.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'industrie_tampon', label: "Entreprise industrielle", type: 'text', required: true },
      { key: 'commune_tampon', label: "Commune / collectivité locale", type: 'text', required: true },
      { key: 'zone_tampon_desc', label: "Description de la zone tampon", type: 'textarea', required: true },
      { key: 'contraintes_tampon', label: "Contraintes d\"aménagement de la zone", type: 'textarea', required: true },
      { key: 'duree_conv_tampon', label: "Durée de la convention (années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONVENTION DE ZONE TAMPON INDUSTRIELLE</h1><p><strong>{{industrie_tampon}}</strong> et la commune de <strong>{{commune_tampon}}</strong> définissent une zone tampon.</p><p><strong>Description :</strong> {{zone_tampon_desc}}</p><p><strong>Contraintes d"aménagement :</strong> {{contraintes_tampon}}</p><p>Durée : <strong>{{duree_conv_tampon}} ans</strong></p></div>`,
  },
  {
    code: 'env_accord_nuisances_sonores',
    name: "Accord de Gestion des Nuisances Sonores",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Accord de gestion et de réduction des nuisances sonores d\"un site industriel.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'emetteur_bruit', label: "Source des nuisances (entreprise)", type: 'text', required: true },
      { key: 'riverains_repr', label: "Représentant des riverains / autorité", type: 'text', required: true },
      { key: 'niveaux_sonores', label: "Niveaux sonores actuels et tolérés (dB)", type: 'text', required: true },
      { key: 'mesures_reduction', label: "Mesures de réduction des nuisances", type: 'textarea', required: true },
      { key: 'echeancier_bruit', label: "Échéancier de mise en oeuvre", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION DES NUISANCES SONORES</h1><p><strong>{{emetteur_bruit}}</strong> s"engage envers <strong>{{riverains_repr}}</strong> à réduire les nuisances sonores.</p><p>Niveaux : <strong>{{niveaux_sonores}}</strong>.</p><p><strong>Mesures :</strong> {{mesures_reduction}}</p><p>Échéancier : <strong>{{echeancier_bruit}}</strong></p></div>`,
  },
  {
    code: 'env_rapport_gri',
    name: "Rapport GRI (Global Reporting Initiative)",
    category: 'agro_environnement',
    price: 18000,
    priceMax: 54000,
    description: "Rapport de performance de durabilité conforme aux standards GRI pour une entreprise africaine.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'entreprise_gri', label: "Nom de l\"entreprise", type: 'text', required: true },
      { key: 'annee_gri', label: "Année de reporting", type: 'text', required: true },
      { key: 'standard_gri', label: "Standard GRI appliqué (ex. GRI 2021)", type: 'text', required: true },
      { key: 'indicateurs_env_gri', label: "Indicateurs environnementaux clés", type: 'textarea', required: true },
      { key: 'indicateurs_soc_gri', label: "Indicateurs sociaux clés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT GRI - {{entreprise_gri}} - {{annee_gri}}</h1><p><strong>Standard appliqué :</strong> {{standard_gri}}</p><h2>Indicateurs environnementaux</h2><p>{{indicateurs_env_gri}}</p><h2>Indicateurs sociaux</h2><p>{{indicateurs_soc_gri}}</p><p>Directeur Développement Durable : ____________________</p></div>`,
  },
  {
    code: 'env_charte_rse_afrique',
    name: "Charte RSE Afrique Durable",
    category: 'agro_environnement',
    price: 10000,
    priceMax: 30000,
    description: "Charte d\"engagement RSE adaptée au contexte africain et aux enjeux du développement durable.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'entreprise_charte', label: "Nom de l\"entreprise signataire", type: 'text', required: true },
      { key: 'secteur_charte', label: "Secteur d\"activité", type: 'text', required: true },
      { key: 'engagements_charte', label: "Engagements RSE pris par l\"entreprise", type: 'textarea', required: true },
      { key: 'parties_prenantes', label: "Parties prenantes associées à la charte", type: 'text', required: true },
      { key: 'date_charte', label: "Date de signature de la charte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE RSE AFRIQUE DURABLE</h1><p>Nous, <strong>{{entreprise_charte}}</strong>, acteur du secteur <strong>{{secteur_charte}}</strong>, prenons les engagements suivants en faveur du développement durable et de la responsabilité sociale en Afrique :</p><p>{{engagements_charte}}</p><p>Parties prenantes associées : <strong>{{parties_prenantes}}</strong></p><p>Fait le <strong>{{date_charte}}</strong>.</p><p>Le Directeur Général : ____________________</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 36b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
