import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  {
    code: 'qhse2_plan_prevention_risques',
    name: "Plan de Prévention des Risques Professionnels",
    category: 'btp_construction',
    price: 8000,
    priceMax: 24000,
    description: "Document structuré de prévention des risques professionnels conforme aux exigences OHADA et réglementations nationales.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'raison_sociale', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'date_elaboration', label: "Date d'élaboration", type: 'date', required: true },
      { key: 'responsable_securite', label: "Responsable sécurité", type: 'text', required: true },
      { key: 'description_risques', label: "Description des risques identifiés", type: 'textarea', required: true },
      { key: 'mesures_prevention', label: "Mesures de prévention retenues", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE PRÉVENTION DES RISQUES PROFESSIONNELS</h1><p><strong>Entreprise :</strong> {{raison_sociale}}</p><p><strong>Date :</strong> {{date_elaboration}}</p><p><strong>Responsable sécurité :</strong> {{responsable_securite}}</p><h2>1. Risques identifiés</h2><p>{{description_risques}}</p><h2>2. Mesures de prévention</h2><p>{{mesures_prevention}}</p></div>`,
  },
  {
    code: 'qhse2_duer',
    name: "Document Unique d'Évaluation des Risques (DUER)",
    category: 'btp_construction',
    price: 10000,
    priceMax: 30000,
    description: "Document unique d'évaluation des risques professionnels (DUER) conforme à la législation du travail en Afrique francophone.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'entreprise', label: "Nom de l'entreprise", type: 'text', required: true },
      { key: 'date_mise_a_jour', label: "Date de mise à jour", type: 'date', required: true },
      { key: 'unite_travail', label: "Unité de travail concernée", type: 'text', required: true },
      { key: 'dangers_identifies', label: "Dangers identifiés", type: 'textarea', required: true },
      { key: 'niveau_risque', label: "Niveau de risque et criticité", type: 'textarea', required: true },
      { key: 'actions_correctives', label: "Actions correctives planifiées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>DOCUMENT UNIQUE D'ÉVALUATION DES RISQUES (DUER)</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Unité de travail :</strong> {{unite_travail}}</p><p><strong>Date de mise à jour :</strong> {{date_mise_a_jour}}</p><h2>Dangers identifiés</h2><p>{{dangers_identifies}}</p><h2>Niveau de risque</h2><p>{{niveau_risque}}</p><h2>Actions correctives</h2><p>{{actions_correctives}}</p></div>`,
  },
  {
    code: 'qhse2_registre_accidents',
    name: "Registre des Accidents du Travail",
    category: 'btp_construction',
    price: 5000,
    priceMax: 14000,
    description: "Registre légal de consignation des accidents du travail et maladies professionnelles selon le Code du travail OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'entreprise', label: "Raison sociale", type: 'text', required: true },
      { key: 'annee_registre', label: "Année du registre", type: 'text', required: true },
      { key: 'responsable_rh', label: "Responsable RH/HSE", type: 'text', required: true },
      { key: 'observations', label: "Observations générales", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>REGISTRE DES ACCIDENTS DU TRAVAIL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee_registre}}</p><p><strong>Tenu par :</strong> {{responsable_rh}}</p><table border="1" style="width:100%"><thead><tr><th>Date</th><th>Salarié</th><th>Nature accident</th><th>Arrêt (j)</th><th>Gravité</th></tr></thead><tbody><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table><h2>Observations</h2><p>{{observations}}</p></div>`,
  },
  {
    code: 'qhse2_rapport_analyse_accident',
    name: "Rapport d'Analyse d'Accident du Travail",
    category: 'btp_construction',
    price: 7000,
    priceMax: 20000,
    description: "Rapport structuré d'analyse approfondie d'un accident du travail avec méthode des 5 Pourquoi et arbre des causes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accident', label: "Date de l'accident", type: 'date', required: true },
      { key: 'victime', label: "Nom de la victime", type: 'text', required: true },
      { key: 'description_accident', label: "Description de l'accident", type: 'textarea', required: true },
      { key: 'causes_identifiees', label: "Causes identifiées (arbre des causes)", type: 'textarea', required: true },
      { key: 'actions_preventives', label: "Actions préventives recommandées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'ANALYSE D'ACCIDENT DU TRAVAIL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date de l'accident :</strong> {{date_accident}}</p><p><strong>Victime :</strong> {{victime}}</p><h2>Description de l'accident</h2><p>{{description_accident}}</p><h2>Analyse des causes</h2><p>{{causes_identifiees}}</p><h2>Actions préventives</h2><p>{{actions_preventives}}</p></div>`,
  },
  {
    code: 'qhse2_fiche_securite_poste',
    name: "Fiche de Sécurité au Poste de Travail",
    category: 'btp_construction',
    price: 4000,
    priceMax: 12000,
    description: "Fiche individuelle de sécurité décrivant les risques et consignes de sécurité propres à chaque poste de travail.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'intitule_poste', label: "Intitulé du poste", type: 'text', required: true },
      { key: 'departement', label: "Département / Service", type: 'text', required: true },
      { key: 'risques_specifiques', label: "Risques spécifiques au poste", type: 'textarea', required: true },
      { key: 'epi_obligatoires', label: "EPI obligatoires", type: 'textarea', required: true },
      { key: 'consignes_urgence', label: "Consignes d'urgence", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE SÉCURITÉ AU POSTE DE TRAVAIL</h1><p><strong>Poste :</strong> {{intitule_poste}}</p><p><strong>Département :</strong> {{departement}}</p><h2>Risques spécifiques</h2><p>{{risques_specifiques}}</p><h2>EPI obligatoires</h2><p>{{epi_obligatoires}}</p><h2>Consignes d'urgence</h2><p>{{consignes_urgence}}</p></div>`,
  },
  {
    code: 'qhse2_plan_urgence_industriel',
    name: "Plan d'Urgence Industriel",
    category: 'btp_construction',
    price: 12000,
    priceMax: 36000,
    description: "Plan d'urgence industriel complet définissant les procédures d'intervention en cas de sinistre grave sur site industriel.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'site_industriel', label: "Nom du site industriel", type: 'text', required: true },
      { key: 'date_elaboration', label: "Date d'élaboration", type: 'date', required: true },
      { key: 'directeur_site', label: "Directeur du site", type: 'text', required: true },
      { key: 'scenarii_accidentels', label: "Scénarii accidentels couverts", type: 'textarea', required: true },
      { key: 'chaine_alerte', label: "Chaîne d'alerte et contacts d'urgence", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D'URGENCE INDUSTRIEL</h1><p><strong>Site :</strong> {{site_industriel}}</p><p><strong>Directeur :</strong> {{directeur_site}}</p><p><strong>Date :</strong> {{date_elaboration}}</p><h2>Scénarii accidentels</h2><p>{{scenarii_accidentels}}</p><h2>Chaîne d'alerte</h2><p>{{chaine_alerte}}</p></div>`,
  },
  {
    code: 'qhse2_protocole_epi',
    name: "Protocole de Port des EPI",
    category: 'btp_construction',
    price: 4500,
    priceMax: 13000,
    description: "Protocole définissant les règles de mise à disposition, port obligatoire et entretien des équipements de protection individuelle.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_application', label: "Date d'application", type: 'date', required: true },
      { key: 'liste_epi', label: "Liste des EPI et postes concernés", type: 'textarea', required: true },
      { key: 'regles_entretien', label: "Règles d'entretien et de remplacement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROTOCOLE DE PORT DES ÉQUIPEMENTS DE PROTECTION INDIVIDUELLE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>En vigueur depuis :</strong> {{date_application}}</p><h2>EPI et postes concernés</h2><p>{{liste_epi}}</p><h2>Entretien et remplacement</h2><p>{{regles_entretien}}</p></div>`,
  },
  {
    code: 'qhse2_rapport_inspection_securite',
    name: "Rapport d'Inspection Sécurité",
    category: 'btp_construction',
    price: 6000,
    priceMax: 18000,
    description: "Rapport périodique d'inspection sécurité du chantier ou de l'établissement avec grille de contrôle et plan d'action.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'site_inspecte', label: "Site inspecté", type: 'text', required: true },
      { key: 'date_inspection', label: "Date d'inspection", type: 'date', required: true },
      { key: 'inspecteur', label: "Nom de l'inspecteur", type: 'text', required: true },
      { key: 'constats', label: "Constats et non-conformités relevés", type: 'textarea', required: true },
      { key: 'recommandations', label: "Recommandations et délais", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'INSPECTION SÉCURITÉ</h1><p><strong>Site :</strong> {{site_inspecte}}</p><p><strong>Date :</strong> {{date_inspection}}</p><p><strong>Inspecteur :</strong> {{inspecteur}}</p><h2>Constats et non-conformités</h2><p>{{constats}}</p><h2>Recommandations</h2><p>{{recommandations}}</p></div>`,
  },
  {
    code: 'qhse2_rapport_audit_qhse',
    name: "Rapport d'Audit QHSE",
    category: 'btp_construction',
    price: 14000,
    priceMax: 42000,
    description: "Rapport complet d'audit Qualité Hygiène Sécurité Environnement selon les référentiels ISO 45001 et ISO 14001 adaptés au contexte ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'organisme_audite', label: "Organisme audité", type: 'text', required: true },
      { key: 'date_audit', label: "Date de l'audit", type: 'date', required: true },
      { key: 'auditeur_principal', label: "Auditeur principal", type: 'text', required: true },
      { key: 'perimetre_audit', label: "Périmètre de l'audit", type: 'textarea', required: true },
      { key: 'points_forts', label: "Points forts constatés", type: 'textarea', required: true },
      { key: 'ecarts_constates', label: "Écarts et non-conformités", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'AUDIT QHSE</h1><p><strong>Organisme :</strong> {{organisme_audite}}</p><p><strong>Date :</strong> {{date_audit}}</p><p><strong>Auditeur :</strong> {{auditeur_principal}}</p><h2>Périmètre</h2><p>{{perimetre_audit}}</p><h2>Points forts</h2><p>{{points_forts}}</p><h2>Écarts et non-conformités</h2><p>{{ecarts_constates}}</p></div>`,
  },
  {
    code: 'qhse2_plan_amelioration_continue',
    name: "Plan d'Amélioration Continue QHSE",
    category: 'btp_construction',
    price: 9000,
    priceMax: 27000,
    description: "Plan d'amélioration continue QHSE structuré selon la roue de Deming (PDCA) pour la mise en oeuvre d'une démarche d'excellence.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'periode', label: "Période couverte", type: 'text', required: true },
      { key: 'objectifs_qhse', label: "Objectifs QHSE de la période", type: 'textarea', required: true },
      { key: 'actions_planifiees', label: "Actions planifiées (PDCA)", type: 'textarea', required: true },
      { key: 'indicateurs_suivi', label: "Indicateurs de suivi", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D'AMÉLIORATION CONTINUE QHSE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Période :</strong> {{periode}}</p><h2>Objectifs QHSE</h2><p>{{objectifs_qhse}}</p><h2>Actions planifiées</h2><p>{{actions_planifiees}}</p><h2>Indicateurs de suivi</h2><p>{{indicateurs_suivi}}</p></div>`,
  },
  {
    code: 'qhse2_gestion_produits_chimiques',
    name: "Procédure de Gestion des Produits Chimiques",
    category: 'btp_construction',
    price: 7500,
    priceMax: 22000,
    description: "Procédure encadrant le stockage, la manipulation, l'étiquetage et l'élimination des produits chimiques dangereux sur site.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_application', label: "Date d'application", type: 'date', required: true },
      { key: 'liste_produits', label: "Liste des produits chimiques concernés", type: 'textarea', required: true },
      { key: 'regles_stockage', label: "Règles de stockage et compatibilité", type: 'textarea', required: true },
      { key: 'procedure_elimination', label: "Procédure d'élimination des déchets", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROCÉDURE DE GESTION DES PRODUITS CHIMIQUES</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>En vigueur depuis :</strong> {{date_application}}</p><h2>Produits concernés</h2><p>{{liste_produits}}</p><h2>Règles de stockage</h2><p>{{regles_stockage}}</p><h2>Élimination des déchets</h2><p>{{procedure_elimination}}</p></div>`,
  },
  {
    code: 'qhse2_fds',
    name: "Fiche de Données de Sécurité (FDS)",
    category: 'btp_construction',
    price: 5000,
    priceMax: 15000,
    description: "Fiche de données de sécurité (FDS) conforme au règlement CLP pour les produits chimiques utilisés en milieu industriel et BTP.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'nom_produit', label: "Nom du produit", type: 'text', required: true },
      { key: 'fabricant', label: "Fabricant / fournisseur", type: 'text', required: true },
      { key: 'composition', label: "Composition et informations sur les composants", type: 'textarea', required: true },
      { key: 'premiers_secours', label: "Premiers secours en cas d'exposition", type: 'textarea', required: true },
      { key: 'stockage_manipulation', label: "Conditions de stockage et manipulation", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>FICHE DE DONNÉES DE SÉCURITÉ (FDS)</h1><p><strong>Produit :</strong> {{nom_produit}}</p><p><strong>Fabricant :</strong> {{fabricant}}</p><h2>Composition</h2><p>{{composition}}</p><h2>Premiers secours</h2><p>{{premiers_secours}}</p><h2>Stockage et manipulation</h2><p>{{stockage_manipulation}}</p></div>`,
  },
  {
    code: 'qhse2_registre_formations_securite',
    name: "Registre des Formations Sécurité",
    category: 'btp_construction',
    price: 4000,
    priceMax: 11000,
    description: "Registre officiel de suivi des formations sécurité dispensées aux salariés, conforme aux exigences légales en Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee', label: "Année", type: 'text', required: true },
      { key: 'responsable_formation', label: "Responsable formation", type: 'text', required: true },
      { key: 'observations', label: "Observations", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>REGISTRE DES FORMATIONS SÉCURITÉ</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee}}</p><p><strong>Responsable :</strong> {{responsable_formation}}</p><table border="1" style="width:100%"><thead><tr><th>Date</th><th>Thème</th><th>Formateur</th><th>Participants</th><th>Durée (h)</th></tr></thead><tbody><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table><p>{{observations}}</p></div>`,
  },
  {
    code: 'qhse2_permis_travail_hauteur',
    name: "Permis de Travail en Hauteur",
    category: 'btp_construction',
    price: 6000,
    priceMax: 18000,
    description: "Permis de travail en hauteur à remplir avant toute intervention à plus de 2 mètres, conforme aux normes BTP en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'chantier', label: "Chantier / Site", type: 'text', required: true },
      { key: 'date_intervention', label: "Date d'intervention", type: 'date', required: true },
      { key: 'intervenants', label: "Nom des intervenants", type: 'text', required: true },
      { key: 'description_travaux', label: "Description des travaux", type: 'textarea', required: true },
      { key: 'equipements_utilises', label: "Équipements de protection utilisés", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PERMIS DE TRAVAIL EN HAUTEUR</h1><p><strong>Chantier :</strong> {{chantier}}</p><p><strong>Date :</strong> {{date_intervention}}</p><p><strong>Intervenants :</strong> {{intervenants}}</p><h2>Description des travaux</h2><p>{{description_travaux}}</p><h2>Équipements de protection</h2><p>{{equipements_utilises}}</p><p style="margin-top:20px"><strong>Visa du responsable sécurité :</strong> ___________________</p></div>`,
  },
  {
    code: 'qhse2_permis_feu',
    name: "Permis de Feu",
    category: 'btp_construction',
    price: 5500,
    priceMax: 16000,
    description: "Permis de feu autorisant les travaux par points chauds (soudure, meulage, découpe) sur chantier ou site industriel.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'site', label: "Site / Chantier", type: 'text', required: true },
      { key: 'date_validite', label: "Date de validité", type: 'date', required: true },
      { key: 'nature_travaux', label: "Nature des travaux par points chauds", type: 'textarea', required: true },
      { key: 'mesures_protection', label: "Mesures de protection incendie mises en place", type: 'textarea', required: true },
      { key: 'responsable_chantier', label: "Responsable de chantier", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>PERMIS DE FEU</h1><p><strong>Site :</strong> {{site}}</p><p><strong>Valable le :</strong> {{date_validite}}</p><p><strong>Responsable chantier :</strong> {{responsable_chantier}}</p><h2>Nature des travaux</h2><p>{{nature_travaux}}</p><h2>Mesures de protection incendie</h2><p>{{mesures_protection}}</p><p style="margin-top:20px"><strong>Autorisation délivrée par :</strong> ___________________</p></div>`,
  },
  {
    code: 'qhse2_permis_espace_confine',
    name: "Permis de Travail en Espace Confiné",
    category: 'btp_construction',
    price: 7000,
    priceMax: 21000,
    description: "Permis de travail en espace confiné (fosse, citerne, galerie) avec mesures atmosphériques et procédures de secours.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'site', label: "Site / Installation", type: 'text', required: true },
      { key: 'date_intervention', label: "Date d'intervention", type: 'date', required: true },
      { key: 'description_espace', label: "Description de l'espace confiné", type: 'textarea', required: true },
      { key: 'mesures_atmospheriques', label: "Résultats mesures atmosphériques (O2, CO, H2S)", type: 'textarea', required: true },
      { key: 'procedure_sauvetage', label: "Procédure de sauvetage et évacuation", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PERMIS DE TRAVAIL EN ESPACE CONFINÉ</h1><p><strong>Site :</strong> {{site}}</p><p><strong>Date :</strong> {{date_intervention}}</p><h2>Description de l'espace confiné</h2><p>{{description_espace}}</p><h2>Mesures atmosphériques</h2><p>{{mesures_atmospheriques}}</p><h2>Procédure de sauvetage</h2><p>{{procedure_sauvetage}}</p><p style="margin-top:20px"><strong>Visa du responsable HSE :</strong> ___________________</p></div>`,
  },
  {
    code: 'qhse2_registre_presqu_accident',
    name: "Registre des Incidents de Presqu'Accident",
    category: 'btp_construction',
    price: 4500,
    priceMax: 13000,
    description: "Registre de signalement et suivi des presqu'accidents et situations dangereuses pour alimenter la démarche préventive.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee', label: "Année", type: 'text', required: true },
      { key: 'responsable_hse', label: "Responsable HSE", type: 'text', required: true },
      { key: 'politique_signalement', label: "Politique de signalement encouragée", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>REGISTRE DES INCIDENTS ET PRESQU'ACCIDENTS</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee}}</p><p><strong>Responsable HSE :</strong> {{responsable_hse}}</p><p>{{politique_signalement}}</p><table border="1" style="width:100%"><thead><tr><th>Date</th><th>Lieu</th><th>Description</th><th>Signalant</th><th>Action corrective</th></tr></thead><tbody><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table></div>`,
  },
  {
    code: 'qhse2_plan_formation_securite',
    name: "Plan de Formation Sécurité Annuel",
    category: 'btp_construction',
    price: 8000,
    priceMax: 24000,
    description: "Plan annuel de formation à la sécurité identifiant les besoins, les actions de formation et le budget prévisionnel.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee', label: "Année", type: 'text', required: true },
      { key: 'budget_formation', label: "Budget prévisionnel de formation (FCFA)", type: 'text', required: true },
      { key: 'besoins_identifies', label: "Besoins en formation identifiés", type: 'textarea', required: true },
      { key: 'calendrier_actions', label: "Calendrier des actions de formation", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE FORMATION SÉCURITÉ ANNUEL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee}}</p><p><strong>Budget :</strong> {{budget_formation}} FCFA</p><h2>Besoins identifiés</h2><p>{{besoins_identifies}}</p><h2>Calendrier des actions</h2><p>{{calendrier_actions}}</p></div>`,
  },
  {
    code: 'qhse2_rapport_mensuel_accidents',
    name: "Rapport Mensuel Accidents / Incidents",
    category: 'btp_construction',
    price: 5000,
    priceMax: 14000,
    description: "Rapport mensuel de synthèse des accidents et incidents avec calcul des taux de fréquence et de gravité OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'mois_annee', label: "Mois et année", type: 'text', required: true },
      { key: 'responsable_hse', label: "Responsable HSE", type: 'text', required: true },
      { key: 'synthese_accidents', label: "Synthèse des accidents et incidents du mois", type: 'textarea', required: true },
      { key: 'indicateurs_calcules', label: "Indicateurs calculés (TF, TG, IF)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT MENSUEL ACCIDENTS / INCIDENTS</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Période :</strong> {{mois_annee}}</p><p><strong>Responsable HSE :</strong> {{responsable_hse}}</p><h2>Synthèse du mois</h2><p>{{synthese_accidents}}</p><h2>Indicateurs</h2><p>{{indicateurs_calcules}}</p></div>`,
  },
  {
    code: 'qhse2_tableau_bord_securite',
    name: "Tableau de Bord Sécurité",
    category: 'btp_construction',
    price: 7000,
    priceMax: 21000,
    description: "Tableau de bord HSE périodique présentant les indicateurs clés de performance sécurité pour la direction et le CHSCT.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'periode', label: "Période de reporting", type: 'text', required: true },
      { key: 'kpi_securite', label: "KPI sécurité (TF, TG, nombre accidents)", type: 'textarea', required: true },
      { key: 'tendances', label: "Tendances et comparaison période précédente", type: 'textarea', required: true },
      { key: 'actions_prioritaires', label: "Actions prioritaires à mener", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>TABLEAU DE BORD SÉCURITÉ</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Période :</strong> {{periode}}</p><h2>Indicateurs clés</h2><p>{{kpi_securite}}</p><h2>Tendances</h2><p>{{tendances}}</p><h2>Actions prioritaires</h2><p>{{actions_prioritaires}}</p></div>`,
  },
  {
    code: 'qhse2_charte_securite_chantier',
    name: "Charte Sécurité Chantier",
    category: 'btp_construction',
    price: 5000,
    priceMax: 15000,
    description: "Charte sécurité affichée sur chantier définissant les règles d'or et engagements de toutes les parties prenantes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'nom_chantier', label: "Nom du chantier", type: 'text', required: true },
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage", type: 'text', required: true },
      { key: 'entreprise_principale', label: "Entreprise principale", type: 'text', required: true },
      { key: 'regles_or', label: "Les 10 règles d'or sécurité du chantier", type: 'textarea', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE SÉCURITÉ CHANTIER</h1><p><strong>Chantier :</strong> {{nom_chantier}}</p><p><strong>Maître d'ouvrage :</strong> {{maitre_ouvrage}}</p><p><strong>Entreprise :</strong> {{entreprise_principale}}</p><h2>Les règles d'or de notre chantier</h2><p>{{regles_or}}</p><p><strong>Signé le :</strong> {{date_signature}}</p></div>`,
  },
  {
    code: 'qhse2_protocole_secourisme',
    name: "Protocole de Secourisme",
    category: 'btp_construction',
    price: 5500,
    priceMax: 16000,
    description: "Protocole de secourisme définissant les procédures de premiers secours, la localisation des trousses et les contacts d'urgence.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise / Site", type: 'text', required: true },
      { key: 'date_mise_a_jour', label: "Date de mise à jour", type: 'date', required: true },
      { key: 'sauveteurs_secouristes', label: "Liste des sauveteurs secouristes du travail (SST)", type: 'textarea', required: true },
      { key: 'contacts_urgence', label: "Numéros d'urgence (SAMU, pompiers, médecin du travail)", type: 'textarea', required: true },
      { key: 'localisation_materiel', label: "Localisation du matériel de premiers secours", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PROTOCOLE DE SECOURISME</h1><p><strong>Site :</strong> {{entreprise}}</p><p><strong>Mis à jour le :</strong> {{date_mise_a_jour}}</p><h2>Sauveteurs secouristes (SST)</h2><p>{{sauveteurs_secouristes}}</p><h2>Contacts d'urgence</h2><p>{{contacts_urgence}}</p><h2>Matériel de secours</h2><p>{{localisation_materiel}}</p></div>`,
  },
  {
    code: 'qhse2_contrat_medecin_travail',
    name: "Contrat Médecin du Travail",
    category: 'btp_construction',
    price: 10000,
    priceMax: 30000,
    description: "Contrat de prestation de service médecin du travail conforme au Code du travail ivoirien et aux exigences de la CNPS.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'medecin_travail', label: "Médecin du travail (nom et qualification)", type: 'text', required: true },
      { key: 'date_contrat', label: "Date du contrat", type: 'date', required: true },
      { key: 'missions', label: "Missions confiées au médecin du travail", type: 'textarea', required: true },
      { key: 'remuneration', label: "Rémunération et conditions d'exercice", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT MÉDECIN DU TRAVAIL</h1><p>Entre <strong>{{entreprise}}</strong> et le Docteur <strong>{{medecin_travail}}</strong></p><p><strong>Date :</strong> {{date_contrat}}</p><h2>Missions</h2><p>{{missions}}</p><h2>Rémunération et conditions</h2><p>{{remuneration}}</p></div>`,
  },
  {
    code: 'qhse2_rapport_visite_medecin',
    name: "Rapport de Visite du Médecin du Travail",
    category: 'btp_construction',
    price: 6000,
    priceMax: 18000,
    description: "Rapport de visite périodique du médecin du travail avec constats, recommandations et plan d'action santé au travail.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise visitée", type: 'text', required: true },
      { key: 'date_visite', label: "Date de la visite", type: 'date', required: true },
      { key: 'medecin', label: "Médecin du travail", type: 'text', required: true },
      { key: 'constats_medicaux', label: "Constats et observations médicales", type: 'textarea', required: true },
      { key: 'recommandations', label: "Recommandations à l'employeur", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE VISITE DU MÉDECIN DU TRAVAIL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_visite}}</p><p><strong>Médecin :</strong> {{medecin}}</p><h2>Constats médicaux</h2><p>{{constats_medicaux}}</p><h2>Recommandations</h2><p>{{recommandations}}</p></div>`,
  },
  {
    code: 'qhse2_plan_continuite_hse',
    name: "Plan de Continuité d'Activité HSE",
    category: 'btp_construction',
    price: 15000,
    priceMax: 45000,
    description: "Plan de continuité d'activité axé sur les aspects HSE pour maintenir les opérations en situation de crise ou sinistre.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_elaboration', label: "Date d'élaboration", type: 'date', required: true },
      { key: 'scenarios_crise', label: "Scénarios de crise HSE identifiés", type: 'textarea', required: true },
      { key: 'mesures_continuite', label: "Mesures de continuité HSE", type: 'textarea', required: true },
      { key: 'organisation_crise', label: "Organisation de la cellule de crise", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE CONTINUITÉ D'ACTIVITÉ HSE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_elaboration}}</p><h2>Scénarios de crise</h2><p>{{scenarios_crise}}</p><h2>Mesures de continuité</h2><p>{{mesures_continuite}}</p><h2>Organisation de la cellule de crise</h2><p>{{organisation_crise}}</p></div>`,
  },
  {
    code: 'rh5_politique_remuneration',
    name: "Politique de Rémunération",
    category: 'rh_emploi',
    price: 12000,
    priceMax: 36000,
    description: "Politique globale de rémunération définissant la structure de salaire, les avantages et la gestion des révisions salariales conforme au droit OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_application', label: "Date d'application", type: 'date', required: true },
      { key: 'principes_remuneration', label: "Principes directeurs de la rémunération", type: 'textarea', required: true },
      { key: 'structure_salaire', label: "Structure du salaire (fixe, variable, avantages)", type: 'textarea', required: true },
      { key: 'revision_annuelle', label: "Processus de révision salariale annuelle", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE RÉMUNÉRATION</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>En vigueur depuis :</strong> {{date_application}}</p><h2>Principes directeurs</h2><p>{{principes_remuneration}}</p><h2>Structure du salaire</h2><p>{{structure_salaire}}</p><h2>Révision salariale</h2><p>{{revision_annuelle}}</p></div>`,
  },
  {
    code: 'rh5_grille_salaires',
    name: "Grille des Salaires Entreprise",
    category: 'rh_emploi',
    price: 10000,
    priceMax: 30000,
    description: "Grille salariale interne par catégorie professionnelle et niveau d'expérience, alignée sur la convention collective applicable en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee_application', label: "Année d'application", type: 'text', required: true },
      { key: 'convention_collective', label: "Convention collective de référence", type: 'text', required: true },
      { key: 'grille_details', label: "Détail de la grille par catégorie et échelon", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>GRILLE DES SALAIRES</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee_application}}</p><p><strong>Convention :</strong> {{convention_collective}}</p><h2>Grille salariale</h2><p>{{grille_details}}</p><table border="1" style="width:100%"><thead><tr><th>Catégorie</th><th>Échelon</th><th>Salaire min (FCFA)</th><th>Salaire max (FCFA)</th></tr></thead><tbody><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></tbody></table></div>`,
  },
  {
    code: 'rh5_politique_mobilite_internationale',
    name: "Politique de Mobilité Internationale",
    category: 'rh_emploi',
    price: 14000,
    priceMax: 42000,
    description: "Politique encadrant la mobilité internationale des salariés (expatriation, détachement) pour les entreprises opérant en zone CEDEAO.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'entreprise', label: "Groupe / Entreprise", type: 'text', required: true },
      { key: 'date_mise_a_jour', label: "Date de mise à jour", type: 'date', required: true },
      { key: 'perimetre_geographique', label: "Périmètre géographique couvert", type: 'textarea', required: true },
      { key: 'conditions_mobilite', label: "Conditions et critères de mobilité", type: 'textarea', required: true },
      { key: 'package_expatriation', label: "Package d'expatriation (logement, scolarité, billets)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE MOBILITÉ INTERNATIONALE</h1><p><strong>Groupe :</strong> {{entreprise}}</p><p><strong>Mise à jour :</strong> {{date_mise_a_jour}}</p><h2>Périmètre géographique</h2><p>{{perimetre_geographique}}</p><h2>Conditions de mobilité</h2><p>{{conditions_mobilite}}</p><h2>Package d'expatriation</h2><p>{{package_expatriation}}</p></div>`,
  },
  {
    code: 'rh5_contrat_expatriation',
    name: "Contrat d'Expatriation",
    category: 'rh_emploi',
    price: 15000,
    priceMax: 45000,
    description: "Contrat d'expatriation conforme au droit ivoirien et aux conventions bilatérales de sécurité sociale, avec clauses de retour garanties.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'salarie', label: "Nom du salarié expatrié", type: 'text', required: true },
      { key: 'pays_accueil', label: "Pays d'accueil", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début de l'expatriation", type: 'date', required: true },
      { key: 'duree_mission', label: "Durée de la mission", type: 'text', required: true },
      { key: 'remuneration_expatrie', label: "Rémunération et avantages expatriation", type: 'textarea', required: true },
      { key: 'clause_retour', label: "Clause de retour et réintégration", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'EXPATRIATION</h1><p><strong>Salarié :</strong> {{salarie}}</p><p><strong>Pays d'accueil :</strong> {{pays_accueil}}</p><p><strong>Début :</strong> {{date_debut}}</p><p><strong>Durée :</strong> {{duree_mission}}</p><h2>Rémunération et avantages</h2><p>{{remuneration_expatrie}}</p><h2>Retour et réintégration</h2><p>{{clause_retour}}</p></div>`,
  },
  {
    code: 'rh5_accord_detachement',
    name: "Accord de Détachement",
    category: 'rh_emploi',
    price: 12000,
    priceMax: 36000,
    description: "Accord de détachement temporaire de salarié entre deux entités d'un groupe, conforme aux exigences fiscales et sociales OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'entite_origine', label: "Entité d'origine", type: 'text', required: true },
      { key: 'entite_accueil', label: "Entité d'accueil", type: 'text', required: true },
      { key: 'salarie', label: "Salarié détaché", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début du détachement", type: 'date', required: true },
      { key: 'modalites_refacturation', label: "Modalités de refacturation des coûts", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DÉTACHEMENT</h1><p>Entre <strong>{{entite_origine}}</strong> (entité d'origine) et <strong>{{entite_accueil}}</strong> (entité d'accueil)</p><p><strong>Salarié :</strong> {{salarie}}</p><p><strong>Début du détachement :</strong> {{date_debut}}</p><h2>Modalités de refacturation</h2><p>{{modalites_refacturation}}</p></div>`,
  },
  {
    code: 'rh5_contrat_mise_a_disposition',
    name: "Contrat de Mise à Disposition de Personnel",
    category: 'rh_emploi',
    price: 11000,
    priceMax: 33000,
    description: "Contrat de mise à disposition de personnel entre une entreprise utilisatrice et une agence de travail temporaire ou sous-traitant.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'entreprise_preteuse', label: "Entreprise prêteuse", type: 'text', required: true },
      { key: 'entreprise_utilisatrice', label: "Entreprise utilisatrice", type: 'text', required: true },
      { key: 'date_debut', label: "Date de début", type: 'date', required: true },
      { key: 'poste_occupe', label: "Poste occupé et missions", type: 'textarea', required: true },
      { key: 'conditions_financieres', label: "Conditions financières de la mise à disposition", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE MISE À DISPOSITION DE PERSONNEL</h1><p>Entre <strong>{{entreprise_preteuse}}</strong> et <strong>{{entreprise_utilisatrice}}</strong></p><p><strong>Date :</strong> {{date_debut}}</p><h2>Poste et missions</h2><p>{{poste_occupe}}</p><h2>Conditions financières</h2><p>{{conditions_financieres}}</p></div>`,
  },
  {
    code: 'rh5_accord_temps_partiels',
    name: "Accord de Temps Partiels Choisis",
    category: 'rh_emploi',
    price: 8000,
    priceMax: 24000,
    description: "Accord collectif encadrant le recours au temps partiel choisi par les salariés avec garanties de droits et retour à plein temps.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'conditions_acces', label: "Conditions d'accès au temps partiel choisi", type: 'textarea', required: true },
      { key: 'garanties_droits', label: "Garanties de droits des salariés à temps partiel", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TEMPS PARTIELS CHOISIS</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>Conditions d'accès</h2><p>{{conditions_acces}}</p><h2>Garanties des droits</h2><p>{{garanties_droits}}</p></div>`,
  },
  {
    code: 'rh5_politique_diversite_inclusion',
    name: "Politique de Diversité et Inclusion",
    category: 'rh_emploi',
    price: 9000,
    priceMax: 27000,
    description: "Politique d'engagement pour la diversité et l'inclusion en milieu professionnel, adaptée aux réalités socioculturelles d'Afrique de l'Ouest.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_application', label: "Date d'application", type: 'date', required: true },
      { key: 'engagements_diversite', label: "Engagements en matière de diversité", type: 'textarea', required: true },
      { key: 'actions_inclusion', label: "Actions concrètes d'inclusion", type: 'textarea', required: true },
      { key: 'indicateurs_suivi', label: "Indicateurs de suivi D&I", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>POLITIQUE DE DIVERSITÉ ET INCLUSION</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>En vigueur depuis :</strong> {{date_application}}</p><h2>Engagements D&I</h2><p>{{engagements_diversite}}</p><h2>Actions d'inclusion</h2><p>{{actions_inclusion}}</p><h2>Indicateurs</h2><p>{{indicateurs_suivi}}</p></div>`,
  },
  {
    code: 'rh5_charte_parentalite',
    name: "Charte Parentalité Entreprise",
    category: 'rh_emploi',
    price: 7000,
    priceMax: 21000,
    description: "Charte parentalité formalisant les engagements de l'entreprise envers les parents salariés (congés, flexibilité, retour de congé maternité/paternité).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature", type: 'date', required: true },
      { key: 'mesures_parentalite', label: "Mesures parentalité proposées", type: 'textarea', required: true },
      { key: 'accompagnement_retour', label: "Accompagnement au retour de congé parental", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE PARENTALITÉ ENTREPRISE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Signée le :</strong> {{date_signature}}</p><h2>Mesures parentalité</h2><p>{{mesures_parentalite}}</p><h2>Retour de congé parental</h2><p>{{accompagnement_retour}}</p></div>`,
  },
  {
    code: 'rh5_accord_qualite_vie_travail',
    name: "Accord de Qualité de Vie au Travail",
    category: 'rh_emploi',
    price: 10000,
    priceMax: 30000,
    description: "Accord collectif QVT (Qualité de Vie au Travail) visant l'amélioration des conditions de travail et la prévention des risques psychosociaux.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'axes_qvt', label: "Axes prioritaires QVT identifiés", type: 'textarea', required: true },
      { key: 'actions_qvt', label: "Actions et mesures retenues", type: 'textarea', required: true },
      { key: 'budget_qvt', label: "Budget alloué (FCFA)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE QUALITÉ DE VIE AU TRAVAIL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Signé le :</strong> {{date_accord}}</p><h2>Axes prioritaires</h2><p>{{axes_qvt}}</p><h2>Actions retenues</h2><p>{{actions_qvt}}</p><p><strong>Budget :</strong> {{budget_qvt}} FCFA</p></div>`,
  },
  {
    code: 'rh5_plan_action_handicap',
    name: "Plan d'Action Handicap",
    category: 'rh_emploi',
    price: 9000,
    priceMax: 27000,
    description: "Plan d'action en faveur de l'emploi des personnes handicapées conforme aux obligations légales ivoiriennes et engagements RSE.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'periode', label: "Période du plan", type: 'text', required: true },
      { key: 'etat_lieux', label: "État des lieux emploi des personnes handicapées", type: 'textarea', required: true },
      { key: 'actions_planifiees', label: "Actions planifiées (recrutement, maintien, formation)", type: 'textarea', required: true },
      { key: 'objectifs_chiffres', label: "Objectifs chiffrés et indicateurs", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN D'ACTION HANDICAP</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Période :</strong> {{periode}}</p><h2>État des lieux</h2><p>{{etat_lieux}}</p><h2>Actions planifiées</h2><p>{{actions_planifiees}}</p><h2>Objectifs et indicateurs</h2><p>{{objectifs_chiffres}}</p></div>`,
  },
  {
    code: 'rh5_rapport_bilan_social',
    name: "Rapport de Bilan Social",
    category: 'rh_emploi',
    price: 15000,
    priceMax: 45000,
    description: "Bilan social annuel récapitulant les principales données sociales de l'entreprise (emploi, rémunération, formation, conditions de travail).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee', label: "Année de référence", type: 'text', required: true },
      { key: 'directeur_rh', label: "Directeur des Ressources Humaines", type: 'text', required: true },
      { key: 'donnees_emploi', label: "Données emploi (effectifs, CDD, CDI, turnover)", type: 'textarea', required: true },
      { key: 'donnees_remuneration', label: "Données rémunération (masse salariale, SMIG)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>BILAN SOCIAL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee}}</p><p><strong>DRH :</strong> {{directeur_rh}}</p><h2>Données emploi</h2><p>{{donnees_emploi}}</p><h2>Données rémunération</h2><p>{{donnees_remuneration}}</p></div>`,
  },
  {
    code: 'rh5_rapport_egalite_professionnelle',
    name: "Rapport d'Égalité Professionnelle",
    category: 'rh_emploi',
    price: 12000,
    priceMax: 36000,
    description: "Rapport sur l'égalité professionnelle entre hommes et femmes, avec analyse des écarts de rémunération et plan d'action correctif.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee', label: "Année", type: 'text', required: true },
      { key: 'analyse_ecarts', label: "Analyse des écarts de rémunération H/F", type: 'textarea', required: true },
      { key: 'plan_action_egalite', label: "Plan d'action pour l'égalité professionnelle", type: 'textarea', required: true },
      { key: 'indicateurs', label: "Indicateurs de suivi", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'ÉGALITÉ PROFESSIONNELLE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee}}</p><h2>Analyse des écarts H/F</h2><p>{{analyse_ecarts}}</p><h2>Plan d'action</h2><p>{{plan_action_egalite}}</p><h2>Indicateurs de suivi</h2><p>{{indicateurs}}</p></div>`,
  },
  {
    code: 'rh5_accord_reduction_temps_travail',
    name: "Accord de Réduction du Temps de Travail",
    category: 'rh_emploi',
    price: 11000,
    priceMax: 33000,
    description: "Accord collectif de réduction du temps de travail (RTT) conforme au Code du travail ivoirien avec modalités de compensation.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'nouvelle_duree_travail', label: "Nouvelle durée du travail hebdomadaire", type: 'text', required: true },
      { key: 'modalites_rtt', label: "Modalités d'attribution et de prise des RTT", type: 'textarea', required: true },
      { key: 'compensations', label: "Compensations salariales et maintien des droits", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÉDUCTION DU TEMPS DE TRAVAIL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_accord}}</p><p><strong>Nouvelle durée :</strong> {{nouvelle_duree_travail}}</p><h2>Modalités RTT</h2><p>{{modalites_rtt}}</p><h2>Compensations</h2><p>{{compensations}}</p></div>`,
  },
  {
    code: 'rh5_plan_sauvegarde_emploi',
    name: "Plan de Sauvegarde de l'Emploi (PSE)",
    category: 'rh_emploi',
    price: 18000,
    priceMax: 54000,
    description: "Plan de sauvegarde de l'emploi (PSE) conforme aux dispositions du Code du travail en zone OHADA avec mesures d'accompagnement des salariés.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_elaboration', label: "Date d'élaboration", type: 'date', required: true },
      { key: 'contexte_economique', label: "Contexte économique justifiant le PSE", type: 'textarea', required: true },
      { key: 'mesures_reclassement', label: "Mesures de reclassement et reconversion", type: 'textarea', required: true },
      { key: 'indemnites_depart', label: "Indemnités de départ et aides financières", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE SAUVEGARDE DE L'EMPLOI (PSE)</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_elaboration}}</p><h2>Contexte économique</h2><p>{{contexte_economique}}</p><h2>Mesures de reclassement</h2><p>{{mesures_reclassement}}</p><h2>Indemnités de départ</h2><p>{{indemnites_depart}}</p></div>`,
  },
  {
    code: 'rh5_accord_gpec',
    name: "Accord de Gestion Prévisionnelle des Emplois et Compétences (GPEC)",
    category: 'rh_emploi',
    price: 15000,
    priceMax: 45000,
    description: "Accord GPEC définissant la démarche anticipative de gestion des emplois et des compétences dans un contexte d'évolution économique rapide.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'diagnostic_competences', label: "Diagnostic des emplois et compétences actuels", type: 'textarea', required: true },
      { key: 'projections_emplois', label: "Projections des besoins en emplois et compétences", type: 'textarea', required: true },
      { key: 'plan_actions_gpec', label: "Plan d'actions GPEC (formation, mobilité, recrutement)", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GESTION PRÉVISIONNELLE DES EMPLOIS ET COMPÉTENCES (GPEC)</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>Diagnostic actuel</h2><p>{{diagnostic_competences}}</p><h2>Projections</h2><p>{{projections_emplois}}</p><h2>Plan d'actions</h2><p>{{plan_actions_gpec}}</p></div>`,
  },
  {
    code: 'rh5_rapport_formation_professionnelle',
    name: "Rapport sur la Formation Professionnelle",
    category: 'rh_emploi',
    price: 10000,
    priceMax: 30000,
    description: "Rapport annuel sur la formation professionnelle continue avec bilan des actions réalisées et utilisation du budget formation (FDFP en Côte d'Ivoire).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee', label: "Année", type: 'text', required: true },
      { key: 'budget_fdfp', label: "Budget FDFP mobilisé (FCFA)", type: 'text', required: true },
      { key: 'bilan_formations', label: "Bilan des formations réalisées", type: 'textarea', required: true },
      { key: 'formations_prevues', label: "Formations prévues pour la période suivante", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT SUR LA FORMATION PROFESSIONNELLE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee}}</p><p><strong>Budget FDFP :</strong> {{budget_fdfp}} FCFA</p><h2>Bilan des formations</h2><p>{{bilan_formations}}</p><h2>Formations à venir</h2><p>{{formations_prevues}}</p></div>`,
  },
  {
    code: 'rh5_contrat_generation',
    name: "Contrat de Génération (Adaptation Locale)",
    category: 'rh_emploi',
    price: 10000,
    priceMax: 30000,
    description: "Accord de contrat de génération adapté au contexte ivoirien favorisant l'emploi des jeunes et le maintien des seniors avec transfert de compétences.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'objectifs_emploi_jeunes', label: "Objectifs d'embauche et intégration des jeunes", type: 'textarea', required: true },
      { key: 'maintien_seniors', label: "Mesures de maintien en emploi des seniors", type: 'textarea', required: true },
      { key: 'transfert_competences', label: "Dispositif de transfert de compétences", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE GÉNÉRATION</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>Emploi des jeunes</h2><p>{{objectifs_emploi_jeunes}}</p><h2>Maintien des seniors</h2><p>{{maintien_seniors}}</p><h2>Transfert de compétences</h2><p>{{transfert_competences}}</p></div>`,
  },
  {
    code: 'rh5_accord_interessement',
    name: "Accord d'Intéressement",
    category: 'rh_emploi',
    price: 12000,
    priceMax: 36000,
    description: "Accord d'intéressement collectif liant la rémunération variable à la performance de l'entreprise, adapté au cadre fiscal ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'formule_calcul', label: "Formule de calcul de la prime d'intéressement", type: 'textarea', required: true },
      { key: 'criteres_performance', label: "Critères de performance retenus", type: 'textarea', required: true },
      { key: 'modalites_versement', label: "Modalités et calendrier de versement", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'INTÉRESSEMENT</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>Formule de calcul</h2><p>{{formule_calcul}}</p><h2>Critères de performance</h2><p>{{criteres_performance}}</p><h2>Modalités de versement</h2><p>{{modalites_versement}}</p></div>`,
  },
  {
    code: 'rh5_accord_participation',
    name: "Accord de Participation",
    category: 'rh_emploi',
    price: 12000,
    priceMax: 36000,
    description: "Accord de participation des salariés aux résultats de l'entreprise, avec définition de la réserve spéciale et modalités de distribution.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'formule_participation', label: "Formule de calcul de la réserve spéciale de participation", type: 'textarea', required: true },
      { key: 'modes_affectation', label: "Modes d'affectation et de disponibilité des droits", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTICIPATION</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>Formule de calcul</h2><p>{{formule_participation}}</p><h2>Modes d'affectation</h2><p>{{modes_affectation}}</p></div>`,
  },
  {
    code: 'rh5_reglement_plan_epargne',
    name: "Règlement du Plan d'Épargne Entreprise",
    category: 'rh_emploi',
    price: 11000,
    priceMax: 33000,
    description: "Règlement du Plan d'Épargne Entreprise (PEE) avec gestion des versements volontaires, abondement et disponibilité des fonds.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_application', label: "Date d'application", type: 'date', required: true },
      { key: 'beneficiaires', label: "Bénéficiaires du plan d'épargne", type: 'textarea', required: true },
      { key: 'conditions_abondement', label: "Conditions et taux d'abondement employeur", type: 'textarea', required: true },
      { key: 'cas_deblocage', label: "Cas de déblocage anticipé des fonds", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RÈGLEMENT DU PLAN D'ÉPARGNE ENTREPRISE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>En vigueur depuis :</strong> {{date_application}}</p><h2>Bénéficiaires</h2><p>{{beneficiaires}}</p><h2>Abondement employeur</h2><p>{{conditions_abondement}}</p><h2>Déblocage anticipé</h2><p>{{cas_deblocage}}</p></div>`,
  },
  {
    code: 'rh5_rapport_annuel_rh',
    name: "Rapport Annuel RH",
    category: 'rh_emploi',
    price: 15000,
    priceMax: 45000,
    description: "Rapport annuel RH complet présentant les réalisations, indicateurs clés et perspectives de la Direction des Ressources Humaines.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'annee', label: "Année", type: 'text', required: true },
      { key: 'directeur_rh', label: "Directeur des Ressources Humaines", type: 'text', required: true },
      { key: 'faits_marquants', label: "Faits marquants RH de l'année", type: 'textarea', required: true },
      { key: 'kpi_rh', label: "Indicateurs RH clés (turnover, absentéisme, formation)", type: 'textarea', required: true },
      { key: 'perspectives', label: "Perspectives et chantiers RH à venir", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT ANNUEL RH</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Année :</strong> {{annee}}</p><p><strong>DRH :</strong> {{directeur_rh}}</p><h2>Faits marquants</h2><p>{{faits_marquants}}</p><h2>Indicateurs clés</h2><p>{{kpi_rh}}</p><h2>Perspectives</h2><p>{{perspectives}}</p></div>`,
  },
  {
    code: 'rh5_charte_manager',
    name: "Charte du Manager",
    category: 'rh_emploi',
    price: 7000,
    priceMax: 21000,
    description: "Charte du manager définissant le rôle, les responsabilités et les comportements attendus des cadres managériaux dans l'entreprise.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_application', label: "Date d'application", type: 'date', required: true },
      { key: 'valeurs_manageriales', label: "Valeurs managériales de l'entreprise", type: 'textarea', required: true },
      { key: 'responsabilites_manager', label: "Responsabilités et engagements du manager", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DU MANAGER</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>En vigueur depuis :</strong> {{date_application}}</p><h2>Valeurs managériales</h2><p>{{valeurs_manageriales}}</p><h2>Responsabilités et engagements</h2><p>{{responsabilites_manager}}</p></div>`,
  },
  {
    code: 'rh5_evaluation_directeur_rh',
    name: "Évaluation du Directeur RH",
    category: 'rh_emploi',
    price: 9000,
    priceMax: 27000,
    description: "Grille d'évaluation annuelle du Directeur des Ressources Humaines avec objectifs quantitatifs et qualitatifs et plan de développement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'nom_directeur_rh', label: "Nom du Directeur RH", type: 'text', required: true },
      { key: 'periode_evaluation', label: "Période d'évaluation", type: 'text', required: true },
      { key: 'evaluateur', label: "Évaluateur (DG ou PDG)", type: 'text', required: true },
      { key: 'bilan_objectifs', label: "Bilan des objectifs de la période", type: 'textarea', required: true },
      { key: 'plan_developpement', label: "Plan de développement professionnel", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ÉVALUATION DU DIRECTEUR DES RESSOURCES HUMAINES</h1><p><strong>DRH évalué :</strong> {{nom_directeur_rh}}</p><p><strong>Période :</strong> {{periode_evaluation}}</p><p><strong>Évaluateur :</strong> {{evaluateur}}</p><h2>Bilan des objectifs</h2><p>{{bilan_objectifs}}</p><h2>Plan de développement</h2><p>{{plan_developpement}}</p></div>`,
  },
  {
    code: 'rh5_accord_teletravail_international',
    name: "Accord de Télétravail International",
    category: 'rh_emploi',
    price: 13000,
    priceMax: 39000,
    description: "Accord encadrant le télétravail international des salariés opérant depuis l'étranger, avec gestion des aspects fiscaux et sociaux transfrontaliers.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'entreprise', label: "Entreprise", type: 'text', required: true },
      { key: 'date_accord', label: "Date de l'accord", type: 'date', required: true },
      { key: 'perimetre_pays', label: "Pays éligibles au télétravail international", type: 'textarea', required: true },
      { key: 'conditions_eligibilite', label: "Conditions d'éligibilité du salarié", type: 'textarea', required: true },
      { key: 'regime_fiscal_social', label: "Régime fiscal et social applicable", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TÉLÉTRAVAIL INTERNATIONAL</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Date :</strong> {{date_accord}}</p><h2>Pays éligibles</h2><p>{{perimetre_pays}}</p><h2>Conditions d'éligibilité</h2><p>{{conditions_eligibilite}}</p><h2>Régime fiscal et social</h2><p>{{regime_fiscal_social}}</p></div>`,
  },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 21b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
