import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ── 25 Import/Export ──────────────────────────────────────────────────────
  {
    code: 'imp_cvim_vente_intl',
    name: "Contrat de vente internationale de marchandises (CVIM/Incoterms)",
    category: 'commercial_financier',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de vente internationale conforme à la Convention de Vienne (CVIM) avec stipulation de l'Incoterm applicable, conditions de livraison, transfert de risques et modalités de paiement.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 88,
    fieldsJson: F([
      { key: 'vendeur', label: "Raison sociale du vendeur", type: 'text', required: true },
      { key: 'acheteur', label: "Raison sociale de l'acheteur", type: 'text', required: true },
      { key: 'marchandise', label: "Désignation de la marchandise", type: 'textarea', required: true },
      { key: 'incoterm', label: "Incoterm applicable (ex: FOB Abidjan)", type: 'text', required: true },
      { key: 'prix_total', label: "Prix total en USD ou EUR", type: 'text', required: true },
      { key: 'date_livraison', label: "Date de livraison prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE VENTE INTERNATIONALE DE MARCHANDISES</h1><p><strong>Vendeur :</strong> {{vendeur}}</p><p><strong>Acheteur :</strong> {{acheteur}}</p><h2>Article 1 — Objet du contrat</h2><p>Le vendeur s'engage à livrer à l'acheteur les marchandises suivantes : {{marchandise}}</p><h2>Article 2 — Conditions de livraison</h2><p>La livraison s'effectuera selon l'Incoterm : {{incoterm}}, conformément aux Incoterms ICC en vigueur.</p><h2>Article 3 — Prix</h2><p>Le prix total convenu est de : {{prix_total}}</p><h2>Article 4 — Délai de livraison</h2><p>La livraison est prévue au plus tard le : {{date_livraison}}</p><h2>Article 5 — Droit applicable</h2><p>Le présent contrat est soumis à la Convention des Nations Unies sur les contrats de vente internationale de marchandises (CVIM) et subsidiairement au droit OHADA.</p></div>`,
  },
  {
    code: 'imp_agent_commercial_export',
    name: "Accord de service d'agent commercial à l'export",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord encadrant la mission d'un agent commercial mandaté pour prospecter et conclure des ventes à l'exportation au nom du mandant, avec définition du territoire, des commissions et des objectifs.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'mandant', label: "Raison sociale du mandant (exportateur)", type: 'text', required: true },
      { key: 'agent', label: "Nom ou raison sociale de l'agent", type: 'text', required: true },
      { key: 'territoire', label: "Territoire de prospection", type: 'text', required: true },
      { key: 'taux_commission', label: "Taux de commission (%)", type: 'text', required: true },
      { key: 'duree_accord', label: "Durée de l'accord", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'AGENT COMMERCIAL À L'EXPORT</h1><p><strong>Mandant :</strong> {{mandant}}</p><p><strong>Agent :</strong> {{agent}}</p><h2>Article 1 — Mission</h2><p>Le mandant confie à l'agent la mission de prospecter et de développer les ventes à l'export sur le territoire suivant : {{territoire}}</p><h2>Article 2 — Rémunération</h2><p>L'agent percevra une commission de {{taux_commission}} % sur le chiffre d'affaires HT réalisé grâce à son entremise.</p><h2>Article 3 — Durée</h2><p>Le présent accord est conclu pour une durée de : {{duree_accord}}</p><h2>Article 4 — Obligations de l'agent</h2><p>L'agent s'engage à rendre compte régulièrement de ses activités, à respecter les conditions tarifaires fixées par le mandant et à ne pas représenter de sociétés concurrentes sans autorisation écrite préalable.</p></div>`,
  },
  {
    code: 'imp_representant_import',
    name: "Accord de service de représentant commercial à l'import",
    category: 'commercial_financier',
    price: 5500,
    priceMax: 16500,
    description: "Accord définissant les conditions dans lesquelles un représentant commercial agit au nom d'un importateur pour sourcer, négocier et coordonner les achats à l'international.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'importateur', label: "Raison sociale de l'importateur", type: 'text', required: true },
      { key: 'representant', label: "Nom ou raison sociale du représentant", type: 'text', required: true },
      { key: 'produits_cibles', label: "Produits ou familles de produits visés", type: 'textarea', required: true },
      { key: 'pays_sourcing', label: "Pays de sourcing", type: 'text', required: true },
      { key: 'honoraires', label: "Honoraires ou mode de rémunération", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE REPRÉSENTANT COMMERCIAL À L'IMPORT</h1><p><strong>Importateur :</strong> {{importateur}}</p><p><strong>Représentant :</strong> {{representant}}</p><h2>Article 1 — Mission de représentation</h2><p>L'importateur mandate le représentant pour identifier, négocier et coordonner les achats des produits suivants : {{produits_cibles}}, auprès de fournisseurs situés dans les pays suivants : {{pays_sourcing}}</p><h2>Article 2 — Rémunération</h2><p>Le représentant sera rémunéré selon les modalités suivantes : {{honoraires}}</p><h2>Article 3 — Obligations</h2><p>Le représentant agit dans l'intérêt exclusif de l'importateur, sans pouvoir engager ce dernier sans accord écrit préalable au-delà du montant fixé contractuellement.</p></div>`,
  },
  {
    code: 'imp_distribution_exclusive_export',
    name: "Accord de distribution exclusive à l'export",
    category: 'commercial_financier',
    price: 7000,
    priceMax: 21000,
    description: "Contrat accordant à un distributeur l'exclusivité de commercialisation des produits d'un fournisseur sur un territoire à l'export, avec obligations de quota, de promotion et de reporting.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'fournisseur', label: "Raison sociale du fournisseur", type: 'text', required: true },
      { key: 'distributeur', label: "Raison sociale du distributeur exclusif", type: 'text', required: true },
      { key: 'territoire_exclusif', label: "Territoire d'exclusivité", type: 'text', required: true },
      { key: 'produits', label: "Gamme de produits concernés", type: 'textarea', required: true },
      { key: 'quota_annuel', label: "Quota annuel minimum d'achat", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTION EXCLUSIVE À L'EXPORT</h1><p><strong>Fournisseur :</strong> {{fournisseur}}</p><p><strong>Distributeur exclusif :</strong> {{distributeur}}</p><h2>Article 1 — Exclusivité territoriale</h2><p>Le fournisseur accorde au distributeur l'exclusivité de distribution des produits suivants : {{produits}}, sur le territoire : {{territoire_exclusif}}</p><h2>Article 2 — Quota minimum</h2><p>Le distributeur s'engage à atteindre un quota annuel minimum d'achats de : {{quota_annuel}}</p><h2>Article 3 — Durée</h2><p>Le présent accord est conclu pour une durée de {{duree_contrat}}, renouvelable par accord exprès des parties.</p><h2>Article 4 — Sanctions</h2><p>Le non-respect du quota annuel pendant deux exercices consécutifs entraîne de plein droit la perte de l'exclusivité territoriale.</p></div>`,
  },
  {
    code: 'imp_distribution_selective_intl',
    name: "Accord de distribution sélective internationale",
    category: 'commercial_financier',
    price: 6500,
    priceMax: 19500,
    description: "Contrat de distribution sélective permettant à un fournisseur de choisir ses revendeurs agréés à l'international selon des critères qualitatifs, de positionnement et de compétences techniques.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'fournisseur', label: "Raison sociale du fournisseur", type: 'text', required: true },
      { key: 'revendeur', label: "Raison sociale du revendeur agréé", type: 'text', required: true },
      { key: 'criteres_selection', label: "Critères de sélection appliqués", type: 'textarea', required: true },
      { key: 'zone_commerciale', label: "Zone commerciale autorisée", type: 'text', required: true },
      { key: 'date_debut', label: "Date d'entrée en vigueur", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTION SÉLECTIVE INTERNATIONALE</h1><p><strong>Fournisseur :</strong> {{fournisseur}}</p><p><strong>Revendeur agréé :</strong> {{revendeur}}</p><h2>Article 1 — Agrément</h2><p>Le fournisseur accorde au revendeur le statut de distributeur agréé au regard des critères suivants : {{criteres_selection}}</p><h2>Article 2 — Zone commerciale</h2><p>Le revendeur est autorisé à commercialiser les produits dans la zone : {{zone_commerciale}}</p><h2>Article 3 — Entrée en vigueur</h2><p>Le présent accord prend effet le : {{date_debut}}</p><h2>Article 4 — Conditions de maintien</h2><p>Le maintien de l'agrément est conditionné au respect permanent des critères de sélection et à la fourniture d'un rapport d'activité semestriel.</p></div>`,
  },
  {
    code: 'imp_courtier_marchandises_intl',
    name: "Accord de service de courtier en marchandises internationales",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13500,
    description: "Accord encadrant l'intervention d'un courtier en marchandises chargé de mettre en relation acheteurs et vendeurs sur les marchés internationaux, contre rémunération à la transaction.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'donneur_ordre', label: "Raison sociale du donneur d'ordre", type: 'text', required: true },
      { key: 'courtier', label: "Raison sociale du courtier", type: 'text', required: true },
      { key: 'type_marchandise', label: "Type de marchandise à négocier", type: 'text', required: true },
      { key: 'courtage', label: "Taux ou montant du courtage", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE COURTIER EN MARCHANDISES INTERNATIONALES</h1><p><strong>Donneur d'ordre :</strong> {{donneur_ordre}}</p><p><strong>Courtier :</strong> {{courtier}}</p><h2>Article 1 — Mission de courtage</h2><p>Le courtier est mandaté pour rechercher des contreparties sur les marchés internationaux pour les marchandises suivantes : {{type_marchandise}}</p><h2>Article 2 — Rémunération</h2><p>La rémunération du courtier est fixée à : {{courtage}}, payable à la conclusion effective de la transaction.</p><h2>Article 3 — Indépendance</h2><p>Le courtier agit en qualité d'intermédiaire indépendant et ne saurait engager les parties sans leur accord écrit exprès.</p></div>`,
  },
  {
    code: 'imp_credit_documentaire_lc',
    name: "Accord de crédit documentaire (lettre de crédit LC)",
    category: 'commercial_financier',
    price: 9000,
    priceMax: 27000,
    description: "Document encadrant l'ouverture et l'utilisation d'un crédit documentaire (LC) entre banque émettrice, bénéficiaire exportateur et donneur d'ordre importateur, conforme aux RUU 600 de la CCI.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'banque_emettrice', label: "Banque émettrice", type: 'text', required: true },
      { key: 'donneur_ordre', label: "Donneur d'ordre (importateur)", type: 'text', required: true },
      { key: 'beneficiaire', label: "Bénéficiaire (exportateur)", type: 'text', required: true },
      { key: 'montant_lc', label: "Montant du crédit documentaire", type: 'text', required: true },
      { key: 'date_expiration', label: "Date d'expiration du crédit", type: 'date', required: true },
      { key: 'documents_requis', label: "Documents requis pour la levée", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CRÉDIT DOCUMENTAIRE (LETTRE DE CRÉDIT LC)</h1><p><strong>Banque émettrice :</strong> {{banque_emettrice}}</p><p><strong>Donneur d'ordre :</strong> {{donneur_ordre}}</p><p><strong>Bénéficiaire :</strong> {{beneficiaire}}</p><h2>Article 1 — Ouverture du crédit</h2><p>La banque émettrice ouvre en faveur du bénéficiaire un crédit documentaire irrévocable d'un montant de : {{montant_lc}}, soumis aux Règles et Usances Uniformes relatives aux crédits documentaires (RUU 600 CCI).</p><h2>Article 2 — Documents requis</h2><p>Le paiement sera effectué contre présentation des documents suivants dans les délais impartis : {{documents_requis}}</p><h2>Article 3 — Expiration</h2><p>Le crédit expire le : {{date_expiration}} au lieu de présentation des documents.</p></div>`,
  },
  {
    code: 'imp_remise_documentaire',
    name: "Accord de remise documentaire (D/P, D/A)",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord organisant l'encaissement de documents commerciaux via une banque remettante et une banque présentatrice, selon les modalités Documents contre Paiement (D/P) ou Documents contre Acceptation (D/A).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'exportateur', label: "Raison sociale de l'exportateur (cédant)", type: 'text', required: true },
      { key: 'importateur', label: "Raison sociale de l'importateur (tiré)", type: 'text', required: true },
      { key: 'banque_remettante', label: "Banque remettante", type: 'text', required: true },
      { key: 'modalite', label: "Modalité (D/P ou D/A)", type: 'text', required: true },
      { key: 'montant', label: "Montant de la remise documentaire", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE REMISE DOCUMENTAIRE (D/P — D/A)</h1><p><strong>Exportateur (cédant) :</strong> {{exportateur}}</p><p><strong>Importateur (tiré) :</strong> {{importateur}}</p><p><strong>Banque remettante :</strong> {{banque_remettante}}</p><h2>Article 1 — Mode d'encaissement</h2><p>Les parties conviennent d'un règlement par remise documentaire selon la modalité : {{modalite}}, conforme aux Règles Uniformes relatives aux encaissements (RUE 522 CCI).</p><h2>Article 2 — Montant</h2><p>Le montant de la remise est de : {{montant}}</p><h2>Article 3 — Obligations</h2><p>La banque présentatrice ne remettra les documents à l'importateur que conformément aux instructions de la banque remettante et à la modalité convenue.</p></div>`,
  },
  {
    code: 'imp_garantie_bancaire_export',
    name: "Accord de garantie bancaire à l'export (BFCE)",
    category: 'commercial_financier',
    price: 8500,
    priceMax: 25500,
    description: "Accord de garantie bancaire couvrant les risques à l'exportation, notamment le risque de non-paiement acheteur, le risque politique et le risque de fabrication, conforme aux standards BFCE/Bpifrance.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'exportateur', label: "Raison sociale de l'exportateur garanti", type: 'text', required: true },
      { key: 'banque_garante', label: "Banque garante", type: 'text', required: true },
      { key: 'acheteur_etranger', label: "Acheteur étranger bénéficiaire", type: 'text', required: true },
      { key: 'montant_garanti', label: "Montant garanti", type: 'text', required: true },
      { key: 'risques_couverts', label: "Nature des risques couverts", type: 'textarea', required: true },
      { key: 'date_fin_garantie', label: "Date de fin de garantie", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE GARANTIE BANCAIRE À L'EXPORT</h1><p><strong>Exportateur garanti :</strong> {{exportateur}}</p><p><strong>Banque garante :</strong> {{banque_garante}}</p><p><strong>Acheteur étranger :</strong> {{acheteur_etranger}}</p><h2>Article 1 — Objet de la garantie</h2><p>La banque garante s'engage à couvrir les risques suivants liés à l'opération d'exportation : {{risques_couverts}}, pour un montant maximum de : {{montant_garanti}}</p><h2>Article 2 — Durée</h2><p>La garantie prend fin le : {{date_fin_garantie}}</p><h2>Article 3 — Mise en jeu</h2><p>La garantie est mise en jeu sur première demande écrite documentée de l'exportateur bénéficiaire, dans les délais et formes convenus.</p></div>`,
  },
  {
    code: 'imp_assurance_credit_export_coface',
    name: "Accord de service d'assurance crédit export (COFACE Africa)",
    category: 'commercial_financier',
    price: 7500,
    priceMax: 22500,
    description: "Accord de souscription à une assurance crédit export couvrant le risque d'insolvabilité ou de défaillance des acheteurs étrangers, adapté au marché africain via COFACE Africa.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'assure', label: "Raison sociale de l'assuré (exportateur)", type: 'text', required: true },
      { key: 'assureur', label: "Nom de l'assureur (ex: COFACE Africa)", type: 'text', required: true },
      { key: 'encours_garanti', label: "Encours maximum garanti", type: 'text', required: true },
      { key: 'pays_couverts', label: "Pays acheteurs couverts", type: 'textarea', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle d'assurance", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ASSURANCE CRÉDIT EXPORT</h1><p><strong>Assuré :</strong> {{assure}}</p><p><strong>Assureur :</strong> {{assureur}}</p><h2>Article 1 — Objet</h2><p>L'assureur garantit à l'assuré le paiement des créances commerciales nées de ventes à l'export vers les pays suivants : {{pays_couverts}}, jusqu'à concurrence d'un encours maximum de : {{encours_garanti}}</p><h2>Article 2 — Prime</h2><p>La prime annuelle d'assurance est fixée à : {{prime_annuelle}}</p><h2>Article 3 — Sinistre</h2><p>En cas de sinistre avéré (insolvabilité ou retard prolongé de paiement), l'assuré déclarera le sinistre dans les délais contractuels et coopérera pleinement à la procédure de recouvrement.</p></div>`,
  },
  {
    code: 'imp_transfert_technologie_licence',
    name: "Accord de transfert de technologie (licence export)",
    category: 'commercial_financier',
    price: 10000,
    priceMax: 30000,
    description: "Accord de licence accordant à un licencié étranger le droit d'utiliser, reproduire ou exploiter une technologie, un brevet ou un savoir-faire, contre paiement de redevances.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'donneur_licence', label: "Donneur de licence (titulaire)", type: 'text', required: true },
      { key: 'licencie', label: "Licencié (bénéficiaire étranger)", type: 'text', required: true },
      { key: 'technologie', label: "Description de la technologie ou brevet", type: 'textarea', required: true },
      { key: 'redevance', label: "Taux de redevance (royalty)", type: 'text', required: true },
      { key: 'territoire_licence', label: "Territoire de la licence", type: 'text', required: true },
      { key: 'duree_licence', label: "Durée de la licence", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSFERT DE TECHNOLOGIE (LICENCE EXPORT)</h1><p><strong>Donneur de licence :</strong> {{donneur_licence}}</p><p><strong>Licencié :</strong> {{licencie}}</p><h2>Article 1 — Objet de la licence</h2><p>Le donneur de licence concède au licencié le droit d'exploiter la technologie suivante : {{technologie}}, sur le territoire : {{territoire_licence}}</p><h2>Article 2 — Redevances</h2><p>Le licencié versera des redevances au taux de : {{redevance}} sur le chiffre d'affaires net réalisé grâce à la technologie licenciée.</p><h2>Article 3 — Durée</h2><p>La présente licence est accordée pour une durée de : {{duree_licence}}</p><h2>Article 4 — Confidentialité</h2><p>Le licencié s'engage à maintenir la confidentialité du savoir-faire transmis et à ne pas le sous-licencier sans accord écrit préalable.</p></div>`,
  },
  {
    code: 'imp_joint_venture_intl',
    name: "Accord de joint-venture internationale",
    category: 'commercial_financier',
    price: 12000,
    priceMax: 36000,
    description: "Accord constitutif d'une coentreprise entre partenaires de pays différents, fixant les apports, la gouvernance, le partage des bénéfices et les modalités de sortie.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'partenaire_ci', label: "Partenaire ivoirien (ou africain)", type: 'text', required: true },
      { key: 'partenaire_etranger', label: "Partenaire étranger", type: 'text', required: true },
      { key: 'objet_jv', label: "Objet de la joint-venture", type: 'textarea', required: true },
      { key: 'repartition_capital', label: "Répartition du capital (%)", type: 'text', required: true },
      { key: 'duree_jv', label: "Durée de la joint-venture", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE JOINT-VENTURE INTERNATIONALE</h1><p><strong>Partenaire ivoirien :</strong> {{partenaire_ci}}</p><p><strong>Partenaire étranger :</strong> {{partenaire_etranger}}</p><h2>Article 1 — Constitution</h2><p>Les parties conviennent de constituer une coentreprise ayant pour objet : {{objet_jv}}</p><h2>Article 2 — Capital et gouvernance</h2><p>Le capital de la joint-venture est réparti comme suit : {{repartition_capital}}</p><h2>Article 3 — Durée</h2><p>La joint-venture est constituée pour une durée de : {{duree_jv}}</p><h2>Article 4 — Partage des résultats</h2><p>Les bénéfices et pertes sont répartis proportionnellement aux apports en capital, sauf convention contraire expressément stipulée.</p></div>`,
  },
  {
    code: 'imp_inspection_avant_embarquement',
    name: "Accord de service d'inspection avant embarquement (SGS, BIVAC)",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Accord de prestation de service d'inspection avant embarquement (PSI) mandaté par l'autorité douanière ou l'importateur, conforme aux standards SGS/BIVAC et aux règles OMC/OTC.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'mandant', label: "Mandant (importateur ou autorité)", type: 'text', required: true },
      { key: 'societe_inspection', label: "Société d'inspection (ex: SGS, BIVAC)", type: 'text', required: true },
      { key: 'marchandise_inspectee', label: "Nature de la marchandise à inspecter", type: 'textarea', required: true },
      { key: 'port_embarquement', label: "Port ou lieu d'embarquement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'INSPECTION AVANT EMBARQUEMENT</h1><p><strong>Mandant :</strong> {{mandant}}</p><p><strong>Société d'inspection :</strong> {{societe_inspection}}</p><h2>Article 1 — Mission d'inspection</h2><p>La société d'inspection est mandatée pour vérifier la qualité, la quantité et la conformité des marchandises suivantes : {{marchandise_inspectee}}, au lieu d'embarquement : {{port_embarquement}}</p><h2>Article 2 — Rapport d'inspection</h2><p>À l'issue de l'inspection, un certificat d'inspection (Clean Report of Findings — CRF) ou un rapport de non-conformité sera émis dans les 48 heures ouvrables.</p><h2>Article 3 — Responsabilité</h2><p>La responsabilité de la société d'inspection est limitée au montant des honoraires perçus pour la mission concernée.</p></div>`,
  },
  {
    code: 'imp_certification_origine',
    name: "Accord de service de certification d'origine",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Accord de prestation pour l'obtention et la délivrance de certificats d'origine (chambre de commerce, Form A, EUR.1) attestant l'origine des marchandises exportées.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'exportateur', label: "Raison sociale de l'exportateur", type: 'text', required: true },
      { key: 'organisme_certificateur', label: "Organisme certificateur (ex: CCI-CI)", type: 'text', required: true },
      { key: 'produits_origine', label: "Produits concernés et critères d'origine", type: 'textarea', required: true },
      { key: 'pays_destination', label: "Pays de destination", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CERTIFICATION D'ORIGINE</h1><p><strong>Exportateur :</strong> {{exportateur}}</p><p><strong>Organisme certificateur :</strong> {{organisme_certificateur}}</p><h2>Article 1 — Objet</h2><p>L'organisme certificateur s'engage à délivrer les certificats d'origine requis pour les produits suivants : {{produits_origine}}, à destination de : {{pays_destination}}</p><h2>Article 2 — Conditions de délivrance</h2><p>L'exportateur fournira toutes les pièces justificatives nécessaires à l'établissement de l'origine préférentielle ou non préférentielle des marchandises.</p><h2>Article 3 — Responsabilité déclarative</h2><p>L'exportateur demeure seul responsable de l'exactitude des informations déclarées à l'appui de la demande de certification.</p></div>`,
  },
  {
    code: 'imp_test_conformite_import',
    name: "Accord de service de test de conformité à l'importation",
    category: 'commercial_financier',
    price: 4500,
    priceMax: 13500,
    description: "Accord de prestation de service de test et de vérification de la conformité des produits importés aux normes techniques, sanitaires ou phytosanitaires applicables en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'importateur', label: "Raison sociale de l'importateur", type: 'text', required: true },
      { key: 'laboratoire', label: "Laboratoire ou organisme de test", type: 'text', required: true },
      { key: 'produits_testes', label: "Produits soumis aux tests", type: 'textarea', required: true },
      { key: 'normes_applicables', label: "Normes ou réglementations applicables", type: 'text', required: true },
      { key: 'delai_test', label: "Délai de réalisation des tests", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TEST DE CONFORMITÉ À L'IMPORTATION</h1><p><strong>Importateur :</strong> {{importateur}}</p><p><strong>Organisme de test :</strong> {{laboratoire}}</p><h2>Article 1 — Objet</h2><p>L'organisme de test s'engage à réaliser les analyses et essais de conformité sur les produits suivants : {{produits_testes}}, au regard des normes : {{normes_applicables}}</p><h2>Article 2 — Délais</h2><p>Les résultats seront communiqués dans un délai de : {{delai_test}} à compter de la réception des échantillons.</p><h2>Article 3 — Rapport</h2><p>Un rapport de conformité ou de non-conformité motivé sera délivré à l'importateur avec les préconisations correctives le cas échéant.</p></div>`,
  },
  {
    code: 'imp_commissionnaire_douane_agree',
    name: "Accord de service de commissionnaire en douane agréé",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Accord de mandat confiant à un commissionnaire en douane agréé (CDA) la réalisation des formalités douanières d'importation ou d'exportation au nom et pour le compte de l'opérateur.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'mandant', label: "Raison sociale du mandant (opérateur)", type: 'text', required: true },
      { key: 'cda', label: "Commissionnaire en douane agréé (CDA)", type: 'text', required: true },
      { key: 'operations_confies', label: "Nature des opérations confiées", type: 'textarea', required: true },
      { key: 'honoraires_cda', label: "Honoraires du CDA", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE COMMISSIONNAIRE EN DOUANE AGRÉÉ</h1><p><strong>Mandant :</strong> {{mandant}}</p><p><strong>Commissionnaire en douane agréé :</strong> {{cda}}</p><h2>Article 1 — Mandat douanier</h2><p>Le mandant confie au CDA la réalisation des opérations douanières suivantes en son nom et pour son compte : {{operations_confies}}</p><h2>Article 2 — Honoraires</h2><p>La rémunération du CDA est fixée à : {{honoraires_cda}}</p><h2>Article 3 — Responsabilité</h2><p>Le CDA est responsable de l'exactitude des déclarations en douane souscrites et de leur conformité aux dispositions du Code des douanes de Côte d'Ivoire.</p></div>`,
  },
  {
    code: 'imp_declarant_douane',
    name: "Accord de service de déclarant en douane",
    category: 'commercial_financier',
    price: 3500,
    priceMax: 10500,
    description: "Accord de prestation entre un opérateur de commerce international et un déclarant en douane habilité, pour l'établissement et le dépôt des déclarations en détail à la Direction Générale des Douanes.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'operateur', label: "Raison sociale de l'opérateur", type: 'text', required: true },
      { key: 'declarant', label: "Nom du déclarant en douane habilité", type: 'text', required: true },
      { key: 'numero_agrement', label: "Numéro d'agrément du déclarant", type: 'text', required: true },
      { key: 'type_declarations', label: "Type de déclarations à établir", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DÉCLARANT EN DOUANE</h1><p><strong>Opérateur :</strong> {{operateur}}</p><p><strong>Déclarant en douane :</strong> {{declarant}} — Agrément N° {{numero_agrement}}</p><h2>Article 1 — Prestation</h2><p>Le déclarant en douane est mandaté pour établir et déposer les déclarations suivantes : {{type_declarations}}, auprès de la Direction Générale des Douanes de Côte d'Ivoire.</p><h2>Article 2 — Obligations documentaires</h2><p>L'opérateur s'engage à fournir au déclarant tous les documents nécessaires (facture commerciale, connaissement, liste de colisage, etc.) dans les délais requis.</p></div>`,
  },
  {
    code: 'imp_dedouanement_express',
    name: "Accord de service de dédouanement express",
    category: 'commercial_financier',
    price: 6000,
    priceMax: 18000,
    description: "Accord de prestation de dédouanement rapide pour les envois urgents (fret express, messagerie internationale), avec engagement de délais de mainlevée sous 24 à 48 heures.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'expediteur', label: "Raison sociale de l'expéditeur", type: 'text', required: true },
      { key: 'prestataire_express', label: "Prestataire de dédouanement express", type: 'text', required: true },
      { key: 'nature_envoi', label: "Nature de l'envoi express", type: 'text', required: true },
      { key: 'valeur_declaree', label: "Valeur déclarée de l'envoi", type: 'text', required: true },
      { key: 'delai_mainlevee', label: "Délai de mainlevée garanti", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DÉDOUANEMENT EXPRESS</h1><p><strong>Client :</strong> {{expediteur}}</p><p><strong>Prestataire :</strong> {{prestataire_express}}</p><h2>Article 1 — Objet</h2><p>Le prestataire s'engage à réaliser le dédouanement express de l'envoi suivant : {{nature_envoi}}, d'une valeur déclarée de : {{valeur_declaree}}</p><h2>Article 2 — Délai garanti</h2><p>La mainlevée sera obtenue dans un délai maximum de : {{delai_mainlevee}}, sous réserve de la complétude des documents fournis par le client.</p><h2>Article 3 — Pénalités</h2><p>En cas de non-respect du délai garanti imputable au prestataire, une pénalité forfaitaire sera appliquée selon le barème annexé au présent accord.</p></div>`,
  },
  {
    code: 'imp_liquidation_droits_taxes',
    name: "Accord de service de liquidation de droits et taxes",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Accord de prestation pour le calcul, la vérification et le paiement des droits et taxes douanières dus à l'importation ou à l'exportation, selon la classification tarifaire applicable.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'redevable', label: "Raison sociale du redevable", type: 'text', required: true },
      { key: 'prestataire', label: "Prestataire de liquidation", type: 'text', required: true },
      { key: 'position_tarifaire', label: "Position tarifaire (code SH)", type: 'text', required: true },
      { key: 'valeur_en_douane', label: "Valeur en douane des marchandises", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE LIQUIDATION DE DROITS ET TAXES</h1><p><strong>Redevable :</strong> {{redevable}}</p><p><strong>Prestataire :</strong> {{prestataire}}</p><h2>Article 1 — Mission</h2><p>Le prestataire est mandaté pour calculer et vérifier les droits et taxes applicables à la position tarifaire : {{position_tarifaire}}, sur la base d'une valeur en douane de : {{valeur_en_douane}}</p><h2>Article 2 — Paiement</h2><p>Les droits liquidés seront acquittés auprès du receveur des douanes compétent dans les délais légaux.</p><h2>Article 3 — Contestation</h2><p>En cas de désaccord sur la liquidation, le prestataire assistera le redevable dans la procédure de réclamation contentieuse.</p></div>`,
  },
  {
    code: 'imp_remboursement_droits_drawback',
    name: "Accord de service de remboursement de droits (drawback)",
    category: 'commercial_financier',
    price: 5500,
    priceMax: 16500,
    description: "Accord de prestation pour l'obtention du remboursement des droits de douane acquittés sur des intrants réexportés sous forme de produits finis (régime drawback conforme au code des douanes CEDEAO).",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'entreprise', label: "Raison sociale de l'entreprise bénéficiaire", type: 'text', required: true },
      { key: 'prestataire_drawback', label: "Prestataire spécialisé drawback", type: 'text', required: true },
      { key: 'intrants_concernes', label: "Intrants importés concernés", type: 'textarea', required: true },
      { key: 'produits_reexportes', label: "Produits finis réexportés", type: 'text', required: true },
      { key: 'montant_droits_payes', label: "Montant des droits à rembourser", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE REMBOURSEMENT DE DROITS (DRAWBACK)</h1><p><strong>Entreprise bénéficiaire :</strong> {{entreprise}}</p><p><strong>Prestataire :</strong> {{prestataire_drawback}}</p><h2>Article 1 — Objet</h2><p>Le prestataire est mandaté pour constituer et déposer le dossier de demande de remboursement des droits de douane payés sur les intrants suivants : {{intrants_concernes}}, incorporés dans les produits réexportés : {{produits_reexportes}}</p><h2>Article 2 — Montant attendu</h2><p>Le montant estimé des droits à récupérer est de : {{montant_droits_payes}}</p><h2>Article 3 — Diligence</h2><p>Le prestataire déposera la demande dans les délais prescrits et assurera le suivi jusqu'à l'ordonnancement du remboursement.</p></div>`,
  },
  {
    code: 'imp_rapport_performance_export',
    name: "Rapport de performance export",
    category: 'commercial_financier',
    price: 3000,
    priceMax: 9000,
    description: "Rapport périodique d'analyse des indicateurs clés de performance à l'exportation : volumes, marchés, marges, délais de paiement et incidents de recouvrement.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'entreprise', label: "Raison sociale de l'entreprise exportatrice", type: 'text', required: true },
      { key: 'periode', label: "Période du rapport", type: 'text', required: true },
      { key: 'ca_export', label: "Chiffre d'affaires export de la période", type: 'text', required: true },
      { key: 'principaux_marches', label: "Principaux marchés et parts respectives", type: 'textarea', required: true },
      { key: 'incidents_recouvrement', label: "Incidents de recouvrement signalés", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE EXPORT</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Période :</strong> {{periode}}</p><h2>1. Résultats commerciaux</h2><p>Chiffre d'affaires export de la période : {{ca_export}}</p><h2>2. Répartition par marché</h2><p>{{principaux_marches}}</p><h2>3. Incidents de recouvrement</h2><p>{{incidents_recouvrement}}</p><h2>4. Recommandations</h2><p>Sur la base de l'analyse des indicateurs, les actions correctives et les priorités de développement pour la période suivante sont identifiées et présentées au Comité Export.</p></div>`,
  },
  {
    code: 'imp_plan_developpement_export',
    name: "Plan de développement commercial à l'export",
    category: 'commercial_financier',
    price: 5000,
    priceMax: 15000,
    description: "Document stratégique définissant les objectifs, les marchés cibles, les ressources allouées et le calendrier d'actions pour le développement des exportations d'une entreprise sur 12 à 36 mois.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'entreprise', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'produits_export', label: "Produits ou services à exporter", type: 'textarea', required: true },
      { key: 'marches_cibles', label: "Marchés cibles identifiés", type: 'textarea', required: true },
      { key: 'objectif_ca', label: "Objectif de CA export sur 3 ans", type: 'text', required: true },
      { key: 'budget_prospection', label: "Budget de prospection alloué", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT COMMERCIAL À L'EXPORT</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><h2>1. Offre export</h2><p>Produits ou services concernés : {{produits_export}}</p><h2>2. Marchés cibles</h2><p>{{marches_cibles}}</p><h2>3. Objectifs</h2><p>Objectif de chiffre d'affaires export sur la période du plan : {{objectif_ca}}</p><h2>4. Budget de prospection</h2><p>Budget alloué à la prospection internationale : {{budget_prospection}}</p><h2>5. Calendrier d'actions</h2><p>Un calendrier détaillé des actions de prospection, participations à des foires et missions commerciales sera établi en annexe du présent plan.</p></div>`,
  },
  {
    code: 'imp_trade_finance_intl',
    name: "Accord de service de financement du commerce international (trade finance)",
    category: 'commercial_financier',
    price: 9000,
    priceMax: 27000,
    description: "Accord de service de financement structuré couvrant les besoins en fonds de roulement liés aux opérations d'import-export : avance sur marchandises, préfinancement export, affacturage international.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'beneficiaire', label: "Raison sociale du bénéficiaire", type: 'text', required: true },
      { key: 'etablissement_financier', label: "Établissement financier prestataire", type: 'text', required: true },
      { key: 'type_financement', label: "Type de financement (ex: préfinancement export)", type: 'text', required: true },
      { key: 'montant_financement', label: "Montant du financement", type: 'text', required: true },
      { key: 'taux_interet', label: "Taux d'intérêt annuel", type: 'text', required: true },
      { key: 'garanties', label: "Garanties constituées", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE FINANCEMENT DU COMMERCE INTERNATIONAL</h1><p><strong>Bénéficiaire :</strong> {{beneficiaire}}</p><p><strong>Établissement financier :</strong> {{etablissement_financier}}</p><h2>Article 1 — Nature du financement</h2><p>L'établissement financier accorde au bénéficiaire un financement de type : {{type_financement}}, d'un montant de : {{montant_financement}}</p><h2>Article 2 — Coût</h2><p>Le taux d'intérêt annuel appliqué est de : {{taux_interet}}</p><h2>Article 3 — Garanties</h2><p>Le financement est garanti par : {{garanties}}</p><h2>Article 4 — Remboursement</h2><p>Le remboursement est lié au cycle commercial financé et intervient au plus tard à l'encaissement de la créance export correspondante.</p></div>`,
  },
  {
    code: 'imp_partenariat_cci_intl',
    name: "Accord de partenariat chambre de commerce internationale",
    category: 'commercial_financier',
    price: 4000,
    priceMax: 12000,
    description: "Accord de partenariat entre une entreprise et une chambre de commerce internationale (CCI-CI, ICC) pour l'accompagnement aux foires, la certification et l'accès aux réseaux de commerce international.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'entreprise', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'chambre', label: "Chambre de commerce partenaire", type: 'text', required: true },
      { key: 'services_attendus', label: "Services attendus du partenariat", type: 'textarea', required: true },
      { key: 'cotisation', label: "Montant de la cotisation annuelle", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT CHAMBRE DE COMMERCE INTERNATIONALE</h1><p><strong>Entreprise membre :</strong> {{entreprise}}</p><p><strong>Chambre de commerce :</strong> {{chambre}}</p><h2>Article 1 — Objet du partenariat</h2><p>Le présent accord formalise l'adhésion et le partenariat entre les parties, portant sur les services suivants : {{services_attendus}}</p><h2>Article 2 — Cotisation</h2><p>L'entreprise s'acquitte d'une cotisation annuelle de : {{cotisation}}</p><h2>Article 3 — Avantages membres</h2><p>En contrepartie, l'entreprise bénéficie de l'accès aux réseaux d'affaires, aux missions commerciales, aux bases de données de commerce international et aux services de certification de la chambre.</p></div>`,
  },
  {
    code: 'imp_charte_exportateur_africain',
    name: "Charte de l'exportateur africain responsable",
    category: 'commercial_financier',
    price: 2000,
    priceMax: 6000,
    description: "Document d'engagement volontaire définissant les principes éthiques, sociaux et environnementaux auxquels souscrit un exportateur africain dans le cadre de ses relations commerciales internationales.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'exportateur', label: "Raison sociale de l'exportateur signataire", type: 'text', required: true },
      { key: 'secteur_activite', label: "Secteur d'activité", type: 'text', required: true },
      { key: 'date_signature', label: "Date de signature de la charte", type: 'date', required: true },
      { key: 'representant_legal', label: "Nom et titre du représentant légal", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE L'EXPORTATEUR AFRICAIN RESPONSABLE</h1><p><strong>Signataire :</strong> {{exportateur}} — Secteur : {{secteur_activite}}</p><p><strong>Représentant légal :</strong> {{representant_legal}}</p><h2>Préambule</h2><p>Convaincu que l'exportation responsable est un levier de développement durable pour l'Afrique, l'exportateur soussigné s'engage à respecter les principes suivants.</p><h2>Engagement 1 — Éthique commerciale</h2><p>Refus de toute pratique corrompue, respect des règles de concurrence loyale et transparence dans les relations avec les partenaires étrangers.</p><h2>Engagement 2 — Responsabilité sociale</h2><p>Garantie de conditions de travail dignes dans toute la chaîne de valeur export.</p><h2>Engagement 3 — Durabilité environnementale</h2><p>Réduction de l'empreinte carbone des opérations logistiques et respect des standards environnementaux des marchés de destination.</p><p><strong>Fait à Abidjan, le :</strong> {{date_signature}}</p></div>`,
  },

  // ── 25 Douane/Transit ─────────────────────────────────────────────────────
  {
    code: 'douan_transit_routier_tir',
    name: "Accord de transit international routier (TIR)",
    category: 'transport_logistique',
    price: 6000,
    priceMax: 18000,
    description: "Accord encadrant les opérations de transit international sous couvert du carnet TIR, permettant le passage des frontières sans contrôle douanier intermédiaire des marchandises sous scellés.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'transporteur', label: "Raison sociale du transporteur TIR", type: 'text', required: true },
      { key: 'expediteur', label: "Raison sociale de l'expéditeur", type: 'text', required: true },
      { key: 'pays_depart', label: "Pays de départ", type: 'text', required: true },
      { key: 'pays_destination', label: "Pays de destination finale", type: 'text', required: true },
      { key: 'numero_carnet_tir', label: "Numéro du carnet TIR", type: 'text', required: true },
      { key: 'date_depart', label: "Date de départ prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSIT INTERNATIONAL ROUTIER (TIR)</h1><p><strong>Transporteur TIR :</strong> {{transporteur}}</p><p><strong>Expéditeur :</strong> {{expediteur}}</p><h2>Article 1 — Opération de transit</h2><p>Le transporteur prend en charge les marchandises au départ de : {{pays_depart}}, à destination de : {{pays_destination}}, sous couvert du carnet TIR N° : {{numero_carnet_tir}}</p><h2>Article 2 — Date de départ</h2><p>L'opération de transit débute le : {{date_depart}}</p><h2>Article 3 — Obligations TIR</h2><p>Le transporteur s'engage à respecter les dispositions de la Convention TIR de 1975, à maintenir les scellés douaniers intacts jusqu'au bureau de douane de destination et à présenter le carnet à chaque bureau frontière traversé.</p></div>`,
  },
  {
    code: 'douan_transit_douane_t1_ata',
    name: "Accord de transit en douane (T1/carnet ATA)",
    category: 'transport_logistique',
    price: 5000,
    priceMax: 15000,
    description: "Accord organisant le transport de marchandises sous le régime suspensif T1 ou sous carnet ATA pour les envois temporaires, avec cautionnement douanier et apurement dans les délais.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'titulaire', label: "Titulaire du régime de transit", type: 'text', required: true },
      { key: 'garant', label: "Caution / garant douanier", type: 'text', required: true },
      { key: 'type_document', label: "Type de document (T1 ou carnet ATA)", type: 'text', required: true },
      { key: 'marchandise', label: "Description de la marchandise", type: 'textarea', required: true },
      { key: 'bureau_apurement', label: "Bureau douanier d'apurement", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSIT EN DOUANE (T1 / CARNET ATA)</h1><p><strong>Titulaire :</strong> {{titulaire}}</p><p><strong>Garant :</strong> {{garant}}</p><h2>Article 1 — Régime de transit</h2><p>La marchandise suivante : {{marchandise}}, est placée sous le régime de transit : {{type_document}}</p><h2>Article 2 — Apurement</h2><p>Le régime doit être apuré au bureau de douane : {{bureau_apurement}}, dans les délais impartis par la réglementation douanière applicable.</p><h2>Article 3 — Responsabilité du garant</h2><p>En cas de défaut d'apurement, le garant est solidairement responsable du paiement des droits et taxes en suspension.</p></div>`,
  },
  {
    code: 'douan_entrepot_sous_douane',
    name: "Accord de service d'entrepôt sous douane (régime entrepôt)",
    category: 'transport_logistique',
    price: 5500,
    priceMax: 16500,
    description: "Accord de prestation entre un opérateur logistique et un importateur pour le stockage de marchandises sous le régime douanier d'entrepôt, en suspension de droits et taxes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'deposant', label: "Raison sociale du déposant", type: 'text', required: true },
      { key: 'gestionnaire_entrepot', label: "Gestionnaire de l'entrepôt douanier", type: 'text', required: true },
      { key: 'numero_agrement_entrepot', label: "Numéro d'agrément de l'entrepôt", type: 'text', required: true },
      { key: 'marchandises_stockees', label: "Nature des marchandises stockées", type: 'textarea', required: true },
      { key: 'duree_stockage', label: "Durée maximale de stockage autorisée", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ENTREPÔT SOUS DOUANE</h1><p><strong>Déposant :</strong> {{deposant}}</p><p><strong>Gestionnaire de l'entrepôt :</strong> {{gestionnaire_entrepot}} — Agrément N° {{numero_agrement_entrepot}}</p><h2>Article 1 — Stockage en suspension</h2><p>Le gestionnaire reçoit en dépôt les marchandises suivantes : {{marchandises_stockees}}, en suspension de droits et taxes douanières.</p><h2>Article 2 — Durée</h2><p>La durée maximale de placement sous régime entrepôt est de : {{duree_stockage}}</p><h2>Article 3 — Sortie du régime</h2><p>La sortie des marchandises s'effectue soit par mise à la consommation après acquittement des droits, soit par réexportation, soit par transfert vers un autre régime suspensif autorisé.</p></div>`,
  },
  {
    code: 'douan_admission_temporaire_ata',
    name: "Accord de service d'admission temporaire (ATA)",
    category: 'transport_logistique',
    price: 4500,
    priceMax: 13500,
    description: "Accord encadrant l'admission temporaire de marchandises en franchise de droits pour usage professionnel limité (matériel de foire, outillage, échantillons), sous couvert d'un carnet ATA délivré par la CCI.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'titulaire_ata', label: "Titulaire du carnet ATA", type: 'text', required: true },
      { key: 'materiel_importe', label: "Description du matériel admis temporairement", type: 'textarea', required: true },
      { key: 'usage_prevu', label: "Usage professionnel prévu", type: 'text', required: true },
      { key: 'date_reexportation', label: "Date limite de réexportation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'ADMISSION TEMPORAIRE (ATA)</h1><p><strong>Titulaire du carnet ATA :</strong> {{titulaire_ata}}</p><h2>Article 1 — Objet</h2><p>Le présent accord encadre l'importation temporaire en franchise douanière du matériel suivant : {{materiel_importe}}, pour l'usage professionnel suivant : {{usage_prevu}}</p><h2>Article 2 — Réexportation</h2><p>Le titulaire s'engage à réexporter l'intégralité du matériel au plus tard le : {{date_reexportation}}</p><h2>Article 3 — Défaut de réexportation</h2><p>Tout défaut de réexportation dans les délais entraîne l'exigibilité immédiate des droits et taxes suspendus, majorés de pénalités de retard.</p></div>`,
  },
  {
    code: 'douan_perfectionnement_actif',
    name: "Accord de service de perfectionnement actif en douane",
    category: 'transport_logistique',
    price: 6000,
    priceMax: 18000,
    description: "Accord encadrant le régime de perfectionnement actif permettant d'importer des matières premières en suspension de droits pour les transformer et réexporter les produits finis.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'operateur', label: "Raison sociale de l'opérateur industriel", type: 'text', required: true },
      { key: 'matieres_premieres', label: "Matières premières importées en suspension", type: 'textarea', required: true },
      { key: 'produits_compensateurs', label: "Produits compensateurs (finis) à réexporter", type: 'text', required: true },
      { key: 'taux_rendement', label: "Taux de rendement de la transformation", type: 'text', required: true },
      { key: 'delai_apurement', label: "Délai d'apurement du régime", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PERFECTIONNEMENT ACTIF EN DOUANE</h1><p><strong>Opérateur industriel :</strong> {{operateur}}</p><h2>Article 1 — Objet du régime</h2><p>L'opérateur est autorisé à importer en suspension de droits les matières premières suivantes : {{matieres_premieres}}, afin de produire les produits compensateurs suivants : {{produits_compensateurs}}</p><h2>Article 2 — Taux de rendement</h2><p>Le taux de rendement de la transformation est fixé à : {{taux_rendement}}</p><h2>Article 3 — Apurement</h2><p>Le régime doit être apuré dans un délai de : {{delai_apurement}} à compter de l'acceptation de chaque déclaration d'entrée en perfectionnement actif.</p></div>`,
  },
  {
    code: 'douan_perfectionnement_passif',
    name: "Accord de service de perfectionnement passif en douane",
    category: 'transport_logistique',
    price: 5500,
    priceMax: 16500,
    description: "Accord encadrant le régime de perfectionnement passif permettant d'exporter temporairement des marchandises pour transformation à l'étranger et réimportation en franchise partielle de droits.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'exportateur', label: "Raison sociale de l'exportateur", type: 'text', required: true },
      { key: 'transformateur_etranger', label: "Transformateur étranger", type: 'text', required: true },
      { key: 'marchandises_exportees', label: "Marchandises exportées pour transformation", type: 'textarea', required: true },
      { key: 'operations_transformation', label: "Opérations de transformation réalisées à l'étranger", type: 'text', required: true },
      { key: 'delai_reimportation', label: "Délai de réimportation", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PERFECTIONNEMENT PASSIF EN DOUANE</h1><p><strong>Exportateur :</strong> {{exportateur}}</p><p><strong>Transformateur étranger :</strong> {{transformateur_etranger}}</p><h2>Article 1 — Exportation temporaire</h2><p>L'exportateur expédie temporairement les marchandises suivantes : {{marchandises_exportees}}, pour y faire réaliser les opérations suivantes : {{operations_transformation}}</p><h2>Article 2 — Réimportation</h2><p>Les produits transformés devront être réimportés dans un délai de : {{delai_reimportation}}</p><h2>Article 3 — Avantage tarifaire</h2><p>À la réimportation, les droits de douane ne seront calculés que sur la valeur ajoutée à l'étranger, conformément aux dispositions du code des douanes applicable.</p></div>`,
  },
  {
    code: 'douan_zone_franche_zfi_ci',
    name: "Accord de service de zone franche douanière (ZFI-CI)",
    category: 'transport_logistique',
    price: 8000,
    priceMax: 24000,
    description: "Accord d'installation et d'exploitation au sein de la Zone Franche Industrielle de Côte d'Ivoire (ZFI-CI), avec bénéfice des avantages douaniers et fiscaux accordés aux entreprises franc-portistes.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'entreprise_franc_portiste', label: "Raison sociale de l'entreprise franc-portiste", type: 'text', required: true },
      { key: 'activite_zfi', label: "Activité exercée en zone franche", type: 'textarea', required: true },
      { key: 'superficie_occupee', label: "Superficie occupée (m²)", type: 'text', required: true },
      { key: 'duree_convention', label: "Durée de la convention ZFI", type: 'text', required: true },
      { key: 'avantages_accordes', label: "Avantages douaniers et fiscaux accordés", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE ZONE FRANCHE INDUSTRIELLE (ZFI-CI)</h1><p><strong>Entreprise franc-portiste :</strong> {{entreprise_franc_portiste}}</p><h2>Article 1 — Installation en zone franche</h2><p>L'entreprise est autorisée à s'installer et à exercer l'activité suivante au sein de la ZFI-CI : {{activite_zfi}}, sur une superficie de : {{superficie_occupee}}</p><h2>Article 2 — Durée</h2><p>La convention d'implantation est conclue pour une durée de : {{duree_convention}}</p><h2>Article 3 — Avantages</h2><p>L'entreprise bénéficie des avantages suivants : {{avantages_accordes}}, sous réserve du respect des obligations déclaratives et des engagements d'exportation stipulés par la réglementation ZFI.</p></div>`,
  },
  {
    code: 'douan_transit_uemoa_couloir',
    name: "Accord de transit UEMOA (couloir régional)",
    category: 'transport_logistique',
    price: 5000,
    priceMax: 15000,
    description: "Accord de transport et de transit routier sur les corridors régionaux UEMOA (Abidjan-Ouagadougou, Abidjan-Bamako, etc.), conforme aux dispositions du Code communautaire de la route UEMOA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'chargeur', label: "Raison sociale du chargeur", type: 'text', required: true },
      { key: 'transporteur_routier', label: "Transporteur routier agréé UEMOA", type: 'text', required: true },
      { key: 'corridor', label: "Corridor régional emprunté", type: 'text', required: true },
      { key: 'marchandise_transportee', label: "Nature de la marchandise transportée", type: 'textarea', required: true },
      { key: 'fret_convenu', label: "Fret convenu", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE TRANSIT UEMOA (COULOIR RÉGIONAL)</h1><p><strong>Chargeur :</strong> {{chargeur}}</p><p><strong>Transporteur agréé UEMOA :</strong> {{transporteur_routier}}</p><h2>Article 1 — Transport régional</h2><p>Le transporteur prend en charge les marchandises suivantes : {{marchandise_transportee}}, sur le corridor régional : {{corridor}}</p><h2>Article 2 — Fret</h2><p>Le fret convenu est de : {{fret_convenu}}, payable aux conditions convenues entre les parties.</p><h2>Article 3 — Réglementation applicable</h2><p>Le transport est soumis au Code communautaire de la route de l'UEMOA, aux conventions bilatérales entre États membres et aux dispositions du règlement de sécurité routière en vigueur.</p></div>`,
  },
  {
    code: 'douan_facilitation_commerce_ofa',
    name: "Accord de service de facilitation du commerce (OFA)",
    category: 'transport_logistique',
    price: 4000,
    priceMax: 12000,
    description: "Accord de prestation de service dans le cadre de l'Accord de Facilitation des Échanges de l'OMC (AFE/OFA), visant à simplifier et harmoniser les procédures douanières pour les opérateurs de bonne foi.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'operateur', label: "Raison sociale de l'opérateur bénéficiaire", type: 'text', required: true },
      { key: 'autorite_douaniere', label: "Autorité douanière partenaire", type: 'text', required: true },
      { key: 'mesures_facilitation', label: "Mesures de facilitation appliquées", type: 'textarea', required: true },
      { key: 'engagements_operateur', label: "Engagements de conformité de l'opérateur", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE FACILITATION DU COMMERCE (OFA/AFE)</h1><p><strong>Opérateur :</strong> {{operateur}}</p><p><strong>Autorité douanière :</strong> {{autorite_douaniere}}</p><h2>Article 1 — Mesures de facilitation</h2><p>L'autorité douanière s'engage à appliquer les mesures de facilitation suivantes au profit de l'opérateur : {{mesures_facilitation}}</p><h2>Article 2 — Engagements de l'opérateur</h2><p>En contrepartie, l'opérateur s'engage à : {{engagements_operateur}}</p><h2>Article 3 — Cadre de référence</h2><p>Le présent accord s'inscrit dans le cadre de l'Accord sur la Facilitation des Échanges de l'OMC et de sa déclinaison nationale par la Direction Générale des Douanes de Côte d'Ivoire.</p></div>`,
  },
  {
    code: 'douan_guce_ci',
    name: "Accord de service de Guichet Unique du Commerce Extérieur (GUCE-CI)",
    category: 'transport_logistique',
    price: 4500,
    priceMax: 13500,
    description: "Accord d'utilisation du Guichet Unique du Commerce Extérieur de Côte d'Ivoire (GUCE-CI), plateforme électronique centralisant l'ensemble des formalités d'import-export auprès des administrations compétentes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'entreprise_utilisatrice', label: "Raison sociale de l'entreprise utilisatrice", type: 'text', required: true },
      { key: 'numero_contribuable', label: "Numéro de contribuable (CC)", type: 'text', required: true },
      { key: 'type_operations', label: "Type d'opérations déclarées via GUCE", type: 'text', required: true },
      { key: 'administrateur_compte', label: "Nom de l'administrateur du compte GUCE", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'UTILISATION DU GUICHET UNIQUE DU COMMERCE EXTÉRIEUR (GUCE-CI)</h1><p><strong>Entreprise utilisatrice :</strong> {{entreprise_utilisatrice}}</p><p><strong>Numéro de contribuable :</strong> {{numero_contribuable}}</p><h2>Article 1 — Accès à la plateforme</h2><p>L'entreprise est habilitée à utiliser la plateforme GUCE-CI pour les opérations suivantes : {{type_operations}}</p><h2>Article 2 — Administrateur du compte</h2><p>L'administrateur désigné du compte GUCE-CI est : {{administrateur_compte}}, qui est seul habilité à créer des sous-comptes utilisateurs.</p><h2>Article 3 — Sécurité et responsabilité</h2><p>L'entreprise est responsable de la confidentialité de ses identifiants d'accès et de l'exactitude des déclarations électroniques soumises via la plateforme GUCE-CI.</p></div>`,
  },
  {
    code: 'douan_scanner_portuaire',
    name: "Accord de service de scanner portuaire (contrôle non intrusif)",
    category: 'transport_logistique',
    price: 3500,
    priceMax: 10500,
    description: "Accord de prestation de service de contrôle non intrusif par scanner de conteneurs ou de véhicules au Port Autonome d'Abidjan, dans le cadre des procédures de ciblage douanier.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'operateur_portuaire', label: "Opérateur portuaire / armateur", type: 'text', required: true },
      { key: 'unite_controle', label: "Unité de contrôle scanner (DGD-CI)", type: 'text', required: true },
      { key: 'conteneurs_concernes', label: "Numéros de conteneurs soumis au scan", type: 'text', required: true },
      { key: 'date_scan', label: "Date du contrôle scanner", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE SCANNER PORTUAIRE (CONTRÔLE NON INTRUSIF)</h1><p><strong>Opérateur portuaire :</strong> {{operateur_portuaire}}</p><p><strong>Unité de contrôle :</strong> {{unite_controle}}</p><h2>Article 1 — Objet du contrôle</h2><p>Le présent accord autorise et organise le contrôle non intrusif par scanner des conteneurs suivants : {{conteneurs_concernes}}</p><h2>Article 2 — Date d'intervention</h2><p>Le contrôle est programmé le : {{date_scan}}</p><h2>Article 3 — Suite du contrôle</h2><p>En cas d'anomalie détectée à l'image, l'unité de contrôle procédera à une visite physique des marchandises en présence du représentant de l'opérateur portuaire ou de son commissionnaire en douane.</p></div>`,
  },
  {
    code: 'douan_operateur_economique_agree',
    name: "Accord de service de certifié opérateur économique agréé (OEA)",
    category: 'transport_logistique',
    price: 7000,
    priceMax: 21000,
    description: "Accord de partenariat entre la Direction Générale des Douanes de Côte d'Ivoire et un opérateur économique pour l'obtention et le maintien du statut d'Opérateur Économique Agréé (OEA).",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 78,
    fieldsJson: F([
      { key: 'entreprise_oea', label: "Raison sociale de l'entreprise candidate OEA", type: 'text', required: true },
      { key: 'categorie_oea', label: "Catégorie OEA demandée (Sécurité, Conformité, Complet)", type: 'text', required: true },
      { key: 'date_demande', label: "Date de dépôt de la demande OEA", type: 'date', required: true },
      { key: 'avantages_oea', label: "Avantages sollicités dans le cadre du statut OEA", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE D'OPÉRATEUR ÉCONOMIQUE AGRÉÉ (OEA)</h1><p><strong>Entreprise candidate :</strong> {{entreprise_oea}}</p><p><strong>Catégorie OEA :</strong> {{categorie_oea}}</p><h2>Article 1 — Demande d'agrément</h2><p>L'entreprise dépose auprès de la Direction Générale des Douanes une demande de statut OEA, catégorie : {{categorie_oea}}, en date du : {{date_demande}}</p><h2>Article 2 — Avantages attendus</h2><p>L'obtention du statut OEA permettra à l'entreprise de bénéficier des avantages suivants : {{avantages_oea}}</p><h2>Article 3 — Obligations de maintien</h2><p>L'entreprise s'engage à maintenir les standards de conformité, de sûreté et de sécurité documentés dans son auto-évaluation OEA et à se soumettre aux audits périodiques de l'administration douanière.</p></div>`,
  },
  {
    code: 'douan_dedouanement_maritime',
    name: "Accord de service de dédouanement maritime (bill of lading)",
    category: 'transport_logistique',
    price: 6000,
    priceMax: 18000,
    description: "Accord de prestation de service de dédouanement des marchandises arrivées par voie maritime au Port Autonome d'Abidjan, sur la base d'un connaissement (bill of lading) original ou télex release.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 83,
    fieldsJson: F([
      { key: 'importateur', label: "Raison sociale de l'importateur", type: 'text', required: true },
      { key: 'commissionnaire', label: "Commissionnaire en douane mandaté", type: 'text', required: true },
      { key: 'numero_bl', label: "Numéro de connaissement (B/L)", type: 'text', required: true },
      { key: 'navire', label: "Nom du navire transporteur", type: 'text', required: true },
      { key: 'description_cargaison', label: "Description de la cargaison", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DÉDOUANEMENT MARITIME</h1><p><strong>Importateur :</strong> {{importateur}}</p><p><strong>Commissionnaire en douane :</strong> {{commissionnaire}}</p><h2>Article 1 — Opération de dédouanement</h2><p>Le commissionnaire est mandaté pour procéder au dédouanement de la cargaison décrite ci-après : {{description_cargaison}}, arrivée à bord du navire : {{navire}}, sous connaissement N° : {{numero_bl}}</p><h2>Article 2 — Documents à fournir</h2><p>L'importateur remet au commissionnaire l'original du connaissement ou le télex release, la facture commerciale, la liste de colisage et tout certificat requis.</p><h2>Article 3 — Délai de mainlevée</h2><p>Le commissionnaire s'engage à déposer la déclaration en détail dans les meilleurs délais afin d'éviter les frais de surestarie au Port Autonome d'Abidjan.</p></div>`,
  },
  {
    code: 'douan_manifeste_electronique_sydonia',
    name: "Accord de service de manifeste électronique (SYDONIA)",
    category: 'transport_logistique',
    price: 4000,
    priceMax: 12000,
    description: "Accord de prestation pour la transmission électronique du manifeste de cargaison via le système SYDONIA World (CNUCED) utilisé par la Direction Générale des Douanes de Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'agent_maritime', label: "Agent maritime ou compagnie de transport", type: 'text', required: true },
      { key: 'prestataire_sydonia', label: "Prestataire de saisie SYDONIA", type: 'text', required: true },
      { key: 'moyen_transport', label: "Moyen de transport (navire/camion/avion)", type: 'text', required: true },
      { key: 'date_arrivee', label: "Date d'arrivée prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE MANIFESTE ÉLECTRONIQUE (SYDONIA)</h1><p><strong>Agent maritime :</strong> {{agent_maritime}}</p><p><strong>Prestataire SYDONIA :</strong> {{prestataire_sydonia}}</p><h2>Article 1 — Transmission du manifeste</h2><p>Le prestataire est mandaté pour transmettre électroniquement le manifeste de la cargaison arrivant par : {{moyen_transport}}, avant la date d'arrivée prévue du : {{date_arrivee}}</p><h2>Article 2 — Délai légal</h2><p>La transmission du manifeste électronique doit intervenir au minimum 24 heures avant l'arrivée pour les cargaisons maritimes, conformément aux dispositions du code des douanes ivoirien.</p><h2>Article 3 — Responsabilité</h2><p>L'agent maritime demeure responsable de l'exactitude et de l'exhaustivité des données du manifeste transmis.</p></div>`,
  },
  {
    code: 'douan_controle_valeur_cvam',
    name: "Accord de service de contrôle de valeur en douane (CVAM)",
    category: 'transport_logistique',
    price: 5000,
    priceMax: 15000,
    description: "Accord de prestation d'assistance lors d'un contrôle de la valeur en douane (CVAM) par les services douaniers, incluant la constitution du dossier justificatif et la négociation de transaction.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'importateur', label: "Raison sociale de l'importateur contrôlé", type: 'text', required: true },
      { key: 'conseil_douanier', label: "Conseil douanier mandaté", type: 'text', required: true },
      { key: 'declaration_controlee', label: "Numéro de la déclaration en douane contrôlée", type: 'text', required: true },
      { key: 'montant_litige', label: "Montant du redressement notifié", type: 'text', required: true },
      { key: 'documents_justificatifs', label: "Documents justificatifs produits", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CONTRÔLE DE VALEUR EN DOUANE (CVAM)</h1><p><strong>Importateur contrôlé :</strong> {{importateur}}</p><p><strong>Conseil douanier :</strong> {{conseil_douanier}}</p><h2>Article 1 — Contexte du contrôle</h2><p>L'importateur a reçu notification d'un contrôle de la valeur en douane portant sur la déclaration N° : {{declaration_controlee}}, pour un redressement notifié de : {{montant_litige}}</p><h2>Article 2 — Mission du conseil</h2><p>Le conseil est mandaté pour constituer le dossier de justification de la valeur transactionnelle et représenter l'importateur devant les services CVAM.</p><h2>Article 3 — Documents produits</h2><p>{{documents_justificatifs}}</p></div>`,
  },
  {
    code: 'douan_lutte_fraude_douaniere',
    name: "Accord de service de lutte contre la fraude douanière",
    category: 'transport_logistique',
    price: 6000,
    priceMax: 18000,
    description: "Accord de coopération entre un opérateur économique et les services douaniers pour la mise en place de dispositifs de prévention et de détection de la fraude douanière dans la chaîne logistique.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'operateur', label: "Raison sociale de l'opérateur économique", type: 'text', required: true },
      { key: 'service_douanier', label: "Service douanier partenaire", type: 'text', required: true },
      { key: 'dispositifs_prevention', label: "Dispositifs de prévention mis en place", type: 'textarea', required: true },
      { key: 'referent_antifraude', label: "Référent anti-fraude désigné", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE LUTTE CONTRE LA FRAUDE DOUANIÈRE</h1><p><strong>Opérateur économique :</strong> {{operateur}}</p><p><strong>Service douanier partenaire :</strong> {{service_douanier}}</p><h2>Article 1 — Dispositifs de prévention</h2><p>L'opérateur s'engage à mettre en place les dispositifs suivants pour prévenir toute fraude douanière dans sa chaîne logistique : {{dispositifs_prevention}}</p><h2>Article 2 — Référent anti-fraude</h2><p>Le référent anti-fraude désigné au sein de l'opérateur est : {{referent_antifraude}}</p><h2>Article 3 — Coopération</h2><p>L'opérateur s'engage à signaler sans délai tout soupçon de fraude douanière à son service douanier partenaire et à coopérer pleinement aux enquêtes diligentées.</p></div>`,
  },
  {
    code: 'douan_contentieux_transaction',
    name: "Accord de service de contentieux douanier (transaction)",
    category: 'transport_logistique',
    price: 7000,
    priceMax: 21000,
    description: "Accord de prestation d'assistance dans le cadre d'un contentieux douanier, visant à négocier une transaction amiable avec l'administration douanière conformément aux dispositions du code des douanes.",
    templateType: 'pdf',
    classe: 'A',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'contrevenant', label: "Raison sociale du contrevenant", type: 'text', required: true },
      { key: 'avocat_conseil', label: "Avocat ou conseil douanier mandaté", type: 'text', required: true },
      { key: 'nature_infraction', label: "Nature de l'infraction douanière reprochée", type: 'textarea', required: true },
      { key: 'amende_encourue', label: "Montant de l'amende douanière encourue", type: 'text', required: true },
      { key: 'proposition_transaction', label: "Montant proposé pour la transaction", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE CONTENTIEUX DOUANIER (TRANSACTION)</h1><p><strong>Contrevenant :</strong> {{contrevenant}}</p><p><strong>Conseil mandaté :</strong> {{avocat_conseil}}</p><h2>Article 1 — Infraction douanière</h2><p>Le présent accord porte sur le contentieux douanier relatif à l'infraction suivante : {{nature_infraction}}, pour laquelle l'amende douanière encourue est de : {{amende_encourue}}</p><h2>Article 2 — Proposition de transaction</h2><p>Le contrevenant propose de régler le contentieux par voie de transaction pour le montant de : {{proposition_transaction}}</p><h2>Article 3 — Effets de la transaction</h2><p>La transaction douanière, une fois acceptée et exécutée, éteint l'action publique douanière relative aux infractions visées dans le présent accord, conformément aux dispositions du code des douanes.</p></div>`,
  },
  {
    code: 'douan_plateforme_echange_electronique',
    name: "Accord de service de plateforme d'échange électronique douanier",
    category: 'transport_logistique',
    price: 5000,
    priceMax: 15000,
    description: "Accord de raccordement à la plateforme d'échange électronique de données douanières, permettant la transmission dématérialisée des déclarations, manifestes et documents d'accompagnement.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'utilisateur', label: "Raison sociale de l'utilisateur", type: 'text', required: true },
      { key: 'operateur_plateforme', label: "Opérateur de la plateforme d'échange", type: 'text', required: true },
      { key: 'flux_dematérialises', label: "Flux documentaires dématérialisés", type: 'textarea', required: true },
      { key: 'date_raccordement', label: "Date de raccordement prévue", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE PLATEFORME D'ÉCHANGE ÉLECTRONIQUE DOUANIER</h1><p><strong>Utilisateur :</strong> {{utilisateur}}</p><p><strong>Opérateur de la plateforme :</strong> {{operateur_plateforme}}</p><h2>Article 1 — Raccordement</h2><p>L'utilisateur est raccordé à la plateforme d'échange électronique à compter du : {{date_raccordement}}</p><h2>Article 2 — Flux dématérialisés</h2><p>Les flux documentaires traités via la plateforme sont les suivants : {{flux_dematérialises}}</p><h2>Article 3 — Sécurité des échanges</h2><p>Les échanges électroniques sont sécurisés par protocole de chiffrement conforme aux standards de la Direction Générale des Douanes de Côte d'Ivoire.</p></div>`,
  },
  {
    code: 'douan_dedouanement_aero',
    name: "Accord de service de dédouanement aéroportuaire",
    category: 'transport_logistique',
    price: 5500,
    priceMax: 16500,
    description: "Accord de prestation de dédouanement des marchandises transportées par voie aérienne à l'Aéroport International Félix Houphouët-Boigny d'Abidjan, avec gestion des formalités IATA et douanières.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'importateur_aero', label: "Raison sociale de l'importateur", type: 'text', required: true },
      { key: 'commissionnaire_aero', label: "Commissionnaire en douane aéroportuaire", type: 'text', required: true },
      { key: 'numero_awb', label: "Numéro de lettre de transport aérien (AWB)", type: 'text', required: true },
      { key: 'compagnie_aerienne', label: "Compagnie aérienne transporteur", type: 'text', required: true },
      { key: 'contenu_envoi', label: "Contenu de l'envoi aérien", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE DÉDOUANEMENT AÉROPORTUAIRE</h1><p><strong>Importateur :</strong> {{importateur_aero}}</p><p><strong>Commissionnaire aéroportuaire :</strong> {{commissionnaire_aero}}</p><h2>Article 1 — Objet du dédouanement</h2><p>Le commissionnaire est mandaté pour dédouaner l'envoi aérien suivant : {{contenu_envoi}}, transporté par : {{compagnie_aerienne}}, sous AWB N° : {{numero_awb}}</p><h2>Article 2 — Lieu d'intervention</h2><p>Les formalités sont accomplies auprès du bureau de douane de l'Aéroport International Félix Houphouët-Boigny d'Abidjan.</p><h2>Article 3 — Délai</h2><p>Le commissionnaire s'engage à initier les formalités de dédouanement dans les 24 heures suivant la réception des documents et la disponibilité des marchandises en entrepôt de fret aérien.</p></div>`,
  },
  {
    code: 'douan_tec_cedeao',
    name: "Accord de service de tarif douanier commun CEDEAO (TEC)",
    category: 'transport_logistique',
    price: 4500,
    priceMax: 13500,
    description: "Accord de prestation de conseil et d'assistance pour l'application du Tarif Extérieur Commun de la CEDEAO (TEC-CEDEAO) aux opérations d'importation dans l'espace communautaire ouest-africain.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'importateur', label: "Raison sociale de l'importateur", type: 'text', required: true },
      { key: 'conseil_tarifaire', label: "Cabinet ou conseil tarifaire mandaté", type: 'text', required: true },
      { key: 'produits_importes', label: "Produits concernés par la classification TEC", type: 'textarea', required: true },
      { key: 'categorie_tec', label: "Catégorie TEC-CEDEAO applicable (0 à 5)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE TARIF DOUANIER COMMUN CEDEAO (TEC)</h1><p><strong>Importateur :</strong> {{importateur}}</p><p><strong>Conseil tarifaire :</strong> {{conseil_tarifaire}}</p><h2>Article 1 — Classification tarifaire</h2><p>Le conseil tarifaire est mandaté pour déterminer la classification tarifaire des produits suivants au regard du TEC-CEDEAO : {{produits_importes}}</p><h2>Article 2 — Catégorie TEC applicable</h2><p>La catégorie TEC-CEDEAO applicable est la catégorie : {{categorie_tec}}, avec le taux de droit de douane correspondant.</p><h2>Article 3 — Avis motivé</h2><p>Le conseil remettra un avis tarifaire écrit et motivé, opposable dans les relations avec l'administration douanière, dans un délai de 5 jours ouvrables.</p></div>`,
  },
  {
    code: 'douan_rapport_perf_commissionnaire',
    name: "Rapport de performance commissionnaire en douane",
    category: 'transport_logistique',
    price: 3000,
    priceMax: 9000,
    description: "Rapport périodique d'évaluation de la performance d'un commissionnaire en douane agréé : délais de dédouanement, taux d'incidents, économies réalisées et recommandations d'amélioration.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'client', label: "Raison sociale du client évalué", type: 'text', required: true },
      { key: 'commissionnaire', label: "Commissionnaire en douane évalué", type: 'text', required: true },
      { key: 'periode_rapport', label: "Période couverte par le rapport", type: 'text', required: true },
      { key: 'nombre_declarations', label: "Nombre de déclarations traitées", type: 'text', required: true },
      { key: 'delai_moyen_dedouanement', label: "Délai moyen de dédouanement", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE COMMISSIONNAIRE EN DOUANE</h1><p><strong>Client :</strong> {{client}}</p><p><strong>Commissionnaire évalué :</strong> {{commissionnaire}}</p><p><strong>Période :</strong> {{periode_rapport}}</p><h2>1. Volume d'activité</h2><p>Nombre de déclarations en douane traitées sur la période : {{nombre_declarations}}</p><h2>2. Délais de dédouanement</h2><p>Délai moyen de dédouanement observé : {{delai_moyen_dedouanement}}</p><h2>3. Analyse des incidents</h2><p>Synthèse des incidents douaniers survenus sur la période (contrôles, redressements, pénalités) et mesures correctives mises en place.</p><h2>4. Recommandations</h2><p>Actions prioritaires recommandées pour optimiser les performances douanières sur la période suivante.</p></div>`,
  },
  {
    code: 'douan_plan_conformite_entreprise',
    name: "Plan de conformité douanière entreprise",
    category: 'transport_logistique',
    price: 5000,
    priceMax: 15000,
    description: "Document stratégique définissant les procédures internes, les responsabilités et le calendrier d'audit pour assurer la conformité douanière continue d'une entreprise importatrice ou exportatrice.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'entreprise', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'responsable_conformite', label: "Responsable conformité douanière désigné", type: 'text', required: true },
      { key: 'risques_identifies', label: "Risques douaniers identifiés", type: 'textarea', required: true },
      { key: 'mesures_mises_en_place', label: "Mesures de conformité mises en place", type: 'textarea', required: true },
      { key: 'calendrier_audit', label: "Calendrier des audits de conformité", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>PLAN DE CONFORMITÉ DOUANIÈRE ENTREPRISE</h1><p><strong>Entreprise :</strong> {{entreprise}}</p><p><strong>Responsable conformité :</strong> {{responsable_conformite}}</p><h2>1. Cartographie des risques</h2><p>Risques douaniers identifiés : {{risques_identifies}}</p><h2>2. Mesures de conformité</h2><p>{{mesures_mises_en_place}}</p><h2>3. Calendrier d'audits</h2><p>{{calendrier_audit}}</p><h2>4. Gouvernance</h2><p>Le responsable conformité douanière rend compte trimestriellement à la Direction Générale de l'état de conformité douanière de l'entreprise et propose les ajustements nécessaires au présent plan.</p></div>`,
  },
  {
    code: 'douan_formation_reglementation',
    name: "Accord de service de formation en réglementation douanière",
    category: 'transport_logistique',
    price: 4000,
    priceMax: 12000,
    description: "Accord de prestation de formation professionnelle sur la réglementation douanière ivoirienne et communautaire CEDEAO/UEMOA, destinée aux équipes logistiques et commerciales des entreprises.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'entreprise_cliente', label: "Raison sociale de l'entreprise cliente", type: 'text', required: true },
      { key: 'organisme_formation', label: "Organisme de formation douanière", type: 'text', required: true },
      { key: 'thematiques', label: "Thématiques de formation retenues", type: 'textarea', required: true },
      { key: 'nombre_stagiaires', label: "Nombre de stagiaires prévus", type: 'text', required: true },
      { key: 'date_formation', label: "Date de la formation", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SERVICE DE FORMATION EN RÉGLEMENTATION DOUANIÈRE</h1><p><strong>Entreprise cliente :</strong> {{entreprise_cliente}}</p><p><strong>Organisme de formation :</strong> {{organisme_formation}}</p><h2>Article 1 — Programme de formation</h2><p>L'organisme s'engage à dispenser une formation sur les thématiques suivantes : {{thematiques}}, au profit de : {{nombre_stagiaires}} stagiaire(s) désignés par l'entreprise.</p><h2>Article 2 — Date et lieu</h2><p>La formation se tient le : {{date_formation}}</p><h2>Article 3 — Évaluation</h2><p>À l'issue de la formation, une évaluation des acquis est réalisée et une attestation de participation est remise à chaque stagiaire ayant satisfait aux conditions de présence.</p></div>`,
  },
  {
    code: 'douan_partenariat_douane_prive',
    name: "Accord de partenariat douane-secteur privé",
    category: 'transport_logistique',
    price: 4500,
    priceMax: 13500,
    description: "Accord de coopération formalisé entre la Direction Générale des Douanes de Côte d'Ivoire et une organisation professionnelle du secteur privé, pour l'amélioration du climat des affaires et la lutte contre la fraude.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'organisation_privee', label: "Organisation professionnelle du secteur privé", type: 'text', required: true },
      { key: 'dgd', label: "Entité douanière partenaire (DGD-CI)", type: 'text', required: true },
      { key: 'objectifs_partenariat', label: "Objectifs du partenariat douane-privé", type: 'textarea', required: true },
      { key: 'comite_suivi', label: "Composition du comité de suivi", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE PARTENARIAT DOUANE — SECTEUR PRIVÉ</h1><p><strong>Organisation professionnelle :</strong> {{organisation_privee}}</p><p><strong>Entité douanière partenaire :</strong> {{dgd}}</p><h2>Article 1 — Objectifs du partenariat</h2><p>Les parties s'engagent à collaborer en vue d'atteindre les objectifs suivants : {{objectifs_partenariat}}</p><h2>Article 2 — Comité de suivi</h2><p>Un comité paritaire de suivi est institué avec la composition suivante : {{comite_suivi}}</p><h2>Article 3 — Durée et renouvellement</h2><p>Le présent partenariat est conclu pour une durée d'un an, renouvelable par tacite reconduction après évaluation conjointe des résultats obtenus.</p></div>`,
  },
  {
    code: 'douan_charte_commerce_transfrontalier',
    name: "Charte du commerce transfrontalier facilité",
    category: 'transport_logistique',
    price: 2500,
    priceMax: 7500,
    description: "Document d'engagement collectif signé par les acteurs du commerce transfrontalier (commerçants, transporteurs, administrations) pour faciliter et sécuriser les échanges aux postes frontières.",
    templateType: 'pdf',
    classe: 'C',
    active: true,
    popularity: 46,
    fieldsJson: F([
      { key: 'signataires', label: "Parties signataires de la charte", type: 'textarea', required: true },
      { key: 'postes_frontiere', label: "Postes frontières concernés", type: 'text', required: true },
      { key: 'date_signature_charte', label: "Date de signature de la charte", type: 'date', required: true },
      { key: 'engagements_communs', label: "Engagements communs des signataires", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>CHARTE DU COMMERCE TRANSFRONTALIER FACILITÉ</h1><p><strong>Postes frontières concernés :</strong> {{postes_frontiere}}</p><p><strong>Signataires :</strong> {{signataires}}</p><h2>Préambule</h2><p>Convaincus que la facilitation du commerce transfrontalier est un moteur d'intégration régionale et de développement économique, les signataires adoptent la présente charte.</p><h2>Engagements communs</h2><p>{{engagements_communs}}</p><h2>Principes directeurs</h2><p>Les signataires s'engagent à : respecter la dignité des opérateurs transfrontaliers, lutter contre le harcèlement aux postes frontières, appliquer les tarifs officiels et faciliter la fluidité des échanges dans le respect des réglementations nationales et communautaires.</p><p><strong>Fait aux postes frontières concernés, le :</strong> {{date_signature_charte}}</p></div>`,
  },
];
async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 75b OK — créés:${created} maj:${updated} TOTAL:${total}`);
}
main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
