import { PrismaClient } from '@prisma/client';
const prisma = new PrismaClient();
const F = (f: object[]) => JSON.stringify(f);
const templates = [
  // ─── ASSURANCE VIE (25 templates) ───────────────────────────────────────────
  {
    code: 'avie_capitalisation_individuel',
    name: "Contrat d'assurance vie individuel (capitalisation)",
    category: 'assurance',
    price: 8000,
    priceMax: 24000,
    description: "Contrat d'assurance vie individuel à vocation d'épargne et de capitalisation, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 80,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom complet du souscripteur", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance du souscripteur", type: 'date', required: true },
      { key: 'prime_periodique', label: "Montant de la prime périodique (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (en années)", type: 'text', required: true },
      { key: 'beneficiaire_nom', label: "Nom du bénéficiaire désigné", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE VIE INDIVIDUEL — CAPITALISATION</h1><p>Entre la compagnie d'assurance soussignée, d'une part, et <strong>{{souscripteur_nom}}</strong>, né(e) le {{date_naissance}}, d'autre part.</p><h2>Article 1 — Objet</h2><p>Le présent contrat a pour objet la constitution d'une épargne par versement de primes périodiques d'un montant de <strong>{{prime_periodique}} FCFA</strong>, pour une durée de <strong>{{duree_contrat}} ans</strong>.</p><h2>Article 2 — Bénéficiaire</h2><p>En cas de décès du souscripteur, le capital constitué sera versé à <strong>{{beneficiaire_nom}}</strong>.</p><h2>Article 3 — Droit applicable</h2><p>Le présent contrat est régi par le Code des Assurances CIMA et les lois en vigueur en Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_mixte_deces_epargne',
    name: "Contrat d'assurance vie mixte (décès et épargne)",
    category: 'assurance',
    price: 9000,
    priceMax: 27000,
    description: "Contrat combinant une garantie décès et une épargne, conforme au Code CIMA pour l'espace francophone africain.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 75,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom complet du souscripteur", type: 'text', required: true },
      { key: 'capital_deces', label: "Capital garanti en cas de décès (FCFA)", type: 'text', required: true },
      { key: 'prime_mensuelle', label: "Prime mensuelle (FCFA)", type: 'text', required: true },
      { key: 'duree_contrat', label: "Durée du contrat (en années)", type: 'text', required: true },
      { key: 'beneficiaire_nom', label: "Nom du bénéficiaire", type: 'text', required: true },
      { key: 'date_effet', label: "Date d'effet du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE VIE MIXTE — DÉCÈS ET ÉPARGNE</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong> — Prise d'effet : {{date_effet}}</p><h2>Article 1 — Garantie décès</h2><p>En cas de décès de l'assuré avant le terme, un capital de <strong>{{capital_deces}} FCFA</strong> est versé à <strong>{{beneficiaire_nom}}</strong>.</p><h2>Article 2 — Garantie épargne</h2><p>En cas de vie au terme, le souscripteur perçoit le capital constitué par les primes mensuelles de <strong>{{prime_mensuelle}} FCFA</strong> versées pendant <strong>{{duree_contrat}} ans</strong>, majorées des intérêts capitalisés.</p><h2>Article 3 — Droit applicable</h2><p>Contrat régi par le Code CIMA et les textes nationaux en vigueur.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_deces_temporaire',
    name: "Contrat d'assurance décès temporaire",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Contrat d'assurance décès à durée limitée couvrant le risque de décès de l'assuré pendant la période garantie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'capital_garanti', label: "Capital garanti (FCFA)", type: 'text', required: true },
      { key: 'duree_garantie', label: "Durée de la garantie (en années)", type: 'text', required: true },
      { key: 'beneficiaire_nom', label: "Bénéficiaire en cas de décès", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE DÉCÈS TEMPORAIRE</h1><p>Assuré : <strong>{{assure_nom}}</strong></p><h2>Article 1 — Garantie</h2><p>La compagnie garantit le paiement d'un capital de <strong>{{capital_garanti}} FCFA</strong> au bénéficiaire <strong>{{beneficiaire_nom}}</strong> si l'assuré décède dans un délai de <strong>{{duree_garantie}} ans</strong> à compter de la date d'effet.</p><h2>Article 2 — Exclusions</h2><p>Sont exclus : le suicide dans la première année, le décès résultant d'une guerre déclarée ou d'un acte terroriste.</p><h2>Article 3 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_deces_permanente',
    name: "Contrat d'assurance décès permanente",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Contrat d'assurance décès vie entière garantissant le paiement d'un capital quel que soit le moment du décès.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance de l'assuré", type: 'date', required: true },
      { key: 'capital_garanti', label: "Capital garanti (FCFA)", type: 'text', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle (FCFA)", type: 'text', required: true },
      { key: 'beneficiaire_nom', label: "Nom du bénéficiaire", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE DÉCÈS PERMANENTE (VIE ENTIÈRE)</h1><p>Assuré : <strong>{{assure_nom}}</strong>, né(e) le {{date_naissance}}</p><h2>Article 1 — Objet</h2><p>La compagnie garantit le versement d'un capital de <strong>{{capital_garanti}} FCFA</strong> au bénéficiaire <strong>{{beneficiaire_nom}}</strong> au moment du décès de l'assuré, quelle qu'en soit la date.</p><h2>Article 2 — Prime</h2><p>La prime annuelle est fixée à <strong>{{prime_annuelle}} FCFA</strong>, payable jusqu'au décès de l'assuré ou jusqu'à l'âge limite fixé aux conditions particulières.</p><h2>Article 3 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_universelle',
    name: "Contrat d'assurance vie universelle",
    category: 'assurance',
    price: 10000,
    priceMax: 30000,
    description: "Contrat d'assurance vie flexible à capital variable, combinant épargne et protection décès avec gestion personnalisée des primes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom complet du souscripteur", type: 'text', required: true },
      { key: 'prime_initiale', label: "Prime initiale versée (FCFA)", type: 'text', required: true },
      { key: 'capital_deces_minimum', label: "Capital décès minimum garanti (FCFA)", type: 'text', required: true },
      { key: 'taux_rendement', label: "Taux de rendement garanti (%)", type: 'text', required: true },
      { key: 'beneficiaire_nom', label: "Bénéficiaire désigné", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE VIE UNIVERSELLE</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong></p><h2>Article 1 — Fonctionnement</h2><p>Le présent contrat permet des versements flexibles. La prime initiale est de <strong>{{prime_initiale}} FCFA</strong>. Le capital décès minimum garanti est de <strong>{{capital_deces_minimum}} FCFA</strong>.</p><h2>Article 2 — Rendement</h2><p>Le taux de rendement garanti minimal est de <strong>{{taux_rendement}}%</strong> par an, appliqué à la valeur de rachat du contrat.</p><h2>Article 3 — Bénéficiaire</h2><p>Le bénéficiaire désigné est <strong>{{beneficiaire_nom}}</strong>.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_designation_beneficiaire',
    name: "Accord de désignation de bénéficiaire",
    category: 'assurance',
    price: 3000,
    priceMax: 9000,
    description: "Acte de désignation ou de modification du bénéficiaire d'un contrat d'assurance vie, opposable à la compagnie.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'numero_police', label: "Numéro de police d'assurance", type: 'text', required: true },
      { key: 'beneficiaire_nom', label: "Nom complet du nouveau bénéficiaire", type: 'text', required: true },
      { key: 'lien_parente', label: "Lien de parenté avec le souscripteur", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DÉSIGNATION DE BÉNÉFICIAIRE</h1><p>Je soussigné(e) <strong>{{souscripteur_nom}}</strong>, souscripteur de la police n° <strong>{{numero_police}}</strong>, désigne par le présent acte :</p><p><strong>{{beneficiaire_nom}}</strong>, ayant la qualité de <strong>{{lien_parente}}</strong>, comme bénéficiaire du capital ou de la rente stipulés au contrat susvisé.</p><h2>Article 1 — Acceptation</h2><p>La présente désignation prend effet dès réception par la compagnie et sous réserve de l'acceptation du bénéficiaire si celui-ci a déjà accepté le bénéfice du contrat.</p><h2>Article 2 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_modification_beneficiaire',
    name: "Accord de modification de bénéficiaire",
    category: 'assurance',
    price: 3000,
    priceMax: 9000,
    description: "Acte de modification du bénéficiaire antérieurement désigné dans un contrat d'assurance vie, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'numero_police', label: "Numéro de police", type: 'text', required: true },
      { key: 'ancien_beneficiaire', label: "Ancien bénéficiaire (à révoquer)", type: 'text', required: true },
      { key: 'nouveau_beneficiaire', label: "Nouveau bénéficiaire désigné", type: 'text', required: true },
      { key: 'motif_modification', label: "Motif de la modification", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE MODIFICATION DE BÉNÉFICIAIRE</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong> — Police n° <strong>{{numero_police}}</strong></p><h2>Article 1 — Révocation</h2><p>La désignation antérieure de <strong>{{ancien_beneficiaire}}</strong> est révoquée par le présent acte.</p><h2>Article 2 — Nouvelle désignation</h2><p>Le souscripteur désigne désormais <strong>{{nouveau_beneficiaire}}</strong> comme bénéficiaire.</p><h2>Article 3 — Motif</h2><p>{{motif_modification}}</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_rachat_partiel',
    name: "Accord de rachat partiel d'assurance vie",
    category: 'assurance',
    price: 4000,
    priceMax: 12000,
    description: "Demande et accord de rachat partiel de la valeur de rachat d'un contrat d'assurance vie, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'numero_police', label: "Numéro de police", type: 'text', required: true },
      { key: 'montant_rachat', label: "Montant du rachat partiel demandé (FCFA)", type: 'text', required: true },
      { key: 'motif_rachat', label: "Motif du rachat partiel", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RACHAT PARTIEL D'ASSURANCE VIE</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong> — Police n° <strong>{{numero_police}}</strong></p><h2>Article 1 — Demande de rachat partiel</h2><p>Le souscripteur demande le rachat partiel d'un montant de <strong>{{montant_rachat}} FCFA</strong> sur la valeur de rachat de son contrat.</p><h2>Article 2 — Motif</h2><p>{{motif_rachat}}</p><h2>Article 3 — Effets</h2><p>Le rachat partiel réduit proportionnellement la valeur de rachat et les garanties du contrat. La compagnie procède au versement dans un délai de trente (30) jours ouvrés.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_rachat_total',
    name: "Accord de rachat total d'assurance vie",
    category: 'assurance',
    price: 4000,
    priceMax: 12000,
    description: "Demande et accord de rachat total entraînant la résiliation du contrat d'assurance vie, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'numero_police', label: "Numéro de police", type: 'text', required: true },
      { key: 'valeur_rachat_estimee', label: "Valeur de rachat estimée (FCFA)", type: 'text', required: true },
      { key: 'motif_resiliation', label: "Motif de résiliation du contrat", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RACHAT TOTAL D'ASSURANCE VIE</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong> — Police n° <strong>{{numero_police}}</strong></p><h2>Article 1 — Demande de rachat total</h2><p>Le souscripteur demande le rachat total de son contrat. La valeur de rachat estimée est de <strong>{{valeur_rachat_estimee}} FCFA</strong>.</p><h2>Article 2 — Motif</h2><p>{{motif_resiliation}}</p><h2>Article 3 — Effets</h2><p>Le rachat total entraîne la résiliation définitive du contrat. Toutes les garanties prennent fin à la date de versement du montant de rachat.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_avance_sur_police',
    name: "Accord d'avance sur police d'assurance vie",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Contrat d'avance consentie par la compagnie sur la valeur de rachat d'une police d'assurance vie, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'numero_police', label: "Numéro de police", type: 'text', required: true },
      { key: 'montant_avance', label: "Montant de l'avance accordée (FCFA)", type: 'text', required: true },
      { key: 'taux_interet', label: "Taux d'intérêt de l'avance (%)", type: 'text', required: true },
      { key: 'duree_avance', label: "Durée maximale de l'avance (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD D'AVANCE SUR POLICE D'ASSURANCE VIE</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong> — Police n° <strong>{{numero_police}}</strong></p><h2>Article 1 — Objet</h2><p>La compagnie consent une avance de <strong>{{montant_avance}} FCFA</strong> sur la valeur de rachat du contrat.</p><h2>Article 2 — Conditions financières</h2><p>L'avance porte intérêt au taux de <strong>{{taux_interet}}%</strong> par an et est remboursable dans un délai maximum de <strong>{{duree_avance}} mois</strong>.</p><h2>Article 3 — Garantie</h2><p>L'avance est garantie par la valeur de rachat du contrat. À défaut de remboursement, la compagnie procède au rachat partiel ou total du contrat.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_nantissement_police',
    name: "Accord de nantissement de police d'assurance vie",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Acte de nantissement d'une police d'assurance vie au profit d'un créancier, conforme au droit OHADA et au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur (débiteur)", type: 'text', required: true },
      { key: 'numero_police', label: "Numéro de police nantie", type: 'text', required: true },
      { key: 'creancier_nom', label: "Nom du créancier bénéficiaire du nantissement", type: 'text', required: true },
      { key: 'montant_creance', label: "Montant de la créance garantie (FCFA)", type: 'text', required: true },
      { key: 'date_echeance', label: "Date d'échéance de la créance", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE NANTISSEMENT DE POLICE D'ASSURANCE VIE</h1><p>Entre <strong>{{souscripteur_nom}}</strong> (débiteur) et <strong>{{creancier_nom}}</strong> (créancier).</p><h2>Article 1 — Nantissement</h2><p>Le souscripteur nantit la police n° <strong>{{numero_police}}</strong> au profit de <strong>{{creancier_nom}}</strong> pour garantir une créance de <strong>{{montant_creance}} FCFA</strong> échéant le {{date_echeance}}.</p><h2>Article 2 — Notification</h2><p>La compagnie d'assurance est notifiée du présent nantissement et ne pourra procéder à aucun rachat sans l'accord préalable du créancier nanti.</p><h2>Article 3 — Droit applicable</h2><p>Acte uniforme OHADA sur les sûretés — Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_cession_police',
    name: "Accord de cession de police d'assurance vie",
    category: 'assurance',
    price: 7000,
    priceMax: 21000,
    description: "Acte de cession de la police d'assurance vie par le souscripteur à un cessionnaire, conforme au Code CIMA et au droit OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 52,
    fieldsJson: F([
      { key: 'cedant_nom', label: "Nom du cédant (souscripteur initial)", type: 'text', required: true },
      { key: 'cessionnaire_nom', label: "Nom du cessionnaire", type: 'text', required: true },
      { key: 'numero_police', label: "Numéro de police cédée", type: 'text', required: true },
      { key: 'prix_cession', label: "Prix de cession (FCFA)", type: 'text', required: true },
      { key: 'date_cession', label: "Date de prise d'effet de la cession", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE CESSION DE POLICE D'ASSURANCE VIE</h1><p>Entre <strong>{{cedant_nom}}</strong> (cédant) et <strong>{{cessionnaire_nom}}</strong> (cessionnaire).</p><h2>Article 1 — Cession</h2><p>Le cédant cède au cessionnaire, qui accepte, la totalité de ses droits sur la police d'assurance vie n° <strong>{{numero_police}}</strong>, pour un prix de <strong>{{prix_cession}} FCFA</strong>, à compter du {{date_cession}}.</p><h2>Article 2 — Obligations du cessionnaire</h2><p>Le cessionnaire reprend à sa charge le paiement des primes futures et devient titulaire de tous les droits attachés à la police.</p><h2>Article 3 — Notification</h2><p>La compagnie est notifiée de la présente cession par lettre recommandée avec accusé de réception.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — OHADA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_prevoyance_invalidite',
    name: "Contrat de prévoyance individuel (invalidité)",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Contrat de prévoyance couvrant le risque d'invalidité totale ou partielle de l'assuré, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'profession', label: "Profession de l'assuré", type: 'text', required: true },
      { key: 'rente_mensuelle', label: "Rente mensuelle en cas d'invalidité (FCFA)", type: 'text', required: true },
      { key: 'taux_invalidite_seuil', label: "Taux d'invalidité ouvrant droit à la rente (%)", type: 'text', required: true },
      { key: 'duree_garantie', label: "Durée de la garantie (en années)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE PRÉVOYANCE INDIVIDUEL — INVALIDITÉ</h1><p>Assuré : <strong>{{assure_nom}}</strong> — Profession : <strong>{{profession}}</strong></p><h2>Article 1 — Objet</h2><p>La compagnie garantit le versement d'une rente mensuelle de <strong>{{rente_mensuelle}} FCFA</strong> si l'assuré subit une invalidité égale ou supérieure à <strong>{{taux_invalidite_seuil}}%</strong>.</p><h2>Article 2 — Durée</h2><p>La garantie court pendant <strong>{{duree_garantie}} ans</strong> à compter de la date d'effet du contrat.</p><h2>Article 3 — Franchise</h2><p>Une franchise de quatre-vingt-dix (90) jours s'applique avant le versement de la rente.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_ipt',
    name: "Contrat d'assurance invalidité permanente et totale (IPT)",
    category: 'assurance',
    price: 7000,
    priceMax: 20000,
    description: "Contrat garantissant le versement d'un capital en cas d'invalidité permanente et totale (IPT) de l'assuré, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 63,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'capital_ipt', label: "Capital garanti en cas d'IPT (FCFA)", type: 'text', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle (FCFA)", type: 'text', required: true },
      { key: 'definition_ipt', label: "Définition contractuelle de l'IPT retenue", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE INVALIDITÉ PERMANENTE ET TOTALE (IPT)</h1><p>Assuré : <strong>{{assure_nom}}</strong></p><h2>Article 1 — Définition de l'IPT</h2><p>{{definition_ipt}}</p><h2>Article 2 — Garantie</h2><p>En cas de reconnaissance de l'état d'IPT de l'assuré, la compagnie verse un capital de <strong>{{capital_ipt}} FCFA</strong> en une seule fois.</p><h2>Article 3 — Prime</h2><p>La prime annuelle est fixée à <strong>{{prime_annuelle}} FCFA</strong>.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_perte_emploi',
    name: "Contrat d'assurance perte d'emploi",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Contrat garantissant le maintien de revenus en cas de perte involontaire d'emploi, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 61,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'employeur_nom', label: "Employeur actuel", type: 'text', required: true },
      { key: 'revenu_mensuel', label: "Revenu mensuel brut (FCFA)", type: 'text', required: true },
      { key: 'indemnite_mensuelle', label: "Indemnité mensuelle garantie (FCFA)", type: 'text', required: true },
      { key: 'duree_indemnisation', label: "Durée maximale d'indemnisation (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE PERTE D'EMPLOI</h1><p>Assuré : <strong>{{assure_nom}}</strong> — Employeur : <strong>{{employeur_nom}}</strong></p><h2>Article 1 — Garantie</h2><p>En cas de perte involontaire d'emploi (licenciement économique ou fermeture d'entreprise), la compagnie verse une indemnité mensuelle de <strong>{{indemnite_mensuelle}} FCFA</strong> pendant une durée maximale de <strong>{{duree_indemnisation}} mois</strong>.</p><h2>Article 2 — Conditions d'éligibilité</h2><p>L'assuré doit justifier d'un revenu mensuel brut de <strong>{{revenu_mensuel}} FCFA</strong> et d'une ancienneté minimale de douze (12) mois dans l'entreprise.</p><h2>Article 3 — Exclusions</h2><p>Sont exclus : la démission, la retraite, la rupture conventionnelle à l'initiative de l'assuré.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_rente_viagere',
    name: "Contrat de rente viagère",
    category: 'assurance',
    price: 8000,
    priceMax: 24000,
    description: "Contrat garantissant le versement d'une rente viagère à l'assuré jusqu'à son décès, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 59,
    fieldsJson: F([
      { key: 'rentier_nom', label: "Nom du rentier (bénéficiaire de la rente)", type: 'text', required: true },
      { key: 'capital_constitutif', label: "Capital constitutif versé (FCFA)", type: 'text', required: true },
      { key: 'rente_mensuelle', label: "Montant de la rente mensuelle (FCFA)", type: 'text', required: true },
      { key: 'date_premier_versement', label: "Date du premier versement de rente", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE RENTE VIAGÈRE</h1><p>Bénéficiaire : <strong>{{rentier_nom}}</strong></p><h2>Article 1 — Constitution</h2><p>En contrepartie du versement d'un capital constitutif de <strong>{{capital_constitutif}} FCFA</strong>, la compagnie s'engage à verser une rente mensuelle viagère de <strong>{{rente_mensuelle}} FCFA</strong> au profit de <strong>{{rentier_nom}}</strong>.</p><h2>Article 2 — Premier versement</h2><p>Le premier versement est effectué le {{date_premier_versement}} et sera maintenu jusqu'au décès du bénéficiaire.</p><h2>Article 3 — Réversion</h2><p>Les conditions de réversion éventuelle au profit du conjoint survivant sont précisées aux conditions particulières.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_rente_education',
    name: "Contrat de rente temporaire d'éducation",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Contrat garantissant le versement d'une rente temporaire pour financer les études des enfants en cas de décès de l'assuré.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 67,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré (parent)", type: 'text', required: true },
      { key: 'enfants_beneficiaires', label: "Nom(s) et date(s) de naissance des enfants", type: 'textarea', required: true },
      { key: 'rente_annuelle', label: "Rente annuelle par enfant (FCFA)", type: 'text', required: true },
      { key: 'age_limite', label: "Âge limite des enfants pour la rente", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE RENTE TEMPORAIRE D'ÉDUCATION</h1><p>Assuré : <strong>{{assure_nom}}</strong></p><h2>Article 1 — Objet</h2><p>En cas de décès de l'assuré, la compagnie verse une rente annuelle de <strong>{{rente_annuelle}} FCFA</strong> par enfant bénéficiaire, jusqu'à l'âge de <strong>{{age_limite}} ans</strong>.</p><h2>Article 2 — Bénéficiaires</h2><p>{{enfants_beneficiaires}}</p><h2>Article 3 — Indexation</h2><p>La rente est revalorisée annuellement selon l'indice des prix à la consommation publié par l'INS de Côte d'Ivoire.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_per_individuel_cima',
    name: "Contrat de retraite supplémentaire individuelle (PER individuel CIMA)",
    category: 'assurance',
    price: 10000,
    priceMax: 30000,
    description: "Plan d'épargne retraite individuel conforme aux dispositions du Code CIMA relatives aux contrats de capitalisation à long terme.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 71,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance", type: 'date', required: true },
      { key: 'age_retraite_vise', label: "Âge de départ à la retraite visé", type: 'text', required: true },
      { key: 'versement_initial', label: "Versement initial (FCFA)", type: 'text', required: true },
      { key: 'versements_periodiques', label: "Versements périodiques prévus (FCFA/mois)", type: 'text', required: false },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE RETRAITE SUPPLÉMENTAIRE INDIVIDUELLE — PER INDIVIDUEL CIMA</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong>, né(e) le {{date_naissance}}</p><h2>Article 1 — Objet</h2><p>Le présent plan d'épargne retraite a pour objet la constitution d'une épargne en vue de la retraite prévue à l'âge de <strong>{{age_retraite_vise}} ans</strong>.</p><h2>Article 2 — Versements</h2><p>Le versement initial est de <strong>{{versement_initial}} FCFA</strong>. Des versements périodiques de <strong>{{versements_periodiques}} FCFA/mois</strong> sont prévus.</p><h2>Article 3 — Sortie</h2><p>À l'échéance, le souscripteur peut opter pour une sortie en capital, en rente, ou une combinaison des deux, selon les modalités fixées aux conditions particulières.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_retraite_collective_83',
    name: "Contrat de retraite collective entreprise (article 83 CIMA)",
    category: 'assurance',
    price: 12000,
    priceMax: 36000,
    description: "Contrat collectif de retraite supplémentaire souscrit par une entreprise au bénéfice de ses salariés, conforme à l'article 83 du Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 64,
    fieldsJson: F([
      { key: 'entreprise_nom', label: "Raison sociale de l'entreprise souscriptrice", type: 'text', required: true },
      { key: 'nombre_salaries', label: "Nombre de salariés bénéficiaires", type: 'text', required: true },
      { key: 'cotisation_employeur', label: "Cotisation patronale par salarié/mois (FCFA)", type: 'text', required: true },
      { key: 'cotisation_salarie', label: "Cotisation salariale par salarié/mois (FCFA)", type: 'text', required: false },
      { key: 'date_mise_en_place', label: "Date de mise en place du contrat", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT DE RETRAITE COLLECTIVE ENTREPRISE — ARTICLE 83 CIMA</h1><p>Souscripteur : <strong>{{entreprise_nom}}</strong> — Nombre de bénéficiaires : <strong>{{nombre_salaries}}</strong></p><h2>Article 1 — Objet</h2><p>L'entreprise souscrit, à compter du {{date_mise_en_place}}, un contrat collectif de retraite supplémentaire au bénéfice de l'ensemble de ses salariés.</p><h2>Article 2 — Cotisations</h2><p>La cotisation patronale est de <strong>{{cotisation_employeur}} FCFA/mois/salarié</strong>. La cotisation salariale éventuelle est de <strong>{{cotisation_salarie}} FCFA/mois/salarié</strong>.</p><h2>Article 3 — Droits individuels</h2><p>Chaque salarié dispose d'un compte individuel retraite. Les droits acquis sont transférables en cas de départ de l'entreprise.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA, article 83 — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_sortie_capital_retraite',
    name: "Accord de sortie en capital retraite",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Accord formalisant la demande et les modalités de sortie en capital d'un contrat de retraite supplémentaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom du bénéficiaire à la retraite", type: 'text', required: true },
      { key: 'numero_contrat', label: "Numéro de contrat retraite", type: 'text', required: true },
      { key: 'capital_acquis', label: "Capital retraite acquis (FCFA)", type: 'text', required: true },
      { key: 'date_retraite', label: "Date de départ à la retraite", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SORTIE EN CAPITAL RETRAITE</h1><p>Bénéficiaire : <strong>{{assure_nom}}</strong> — Contrat n° <strong>{{numero_contrat}}</strong></p><h2>Article 1 — Demande</h2><p>Le bénéficiaire, ayant atteint l'âge de retraite le {{date_retraite}}, demande la liquidation de son contrat sous forme d'un versement unique en capital.</p><h2>Article 2 — Montant</h2><p>Le capital retraite acquis s'élève à <strong>{{capital_acquis}} FCFA</strong>, incluant les primes versées et les intérêts capitalisés.</p><h2>Article 3 — Fiscalité</h2><p>Le versement est soumis aux dispositions fiscales en vigueur en Côte d'Ivoire au moment de la liquidation.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_sortie_rente_retraite',
    name: "Accord de sortie en rente retraite",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Accord formalisant la conversion du capital retraite en rente viagère ou temporaire au profit du bénéficiaire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 56,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom du bénéficiaire à la retraite", type: 'text', required: true },
      { key: 'numero_contrat', label: "Numéro de contrat retraite", type: 'text', required: true },
      { key: 'capital_converti', label: "Capital converti en rente (FCFA)", type: 'text', required: true },
      { key: 'rente_mensuelle', label: "Rente mensuelle résultante (FCFA)", type: 'text', required: true },
      { key: 'type_rente', label: "Type de rente (viagère / temporaire)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE SORTIE EN RENTE RETRAITE</h1><p>Bénéficiaire : <strong>{{assure_nom}}</strong> — Contrat n° <strong>{{numero_contrat}}</strong></p><h2>Article 1 — Conversion</h2><p>Le capital retraite de <strong>{{capital_converti}} FCFA</strong> est converti en une rente de type <strong>{{type_rente}}</strong>.</p><h2>Article 2 — Montant de la rente</h2><p>La rente mensuelle nette versée au bénéficiaire est de <strong>{{rente_mensuelle}} FCFA</strong>.</p><h2>Article 3 — Irréversibilité</h2><p>Le choix de sortie en rente est irrévocable à compter de la signature du présent accord.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_rapport_performance',
    name: "Rapport de performance contrat d'assurance vie",
    category: 'assurance',
    price: 4000,
    priceMax: 12000,
    description: "Rapport annuel de performance remis au souscripteur d'un contrat d'assurance vie, présentant la valorisation et les arbitrages effectués.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 53,
    fieldsJson: F([
      { key: 'souscripteur_nom', label: "Nom du souscripteur", type: 'text', required: true },
      { key: 'numero_contrat', label: "Numéro de contrat", type: 'text', required: true },
      { key: 'valeur_debut_periode', label: "Valeur au début de la période (FCFA)", type: 'text', required: true },
      { key: 'valeur_fin_periode', label: "Valeur en fin de période (FCFA)", type: 'text', required: true },
      { key: 'taux_rendement_realise', label: "Taux de rendement réalisé sur la période (%)", type: 'text', required: true },
      { key: 'observations', label: "Observations et commentaires", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>RAPPORT DE PERFORMANCE — CONTRAT D'ASSURANCE VIE</h1><p>Souscripteur : <strong>{{souscripteur_nom}}</strong> — Contrat n° <strong>{{numero_contrat}}</strong></p><h2>1. Évolution de la valeur</h2><p>Valeur en début de période : <strong>{{valeur_debut_periode}} FCFA</strong><br/>Valeur en fin de période : <strong>{{valeur_fin_periode}} FCFA</strong></p><h2>2. Performance</h2><p>Taux de rendement réalisé : <strong>{{taux_rendement_realise}}%</strong></p><h2>3. Observations</h2><p>{{observations}}</p><h2>4. Avertissement</h2><p>Les performances passées ne préjugent pas des performances futures. Ce rapport est établi conformément aux obligations d'information du Code CIMA.</p><p class="signature">Édité à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_plan_developpement',
    name: "Plan de développement assurance vie",
    category: 'assurance',
    price: 8000,
    priceMax: 24000,
    description: "Document stratégique de planification du développement d'une activité d'assurance vie sur un marché donné de l'espace CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'compagnie_nom', label: "Nom de la compagnie d'assurance", type: 'text', required: true },
      { key: 'marche_cible', label: "Marché cible (pays ou région CIMA)", type: 'text', required: true },
      { key: 'objectif_primes', label: "Objectif de primes collectées à 3 ans (FCFA)", type: 'text', required: true },
      { key: 'axes_developpement', label: "Axes de développement prioritaires", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>PLAN DE DÉVELOPPEMENT ASSURANCE VIE</h1><p>Compagnie : <strong>{{compagnie_nom}}</strong> — Marché cible : <strong>{{marche_cible}}</strong></p><h2>1. Objectif commercial</h2><p>Atteindre <strong>{{objectif_primes}} FCFA</strong> de primes collectées à l'horizon trois (3) ans.</p><h2>2. Axes de développement</h2><p>{{axes_developpement}}</p><h2>3. Cadre réglementaire</h2><p>Ce plan est établi dans le respect des dispositions du Code CIMA relatives aux compagnies d'assurance vie et aux obligations de solvabilité.</p><h2>4. Suivi et révision</h2><p>Le plan fait l'objet d'une revue semestrielle par la direction générale et est soumis au contrôle de la CRCA.</p><p class="signature">Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_accord_distribution_courtier',
    name: "Accord de distribution assurance vie par courtier",
    category: 'assurance',
    price: 7000,
    priceMax: 21000,
    description: "Convention de distribution de produits d'assurance vie entre une compagnie et un courtier agréé, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 54,
    fieldsJson: F([
      { key: 'compagnie_nom', label: "Nom de la compagnie d'assurance", type: 'text', required: true },
      { key: 'courtier_nom', label: "Nom du cabinet de courtage", type: 'text', required: true },
      { key: 'produits_distribues', label: "Produits d'assurance vie distribués", type: 'textarea', required: true },
      { key: 'taux_commission', label: "Taux de commission (%) sur primes acquises", type: 'text', required: true },
      { key: 'territoire', label: "Territoire de distribution", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE DISTRIBUTION ASSURANCE VIE PAR COURTIER</h1><p>Entre <strong>{{compagnie_nom}}</strong> (la compagnie) et <strong>{{courtier_nom}}</strong> (le courtier).</p><h2>Article 1 — Objet</h2><p>La compagnie mandate le courtier pour distribuer les produits d'assurance vie suivants : <strong>{{produits_distribues}}</strong> sur le territoire de <strong>{{territoire}}</strong>.</p><h2>Article 2 — Rémunération</h2><p>Le courtier perçoit une commission de <strong>{{taux_commission}}%</strong> sur les primes acquises nettes de taxes.</p><h2>Article 3 — Obligations du courtier</h2><p>Le courtier s'engage à respecter les règles de bonne conduite édictées par le Code CIMA, à tenir un registre de ses opérations et à communiquer trimestriellement ses statistiques de production à la compagnie.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'avie_charte_conseil',
    name: "Charte de conseil en assurance vie",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Charte définissant les obligations de conseil du distributeur d'assurance vie envers ses clients, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'distributeur_nom', label: "Nom du distributeur (compagnie ou courtier)", type: 'text', required: true },
      { key: 'responsable_conformite', label: "Nom du responsable conformité", type: 'text', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entrée en vigueur de la charte", type: 'date', required: true },
      { key: 'engagements_cles', label: "Engagements clés envers les clients", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE CONSEIL EN ASSURANCE VIE</h1><p>Établie par : <strong>{{distributeur_nom}}</strong> — Responsable conformité : <strong>{{responsable_conformite}}</strong></p><p>En vigueur à compter du : {{date_entree_vigueur}}</p><h2>Article 1 — Principes directeurs</h2><p>Le distributeur s'engage à fournir à chaque client un conseil personnalisé, fondé sur l'analyse de sa situation patrimoniale, de ses besoins et de son appétence au risque.</p><h2>Article 2 — Engagements clés</h2><p>{{engagements_cles}}</p><h2>Article 3 — Documentation</h2><p>Chaque conseil donné fait l'objet d'une fiche de conseil signée par le client, conservée pendant dix (10) ans.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },

  // ─── ASSURANCE IARD / NON-VIE (25 templates) ────────────────────────────────
  {
    code: 'iard_multirisque_habitation',
    name: "Contrat d'assurance multirisque habitation",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Contrat couvrant les dommages au logement et aux biens du souscripteur (incendie, vol, dégât des eaux, RC), conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 82,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'adresse_bien', label: "Adresse du bien assuré", type: 'text', required: true },
      { key: 'valeur_bien', label: "Valeur déclarée du bien (FCFA)", type: 'text', required: true },
      { key: 'garanties_choisies', label: "Garanties souscrites", type: 'textarea', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle TTC (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE MULTIRISQUE HABITATION</h1><p>Assuré : <strong>{{assure_nom}}</strong> — Bien situé à : <strong>{{adresse_bien}}</strong></p><h2>Article 1 — Objet</h2><p>La compagnie garantit les dommages subis par le bien assuré, dont la valeur déclarée est de <strong>{{valeur_bien}} FCFA</strong>.</p><h2>Article 2 — Garanties</h2><p>{{garanties_choisies}}</p><h2>Article 3 — Prime</h2><p>La prime annuelle est de <strong>{{prime_annuelle}} FCFA</strong> TTC, payable à l'échéance annuelle.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_multirisque_commerce',
    name: "Contrat d'assurance multirisque commerce",
    category: 'assurance',
    price: 7000,
    priceMax: 21000,
    description: "Contrat couvrant les risques d'un local commercial (incendie, vol, responsabilité civile exploitation), conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 77,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom / raison sociale de l'assuré", type: 'text', required: true },
      { key: 'adresse_commerce', label: "Adresse du local commercial", type: 'text', required: true },
      { key: 'nature_activite', label: "Nature de l'activité commerciale", type: 'text', required: true },
      { key: 'capitaux_assures', label: "Capitaux assurés (marchandises + mobilier, FCFA)", type: 'text', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle TTC (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE MULTIRISQUE COMMERCE</h1><p>Assuré : <strong>{{assure_nom}}</strong> — Local : <strong>{{adresse_commerce}}</strong></p><h2>Article 1 — Activité</h2><p>L'activité assurée est : <strong>{{nature_activite}}</strong>.</p><h2>Article 2 — Capitaux assurés</h2><p>Les capitaux assurés s'élèvent à <strong>{{capitaux_assures}} FCFA</strong> pour les marchandises et le mobilier.</p><h2>Article 3 — Prime</h2><p>Prime annuelle TTC : <strong>{{prime_annuelle}} FCFA</strong>.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_trc_btp',
    name: "Contrat d'assurance tous risques chantier (TRC BTP)",
    category: 'assurance',
    price: 15000,
    priceMax: 45000,
    description: "Contrat TRC garantissant les dommages matériels survenus pendant la réalisation d'un ouvrage de construction, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 73,
    fieldsJson: F([
      { key: 'maitre_ouvrage_nom', label: "Nom du maître d'ouvrage", type: 'text', required: true },
      { key: 'nature_ouvrage', label: "Nature et description de l'ouvrage", type: 'textarea', required: true },
      { key: 'valeur_ouvrage', label: "Valeur de l'ouvrage (FCFA)", type: 'text', required: true },
      { key: 'duree_chantier', label: "Durée prévisionnelle du chantier (mois)", type: 'text', required: true },
      { key: 'date_ouverture_chantier', label: "Date d'ouverture du chantier", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE TOUS RISQUES CHANTIER (TRC BTP)</h1><p>Maître d'ouvrage : <strong>{{maitre_ouvrage_nom}}</strong></p><h2>Article 1 — Ouvrage assuré</h2><p>{{nature_ouvrage}}</p><h2>Article 2 — Valeur et durée</h2><p>Valeur de l'ouvrage : <strong>{{valeur_ouvrage}} FCFA</strong> — Durée du chantier : <strong>{{duree_chantier}} mois</strong> à compter du {{date_ouverture_chantier}}.</p><h2>Article 3 — Garanties</h2><p>Le contrat couvre tous dommages matériels accidentels à l'ouvrage en cours de réalisation, y compris les dommages aux existants, à l'exclusion des cas visés aux conditions générales.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_rc_decennale',
    name: "Contrat d'assurance responsabilité civile décennale (RC décennale)",
    category: 'assurance',
    price: 12000,
    priceMax: 36000,
    description: "Contrat d'assurance RC décennale obligatoire pour les constructeurs, conforme au Code CIMA et aux lois sur la construction en Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 76,
    fieldsJson: F([
      { key: 'constructeur_nom', label: "Nom / raison sociale du constructeur", type: 'text', required: true },
      { key: 'numero_agrement', label: "Numéro d'agrément professionnel", type: 'text', required: true },
      { key: 'nature_travaux', label: "Nature des travaux de construction", type: 'textarea', required: true },
      { key: 'montant_marche', label: "Montant du marché de travaux (FCFA)", type: 'text', required: true },
      { key: 'date_reception', label: "Date prévisionnelle de réception des travaux", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE RESPONSABILITÉ CIVILE DÉCENNALE</h1><p>Assuré : <strong>{{constructeur_nom}}</strong> — Agrément n° <strong>{{numero_agrement}}</strong></p><h2>Article 1 — Objet</h2><p>La compagnie garantit la responsabilité décennale du constructeur pour les travaux suivants : <strong>{{nature_travaux}}</strong>, d'un montant de <strong>{{montant_marche}} FCFA</strong>.</p><h2>Article 2 — Durée de la garantie</h2><p>La garantie court pendant dix (10) ans à compter de la réception des travaux, prévue le {{date_reception}}.</p><h2>Article 3 — Droit applicable</h2><p>Code CIMA — Loi ivoirienne sur la construction — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_rcp',
    name: "Contrat d'assurance responsabilité civile professionnelle (RCP)",
    category: 'assurance',
    price: 8000,
    priceMax: 24000,
    description: "Contrat couvrant la responsabilité civile d'un professionnel pour les dommages causés à des tiers dans l'exercice de son activité.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 79,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom / raison sociale du professionnel", type: 'text', required: true },
      { key: 'profession_exercee', label: "Profession exercée", type: 'text', required: true },
      { key: 'plafond_garantie', label: "Plafond de garantie par sinistre (FCFA)", type: 'text', required: true },
      { key: 'chiffre_affaires', label: "Chiffre d'affaires annuel déclaré (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE RESPONSABILITÉ CIVILE PROFESSIONNELLE (RCP)</h1><p>Assuré : <strong>{{assure_nom}}</strong> — Profession : <strong>{{profession_exercee}}</strong></p><h2>Article 1 — Garantie</h2><p>La compagnie garantit les conséquences pécuniaires de la responsabilité civile de l'assuré pour les dommages causés à des tiers dans l'exercice de sa profession, dans la limite d'un plafond de <strong>{{plafond_garantie}} FCFA</strong> par sinistre.</p><h2>Article 2 — Assiette de calcul de la prime</h2><p>La prime est calculée sur la base d'un chiffre d'affaires annuel déclaré de <strong>{{chiffre_affaires}} FCFA</strong>.</p><h2>Article 3 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_rc_exploitation',
    name: "Contrat d'assurance responsabilité civile exploitation",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Contrat couvrant la responsabilité civile d'une entreprise pour les dommages causés à des tiers dans le cadre de son exploitation.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 70,
    fieldsJson: F([
      { key: 'entreprise_nom', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'activite_principale', label: "Activité principale de l'entreprise", type: 'text', required: true },
      { key: 'plafond_garantie', label: "Plafond de garantie annuel (FCFA)", type: 'text', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle TTC (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE RESPONSABILITÉ CIVILE EXPLOITATION</h1><p>Assuré : <strong>{{entreprise_nom}}</strong> — Activité : <strong>{{activite_principale}}</strong></p><h2>Article 1 — Garantie</h2><p>La compagnie garantit la responsabilité civile de l'entreprise pour les dommages corporels, matériels et immatériels causés à des tiers au cours de l'exploitation, dans la limite de <strong>{{plafond_garantie}} FCFA</strong> par an.</p><h2>Article 2 — Prime</h2><p>Prime annuelle : <strong>{{prime_annuelle}} FCFA</strong> TTC.</p><h2>Article 3 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_flotte_automobile',
    name: "Contrat d'assurance flotte automobile entreprise",
    category: 'assurance',
    price: 10000,
    priceMax: 30000,
    description: "Contrat d'assurance couvrant l'ensemble des véhicules d'une flotte d'entreprise, conforme au Code CIMA et à la réglementation automobile.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 81,
    fieldsJson: F([
      { key: 'entreprise_nom', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'nombre_vehicules', label: "Nombre de véhicules de la flotte", type: 'text', required: true },
      { key: 'garanties_retenues', label: "Garanties retenues (RC, tous risques, etc.)", type: 'textarea', required: true },
      { key: 'prime_totale_annuelle', label: "Prime totale annuelle de flotte (FCFA)", type: 'text', required: true },
      { key: 'date_effet', label: "Date d'effet du contrat de flotte", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE FLOTTE AUTOMOBILE ENTREPRISE</h1><p>Assuré : <strong>{{entreprise_nom}}</strong> — Flotte de <strong>{{nombre_vehicules}}</strong> véhicules</p><h2>Article 1 — Objet</h2><p>Le présent contrat prend effet le {{date_effet}} et couvre l'ensemble des véhicules de la flotte.</p><h2>Article 2 — Garanties</h2><p>{{garanties_retenues}}</p><h2>Article 3 — Prime de flotte</h2><p>Prime totale annuelle : <strong>{{prime_totale_annuelle}} FCFA</strong>. Un relevé d'information de flotte est établi à chaque échéance.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Code de la route — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_amt',
    name: "Contrat d'assurance marchandises transportées (AMT)",
    category: 'assurance',
    price: 7000,
    priceMax: 21000,
    description: "Contrat couvrant les marchandises contre les risques de transport terrestre, maritime ou aérien dans l'espace OHADA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom / raison sociale de l'assuré", type: 'text', required: true },
      { key: 'nature_marchandises', label: "Nature des marchandises assurées", type: 'textarea', required: true },
      { key: 'valeur_marchandises', label: "Valeur assurée des marchandises (FCFA)", type: 'text', required: true },
      { key: 'trajet', label: "Trajet couvert (origine et destination)", type: 'text', required: true },
      { key: 'mode_transport', label: "Mode de transport (terrestre/maritime/aérien)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE MARCHANDISES TRANSPORTÉES (AMT)</h1><p>Assuré : <strong>{{assure_nom}}</strong></p><h2>Article 1 — Marchandises assurées</h2><p>{{nature_marchandises}}</p><h2>Article 2 — Valeur et trajet</h2><p>Valeur assurée : <strong>{{valeur_marchandises}} FCFA</strong> — Trajet : <strong>{{trajet}}</strong> par voie <strong>{{mode_transport}}</strong>.</p><h2>Article 3 — Garanties</h2><p>Le contrat couvre les pertes et dommages aux marchandises résultant d'accidents de transport, d'incendie, de vol avec effraction et des périls maritimes le cas échéant.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Convention de Montréal (aérien) — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_corps_navire',
    name: "Contrat d'assurance corps de navire",
    category: 'assurance',
    price: 15000,
    priceMax: 45000,
    description: "Contrat d'assurance couvrant les dommages subis par le navire (coque, machines, équipements), conforme au Code CIMA et aux conventions maritimes.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'armateur_nom', label: "Nom de l'armateur / propriétaire", type: 'text', required: true },
      { key: 'nom_navire', label: "Nom et type du navire", type: 'text', required: true },
      { key: 'valeur_assurance', label: "Valeur agréée du navire (FCFA)", type: 'text', required: true },
      { key: 'zones_navigation', label: "Zones de navigation autorisées", type: 'textarea', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE CORPS DE NAVIRE</h1><p>Armateur : <strong>{{armateur_nom}}</strong> — Navire : <strong>{{nom_navire}}</strong></p><h2>Article 1 — Valeur agréée</h2><p>La valeur agréée du navire est fixée à <strong>{{valeur_assurance}} FCFA</strong>.</p><h2>Article 2 — Zones de navigation</h2><p>{{zones_navigation}}</p><h2>Article 3 — Garanties</h2><p>Le contrat couvre les avaries particulières, les avaries communes, le recours des tiers, la responsabilité civile à l'égard des tiers et les frais de sauvetage.</p><h2>Article 4 — Prime</h2><p>Prime annuelle : <strong>{{prime_annuelle}} FCFA</strong>.</p><h2>Article 5 — Droit applicable</h2><p>Code CIMA — Loi ivoirienne sur le droit maritime — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_aviation_casco',
    name: "Contrat d'assurance aviation (casco)",
    category: 'assurance',
    price: 20000,
    priceMax: 60000,
    description: "Contrat d'assurance couvrant les dommages à la cellule d'un aéronef, conforme au Code CIMA et aux conventions de Chicago.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 45,
    fieldsJson: F([
      { key: 'proprietaire_nom', label: "Nom du propriétaire de l'aéronef", type: 'text', required: true },
      { key: 'immatriculation', label: "Immatriculation de l'aéronef", type: 'text', required: true },
      { key: 'valeur_assurance', label: "Valeur agréée de l'aéronef (FCFA)", type: 'text', required: true },
      { key: 'zone_exploitation', label: "Zone d'exploitation (nationale / régionale UEMOA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE AVIATION — CASCO</h1><p>Propriétaire : <strong>{{proprietaire_nom}}</strong> — Aéronef : <strong>{{immatriculation}}</strong></p><h2>Article 1 — Valeur assurée</h2><p>La valeur agréée de l'aéronef est fixée à <strong>{{valeur_assurance}} FCFA</strong>.</p><h2>Article 2 — Zone d'exploitation</h2><p><strong>{{zone_exploitation}}</strong></p><h2>Article 3 — Garanties casco</h2><p>Le contrat couvre les dommages accidentels à la cellule, aux moteurs et aux équipements de bord, survenant en vol, au sol ou lors des opérations d'embarquement et de débarquement.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Convention de Chicago — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_bris_machine',
    name: "Contrat d'assurance bris de machine",
    category: 'assurance',
    price: 9000,
    priceMax: 27000,
    description: "Contrat couvrant les dommages accidentels aux machines et équipements industriels, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 66,
    fieldsJson: F([
      { key: 'entreprise_nom', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'description_machines', label: "Description des machines assurées", type: 'textarea', required: true },
      { key: 'valeur_neuf', label: "Valeur à neuf des machines (FCFA)", type: 'text', required: true },
      { key: 'prime_annuelle', label: "Prime annuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE BRIS DE MACHINE</h1><p>Assuré : <strong>{{entreprise_nom}}</strong></p><h2>Article 1 — Machines assurées</h2><p>{{description_machines}}</p><h2>Article 2 — Valeur assurée</h2><p>Valeur à neuf des machines : <strong>{{valeur_neuf}} FCFA</strong>. L'indemnisation est effectuée sur la base de la valeur vénale au jour du sinistre.</p><h2>Article 3 — Prime</h2><p>Prime annuelle : <strong>{{prime_annuelle}} FCFA</strong>.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_pertes_exploitation',
    name: "Contrat d'assurance pertes d'exploitation après sinistre",
    category: 'assurance',
    price: 10000,
    priceMax: 30000,
    description: "Contrat garantissant la perte de marge brute consécutive à un sinistre immobilisant l'outil de production, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 68,
    fieldsJson: F([
      { key: 'entreprise_nom', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'marge_brute_annuelle', label: "Marge brute annuelle assurée (FCFA)", type: 'text', required: true },
      { key: 'periode_indemnisation', label: "Période maximale d'indemnisation (mois)", type: 'text', required: true },
      { key: 'franchise_jours', label: "Franchise en jours", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE PERTES D'EXPLOITATION APRÈS SINISTRE</h1><p>Assuré : <strong>{{entreprise_nom}}</strong></p><h2>Article 1 — Garantie</h2><p>La compagnie garantit la perte de marge brute résultant d'une interruption ou d'une réduction d'activité consécutive à un sinistre garanti par le contrat dommages de l'entreprise.</p><h2>Article 2 — Montant assuré</h2><p>Marge brute annuelle assurée : <strong>{{marge_brute_annuelle}} FCFA</strong> — Période maximale d'indemnisation : <strong>{{periode_indemnisation}} mois</strong>.</p><h2>Article 3 — Franchise</h2><p>Une franchise de <strong>{{franchise_jours}} jours</strong> s'applique à chaque sinistre.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_credit_domestique',
    name: "Contrat d'assurance crédit domestique",
    category: 'assurance',
    price: 8000,
    priceMax: 24000,
    description: "Contrat garantissant le risque d'insolvabilité des acheteurs résidant en Côte d'Ivoire, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 60,
    fieldsJson: F([
      { key: 'vendeur_nom', label: "Raison sociale du vendeur (assuré)", type: 'text', required: true },
      { key: 'encours_assure', label: "Encours maximum assuré (FCFA)", type: 'text', required: true },
      { key: 'taux_couverture', label: "Taux de couverture des pertes (%)", type: 'text', required: true },
      { key: 'delai_carence', label: "Délai de carence (jours) avant indemnisation", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE CRÉDIT DOMESTIQUE</h1><p>Assuré (vendeur) : <strong>{{vendeur_nom}}</strong></p><h2>Article 1 — Objet</h2><p>La compagnie garantit l'assuré contre le risque de non-paiement de ses clients résidant en Côte d'Ivoire, pour un encours maximal assuré de <strong>{{encours_assure}} FCFA</strong>.</p><h2>Article 2 — Taux de couverture</h2><p>La compagnie prend en charge <strong>{{taux_couverture}}%</strong> des pertes nettes définitives.</p><h2>Article 3 — Délai de carence</h2><p>L'indemnisation intervient après un délai de carence de <strong>{{delai_carence}} jours</strong> suivant la déclaration de sinistre.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_credit_export',
    name: "Contrat d'assurance crédit export",
    category: 'assurance',
    price: 10000,
    priceMax: 30000,
    description: "Contrat garantissant le risque de non-paiement par des acheteurs étrangers suite à des exportations depuis la Côte d'Ivoire.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 58,
    fieldsJson: F([
      { key: 'exportateur_nom', label: "Raison sociale de l'exportateur", type: 'text', required: true },
      { key: 'pays_acheteurs', label: "Pays des acheteurs couverts", type: 'text', required: true },
      { key: 'encours_assure', label: "Encours maximum assuré (FCFA)", type: 'text', required: true },
      { key: 'taux_couverture', label: "Taux de couverture (%)", type: 'text', required: true },
      { key: 'police_duree', label: "Durée de la police (mois)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE CRÉDIT EXPORT</h1><p>Exportateur assuré : <strong>{{exportateur_nom}}</strong></p><h2>Article 1 — Couverture géographique</h2><p>Pays des acheteurs couverts : <strong>{{pays_acheteurs}}</strong></p><h2>Article 2 — Encours et couverture</h2><p>Encours maximum assuré : <strong>{{encours_assure}} FCFA</strong> — Taux de couverture : <strong>{{taux_couverture}}%</strong>.</p><h2>Article 3 — Durée</h2><p>La police est conclue pour une durée de <strong>{{police_duree}} mois</strong>.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Règles OCDE sur les crédits export — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_caution_marche_public',
    name: "Contrat d'assurance caution (marché public)",
    category: 'assurance',
    price: 8000,
    priceMax: 24000,
    description: "Contrat de cautionnement émis par une compagnie d'assurance au profit d'un maître d'ouvrage public, conforme au Code CIMA et au Code des marchés publics.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 74,
    fieldsJson: F([
      { key: 'entreprise_cautionnee', label: "Raison sociale de l'entreprise cautionnée", type: 'text', required: true },
      { key: 'maitre_ouvrage', label: "Maître d'ouvrage bénéficiaire", type: 'text', required: true },
      { key: 'objet_marche', label: "Objet du marché public garanti", type: 'textarea', required: true },
      { key: 'montant_caution', label: "Montant de la caution (FCFA)", type: 'text', required: true },
      { key: 'type_caution', label: "Type de caution (soumission / bonne exécution / retenue)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE CAUTION — MARCHÉ PUBLIC</h1><p>Entreprise cautionnée : <strong>{{entreprise_cautionnee}}</strong> — Maître d'ouvrage : <strong>{{maitre_ouvrage}}</strong></p><h2>Article 1 — Marché garanti</h2><p>{{objet_marche}}</p><h2>Article 2 — Caution</h2><p>Type de caution : <strong>{{type_caution}}</strong> — Montant : <strong>{{montant_caution}} FCFA</strong>.</p><h2>Article 3 — Appel en garantie</h2><p>Le maître d'ouvrage peut appeler la caution par simple demande écrite en cas de défaillance de l'entreprise cautionnée, sans que la compagnie puisse opposer le bénéfice de discussion ou de division.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Code des marchés publics — OHADA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_agricole_recolte',
    name: "Contrat d'assurance agricole récolte",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Contrat couvrant les pertes de récolte causées par des aléas climatiques ou des ravageurs, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 62,
    fieldsJson: F([
      { key: 'agriculteur_nom', label: "Nom de l'agriculteur / exploitant", type: 'text', required: true },
      { key: 'culture_assuree', label: "Culture(s) assurée(s)", type: 'text', required: true },
      { key: 'superficie_ha', label: "Superficie assurée (hectares)", type: 'text', required: true },
      { key: 'rendement_garanti', label: "Rendement garanti (tonnes/ha)", type: 'text', required: true },
      { key: 'prix_referentiel', label: "Prix de référence de la culture (FCFA/tonne)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE AGRICOLE RÉCOLTE</h1><p>Exploitant assuré : <strong>{{agriculteur_nom}}</strong></p><h2>Article 1 — Objet</h2><p>Culture(s) assurée(s) : <strong>{{culture_assuree}}</strong> — Superficie : <strong>{{superficie_ha}} ha</strong>.</p><h2>Article 2 — Garantie</h2><p>La compagnie indemnise toute perte de récolte résultant d'une sécheresse, d'inondations, d'attaques de ravageurs ou d'autres aléas climatiques reconnus, dès lors que le rendement réel est inférieur au rendement garanti de <strong>{{rendement_garanti}} t/ha</strong>.</p><h2>Article 3 — Prix de référence</h2><p>L'indemnisation est calculée sur la base du prix de référence de <strong>{{prix_referentiel}} FCFA/tonne</strong>.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_parametrique_secheresse',
    name: "Contrat d'assurance paramétrique sécheresse",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Contrat d'assurance indicielle déclenchée par un indice de sécheresse (pluviométrie) mesuré à une station de référence.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 55,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré (agriculteur / coopérative)", type: 'text', required: true },
      { key: 'station_reference', label: "Station météorologique de référence", type: 'text', required: true },
      { key: 'seuil_declenchement_mm', label: "Seuil de déclenchement (mm de pluie)", type: 'text', required: true },
      { key: 'indemnite_max', label: "Indemnité maximale par hectare (FCFA)", type: 'text', required: true },
      { key: 'periode_mesure', label: "Période de mesure (du ... au ...)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE PARAMÉTRIQUE SÉCHERESSE</h1><p>Assuré : <strong>{{assure_nom}}</strong></p><h2>Article 1 — Indice de référence</h2><p>Le contrat est basé sur la pluviométrie mesurée à la station <strong>{{station_reference}}</strong> pendant la période <strong>{{periode_mesure}}</strong>.</p><h2>Article 2 — Déclenchement</h2><p>L'indemnisation est déclenchée automatiquement si la pluviométrie cumulée sur la période de référence est inférieure à <strong>{{seuil_declenchement_mm}} mm</strong>.</p><h2>Article 3 — Indemnité</h2><p>L'indemnité maximale est de <strong>{{indemnite_max}} FCFA/ha</strong>, versée dans les trente (30) jours suivant la fin de la période de mesure.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_sante_individuelle',
    name: "Contrat d'assurance santé individuelle",
    category: 'assurance',
    price: 5000,
    priceMax: 15000,
    description: "Contrat d'assurance maladie et hospitalisation individuelle couvrant les frais médicaux, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 84,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'date_naissance', label: "Date de naissance de l'assuré", type: 'date', required: true },
      { key: 'plafond_remboursement', label: "Plafond annuel de remboursement (FCFA)", type: 'text', required: true },
      { key: 'taux_remboursement', label: "Taux de remboursement des frais médicaux (%)", type: 'text', required: true },
      { key: 'prime_mensuelle', label: "Prime mensuelle (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE SANTÉ INDIVIDUELLE</h1><p>Assuré : <strong>{{assure_nom}}</strong>, né(e) le {{date_naissance}}</p><h2>Article 1 — Garanties</h2><p>Le contrat rembourse les frais médicaux, pharmaceutiques et d'hospitalisation à hauteur de <strong>{{taux_remboursement}}%</strong>, dans la limite d'un plafond annuel de <strong>{{plafond_remboursement}} FCFA</strong>.</p><h2>Article 2 — Prime</h2><p>Prime mensuelle : <strong>{{prime_mensuelle}} FCFA</strong>.</p><h2>Article 3 — Réseau de soins</h2><p>L'assuré bénéficie du réseau de soins agréé par la compagnie sur l'ensemble du territoire ivoirien.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_sante_collective',
    name: "Contrat d'assurance santé collective entreprise",
    category: 'assurance',
    price: 10000,
    priceMax: 30000,
    description: "Contrat collectif de complémentaire santé souscrit par une entreprise pour ses salariés, conforme au Code CIMA et au Code du travail ivoirien.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 85,
    fieldsJson: F([
      { key: 'entreprise_nom', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'nombre_salaries', label: "Nombre de salariés couverts", type: 'text', required: true },
      { key: 'niveau_garantie', label: "Niveau de garantie souscrit (base / confort / premium)", type: 'text', required: true },
      { key: 'cotisation_mensuelle', label: "Cotisation mensuelle globale (FCFA)", type: 'text', required: true },
      { key: 'part_employeur_pct', label: "Part employeur (%)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE SANTÉ COLLECTIVE ENTREPRISE</h1><p>Entreprise : <strong>{{entreprise_nom}}</strong> — Effectif couvert : <strong>{{nombre_salaries}}</strong> salariés</p><h2>Article 1 — Garanties</h2><p>Niveau de garantie : <strong>{{niveau_garantie}}</strong>. Les prestations détaillées figurent au tableau de garanties annexé.</p><h2>Article 2 — Cotisations</h2><p>Cotisation mensuelle globale : <strong>{{cotisation_mensuelle}} FCFA</strong> — Part employeur : <strong>{{part_employeur_pct}}%</strong>.</p><h2>Article 3 — Caractère obligatoire</h2><p>L'adhésion est obligatoire pour l'ensemble des salariés et de leurs ayants droit tels que définis aux conditions particulières.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Code du travail ivoirien — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_voyage_rapatriement',
    name: "Contrat d'assurance voyage et assistance rapatriement",
    category: 'assurance',
    price: 3000,
    priceMax: 9000,
    description: "Contrat couvrant les frais médicaux, l'annulation et le rapatriement lors de voyages à l'international.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 72,
    fieldsJson: F([
      { key: 'voyageur_nom', label: "Nom du voyageur assuré", type: 'text', required: true },
      { key: 'destination', label: "Pays de destination", type: 'text', required: true },
      { key: 'date_depart', label: "Date de départ", type: 'date', required: true },
      { key: 'date_retour', label: "Date de retour prévue", type: 'date', required: true },
      { key: 'plafond_frais_medicaux', label: "Plafond frais médicaux (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>CONTRAT D'ASSURANCE VOYAGE ET ASSISTANCE RAPATRIEMENT</h1><p>Assuré : <strong>{{voyageur_nom}}</strong> — Destination : <strong>{{destination}}</strong></p><h2>Article 1 — Période de garantie</h2><p>Du <strong>{{date_depart}}</strong> au <strong>{{date_retour}}</strong>.</p><h2>Article 2 — Garanties</h2><p>Frais médicaux à l'étranger : plafond de <strong>{{plafond_frais_medicaux}} FCFA</strong> — Rapatriement médical illimité — Annulation de voyage jusqu'à 100% des frais engagés.</p><h2>Article 3 — Assistance 24h/24</h2><p>Une plateforme d'assistance médicale est disponible vingt-quatre heures sur vingt-quatre, sept jours sur sept.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_reglement_amiable_sinistre',
    name: "Accord de règlement amiable de sinistre IARD",
    category: 'assurance',
    price: 4000,
    priceMax: 12000,
    description: "Protocole d'accord transactionnel entre la compagnie d'assurance et l'assuré pour régler un sinistre IARD à l'amiable.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 69,
    fieldsJson: F([
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'numero_sinistre', label: "Numéro de sinistre", type: 'text', required: true },
      { key: 'description_sinistre', label: "Description du sinistre", type: 'textarea', required: true },
      { key: 'indemnite_proposee', label: "Indemnité proposée et acceptée (FCFA)", type: 'text', required: true },
      { key: 'date_versement', label: "Date de versement de l'indemnité", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE RÈGLEMENT AMIABLE DE SINISTRE IARD</h1><p>Assuré : <strong>{{assure_nom}}</strong> — Sinistre n° <strong>{{numero_sinistre}}</strong></p><h2>Article 1 — Faits</h2><p>{{description_sinistre}}</p><h2>Article 2 — Transaction</h2><p>En règlement définitif et irrévocable du sinistre susvisé, la compagnie versera à l'assuré la somme de <strong>{{indemnite_proposee}} FCFA</strong> le {{date_versement}}.</p><h2>Article 3 — Renonciation</h2><p>L'acceptation de cette indemnité vaut renonciation de l'assuré à tout recours ultérieur relatif à ce sinistre, y compris devant les juridictions compétentes.</p><h2>Article 4 — Droit applicable</h2><p>Code CIMA — Code civil ivoirien — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_rapport_expertise_sinistre',
    name: "Rapport d'expertise sinistre IARD",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Rapport d'expertise établi par un expert mandaté pour évaluer les dommages consécutifs à un sinistre IARD, conforme aux pratiques CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 65,
    fieldsJson: F([
      { key: 'expert_nom', label: "Nom et qualité de l'expert mandaté", type: 'text', required: true },
      { key: 'assure_nom', label: "Nom de l'assuré", type: 'text', required: true },
      { key: 'date_sinistre', label: "Date du sinistre", type: 'date', required: true },
      { key: 'nature_dommages', label: "Nature et description des dommages constatés", type: 'textarea', required: true },
      { key: 'montant_evalue', label: "Montant des dommages évalués (FCFA)", type: 'text', required: true },
      { key: 'conclusions', label: "Conclusions et recommandations de l'expert", type: 'textarea', required: true },
    ]),
    body: `<div class="doc"><h1>RAPPORT D'EXPERTISE SINISTRE IARD</h1><p>Expert : <strong>{{expert_nom}}</strong> — Assuré : <strong>{{assure_nom}}</strong> — Sinistre du {{date_sinistre}}</p><h2>1. Constat des dommages</h2><p>{{nature_dommages}}</p><h2>2. Évaluation</h2><p>Montant total des dommages évalués : <strong>{{montant_evalue}} FCFA</strong>.</p><h2>3. Conclusions</h2><p>{{conclusions}}</p><h2>4. Réserves</h2><p>Le présent rapport est établi contradictoirement et sous réserve de prise en compte des éléments complémentaires qui pourraient être portés à la connaissance de l'expert.</p><p class="signature">Établi à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_plan_gestion_risques',
    name: "Plan de gestion des risques IARD entreprise",
    category: 'assurance',
    price: 12000,
    priceMax: 36000,
    description: "Document de cartographie et de gestion des risques IARD d'une entreprise, servant de base au programme d'assurance.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 57,
    fieldsJson: F([
      { key: 'entreprise_nom', label: "Raison sociale de l'entreprise", type: 'text', required: true },
      { key: 'responsable_risques', label: "Nom du responsable gestion des risques", type: 'text', required: true },
      { key: 'risques_identifies', label: "Principaux risques IARD identifiés", type: 'textarea', required: true },
      { key: 'mesures_prevention', label: "Mesures de prévention et de mitigation", type: 'textarea', required: true },
      { key: 'programme_assurance', label: "Programme d'assurance retenu", type: 'textarea', required: false },
    ]),
    body: `<div class="doc"><h1>PLAN DE GESTION DES RISQUES IARD — ENTREPRISE</h1><p>Entreprise : <strong>{{entreprise_nom}}</strong> — Responsable risques : <strong>{{responsable_risques}}</strong></p><h2>1. Cartographie des risques</h2><p>{{risques_identifies}}</p><h2>2. Mesures de prévention</h2><p>{{mesures_prevention}}</p><h2>3. Programme d'assurance</h2><p>{{programme_assurance}}</p><h2>4. Révision</h2><p>Ce plan est révisé annuellement et après tout sinistre significatif. Il est communiqué à la compagnie d'assurance et au courtier mandaté.</p><p class="signature">Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_coassurance',
    name: "Accord de coassurance (partage de risque)",
    category: 'assurance',
    price: 10000,
    priceMax: 30000,
    description: "Convention de coassurance entre plusieurs compagnies pour partager un risque IARD de grande taille, conforme au Code CIMA.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 50,
    fieldsJson: F([
      { key: 'apériteur_nom', label: "Nom de la compagnie apéritrice", type: 'text', required: true },
      { key: 'coassureurs', label: "Liste des coassureurs et leurs quotes-parts (%)", type: 'textarea', required: true },
      { key: 'risque_assure', label: "Description du risque assuré en coassurance", type: 'textarea', required: true },
      { key: 'capital_total', label: "Capital total assuré (FCFA)", type: 'text', required: true },
    ]),
    body: `<div class="doc"><h1>ACCORD DE COASSURANCE — PARTAGE DE RISQUE</h1><p>Apériteur : <strong>{{apériteur_nom}}</strong></p><h2>Article 1 — Risque couvert</h2><p>{{risque_assure}}</p><h2>Article 2 — Capital assuré</h2><p>Capital total assuré : <strong>{{capital_total}} FCFA</strong></p><h2>Article 3 — Quotes-parts</h2><p>{{coassureurs}}</p><h2>Article 4 — Rôle de l'apériteur</h2><p>L'apériteur assure la gestion administrative et technique du contrat pour le compte de l'ensemble des coassureurs. Les sinistres sont réglés par chaque coassureur à hauteur de sa quote-part.</p><h2>Article 5 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
  {
    code: 'iard_charte_souscription_responsable',
    name: "Charte de souscription IARD responsable",
    category: 'assurance',
    price: 6000,
    priceMax: 18000,
    description: "Charte interne définissant les critères de souscription ESG (environnement, social, gouvernance) d'une compagnie d'assurance IARD.",
    templateType: 'pdf',
    classe: 'B',
    active: true,
    popularity: 48,
    fieldsJson: F([
      { key: 'compagnie_nom', label: "Nom de la compagnie d'assurance", type: 'text', required: true },
      { key: 'directeur_technique', label: "Nom du directeur technique", type: 'text', required: true },
      { key: 'secteurs_exclus', label: "Secteurs exclus de la souscription (ESG)", type: 'textarea', required: true },
      { key: 'criteres_esg', label: "Critères ESG retenus pour la souscription", type: 'textarea', required: true },
      { key: 'date_entree_vigueur', label: "Date d'entrée en vigueur", type: 'date', required: true },
    ]),
    body: `<div class="doc"><h1>CHARTE DE SOUSCRIPTION IARD RESPONSABLE</h1><p>Compagnie : <strong>{{compagnie_nom}}</strong> — Direction technique : <strong>{{directeur_technique}}</strong></p><p>En vigueur à compter du : {{date_entree_vigueur}}</p><h2>Article 1 — Engagement responsable</h2><p>La compagnie s'engage à intégrer les critères ESG dans sa politique de souscription IARD, conformément aux Principes pour une Assurance Durable (PSI) de l'UNEP FI.</p><h2>Article 2 — Secteurs exclus</h2><p>{{secteurs_exclus}}</p><h2>Article 3 — Critères ESG de souscription</h2><p>{{criteres_esg}}</p><h2>Article 4 — Gouvernance</h2><p>Le comité de souscription veille à l'application de la présente charte et publie un rapport annuel de souscription responsable.</p><h2>Article 5 — Droit applicable</h2><p>Code CIMA — Côte d'Ivoire.</p><p class="signature">Fait à Abidjan, le {{date_signature}}</p></div>`,
  },
];

async function main() {
  let created = 0, updated = 0;
  for (const t of templates) {
    const ex = await prisma.documentTemplate.findUnique({ where: { code: t.code } });
    await prisma.documentTemplate.upsert({ where: { code: t.code }, update: t, create: t });
    if (ex) updated++; else created++;
  }
  const total = await prisma.documentTemplate.count();
  console.log(`Batch 65a OK — créés:${created} maj:${updated} TOTAL:${total}`);
}

main().catch(e => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
